- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/_contents-list.scss
- app/views/govuk_publishing_components/components/_contents_list.html.erb
- app/views/govuk_publishing_components/components/docs/contents_list.yml
- lib/govuk_publishing_components/presenters/contents_list_helper.rb
- spec/components/contents_list_spec.rb
- spec/lib/govuk_publishing_components/components/contents_list_helper_spec.rb
First commit: refactors the contents list component to move more logic out of the view and into the helper. This makes it easier for us to add another option to the component in the second commit.
Second commit: Adds an option to the component to set a font-size other than the default 16px.
On the new [Brexit landing page](https://www.gov.uk/brexit), we want the contents list to match the font-size of the surrounding text, which is 19px. At the moment, we are overriding the `gem-c-contents-list__link` class within Collections, which isn't ideal. This adds the option to the component itself, so we can remove the override.
https://govuk-publishing-compo-pr-1112.herokuapp.com/component-guide/contents_list
> Refactor contents list component

- CHANGELOG.md
- app/views/govuk_publishing_components/components/_lead_paragraph.html.erb
- app/views/govuk_publishing_components/components/docs/lead_paragraph.yml
- spec/components/lead_paragraph_spec.rb
Add a margin_bottom option to the lead paragraph component. 
We may sometimes want the margin bottom on the component to be different to the default 45px. Specifically, this change is being made now for the Brexit landing page.
https://govuk-publishing-compo-pr-1114.herokuapp.com/component-guide/lead_paragraph
> Add margin bottom option to lead para

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
Includes:
* Add font-size option to contents list component ([PR #1112](https://github.com/alphagov/govuk_publishing_components/pull/1112))
* Add margin-bottom option to lead paragraph component ([PR #1114](https://github.com/alphagov/govuk_publishing_components/pull/1114))
> Version 20.5.0

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/_chevron-banner.scss
Adjusts the IE-specific CSS for the chevron banner so that it displays without a left-side gap on the chevron:
We adjusted the layout for the chevron banner, but forgot to adjust the IE-specific CSS to match.
https://govuk-publishing-compo-pr-1116.herokuapp.com/
> Fix IE specific CSS

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
Includes:
* Fix IE-specific CSS for chevron banner ([PR #1116](https://github.com/alphagov/govuk_publishing_components/pull/1116))
> Version 20.5.1

- CHANGELOG.md
Fix changelog heading for version 20.5.0. Replacing a non-standard spacing character with the standard one.
Because it doesn't allow the heading to be rendered correctly
> Fix changelog heading for v 20.5.0

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/_step-by-step-nav.scss
Fix the focus state of navigation button when a step-by-step header is hovered. Fixes #1058
Because it doesn't meet the required contrast ratio.
Before
After
https://govuk-publishing-compo-pr-1119.herokuapp.com/component-guide/step_by_step_nav
> Fix focus state on step by step nav when header element is hovered

- CHANGELOG.md
- package-lock.json
- package.json
Update `govuk_publishing_components` to use [`govuk-frontend` version 3.2.0.](https://github.com/alphagov/govuk-frontend/releases/tag/v3.2.0)
Keep frontend code in sync with the Design System updates
For more details regarding changes see [govuk-frontend 3.2.0 changelog](https://github.com/alphagov/govuk-frontend/releases/tag/v3.2.0)
https://govuk-publishing-compo-pr-1113.herokuapp.com/
> Bump govuk-frontend to 3.2.0

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
Includes:
* Update to [govuk-frontend to 3.2.0](https://github.com/alphagov/govuk-frontend/releases/tag/v3.2.0) ([PR #1113](https://github.com/alphagov/govuk_publishing_components/pull/1113))
* Fix focus state on step by step nav when header element is hovered [PR #1119](https://github.com/alphagov/govuk_publishing_components/pull/1119)
> Bump to version 20.5.2

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
This is a breaking change for guides in government-frontend.  The FAQ schema is not used anywhere else yet.
> Bump to 21.0.0

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/_search.scss
- Updates border colour and style to match inputs
- Updates focus states to match inputs
- Updates label colour when label is set to be outside in input or when javascript is disabled so it matches label component colour
- general reordering and consolidation of styles
To update to latest styles, matching other components.
Fixes #1027
<details>
<summary>Default states before and after</summary>
**Before:**
**After:**
</details>
<details>
<summary>Focus states before and after</summary>
**Before:**
**After:**
</details>
https://govuk-publishing-compo-pr-1128.herokuapp.com/component-guide/search
an additional option is to completely modernise it and use an inline svg for the icon and add aria-label="Search" on the button to describe it.
Fallback for SVG would be an `image` tag within, like …
> Update search component styles

- CHANGELOG.md
- app/views/govuk_publishing_components/components/_select.html.erb
- app/views/govuk_publishing_components/components/docs/select.yml
- spec/components/select_spec.rb
Adds an option to the select component to add a 'name' attribute that is different from the 'id' attribute. If none is passed, 'name' defaults to 'id' (as before this change was made).
Smart answers is being converted to use components and the selects for dates have differing 'id' and 'name' attributes.
https://govuk-publishing-compo-pr-1130.herokuapp.com/component-guide/select
> Add name option to select component

- CHANGELOG.md
- app/views/govuk_publishing_components/components/_select.html.erb
- app/views/govuk_publishing_components/components/docs/select.yml
- spec/components/select_spec.rb
Adds an option to the select component to give it a custom-sized label. Component defaults to the existing label style unless specified.
Smart answers needs this - the question text for a select is currently smaller and not-bold compared to all the other component labels.
https://govuk-publishing-compo-pr-1131.herokuapp.com/component-guide/select
> Add label size option for select

- CHANGELOG.md
- app/views/govuk_publishing_components/components/_cookie_banner.html.erb
- spec/components/cookie_banner_spec.rb
- spec/javascripts/components/cookie-banner-spec.js
This commit updates the cookie banner text to reflect our use of cookies and analytics on GOV.UK
Note: the spacing looks wrong in the screenshots because this is how the cookie banner renders in the component guide. Left and right spacing is visible on the live site.
> Update cookie banner text

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
Includes:
* Update cookie banner text ([PR #1136](https://github.com/alphagov/govuk_publishing_components/pull/1136))
> Version 21.1.1

- app/assets/stylesheets/govuk_publishing_components/components/_feedback.scss
Sets the feedback component to be `position: relative` so sticky or fixed elements that precede the feedback component don't overlap it; and sets the feedback element container's background to be white to stop any underlapping elements from showing through.
A sticky or fixed element was overlapping the feedback component on Service Manual Frontend and this would fix it.
Problem can be seen on the [Agile and government services: an introduction](https://www.gov.uk/service-manual/agile-delivery/agile-government-services-introduction) page in the Service Manual. Scroll to the feedback component and open either one of the feedback forms by clicking 'No' or 'Is there anything wrong with this page?'. Once the feedback form has opened, scroll to the bottom of the page to see the sticky menu will …
> Prevent sticky / fixed elements from overlapping feedback component

- CHANGELOG.md
- app/views/govuk_publishing_components/components/_fieldset.html.erb
- app/views/govuk_publishing_components/components/_select.html.erb
- app/views/govuk_publishing_components/components/docs/fieldset.yml
- spec/components/fieldset_spec.rb
Adds a custom legend size option to the fieldset component. Defaults to original size before change.
Also fixes a small bug with the same functionality in the select component.
Needed for visual consistency in smart-answers.
https://govuk-publishing-compo-pr-1134.herokuapp.com/component-guide/fieldset
> Fieldset legend custom size

- app/views/govuk_publishing_components/components/docs/input.yml
Input component documentation includes a `href` attribute, but this is unused, so removing.
Because!
None.
https://govuk-publishing-compo-pr-1139.herokuapp.com/component-guide/input/with_error_items
> Correcting input error documentation

- CHANGELOG.md
- app/views/govuk_publishing_components/components/_select.html.erb
- app/views/govuk_publishing_components/components/docs/select.yml
- spec/components/select_spec.rb
Add an error state to the select component. This [already exists](http://govuk-frontend-review.herokuapp.com/components/select/with-hint-text-and-error-message/preview) in `govuk-frontend`, but isn't documented.
For the [smart-answers upgrade](https://github.com/alphagov/smart-answers/pull/4132). I can't be certain there isn't a select question that doesn't have a blank answer, so we need an error message.
> Add error state to select component

- CHANGELOG.md
- app/views/govuk_publishing_components/components/_input.html.erb
- app/views/govuk_publishing_components/components/_label.html.erb
- app/views/govuk_publishing_components/components/docs/input.yml
- app/views/govuk_publishing_components/components/docs/label.yml
- spec/components/input_spec.rb
- spec/components/label_spec.rb
Use the govuk-frontend classes for labels to provide a size option for labels, and use this in the label component and the input component.
This is needed for the upgrade of [smart-answers to use components](https://github.com/alphagov/smart-answers/pull/4132) where we want a consistent, large and bold style for labels. Other components already have this.
There are potentially some additional bits of work to come out of this...
- could this be done using the shared helper?
- some components kind of already do this, but use a `bold` flag to set `govuk-label--s`. We should remove this in favour of the more flexible `heading_size` option. Components are radio and label.
- the component uses the option `heading_size` for the label style, but this is also used by the radio component to set the …
> Add size option to label

- CHANGELOG.md
- lib/govuk_publishing_components/presenters/machine_readable/faq_page_schema.rb
- spec/lib/govuk_publishing_components/presenters/schema_org_spec.rb
FAQPage schemas are used to help us get rich results on Google for queries like https://www.google.com/search?q=apply+for+uk+visa
FAQPages have lists of question and answer pairs.  We generate "questions" from h2 tag text, and the "answers" are the html content that follows (until the next h2).  We've noticed a couple of glitches:
We knew that a lot of pages don't have an initial h2, so we defaulted to using "Summary" as the initial content was often just that.  Unfortunately, Google doesn't seem to like this if the word "Summary" is not in the right place.  We'll try using the page title instead, because this should be on the page in a relevant place.
When there is no content between h2 tags, we shouldn't generate a question and answer pair, because we'll have an empty answer.
An example …
> FAQPage schema fixes

- CHANGELOG.md
- app/views/govuk_publishing_components/components/_fieldset.html.erb
- app/views/govuk_publishing_components/components/_select.html.erb
- app/views/govuk_publishing_components/components/docs/error_message.yml
- app/views/govuk_publishing_components/components/docs/fieldset.yml
- app/views/govuk_publishing_components/components/docs/select.yml
- spec/components/error_message_spec.rb
- spec/components/fieldset_spec.rb
- spec/components/select_spec.rb
Allows the select component to appear in an error state and accept a given id for an error element (used for aria-describedby) but without an error message appearing. 
This PR also updates the doc and tests for the error message component - I needed to be able to pass an ID to it, it turns out you can already do that but it wasn't documented.
This PR also adds an error state to the fieldset component.
This is intended for use where the select component error message should be rendered separately from the component, which is needed in the [smart answers upgrade](https://github.com/alphagov/smart-answers/pull/4132).
This is the select component in the new state:
This the fieldset error state:
This is how all of this combined will look in smart answers:
This change brings the component …
> Add select component error state without message

- app/controllers/govuk_publishing_components/application_controller.rb
- spec/dummy/config/initializers/content_security_policy.rb
This adds the GOV.UK security policy to the dummy application of this gem. This means that when using this app in dev or viewing it at https://components.publishing.service.gov.uk/component-guide the GOV.UK CSP will apply.
This also has to unfortunately allow unsafe-eval for JS so that the component-guide browser can use AXE. Relevant project issues:
- dequelabs/axe-core#1175
- olado/doT#276
This PR replaces https://github.com/alphagov/govuk_publishing_components/pull/913 by scaling down the ambition of disallowing inline scripts by the use of a nonce. Removing unsafe-inline will only be possible once we drop jQuery 1.x (this [code](https://github.com/jquery/jquery/blob/e09907ce152fb6ef7537a3733b1d65ead8ee6303/src/event/support.js#L7-L20) causes it).
> Add content security policy

- app/assets/stylesheets/component_guide/application.scss
- app/views/govuk_publishing_components/component_guide/example.html.erb
- app/views/govuk_publishing_components/component_guide/show.html.erb
This reorders the code and example blocks on the component guide page.
Because it matches the way examples are presented in the Design System and matches my mental model. I'm raising this with the assumption that this matches other peoples' mental model too 🙂
Live preview:
- [Before](https://components.publishing.service.gov.uk/component-guide/accordion)
- [After](https://govuk-publishing-compo-pr-1147.herokuapp.com/component-guide/accordion)
or scroll below:
<table>
<tr><th>Before</th><th>After</ht></tr>
<tr><td>
</td><td>
</td></tr>
</table>
https://govuk-publishing-compo-pr-1147.herokuapp.com/
> Show code after preview in component guide

- app/views/govuk_publishing_components/component_guide/show.html.erb
Move the 'preview all' link to the first 'How it looks' heading, rather than the 'Other examples' heading.
Whenever I want to find this link I find it difficult. Also it previews all states of the component, not just the other examples.
It's now here:
https://govuk-publishing-compo-pr-1148.herokuapp.com/component-guide
> Make preview all link more prominent

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
Includes:
* Move organisation crest images into the gem ([PR #1149](https://github.com/alphagov/govuk_publishing_components/pull/1149))
> Version 21.4.0

- lib/govuk_publishing_components/presenters/step_by_step_nav_helper.rb
- spec/components/step_by_step_nav_spec.rb
- spec/lib/govuk_publishing_components/components/step_by_step_nav_helper_spec.rb
https://apidock.com/rails/ActiveSupport/Inflector/parameterize
We want to be able to generate links to steps from other places on the site. Using the rails builtin methods for doing this seems like an easy way to converge - even if one of the existing tests does end up looking a little weird. (I'm not sure that 'Step 3?"`_!' is a piece of text that we're likely to see for real.)
> Replace regex with similar method from Rails

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
Includes:
* Add warning, file download and numbered steps icons that were originally fetched from govuk_frontend_toolkit ([PR #1154](https://github.com/alphagov/govuk_publishing_components/pull/1154))
> Version 21.4.1

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/components/contextual-guidance.js
- app/assets/stylesheets/govuk_publishing_components/_all_components.scss
- app/assets/stylesheets/govuk_publishing_components/components/_contextual-guidance.scss
- app/views/govuk_publishing_components/components/_contextual_guidance.html.erb
- app/views/govuk_publishing_components/components/docs/contextual_guidance.yml
- spec/components/contextual_guidance_spec.rb
- spec/javascripts/components/contextual-guidance-spec.js
This PR:
- moves the [contextual-guidance component from Content Publisher](https://content-publisher.integration.publishing.service.gov.uk/component-guide/contextual_guidance) to this gem.
- updates the component as follows:
- ensures the component generates the required layout (2/3 for input 1/3 for guidance) - instead of relying on manually placing the components in the right structure
- refactors the code so that the guidance refers to the input using a `for` attribute - instead of defining for each input what's the associated guidance and then querying it from there. This helps improving isolation for this component as no special attributes are need for the input fields.
The component was ported as-is in the first commit then updated on the following ones to make the refactor …
> Add contextual guidance component

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
* Add contextual guidance component ([PR #1156](https://github.com/alphagov/govuk_publishing_components/pull/1156))
> Release 21.5.0

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/helpers/_brand-colours.scss
We have some specific organisations which are styled separately. The hover and focus states for these organisations were set to remain as the brand colours, whereas all other organisations have text set to black on hover and focus. This brings those other organisations in line with the rest.
The branding hover and focus states should be consistent across organisations
> Bring specific org focus states in line with others

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
Includes:
* Bring specific org focus states in line with others ([PR #1158](https://github.com/alphagov/govuk_publishing_components/pull/1158))
> Version 21.5.1

- app/assets/javascripts/component_guide/accessibility-test.js
- app/assets/javascripts/govuk_publishing_components/dependencies.js
- config/initializers/assets.rb
This gem's `manifest.js` is used for the dummy app that runs the tests, for the gem assets it has a custom manifest [`govuk_publishing_components_manifest.js`](https://github.com/alphagov/govuk_publishing_components/blob/master/app/assets/config/govuk_publishing_components_manifest.js) (presumably not to be confused with the other `manifest.js`), which is something that I've missed in #1160.
Since we're doing an assets clean-up I reference axe-core and jquery directly instead of adding the entire `node_modules` to the paths (which makes searching for assets exponentially longer).
To help all all apps (except for those who depend on `govuk_frontend_toolkit`) to render assets correctly and pass all tests.
None.
> Fix manifest.js name in assets reference

- config/initializers/assets.rb
Add back assets removed in #1160 until we have a thorough understanding of how `manifest.js` works.
To make sure we don't end up with broken references in other apps.
No visual change
> Add assets paths to precompile config

- config/initializers/assets.rb
Disable concurrent export.
Otherwise the assets will be compiled in a random order resulting in failures where, for example, a mixin is called but not yet compiled.
Our [current issue in the CI](https://github.com/sass/sassc-rails/issues/121)
Other [issues related to concurrency in Sprockets 4](https://github.com/rails/sprockets/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+thread+OR+concurrent)
> Disable concurrent export

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
* BREAKING: Update to Sprockets 4 ([PR #1160](https://github.com/alphagov/govuk_publishing_components/pull/1160))
You must make the following changes when you migrate to this release:
- Check application assets and make sure they are [declared in the `manifest.js`](https://github.com/rails/sprockets/blob/master/UPGRADING.md#manifestjs)
- Check reference paths against [assets.paths declarations in govuk_publishing_components](https://github.com/alphagov/govuk_publishing_components/blob/master/config/initializers/assets.rb#L15-L19) and update accordingly.
This release was tested locally with: [calendars](https://github.com/alphagov/calendars), [collections](https://github.com/alphagov/collections), [email-alert-frontend](https://github.com/alphagov/email-alert-frontend), …
> Release 22.0.0

- app/assets/stylesheets/govuk_publishing_components/_all_components_print.scss
- app/assets/stylesheets/govuk_publishing_components/components/print/_attachment.scss
- app/assets/stylesheets/govuk_publishing_components/components/print/_back-link.scss
- app/assets/stylesheets/govuk_publishing_components/components/print/_button.scss
- app/assets/stylesheets/govuk_publishing_components/components/print/_layout-footer.scss
- app/assets/stylesheets/govuk_publishing_components/components/print/_layout-header.scss
- app/assets/stylesheets/govuk_publishing_components/components/print/_metadata.scss
- app/assets/stylesheets/govuk_publishing_components/components/print/_search.scss
- app/assets/stylesheets/govuk_publishing_components/components/print/_skip-link.scss
- app/assets/stylesheets/govuk_publishing_components/components/print/_subscription-links.scss
- app/assets/stylesheets/govuk_publishing_components/components/print/_textarea.scss
- app/assets/stylesheets/govuk_publishing_components/components/print/_translation-nav.scss
- app/views/govuk_publishing_components/components/_layout_for_admin.html.erb
We seem to be missing some print stylesheets for some components, where print styles would be sensible. This PR adds some.
People print pages on GOV.UK.
Screenshots are a bit pointless because most of these changes involve hiding things, but here's a summary.
- [attachment](https://govuk-publishing-compo-pr-1164.herokuapp.com/component-guide/attachment/preview): hide the icon (not sure about this one, should we hide the entire component?)
- [back link](https://govuk-publishing-compo-pr-1164.herokuapp.com/component-guide/back_link/preview): hide completely
- [button](https://govuk-publishing-compo-pr-1164.herokuapp.com/component-guide/button/preview): make all buttons look the same (and like buttons, see below)
- [textarea](https://govuk-publishing-compo-pr-1164.herokuapp.com/component-guid …
> Add component print styles

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/_translation-nav.scss
- app/views/govuk_publishing_components/components/_translation-nav.html.erb
- app/views/govuk_publishing_components/components/docs/translation-nav.yml
- lib/govuk_publishing_components/presenters/translation_nav_helper.rb
- spec/components/translation_nav_spec.rb
Add inverse option to translation component so it displays as white text when the flag is passed. This can be used when using the component on a darker background
We have a use case for using the translation component on a darker background.
https://govuk-publishing-compo-pr-1173.herokuapp.com/component-guide/translation_nav
> Add inverse option to translation component

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
Includes:
* Add component print styles ([PR #1164](https://github.com/alphagov/govuk_publishing_components/pull/1164))
* Bring specific org focus states in line with others ([PR #1158](https://github.com/alphagov/govuk_publishing_components/pull/1158))
* Add inverse option to translation component ([PR #1173](https://github.com/alphagov/govuk_publishing_components/pull/1173))
This version also contains the rollback of the sprockets update, as it was causing problems in our frontend applications.
> Version 21.6.0

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/lib/cookie-functions.js
It is now necessary to not pre-select options on the cookie preferences
form unless the user has explicitly set them. This cookie is used to
check whether they have done so.
> Add essential cookie

- CHANGELOG.md
- app/views/govuk_publishing_components/components/_layout_for_admin.html.erb
This was previously referring to an uninitialised variable and thus had
a value of nil meaning no media type was being set.
This had the effect of overwriting button styling causing broken looking pages.
This fixes a bug where the print stylesheet was not having the media set to "print" was instead set to an uninitialised variable.
This was breaking apps that use the admin layout.
Before:
After:
> Fix media print for admin layout

- CHANGELOG.md
- app/views/govuk_publishing_components/components/docs/machine_readable_metadata.yml
- lib/govuk_publishing_components/presenters/machine_readable/government_service_schema.rb
- lib/govuk_publishing_components/presenters/schema_org.rb
- spec/lib/govuk_publishing_components/presenters/schema_org_spec.rb
This PR adds a new `GovernmentService` schema to be used by the machine readable metadata component. At the moment this is a basic skeleton of a schema, which will be iterated upon as we build out the data used to power it.
Trello: https://trello.com/c/g6uvswCG/69-add-governmentservice-schema-to-transaction-pages
So that we can use the `GovernmentService` schema to help improve results shown on search engines.
Example outputs of this schema run against Google's Structured Data Testing Tool
Book your driving test
Apply for or renew a Blue Badge
https://govuk-publishing-compo-pr-1177.herokuapp.com/
> Add GovernmentService schema.org schema

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
This PR bumps govuk_publishing_components to version `21.7.0`.
> Version 21.7.0

- app/views/govuk_publishing_components/components/_summary_list.html.erb
- spec/components/summary_list_spec.rb
- Update "Edit" link text on summary-list component to be "Change".
- Fix exceeding underline on "Edit" links when used inline with "Delete" link.
We've found in research for Content Publisher that users are confused by the "Edit" action on sections that they haven't yet filled in/haven't interacted with. [The Design System component](https://design-system.service.gov.uk/components/summary-list/) was updated to use "Change" as primary action link so we're updating this one to match the reference. This change is also required for the "Check your answers page" on "Register as an organisation getting funding directly from the EU".
Before
After
https://govuk-publishing-compo-pr-1182.herokuapp.com/summary_list/with_edit_on_individual_items/preview
[Trello card](https://trello.com/c/bjsifdKZ)
> Update edit link text on summary-list

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
* Add `id` option to fieldset ([PR #1183](https://github.com/alphagov/govuk_publishing_components/pull/1183))
* Fix edit link on summary-list component ([PR #1182](https://github.com/alphagov/govuk_publishing_components/pull/1182))
* Make chevron component more resilient ([PR #1181](https://github.com/alphagov/govuk_publishing_components/pull/1181))
> Release v21.8.0

- CHANGELOG.md
- app/views/govuk_publishing_components/components/_summary_list.html.erb
Replacing `+` operator with string interpolation for Change link strings.
Some Rails application do not support string merging using the `+` [failing in the CI because of this](https://ci.integration.publishing.service.gov.uk/job/collections-publisher/job/dependabot%252Fbundler%252Fgovuk_publishing_components-21.8.1/).
> Fix string merge in summary-list component

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/_all_components.scss
- app/assets/stylesheets/govuk_publishing_components/components/_contextual-sidebar.scss
- app/views/govuk_publishing_components/components/_contextual_sidebar.html.erb
- app/views/govuk_publishing_components/components/contextual_sidebar/_brexit_cta.html.erb
- app/views/govuk_publishing_components/components/docs/contextual_sidebar.yml
- lib/govuk_publishing_components/presenters/contextual_navigation.rb
Trello: https://trello.com/c/AksjKWzc/212-create-frontend-landing-page-link-on-sidebar
Adds a "Brexit call-to-action" section to the contextual sidebar component.
We want to signpost people to the Brexit landing page from Brexit-related content. This has been built onto the contextual sidebar component instead of the related navigation component because it needs to be displayed in different positions depending on if the page has related links, step-by-steps or both.
Brexit related content is defined here as: anything tagged to /brexit, /world/brexit or tagged to a taxon which has /brexit as a parent taxon.
**With current step-by-step**
**With related links**
**With part of step-by-steps**
https://govuk-publishing-compo-pr-1189.herokuapp.com/component-guide/contextual_sidebar
> Add Brexit call-to-action link as a related link in the contextual sidebar

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
Includes:
* Fix string merge in summary-list component ([PR #1188](https://github.com/alphagov/govuk_publishing_components/pull/1188))
* Add Brexit call-to-action link as a related link in the contextual sidebar ([PR #1189](https://github.com/alphagov/govuk_publishing_components/pull/1189))
> Version 21.9.0

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/components/details.js
- app/views/govuk_publishing_components/components/_details.html.erb
- app/views/govuk_publishing_components/components/docs/details.yml
- spec/components/details_spec.rb
- spec/javascripts/components/details-spec.js
Trello:
https://trello.com/c/Dtle7GcF/197-modify-details-component-to-enable-tracking-analytics
to unblock https://github.com/alphagov/finder-frontend/pull/1702
Allow tracking of the details component, e.g: on the Brexit checker.
The details component, by default, has `data-module="govuk-details` which makes it difficult for us to add our usual `data-module="track-click"`. We also want some more custom tracking of the open and close status of the component. This adds tracking JS to the component. 
Passing all the necessary data attributes, including `track-label` simply passes the details element to our usual [TrackClick method in static](https://github.com/alphagov/static/blob/master/app/assets/javascripts/modules/track-click.js). This then works in exactly the same way as the rest of …
> Allow tracking of the details component

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
Includes:
* Allow tracking on the details component ([PR #1187](https://github.com/alphagov/govuk_publishing_components/pull/1187))
> Version 21.10.0

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/_document-list.scss
- app/views/govuk_publishing_components/components/_document_list.html.erb
- app/views/govuk_publishing_components/components/docs/document_list.yml
- spec/components/document_list_spec.rb
This is needed to support using the document list for roles in Whitehall. Some roles don't have their own URLs (they are base path less editions) so it doesn't make sense to render a link.
There is some confusion over whether the name of the component "document list" makes sense with this feature. We've decided that it should be fine as long as we make it clear that this is a list of documents, not a list of links (as it is currently written in the description).
https://govuk-publishing-compo-pr-1194.herokuapp.com/component-guide/document_list
[Trello Card](https://trello.com/c/bkZh5sS4/862-update-document-list-component-to-support-documents-without-links)
> Make it possible to render a document list without links

- app/assets/javascripts/component_guide/filter-components.js
Trigger search if search query exists in the query string on page load
When you perform a search then use the back button to come back the search does not persist. This is confusing for users as the user now has to trigger an additional change for the list to be filtered.
https://govuk-publishing-compo-pr-1196.herokuapp.com/
> Trigger search if search query exists in query string on page load

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/_search.scss
This is the only place where we use the `light-blue` in the library and as far as I know, for no strong reasons.
Using `blue` increases the contrast with the magnifying glass icon and makes the component more consistent with other elements on the page.
Before
After
> Update background colour for search buttons

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/_organisation-logo.scss
- app/views/govuk_publishing_components/components/_organisation_logo.html.erb
- app/views/govuk_publishing_components/components/docs/organisation_logo.yml
- spec/components/organisation_logo_spec.rb
This adds an extra configuration option to set the wrapping element of the organisation logo to be a heading.
This also adds the option to make that element not fill up as wide as the parent element. Since this could break things, this option is off by default.
Wrapping the organisation logo in a heading allows it to be part of the content of the page, as required by the [Ministers page](https://www.gov.uk/government/ministers). 
Making the component inline removes a large invisible area that users could mistakenly tap and trigger the link. It also makes the focus state more consistent.
No visual changes when changing the wrapping element.
https://govuk-publishing-compo-pr-1198.herokuapp.com/component-guide/organisation_logo
> Add heading and inline options to organisation logo

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
💎  release includes:
* Update background colour for search buttons ([PR #1197](https://github.com/alphagov/govuk_publishing_components/pull/1197))
* Add option to wrap the organisation logo with a heading, and for the organisation logo to not take up the entire width of the parent element ([PR #1198](https://github.com/alphagov/govuk_publishing_components/pull/1198))
* Support document list items without links ([PR #1194](https://github.com/alphagov/govuk_publishing_components/pull/1194))
> Version 21.11.0

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/lib/primary-links.js
- spec/javascripts/govuk_publishing_components/lib/primary-links.spec.js
Migrate primary-links.js from govuk_frontend_toolkit.
Currently used by manuals-frontend and manuals-publisher
[Part of the work to migrate away from govuk_frontend_toolkit](https://trello.com/c/fxfRx7dQ/95-remove-govukfrontendtoolkit-from-static)
> Migrate primary-links JavaScript from frontend_toolkit

- CHANGELOG.md
- app/views/govuk_publishing_components/components/_search.html.erb
- app/views/govuk_publishing_components/components/docs/search.yml
- spec/components/search_spec.rb
This is adding the ability to specify the `aria-controls` attribute, that's available on the input component.
On finders we are looking to upgrade the text input with a search icon to a search component.
The latter is currently missing this attribute which is being used to announce dynamic changes.
https://govuk-publishing-compo-pr-1203.herokuapp.com/component-guide/search
> Allow aria-controls attribute on search component

- CHANGELOG.md
- package-lock.json
- package.json
Notable change:
- update hex value for secondary text to improve contrast ([updated from #6f777b to #626a6e](https://github.com/alphagov/govuk-frontend/pull/1609))
Update `govuk_publishing_components` to use [`govuk-frontend` version 3.4.0.](https://github.com/alphagov/govuk-frontend/releases/tag/v3.4.0)
Keep frontend code in sync with the Design System updates
For more details regarding changes see [govuk-frontend 3.4.0 changelog](https://github.com/alphagov/govuk-frontend/releases/tag/v3.4.0)
https://govuk-publishing-compo-pr-1204.herokuapp.com/
> Update govuk-frontend to 3.4.0

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
Contains
* Update govuk-frontend to 3.4.0 ([PR #1204](https://github.com/alphagov/govuk_publishing_components/pull/1204))
* Allow aria-controls attribute on search component ([PR #1203](https://github.com/alphagov/govuk_publishing_components/pull/1203))
> Release version 21.13.0

- app/views/govuk_publishing_components/components/docs/accordion.yml
- app/views/govuk_publishing_components/components/docs/breadcrumbs.yml
- app/views/govuk_publishing_components/components/docs/contents_list.yml
- app/views/govuk_publishing_components/components/docs/contextual_sidebar.yml
- app/views/govuk_publishing_components/components/docs/error_summary.yml
- app/views/govuk_publishing_components/components/docs/govspeak.yml
- app/views/govuk_publishing_components/components/docs/inverse_header.yml
- app/views/govuk_publishing_components/components/docs/layout_footer.yml
- app/views/govuk_publishing_components/components/docs/layout_header.yml
- app/views/govuk_publishing_components/components/docs/metadata.yml
- app/views/govuk_publishing_components/components/docs/radio.yml
- app/views/govuk_publishing_components/components/docs/skip_link.yml
Update `accessibility_excluded_rules` on a few components to remove false positives from the component guide.
Our components have fair few accessibility issues, but having not-so-relevant errors makes it harder to focus on those that actually need to be addressed.
https://govuk-publishing-compo-pr-1200.herokuapp.com/component-guide
> Remove false positive accessibility errors

- CHANGELOG.md
- app/controllers/govuk_publishing_components/application_controller.rb
This is causing tests to fail for apps that use the gem but not
on Rails 5.2, which is where CSP is introduced as a feature.
> Check if CSP is available

- app/assets/stylesheets/govuk_publishing_components/components/_feedback.scss
- app/views/govuk_publishing_components/components/feedback/_yes_no_banner.html.erb
This change addresses the issue encountered when a user that has blocked
css styling sees the feedback component. Originally, the options
presented to the user are all strung together in one line, making it
potentially confusing. This change separates them out into a list,
meaning that when there is no styling for the page, each option is on
its own separate row.
The styling is effectively neutralised if css is turned on, and all of
the default behaviours for the lists are removed.
See this [Trello card](https://trello.com/c/otALwPuk/1170-y-n-links-not-obvious-when-styles-are-removed) for more details
> Change tags and styling for feedback component

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
* Add a condition to check that we can use the content_security_policy feature supported from Rails 5.2. ([PR #1206](https://github.com/alphagov/govuk_publishing_components/pull/1206))
> Release version 21.13.1

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/_layout-header.scss
Fixes #1029 
Currently headers with environment label on mobile overlap the menu button if it exists.
This is caused by `white-space: nowrap;` on the `.gem-c-header__logo`.
This property doesn't exist in the GOV.UK Design system code and removing doesn't look to cause any issues.
- https://govuk-publishing-compo-pr-1212.herokuapp.com/component-guide/layout_header
> Fix header environment label layout on mobile

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/_feedback.scss
- app/views/govuk_publishing_components/components/feedback/_yes_no_banner.html.erb
- spec/components/feedback_spec.rb
- spec/javascripts/components/feedback-spec.js
Fix Feedback component layout on mobile.
- uses CSS grid for mobile viewport. Grid is supported in at least two previous mobile browsers - Safari, Chrome, Firefox, Samsung internet that we a majority of users on
- moves link classes to list elements and introduces additional classes to use with the grid positioning
With #1207 we inadvertently broke the component's layout on mobile.
See: https://www.gov.uk/guidance/style-guide/a-to-z-of-gov-uk-style
See: https://www.gov.uk/change-name-deed-poll
https://govuk-publishing-compo-pr-1211.herokuapp.com/component-guide/feedback
- rollback #1207 and think of a better no-css approach
- keep #1207 and just with the Yes/no that sit underneath the heading
[Trello ticket](https://trello.com/c/DyaJaUmQ/1185-fix-feedback-component-layout-on-mobile)
> Fix feedback component layout on mobile

- CHANGELOG.md
- lib/govuk_publishing_components/presenters/meta_tags.rb
- spec/components/meta_tags_spec.rb
Search pages have the document type finder now.
Setting this value invokes this [code from static](https://github.com/alphagov/static/blob/ce77c63aad26f8a408230f30faf7920d45588eaf/app/assets/javascripts/analytics/pii.js#L6) which strips things that look like postcodes from GA.
It's a little heavy handed apparently, so does things like converting 'p800refund' into '[postcode]fund', so we might want to look at it a little more.
> Add finders to doc types that have postcodes

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/_feedback.scss
- remove redundant row definitions and use the implicit rows.
- remove grid column and row definitions from the parent container,
as they're inherited from the child when needed
- replace column definition with a simple two width definitions,
as we only care about the minimum width of the first column
Remove redundant declarations. Keep it simple.
https://govuk-publishing-compo-pr-1216.herokuapp.com/component-guide/feedback/preview
> Simplify CSS Grid on feedback component

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/_feedback.scss
This updates the button / link alignment so that they are side-by-side only on desktop; otherwise stacked.
It also updates the vertical alignment.
Fixes: #1217
See #1217 
https://govuk-publishing-compo-pr-1218.herokuapp.com/component-guide/feedback/preview
> Fix 'Help us improve' feedback form button / link alignment

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
Contains:
* Fix 'Help us improve' feedback form button / link alignment ([#1217](https://github.com/alphagov/govuk_publishing_components/pull/1217))
* Simplify CSS Grid on feedback component ([#1216](https://github.com/alphagov/govuk_publishing_components/pull/1216))
* Add finder doc types to things that strip postcodes from GA. ([#1214](https://github.com/alphagov/govuk_publishing_components/pull/1214))
> Release 21.13.4

- app/views/govuk_publishing_components/components/docs/checkboxes.yml
- lib/govuk_publishing_components/presenters/checkboxes_helper.rb
- spec/components/checkboxes_spec.rb
Fix the option for small checkboxes. The relevant class was only being applied to the component when more than one checkbox was present. This change moves the class into the parent element, so it applies in both situations. I've also added a note to the documentation to clarify the one box/more than one box thing.
One small checkbox is required in [finder-frontend](https://github.com/alphagov/finder-frontend/pull/1798)
None.
https://govuk-publishing-compo-pr-1221.herokuapp.com/
> Fix checkbox small option

- CHANGELOG.md
- app/views/govuk_publishing_components/components/_fieldset.html.erb
- app/views/govuk_publishing_components/components/docs/fieldset.yml
- spec/components/fieldset_spec.rb
Allow custom heading size on fieldset component.
So we can generate custom headings within legends consistently across GOV.UK
Before: https://components.publishing.service.gov.uk/component-guide/fieldset
After: https://govuk-publishing-compo-pr-1223.herokuapp.com/component-guide/fieldset
[Trello card](https://trello.com/c/gYQgI6Xg)
> Allow custom heading size on fieldset component

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
* Allow custom heading size on fieldset component ([#1223](https://github.com/alphagov/govuk_publishing_components/pull/1223))
> Release 21.14.0

- CHANGELOG.md
- app/views/govuk_publishing_components/components/_contextual_guidance.html.erb
- app/views/govuk_publishing_components/components/_textarea.html.erb
- app/views/govuk_publishing_components/components/docs/contextual_guidance.yml
- app/views/govuk_publishing_components/components/docs/textarea.yml
- spec/components/contextual_guidance_spec.rb
- spec/components/textarea_spec.rb
Allow `aria-describedby` on textarea component (similarly to input).
Update the contextual-guidance component to be able to specify an `id` for the guidance content.
To be able to provide descriptions to inputs/textarea to screen readers using the contextual-guidance content.
No visual change.
https://govuk-publishing-compo-pr-1225.herokuapp.com/
[Trello card](https://trello.com/c/LQIMhHs0)
> Allow describedby on textarea

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/components/cookie-banner.js
- app/assets/javascripts/govuk_publishing_components/lib/cookie-functions.js
- app/assets/stylesheets/govuk_publishing_components/components/_cookie-banner.scss
- app/views/govuk_publishing_components/components/_cookie_banner.html.erb
- app/views/govuk_publishing_components/components/docs/cookie_banner.yml
- spec/components/cookie_banner_spec.rb
- spec/javascripts/components/cookie-banner-spec.js
- spec/javascripts/govuk_publishing_components/lib/cookie-functions-spec.js
- spec/javascripts/govuk_publishing_components/lib/govspeak/youtube-link-enhancement-spec.js
Update cookie banner to switch from an opt-out to an opt-in approach.
To give users the power to choose.
Before
After
https://govuk-publishing-compo-pr-1228.herokuapp.com/
> Update cookie banner

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
* Allow textarea to be described by an element outside the component ([#1225](https://github.com/alphagov/govuk_publishing_components/pull/1225))
* Add guidance_id to contextual guidance component ([#1225](https://github.com/alphagov/govuk_publishing_components/pull/1225))
* Update cookie banner component from an opt-out to an opt-in approach ([#1227](https://github.com/alphagov/govuk_publishing_components/pull/1227))
> Release 21.15.0

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
* Fix URL in cookie banner component ([#1228](https://github.com/alphagov/govuk_publishing_components/pull/1228))
> Release 21.15.1

- CHANGELOG.md
- app/views/govuk_publishing_components/components/_cookie_banner.html.erb
Replace `.govuk-row` CSS class with `.govuk-grid-row`
Fixes content alignment
https://govuk-publishing-compo-pr-1233.herokuapp.com/component-guide/cookie_banner
> Use correct grid row class in cookie banner

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/lib/cookie-functions.js
- Fix categorisation of survey cookies
- Improve cookie deletion code
Survey cookies are dynamically generated, so we can't include them in the static list of cookie categories. We need to modify the existing code the handled these to return "settings" instead.
The existing deletion code wasn't deleting all cookies. Sometimes cookies (e.g: GA cookies) are set on www.gov.uk and .www.gov.uk. Our existing code wasn't deleting both types.
> Cookie fixes

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/_cookie-banner.scss
Remove excessive spacing on the right-hand side of the banner on mobile.
For visual harmony
Before
After
https://govuk-publishing-compo-pr-1235.herokuapp.com/
> Fix cookie banner layout mobile

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
Includes:
* Use correct grid row class in cookie banner ([#1233](https://github.com/alphagov/govuk_publishing_components/pull/1233))
* Fix categorisation of survey cookies ([#1234](https://github.com/alphagov/govuk_publishing_components/pull/1234))
* Improve cookie deletion code ([#1234](https://github.com/alphagov/govuk_publishing_components/pull/1234))
> Version 21.15.2

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/components/cookie-banner.js
- app/assets/javascripts/govuk_publishing_components/lib/cookie-functions.js
- spec/javascripts/components/cookie-banner-spec.js
At the moment, if a user had visited GOVUK recently and had cookies set, and they also visited yesterday and got the new default consent cookie, all their existing cookies would remain and not be deleted. This is because the cookie deletion wasn't quite working and cookies are only deleted when setting the consent cookie. The only way for this person to delete their cookies would be for them to 1) manually delete them or 2) for them to set their preferences on the settings page.
This commit adds a method to delete all unconsented cookies when the cookie banner is present, so people in the above position will have previously set cookies deleted for them rather than having to manually delete them.
We can see a GA cookie set before `cookies_policy` was set is never deleted, even on page …
> Delete unconsented cookies before explicit preferences set

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
Includes:
* Delete unconsented cookies automatically ([#1239](https://github.com/alphagov/govuk_publishing_components/pull/1239))
> Version 21.16.0

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/components/cookie-banner.js
- spec/javascripts/components/cookie-banner-spec.js
Fire a pageview when a user clicks to accept cookies. This enables us to capture the landing page, which is critical information in the user journey.
This works by calling the analyticsInit function, which initialises all of the analytics and fires a pageview for both the standard and shared properties.
None.
https://govuk-publishing-compo-pr-1238.herokuapp.com/
> Create pageview on cookie consent

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/_document-list.scss
- app/views/govuk_publishing_components/components/_document_list.html.erb
- app/views/govuk_publishing_components/components/docs/document_list.yml
- spec/components/document_list_spec.rb
Update the document list component so that a document is presented without a wrapping list when only one item is provided.
When using the document list component in conjunction with a table we end up with a list of one item in each cell which makes it harder to navigate using assistive tech. This u
https://govuk-publishing-compo-pr-1226.herokuapp.com/
[Trello card](https://trello.com/c/pJHJYOcK/1256-document-list-markup-should-be-simplified)
> Simplify document list component markup when having only one item

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
* Create pageview on cookie consent ([#1238](https://github.com/alphagov/govuk_publishing_components/pull/1238))
* Simplify document list component markup when having only one item ([#1226](https://github.com/alphagov/govuk_publishing_components/pull/1226))
> Version 21.16.1

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
* Fix stray closing tag in document list component ([#1242](https://github.com/alphagov/govuk_publishing_components/pull/1242))
> Release 21.16.2

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/_document-list.scss
- app/views/govuk_publishing_components/components/_document_list.html.erb
- app/views/govuk_publishing_components/components/docs/document_list.yml
- spec/components/document_list_spec.rb
Reverts alphagov/govuk_publishing_components#1226
One thing that was missed when carrying out this work is that `finder-frontend` (both backend/Rails and frontend/JavaScript) relies heavily on this component having a specific markup structure (div>ul>li) – hence we can not simplify the markup within the component. An alternative option would be to extract the document bit to its own component and update the document-list to make use of it.
> Revert "Simplify document list component markup when having only one item"

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
* Revert 'Simplify document list component markup when having only one item' ([#1244](https://github.com/alphagov/govuk_publishing_components/pull/1244))
> Release 21.16.3

- CHANGELOG.md
- app/views/govuk_publishing_components/components/docs/machine_readable_metadata.yml
- lib/govuk_publishing_components/presenters/machine_readable/dataset_schema.rb
- lib/govuk_publishing_components/presenters/schema_org.rb
- spec/lib/govuk_publishing_components/presenters/schema_org_spec.rb
Add Dataset schema.org schema to machine readable metadata component.
Things that appear in the published statistics list in the [research and stats finder](https://www.gov.uk/search/research-and-statistics) can be marked up with structured data so that they are recognised as statistical datasets (https://developers.google.com/search/docs/data-types/dataset).
One benefit of this is that they might appear in Google's dataset search tool: https://toolbox.google.com/datasetsearch.
https://trello.com/c/0W3LfcGl/1232-implement-schemaorg-dataset-schema-on-published-statistics-document-types
> Add Dataset schema.org schema to machine readable metadata component

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
Adds the schema.org Dataset machine readable schema
https://trello.com/c/0W3LfcGl/1232-implement-schemaorg-dataset-schema-on-published-statistics-document-types
> Bump to 21.17.0

- lib/govuk_publishing_components/presenters/contextual_navigation.rb
Currently we want to show a contextual Brexit sidebar on start pages for any content that is tagged to /brexit or /world/brexit.
This link serves as a call to action to bring people back to the Brexit landing page.
The landing page in turn links to the checker as a major feature, which itself has a start page.
Currently that start page shows this sidebar, putting the user in a loop between the start page and landing page.
To prevent this we add an additional condition to the show_brexit_cta? method, only used in this repo in _show_contextual_sidebar.html.erb,
causing it to return false if the content_id matches the content_id for the Brexit checker start page
Tested:
Example of startup page
Example of other Brexit taxon page
> Remove Brexit CTA link from checker start page

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
Includes:
* Remove Brexit CTA link from checker start page ([#1249](https://github.com/alphagov/govuk_publishing_components/pull/1249))
> Version 21.18.0

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
Includes:
* Add print icons ([#1251](https://github.com/alphagov/govuk_publishing_components/pull/1251))
> Version 21.19.0

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/_notice.scss
Increase notice border size from 2px to 5px.
- Makes the notice more visually prominent
- Brings the component in line with other types of notice/alert, e.g: [error summary](https://components.publishing.service.gov.uk/component-guide/error_summary) and [success alert](https://components.publishing.service.gov.uk/component-guide/success_alert)
https://govuk-publishing-compo-pr-1254.herokuapp.com/component-guide/notice
> Increase notice border size

- CHANGELOG.md
- lib/govuk_publishing_components/presenters/contextual_navigation.rb
Zendesk: https://govuk.zendesk.com/agent/tickets/3890644
Trello: https://trello.com/c/wP0pwnM3/824-related-links-impacting-visibility-of-breadcrumbs-on-guidance
The current ordered_related_items breadcrumb logic relies on having a parent in the links hash, but we don't actually check for this until we try to add breadcrumbs. This adds a check early on, so we don't end up with empty breadcrumbs.
The ordered related items breadcrumbs logic relies on the content item having a parent in the links hash. This isn't always present (in fact, it seems to be a feature of mainstream browse and HTML attachments rather than ordered_related_items).
This means documents with ordered_related_items have empty breadcrumbs, which isn't ideal, especially when they're tagged to taxons which could be shown. …
> Check for ordered related items and parent in breadcrumb logic

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
Includes:
* Check for ordered related items and parent in breadcrumb logic ([#1257](https://github.com/alphagov/govuk_publishing_components/pull/1257))
> Version 21.20.0

- CHANGELOG.md
- package-lock.json
- package.json
Update govuk-frontend dependency to 3.5.0
Keeping dependencies up to date.
Change log: https://github.com/alphagov/govuk-frontend/releases/tag/v3.5.0
> Update govuk-frontend to 3.5.0

- CHANGELOG.md
- lib/govuk_publishing_components/presenters/machine_readable/dataset_schema.rb
- spec/lib/govuk_publishing_components/presenters/schema_org_spec.rb
This is related to the ticket [here](https://trello.com/c/5sN5oxbt/1288-fix-errors-in-dataset-schema), and is aiming to mitigate the errors we've seen with descriptions being bad lengths.
> change dataset schema description to use body primarily

- CHANGELOG.md
- app/views/govuk_publishing_components/components/_layout_footer.html.erb
- app/views/govuk_publishing_components/components/docs/layout_footer.yml
- spec/components/layout_footer_spec.rb
Lets you set attributes for the links in the meta part of the footer.
One of the links in the footer meta required a `lang` and a `hreflang` attribute - but attributes couldn't be added to the meta links. 
https://govuk-publishing-compo-pr-1261.herokuapp.com/component-guide/layout_footer
> Add attribute parameter to meta links in layout footer component

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
Includes:
* Update govuk-frontend to 3.5.0 ([#1262](https://github.com/alphagov/govuk_publishing_components/pull/1262))
* Add attribute parameter to meta links in layout footer component ([#1261](https://github.com/alphagov/govuk_publishing_components/pull/1261))
* Change the dataset schema description ([#1260](https://github.com/alphagov/govuk_publishing_components/pull/1260))
🚀
> Version 21.21.0 

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
Includes:
* Update the text for the Transition contextual sidebar link ([#1264](https://github.com/alphagov/govuk_publishing_components/pull/1264))
> Version 21.21.1

- CHANGELOG.md
- lib/govuk_publishing_components/presenters/page_with_step_by_step_navigation.rb
- spec/features/contextual_navigation_spec.rb
- spec/lib/govuk_publishing_components/presenters/page_with_step_by_step_navigation_spec.rb
https://govuk.zendesk.com/agent/tickets/3884434
We initially had a hard limit on step by step pages to prevent pages that are part of many routes from being overwhelmed with sidebar navigation. We envisaged that https://www.gov.uk/request-copy-criminal-record might be an example of this but the limit was never actually reached at the time.  
This was before the publishing tool and pattern were iterated meaning that publishers had a much finer-grained control over when step by step navigation was shown. 
It appears that this limit may have run its course because we actually want to show 6 step by steps on https://www.gov.uk/eori, so we're going to try removing it for the time being.
> Remove hard limit on step by steps

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/_step-by-step-nav-related.scss
We recently relaxed the restriction on multiple related step by step links in sidebar navigation. This meant that they got renewed scrutiny from design folks who have asked that we increase the spacing between the links to related step by step pages so that they are like related links.
This change also removes the bold font weight when multiple related step by steps are shown in the sidebar.  It does not affect the font weight of the title of a step by step if it is the only one (and therefore also renders the full step by step outline).
Using normal font weight means that the links are closer to related links in appearance, thus increasing the consistency of navigation styles.
> Make step by steps resemble related link styles

- docs/pull_request_template.md
Remove the heroku link in PR templates
We are using the new heroku review apps, which don't have fixed URLs based on PR number.
> Remove heroku link in PR template

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/lib/cookie-functions.js
Trello: https://trello.com/c/3rncf9Pt/439-tech-debt-global-bar-logic-assumes-cookie-category
Given a cookie name, look up the category that this cookie is in.
Good for checking if a cookie has been consented to in advance of doing cookie-based logic.
This will be used to replace [this line](https://github.com/alphagov/static/pull/2019/files#diff-146dfe5256358c4209bb150ac180fabeR15) in Static which assumes the `global_bar_seen` is in the "settings" category. We don't want to make this assumption as the category could change.
> Add cookie category lookup function

- CHANGELOG.md
- lib/govuk_publishing_components/presenters/related_navigation_helper.rb
- spec/components/related_navigation_spec.rb
The slug for the world location 'UK mission in the European Union' doesn't match exactly the title of the world location. Instead the slug shortens 'European Union' to 'EU'.
This means that links to this world location are currently broken (for example
https://www.gov.uk/government/speeches/triggering-the-jcpoa-dispute-resolution-mechanism-foreign-secretarys-commons-statement (see section at the bottom of the page).
This is similar to the special cases that we used to have in government-frontend before they were removed and moved into govuk_publishing_components: https://github.com/alphagov/government-frontend/pull/1035 (see the comment there for more details on why we generate the base paths for world locations based on their slugs).
[Zendesk …
> Add special case for 'UK mission in the European Union'

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
Includes:
* Add cookie category lookup function ([#1272](https://github.com/alphagov/govuk_publishing_components/pull/1272))
* Fix a world location link for 'UK mission in the European Union' ([#1274](https://github.com/alphagov/govuk_publishing_components/pull/1274))
> Version 21.22.0

- app/views/govuk_publishing_components/components/docs/character_count.yml
Adds example showing `threshold` on the `character_count` component.
There is no mention of this functionality on https://components.publishing.service.gov.uk/component-guide/character_count.
I do wonder if the above page should link to https://design-system.service.gov.uk/components/character-count/, which is a little more fully featured. This feels like a bit of documentation duplication - but better to get govuk_publishing_components up to date and consider a better documentation approach later.
N/A
> Adds missing 'threshold' example to character_count component

- CHANGELOG.md
- app/views/govuk_publishing_components/components/_character_count.html.erb
- spec/components/character_count_spec.rb
Make number passed to the character count component (either `maxlength` or `maxwords`) required, render nothing if not passed.
I just tried to use this component and got the maxlength parameter in the wrong place, but instead of failing gracefully the component loaded and then broke, which was briefly very confusing. If one of these parameters is required, let's make it required.
No changes.
> Make maxlength or maxwords required

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/govspeak/_button.scss
- app/views/govuk_publishing_components/components/docs/govspeak.yml
- include 'gem-c-button' class in extend for govuk-button
- this is here to prevent buttons (with white text) from being styled by top level selectors for links, by nesting the styles beneath 'gem-c-govspeak'
- this change relates to a pending update of govspeak to switch to the govuk-frontend button classes for buttons
- once that change is complete the .button class can be removed from here and the example updated
We're trying to remove the toolkit `.button` styles from static.
> Update govspeak button styles

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
* Update govspeak button styles ([PR #1282](https://github.com/alphagov/govuk_publishing_components/pull/1282))
* Make maxlength or maxwords required ([#1276](https://github.com/alphagov/govuk_publishing_components/pull/1276))
> Version 21.22.1

- CHANGELOG.md
- Gemfile.lock
- govuk_publishing_components.gemspec
Downgrade 'rouge' to a dev_dependency
Upgrades to 'rouge' open PRs in repositories that use govuk_publishing_components.
Example: https://github.com/alphagov/whitehall/pull/5342
But this isn't actually used by the components themselves, so should be stripped
out of the gem.
N/A. Heroku app still shows syntax highlighting as expected.
> Downgrade 'rouge' to a development_dependency

- CHANGELOG.md
- Gemfile.lock
- govuk_publishing_components.gemspec
Reverts alphagov/govuk_publishing_components#1288
I didn't realise apps use govuk_publishing_components as a component viewer, as well as for its components. Looks like this change would affect lots of apps: https://github.com/search?q=mount+GovukPublishingComponents%3A%3AEngine&type=Code
See problems caused: https://github.com/alphagov/govuk_publishing_components/pull/1288#issuecomment-585667251
Long term we should probably think about splitting out govuk_publishing_components into components and viewer, rather than bundle it all together.
> Revert "Downgrade 'rouge' to a development_dependency"

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/_breadcrumbs.scss
- app/views/govuk_publishing_components/components/_breadcrumbs.html.erb
- app/views/govuk_publishing_components/components/_contextual_breadcrumbs.html.erb
On mobile devices update breadcrumb behaviour as per :
https://trello.com/c/YuObLgSq/10-fix-breadcrumbs-on-mobile
Apply mobile enhancement designs to the GOV.UK Breadcrumb component, specifically:
- Collapse breadcrumb to show only the first and last item (the parent item) on devices less than 640px wide
- Increase the touch target padding on mobile devices
- Collapse on Mobile to be de facto behaviour
The reasoning is taken from this snippet in the trello card:
> This [article by NNG](https://www.nngroup.com/articles/breadcrumbs/) lays out the pros and cons of showing a full breadcrumb path on mobile. In short, the drawbacks of having a multi-line breadcrumb, and the need to save space on mobile, make it less useful to users. By truncating the breadcrumb we at least allow users to go …
> Mobile breadcrumb to show first and last items only

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/_document-list.scss
Trello: https://trello.com/c/6bJCf1zv/472-increase-spacing-in-document-list-component
Increase margin bottom and padding for broader spacing between document list items.
Flagged through the use of this component on the [GOV.UK transition page](https://www.gov.uk/transition) where the new news section appeared cramped.
The proposal is to increase the amount of spacing, not just for that component but across the site.
Examples:
- Left had side is current,
- Right hand side is proposed change,
Sorry this one was at the bottom of my page, couldn't make them level:
> Increase padding and margin for document list

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/_breadcrumbs.scss
On mobile devices update breadcrumb behaviour for long taxons to wrap and appear aligned with horizontally. Ensure chevron appears aligned correctly. As per trello card:
https://trello.com/c/YuObLgSq/10-fix-breadcrumbs-on-mobile
Apply mobile enhancement designs to the GOV.UK Breadcrumb component, specifically:
- Breadcrumb to display first and last items horizontally on devices less than 640px wide
- Ensure the chevron is aligned to the top of the horizontal breadcrumb
The reasoning is taken from this snippet in the trello card:
> This [article by NNG](https://www.nngroup.com/articles/breadcrumbs/) lays out the pros and cons of showing a full breadcrumb path on mobile. In short, the drawbacks of having a multi-line breadcrumb, and the need to save space on mobile, make it less useful to …
> Mobile breadcrumb to wrap long taxon and correctly align chevron top

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
- Mobile breadcrumb to wrap long taxon and correctly align chevron top ([PR #1296](https://github.com/alphagov/govuk_publishing_components/pull/1296))
- Mobile breadcrumb to show first and last items only ([PR #1290](https://github.com/alphagov/govuk_publishing_components/pull/1290))
- Increases spacing between document links ([PR #1294](https://github.com/alphagov/govuk_publishing_components/pull/1294))
> Version 21.22.2

- CHANGELOG.md
- app/views/govuk_publishing_components/components/_modal_dialogue.html.erb
- app/views/govuk_publishing_components/components/docs/modal_dialogue.yml
- spec/components/modal_dialogue_spec.rb
Enable `aria-label` attribute on `<dialog>` element to be used to summarise what the modal is about.
The modal dialogue component is too verbose when it contains complex content.
When the component is not limited to presenting information (e.g. an alert dialog or an informative dialog) and it contains interactive elements (e.g. form elements) you should use the `aria_label` attribute. This will provide context around what the modal dialogue is about and will prevent it from being too verbose for screen reader users (if `aria_label` is not specified the whole modal content will be read out).
An example in Content Data where the modal dialogue component is used to provide additional information about what a metric means. In this case, reading the whole modal content is helpful.
An example …
> Enable aria-label on modal dialogue component

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/_title.scss
- app/views/govuk_publishing_components/components/_title.html.erb
- app/views/govuk_publishing_components/components/docs/title.yml
- lib/govuk_publishing_components/presenters/shared_helper.rb
- spec/components/title_spec.rb
Allow setting a custom margin-top on title component.
This change will allow the title component to be used in a [Design System page template](https://design-system.service.gov.uk/styles/page-template/) (which sets the padding on the main container – see examples below) by specifying a `margin_top: 0`. This property is introduced to avoid a breaking change and ease the transition to the new page template. When all applications will be using the Design System page template the component will be updated, specifying `margin_top: 0` will not be required and this example will be removed.
https://github.com/alphagov/govuk_publishing_components/pull/1293 is currently dependent on this change and presumably the new layout/template change too.
> Enable custom margin top on title component

- CHANGELOG.md
- app/assets/stylesheets/component_guide/application.scss
- app/views/govuk_publishing_components/component_guide/example.html.erb
- app/views/govuk_publishing_components/component_guide/index.html.erb
- app/views/govuk_publishing_components/component_guide/show.html.erb
- app/views/layouts/govuk_publishing_components/application.html.erb
Fix component guide layout in IE11 by using [the Design System page template](https://design-system.service.gov.uk/styles/page-template/) and render breadcrumbs only if there are items.
@tombye said it's broken while testing at the Empathy lab – and it was bugging me for a while
<table>
<tr><td>
</td><td>
</td></tr>
</table>
> Fix component guide layout in IE11

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
* Enable custom margin top on title component ([PR #1302](https://github.com/alphagov/govuk_publishing_components/pull/1302))
* Enable aria-label on modal dialogue component ([PR #1300](https://github.com/alphagov/govuk_publishing_components/pull/1300))
* Fix component guide layout in IE11 ([PR #1293](https://github.com/alphagov/govuk_publishing_components/pull/1293))
> Release 21.23.0

- CHANGELOG.md
- config/locales/en.yml
This updates the text displayed for users to request an accessible format to be
consistent with the text we use in Whitehall.
This was flagged as an inconsistency when attempting to import a document from Whitehall to Content Publisher.  Content Publisher uses this component, whereas Whitehall reads from its own locale config file.  After checking with a content designer we have decided to match what Whitehall uses so that the message a) is consistent and b) more precise about what the user can request.
**Before**
**After**
> Change attachment request format CTA

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
* Change attachment request format text to match Whitehall ([PR #1306](https://github.com/alphagov/govuk_publishing_components/pull/1306))
> Bump to 21.23.1

- CHANGELOG.md
- app/views/govuk_publishing_components/components/_breadcrumbs.html.erb
- app/views/govuk_publishing_components/components/_step_by_step_nav_header.html.erb
- app/views/govuk_publishing_components/components/docs/breadcrumbs.yml
- lib/govuk_publishing_components/presenters/breadcrumbs.rb
- spec/components/breadcrumbs_spec.rb
On mobile devices update breadcrumb behaviour as per :
https://trello.com/c/YuObLgSq/10-fix-breadcrumbs-on-mobile
Update guidance documentation to remove patterns with "is_current_page"
When a breadcrumb on a mobile device is collapsed, if last item is set as "is_current_page" then it is not possible to navigate to parent items. To eliminate the inconsistency, this option has been removed
> Mobile breadcrumb update guidance

- CHANGELOG.md
- app/views/govuk_publishing_components/components/_radio.html.erb
- app/views/govuk_publishing_components/components/docs/checkboxes.yml
- app/views/govuk_publishing_components/components/docs/radio.yml
- lib/govuk_publishing_components/presenters/checkboxes_helper.rb
- spec/components/checkboxes_spec.rb
- spec/components/radio_spec.rb
Trello: https://trello.com/c/aMTEk0vX/263-add-govuk-caption-style-to-questions
Checkbox and radio components provide a form with an optional page header.
In the design system, question page headings can have a caption, describing the high level category this page fits into ([example](https://design-system.service.gov.uk/patterns/question-pages/section-headings/index.html) | [question pages](https://design-system.service.gov.uk/patterns/question-pages/))
This PR adds the ability for radio and checkbox forms to receive a caption variable that will be rendered as `govuk-caption-xl`.
As captions should describe high level sections on page headers, I have assumed they should not be applied to any other kinds of header.
Even if captions are passed to components, if `is_page_header` is not true, …
> Add caption to question forms

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/_back-link.scss
Update styling of back link component
https://trello.com/c/ZYJ7nnYt/21-make-back-icon-more-consistent-on-mobiles
Update styling on back link component and increase touch target on mobile devices
Back links use an inconsistent icon from the breadcrumbs, The link also has a small touch target on mobiles. We should have consistent design patterns across GOV.UK. 
Before change - mobile
Before Change - desktop
After change - mobile
After Change - desktop
> Change back link arrow to chevron

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
* Mobile breadcrumb update guidance [PR #1298](https://github.com/alphagov/govuk_publishing_components/pull/1298)
* Add page heading captions to checkboxes and radio boxes components ([PR #1304](https://github.com/alphagov/govuk_publishing_components/pull/1304))
* Change back link arrow to chevron [PR #1299](https://github.com/alphagov/govuk_publishing_components/pull/1299)
> Release 21.24.0

- CHANGELOG.md
- app/views/govuk_publishing_components/components/_cookie_banner.html.erb
- app/views/govuk_publishing_components/components/docs/cookie_banner.yml
- spec/components/cookie_banner_spec.rb
Adds the ability to pass the following into the cookie banner and override the default:
- Cookie banner message
- The URL on the 'set cookie preferences' button
This makes the banner more usable by other services which may have their own cookie settings pages and want to remove references to "GOV.UK" in the cookie banner messaging.
Our specific use case at the moment is data.gov.uk, which is GDS-owned but lives on a separate URL.
Heroku: https://govuk-publis-make-cooki-p0dhlc.herokuapp.com/component-guide/cookie_banner
> Make cookie banner text and preferences URL customisable

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/lib/cookie-functions.js
Add DGU-specific cookies to the list of cookie categories.
This cookie isn't actually being used on data.gov.uk any more, but it needs to be added to the list so it can be removed when the default cookie consent is set.
> Add data.gov.uk (DGU) cookies

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
Includes:
* Make cookie banner text and preferences URL customisable ([PR #1310](https://github.com/alphagov/govuk_publishing_components/pull/1310))
* Add DGU-specific cookie ([PR #1315](https://github.com/alphagov/govuk_publishing_components/pull/1315))
> Version 21.25.0

- CHANGELOG.md
- app/assets/stylesheets/component_guide/application.scss
- app/assets/stylesheets/govuk_publishing_components/component_support.scss
- app/assets/stylesheets/govuk_publishing_components/govuk-frontend.scss
- app/assets/stylesheets/govuk_publishing_components/govuk_frontend_support.scss
- app/controllers/govuk_publishing_components/component_guide_controller.rb
- app/models/govuk_publishing_components/component_docs.rb
- app/views/govuk_publishing_components/component_guide/index.html.erb
- spec/component_guide/component_index_spec.rb
Change the components gem to support the model proposed in [RFC 108](https://github.com/alphagov/govuk-rfcs/pull/110) where individual components are included in an application rather than all of them.
The Sass now contains two additional files necessary for applications when importing individual components:
- `govuk_frontend_support`, which contains general settings from the gem plus everything from govuk-frontend that adds no weight to the compiled CSS (settings, tools and helpers)
- `component_support`, which contains everything else from govuk-frontend, plus helpers and mixins from the gem used by various components
So an application would import both of these files, then the sass for the components it needs. This has been split into two files like this so that static can import the …
> Allow individual components to be imported into apps

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
* Allow individual components to be imported into apps ([PR #1159](https://github.com/alphagov/govuk_publishing_components/pull/1159))
This is a significant change, but it's fully backwards compatible and no changes in applications are required, so I believe it should still be a minor version.
> Version 21.26.0

- app/views/layouts/govuk_publishing_components/application.html.erb
- the new gem allows individual sass for components to be imported into applications
- this isn't quite perfect yet, because the component guide imports its own sass and the application's sass
- both now import govuk-frontend (this isn't ideal, I realise) but differ in the components they import, the guide imports all, the application imports some
- now that the two are different, including the application's sass after the component guide means that govuk-frontend's styles for the layout header are overridding those in the layout header component
- fix is to swap the ordering of these in the guide markup, but ideally a better solution can be found as clearly some duplication is happening here
Component guide should look like this:
but looks like this:
This PR fixes that.
Just for …
> Fix layout header width issue

- SUPPORT.md
The support notice is brief because, as a community, we can't make promises about how quick we can respond to issues or feature requests.
The support notice should be linked to within the GitHub interface when person raises an issue. For more information, see the [GitHub documentation on SUPPORT.md](https://help.github.com/en/github/building-a-strong-community/adding-support-resources-to-your-project)
This repository doesn't currently anything around what to expect when raising an issue.
None.
> Add Code of Conduct, Security, and Support docs

- CHANGELOG.md
- app/views/govuk_publishing_components/components/_share_links.html.erb
- app/views/govuk_publishing_components/components/docs/share_links.yml
- spec/components/share_links_spec.rb
- Adds an `hidden_text` link to specify custom visually hidden link text
- Adds a default 'Share on` visually hidden text to each share link if `hidden_text` value is not provided
Improve accessibility and remove the need for [workarounds](#1064 )
Fixes #1064 
https://govuk-publis-share-link-crmidx.herokuapp.com/component-guide/share_links/with_custom_visually_hidden_text
> Add visually hidden text to share links component

- CHANGELOG.md
- app/controllers/govuk_publishing_components/component_guide_controller.rb
- app/views/govuk_publishing_components/component_guide/index.html.erb
- spec/component_guide/component_index_spec.rb
This change relates to the work done in https://github.com/alphagov/govuk_publishing_components/pull/1159 to allow individual components to be imported into an application, specifically relating to an oversight in the 'suggested sass for this application' functionality.
- the component guide was checking for what components are in use, but some components import other components, so it was missing those
- added a check for components within components and added to suggested sass output
> Improve suggested sass functionality

- app/views/govuk_publishing_components/components/_layout_for_public.html.erb
- app/views/govuk_publishing_components/components/docs/layout_for_public.yml
- spec/components/layout_for_public_spec.rb
https://trello.com/c/i18ikmOk/214-omit-header-for-htmlpublications
**This PR is against rebased-add-layout and not against master.**
Duplicate the functionality from govuk_template in static. This
is used to render previews of CSV files from Whitehall.
This is used to render previews of CSV files from Whitehall. I'm unclear on why we still show the footer and don't have a flag for that but this is being kept to the scope of the original.
When implemented in the component guide only the footer is shown visibly on the page:
> Add option to omit header

- app/views/govuk_publishing_components/components/layout_header/_header_logo.html.erb
**Note this PR is not raised against master**
https://trello.com/c/Evatcpym/216-check-tracking-for-the-public-template
This adds tracking to the home link in the header
This replicates what is currently live in the static template. No visible changes are introduced. No other links are tracked in the original.
> Add tracking to home link

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
* Update Sass documentation ([PR #1321](https://github.com/alphagov/govuk_publishing_components/pull/1321))
* Improve suggested sass functionality ([PR #1320](https://github.com/alphagov/govuk_publishing_components/pull/1320))
* Fix layout header width issue ([PR #1319](https://github.com/alphagov/govuk_publishing_components/pull/1319))
* Add visually hidden text to share links component ([PR #1286](https://github.com/alphagov/govuk_publishing_components/pull/1286/))
> Version 21.26.1

- CHANGELOG.md
- app/views/govuk_publishing_components/components/_breadcrumbs.html.erb
- app/views/govuk_publishing_components/components/docs/breadcrumbs.yml
- spec/components/breadcrumbs_spec.rb
Part of updating breadcrumb behaviour as per :
https://trello.com/c/YuObLgSq/10-fix-breadcrumbs-on-mobile
https://docs.google.com/document/d/1OFG1Ln6VeCR_bc0qmUtRwMJU62Ljw4F3HO6hq2yloXk/
Add logic to check for breadcrumb item to not show if it does not have a corresponding "url" 
Breadcrumb items with no "url", do not aid navigation. Specifically, when a breadcrumb is collapsed on a mobile device to show only first and last items, there is no method to navigate to the parent page
> Dont show breadcrumb item with no url

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
* Streamline feedback component ([PR #1327](https://github.com/alphagov/govuk_publishing_components/pull/1327))
* Dont show breadcrumb item with no url ([PR #1324](https://github.com/alphagov/govuk_publishing_components/pull/1324))
> Version 21.26.2

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/_contents-list.scss
- app/views/govuk_publishing_components/components/docs/contents_list.yml
- lib/govuk_publishing_components/presenters/contents_list_helper.rb
- spec/components/contents_list_spec.rb
Remove `font_size` option on the contents list component.
- We added this option to the component for one iteration of the Brexit landing page, but it ended up not being used.
- The mobile team are looking at making font-sizes more consistent across GOVUK so page hierarchy is clearer. 
- The font-size flag on this component isn't being used yet and we probably don't want to encourage its use. We may as well remove it for now.
> Remove font-size option for contents list

- CHANGELOG.md
- spec/javascripts/components/feedback-spec.js
- there are several tests in the feedback component to check that when parts of the component are interacted with specific inputs or error messages receive focus
- these tests were failing intermittently, despite not having changed recently
- unsure of the cause of this, but the result was that the body was focussed and not the intended input
- changing the tests to check that focus is called on the correct elements instead of checking to see what the activeElement is seems to work
These errors have been causing builds to fail for days. Hopefully this has fixed them.
None.
> Fix feedback component tests

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/_breadcrumbs.scss
- app/views/govuk_publishing_components/components/_breadcrumbs.html.erb
- app/views/govuk_publishing_components/components/_contextual_breadcrumbs.html.erb
- app/views/govuk_publishing_components/components/docs/breadcrumbs.yml
- spec/components/breadcrumbs_spec.rb
- spec/components/contextual_breadcrumbs_spec.rb
- Revert default breadcrumb behaviour back to non-collapsing on mobile
- Adds a `collapse_on_mobile` flag. This defaults to false, but it is recommended that anyone using the breadcrumbs for navigation sets this to true.
- Set collapse_on_mobile to true in the contextual breadcrumbs component
- Reverts [#1324](https://github.com/alphagov/govuk_publishing_components/pull/1324) to allow breadcrumb items without URLs.
- Mobile touch targets only apply if `collapse_on_mobile` is set to true. We can look at fixing this in the future, but I think it will need some design work.
As discussed in https://github.com/alphagov/govuk_publishing_components/pull/1324 , we had missed some use cases for this component and our changes essentially broke this component for them.
My original approach was to …
> Make breadcrumb component more flexible to support different uses

- app/assets/stylesheets/govuk_publishing_components/component_support.scss
Remove `govuk/components/all` from `component_support`.
We already import styles for components [in each individual file](https://github.com/alphagov/govuk_publishing_components/blob/master/app/assets/stylesheets/govuk_publishing_components/components/_accordion.scss#L1) so adding them in the `component_support` again inflates the scss and increased the compilation time unnecessarily.
TBD
> Remove redundant components import

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
Includes:
* Remove font_size option on contents list ([PR #1325](https://github.com/alphagov/govuk_publishing_components/pull/1325))
* Fix feedback component tests ([PR #1329](https://github.com/alphagov/govuk_publishing_components/pull/1329))
* Revert 'Dont show breadcrumb item with no url' ([PR #1330](https://github.com/alphagov/govuk_publishing_components/pull/1330))
* Make breadcrumb collapsing behaviour opt-in and provide `collapse_on_mobile` flag ([PR #1330](https://github.com/alphagov/govuk_publishing_components/pull/1330))
> Version 21.27.0

- CHANGELOG.md
- app/views/govuk_publishing_components/components/_search.html.erb
- spec/components/search_spec.rb
Check for `true` (boolean) value for `on_govuk_blue` parameter.
We used to check only if the parameter exist, not its value.
This made it difficult to conditionally toggle classes.
Now we check it the local_assign value is `true` before we add `gem-c-search--on-govuk-blue` CSS class to the component.
In finder-frontend we're looking to unify the page templates and we have scenarios where the search box will appear on either a white or blue background. At the moment the search component renders will appropriate classes as soon as `on_govuk_blue` local parameter is present without checking for `true`, which means we cannot alternate the appearance
> Fix handling of `on_govuk_blue` parameter value in the search component

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
-  Fix handling of `on_govuk_blue` parameter value in the search component ([PR #1334](https://github.com/alphagov/govuk_publishing_components/pull/1334))
> Version 21.27.1

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/_previous-and-next-navigation.scss
- app/views/govuk_publishing_components/components/_previous_and_next_navigation.html.erb
Trello: https://trello.com/c/4ZsqNg3r/11-layout-improve-previous-and-next-navigation-component-on-mobile
This PR makes the following changes to the pagination (previous and next) component:
- Increase spacing above and below the component
- Increase spacing between previous and next links
- Add border-top to links
Changes made as per the [design doc](https://docs.google.com/document/d/1ryu7LdOiJdKGqG_lUZOwDPOpLpSNw0MVAGaWx6ocmuw/edit#)
The pagination component needs to be a separate and distinct section of the page. These changes help separate the component from the rest of the page content. The spacing and border changes also add clearer separation between the previous and next links themselves.
> Tweak pagination component spacing and add border

- app/models/govuk_publishing_components/component_example.rb
- app/views/govuk_publishing_components/components/_layout_for_public.html.erb
- spec/components/layout_footer_spec.rb
- spec/components/layout_for_public_spec.rb
- spec/components/layout_header_spec.rb
- spec/components/search_spec.rb
- spec/dummy/app/controllers/welcome_controller.rb
- spec/dummy/config/routes.rb
Changes some quotes and adds some commas. This was necessary on parts of the codebase where we diverged from master which has been re-linted to current standards. This is a PR against rebased-add-layout rather than master.
> Linting where rebased-add-layout has diverged from master

- CHANGELOG.md
- app/views/govuk_publishing_components/components/docs/button.yml
- lib/govuk_publishing_components/presenters/button_helper.rb
- spec/components/button_spec.rb
Add support for custom `class` and `aria-label` to the button component.
Currently need for the [reorderable list component](https://github.com/alphagov/content-publisher/pull/1819) in Content Publisher as follows:
- custom `class` is required to be able to query buttons from JavaScript using `js-` prefixed class (e.g. `.js-app-button-up` to identify a button that moves items upwards) without adding excessive wrapper elements.
- `aria-label` is required to give screen reader users context on what button acts on (e.g. "Up" button would have a "Move Budget 2019 up" as `aria-label`).
[Trello card](https://trello.com/c/H3T7JWtS)
> Enable custom classes and aria-label on button component

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
* Improve numeric inputs ([PR #1345](https://github.com/alphagov/govuk_publishing_components/pull/1345))
* Enable custom classes and `aria-label` on button component ([PR #1344](https://github.com/alphagov/govuk_publishing_components/pull/1344))
* Tweak pagination component spacing and add border ([PR #1337](https://github.com/alphagov/govuk_publishing_components/pull/1337))
> Release 21.28.0

- govuk_publishing_components.gemspec
This is depended on by https://github.com/alphagov/govuk-jenkinslib/pull/66.
> Make entire repository pass Rubocop linting

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/_attachment.scss
- app/assets/stylesheets/govuk_publishing_components/components/govspeak/_attachment.scss
- app/views/govuk_publishing_components/components/docs/govspeak.yml
Fix overflowing URLs and email addresses in govspeak-rendered attachments and the attachment component.
To make sure the page layout doesn't break
<table>
<tr><td>
</td><td>
</td></tr>
</table>
Reference: [the `url` class generated by govspeak](https://github.com/alphagov/govspeak/blob/f8131efa42c2838a6c94288bd0404e13b0f17ad2/lib/govspeak/presenters/attachment_presenter.rb#L39)
<table>
<tr><td>
</td><td>
</td></tr>
</table>
govspeak attachments problem on the live website: https://www.gov.uk/government/publications/covid-19-track-coronavirus-cases reported by @timpaul.
[attachments component problem tracked in Content Publisher](https://trello.com/c/IGI9Hf16).
> Fix overflowing text in attachments

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
* Fix overflowing text in attachments ([PR #1352](https://github.com/alphagov/govuk_publishing_components/pull/1352))
> Release 21.28.1

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/_feedback.scss
- app/views/govuk_publishing_components/components/_feedback.html.erb
- app/views/govuk_publishing_components/components/docs/feedback.yml
- app/views/govuk_publishing_components/components/feedback/_yes_no_banner.html.erb
- spec/components/feedback_spec.rb
- Implement new design for feedback component, with larger touch targets and more responsive layout.
- Tidy up unused feedback component code
- Remove outdated sections of feedback component documentation
Small touch targets and small spacing between items makes it visually frustrating, but for mobile users this might make it harder to click on the intended link.
The previous design also failed when a user zoomed, as the links started to overflow the container.
> Make feedback component more responsive and usable on mobile

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/_document-list.scss
- app/views/govuk_publishing_components/components/_document_list.html.erb
- app/views/govuk_publishing_components/components/docs/document_list.yml
- spec/components/document_list_spec.rb
Extend the document-list component to allow parts of documents to be displayed.
Some documents such as guides and travel advice contain parts.
This extends the document-list component to display those parts. 
In finder-frontend we're testing with users showing [document parts in search results](https://github.com/alphagov/finder-frontend/pull/1877). 
For the test we vendored-in the component and extended it and this is upstreaming the change.
The layout uses grid at desktop, if grid isn't supported the parts are collapsed into a list like structure.
**Desktop:**
**Tablet:**
**Mobile:**
**With branding:**
> Extend document-list component to show parts of a document

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/govspeak/_button.scss
- app/views/govuk_publishing_components/components/docs/govspeak.yml
- remove 'button' class from extend for buttons in govspeak
- this change relates to an update of govspeak that switches from the toolkit buttons to the new component guide buttons
- after consideration I don't believe we need to extend both the gem-c-button class and the govuk-button class, just the gem-c-button class seems to work fine, adding both adding unnecessary CSS weight
- this change follows on from PR #1282 
This all ties in to the removal of the `.button` class from static: https://github.com/alphagov/static/pull/2035
Trello card: https://trello.com/c/d8D7JTJE/203-%F0%9F%8F%B4%E2%98%A0%EF%B8%8F-remove-design-patterns-buttons-from-static
None.
> Update govspeak button styles again

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
Includes:
* Make feedback component more responsive and usable on mobile ([PR #1346](https://github.com/alphagov/govuk_publishing_components/pull/1346))
* Extend document-list component to show parts of a document ([PR #1326](https://github.com/alphagov/govuk_publishing_components/pull/1326))
* Update govspeak button styles again ([PR #1342](https://github.com/alphagov/govuk_publishing_components/pull/1342))
> Version 21.29.0

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/_previous-and-next-navigation.scss
Adds the legacy alternative for dark-grey in the previous and next navigation component.
I missed off the `legacy` value for dark-grey when making changes to the previous and next navigation component, and this was leading to some failing builds for some apps.
> Add missing legacy colour for dark-grey

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
Includes:
* Patch: add missing legacy colour for dark-grey ([PR #1358](https://github.com/alphagov/govuk_publishing_components/pull/1358))
> Version 21.29.1

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/_attachment.scss
- app/views/govuk_publishing_components/components/_attachment.html.erb
- app/views/govuk_publishing_components/components/docs/attachment.yml
- lib/govuk_publishing_components/presenters/attachment.rb
- spec/components/attachment_spec.rb
- spec/lib/govuk_publishing_components/presenters/attachment_spec.rb
Add reference details to attachments
To accommodate publications attachments and bring them close to how they are now rendered by Whitehall (in terms of presented data)
[Preview attachment component](https://govuk-publis-publicatio-e3wxt3.herokuapp.com/component-guide/attachment)
[Trello card](https://trello.com/c/UET4vx6k/1439-update-attachment-component-to-accommodate-new-attachment-design)
> Update attachment component to accommodate publications

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
* Update attachment component to accommodate publications ([PR #1375](https://github.com/alphagov/govuk_publishing_components/pull/1375))
> Release 21.30.0

- CHANGELOG.md
- app/views/govuk_publishing_components/components/_layout_header.html.erb
- spec/components/layout_header_spec.rb
Hide product name and environment tag if the environment is set to "public". In line with the approach in #1265 – which will bring a new and shiny public-facing layout ✨ , but until that's ready we can already use the header in public-facing apps such as https://github.com/alphagov/govuk-coronavirus-business-volunteer-form.
To prepare the header component for public-facing usage
[Trello card](https://trello.com/c/S8Ht5CJq/10-setup-application-page-layout)
> Prepare header component for public-facing usage

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
Prepare header component for public-facing usage ([PR #1384](https://github.com/alphagov/govuk_publishing_components/pull/1384))
> Release 21.31.0

- CHANGELOG.md
- app/views/govuk_publishing_components/components/_label.html.erb
- app/views/govuk_publishing_components/components/docs/label.yml
- app/views/govuk_publishing_components/components/docs/textarea.yml
- spec/components/label_spec.rb
Enable label as page heading
Rationale: https://design-system.service.gov.uk/get-started/labels-legends-headings/#labels-as-page-headings.
This PR mirrors the Design System component code in [govuk-frontend](https://github.com/alphagov/govuk-frontend/blob/master/src/govuk/components/label/template.njk)
Example on textarea
[Trello card](https://trello.com/c/nx25TT4p/60-allow-textarea-component-to-be-used-in-a-one-question-per-page-scenario)
Fixes #1388. Raised to help https://github.com/alphagov/govuk-coronavirus-business-volunteer-form/pull/36
> Enable label as page heading

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
* Enable label as page heading ([PR #1389](https://github.com/alphagov/govuk_publishing_components/pull/1389))
> Release 21.32.0

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/helpers/_brand-colours.scss
Add a brand colour for Public Health England, to be used on the coronavirus landing page.
We don't have this as a brand colour yet and we now need to use it in components.
No visual changes, but here's an example of the colour in use.
> Add PHE branding

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/_heading.scss
- app/views/govuk_publishing_components/components/_heading.html.erb
- app/views/govuk_publishing_components/components/docs/heading.yml
- lib/govuk_publishing_components/presenters/heading_helper.rb
- spec/components/heading_spec.rb
Adds an inverse option for the heading, for white text on a dark background.
Needed on the coronavirus landing page.
> Add invert option to heading component

- app/assets/stylesheets/govuk_publishing_components/components/helpers/_brand-colours.scss
Rename recently added colour variable to have a `gem-c` prefix.
Because it's already used elsewhere and might cause a conflict. Also this is good practice.
None.
> Rename colour variable

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
* Add PHE branding ([PR #1396](https://github.com/alphagov/govuk_publishing_components/pull/1396))
* Add invert option to heading component ([PR #1397](https://github.com/alphagov/govuk_publishing_components/pull/1397))
> Version 21.33.0

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/lib/cookie-functions.js
Required for https://github.com/alphagov/frontend/pull/2298
The cookie name is constructed in https://github.com/alphagov/frontend/pull/2298/files#diff-6b36a1b0d15da539f564a110dc18b378R139 and https://github.com/alphagov/frontend/pull/2298/files#diff-ca00ebfded4d715e743554943f03131fR34.
> Add custom multivariate test cookie as essential

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
* Add custom multivariate test as essential cookie ([PR #1400](https://github.com/alphagov/govuk_publishing_components/pull/1400))
> Release 21.34.0

- CHANGELOG.md
- app/views/govuk_publishing_components/components/docs/checkboxes.yml
- app/views/govuk_publishing_components/components/docs/radio.yml
- lib/govuk_publishing_components/presenters/checkboxes_helper.rb
Fix conditional reveal on checkboxes
Add examples for pre-checked items with conditonal reveal
GOV.UK Frontend script for conditional reveal (`checkboxes.js`) requires a `data-aria-controls` not a `data-controls` attribute as currently implemented. This being misconfigured means the script doesn't show the conditional content when pre-checked. This is a major problem when presenting errors to a field within the conditionally revealed block.
No visual changes, only functional changes: [Preview checkboxes with conditional revealed content in a pre-checked state](https://govuk-publis-fix-condit-svxz7n.herokuapp.com/component-guide/checkboxes/checkbox_items_with_conditional_reveal_checked) – you'll also see a bunch of axe errors which are not introduced by this change and shall be addressed, …
> Fix conditional reveal on checkboxes

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
* Fix conditional reveal on checkboxes #1402 ([PR #1402](https://github.com/alphagov/govuk_publishing_components/pull/1402))
> Release 21.34.1

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/components/cookie-banner.js
- spec/javascripts/components/cookie-banner-spec.js
Currently, if a user accepts cookies and then immediately clicks to hide the global banner, this setting isn't saved and they will see the banner the next time they refresh.
This is because the global_bar_seen cookie isn't set when giving consent to cookies, it is only set on the next page view.
This commit runs the initialise code for the global bar when cookies are approved, to set the cookie without the need for page refresh.
> Initialise global bar on approving all cookies

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
Includes:
* Set global_bar_cookie immediately when cookie consent given ([PR #1405](https://github.com/alphagov/govuk_publishing_components/pull/1405))
> Version 21.35.0

- CHANGELOG.md
- app/models/govuk_publishing_components/shared_accessibility_criteria.rb
- app/views/govuk_publishing_components/components/docs/cookie_banner.yml
- app/views/govuk_publishing_components/components/docs/layout_footer.yml
- app/views/govuk_publishing_components/components/docs/layout_header.yml
Adds 'have meaningful text' into the shared accessibility criteria for links, and changes some of the documentation files to use the shared accessibility criteria for links, rather than writing out their own, which were largely the same.
None.
> Update link accessibility criteria

- CHANGELOG.md
- app/assets/stylesheets/component_guide/application.scss
- app/controllers/govuk_publishing_components/component_guide_controller.rb
- spec/component_guide/component_index_spec.rb
Since the change to allow applications to only include the sass for components they need, we've had duplicate CSS for all components loading in the component guide.
This change includes the sass for components used in the guide in the suggested sass and removes the sass for components from the guide stylesheet. There are two possible configurations for an application:
- the application includes the sass for all components, as before. Both the application and the guide have no styling issues or duplication
- the application includes the sass for only the components it is using, plus the components in use within the guide (8 components, although there may be some overlap, e.g. both probably use `breadcrumbs`). Both the application and the guide have no styling issues or duplication
This …
> Fix duplicate CSS for components loading in component guide

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
* Update link accessibility criteria ([PR #1407](https://github.com/alphagov/govuk_publishing_components/pull/1407))
* Fix duplicate CSS for components loading in component guide ([PR #1356](https://github.com/alphagov/govuk_publishing_components/pull/1356))
> Version 21.36.0

- app/views/govuk_publishing_components/components/docs/textarea.yml
- spec/components/textarea_spec.rb
Add documentation and a test for the ability to give the textarea component a custom ID.
I wanted to do this recently and found it wasn't documented.
> Document textarea ID option

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/_back-link.scss
Safari only supports clip-path with the -webkit prefix, which is being being used to apply the clip-path in GOV.UK Frontend. In order to unset it, we also need to use the -webkit prefix here.
See #1387
Fixes #1387
> Fix back link in Safari

- CHANGELOG.md
- app/assets/stylesheets/component_guide/application.scss
- app/assets/stylesheets/component_guide/print.scss
- app/controllers/govuk_publishing_components/component_guide_controller.rb
- app/views/layouts/govuk_publishing_components/application.html.erb
- config/initializers/assets.rb
- spec/component_guide/component_index_spec.rb
New strategy for the component guide sass:
- include all components
- include a new print stylesheet for all the components
- don't include the application stylesheet anymore
Oh boy this is complicated. Hold on to your hats.
Back before individual component sass inclusion, the component guide was relatively simple. It had its own styles for specific bits but also used several components (e.g. lead paragraph). It pulled in the stylesheet from the parent application (either an actual application, or the gem's own dummy app). Both the parent and the dummy included all styles for all components, so everything worked.
Then we introduced individual component sass inclusion. The guide in the gem worked fine, because the dummy app was still pulling in all component styles, but the guide in an …
> Change component guide sass

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
* Fix back link arrow rendering in Safari ([PR #1411](https://github.com/alphagov/govuk_publishing_components/pull/1411))
* Change component guide sass ([PR #1409](https://github.com/alphagov/govuk_publishing_components/pull/1409))
> Version 21.36.1

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/_warning-text.scss
- app/views/govuk_publishing_components/components/_warning_text.html.erb
- app/views/govuk_publishing_components/components/docs/warning_text.yml
- spec/components/warning_text_spec.rb
- allows the component to be rendered as a heading
- uses the shared helper code for headings
We're using the styles from the component on a heading element on [travel pages like this one](https://www.gov.uk/foreign-travel-advice/usa/entry-requirements) but not the component itself. This change will allow us to switch to using the component.
> Add heading option to warning component

- CHANGELOG.md
- app/views/govuk_publishing_components/components/docs/machine_readable_metadata.yml
- lib/govuk_publishing_components/presenters/machine_readable/dataset_schema.rb
- lib/govuk_publishing_components/presenters/machine_readable/page.rb
- spec/lib/govuk_publishing_components/presenters/schema_org_spec.rb
Add the "distribution" property to the machine readable metadata for datasets.  You can try it out by putting something like this snippet in the Google metadata verification tool:
```
{
"@context": "http://schema.org",
"@type": "Dataset",
"mainEntityOfPage": {
"@type": "WebPage",
"@id": "https://www.gov.uk/government/statistics/e-coli-bacteraemia-monthly-data-by-location-of-onset"
},
"headline": "E. coli bacteraemia: monthly data by location of onset",
"distribution": [
{
"name": "E. coli bacteraemia: monthly counts by location of onset by NHS organisation, from February 2019 to February 2020",
"encodingFormat": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
"contentUrl": "https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/ …
```
> Add the "distribution" property to the dataset metadata

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
* Add heading option to warning component ([PR #1415](https://github.com/alphagov/govuk_publishing_components/pull/1415))
* Add the "distribution" property to the dataset machine readable metadata ([PR #1416](https://github.com/alphagov/govuk_publishing_components/pull/1416))
* Fix the dataset machine readable metadata erroring if there is no description set ([PR #1416](https://github.com/alphagov/govuk_publishing_components/pull/1416))
> Bump to version 21.37.0

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/lib/govspeak/youtube-link-enhancement.js
- app/views/govuk_publishing_components/components/docs/govspeak.yml
- spec/javascripts/govuk_publishing_components/lib/govspeak/youtube-link-enhancement-spec.js
Expand our video player code to handle livestream links.
This PR also fixes a Javascript error that was happening because the video title property couldn't be reached.
Our video player code expected a video URL that looks like this: 
`https://www.youtube.com/watch?v=y6hbrS3DheU` - essentially a youtube URL with a videoId (v) query param.
This means that it didn't support livestream URLs which look like this: 
`https://www.youtube.com/embed/live_stream?channel=UCoMdktPbSTixAyNGwb-UYkQ`
These URLs are structured slightly differently with 'live_stream' and a channel ID instead of videoId.
Preview URLs:
- [Standard Youtube Embed](https://govuk-publis-spike-live-ftkn8m.herokuapp.com/component-guide/govspeak/with_youtube_embed)
- [Livestream Youtube …
> Allow livestream youtube URLs

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
Includes:
* Expand video player to support youtube livestream URLs ([PR #1418](https://github.com/alphagov/govuk_publishing_components/pull/1418))
> Version 21.38.0

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
* Correct CreativeWork to use name and text fields instead of headLine and description ([PR #1423](https://github.com/alphagov/govuk_publishing_components/pull/1423))
> Release 21.38.1

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/helpers/_brand-colours.scss
Trello: https://trello.com/c/YT0f0FDN/133-update-theme-from-lime-to-yellow
Switch covid-green to covid-yellow
Update the branding colour for Public Health England to match the latest colours being used
> Update colour from lime to lemon

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
Includes:
* Switch Public Health England branding colour from green to yellow ([PR #1425](https://github.com/alphagov/govuk_publishing_components/pull/1425))
> Version 21.38.2

- CHANGELOG.md
- app/views/govuk_publishing_components/components/_attachment.html.erb
It could otherwise be confusing that if you've ever visited one of
these it looks like you've ordered a copy of every attachment.
This addresses https://github.com/alphagov/govuk_publishing_components/pull/1375#discussion_r395325402, part of https://trello.com/c/UET4vx6k/1439-update-attachment-component-to-accommodate-new-attachment-design.
Remove ':visited' styling from 'Order a copy' link
It could otherwise be confusing that if you've ever visited one of
these it looks like you've ordered a copy of every attachment.
|--------|-----|
|<img width="685" alt="Screenshot 2020-04-03 at 11 21 10" src="https://user-images.githubusercontent.com/5111927/78350562-51264800-759d-11ea-843e-7246fd6263d3.png">|<img width="680" alt="Screenshot 2020-04-03 at 11 21 29" …
> Remove ':visited' styling from 'Order a copy' link

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
Includes:
* Update yellow hex code for Public Health England ([PR #1428](https://github.com/alphagov/govuk_publishing_components/pull/1428))
* Remove ':visited' styling from 'Order a copy' link ([PR #1427](https://github.com/alphagov/govuk_publishing_components/pull/1427))
> Version 21.38.3

- CHANGELOG.md
- app/views/govuk_publishing_components/components/_attachment.html.erb
- app/views/govuk_publishing_components/components/docs/attachment.yml
- spec/components/attachment_spec.rb
Attachment is used on admin-facing pages as well as user-facing
pages. Their requirements for a preview are somewhat different,
and having 'Order a copy' doesn't fit the design for them.
I've chosen to make this a boolean, following the style of the
'hide_opendocument_metadata' parameter, rather than inventing
some sort of 'admin context' which is open to misinterpretation.
Trello: https://trello.com/c/UET4vx6k/1439-update-attachment-component-to-accommodate-new-attachment-design
See https://govuk-publis-hide-order-mpkgzj.herokuapp.com/component-guide/attachment
> Add 'hide_order_copy_link' parameter to hide 'Order a copy'

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
* Add 'hide_order_copy_link' parameter to hide 'Order a copy' ([PR #1430](https://github.com/alphagov/govuk_publishing_components/pull/1430))
(Needed for Trello: https://trello.com/c/UET4vx6k/1439-update-attachment-component-to-accommodate-new-attachment-design)
> Bump to version 21.38.4

- app/controllers/govuk_publishing_components/component_guide_controller.rb
- spec/component_guide/component_index_spec.rb
Remove the underscore from the start of the sass filename in the 'suggested sass' feature.
Before:
```
@import 'govuk_publishing_components/components/_accordion';
@import 'govuk_publishing_components/components/_breadcrumbs';
```
After:
```
@import 'govuk_publishing_components/components/accordion';
@import 'govuk_publishing_components/components/breadcrumbs';
```
The suggested sass output worked fine for `collections` and `finder-frontend` but it turns out that `government-frontend` has stricter linting rules, and [insisted that the underscores be removed](https://github.com/alphagov/government-frontend/pull/1717).
Underscores aren't mandated, in fact [collections works fine](https://github.com/alphagov/collections/pull/1663) without them.
No change.
> Remove underscore from suggested sass output

- CHANGELOG.md
- app/views/govuk_publishing_components/component_guide/_application_stylesheet.html.erb
- app/views/govuk_publishing_components/component_guide/example.html.erb
- app/views/govuk_publishing_components/component_guide/preview.html.erb
- app/views/govuk_publishing_components/component_guide/show.html.erb
- app/views/layouts/govuk_publishing_components/application.html.erb
- spec/component_guide/component_example_spec.rb
Add the application stylesheet into the component guide if that component is from the application, not from the gem.
Work [previously done](https://github.com/alphagov/govuk_publishing_components/pull/1409) on the stylesheets used in the component guide is still not right, because excluding the application stylesheet from the component guide means that components from that application will appear unstyled.
None.
> Add application stylesheet where needed

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/_cookie-banner.scss
- app/views/govuk_publishing_components/components/_cookie_banner.html.erb
- app/views/govuk_publishing_components/components/docs/cookie_banner.yml
- spec/components/cookie_banner_spec.rb
Add cookie banner variation for services.
With this addition, we also enable custom title and confirmation messages for the cookie banner.
For services asking for cookies used for analytics only, we have a simpler approach (similarly with other GDS services, such as Notify, Wifi). We introduce this variation to be used across C19-related services.
[Preview example](https://govuk-publis-update-coo-zbw2lb.herokuapp.com/component-guide/cookie_banner/in_services_asking_for_analytics_only)
Co-Authored-By: @bilbof
[Trello card](https://trello.com/c/TObzdyej)
> Add cookie banner variation for services

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/lib/govspeak/youtube-link-enhancement.js
- app/views/govuk_publishing_components/components/docs/govspeak.yml
We need to be able to track when users are viewing the Livestream on GOV.UK.
We should use the YouTube API to send data to GA.
https://developers.google.com/youtube/iframe_api_reference#Retrieving_playlist_information
It will help us determine if it is a useful feature to include on GOV.UK.
Most commonly people use GTM to track videos on sites but we have security concerns about this.
Using the Youtube API we should be able to get around this but it is more complicated. It will give us more accurate information about viewing numbers and how users interact with the video, E.g do users pause it, start watching late and watch at increased speed? Currently, we are unable to do so and at best we can estimate the number of users but it is not accurate. For us to work this out we'd need this …
> Add Youtube Embed Analytics

- CHANGELOG.md
- app/views/govuk_publishing_components/components/_attachment_link.html.erb
- spec/components/attachment_link_spec.rb
We discovered a small bug in Content Publisher content where attachment links
that are rendered in Govspeak have a couple of instances of excess newline
characters being generated.
1. Newline between the last metadata attribute's (`.gem-c-attachment-link__attribute`) closing span tag, and the `gem-c-attachment-link` closing span tag.
e.g. `<span class=\"gem-c-attachment-link__attribute\">2 pages</span>)\n</span>`
2. Two newline characters after the attachment link text.
e.g. `<a class=\"govuk-link\" href=\"attachment\">Attachment</a>\n\n`
This fixes the ERB tags so that the extra newlines aren't generated for these
elements.
When importing documents in to Content Publisher from Whitehall, our integrity checks threw an error as there was a mismatch between the HTML generated by Govspeak in …
> Remove excess newlines for attachment link component

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/components/cookie-banner.js
This adds an event listener to all cookie banner hide buttons. Previously only the first hide button would hide the banner.
querySelectorAll returns a list of elements, whereas querySelector returns only the first element found. Since there are two hide links now we want to add an event listener to all of them.
https://govuk-publis-bilbof-fix-dk83zo.herokuapp.com/component-guide/cookie_banner/in_services_asking_for_analytics_only
https://trello.com/c/oT8l91fv/198-bugfix-hide-button-on-cookie-banner-component-should-hide-banner
> Fix hide link on cookie banner

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
* Adds tracking for youtube ([PR #1440](https://github.com/alphagov/govuk_publishing_components/pull/1438))
* Fix excess newlines for the Attachment Link component ([PR #1442](https://github.com/alphagov/govuk_publishing_components/pull/1442))
> Bump to 21.40.0

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/_cookie-banner.scss
Fix actions (buttons/link) alignment at various breakpoints on the 'services' variation of the cookie banner.
This variation of the component was borrowed from GovWifi which has a longer link text. This is a generic solution (not ideal) but fixes the issue regardless of the text size used on content.
No to seem like we're leading users towards one answer or another
<table>
</td></tr>
</table>
Fixes #1446
> Fix button alignment on cookie-banner

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
* Fix button alignment on cookie-banner ([PR #1450](https://github.com/alphagov/govuk_publishing_components/pull/1450))
> Release 21.41.1

- CHANGELOG.md
- lib/govuk_publishing_components/presenters/machine_readable/faq_page_schema.rb
- spec/lib/govuk_publishing_components/presenters/schema_org_spec.rb
Make FAQs look deeper in the page for questions
Make FAQs look deeper in the page for questions. Previously, it looked only at immediate children of the body for h2 elements, this looks recursively through the DOM
Some pages (eg https://www.gov.uk/government/publications/coronavirus-outbreak-faqs-what-you-can-and-cant-do/coronavirus-outbreak-faqs-what-you-can-and-cant-do) have the h2s deeper in the DOM
> Make FAQs look deeper in the page for questions

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
Just contains a tweak to the FAQPage schema to allow it to work with deeper document structures.
Works with https://github.com/alphagov/government-frontend/pull/1726
> Bump to 21.41.2

- app/views/govuk_publishing_components/components/docs/share_links.yml
Fix the broken 'Real world example' links in the share links component, by prefixing them with the https://www.gov.uk URL.
The real world example links are broken on https://components.publishing.service.gov.uk/component-guide/share_links.
> Update links to real world examples of share links

- app/views/layouts/govuk_publishing_components/application.html.erb
Load application styles after gem styles (same order as scripts and all assets in apps).
In frontend applications, styles/scripts from the gem are loaded first, then the application-level styles/scripts which sometimes depend or inherit from the ones in the gem. With this change, we apply the same order to the component guide so that components look and behave the same as they do when used in the application.
Some visual fixes for components presented in the guide across apps.
> Load application styles after gem styles in the component guide

- README.md
- docs/run-component-guide.md
- Try to clarify the scope of the project, relationship with GOV.UK Design System and browser support in the main [README.md](https://github.com/alphagov/govuk_publishing_components/blob/update-guidance/README.md)
- Replace bowl/vm/vagrant approach with [govuk-docker](https://github.com/alphagov/govuk-docker) in [run-component-guide.md](https://github.com/alphagov/govuk_publishing_components/blob/update-guidance/docs/run-component-guide.md)
To keep our docs tidy.
No visual change.
> Update main README and usage guidance

- CHANGELOG.md
- app/controllers/govuk_publishing_components/component_guide_controller.rb
- was previously looking for instances of component use only in the view, but government-frontend had one component call in a ruby helper, which was overlooked, resulting in an unstyled component
- now includes all ruby files in /app/ when looking for components
None
> Expand scope of suggested sass functionality

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/_title.scss
- app/views/govuk_publishing_components/components/_title.html.erb
- spec/components/title_spec.rb
- use span instead of p
- use govuk-caption-xl from govuk-frontend instead of custom style that did the same thing
- change brings this more in line with govuk-frontend and restores 5px of spacing between context and title
Before:
After:
Design system doc: https://design-system.service.gov.uk/styles/typography/#headings
Trello card: https://trello.com/c/z4DVsyk0/200-make-hub-page-breadcrumbs-more-explicit
> Change title component context

- app/views/govuk_publishing_components/components/docs/character_count.yml
Add documentation for how to add an ID to the textarea in the character count component documentation.
Because I spent at least an hour this morning investigating why this apparently wasn't working and possibly causing a bug, only to discover that I'd not indented the option properly 🤕 
None.
> Document ID option for character count

- CHANGELOG.md
- app/views/govuk_publishing_components/components/_title.html.erb
Inverse option for title component was broken by (cough my) recent change. This fixes it, by restoring the gem specific class that was already styled to inherit the font colour.
Before:
After:
> Fix inverse option for title component context

- CHANGELOG.md
- app/views/govuk_publishing_components/components/_accordion.html.erb
- app/views/govuk_publishing_components/components/docs/accordion.yml
- spec/components/accordion_spec.rb
Adds an option to set the margin bottom for the accordion component. Defaults to 30px as previous behaviour.
We need to change the bottom margin of the component in collections.
> Add custom margin option to accordion component

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/_accordion.scss
Our accordion component is unintentionally deviating from govuk-frontend, resulting in a slightly smaller touch area on mobile devices.
- govuk-frontend component does not appear to explicitly set the line height for the h2 in an accordion
- inside some applications h2 elements have some default styling which was subtly reducing the line height
- end result was on mobile, unopened accordions were 54px tall, not 60px as intended
- this fixes this by explicitly defining the h2 font on mobile
Before | After
----- | -----
> Explicitly set accordion heading line height

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
* Add custom margin option to accordion component ([PR #1470](https://github.com/alphagov/govuk_publishing_components/pull/1470))
* Explicitly set accordion heading line height ([PR #1386](https://github.com/alphagov/govuk_publishing_components/pull/1386))
> Version 21.42.0

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/_button.scss
- app/views/govuk_publishing_components/components/_button.html.erb
- app/views/govuk_publishing_components/components/docs/button.yml
- lib/govuk_publishing_components/presenters/button_helper.rb
- spec/components/all_components_spec.rb
- spec/components/button_spec.rb
Apply bottom margin to the info text element instead of the button element when both `margin_bottom` and `info_text` attributes are set.
To avoid having a gap between the button and the info text.
Found while [dropping the wrapper layout in frontend](https://github.com/alphagov/frontend/pull/2154).
Before
After
> Fix margin on buttons with info text

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/_step-by-step-nav-header.scss
- app/views/govuk_publishing_components/components/docs/step_by_step_nav_header.yml
Removes top border
Changes border bottom colour to blue
Adds margin top of 15px
---
We know that 70% of traffic to coronavirus content is direct to content rather than via landing page. We want to provide users with a clear route to the landing page, and to useful related content. This is to help them discover support that they might not already be aware of or think to search for.
We need to adapt the step by step superbreadcrumb component to be able to be used in this case.
The feature will provide users with a link to the landing page or hub that the content is tagged to using the taxonomy, using the 'superbreadcrumb'.
It will also provide users with a set of related links which will be drawn from the curated content associated with the lowest level topic that the content item is tagged …
> Update step by step header component style

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
Includes:
* Fix margin on buttons with info text ([PR #1474](https://github.com/alphagov/govuk_publishing_components/pull/1474))
* Update step by step header component style ([PR #1476](https://github.com/alphagov/govuk_publishing_components/pull/1476))
> Bump version to 21.43.0

- CHANGELOG.md
- app/views/govuk_publishing_components/components/_summary_list.html.erb
- app/views/govuk_publishing_components/components/docs/summary_list.yml
- spec/components/summary_list_spec.rb
- allows 'change' and 'delete' links in the component to be passed custom text, need to be able to do this to handle translations
- already an option to set the text for the main edit link, so this is a natural extension
We're using the component in simple smart answers and need to be able to change the link text to Welsh.
None.
> Allow summary list custom link text

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/_input.scss
Add missing legacy colour for `light-grey` – missed in [#1481](https://github.com/alphagov/govuk_publishing_components/pull/1481/files#diff-57a28dc54e1ce322564d3c1e15811c5fR37).
It crashes apps in compatibility mode: _jenkins builds for the latest components gem are currently failing (at least for smart answers)_ as reported by @andysellick
> Fix legacy colour on input component

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/components/checkboxes.js
- app/views/govuk_publishing_components/components/_checkboxes.html.erb
- app/views/govuk_publishing_components/components/docs/checkboxes.yml
- lib/govuk_publishing_components/presenters/checkboxes_helper.rb
- spec/components/checkboxes_spec.rb
- spec/javascripts/components/checkboxes-spec.js
Allow a checkbox option to become exclusive, as follows:
- when the exclusive item is checked all non-exclusive items are unchecked
- when a non-exclusive item is checked the exclusive item is unchecked.
This behavior should be doubled by similar checks on the backend to cover the cases when JavaScript is disabled.
- Required in [coronavirus-business-volunteer-form](https://github.com/alphagov/govuk-coronavirus-business-volunteer-form) and [coronavirus-find-support](https://github.com/alphagov/govuk-coronavirus-find-support); follow-up PRs will be raised in both repos
- Clears technical debt and fixes #1456 (by covering the [`toggleCheckboxes`](https://github.com/alphagov/smart-answers/blob/master/app/assets/javascripts/helpers.js#L29-L42) functionality in the checkboxes component; a …
> Add exclusive option to checkboxes component

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/helpers/_brand-colours.scss
Remove the PHE brand colour from our brand colours sass, originally added in https://github.com/alphagov/govuk_publishing_components/pull/1396
- not being used, was originally used with the heading component on the coronavirus landing page, but we're not using it that way anymore
- colour is going to change again anyway
None.
> Remove PHE brand colour

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/govspeak/_footnotes.scss
- app/assets/stylesheets/govuk_publishing_components/components/govspeak/_typography.scss
- app/views/govuk_publishing_components/components/docs/govspeak.yml
Prevent govspeak links from breaking the layout.
We are not always in control of how links are being generated, and when not using dash-separated paths in the URL, links in govspeak break the layout by overflowing. This can become more problematic for users on narrow viewports/mobile devices where an accidental drag can leave them with a blank screen.
Application example using `government-frontend` and links in footnotes
<table>
</td></tr>
</table>
Mobile example using Chrome on Android and Safari on iOS
<table>
</td></tr>
</td></tr>
</table>
`overflow-wrap` is widely supported …
> Prevent govspeak links from breaking the layout

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/govspeak/_tables.scss
- app/views/govuk_publishing_components/components/docs/govspeak.yml
Scroll columns within the table element instead of overflowing the page – which would still require horizontal scrolling.
To prevent tables from breaking the page layout
There are various ways to improve tables on small viewports (some of which are tracked in the backlog – https://github.com/alphagov/govuk-design-system-backlog/issues/61), but all of them require and rely on a better markup for tables – which is not easy to do for all existing content in GOV.UK – with this in mind, I propose this intermediate solution which only addresses the overflowing problem by scoping the horizontal scrolling to the table element.
[Preview govspeak table change](https://govuk-publis-prevent-ta-c0cmde.herokuapp.com/component-guide/govspeak/tables)
Initial state
<table> …
> Prevent govspeak tables from breaking the layout

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/_checkboxes.scss
- app/views/govuk_publishing_components/components/_checkboxes.html.erb
- app/views/govuk_publishing_components/components/docs/checkboxes.yml
- config/locales/en.yml
- spec/components/checkboxes_spec.rb
Allow 'or' divider on checkboxes (similarly with the radio component).
To be used in a pair with the exclusive option.
Example of a page using this pattern: https://coronavirus-business-volunteers.service.gov.uk/expert-advice-type where checkboxes with an 'or' option are not part of the same fieldset. This makes it harder for screen readers to use those forms.
<table>
<tr><th>Without</th><th>With</th></tr>
</td></tr>
</table>
[Trello card](https://trello.com/c/kJe25doD)
> Add 'or' divider to checkboxes component

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
* Prevent govspeak tables from breaking the layout ([PR #1493](https://github.com/alphagov/govuk_publishing_components/pull/1493))
* Prevent govspeak links from breaking the layout ([PR #1492](https://github.com/alphagov/govuk_publishing_components/pull/1492))
* Remove PHE brand colour ([PR #1489](https://github.com/alphagov/govuk_publishing_components/pull/1489))
* Add 'or' divider to checkboxes component ([PR #1488](https://github.com/alphagov/govuk_publishing_components/pull/1488))
* Fix legacy colour on input component ([PR #1487](https://github.com/alphagov/govuk_publishing_components/pull/1487))
* Add `exclusive` option to checkboxes component ([PR #1478](https://github.com/alphagov/govuk_publishing_components/pull/1478))
> Release 21.46.0

- CHANGELOG.md
- app/views/govuk_publishing_components/components/_radio.html.erb
- app/views/govuk_publishing_components/components/docs/radio.yml
- spec/components/radio_spec.rb
Allow `id` to be specified for the outermost element generated by the checkboxes component.
To be able to refer an instance of a checkboxes component. A small step in aligning the checkboxes and radio components.
Required in [govuk-coronavirus-business-volunteer-form as per comment](https://github.com/alphagov/govuk-coronavirus-business-volunteer-form/pull/292#discussion_r423794164)
> Add `id` to checkboxes component

- app/assets/stylesheets/govuk_publishing_components/components/_action-link.scss
- line appears between link text and subtext on desktop, adjust slightly so it is a little shorter and more in line with height of text
Before:
After:
> Tweak size of action link subtext divider

- CHANGELOG.md
- app/views/govuk_publishing_components/components/_action_link.html.erb
- app/views/govuk_publishing_components/components/_button.html.erb
- app/views/govuk_publishing_components/components/docs/action_link.yml
- lib/govuk_publishing_components/presenters/button_helper.rb
- lib/govuk_publishing_components/presenters/shared_helper.rb
- spec/components/action_link_spec.rb
- spec/components/button_spec.rb
- spec/lib/govuk_publishing_components/components/shared_helper_spec.rb
Move the code for passing classes to the button component into the shared helper. This code only accepts classes passed to the component if they are prefixed with `js-`. 
Update the button component to use the shared helper for the classes option, and add the classes option into the action link component.
Moving the code for handling passed classes from the button component to the shared helper allows more than one component to use it in a consistent way, and this is now needed for the action link component.
None.
> Expand js classes code

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
* Expand js classes code ([PR #1513](https://github.com/alphagov/govuk_publishing_components/pull/1513))
* Tweak size of action link subtext divider ([PR #1512](https://github.com/alphagov/govuk_publishing_components/pull/1512))
> Version 21.48.0

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
* Add priority breadcrumb ([PR #1501] (https://github.com/alphagov/govuk_publishing_components/pull/1501))
> Version 21.49.0

- CHANGELOG.md
- app/views/govuk_publishing_components/components/_select.html.erb
- app/views/govuk_publishing_components/components/docs/select.yml
- spec/components/select_spec.rb
Add `is_page_heading` and H1 tag as appropriate to select component.  Similar in approach to that taken with the `radio` element.
Allows pages who dominant feature is a select element not to have repetition the page title and the select element label.
No visual changes between this and a `select` that has an `xl` heading.  
https://govuk-publis-add-h1-to--ywnvox.herokuapp.com/component-guide/select/with_page_heading
Co-Authored by Jonathan Hallam <jonathan.hallam@digital.cabinet-office.gov.uk>
> Add is_page_heading to select

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/_action-link.scss
- app/views/govuk_publishing_components/components/_action_link.html.erb
Make some slight visual fixes to the action link component, specifically:
- fix vertical centering for action links with subtext on mobile
- adjust position of arrow for simple and dark options
Because:
- vertical centering was broken. The fix does involve adding yet another element (but only if subtext is present) but I think it's the only way (happy to be corrected though)
- the arrows for simple and dark weren't quite lined up right with the text. This is actually a tricky one, for some reason these arrows (unlike all the other arrows) are aligned to the top of the component, rather than centrally. So they still don't look great if the link text wraps onto two lines. But at least it looks slightly better now in one situation.
Vertical centering on mobile with subtext before (I've …
> Tweak action link

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/all_components.js
- app/assets/javascripts/govuk_publishing_components/components/accordion.js
- app/assets/javascripts/govuk_publishing_components/components/button.js
- app/assets/javascripts/govuk_publishing_components/components/character-count.js
- app/assets/javascripts/govuk_publishing_components/components/checkboxes.js
- app/assets/javascripts/govuk_publishing_components/components/header.js
- app/assets/javascripts/govuk_publishing_components/components/radio.js
- app/assets/javascripts/govuk_publishing_components/components/tabs.js
- app/assets/javascripts/govuk_publishing_components/lib.js
- app/assets/javascripts/govuk_publishing_components/modules.js
- app/controllers/govuk_publishing_components/component_guide_controller.rb
- app/views/govuk_publishing_components/component_guide/index.html.erb
- docs/install-and-use.md
- spec/component_guide/component_index_spec.rb
- spec/javascripts/govuk_publishing_components/modules.spec.js
Allow individual, component-based, JavaScript imports.
Follow up on #1159 to complete [RFC 108](https://github.com/alphagov/govuk-rfcs/pull/110)
To avoid excessive code from being imported in the application.
~~This PR will remain draft until tested with applications consuming the gem but comments/reviews are welcome.~~
Tested with:
For applications dependent on `static`/`slimmer`, `static` requires to be updated first to use the modules system from this gem instead of `govuk_frontend_toolkit`.
JavaScript modules in GOV.UK are actually design patterns for keeping pieces of code independent of other components. We currently have 3 design patterns for writing JavaScript in GOV.UK applications.
Mostly found in legacy scripts, either migrated from Toolkit, Elements, or written in the same …
> Allow individual script imports

- CHANGELOG.md
- app/assets/stylesheets/component_guide/application.scss
- app/assets/stylesheets/govuk_publishing_components/_all_components.scss
- app/assets/stylesheets/govuk_publishing_components/components/helpers/_brand-colours.scss
Primarily this changes the _all_components helper file to use the same support scripts as we recommend users use to import individual components.
Aside from that I then removed a number of @import calls that were superfluous
Primarily I went in looking to see if there was much low hanging fruit available where we were making unnecessary @import calls, there wasn't actually too much of that now that we support both individual components and all component importing. However I did find a few of those and, given they can add up to steep performance penalties, felt they were best removed.
I also felt it was more prudent to do the same support set-up in the _all_components file as we recommend users take in individual components. This seemed to reduce the risk that these differ in …
> Reduce re-importing of SCSS files

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
* Change `_all_components.scss` to use dependencies from support stylesheets  ([PR #1502](https://github.com/alphagov/govuk_publishing_components/pull/1502))
* Allow individual JavaScript imports ([PR #1472](https://github.com/alphagov/govuk_publishing_components/pull/1472))
To import individual components refer to ['Include the assets section in docs'](https://github.com/alphagov/govuk_publishing_components/blob/master/docs/install-and-use.md) and the 'Suggested imports for this application' section available on `/component-guide` in your application.
> Release 21.51.0

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/_input.scss
- app/views/govuk_publishing_components/components/_input.html.erb
- app/views/govuk_publishing_components/components/docs/input.yml
- spec/components/input_spec.rb
Add a prefix option to the input component
Users were entering data which was unusable, i.e entering text when we desired numbers. This change will help us indicate to users how we would like them to input data.
**BEFORE**
**AFTER**
[Trello](https://trello.com/c/GCGNaCSH/367-add-prefix-to-input-fields-on-product-details-question)
> Add prefix option to input component

- docs/install-and-use.md
This should help prevent folks inadvertently making the /component-guide available in production.
https://trello.com/c/6QWT52eB/496-prevent-production-apps-rendering-component-guide?menu=filter&filter=label:Tech
> Update install instructions

- spec/features/contextual_navigation_spec.rb
- spec/features/step_nav_helper_spec.rb
gds-api-adapters renamed the stubs from `content_store_has_item` to `stub_content_store_has_item`
> Resolve stub deprecation warnings

- CHANGELOG.md
- lib/govuk_publishing_components/presenters/machine_readable/faq_page_schema.rb
- spec/lib/govuk_publishing_components/presenters/schema_org_spec.rb
Removes the recursive bit of the FAQSchema presenter which is used to extract questions and answers from the HTML publication format.
I'm intending to do this more simply and specifically for HTML publications within government-frontend. This code is quite hard to debug without context, and it's not working quite right at the moment.
Note that this is not a breaking change - it still resolves a valid schema on HTML publications, but they are a bit less useful.
This reverts commit f0e470a27660e1d0bcfbd318e4957ba983191095.
> Undo recursive FAQPage presenter

- CHANGELOG.md
- lib/govuk_publishing_components/presenters/content_breadcrumbs_based_on_priority.rb
- spec/lib/govuk_publishing_components/presenters/content_breadcrumbs_based_on_priority_spec.rb
Allow arbitrary depth in taxonomy tagging
This now assembles all the taxons that content is tagged to, whether directly, or via taxonomy inheritance.  It then checks to see if any of those are priority taxons and judges from that whether to show the super-breadcrumb
At the moment, we're not checking the whole taxon tree to see whether a piece of content is tagged to a priority taxon.
> Allow arbitrary depth in taxonomy tagging

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/govspeak/_steps.scss
Previously these sequential bullet images stopped displaying after point
14. This ups the limit to 30 as it seems a reasonable limit.
Zendesk ticket: https://govuk.zendesk.com/agent/tickets/4089053
> Increase limit for steps bullet point images

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
Add breadcrumbs from parent for html documents ([PR #1526] (https://github.com/alphagov/govuk_publishing_components/pull/1526)
> Version 21.53.0

- CHANGELOG.md
- app/views/govuk_publishing_components/components/_step_by_step_nav_header.html.erb
- app/views/govuk_publishing_components/components/docs/step_by_step_nav_header.yml
- spec/components/step_by_step_nav_header_spec.rb
We don't currently track users who click on the superbread crumbs (on the business & education hubs). As this feature is going to be rolled out with the new taxonomy it would be good to add tracking to understand if it is helping users navigate back through the pages.
Event category: breadcrumbClicked
Event action: superBreadcrumb
Event label: page path link (to hub page)
Its done when: When a users clicks on a super bread crumb an event is triggered in GA and we can track the page they were on and the page they went to.
https://trello.com/c/G2iuimyb/283-add-analytics-tracking-to-super-breadcrumb
> Modify Step nav header component to support custom tracking

- lib/govuk_publishing_components/presenters/content_breadcrumbs_based_on_priority.rb
- spec/lib/govuk_publishing_components/presenters/content_breadcrumbs_based_on_priority_spec.rb
We don't currently track users who click on the superbread crumbs (on the business & education hubs). As this feature is going to be rolled out with the new taxonomy it would be good to add tracking to understand if it is helping users navigate back through the pages.
Event category: breadcrumbClicked
Event action: superBreadcrumb
Event label: page path link (to hub page)
Its done when: When a users clicks on a super bread crumb an event is triggered in GA and we can track the page they were on and the page they went to.
https://trello.com/c/G2iuimyb/283-add-analytics-tracking-to-super-breadcrumb
> Adds tracking for super breadcrumbs

- lib/govuk_publishing_components/presenters/breadcrumb_selector.rb
- spec/features/contextual_navigation_spec.rb
The step by step header expects a hash, whereas the other breadcrumb component expects an array of items.
Resolves: https://sentry.io/organizations/govuk/issues/1697331489/?project=202226&query=is%3Aunresolved
https://trello.com/c/dY8wHgpu/280-adding-breadcrumbs-and-superbreadcrumbs-to-all-html-publications
> Fix html publications tagged to step by steps

- CHANGELOG.md
- app/views/govuk_publishing_components/components/_step_by_step_nav_header.html.erb
- app/views/govuk_publishing_components/components/docs/step_by_step_nav_header.yml
- spec/components/step_by_step_nav_header_spec.rb
Uses the shared helper to add a `margin_bottom` option to the step by step navigation header component.
We need it for [this page](https://www.gov.uk/government/publications/coronavirus-outbreak-faqs-what-you-can-and-cant-do/coronavirus-outbreak-faqs-what-you-can-and-cant-do) where it's colliding with the organisation logo.
Trello card: https://trello.com/c/dY8wHgpu/280-adding-breadcrumbs-and-superbreadcrumbs-to-all-html-publications
> Add margin bottom option to step nav header component

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
Includes:
* Modify step nav header component to support custom tracking ([PR #1533](https://github.com/alphagov/govuk_publishing_components/pull/1533))
* Adds tracking for super breadcrumbs ([PR #1542](https://github.com/alphagov/govuk_publishing_components/pull/1542))
* Add margin bottom option to step nav header component ([PR #1544](https://github.com/alphagov/govuk_publishing_components/pull/1544))
* Bugfix to step nav header on HTML publications ([PR #1545](https://github.com/alphagov/govuk_publishing_components/pull/1545))
> Release 21.54.0 (bump minor version)

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
* Add new options to action link component ([PR #1551](https://github.com/alphagov/govuk_publishing_components/pull/1551))
* Bump govuk-frontend from 3.6.0 to 3.7.0 ([PR #1549](https://github.com/alphagov/govuk_publishing_components/pull/1549))
* Fix FAQ Schemas for html publications ([PR #1543](https://github.com/alphagov/govuk_publishing_components/pull/1543)
> Version 21.55.0

- CHANGELOG.md
- app/controllers/govuk_publishing_components/component_guide_controller.rb
- spec/component_guide/component_index_spec.rb
- spec/dummy/app/views/layouts/application.html.erb
- the suggested sass code was looking to see if any components contained other components, but stopped at that first level
- the feedback component contains several partials (identified and correctly ignored by the original code) but they include other components
- this change keeps burrowing down through partials/subcomponents until it can't find anything else
- updated the dummy app to include the feedback component so that this can be tested, which works because the dummy app doesn't include button but feedback does
- however I'm not sure how to do a concrete test for this i.e. if button was already in the dummy app and this code didn't work properly, the test would still pass
Noticed in the upgrade to individual components in `service-manual-frontend` that it hadn't included the input …
> Find components within components

- CHANGELOG.md
- lib/govuk_publishing_components/presenters/breadcrumb_selector.rb
- spec/features/contextual_navigation_spec.rb
Reverse order of top three options in breadcrumb selector, so that content_tagged_to_a_finder comes first, step by step second, priority 3rd
Superbreadcrumb (priority option) is not always the correct option. 
https://trello.com/c/hxOu0Mc9/339-reorder-the-breadcrumb-so-superbreadcrumb-not-top-option
> 339 - Reorder the breadcrumb so superbreadcrumb not top option

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
Includes:
- Reorder the breadcrumb so superbreadcrumb not top option ([PR #1556](https://github.com/alphagov/govuk_publishing_components/pull/1556))
https://trello.com/c/hxOu0Mc9/339-reorder-the-breadcrumb-so-superbreadcrumb-not-top-option
> Bump to version 21.55.2

- .dependabot/config.yml
Currently Dependabot is enabled for all Gems and packages on this repo. We'd like to trial limiting the number of PRs opened by Dependabot to libraries that we care about explicitly.
See https://github.com/alphagov/content-publisher/pull/2062 for more context on this configuration file (and a similar config file for Content Publisher).
There's a few reasons I've picked this repo to try out this config (as well as the existing configuration in Content Publisher).
- It's a Gem, allowing us to learn more about if there's anything special about Gems which means going down this route would be problematic.
- It includes a framework library (`govuk-frontend`) which we'd want to have enabled for this repo, but perhaps not for any others.
- It allows us to test the idea of having a global config …
> Add explicit config for Dependabot

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/_feedback.scss
**Don't merge this until https://github.com/alphagov/frontend/pull/2387 is merged**
Remove the spacing around the form in the feedback component when the component is expanded.
The spacing is largely unnecessary and appears to be in place for one edge case only, the homepage, which has been [fixed in a separate PR](https://github.com/alphagov/frontend/pull/2387).
Here's the homepage at the moment when feedback is expanded:
Here's the fix:
> Remove unnecessary margin around expanded feedback component

- CHANGELOG.md
- app/controllers/govuk_publishing_components/component_guide_controller.rb
- spec/dummy/app/views/layouts/application.html.erb
Modifies the logic behind the suggested imports functionality of the component guide to be more specific when dealing with includes that look like components, but aren't.
This is causing a 500 error in content-publisher, see https://github.com/alphagov/govuk_publishing_components/issues/1570
None.
> Rework suggested imports functionality

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
* Rework suggested imports functionality ([PR #1571](https://github.com/alphagov/govuk_publishing_components/pull/1571))
* Remove unnecessary margin around expanded feedback component ([PR #1547](https://github.com/alphagov/govuk_publishing_components/pull/1547))
> Version 21.55.4

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/component_support.scss
- app/assets/stylesheets/govuk_publishing_components/components/_summary-list.scss
- app/assets/stylesheets/govuk_publishing_components/components/helpers/_link.scss
- app/views/govuk_publishing_components/components/_summary_list.html.erb
- app/views/govuk_publishing_components/components/docs/summary_list.yml
- config/locales/en.yml
- spec/components/summary_list_spec.rb
Update the summary-list component with the following to support the following features:
- allow delete action at group level
- render delete actions as destructive links (in red)
- allow custom heading level and size on section titles
Required by design for the [business-volunteer-form](https://github.com/alphagov/govuk-coronavirus-business-volunteer-form)
<table>
</td></tr>
</td></tr>
</table>
[Trello card](https://trello.com/c/Bszitcav/601-update-summary-list-component-to-allow-delete-action-at-the-group-level)
> Update summary list component to allow delete action at the group level and custom heading levels

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
* Update summary list component to allow delete action at the group level and custom heading levels ([PR #1574](https://github.com/alphagov/govuk_publishing_components/pull/1574))
> Release 21.56.0

- CHANGELOG.md
- app/views/govuk_publishing_components/components/_contextual_breadcrumbs.html.erb
- lib/govuk_publishing_components/presenters/breadcrumb_selector.rb
- spec/features/contextual_navigation_spec.rb
We want to show breadcrumbs alongside superbreadcrumbs where we're using them. Superbreadcrumbs should appear below breadcrumbs. This is how they worked when originally implemented on step by steps.
Also refactor of `BreadcrumbSelector` to return an instance with public methods rather than a hash.
We want breadcrumbs to be a consistent pattern on every page of the site. But keep the benefits of the superbreadcrumbs on coronavirus content and step by steps.
> 369 Show breadcrumbs alongside superbreadcrumbs everywhere they appear

- CHANGELOG.md
- lib/govuk_publishing_components/presenters/content_breadcrumbs_based_on_priority.rb
- spec/lib/govuk_publishing_components/presenters/content_breadcrumbs_based_on_priority_spec.rb
Adds the worker support hub page to the priority breadcrumb list
> 366 Add worker support hub page to the priority breadcrumb list

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
* Replace bodged parent breadcrumbs with specialist topic breadcrumbs ([PR #1565](https://github.com/alphagov/govuk_publishing_components/pull/1565))
* Add worker support hub page to the priority breadcrumb list ([PR #1579](https://github.com/alphagov/govuk_publishing_components/pull/1579))
> Release 21.56.1

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/_input.scss
- app/views/govuk_publishing_components/components/_input.html.erb
- app/views/govuk_publishing_components/components/docs/input.yml
Fix the layout issues on input with prefix/suffix after adding the [prefix feature](#1509):
- on mobile devices or when the input was set to full-width (didn't have a specified width) the suffix content was overflowing on the majority of browsers
- on Firefox, the component was overflowing on narrow screens and mobile devices (as Firefox requires a `min-width` to shrink to)
To ensure cross-browser and cross-device compatibility.
<table>
Chrome 83 – full-width input
</td></tr>
</table>
Firefox 77 – narrow screen
<table>
</td></tr>
</table>
Chrome 83
Firefox 77
Edge 83
IE11
IE10
IE9
IE8
[Trello …
> Fix layout on input with prefix/suffix

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/_cookie-banner.scss
- app/views/govuk_publishing_components/components/_cookie_banner.html.erb
- spec/components/cookie_banner_spec.rb
When JavaScript is disabled we should hide the cookie banner user in services as its sole purpose is to let the user accept/decline cookies used for analytics purposes, which are only being done if JavaScript is enabled.
To avoid confusing users when JavaScript is disabled
Changes to the cookie banner variation used in services (with `services_cookies` set, such as Covid-19 services).
No changes to the cookie banner used on GOV.UK
<table>
<tr><th>JavaScript enabled</th><th>JavaScript disabled</th></tr>
</td></tr>
</table>
> Hide services cookie banner when JavaScript is disabled

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/_action-link.scss
- app/views/govuk_publishing_components/components/_action_link.html.erb
- app/views/govuk_publishing_components/components/docs/action_link.yml
- spec/components/action_link_spec.rb
Extend action link component with a small icon variant.
There is a requirement for a small icon version of the default (dark arrow on yellow background) action link component.
The design has been tweaked in order to have two such links on the Coronavirus landing page header.
https://trello.com/c/oB87oGqD
> Extend action link component with a small icon variant

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/components/print-link.js
- app/assets/stylesheets/govuk_publishing_components/_all_components.scss
- app/assets/stylesheets/govuk_publishing_components/components/_print-link.scss
- app/views/govuk_publishing_components/components/_print_link.html.erb
- app/views/govuk_publishing_components/components/docs/print_link.yml
- config/locales/en.yml
- spec/components/print_link_spec.rb
- spec/javascripts/components/print-link-spec.js
This component adds a link that includes a print icon and can be used to help users print a page.
This component renders two different outputs depending on whether a `href` is specified:
By default, when no `href` is given, the component renders as a button and triggers a print action via JavaScript. In this case the component is hidden in environments where JavaScript is disabled and can be used as a progressive enhancement.
When a `href` is specified the component renders as an anchor tag and navigates to that `href` without JavaScript, suitable for applications which have paths that trigger a print event on load. (for application such as Government Frontend)
This pattern was originally implemented in the Government Frontend application, however we'd like to re-use this component in …
> Add print link component

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
Bump gem to version 21.57.0
Includes 
* Hide services cookie banner when JavaScript is disabled ([PR #1586](https://github.com/alphagov/govuk_publishing_components/pull/1586))
* Improve print styles for govspeak info, help and call to action callouts ([PR #1588](https://github.com/alphagov/govuk_publishing_components/pull/1588) )
* Extend action link component with a small icon variant ([PR #1590](https://github.com/alphagov/govuk_publishing_components/pull/1590) )
> Version 21.57.0

- CHANGELOG.md
- Gemfile.lock
- app/assets/stylesheets/govuk_publishing_components/components/_action-link.scss
- lib/govuk_publishing_components/version.rb
Add 5px to increase space between arrow and text in the small/dark icon versions of the arrow link component, as requested by Mia
Before (left) vs after (right)
https://trello.com/c/oB87oGqD
> Minor adjustment to action link icon spacing

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/_search.scss
- when the page is linearized ([web developer toolbar](https://chrispederick.com/work/web-developer/), miscellaneous, linearize page) the absolutely positioned label for the search input (which is pretending to be placeholder text) appears before the search input and is unreadable on a blue background
- this fixes this by adding a white background to the label, so the appearance is unchanged in the normal view but readable when linearized
As raised by @selfthinker 
Before (normal view)
Before (linearized)
After (linearized)
After when focussed (linearized)
After with some custom colours applied
> Fix search component label accessibility

- Rakefile
Adds rubocop linting to the default rake task.
I keep getting caught out by linting errors being thrown in Jenkins because I forget to run them locally as linting isn't part of the default `bundle exec rake` task. 
Adding the linting to the default will make it easier to remember and (hopefully) will cause more linting errors to be caught locally rather than in Jenkins.
None.
> Add linting to default rake task

- app/views/govuk_publishing_components/component_guide/index.html.erb
Update the links in the component guide main page to provide clearer guidance for developers. Specifically:
1. Remove most of the existing text/links to make the remaining stuff stand out more.
1. Add link to how to release a new version of the gem.
1. Keep the link to all component documentation.
1. Add a section at the bottom to act as a 'what now?' if developers can't find a component they need.
1. The existing guidance is too long and isn't answering the questions developers have.
1. We have guidance for versioning the gem but developers aren't finding it. I've seen multiple PRs in the last few weeks where versioning has been done incorrectly. I've also been recently asked by several developers how to version the gem.
1. We should still link to _some_ documentation.
1. I also keep …
> Provide more guidance for developers

- Gemfile.lock
- govuk_publishing_components.gemspec
- spec/javascripts/govuk_publishing_components/lib/cookie-functions-spec.js
- spec/javascripts/support/jasmine_helper.rb
- spec/javascripts/support/jasmine_selenium_runner.yml
Replace PhantomJS with Chrome for the JavaScript Jasmine tests .
Because [PhantomJS is no longer in development](https://github.com/ariya/phantomjs/issues/15344) and is out of date. This is impacting our ability to remove jQuery as a dependency because PhantomJS is throwing errors for things that [our browser support matrix](https://www.gov.uk/service-manual/technology/designing-for-different-browsers-and-devices) supports, such as `addEventListener` or `NodeList.forEach()`
None.
> Set up Chrome for JavaScript tests

- package-lock.json
Boring update - I ran `npm audit fix` and this is the result.
Running `npm audit` gives you a list of any npm dependencies that it flags as security risks - and running `npm audit fix` automatically updates them where it can. (I think it updates to the best version it can without upgrading to a major version.)
This also flags other security risks but they're now a version or two ahead (for example, jQuery), or can't be updated - and won't be automatically updated.
Because security risks are bad.
None.
> Update dependencies with `npm audit --fix`

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/_list.scss
- app/views/govuk_publishing_components/components/_list.html.erb
- app/views/govuk_publishing_components/components/docs/list.yml
- spec/components/list_spec.rb
This is a direct port of the list component from GOV.UK Frontend / Design System with no extra styles added.
Unordered lists were being hardcoded with a `each` loop in the templates. It seems a more elegant solution to have a component that we can pass an array of strings to display.
No before, as this is a new addition:
> Add list component

- app/controllers/govuk_publishing_components/component_guide_controller.rb
Updating the `Suggested imports for this application` functionality to include looking in the `/lib` directory for component instances in ruby.
I was just converting `smart-answers` to use [individual component assets](https://github.com/alphagov/smart-answers/pull/4659) and noticed that bits of it were unstyled, because govspeak is included in files inside `/lib`. Haven't seen this before, smart-answers might be unique in this, but the change is still worth doing.
None.
> Expand suggested sass ruby coverage

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
Release 21.58.0
* Fix search component label accessibility ([PR #1594](https://github.com/alphagov/govuk_publishing_components/pull/1594))
* Add list component ([PR #1595](https://github.com/alphagov/govuk_publishing_components/pull/1595))
> Version 21.58.0

- CHANGELOG.md
- app/controllers/govuk_publishing_components/audit_controller.rb
- app/models/govuk_publishing_components/audit_applications.rb
- app/models/govuk_publishing_components/audit_comparer.rb
- app/models/govuk_publishing_components/audit_components.rb
- app/views/govuk_publishing_components/audit/show.html.erb
- app/views/govuk_publishing_components/component_guide/index.html.erb
- config/routes.rb
- spec/component_guide/audit_applications_spec.rb
- spec/component_guide/audit_comparer_spec.rb
- spec/component_guide/audit_components_spec.rb
- spec/component_guide/component_audit_spec.rb
- spec/dummy_gem/app/assets/javascripts/govuk_publishing_components/components/test-component.js
- spec/dummy_gem/app/assets/stylesheets/govuk_publishing_components/components/_test-component.scss
- spec/dummy_gem/app/assets/stylesheets/govuk_publishing_components/components/print/_test-component.scss
- spec/dummy_gem/app/views/govuk_publishing_components/components/_test-component-containing-other-component.html.erb
- spec/dummy_gem/app/views/govuk_publishing_components/components/_test-component.html.erb
- spec/dummy_gem/spec/components/test_component.rb
- spec/dummy_gem/spec/javascripts/components/test-component-spec.js
Add some auditing to the component guide, to allow us to understand the components, how they are structured and how they are used.
This code is based on the code from a prototype auditor I built recently - thanks to @injms for the suggestion to add it to the component guide instead of having a command line tool.
As we move into a world of individual component asset inclusion on GOV.UK (and potentially continuous deployment) I'd like to have some confidence that:
- everything is still styled after changes are made
- redundant assets are removed if a component is no longer in use
We also should be making sure that our components are consistent and don't duplicate effort, so this work ties into a wider need to have some kind of [component …
> Add component auditing

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/components/details.js
Fixes a bug introduced in #1597 by adding a check to make sure that element is present before adding an event listener to it.
Before we add an event listener to the details component we should check that the selector has actually found something - or things go wrong.
Unlike `addEventListener`, jQuery's `.on('click', function() { ... })` silently handles nothing being found. This is because the jQuery selector _always_ returns an iterable jQuery object.
The `.on()` listener loops through the jQuery object given to it - which means that if the object has a length of zero then nothing happens and nothing fails.
Using `querySelector` gives an `HTMLElement` object if the element is present or `null` if there are no matches.
Trying to add an event listener to `null` throws an error - this is …
> Check that details component exists

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/_heading.scss
- app/views/govuk_publishing_components/components/docs/heading.yml
- lib/govuk_publishing_components/presenters/heading_helper.rb
- spec/components/heading_spec.rb
Add more font sizes to the heading component. We had 19 and 24 (defaulting to 27), which correspond to govuk headings small and medium and this PR adds 36 (large) and 48 (extra large).
I'm not sure why we have 27 as the default as that doesn't match a govuk heading size, but I'm not going to remove it as it's in use all over the place.
We probably didn't have these font sizes as options before because we also have the Page title component, which provides the 48px size. However I've started to wonder why we need two components and whether one could be enough to provide all needed functionality. This change is an interim step towards merging these two components, plus I need headings of these sizes in one of our applications.
> Add more font sizes to heading component

- Rakefile
- app/assets/javascripts/govuk_publishing_components/components/checkboxes.js
- app/assets/javascripts/govuk_publishing_components/components/step-by-step-nav.js
- app/assets/javascripts/govuk_publishing_components/lib/cookie-functions.js
- app/assets/javascripts/govuk_publishing_components/lib/govspeak/youtube-link-enhancement.js
- spec/javascripts/components/feedback-spec.js
This was mostly:
- changing the way objects are accessed
- swapping double quotes for single quotes
- objects keys with quotes having quotes remove
And one change of `getAttribute` to `hasAttribute` to check whether an attribute is present without needing a comparison.
Because [we should lint with Standard](https://gds-way.cloudapps.digital/manuals/programming-languages/js.html#linting) - and another branch I'm working on was failing Standard listing.
None.
> Fix JavaScript linting errors

- app/controllers/govuk_publishing_components/component_guide_controller.rb
- the suggested component sass/js functionality was missing some components in smart answers, because of the unusual structure of the code there
- this change expands the search criteria for files from .html.erb to all .erb files in the view, plus any .erb files in /lib
- now finds all components in smart answers
Because https://github.com/alphagov/smart-answers/pull/4659 missed the print link component, and had to be corrected in https://github.com/alphagov/smart-answers/pull/4673
None.
> Improve suggested component asset functionality

- CHANGELOG.md
- app/assets/stylesheets/component_guide/application.scss
- app/controllers/govuk_publishing_components/audit_controller.rb
- app/models/govuk_publishing_components/audit_applications.rb
- app/models/govuk_publishing_components/audit_comparer.rb
- app/models/govuk_publishing_components/audit_components.rb
- app/views/govuk_publishing_components/audit/show.html.erb
- app/views/govuk_publishing_components/component_guide/index.html.erb
- spec/component_guide/audit_applications_spec.rb
- spec/component_guide/audit_comparer_spec.rb
- spec/component_guide/audit_components_spec.rb
- spec/component_guide/component_index_spec.rb
- spec/dummy/lib/test_file_1.rb
- spec/dummy/lib/test_file_2.erb
The auditing code makes a lot of assumptions about being able to find specific directories, which means it's liable to errors or unexpected output when it can't find them. For example, when it's running on review apps sometimes it can't find itself, which meant that it was throwing up a ton of 'component does not exist' warnings when it shouldn't have been.
Additionally, some things should be shown or not shown depending on whether the auditing code has been able to find them - for example, if it can't find any applications it shouldn't display (blank) information about component usage in applications.
Additionally improves the scope of the auditing code by relaxing some of the restrictions on file extensions and regexes when looking for component instances in ruby. This was prompted by …
> Make component auditing code more resilient

- app/assets/javascripts/component_guide/accessibility-test.js
- app/assets/javascripts/component_guide/filter-components.js
- app/assets/javascripts/component_guide/visual-regression.js
- package.json
- spec/javascripts/components/toggle-input-class-on-focus-spec.js
- spec/javascripts/govuk_publishing_components/AccessibilityTestSpec.js
- spec/javascripts/govuk_publishing_components/FilterComponentsSpec.js
- spec/javascripts/govuk_publishing_components/VisualRegressionSpec.js
- spec/javascripts/govuk_publishing_components/lib/govspeak/barchart-enhancement-spec.js
- spec/javascripts/govuk_publishing_components/lib/govspeak/youtube-link-enhancement-spec.js
This widens the range of files covered by the JS linter, standard so that it covers all of the JS files we (GOV.UK) maintain for this repository.
The linter wasn't covering all files so approaches taken in some files would fail the linter, as they were linted, whereas others wouldn't, as they were not.
> Cover more JavaScript files with Standard linter

- CHANGELOG.md
- app/views/govuk_publishing_components/components/_breadcrumbs.html.erb
- app/views/govuk_publishing_components/components/_machine_readable_metadata.html.erb
- app/views/govuk_publishing_components/components/_step_by_step_nav_header.html.erb
Format output of machine readable components to make them slightly more human-readable too :-)
At present, the emitted json is all on one line. This makes it hard to read, (which is particularly important when looking at [the docs](https://components.publishing.service.gov.uk/component-guide/machine_readable_metadata)) but also difficult to evolve using tools like [the rich results testing tool](https://search.google.com/test/rich-results).
Formatting it nicely adds a few characters to the page, but allows for greater scrutiny, improvement and (possibly) adoption by 3rd parties.
It turns (using the breadcrumbs on https://www.gov.uk/universal-credit as an
example):
```
{"@context":"http://schema.org","@type":"BreadcrumbList","itemListElement":[{"@type":"ListItem","position":1,"item":{"name" …
```
> Format machine-readable output

- README.md
This is to reflect that there wasn't guidance on JS package managers. It
also adds an example of how to run the guide locally and breaks the
documentation into locally and not locally changes.
> Add running locally details to README

- Gemfile.lock
- Rakefile
- govuk_publishing_components.gemspec
- spec/dummy/config/application.rb
- spec/javascripts/components/toggle-input-class-on-focus-spec.js
This changes the approach to loading Gems to be more explicit to resolve surprisingly consequences for JS tests. In the  process of this it also removes some gems that aren't needed and moves others, that are only used in dev, to development dependencies.
In https://github.com/alphagov/govuk_publishing_components/pull/1598 we added the necessary configuration to replace PhantomJS for JS tests with Chromedriver run through Selenium. Unfortunately due to Bundler/load order complexities this didn't apply in all places, most notably the default `rake` task which is run by CI.
None, I hope
> Fix PhantomJS creeping back into tasks

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/_radio.scss
- app/views/govuk_publishing_components/components/_radio.html.erb
- app/views/govuk_publishing_components/components/docs/radio.yml
- spec/components/radio_spec.rb
Add custom page header size support for radio inputs.
This allows long questions to be displayed as page titles on applications like smart answers.
> Add support for custom sizes for radio page headers

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/_checkboxes.scss
- app/views/govuk_publishing_components/components/docs/checkboxes.yml
- lib/govuk_publishing_components/presenters/checkboxes_helper.rb
- spec/components/checkboxes_spec.rb
Add custom page header size support for checkboxes.
This allows long questions to be displayed as page titles on applications like smart answers.
> Add support for custom heading size for checkboxes

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
* Make component auditing more resilient ([PR #1604](https://github.com/alphagov/govuk_publishing_components/pull/1604))
* Add more font sizes to heading component ([PR #1587](https://github.com/alphagov/govuk_publishing_components/pull/1587))
* Format machine-readable output ([PR #1617](https://github.com/alphagov/govuk_publishing_components/pull/1617))
* Add support for custom sizes for radio page headers ([PR #1616](https://github.com/alphagov/govuk_publishing_components/pull/1616))
* Add support for custom heading size for checkboxes ([PR #1623](https://github.com/alphagov/govuk_publishing_components/pull/1623))
> Bump version to 21.60.0

- app/models/govuk_publishing_components/audit_components.rb
Jenkins generates working paths based on branch names, sometimes starting with an underscore (e.g. `/var/lib/jenkins/workspace/_replace-jquery-in-checkboxes-js/app/views/govuk_publishing_components/components/_step_by_step_nav.html.erb`). In such cases `get_component_name_from_full_path` matches all `/_` occurrences and replaces them with `/` messing the path then failing to read the dummy file. The whole model file should ideally be covered by unit testing to avoid such fails.
To prevent PRs (such as #1419, #1620 or #1622) from silently failing in CI. Ideally, the functions in models should be covered by unit tests.
> Fix `get_component_name_from_full_path`

- spec/dummy/config/environments/development.rb
- spec/lib/govuk_publishing_components/presenters/machine_readable/html_publication_schema_spec.rb
Allow requests for all domains e.g. <app>.dev.gov.uk
To allow local development and cross-browser/device testing in Browserstack
> Allow requests for all domains e.g. <app>.dev.gov.uk

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/govspeak/_charts.scss
- app/views/govuk_publishing_components/components/docs/govspeak.yml
1. Add an array to set the colour of numbers on govspeak bar charts with multicoloured bars based on the colour of the bar itself eg: the yellow bar has black text, the red bar has white text etc.
2. Add an example of a bar chart with multicoloured bars to the component guide for govspeak.
When a number is positioned inside a bar of a barchart, the colour contrast between the background colour of the bar and the default colour of the text (white) isn't high enough in some cases. It should be at least 4.5:1 or above to meet the WCAG 2.1 AA standard and, where possible, 7:1 to meet WCAG 2.1 AAA.
Before:
After:
> Change bar chart numbers and colours to be accessible

- app/models/govuk_publishing_components/audit_applications.rb
- app/models/govuk_publishing_components/audit_comparer.rb
- app/views/govuk_publishing_components/audit/show.html.erb
- spec/component_guide/audit_applications_spec.rb
- spec/component_guide/audit_comparer_spec.rb
- spec/dummy/app/assets/stylesheets/application.scss
- spec/dummy/app/views/layouts/dummy_admin_layout.html.erb
Extend the auditing code to check applications to find any instances of `gem-c-` classes in stylesheets or code, and raise a warning in the auditing page if found.
This will help us spot instances of component style overrides (which can break component isolation) or hard coded component markup (which can leave pages broken if the component is changed).
Any instances found are added to the existing list of warnings.
All instances are also listed after the warnings.
The code checks all the places that components are currently searched in (stylesheets, templates, javascripts, ruby code) but doesn't raise a warning if the instance is a javascript file, as attaching events to components on an application level seems like it might not cause problems? Happy to discuss this approach though.
> Extend auditing

- app/assets/stylesheets/govuk_publishing_components/components/_radio.scss
Adds extra margin between the question and the first item - which could be a description, hint text, or the radio input - if the component is being used as a page heading.
To give the heading more space, as requested by @miaallers.
| Before | After|
|-|-|
| ![image](https://user-images.githubusercontent.com/1732331/89430501-b69a6900-d736-11ea-92d6-673edbdbc8eb.png) | ![image](https://user-images.githubusercontent.com/1732331/89430400-9f5b7b80-d736-11ea-95eb-6497383d129e.png) |
| ![image](https://user-images.githubusercontent.com/1732331/89430582-c6b24880-d736-11ea-9ee3-09184d8d85fc.png) | ![image](https://user-images.githubusercontent.com/1732331/89430650-ddf13600-d736-11ea-9382-6031f1ecbfd1.png) |
> Add space below radio component when page heading

- CHANGELOG.md
- app/views/govuk_publishing_components/components/_image_card.html.erb
- app/views/govuk_publishing_components/components/docs/image_card.yml
- lib/govuk_publishing_components/presenters/image_card_helper.rb
- spec/components/image_card_spec.rb
Introduce the ability to pass an (optional) lang parameter to specify language on the image card component.
This is necessary due to the fact that there are instances on the site where a page will be in Welsh, but certain components on the page will display data in English as there is no Welsh translation for those parts of the page. This is a Web Accessibility fail.
A concrete example is [here](https://www.gov.uk/government/organisations/nuclear-decommissioning-authority.cy)  where even though the document is a Welsh translation, the ministers information is all in English.
----------
Goes hand in hand with https://github.com/alphagov/collections/pull/1853
https://trello.com/c/4znXL1Bn
> Add optional lang parameter to image card component

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/lib/govspeak/youtube-link-enhancement.js
We are using the string `includes` method, which is not compatible with Internet Explorer (see
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/includes).
Therefore replacing with a workaround that is compatible with Internet Explorer.
This prevents the YouTube videos from being embedded for anyone using Internet Explorer.  The following errors appears in the browser's console:
```
Object doesn't support property or method 'includes'
```
Zendesk ticket: https://govuk.zendesk.com/agent/tickets/4189366
> Replace 'includes' with a method compatible with Internet Explorer

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/components/checkboxes.js
- spec/javascripts/components/checkboxes-spec.js
Replace jQuery usage in checkboxes.js with standard functions.
Part of removing jQuery from GOV.UK.
Quick performance check on nested checkboxes using the script below:
```
document.getElementById('checkboxes-971849fc-0').click() // select all siblings
document.getElementById('checkboxes-971849fc-0-0').click() // unselect a child
document.getElementById('checkboxes-971849fc-1').click() // select all siblings
document.getElementById('checkboxes-971849fc-1-0').click() // unselect a child
```
<table>
~7.64 milliseconds
~1.56 milliseconds
</td></tr>
</table>
[Trello card](https://trello.com/c/sghHecNi)
> Replace jQuery in checkboxes.js

- CHANGELOG.md
- lib/govuk_publishing_components/presenters/image_card_helper.rb
This adds a `lang="en"` attribute to the image card component.
The way the date/time is formatted means it will always be in English even when the contents of the page are in a different language. If we don't clearly indicate the language of the element, it fails WCAG 2.1 A 3.1.2 when it's viewed in the context of a translated page.
https://trello.com/c/uA7mDUvI
> Add lang attribute to image card date element

- CHANGELOG.md
- lib/govuk_publishing_components/presenters/content_breadcrumbs_based_on_priority.rb
- spec/lib/govuk_publishing_components/presenters/content_breadcrumbs_based_on_priority_spec.rb
Add the transition taxon to the list of priority taxons. This will result in a transition super breadcrumb being rendered on pages that are tagged directly (or indirectly via a parent) to the transition taxon.
Metric/hypothesis suggestion - with the superbreadcrumb in place users are more likely to go to transition landing page after landing directly from google onto a piece of transition tagged content. This would be good because we will have increased engagement and awareness of transition content and the need to take action to prepare.
Trello https://trello.com/c/OtFElqJ3/385-summon-the-superbreadcrumb-%F0%9F%A6%B8%E2%99%80%EF%B8%8F-for-pages-tagged-to-the-transition-topic
> Add priority breadcrumb to content tagged to the transition taxon

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
* Add public/frontend layout component ([PR #1265](https://github.com/alphagov/govuk_publishing_components/pull/1265))
* Replace jQuery in checkboxes.js ([PR #1620](https://github.com/alphagov/govuk_publishing_components/pull/1620))
* Add lang attribute to image card date/time element ([PR #1642](https://github.com/alphagov/govuk_publishing_components/pull/1642))
* Add priority breadcrumb to content tagged to the transition taxon ([PR #1646](https://github.com/alphagov/govuk_publishing_components/pull/1646))
> Bump to 21.61.0

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/govuk_frontend_support.scss
Add a new brand colour for the FCDO department. This colour is used on the organisation page in dividing lines, icons, link text colour etc. after it is selected in Whitehall.
The brand colour is used in the new organisation page. The brand colours come from [govuk-frontend](https://github.com/alphagov/govuk-frontend/), however since there may be some time before it is release again, we have
added it to the govuk_publishing_components so we can get it deployed.
[Related pull request in govuk-frontend](https://github.com/alphagov/govuk-frontend/pull/1918#pullrequestreview-469159049)
[Trello card](https://trello.com/c/s0NySL7Q/2098-add-new-brand-colour-for-fcdo)
> Add brand colour for FCDO

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
* Add new brand colour for FCDO ([PR#1648](https://github.com/alphagov/govuk_publishing_components/pull/1648))
> Bump to 21.62.0

- CHANGELOG.md
- lib/govuk_publishing_components/presenters/breadcrumb_selector.rb
- spec/features/contextual_navigation_spec.rb
Hide transition priority breadcrumb if content is part of Step by Step.
Because having both breadcrumbs is confusing.
> Hide transition priority breadcrumb if content is part of Step by Step

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/components/step-by-step-nav.js
- app/assets/javascripts/govuk_publishing_components/lib.js
- app/assets/javascripts/govuk_publishing_components/vendor/polyfills/closest.js
- app/assets/javascripts/govuk_publishing_components/vendor/polyfills/indexOf.js
- spec/javascripts/components/step-by-step-nav-spec.js
- remove jquery from the step by step navigation component
- not removing jquery from the test as jasmine has its own jquery, but this has required some changes to make the tests run properly
We want to remove our dependency on jquery.
None.
I've made a few changes to the code to try to support older versions of IE. The big change is adding polyfills for `indexOf` and `closest`, without which the component breaks. I've also put in non-polyfill workarounds to avoid using `textContent`, `forEach` and `prepend`, which means the code isn't perhaps as elegant as it could be, but I think this is reasonable.
We don't support IE8 but people still use it. Ideally we'd rewrite the component JS to fail gracefully on older browsers so that the component is left in a usable state (e.g. all steps …
> Remove jquery from step by step component

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/dependencies.js
- app/assets/javascripts/govuk_publishing_components/lib/toggle.js
- spec/javascripts/components/toggle-spec.js
Remove jquery from `toggle.js`. Also expands the documentation for the code.
We want to remove our dependency on jquery.
None.
> Remove jquery from toggle code

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/_panel.scss
- app/views/govuk_publishing_components/components/_panel.html.erb
- spec/components/panel_spec.rb
On the panel component, move the optional prepended text and appended text into the same block as the `text` for the heading.
The prepended text, heading text, and appended text on the panel component should be in the same block.
The issue with the prepended and appended text being outside the heading element is that they provide context for the heading. Screen reader users might be confused by the incomplete heading and not understand it out of context when they are navigating a page according to its headings.
The panel text on https://www.gov.uk/bank-holidays for each next bank holiday is disjointed. It should be in the same block level element.
```
<div>
The next bank holiday in England and Wales is
</div>
<h2>
31 August
</h2>
<div>
Summer bank holiday
</div>
``` …
> Fix panel component disjointed heading

- app/views/govuk_publishing_components/component_guide/example.html.erb
- app/views/govuk_publishing_components/component_guide/show.html.erb
- make first 'how it looks' heading link to the default example in the component guide for that component
- add 'preview' link for the first example into the same heading, before 'preview all'
- add 'preview' link to the 'how it looks' heading on the default example page
I've found the lack of this navigation occasionally frustrating for quite a while now. It's not a huge problem, and I know the URLs to type, but I think this makes navigating the component guide fractionally easier.
Before | After
> Add links to component guide

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
* Remove jquery from toggle code ([PR #1649](https://github.com/alphagov/govuk_publishing_components/pull/1649))
* Add role="alert" to cookie banner confirmation ([PR #1658](https://github.com/alphagov/govuk_publishing_components/pull/1658))
* Remove jquery from step by step component ([PR #1645](https://github.com/alphagov/govuk_publishing_components/pull/1645))
* Fix panel component disjointed heading ([PR #1660](https://github.com/alphagov/govuk_publishing_components/pull/1660))
> Update release to version 21.63.1

- CHANGELOG.md
- app/views/govuk_publishing_components/components/_search.html.erb
Fix the logic for the `on-white` and `on-blue` stylings for the search component.
Search box (on blue option) on the homepage isn't appearing correctly.
Before:
After:
> Fix the on blue logic for the search component

- app/views/govuk_publishing_components/components/_radio.html.erb
Adds a h2 tag inside the legend tag within the radio component.
This was raised during the accessibility audit of govuk. On the [cookie page](gov.uk/help/cookies), all the headings are legends. As well as this being confusing to users because these look like headings, it mens that this page can't be navigated through using the headings. This solution of putting headings within the legends is the solution used by the [design system for radio buttons](https://design-system.service.gov.uk/components/radios/stacked/index.html). This solution has been backed up by Anika and the content community.
No intended visual changes.
**Card:** https://trello.com/c/mCncj7BE/328-cookies-page-missing-headings
> Add h2 tag into legend by default

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
* Remove jquery from govspeak ([PR #1657](https://github.com/alphagov/govuk_publishing_components/pull/1657))
* Add h2 tag into legend by default ([PR #1665](https://github.com/alphagov/govuk_publishing_components/pull/1665)) (I forgot to add this to the changelog in the PR itself which is why it wasn't here before)
> Bump version to 21.63.3

- CHANGELOG.md
- lib/govuk_publishing_components/presenters/content_breadcrumbs_based_on_priority.rb
- lib/govuk_publishing_components/presenters/contextual_navigation.rb
- spec/features/contextual_navigation_spec.rb
- spec/lib/govuk_publishing_components/presenters/content_breadcrumbs_based_on_priority_spec.rb
The superbreadcrumb makes use of the step_by_step_nav_header. 
The superbreadcrumb is displayed if content is tagged with at least one of the priority taxons defined in `ContentBreadcrumbsBasedOnPriority`.
This change allows the superbreadcrumb to be selected using a query string 'priority-taxon' instead of relying on a simple priority order. If the query string is not defined or not matched, it will use the original logic above.
Previously if a piece of content is tagged to more than one hub page the superbreadcrumb shown to a user is defined by a hierarchy of hubs, and isn't responsive to the hub that a use has navigated from.
This means that a user might go to a piece of content from one hub, but see the superbreadcrumb for a different hub, which is confusing, and doesn't provide a …
> Display preferred super breadcrumb using query string

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
Release for 'Superbreadcrumb can have a priority taxon selected via query param'
> Bump version to 21.64.0

- CHANGELOG.md
- app/views/govuk_publishing_components/components/_step_by_step_nav_header.html.erb
- app/views/govuk_publishing_components/components/docs/step_by_step_nav_header.yml
Changed the nav header to use a heading element instead of a div element.
This failed WCAG 2.1 SC 1.3.1 as the component acted as a heading, but wasn't marked up as a heading.
None.
> Updates step by step nav header

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
* Step by step nav header updated to use heading ([PR #1671](https://github.com/alphagov/govuk_publishing_components/pull/1671))
* Increase icon size and allow transparent icons on action link component ([PR #1674](https://github.com/alphagov/govuk_publishing_components/pull/1674))
> Release 21.65.0

- app/assets/stylesheets/govuk_publishing_components/components/_input.scss
Explicitly set box sizing on inputs, as this is being overwritten by govuk template (or something in static), which is causing layout problems.
Example:
Fix:
Related to: https://github.com/alphagov/collections/pull/1899
> Explicitly set box sizing on inputs

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/_search.scss
Fixes display of search label on blue background when JS is disabled, and the label is shown outside of the search box.
Previous work: https://github.com/alphagov/govuk_publishing_components/pull/1676 (thanks to @danacotoran)
Search label was unreadable.
Before:
After:
> Fix search box label colour

- app/views/govuk_publishing_components/components/_breadcrumbs.html.erb
- lib/govuk_publishing_components/presenters/breadcrumbs.rb
Removes all instances of `aria-current="false"` from the breadcrumbs component.
[Aria-current="false" has no semantic meaning and is the default attribute for aria-current](https://www.digitala11y.com/aria-current-state/). As there's no need for it on either the list or link item and we don't display the current breadcrumb as a rule, it makes more sense to not use it and keep our markup tidy.
> Remove aria-current="false" from breadcrumbs

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
* Fix search box label colour ([PR #1680](https://github.com/alphagov/govuk_publishing_components/pull/1680))
> Version 21.65.1

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/lib/toggle-input-class-on-focus.js
- spec/javascripts/components/toggle-input-class-on-focus-spec.js
Remove jQuery dependence from toggle-input-class JS script (used by the search component).
To reduce our dependency on jQuery.
None.
> Remove jQuery from toggle-input-class JS

- CHANGELOG.md
- app/views/govuk_publishing_components/components/feedback/_yes_no_banner.html.erb
Remove `aria-expanded="false"` from the yes button on the feedback component.
This attribute doesn't change when the user clicks yes and even then, nothing "expands" even though something is revealed. This attribute is redundant as it's not being used and can be confusing to screen reader users as they're expecting something to expand when they interact with the button.
**Card:** https://trello.com/b/NLbahOWX/govuk-accessibility-doing
> Remove aria-expanded attribute from yes feedback button

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/components/feedback.js
This aims to address issues with WCAG SC: 3.3.1 and 3.3.3 for the "No" and "Is there anything wrong with this page?" feedback forms. 
When submitting an empty form, the erroring fields are not identified. [3.3.1]
When submitting an empty form, the error message is very vague. [3.3.3]
There was a previous attempt to fix this issue here https://github.com/alphagov/feedback/pull/758
Here is what happens when there is an attempt to submit the form without any data.
The generic "something went wrong" message is displayed – this is unhelpful to the user as they cannot identify what went wrong:
When invalid data is submitted, the server responds with a `422` status.
However instead of the intended JSON response, it returns a rendered html page. The frontend defaults to the generic error message …
> Feedback form errors frontend workaround

- CHANGELOG.md
- app/views/govuk_publishing_components/components/_notice.html.erb
- app/views/govuk_publishing_components/components/docs/notice.yml
- spec/components/notice_spec.rb
This is the first part of https://trello.com/c/k5JCHIoZ/382-add-language-attribute-to-withdrawn-banner
This allows us to pass in a lang attribute which is necessary when the notice is in a different language from the rest of the page. The specific use case identified so far is in Withdrawn notices appearing on translated pages.
No visual changes, just an extra attribute.
> Add locale attribute to notice component

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/lib/header-navigation.js
- app/assets/stylesheets/govuk_publishing_components/components/_search.scss
- app/views/govuk_publishing_components/components/layout_header/_search.html.erb
- Modify search toggle button to use button markup instead of an anchor tag, to more closely match the presentation and function of this element.
- Hide element when Javascript is disabled as the element is not functional without JS.
- Modify element text to more accurately represent what the element does ("Show/Hide search" depending on the state)
The button that opens/closes the layout header search form on mobile is not actually a button, but an anchor tag. Therefore, it does not behave as a button (for instance, it does not activate when using the space key)
This is semantically incorrect and cannot be easily understood by screen reader users, or used by voice control users.
> Mobile search toggle button

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
* Remove jQuery from toggle-input-class JS ([PR #1683](https://github.com/alphagov/govuk_publishing_components/pull/1683))
* Add locale attribute to notice component ([PR #1686](https://github.com/alphagov/govuk_publishing_components/pull/1686))
* Remove aria-expanded attribute from yes feedback button ([PR #1687](https://github.com/alphagov/govuk_publishing_components/pull/1687))
* Mobile search toggle button ([PR #1682](https://github.com/alphagov/govuk_publishing_components/pull/1682))
> Release 21.66.0

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/lib/govspeak/magna-charta.js
- app/views/govuk_publishing_components/components/docs/govspeak.yml
Amends the js for magna charta (charts for govspeak) to fix a bug on charts.
[A user has pointed out a bug on barcharts](https://www.gov.uk/government/publications/uk-house-price-index-summary-march-2020/uk-house-price-index-summary-march-2020#housing-transaction-distributions). Some investigation found that the `mc-bar-outdented` class isn't being applying where it needs to be because the `spanWidth` variable was returning NaN (because the computed style width was returning auto instead of an actual px value).
This amends the js to use `offsetWidth` instead, returning the class addition to it's intended functionality.
> Fix magna charta span width bug

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
* Fix magna charta span width bug ([PR #1691](https://github.com/alphagov/govuk_publishing_components/pull/1691)) FIX
> Bump release to 21.66.1

- CHANGELOG.md
- app/views/govuk_publishing_components/components/_document_list.html.erb
Swap out the containing `ol` on the document list component for a `ul` instead.
It's inappropriate for document lists to sit within an ordered list as they don't convey that they are ordered through presentation. This fails WCAG 1.3.1 as a result.
**Card:** https://trello.com/c/zeNDQ9hA/374-ordered-list-used-when-list-is-not-ordered
> Swap out ol for ul on documents list

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/lib/header-navigation.js
Only change header toggle button inner text to "show/hide search" depending on open/closed state if the target is the search toggle button.
The search menu uses the same `js-header-toggle` class as the search toggle button in the site header on mobile.
This lead to an issue where the secondary navigation toggle button text would change to "Show/Hide search", which was only supposed to be applied to the search toggle.
Fixes aforementioned problem. The toggle text for the header links should be "Menu", not "Hide/show search"
> Search toggle inner text fix

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
Bumps `govuk_publishing_components` to 21.66.2.
Includes:
* Swap out ol for ul on documents list ([PR #1694](https://github.com/alphagov/govuk_publishing_components/pull/1694)) FIX
* Search toggle inner text fix ([PR #1696](https://github.com/alphagov/govuk_publishing_components/pull/1696)) FIX
> Bump gem to 21.66.2

- CHANGELOG.md
- app/views/govuk_publishing_components/components/_contents_list.html.erb
- app/views/govuk_publishing_components/components/docs/contents_list.yml
- spec/components/contents_list_spec.rb
Updates aria label for the contents list component so that aria label
defaults to "Contents" unless a custom aria label is supplied.
The contents list component is a nav element, and often appears on pages which
have other nav elements. When there are multiple navigation landmarks on
a page, they should be labelled to help assistive technology users
differentiate between them.
No visual changes should occur as a result of this change.
https://trello.com/c/XFKhZwEI
> Add default aria-label for contents list component

- CHANGELOG.md
- app/views/govuk_publishing_components/components/docs/organisation_logo.yml
- lib/govuk_publishing_components/presenters/organisation_logo_helper.rb
- spec/components/organisation_logo_spec.rb
Add an option to set the `lang` attribute to the text of an organisation logo. If no option is passed, no lang attribute is set.
An accessibility audit of organisation pages has shown that pages such as https://www.gov.uk/world/organisations/british-consulate-general-chongqing.zh do not mark the org name in English, even though it is in English inside a page of a different language, which is an accessibility failure.
None.
Trello card: https://trello.com/c/bQn51uw9/392-update-language-attribute-of-organisation-name-on-world-organisation-embassy-pages
> Add lang option to organisation logo text

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
* Add lang option to organisation logo text ([PR #1700](https://github.com/alphagov/govuk_publishing_components/pull/1700))
* Add default aria-label for contents list component ([PR #1698](https://github.com/alphagov/govuk_publishing_components/pull/1698))
> Version 21.66.3

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/_image-card.scss
- app/views/govuk_publishing_components/components/_image_card.html.erb
- spec/components/image_card_spec.rb
https://trello.com/c/mprRX2H8/376-confusing-order-of-content-for-featured-items-on-organisation-pages
Previously the source content for the image card was in a confusing order. Although it was clear from the design which elements belonged together, this was not reflected in the underlying page, with the heading coming after the image and contextual text. This switches the elements around and then uses CSS to realign them as before.
Order before:
- image
- context
- heading
- description and links
Order afterwards: 
- heading
- context
- description and links
- image
This improves the semantics of the page source and means that users who linearise the page will see the content and headings more clearly associated.
There are no intended visual changes. These screenshots are the updated code …
> Reorder image card elements

- app/views/govuk_publishing_components/components/_government_navigation.html.erb
Adds a relevant `aria-label` to the government nav component.
Uses the suggested name of "Departments and policy navigation". This was
suggested because in the site footer the section containing the same
links is called "Departments and policy".
The reason for this change is that the site header links are a nav
element and often appears on pages where other nav elements are present.
When there are multiple navigation landmarks on a page, they should be
labelled in order to help assistive tech users differentiate between
them.
No visual changes should occur as a result of this
https://trello.com/c/XFKhZwEI
> Add aria-label to government_navigation component

- CHANGELOG.md
- app/views/govuk_publishing_components/components/_subscription-links.html.erb
Add `lang="en"` to the element that can appear when the feed link is configured to toggle a box for copying and pasting the link.
Added a new element for this to wrap the input and label only, because for some reason the text of the feed link is repeated inside the existing wrapping element, which is passed to the component and cannot be guaranteed to be English, as opposed to the rest of the text, which comes from the component and is.
Needed on pages like https://www.gov.uk/world/taiwan/news.zh-tw
None.
Trello card: https://trello.com/c/T0DDhI5x/391-update-language-attribute-in-subscription-links-component-of-world-organisation-embassy-pages
> Add language attribute to feed box

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/_feedback.scss
- app/views/govuk_publishing_components/components/feedback/_problem_form.html.erb
- app/views/govuk_publishing_components/components/feedback/_survey_signup_form.html.erb
- app/views/govuk_publishing_components/components/feedback/_yes_no_banner.html.erb
- spec/components/feedback_spec.rb
Replaces links with `role="button"` on the feedback component for actual buttons. Based on mockups by a designer.
Controls are presented as links to seeing users but as buttons to screen reader users and they function like buttons. This can cause screen readers users to struggle to find information and can make it more difficult for voice control users to activate a link/button.
**Extra small**
**Mobile**
**Tablet**
**Desktop**
**Extra small**
**Mobile**
**Tablet**
**Desktop**
**Card:** https://trello.com/c/N1VFz9Fv/395-feedback-component-buttons-that-look-like-links
> Replace feedback component links with buttons

- CHANGELOG.md
- app/views/govuk_publishing_components/components/_contents_list.html.erb
- app/views/govuk_publishing_components/components/docs/contents_list.yml
- spec/components/contents_list_spec.rb
Introduce the ability to pass through `lang` and custom title to the
Contents list component.
If a title lang is not supplied, a `lang` attribute will not be added.
Likewise, if a custom title is not specified, the component will default
to using "Contents" as a title.
Supports this piece of work:  https://github.com/alphagov/whitehall/pull/5831 
The need for this arose because in some instances (for example on world
location pages), when viewing a translation of the page, this title of
this component will be in English and not marked as such.
If a translation exists, we should use the translated string as the
title (e.g Contenu if the page is in French). Otherwise we can use the
English fallback, as long as `lang="en"` is specified.
https://trello.com/c/D2lTyikn
> Extend contents list component

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/lib/select.js
- spec/javascripts/components/select-spec.js
Remove jQuery from select.js
- select.js is used to trigger analytics events on select elements
- it seems to be only used by finder-frontend
- it has an option for extra options to be added to the tracking via a data attribute on the select option elements
- this option does not appear to be in use by finder-frontend, and there was no test for it, so I've added one
To reduce our dependency on jQuery.
None.
> Remove jQuery from select.js

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/_image-card.scss
The recent changes to the source order on the image card introduced a bug affecting IE11. For some reason the image wrapper grows beyond the size of the image it contains. Setting it to any value percentage fixes it, so a 100% height is applied here. It has no knock on effects on other browsers that I can see.  
Bug reported through Zendesk: https://govuk.zendesk.com/agent/tickets/4250243
> Fix IE11 height bug on image card

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/components/step-by-step-nav.js
Removes the attributes from the text `show` (or `hide` if the step is open) [on the step by step nav component](https://components.publishing.service.gov.uk/component-guide/step_by_step_nav) that would hide it from assistive technologies and updates the surrounding markup to be more verbose for screen reader users. What is dictated to screen reader users before and after:
- Before: `Heading level 2, Do a thing` or, with show/hide hiding attributes removed, `heading level 2, Do a thing show`
- After: `Heading level 2, Do a thing, show this section`
A WCAG fail has been raised around the step by step nav component. Because show/hide are hidden from assistive tech, voice control users aren't able to dictate something like "click show" because their software wont be able to find it. This …
> Update step by step show/hide text to be more verbose for screen readers

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
* Update step by step show/hide text to be more verbose for screen readers ([PR #1701](https://github.com/alphagov/govuk_publishing_components/pull/1701)) FIX
> Bump version to 21.67.2

- README.md
Added link to guidance on how to tell a locally running app to use the local version of the components gem.
Seems to a missing thing from the README and developers have been asking questions about it.
None (to the app).
> Update readme to link to local gem guidance

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/_feedback.scss
- app/views/govuk_publishing_components/components/feedback/_yes_no_banner.html.erb
- config/locales/en.yml
- spec/components/feedback_spec.rb
This PR:
- changes the styling of the buttons on the feedback component to be transparent with a white background
- changes the text on the "something wrong" button from `Is there anything wrong with this page?` to `There is something wrong with this page`
- [fixes a display issue on IE11](https://github.com/alphagov/govuk_publishing_components/issues/1709)
The original button re-design to the feedback component was designed and developed quite quickly so that it can be pushed through in time for the accessibility deadline. It has been pointed out that on some pages, notably pages with CTAs or forms, that these quite bright buttons are a bit distracting. This softens the buttons so that they still look like buttons but are less intrusive.
The text change on the "something wrong" button …
> Set feedback buttons to be transparent

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
* Set feedback buttons to be transparent ([PR #1719](https://github.com/alphagov/govuk_publishing_components/pull/1719))
> Update version to 21.68.0

- app/assets/stylesheets/govuk_publishing_components/components/_action-link.scss
- Adding a (potentially global) component hover style colour for white text on a dark background - starting with action link.
There was a request from Design to update a missing hover state on the [action link](https://components.publishing.service.gov.uk/component-guide/action_link) on [corona virus landing page.](https://www.gov.uk/coronavirus)
Ticket: https://trello.com/c/mBN0xr04
Updating the [corona virus](https://www.gov.uk/coronavirus) landing page action link with a unique hover style in complete isolation is not ideal. 
Users will have have a mix of hover styles even within the same page. For example, this also impacts [Bread Crumbs](https://components.publishing.service.gov.uk/component-guide/contextual_breadcrumbs) which is also on this page.
This prompted a wider discussion, …
> Hover style for action link

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/_subscription-links.scss
- app/views/govuk_publishing_components/components/_subscription-links.html.erb
- spec/components/subscription_links_spec.rb
This changes the styling of the subscription links component when the "subscribe to feed" element functions as a button. 
Adjusted the markup of the component to have the `role="button"` attribute. Also, adjusted the styling for the "Get email alerts" link for when the two are side by side, to link the two together visually.
These changes should only take place when the feed button functions as a button. This styling of this component should remain the same in other variations of the component. 
There are instances where the "subscribe to feed" link functions as a button.
This discrepancy between the appearance and the function of this element can make it more difficult for screen reader and voice control users to find the information they need.
Example of a page where this problem …
> Feed subscription link accessibility fix

- CHANGELOG.md
- app/views/govuk_publishing_components/components/_search.html.erb
- app/views/govuk_publishing_components/components/layout_header/_search.html.erb
Update layout header component search label to "Search on GOV.UK".
Update search component to have "Search on GOV.UK as the default text.
The site search box is labelled inconsistently throughout the site (The label for the search box is "Search on GOV.UK" on the homepage and "Search" on sub pages)
This is a fail of WCAG SC 3.2.4: **Consistent Identification**.
https://trello.com/c/RbD3om74
> Update search component input label

- CHANGELOG.md
* Adding hover styling for action link ([PR #1728](https://github.com/alphagov/govuk_publishing_components/pull/1728))
> Update to CHANGELOG

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/_subscription-links.scss
Add a legacy colour to the use of `govuk-colour` in subscription links.
Whitehall is still dependent on the legacy colours, which wasn't included originally, causing a build fail in CI on [this PR](https://github.com/alphagov/whitehall/pull/5839).
None.
> Add legacy colour to subscription links

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/_print-link.scss
- app/views/govuk_publishing_components/components/_print_link.html.erb
Updates the print link component to look like a button as it's actually a button in the markup.
Updates the link variant of this component to act as a button as well by using `data-module="button"`; this means it can now be selected with [spacebar], just like a button.
This component failed WCAG 2.1 success criteria 1.3.1:
> Information, structure, and relationships conveyed through presentation can be programmatically determined or are available in text.
Trello card: https://trello.com/c/Hk1Ir65Z
Before:
After:
Hover before:
Hover after:
Active before:
Active after:
Focus before:
Focus after:
> Update print component to look like a button

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
Includes:
* Update action link component to support simple light arrow ([PR #1739](https://github.com/alphagov/govuk_publishing_components/pull/1739))
* Update print component to look like a button ([PR #1735](https://github.com/alphagov/govuk_publishing_components/pull/1735))
* Add legacy colour to subscription links ([PR #1731](https://github.com/alphagov/govuk_publishing_components/pull/1731))
> Release 21.69.0

- CHANGELOG.md
- app/views/govuk_publishing_components/components/_panel.html.erb
- app/views/govuk_publishing_components/components/docs/panel.yml
- spec/components/panel_spec.rb
Update the panel component to accept an option to set the heading level.
- previously was a hard coded H2
- now defaults to a H2 but can be passed a different level if required
- uses the shared helper for this functionality, which already has tests for e.g. passing invalid values
This is needed for a page where there is no H1 and the panel component is the first thing on the page.
Related to https://trello.com/c/eI2DqKFx/348-accounts-feedback-screen
> Add heading option to panel component

- CHANGELOG.md
- app/views/govuk_publishing_components/components/_layout_for_public.html.erb
- app/views/govuk_publishing_components/components/_layout_header.html.erb
- app/views/govuk_publishing_components/components/docs/layout_header.yml
- app/views/govuk_publishing_components/components/layout_header/_header_logo.html.erb
- spec/components/layout_header_spec.rb
- spec/dummy/app/views/layouts/dummy_admin_layout.html.erb
- the product name wasn't shown in the header if the environment is 'public'
- product name defaulted to 'Publishing' even if not explicitly passed to the component
- now changed so the product name is shown regardless of the environment, but only shown if it is explicitly passed to the component
**Note that this is potentially a breaking change for the following reasons**
This change means that the component guide changes so most of the examples now don't have a product name, only the example showing the product name has one. This change may have some consequences for applications currently using this component. Specifically:
- [coronavirus vulnerable people service](https://github.com/alphagov/govuk-coronavirus-vulnerable-people-form/blob/092e527b41aa656a822154c442c9822976ea5de5/app/view …
> Layout header component always displays product name and environment when provided

- CHANGELOG.md
- app/views/govuk_publishing_components/components/_govspeak.html.erb
- app/views/govuk_publishing_components/components/docs/govspeak.yml
Removes the ability for the Govspeak component to use unsanitized HTML. This changes updates the current non-breaking message to raise an errror whenever non-sanitised HTML is given to the Govspeak component.
This is a **breaking change**.
I've added (another) column to the [frontend apps spreadsheet](https://docs.google.com/spreadsheets/d/1J-0IPyr2ycPuw1IWOIoX0o9Tk9nF35D0DJdsj_ylLQE/edit#gid=0) to highlight which apps will need to be updated, which have already been updated, and which don't use Govspeak at all.
This was marked as deprecated more than two years ago and should be removed (or the message saying it's deprecated should be removed.)
This means that apps that have:
```erb
<%= render "govuk_publishing_components/components/govspeak", {
content: …
```
> Remove ability to pass Govspeak unsanitized HTML

- CHANGELOG.md
- app/views/govuk_publishing_components/components/_input.html.erb
- app/views/govuk_publishing_components/components/docs/input.yml
- spec/components/input_spec.rb
- allows the label for the input to be wrapped in a heading tag, for situations where the input is the first or only thing on a page, and no other suitable heading is appropriate
- based on https://design-system.service.gov.uk/patterns/question-pages/
Needed for a page in accounts where the label/input is the only thing on the page.
Trello card: https://trello.com/c/pI5hMyeb/329-create-account-flow-frontend
> Add heading level option to input component

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/lib/track-click.js
- spec/javascripts/govuk_publishing_components/lib/track-click.spec.js
Add the track click code from static into the gem. This has involved some changes:
- **the code is now a module** which means that it has to be explicitly called using `data-module` on the element to be tracked, whereas previously this was done by the presence of other data attributes alone (`data-track-category` and `data-track-action`)
- **the module has been renamed** because if we did a proper migration (and removed it from `static`) the above change would be a massive breaking change across all of GOV.UK, which we don't have time to deal with right now. Instead, this code will exist as a small semi-duplication, which is less than ideal, but allows us to use it
A side effect of this change was that until the module had been renamed it broke the tests because the `details` component …
> Add track click code from static

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/_action-link.scss
Fix the active state on the action link component by simplifying the styling and rely on default anchor styling for the active state (as we do for any basic links across GOV.UK and within the Design System).
Causes issues when used in the `light_text` flag.
The component used in the site-wide banner in Safari 14.0:
Thank you @conordelahunty for reporting this!
<table>
<tr><th>Before `:active`</th><th>After `:active`</th></tr>
</td></tr>
</table>
[Preview link](https://govuk-publis-fix-active-tkxbuu.herokuapp.com/component-guide/action_link/with_light_text)
> Fix active state on action link

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
Note - this is version 23.0.0 due to a previously yanked version using v22.0.0; this release is unrelated to the yanked version.
* Add track click code from static ([PR #1751](https://github.com/alphagov/govuk_publishing_components/pull/1751))
* Fix active state on action link ([PR #1749](https://github.com/alphagov/govuk_publishing_components/pull/1749))
* Add heading option to input component ([PR #1747](https://github.com/alphagov/govuk_publishing_components/pull/1747)) MINOR
* Add analytics from static ([PR #1745](https://github.com/alphagov/govuk_publishing_components/pull/1745)) MINOR
* **BREAKING** Layout header component always displays product name and environment when provided ([PR #1736](https://github.com/alphagov/govuk_publishing_components/pull/1736))
* Add heading option to …
> Release v23.0.0

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/_print-link.scss
- app/views/govuk_publishing_components/components/_print_link.html.erb
- app/views/govuk_publishing_components/components/docs/print_link.yml
- spec/components/print_link_spec.rb
This change adds support for custom margin-top and bottom using the shared helper.
This retains a similar margin top and bottom - previously 2em (16px) but now govuk-spacing level 3 (around 15px).
The print link is now being used in multiple apps across GOVUK, therefore, needs to be able to match the styling of each app or placement within a page.
None - retains all existing styles.
https://govuk-publis-add-margin-rq2byv.herokuapp.com/component-guide/print_link
> Add margin support for print link

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/_search.scss
The global header was [recently updated](https://github.com/alphagov/static/pull/2293) to use the search component instead of a hard coded search field.
This resulted in an issue where the input outline is now orange due to more specific styles from `govuk_template` conflicting with the search component styles.
This updates the component styles to be more specific in order to override the CSS from `govuk_template`.
The site search input focus style has an orange outline due to `govuk_template` styles being more specific than the search component styles.
The outline should match the focus style of the search button.
NOTE: as of the time this PR is being created the bug is not live, we caught the issue on staging.
https://trello.com/c/RbD3om74
> Fix orange outline on global site search

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
Included in this release:
* Add custom margin support for print link ([PR #1753](https://github.com/alphagov/govuk_publishing_components/pull/1753))
> Bump version to 23.1.0

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/_layout-header.scss
Fix the appearance of the layout header component on IE11 and down.
Before (IE11)
After (IE11)
The change results in a tiny difference for Chrome, before:
After:
Trello card: https://trello.com/c/ICDC0esK/368-accounts-snag-list-%F0%9F%8C%AD
> Fix layout header component in IE

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/print/_govspeak.scss
Example page where footnotes are used: https://www.gov.uk/government/publications/our-plan-to-rebuild-the-uk-governments-covid-19-recovery-strategy/our-plan-to-rebuild-the-uk-governments-covid-19-recovery-strategy 
Hides the footnotes "back link" in the print version.
By "back link" I am referring to this thing ⬇️ 
The footnotes are numbered for easy reference. Having the "back link" in the print version just adds noise as they are really only intended for the web. 
https://trello.com/c/SJyttlVo
> Hide footnotes backlink in print version

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
* Fix layout header component in IE ([PR #1760](https://github.com/alphagov/govuk_publishing_components/pull/1760))
* Hide footnotes backlink in print version ([PR #1759](https://github.com/alphagov/govuk_publishing_components/pull/1759))
> Version 23.2.1

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/analytics/init.js
- spec/javascripts/components/cookie-banner-spec.js
- spec/javascripts/govuk_publishing_components/analytics/auto-track-event.spec.js
- spec/javascripts/govuk_publishing_components/analytics/download-link-tracker.spec.js
- spec/javascripts/govuk_publishing_components/analytics/mailto-link-tracker.spec.js
- spec/javascripts/govuk_publishing_components/analytics/static-analytics-spec.js
Change how variables for the ga property and cross domain tracking configuration are passed to the `analyticsInit` function.
A previous change passed these variables to the `analyticsInit` function so that different applications could use different configurations. Turned out that this approach didn't work with the cookie banner, because it also calls the same function as part of its internal code, and can't access those variables.
Passing these variables from an application into multiple places is too complicated, so the solution is to define the variables as attached to the GOVUK object, so they can be referenced from anywhere in the code.
This requires some tweaks to the tests to make them pass correctly. There are still some issues with the tests that will be addressed prior to the big …
> Change how analytics variables are passed

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
* Change how analytics variables are passed ([PR #1762](https://github.com/alphagov/govuk_publishing_components/pull/1762))
Note: this would be a breaking change if we were using this analytics code in production anywhere yet, but we're not.
> Version 23.3.0

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/_image-card.scss
The [`-ms-high-contrast-adjust` property](https://developer.mozilla.org/en-US/docs/Archive/Web/CSS/-ms-high-contrast-adjust) prevents IE modifying the background colour and hiding the text and image in high contrast mode.
When Windows is in high contrast mode, IE will remove convert any transparency and this element will then block the image and title text being visible. High contrast mode also seems to disable the z-index.
Before:
After:
> Fix image card link text in high contrast mode in IE

- app/assets/javascripts/govuk_publishing_components/lib/govspeak/magna-charta.js
- app/views/govuk_publishing_components/components/docs/govspeak.yml
- spec/javascripts/govuk_publishing_components/lib/govspeak/magna-charta-spec.js
Makes sure that Magna Charta (which is used by the Govspeak component) can correctly render charts when tables with row headings are used.
Adds an example of a chart with multiple headings to the Govspeak component docs.
And adds a test to make sure that tables with row headers are rendered correctly.
Govspeak (the markdown gem) can now generated tables with row headings using the correct `th` element. Previously these were unavailable, which led to a lot of tables that couldn't be understood by assistive technologies such as screenreaders.
But using a `th` as a row heading broke Magna Charta's automatically generated chart - the `th` would be ignored and the first `td` used instead. This has led to charts being incorrectly displayed.
Example table:
```html
<table …
```
> Fix chart glitch when source table has row headers

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
* Bump govuk-frontend from 3.8.1 to 3.9.1 ([PR #1705](https://github.com/alphagov/govuk_publishing_components/pull/1705))
* Fix image card link text in high contrast mode in IE ([PR #1732](https://github.com/alphagov/govuk_publishing_components/pull/1732))
> Release v23.4.0

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/components/details.js
- spec/javascripts/components/details-spec.js
Converts track options correctly when passed in
To allow options to be passed into track event function
none
https://trello.com/c/3U1QEEK1/584-add-event-tracking-to-track-how-many-times-request-accessible-format-is-clicked
> Converts track options correctly when passed in

- CHANGELOG.md
- app/views/govuk_publishing_components/components/contextual_sidebar/_brexit_cta.html.erb
- config/locales/cy.yml
- config/locales/en.yml
- spec/components/contextual_sidebar_spec.rb
- spec/features/contextual_navigation_spec.rb
Updates the heading of the transition sidebar navigation section to reflect the changes elsewhere.
I've also switched to using translation files as this allows us to send viewers of Welsh content to https://www.gov.uk/transition.cy. We don't have translations for the wording at present, so I've added an English language attribute to the section, as it'll always render in this language until we add more translations.
We've updated the taxon to say "Brexit transition", so this should stay in step with that.
https://trello.com/c/2xCCiDu4/598-update-transition-period-sidebar-navigation
Just a text update (apologies for the ropy screenshots)
> Update transition sidebar navigation

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
Includes:
- [Update Brexit sidebar navigation](https://github.com/alphagov/govuk_publishing_components/pull/1777)
> Bump version to 23.5.1

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/lib/govspeak/magna-charta.js
- app/views/govuk_publishing_components/components/docs/govspeak.yml
Within `govspeak` `magna-charta` stacked charts, hiding zeros
+
updating docs with example.
Zendesk ticket flagged an issue regarding overlapping zeros from Content teams when using Stacked charts
After [discussion (ticket)](https://trello.com/c/ghmrZy8g) solution was to hide zeros.
**Before:**
**After:**
---
The new element to appear [within the docs](https://components.publishing.service.gov.uk/component-guide/govspeak)
[Example page where this type of chart is used](https://www.gov.uk/government/publications/coronavirus-job-retention-scheme-statistics-october-2020/coronavirus-job-retention-scheme-statistics-october-2020#employments-furloughed-over-time-by-gender)
- Attention on this type of chart highlighted some other usability concerns (eg The "total" number isn't clear, this is a …
> Hide zero values

- CHANGELOG.md
- app/views/govuk_publishing_components/component_guide/show.html.erb
For some unknown (and potentially unintended) reason we only show the GitHub usage link if the component has a description definition in the associated yaml. This results in some components missing the link. I fixed this by moving the link outside the conditional statement.
To have the GitHub usage link visible on all components.
<table>
</td></tr>
</table>
> Fix GitHub usage link not showing for all components

- CHANGELOG.md
- app/views/govuk_publishing_components/components/_attachment.html.erb
- app/views/govuk_publishing_components/components/docs/attachment.yml
- spec/components/attachment_spec.rb
Introduce ability to override default `heading_level` on the attachment
component.
The component is currently hard coded to use `h2` which isn't very
flexible. This component is often used as a child of a section of a
page, in which case the heading level of the component should be
adjusted to reflect the hierarchy of the content.
No visual changes should occur as a result.
https://trello.com/c/KzyicaBh
> Add heading level to attachment component

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
Includes:
* Fix hide zeros values within stacked barcharts ([PR #1776](https://github.com/alphagov/govuk_publishing_components/pull/1776))
* Fix GitHub usage link not showing for all components ([PR #1780](https://github.com/alphagov/govuk_publishing_components/pull/1780))
* Add heading level to attachment component ([PR #1781](https://github.com/alphagov/govuk_publishing_components/pull/1781))
> Bump version to 23.6.0

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/_all_components.scss
- app/assets/stylesheets/govuk_publishing_components/components/_contextual-sidebar.scss
- app/assets/stylesheets/govuk_publishing_components/components/_transition-countdown.scss
- app/views/govuk_publishing_components/components/_contextual_sidebar.html.erb
- app/views/govuk_publishing_components/components/_transition_countdown.html.erb
- app/views/govuk_publishing_components/components/docs/contextual_sidebar.yml
- app/views/govuk_publishing_components/components/docs/transition_countdown.yml
- config/locales/cy.yml
- config/locales/en.yml
- lib/govuk_publishing_components.rb
- lib/govuk_publishing_components/app_helpers/countdown_helper.rb
- spec/component_guide/component_index_spec.rb
- spec/components/transition_countdown_spec.rb
- spec/features/contextual_navigation_spec.rb
- spec/lib/govuk_publishing_components/app_helpers/countdown_helper_spec.rb
- spec/rails_helper.rb
- Add transition countdown component based on the existing Rails logic in `collections` (credits to @hannako for the great work on the countdown mechanism) and a simplified and improved frontend approach
- Show the transition countdown component in the contextual sidebar
The component is meant to be used on:
- the `/transition` landing page (replacing the current countdown in [`collections`](https://github.com/alphagov/collections/compare/use-transition-countdown-component?expand=1))
- in the contextual sidebar across multiple frontend applications (`frontend`, `government-frontend` and `smart-answers`) when a page is not tagged to a 'brexit' taxon and doesn't show a step-by-step navigation.
[Trello card](https://trello.com/c/GX0JVZ3D)
[Preview countdown …
> Add transition countdown component

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
* Add transition countdown component ([PR #1783](https://github.com/alphagov/govuk_publishing_components/pull/1783))
--
Note the item was misplaced under 23.6.0 at rebase
> Release 23.7.0

- CHANGELOG.md
- app/views/govuk_publishing_components/components/_contextual_sidebar.html.erb
Update data attributes when calling the transition countdown in the contextual sidebar to match the expectation of our tracking script that lives in static.
The script requires `data-module="track-click"` to pick-up data-track attributes and have refactored the dimension approach to avoid previous encoding issues.
> Update contextual sidebar data track attributes

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
* Update contextual sidebar data track attributes ([PR #1788](https://github.com/alphagov/govuk_publishing_components/pull/1788))
> Release 23.7.1

- app/views/govuk_publishing_components/components/_contextual_sidebar.html.erb
- app/views/govuk_publishing_components/components/_related_navigation.html.erb
- app/views/govuk_publishing_components/components/_transition_countdown.html.erb
- app/views/govuk_publishing_components/components/related_navigation/_section.html.erb
- lib/govuk_publishing_components/presenters/related_navigation_helper.rb
- lib/govuk_publishing_components/presenters/shared_helper.rb
- spec/lib/govuk_publishing_components/components/shared_helper_spec.rb
Update the countdown component to check whether a translation is available before setting the language element; and set the direction to `ltr`.
When used on pages that are in right to left lanuages (such as Arabic) and without a translation available, the countdown displayed the number of days left in reverse. 
It was also tagged as being in the page's language even when there was no translation available, which led to the countdown displaying English but being tagged as being in another language.
The translation check is done for the "components.related_navigation.transition.title" key only as I think that it's a reasonable assumption that if the title isn't translated then the text won't be either. Ideally there would be a check for both, but for the moment this will ensure that it is …
> Brexit countdown language and direction fix

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
Includes:
- Fix Brexit countdown in the contextual sidebar to use appropriate lang and text direction ([PR #1790](https://github.com/alphagov/govuk_publishing_components/pull/1790))
> Update to v23.7.2

- app/assets/javascripts/govuk_publishing_components/lib/govspeak/magna-charta.js
- app/assets/stylesheets/govuk_publishing_components/components/govspeak/_charts.scss
- app/assets/stylesheets/govuk_publishing_components/components/mixins/_govuk-template-link-focus-override.scss
- app/assets/stylesheets/govuk_publishing_components/components/print/_accordion.scss
- package.json
- yarn.lock
Most notably this PR changes this project from using [standard](https://github.com/standard/standard) to [standardx](https://github.com/standard/standardx) for JS linting. The reason for this change is to allow the editing of rules, which allows us to disable the [no-var](https://eslint.org/docs/rules/no-var) rule.
It also upgrades stylelint-config-gds from a pre-release version to the actual released version and upgrades other yarn packages.
Across GDS we've been caught off-guard by the switch to requiring `let` or `const` over `var` in our JS applications. Switching to using this approach would mean that the JavaScript we would produce consistent syntax errors in IE versions before 11. Whilst we only provide limited support for these older browsers we're not yet ready for all JS to …
> Update yarn linters

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/component_support.scss
- app/assets/stylesheets/govuk_publishing_components/components/_search.scss
Text bleeds outside the bounding box within the UI search input element - while zooming-text-only at 200% within Firefox, this disrupts the experience for users that have increased their text sizes (a11y)
Using existing helper to resolve. [Ticket 1](https://trello.com/c/xjR2uZnf) & [Ticket 2](https://trello.com/c/4ydEeRoq)
As pixels are being used for layout / positioning and not relative units the element doesn't scale correctly text only zoom is used.
The Design System tackles this / solves this problem by using:
```
@if $govuk-typography-use-rem {
height: govuk-px-to-rem(34px);
}
```
I believe this will be a short-term fix while most apps go through a migration to adopt the Design System fully.
Before
After
This update also impacts other uses of Search, Before:
After 
IE11 testing:
IE8 …
> Fix to resolve input zoom-text overlap

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/govspeak/_steps.scss
Updating the current list bullet numbered SVG into a responsive version so it scales correctly via zoom-text-only / improves a11y considerations 
_"Step numbers don't get bigger with bigger font size"_ - [Ticket] (https://trello.com/c/RurRepSL)
Fail of WCAG SC 1.4.4
[Example page under _FOI request_](https://www.gov.uk/government/organisations/companies-house)
Before > After (100% - Chrome)
Before > After (@ 200% - Firefox)
Before > After (100% - Firefox)
Before > After (@ 200% - Firefox)
IE11 
Vertically aligns better for FF and uses "NTA" font when available.
> Update to responsive bullet SVG

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
Includes:
* Fix to update the current list bullet numbered SVG into a responsive version so it scales correctly via zoom-text-only / improves a11y considerations ([PR #1799](https://github.com/alphagov/govuk_publishing_components/pull/1799))
> Update to v23.7.4

- CHANGELOG.md
- app/views/govuk_publishing_components/components/docs/subscription-links.yml
- config/locales/en.yml
- lib/govuk_publishing_components/presenters/subscription_links_helper.rb
- spec/components/subscription_links_spec.rb
Update subscription links default text
This has been an agreed content change for emails links as we move away
from the terminology 'alert'.
Also removes the `default` argument as I'm struggling to see why we need
it in this instance. Using `default` also meant that a misconfigured locale
path was being covered up which has been corrected.
Trello:
https://trello.com/c/ssSnzp2L/640-remove-alert-from-all-the-sign-up-links
> Update subscription links default email link text

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
Trello:
https://trello.com/c/ssSnzp2L/640-remove-alert-from-all-the-sign-up-links
> Version 23.7.5

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/_share-links.scss
This changes the share links columns to use `em` values instead of `px` which means that the width of the link containers increase proportionately to the font size. This should make for a better experience for users who use the text zoom setting in their browser.
When increasing the font size to 200%, some of the social media links
are overlapping, making them unreadable for users who use this setting.
https://trello.com/c/1nrlxFEB
> Amend share links columns spacing

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
Bump gem to  version `23.7.6`
Includes #1800
> Bump to 23.7.6

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/analytics/pii.js
- spec/javascripts/govuk_publishing_components/analytics/pii.spec.js
Add some new redactions to remove PII from URLs. This is targeted specifically at parameters in URLs in GOV.UK Accounts, so the matching is relatively simple.
The things that are appearing in URLs could be linked to specific users so we need to remove these values.
None.
Trello card: https://trello.com/c/bjcoDa2N/462-remove-or-redact-potential-pii-from-urls
> Add some GOV.UK Accounts specific PII redacts

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
* Add some GOV.UK Accounts specific PII redacts ([PR #1807](https://github.com/alphagov/govuk_publishing_components/pull/1807))
> Version 23.7.7

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/components/show-password.js
- app/assets/stylesheets/govuk_publishing_components/_all_components.scss
- app/assets/stylesheets/govuk_publishing_components/components/_show-password.scss
- app/views/govuk_publishing_components/components/_show_password.html.erb
- app/views/govuk_publishing_components/components/docs/show_password.yml
- config/locales/en.yml
- spec/components/show_password_spec.rb
- spec/javascripts/components/show-password-spec.js
Adds a new component for a password input including a show/hide button to toggle the display of the password. Uses the input component.
We have some (limited) research suggesting it's a feature users want for the GOVUK Accounts registration flow.
Build notes:
- the feature works by toggling the input type between `password` and `text`, which makes the text visible
- because this is a JS only feature all of the extra elements are added using JS, which means that if JS is disabled the input appears as normal
- the text for all of the content comes from data attributes appended to the DOM, which in turn comes from the translation files, so this can be translated if needed
- the button remains to the right of the input except on mobile, where it stacks, and the full text is visible
Browser …
> Add password reveal component

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
* Add password reveal component ([PR #1794](https://github.com/alphagov/govuk_publishing_components/pull/1794))
Includes a correction to the CHANGELOG - the show password component seems to have been listed in release 23.7.7 for some reason.
> Version 23.8.0

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
* Add support for secondary solid buttons ([PR #1814](https://github.com/alphagov/govuk_publishing_components/pull/1814))
> bump to 23.9.0

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
* Disable the transition countdown on a certain page ([PR #1821](https://github.com/alphagov/govuk_publishing_components/pull/1821))
> Release 23.9.1

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/_search.scss
Fix to resolve visual mis-alignment on certain uses of the search gem component
As part of [this PR](https://github.com/alphagov/govuk_publishing_components/pull/1793) this introduced an issue, I noticed there were other instances of the search that were being impacted by this change. This PR is a fix to resolve noticed issues.
**Before** (left) **After** (right)
[Gem mobile use](https://components.publishing.service.gov.uk/component-guide/search) - fix
Gem Desktop (use slight misalignment)
Various other uses no visual change
> Fix for search input misalignment

- app/views/govuk_publishing_components/components/docs/image_card.yml
Replaced the random kitten placeholder images with non-random images.
The example image used for the large image was also 404-ing, so I replaced it.
Whilst place kitten is the second best placeholder service available, it supplies random images - which doesn't play well with visual regression tests. Replacing it with a non-random image means that the visual regression tests won't flag a page as having changed.
No layout changes - just the images have been changed.
Before; image doesn't load as it violated the content security policy:
After:
> Replaces the random placekitten image placeholder

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/components/show-password.js
This is aiming to fix a bug where in the context of a form that contains a show password component, when the user hits Enter on any of the input fields in the form, the browser toggles the passwords visibility (instead of the expected behaviour, which would be to submit the form).
[Recording of the problem](https://drive.google.com/file/d/1soIp-4pWwtnvdD0ttJ_dySnesAmlN-w4/view?usp=sharing) 
The browser assumes that if you press the enter key in any of the fields, you want to submit the form and fires the click event on the first button, even when the button is not `type="submit"`. On a form that contains this component, the 1st button could be the Show/Hide form button, hence this bug.
Adding `type="button"` attribute to the show/hide element would resolve this issue, as it would now be …
> Add type="button" to Show/Hide password button

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/_show-password.scss
It looks like user agent stylesheets are adding margin top and bottom to the show/hide password button, causing some slight misalignment on macOS Safari as well as iOS Chrome and Safari browsers. This overrides those default styles so that the button aligns properly with the input field.
iOS Safari before |  iOS Safari after
------------ | -------------
https://trello.com/c/aJeQWmOS
> Amend Show/Hide password button CSS

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/analytics.js
- app/assets/javascripts/govuk_publishing_components/analytics/explicit-cross-domain-links.js
- spec/javascripts/govuk_publishing_components/analytics/explicit-cross-domain-links.spec.js
Add a data attribute to indicate a link or form should be decorated as if it were a cross-domain link.
GOV.UK uses cross-domain analytics (only if the user has consented to cookies on both domains, of course) to give a joined up view of how users interact with government. So naturally this has to work with GOV.UK Accounts too, or we’ll have an ever-growing blind spot in this joined up view.
Cross-domain analytics works by sticking a `_ga` query param onto cross-domain links, which the analytics code at the link destination picks up. The problem is that with accounts, most of the cross-domain stuff is in the form of OAuth journeys: we have cross-domain *redirects*. So we have non-cross-domain links which may do a cross-domain redirect; for example, navigating from an unauthenticated part …
> Add a data attribute to indicate a link or form should be decorated as if it were a cross-domain link

- CHANGELOG.md
Looks like this was introduced by accident in #1811
> Remove git conflict/merge marker from changelog

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
* Add a data attribute to indicate a link or form should be decorated as if it were a cross-domain link ([PR #1811](https://github.com/alphagov/govuk_publishing_components/pull/1811))
> Bump to 23.10.0

- spec/javascripts/components/show-password-spec.js
Update `show password` component spec to check that the type of the password visibility toggle button is "button".
Following on from this PR where I implemented the change but I forgot to update the test:
https://github.com/alphagov/govuk_publishing_components/pull/1826
> Update show password component tests

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/lib/govspeak/youtube-link-enhancement.js
Replaces unstable method of setting the title to a stable method
The previous way was unstable and youtube changes these variables on a regular basis
> Fixes youtube title bug

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
Includes
* Fixes youtube title bug ([PR #1835](https://github.com/alphagov/govuk_publishing_components/pull/1835))
> Bump version to 23.0.1

- CHANGELOG.md
- lib/govuk_publishing_components.rb
See https://github.com/alphagov/govuk_publishing_components/pull/1831 this PR is opened to fix that one being closed by mistake.
> Fix Rails deprecation warning for autoloading during initialisation 

- CHANGELOG.md
- lib/govuk_publishing_components/app_helpers/countdown_helper.rb
- spec/lib/govuk_publishing_components/app_helpers/countdown_helper_spec.rb
Update the Brexit CountdownClock component so that it is hidden from 23.30 on Brexit eve. 
Currently the component is set to turn itself off at the midnight.  Due to caching, this might leave us in a situation where we are still showing the countdown after midnight. 
There are no visual changes.
Related PR: https://github.com/alphagov/collections/pull/2184
---
[Trello](https://trello.com/c/NrxFXJ0e/726-update-logic-to-remove-countdown-visual-at-1130pm-vs-1159pm-on-31-december?menu=filter&filter=member:jessjones11)
> Turn off the Brexit Countdown Clock at 23.30

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
- Fix Rails deprecation warning for autoloading during initialisation
- Turn off the Brexit countdown clock at 23.30 on Brexit eve
> Version 23.10.2

- CHANGELOG.md
- lib/govuk_publishing_components/version.rb
https://trello.com/c/zshkcMQl/743-deploy-31-12-1045pm-update-brexit-transition-sidebar-section-3
https://trello.com/c/8w2ti59g/756-deploy-31-12-1045pm-replace-brexit-branded-sidebar-element-4
This is not a breaking change, since the countdown component only
had one consumer, which is no longer using it.
> Bump version to 23.11.0

- CHANGELOG.md
- config/locales/cy.yml
- config/locales/en.yml
Update Brexit CTA copy in the contextual sidebar component
See background in [Trello card](https://trello.com/c/vFkN8alA)
<table>
</td></tr>
</table>
> Update Brexit CTA copy in contextual sidebar

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
* Update Brexit CTA copy in contextual sidebar ([PR #1851](https://github.com/alphagov/govuk_publishing_components/pull/1851))
* Extend component auditing ([PR #1796](https://github.com/alphagov/govuk_publishing_components/pull/1796))
Note the `Gemfile.lock` was not updated in https://github.com/alphagov/govuk_publishing_components/pull/1846, hence the jump from 23.10.2 to 23.11.1
> Release 23.11.1

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/analytics/external-link-tracker.js
- app/assets/javascripts/govuk_publishing_components/analytics/pii.js
- spec/javascripts/components/checkboxes-spec.js
- spec/javascripts/components/cookie-banner-spec.js
- spec/javascripts/components/details-spec.js
- spec/javascripts/components/feedback-spec.js
- spec/javascripts/components/select-spec.js
- spec/javascripts/components/step-by-step-nav-spec.js
- spec/javascripts/components/toggle-spec.js
- spec/javascripts/govuk_publishing_components/analytics/analytics.spec.js
- spec/javascripts/govuk_publishing_components/analytics/auto-track-event.spec.js
- spec/javascripts/govuk_publishing_components/analytics/download-link-tracker.spec.js
- spec/javascripts/govuk_publishing_components/analytics/ecommerce.spec.js
- spec/javascripts/govuk_publishing_components/analytics/error-tracking.spec.js
- spec/javascripts/govuk_publishing_components/analytics/external-link-tracker.spec.js
- spec/javascripts/govuk_publishing_components/analytics/google-analytics-universal-tracker.spec.js
- spec/javascripts/govuk_publishing_components/analytics/mailto-link-tracker.spec.js
- spec/javascripts/govuk_publishing_components/analytics/pii.spec.js
- spec/javascripts/govuk_publishing_components/analytics/scroll-tracker-spec.js
- spec/javascripts/govuk_publishing_components/analytics/static-analytics-spec.js
- spec/javascripts/govuk_publishing_components/lib/track-click.spec.js
- spec/javascripts/helpers/SpecHelper.js
Make changes to the analytics code in the gem, ready for use on live GOV.UK, to replace the existing copy of the code in `static`.
- improve how analytics code is called in the tests and modify previous tests that mocked the analytics objects (causing the new analytics tests to fail)
- re-enable and fix disabled tests in external link tracker and ecommerce analytics tests
- copy across changes in analytics code in static made since the analytics code was copied into the gem
We want to get this analytics code ready for use in production.
None.
Trello cards:
- https://trello.com/c/p3UtkNtE/420-resolve-the-two-copies-of-analytics-code
- https://trello.com/c/epZ12grR/110-migrate-analytics-code-into-the-gem
> Get analytics code ready for use in production

- app/views/govuk_publishing_components/components/_machine_readable_metadata.html.erb
- spec/components/machine_readable_metadata_spec.rb
Trello: https://trello.com/c/YhIIykse/2291-3-fix-cross-site-scripting-vulnerabilities
Applies sanitisation to structured data JSON in the machine readable
metadata component.
`json_escape` replaces `&`, `>` and `<` characters with their
unicode equivalents: https://apidock.com/rails/ERB/Util/json_escape
I've managed to retain the pretty-print functionality, after
initially plugging this hole with a `.to_json`, which ActiveRecord
escapes automatically.
Currently, any HTML included in the structured data gets rendered
as-is, breaking the validity of the page and opening up an attack
vector whereby the publisher could inject arbitrary JavaScript
into the page (however unlikely). It should be sanitised before it
is rendered.
N/A
> Escape dangerous HTML in 'Machine readable metadata' component

- CHANGELOG.md
- lib/govuk_publishing_components/version.rb
This release also contains some dependency bumps via #1856, #1857,
#1859 and #1860. I've deliberately ignored #1838 as it is a
minor bump and is likely to affect how things render visually, so
best reviewed manually by a frontend dev.
Trello: https://trello.com/c/YhIIykse/2291-3-fix-cross-site-scripting-vulnerabilities
> Bump to 23.12.1

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/_show-password.scss
- Edge and IE11 now include their own 'show password' option in password inputs
- while this doesn't interfere with our custom functionality to do this, it is a little odd to have both of them there
- fortunately it can be removed using this bit of CSS
Background: https://textslashplain.com/2020/07/29/revealing-passwords/
Edge before:
IE11 before:
After is basically the same thing but without the little eye icon, e.g.
> Hide native browser show password

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/lib/govspeak/magna-charta.js
- app/assets/stylesheets/govuk_publishing_components/components/govspeak/_charts.scss
- spec/javascripts/govuk_publishing_components/lib/govspeak/magna-charta-spec.js
Alters the behaviour for magna charta rendered bar charts for screen reader users.
Currently, screen reader users will only be able to interpret the table portion of the chart, regardless of if it's visible or not, and ignore the toggle button and visualised chart entirely. This PR alters the behaviour to the following:
1. Screen reader users will encounter the button first, which will dictate to them "Change to table and accessible view".
2. If they try to interact with the chart, the message: "This content is not accessible - switch to table" will be announced.
2. When they click the button, "table visible" will be announced.
3. The user can now interact with the table.
4. Clicking the link again, which will now read "Change to chart view" will swap back to chart and announce "chart …
> Update magna charter experience for screen reader users

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
* Hide native browser show password ([PR #1863](https://github.com/alphagov/govuk_publishing_components/pull/1863))
* Update magna charter experience for screen reader users ([PR #1787](https://github.com/alphagov/govuk_publishing_components/pull/1787))
> Bump components gem to version 23.12.2

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/print/_govspeak.scss
Adds `display: none` to print styling for specific elements within the magna charta bar chart component.
To address a bug raised for print styles where bar charts will duplicate data on print due to the chart element and the original table both being visible.
[Card](https://trello.com/c/a1wOFE76/2006-markdown-charts-dont-print)
> Add print styling for magna charta component

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/_layout-footer.scss
Fix a layout bug in Firefox that was causing single column list items to column wrap into the next column. Wasn't occurring in any other browsers, because apparently only Firefox doesn't support the `break-inside` property, so this is a bit of a workaround, but including it for other browsers just in case.
Tested in Firefox, Chrome, Edge, everything back to IE8.
The layout footer component is now being used live, in Accounts 😱 
Before: 
After:
> Fix text overflow bug in Firefox

- CHANGELOG.md
- app/views/govuk_publishing_components/components/_layout_header.html.erb
- app/views/govuk_publishing_components/components/docs/layout_header.yml
- app/views/govuk_publishing_components/components/layout_header/_navigation_items.html.erb
- spec/components/layout_header_spec.rb
Introduce the ability to pass a custom `aria-label` to the layout header navigation. 
Set the aria label to "Top level" by default – this was previously set on the `nav` element's child `ul`, however it makes more sense to add the `aria-label` to the `nav` itself, for screen reader users who navigate pages by navigation landmarks.
On the GOVUK Account there are a few pages with more than one `nav` element on the page. When there are multiple navigation landmarks of the same kind on a page, they should be labelled in order to help assistive tech users differentiate between them as per [WCAG SC 2.4.1: Bypass Blocks](https://www.w3.org/WAI/WCAG21/Understanding/bypass-blocks).
This change will allow us to be more descriptive in the way we label landmarks, and tailor these labels for different …
> Add custom aria label option for layout header nav

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/modules.js
- spec/javascripts/govuk_publishing_components/modules.spec.js
Change the scope to document rather than just body
This is done to support module within the head ie. on meta tags.
This also brings the scope in line with GOVUK Design system where document is used rather than the body.
> Change GOVUK Modules scope to document

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
Includes:
* Fix text overflow bug in Firefox ([PR #1764](https://github.com/alphagov/govuk_publishing_components/pull/1764))
* Tidy component filenames ([PR #1848](https://github.com/alphagov/govuk_publishing_components/pull/1848))
* Add print styling for magna charta component ([PR #1867](https://github.com/alphagov/govuk_publishing_components/pull/1867))
* Add custom aria label option for layout header nav ([PR #1865](https://github.com/alphagov/govuk_publishing_components/pull/1865))
* Change GOVUK Modules scope to document ([PR #1869](https://github.com/alphagov/govuk_publishing_components/pull/1869))
> Bump gem version to 23.12.3

- CHANGELOG.md
- app/views/govuk_publishing_components/components/docs/meta_tags.yml
- lib/govuk_publishing_components/presenters/meta_tags.rb
Update's the documentation for the meta tags component and adds the possible attributes of `section` and `navigation-page-type`.
[The meta tags component documentation](https://components.publishing.service.gov.uk/component-guide/meta_tags) previously only contained sparse details for the `organisation` and `world-locations` analytics tags despite being quite a powerful component with a lot of rendering options. This change exposes said options, allowing for easier analysis and extension of the component in future.
No user facing visual changes.
[Card](https://trello.com/c/AomyVLLP/551-investigate-and-update-collections-to-use-meta-tag-component)
> Update documentation for the meta tags component

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
* Update documentation for the meta tags component ([PR #1870](https://github.com/alphagov/govuk_publishing_components/pull/1870))
> Bump gem release to 23.13.0

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/components/step-by-step-nav.js
- app/assets/stylesheets/govuk_publishing_components/components/_step-by-step-nav.scss
- app/views/govuk_publishing_components/components/_step_by_step_nav.html.erb
- config/locales/en.yml
- spec/javascripts/components/step-by-step-nav-spec.js
Updates the design of the [step by step navigation component](https://components.publishing.service.gov.uk/component-guide/step_by_step_nav), specifically:
- Add an up/down chevron icon for improved visual affordance
- Move the show/hide all button at the top of the component over to the left so that it's easier for zoomed screen users to use
- Alter spacing
This is part of an effort to align the different types of accordion across govuk to follow a single style and reduce confusion for users and meet [WCAG SC 3.2.4](https://www.w3.org/TR/UNDERSTANDING-WCAG20/consistent-behavior-consistent-functionality.html).
[Card](https://trello.com/c/S4Yr0CgY/606-update-step-by-step-accordion)
> Update design for step by step navigation to improve accessibility

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
* Bump govuk-frontend from 3.9.1 to 3.10.2 ([PR #1838](https://github.com/alphagov/govuk_publishing_components/pull/1838))
* Update design for step by step navigation to improve accessibility ([PR #1875](https://github.com/alphagov/govuk_publishing_components/pull/1875))
> Bump gem version to 23.13.1

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/_document-list.scss
- app/views/govuk_publishing_components/components/_document_list.html.erb
- app/views/govuk_publishing_components/components/docs/document_list.yml
A few updates to [the document list component](https://components.publishing.service.gov.uk/component-guide/document_list):
1. Adds a `full_size_description` modifier to `link` objects that increases the size of description text to the standard 19.
2. Amends the design of list items.
3. Remove some unnecessary margin from the `subtext` element
This is prompted by work within the govuk accessibility team whilst assessing if we should replace the [list of links on the contacts page](https://www.gov.uk/contact) with the document list component. We've decided to proceed with this on the condition that we make a couple of design amends for the new context, the principal change being allowing for full size description text.
The design change to list items is something that has been planned …
> Update document list component with description text modifier and amended design

- CHANGELOG.md
- app/assets/images/govuk_publishing_components/take-action-amber.svg
- app/assets/images/govuk_publishing_components/take-action-green.svg
- app/assets/images/govuk_publishing_components/take-action-red.svg
- app/assets/stylesheets/govuk_publishing_components/components/_contextual-sidebar.scss
- app/views/govuk_publishing_components/components/_contextual_sidebar.html.erb
- app/views/govuk_publishing_components/components/contextual_sidebar/_brexit_cta.html.erb
- app/views/govuk_publishing_components/components/contextual_sidebar/_brexit_related_links.html.erb
- app/views/govuk_publishing_components/components/docs/contextual_sidebar.yml
- config/initializers/assets.rb
- config/locales/cy.yml
- config/locales/en.yml
- lib/govuk_publishing_components/presenters/contextual_navigation.rb
- spec/components/contextual_sidebar_spec.rb
- spec/features/contextual_navigation_spec.rb
Update branded Brexit sidebar navigation placement, visual and logic
To drive engagement through a more targeted approach
[Preview component](https://govuk-publis-update-bre-vsk8qa.herokuapp.com/component-guide/contextual_sidebar/with_brexit_cta/preview)
<table>
</td></tr>
</table>
<table>
<tr><th>AT</th><th>Result</th></tr>
<tr><td valign="top">JAWS on Chrome</td><td valign="top">
Brexit campaign slogan. Check, change, go. Check what you need to do. link
</td></tr>
<tr><td valign="top">NVDA on Firefox</td><td valign="top">
Brexit campaign slogan. Check, change, go. Check what you need to do. link
</td></tr>
<tr><td valign="top">VoiceOver on iOS</td><td valign="top">
Link, Brexit campaign slogan, Check, …
> Update Brexit CTA on contextual sidebar

- CHANGELOG.md
- app/views/govuk_publishing_components/components/_layout_footer.html.erb
The main `class` declaration for the footer component was missing a closing `"`. Then I decided to make it more readable as well.
None.
> Fix footer classes

- app/models/govuk_publishing_components/component_doc.rb
Changes the github search query to remove `govuk_publishing_` from the current search query (`org:alphagov govuk_publishing_components/components/[component_id]`), leaving the current query as:
```
org:alphagov components/components/[component_id]
```
The usage search feature in our component docs (the link that reads "Search for usage of this component on GitHub" on each component page) hasn't been working for a month or so. Exactly why isn't clear, there's a suspicion that this was just an update to github's punctuation settings on search. This solution gets around these weird rules by removing the underscores from before the first slash. It's a bit of a janky solution, ideally we'd search for the string like before for more consistent coverage, but it does work.
Docs …
> Fix github searching for components

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/_feedback.scss
Alters some minor styling for the feedback component.
This is to address https://github.com/alphagov/govuk_publishing_components/issues/1825 and https://github.com/alphagov/govuk_publishing_components/issues/1889. The first issue is addressed by removing a now unnecessary `after` styling rule. The second by moving the js hiding styles to the bottom of the stylesheet to prevent them being undermined by style rules that cascade later in the stylesheet.
> Fix bugs on the feedback component

- CHANGELOG.md
- app/views/govuk_publishing_components/components/_layout_footer.html.erb
The `layout_footer` currently used in Accounts does not have the same data attributes for tracking as the footer on the main site. 
Add data attributes for click tracking to the layout footer component to match the attributes of the hard coded footer in static.
I hard coded `data-track-category` to `footerClicked` as it the value of this attribute should be the same for every link in the footer.
So that we can have click event tracking on the GOVUK Account footer. 
Goes hand in hand with this [pull request](https://github.com/alphagov/govuk-account-manager-prototype/pull/665).
------
https://trello.com/c/9A6UPqi8
> Add data attributes to layout footer component

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/_document-list.scss
- app/views/govuk_publishing_components/components/_document_list.html.erb
- app/views/govuk_publishing_components/components/docs/document_list.yml
- spec/components/document_list_spec.rb
Adds an optional attribute to the document list component that removes the border visual element from document list items.
The document list component is currently being used in collections publisher and content publisher and the recent visual change was missed in these apps and [caused some visual disparity](https://github.com/alphagov/govuk_publishing_components/pull/1883). This removes the border element which is the source of said visual discrepancy. This decision is weighted by the fact that there is a plan to eventually [extract the docs list item as a standalone component](https://github.com/alphagov/govuk_publishing_components/compare/extract-document-item-component) meaning there is an appetite for this to not use the border in certain interfaces, such as the publishing apps.
> Add option to remove border from document list items

- CHANGELOG.md
- app/views/govuk_publishing_components/components/docs/layout_header.yml
- app/views/govuk_publishing_components/components/layout_header/_navigation_items.html.erb
- spec/components/layout_header_spec.rb
Add data attribute support on the layout header navigation links. 
The reason for this is because we are intending to use the `layout_header` component for the transition checker nav whose links are cross-domain links and need data attributes for tracking.
During development the markup for the account nav (appears on the transition page, and transition checker) was copied over from the layout header component instead of using the component itself. 
The component audits are now complaining that we are including the assets for `layout_header` in `static`, when we are not using the component.
To fix this problem and reduce repetition, we are removing the hard coded account navigation from static, and using the layout header component in its place: alphagov/static#2408 …
> Update layout header component

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/components/step-by-step-nav.js
- app/assets/stylesheets/govuk_publishing_components/components/_step-by-step-nav.scss
- app/assets/stylesheets/govuk_publishing_components/components/print/_step-by-step-nav.scss
- app/views/govuk_publishing_components/components/docs/contextual_sidebar.yml
Makes several design updates to the step by step:
- Alter vertical padding for step titles
- Adjust circle size, logic font size and number/logic positioning
- Reduce border width across component
- Add a black background to the "active" step circle
- Move the chevron icon to the right
- Add a customisation of the focus state for step titles
The root of this work comes from efforts by the govuk accessibility team to ensure that accordions across govuk are consistent and accessible.
This PR is an iteration on [the recently deployed update to the step by step component](https://github.com/alphagov/govuk_publishing_components/pull/1875). These design changes are both responses to feedback following launch and further improvements based on further conversations between our designer and the …
> Further step by step nav sidebar design updates

- CHANGELOG.md
- app/views/govuk_publishing_components/components/_document_list.html.erb
- app/views/govuk_publishing_components/components/docs/document_list.yml
- spec/components/document_list_spec.rb
Add a `rel` option to the document list component which gets applied to the markup as an attribute on the document link.
We use the `rel` attribute in govuk content to dictate links to external sites, principally for use by search engines. This has emerged as a requirement for the document list component where it's being used to link to external sites. [Read more about what the rel attribute is and how it can be used here](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/rel).
> Add rel attribute option to document list

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/components/cookie-banner.js
Remove `listenForCrossOriginMessages` from `CookieBanner` JS module
This function is a leftover from https://github.com/alphagov/govuk_publishing_components/pull/995 and it's not being used.
Thanks to @36degrees for spotting this!
> Remove listenForCrossOriginMessages from CookieBanner

- CHANGELOG.md
- lib/govuk_publishing_components/presenters/contextual_navigation.rb
Instead of hiding the Brexit CTA on all answer pages, we were meant to only hide it on answer pages that have a start button, which unfortunately requires hardcoding their document IDs.
A misinterpretation of product requirements in #1888 led to a considerable decrease in engagement rate on answer pages (without a start button) which were driving significant traffic to `/transition`.
Example: https://www.gov.uk/call-charges
Details: answer page without start button, tagged to corporate-information
<table>
</td></tr>
</table>
[Trello card](https://trello.com/c/XmaPJL11)
> Rescope Brexit CTA on contextual sidebar

- app/assets/stylesheets/govuk_publishing_components/components/govspeak/_contact.scss
- app/views/govuk_publishing_components/components/docs/govspeak.yml
Update `govspeak` contact information to remove bold
Contact information should not be in bold. This is confusing as it looks like a heading but is not: [(WCAG 1.3.1)](https://www.w3.org/WAI/WCAG21/Understanding/info-and-relationships.html) Also at present it is a `h3` which wasn't always accurate in terms of a `h2` always being before it in the context of the page.
Before (left) After (right)
The gem absorbs `govspeak` [there is a dependant PR here.](https://github.com/alphagov/govspeak/pull/206)
> Update contact heading

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/_list.scss
- spec/components/all_components_spec.rb
Removes the unnecessary list stylesheet. Updates the audit to cope with the list component not having a stylesheet.
The list styles are imported with the core parts of GOV.UK Frontend into the [component support stylesheet][1], so the standalone list stylesheet isn't required.
[1]: https://github.com/alphagov/govuk_publishing_components/blob/c25fba341c13e270ae44e8d0add1d02d8e2c0404/app/assets/stylesheets/govuk_publishing_components/component_support.scss#L4
None.
> Remove unneeded list stylesheet

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
* Bump govuk-frontend from 3.10.2 to 3.11.0 ([PR #1911](https://github.com/alphagov/govuk_publishing_components/pull/1911))
* Rescope Brexit CTA on contextual sidebar ([PR #1910](https://github.com/alphagov/govuk_publishing_components/pull/1910))
* Update `govspeak` contact heading ([PR #1909](https://github.com/alphagov/govuk_publishing_components/pull/1909))
* Remove `listenForCrossOriginMessages` from CookieBanner ([PR #1906](https://github.com/alphagov/govuk_publishing_components/pull/1906))
* Further step by step nav sidebar design updates ([PR #1893](https://github.com/alphagov/govuk_publishing_components/pull/1893))
* Add rel attribute option to document list ([PR #1903](https://github.com/alphagov/govuk_publishing_components/pull/1903))
* BREAKING: Remove chevron banner component …
> Release 24.0.0

- CHANGELOG.md
- app/views/govuk_publishing_components/components/_layout_footer.html.erb
- app/views/govuk_publishing_components/components/layout_header/_header_logo.html.erb
Change value of `data-module` attribute to "gem-track-click" on the layout header and layout footer components.
The reason behind this change is that click tracking is not working on these elements on GOVUK Accounts. 
That is because Accounts does not use `static` and therefore also does not use the [track-click script](https://github.com/alphagov/static/blob/master/app/assets/javascripts/modules/track-click.js) which  enables click tracking on modules with the `data-module="track-click"` attribute.
Changing the value of this attribute to "gem-track-click" means that the header and footer will work with the [component gem's track-click script](https://github.com/alphagov/govuk_publishing_components/blob/master/app/assets/javascripts/govuk_publishing_components/lib/track-click.js) instead. …
> Update data-module on layout header and footer

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
Includes 
* Update `data-module` on layout header and footer ([PR #1913](https://github.com/alphagov/govuk_publishing_components/pull/1913)) – Patch/fix
* Update design of accordion component ([PR #1884](https://github.com/alphagov/govuk_publishing_components/pull/1884)) – Minor
> Bump gem to 24.1.0

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/govuk_frontend_support.scss
Clean up `govuk_frontend_support.scss`
It's [recommended to import base instead of settings, tools, helpers](https://github.com/alphagov/govuk-frontend/blob/master/CHANGELOG.md#import-settings-tools-and-helpers-css-in-one-line) since `govuk-frontend` 3.7.0
The [FCDO colour is already available](https://github.com/alphagov/govuk-frontend/blob/master/CHANGELOG.md#fixes-5) since `govuk-frontend` 3.9.0 
In `govuk-frontend` 4.0.0 we [won't be able to import `core` and `overrides` without `base`](https://github.com/alphagov/govuk_publishing_components/blob/master/app/assets/stylesheets/govuk_publishing_components/component_support.scss#L4-L7), which means that our [`component_support.scss`](https://github.com/alphagov/govuk_publishing_components/blob/master/app/assets/stylesheets/govuk_publishin …
> Update `govuk-frontend` base SCSS imports

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/_accordion.scss
- app/assets/stylesheets/govuk_publishing_components/components/print/_accordion.scss
Remove redundant import in the accordion component that was accidentally introduced in #1884. 
We do however need it for the print stylesheet, as we have two [applications requiring the `components/print/accordion` but not the `component_support`](https://github.com/alphagov/collections/blob/master/app/assets/stylesheets/print.scss#L2). This could potentially be fixed in future by removing `component_support` from `print/_accordion` and updating the suggested print imports to include `component_support`.
This import resulted in a considerable increase in our render-blocking resources.
> Remove redundant import in accordion component

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/_step-by-step-nav.scss
In #1893 we added an SVG to the step by step navigation continuing to rely on the same logic for tracking, but the way the toggle click tracking script is designed expects the element triggering the click event to be an HTMLElement, not a path element, which causes a hard error and fails to send data to GA. With this change, we avoid capturing events at the SVG level, which means they will bubble and be captured by the parent HTMLElement.
- step-by-step-nav script fails on pages when users click the SVG element
- we are losing tracking data since 9 Feb
Example page: https://www.gov.uk/apply-transit-visa
<table>
</td></tr>
No JavaScript errors …
> Fix toggle click tracking on step-by-steps

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/_accordion.scss
Summary margin tweak on the accordion 
Design adjustment requested
> Adjust margin

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/_layout-header.scss
Fix header navigation layout issue which happens on tablet breakpoints on GOVUK Accounts. 
Fix spacing issue which occurs when `layout_header` is used by applications using `static`.
Currently, the layout header component looks different in the context of `static` vs in isolation. This is because this component shares some classes with the hardcoded `#global-header` from static, as well as some layout classes from the Design System.  
- on the account manager, which does not use `static`, the layout header navigation does not align as intended with the rest of the header on tablet breakpoints
- in the context of an application that uses `static` (screenshots below are from `finder-frontend`), the layout header  inherits some styles from `static`. Additionally, application CSS conflicts …
> Fix layout_header layout and spacing issues

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
* Fix deprecation warnings when running tests ([PR #1899](https://github.com/alphagov/govuk_publishing_components/pull/1899))
* Update `govuk-frontend` base SCSS imports ([PR #1922](https://github.com/alphagov/govuk_publishing_components/pull/1922))
* Remove redundant import in accordion component ([PR #1923](https://github.com/alphagov/govuk_publishing_components/pull/1923))
* Fix toggle click tracking on step-by-steps ([PR #1925](https://github.com/alphagov/govuk_publishing_components/pull/1925))
* Accordion summary design adjustment ([PR #1926](https://github.com/alphagov/govuk_publishing_components/pull/1926))
* Fix `layout_header` layout and spacing issues ([PR #1924](https://github.com/alphagov/govuk_publishing_components/pull/1924))
> Release 24.1.1

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/components/cookie-banner.js
- app/assets/stylesheets/govuk_publishing_components/components/_cookie-banner.scss
- app/views/govuk_publishing_components/components/_cookie_banner.html.erb
- app/views/govuk_publishing_components/components/docs/cookie_banner.yml
- spec/components/cookie_banner_spec.rb
- spec/javascripts/components/cookie-banner-spec.js
Update cookies banner to inherit the Design System cookie banner component
This brings our cookie banner in line with the design system in terms of look and feel and follows their guidance for compliance. The biggest differences:
- Adds a reject button to the default implementation and plumbs it into the js
- Hides things with the hidden attribute instead of relying on styles (which fails if a user or browser blocks CSS)
- Use the new design system button group for button layout
- Made the hide button on the confirmation message look like a button
> Update cookies banner to align it with govuk-frontend

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
* Update cookies banner to align it with govuk-frontend ([PR #1918](https://github.com/alphagov/govuk_publishing_components/pull/1918))
> Release 24.2.0

- CHANGELOG.md
- app/assets/stylesheets/component_guide/application.scss
Fix cookie banner preview in the component guide
To be able to check the no-JS version. Fixes #1932.
No visual changes (apart from it appearing in the component guide preview).
<table>
</td></tr>
</table>
> Fix cookie banner preview in the component guide

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/analytics/scroll-tracker.js
Implement scroll tracking to coronavirus landing pages.
We will use the percentage format to track.
```
'/coronavirus': [
['Percent', 20],
['Percent', 40],
['Percent', 60],
['Percent', 80],
['Percent', 100]
],
```
All code changes sit here: https://github.com/alphagov/govuk_publishing_components/blob/master/app/assets/javascripts/govuk_publishing_components/analytics/scroll-tracker.js
We want to understand how far down the page users are going so we know that users are getting the relevant information.
https://trello.com/c/VRNHtbkc/162-scroll-tracking-on-landing-page
> Implements scroll tracking for the covid pages

- CHANGELOG.md
- app/views/govuk_publishing_components/audit/show.html.erb
- recent changes to the accordion had broken the accordions on the component auditing screens
- this wasn't the fault of the component, the markup for the auditing accordions was hard coded
- unsure why this was (even though I built it) but have replaced with the component (apparently successfully)
It was broken.
The only visual change is the accordion now uses the updated accordion design, but this is already known.
> Fix auditing screens

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/components/accordion.js
- app/views/govuk_publishing_components/components/_accordion.html.erb
- app/views/govuk_publishing_components/components/docs/accordion.yml
- spec/components/accordion_spec.rb
Applies an optional anchor navigation feature to accordions. This allows anchor links within accordions to:
- link to another accordion heading on the same page and automatically open that accordion
- link to an id anchor within an accordion on the same page and automatically open the containing accordion
- link to either of the above on different pages with the same setup (accordions with this feature flag) and open the associated accordion as above.
Additionally fixes a couple of typos in the accordions js and removes a line specifying data_attributes as `nil`. The latter is unnecessary and generates an extra `null` attribute on every item on the docs.
On manuals, there was previously a function to link between individual sections in manuals for ease of content. This was done by linking …
> Add anchor navigation feature to accordions

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
Includes:
* Fix cookie banner preview in the component guide ([PR #1935](https://github.com/alphagov/govuk_publishing_components/pull/1935))
* Implements scroll tracking for the covid pages ([PR #1942](https://github.com/alphagov/govuk_publishing_components/pull/1942))
* Add anchor navigation feature to accordions ([PR #1937](https://github.com/alphagov/govuk_publishing_components/pull/1937))
> Bump version to 24.3.0

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/_search.scss
This replaces the extending of a compound selector as this causes a
warning:
```
WARNING on line 80, column 13 of /Users/kevindew/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/govuk_publishing_components-24.1.1/app/assets/stylesheets/govuk_publishing_components/components/_search.scss:
Compound selectors may no longer be extended.
Consider `@extend .gem-c-search__input, [type="search"], :focus` instead.
See http://bit.ly/ExtendCompound for details.
```
In order to share this code I've added a placeholder so it can be
included in both places.
When comparing the before and after of this there is quite a lot of
changes to output CSS. With the previous version of this code there were
59 references to "#global-header .gem-c-search__input" compared to 1
afterwards.
```
cat …
```
> Fix Sass warning for extending a compound selector

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/_cookie-banner.scss
Add spacing to cookie banner confirmation message
It currently sits too close to the top of the browser
> Add spacing to cookie banner confirmation message

- CHANGELOG.md
- app/views/govuk_publishing_components/components/layout_header/_navigation_items.html.erb
Adds a default value for `navigation_aria_label` to the `navigation_items` sub-component.
Currently, `navigation_aria_label` is passed directly to `navigation_items` without any defaulting under the assumption that it's only used by `layout_header`. This however breaks [anything that's only using the separately exposed navigation_items](https://github.com/alphagov/datagovuk_find/blob/24a0ef70958720370a42e7daa7c7b1437fc4dada/app/views/layouts/_proposition_header.html.erb). Adding a default here allows the sub-component to render without needed to pass a custom aria label if it isn't required.
> Add default aria label for navigation items

- CHANGELOG.md
- app/views/govuk_publishing_components/components/_breadcrumbs.html.erb
- app/views/govuk_publishing_components/components/_contents_list.html.erb
- app/views/govuk_publishing_components/components/_cookie_banner.html.erb
- app/views/govuk_publishing_components/components/_highlight_boxes.html.erb
- app/views/govuk_publishing_components/components/_image_card.html.erb
- app/views/govuk_publishing_components/components/_metadata.html.erb
- app/views/govuk_publishing_components/components/_organisation_logo.html.erb
- app/views/govuk_publishing_components/components/_previous_and_next_navigation.html.erb
- app/views/govuk_publishing_components/components/_share_links.html.erb
- app/views/govuk_publishing_components/components/_step_by_step_nav_header.html.erb
- app/views/govuk_publishing_components/components/_step_by_step_nav_related.html.erb
- app/views/govuk_publishing_components/components/_subscription_links.html.erb
- app/views/govuk_publishing_components/components/_taxonomy_list.html.erb
- app/views/govuk_publishing_components/components/_translation_nav.html.erb
- app/views/govuk_publishing_components/components/contextual_sidebar/_brexit_cta.html.erb
- app/views/govuk_publishing_components/components/docs/inverse_header.yml
- app/views/govuk_publishing_components/components/related_navigation/_section.html.erb
- spec/components/breadcrumbs_spec.rb
- spec/components/contents_list_spec.rb
- spec/components/cookie_banner_spec.rb
- spec/components/image_card_spec.rb
- spec/components/organisation_logo_spec.rb
- spec/components/related_navigation_spec.rb
- spec/components/subscription_links_spec.rb
- spec/javascripts/components/cookie-banner-spec.js
Switch from using `trackClick` script from `static` to `gemTrackClick` script from this repo. They are virtually the same, the latter being [copied over from `static` to `govuk_publishing_components`](https://github.com/alphagov/govuk_publishing_components/pull/1751).
Part of [a bigger piece of work](https://github.com/alphagov/static/pull/2405) to reduce the size of assets served to users and keep our codebase to a minimum.
> Switch from trackClick to gemTrackClick script

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
* Switch from `trackClick` to `gemTrackClick` script ([PR #1944](https://github.com/alphagov/govuk_publishing_components/pull/1944))
* Add spacing to cookie banner confirmation message ([PR #1936](https://github.com/alphagov/govuk_publishing_components/pull/1936))
* Fix Sass warning for extending a compound selector ([PR #1933](https://github.com/alphagov/govuk_publishing_components/pull/1933))
* Add default aria label for navigation items (PR [#1946](https://github.com/alphagov/govuk_publishing_components/pull/1946))
> Bump release to 24.3.1

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/components/show-password.js
- app/views/govuk_publishing_components/components/_show_password.html.erb
- config/locales/en.yml
- spec/components/show_password_spec.rb
- spec/javascripts/components/show-password-spec.js
- adds an aria-label to the 'show/hide' button so that assistive tech reads it as 'show/hide password', which makes more sense out of context
- an accessibility audit revealed that the button out of context ('Show') isn't descriptive enough for users of assistive technology, and should be 'show password' instead, but we don't want to change the design because that text is too long on mobile
None.
Our password button says 'show' or 'hide', which has been highlighted as an accessibility fail because the button out of context doesn't make sense.
```
Non-Descriptive Labels (AA)
Labels did not sufficiently describe the topic or purpose of the content.
WCAG Reference:
2.4.6 Headings and Labels (Level AA)
```
The solution proposed by the audit is to add the word 'password' as a visually hidden …
> Show password fixes

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/_breadcrumbs.scss
- app/views/govuk_publishing_components/components/_breadcrumbs.html.erb
- app/views/govuk_publishing_components/components/docs/breadcrumbs.yml
- spec/components/breadcrumbs_spec.rb
Adds a parameter so a border can be added to the bottom of a breadcrumb.
This is needed so this component can be used in alphagov/manuals-frontend.
Desktop:
Mobile:
> Add bottom border option to breadcrumb

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
Includes:
* Add border option to breadcrumb ([PR #1952](https://github.com/alphagov/govuk_publishing_components/pull/1952)) MINOR
* Add custom heading level option to radio component ([PR #1951](https://github.com/alphagov/govuk_publishing_components/pull/1951))
> Bump gem to 24.4.0

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/components/details.js
- spec/javascripts/components/details-spec.js
Fix tracking in `details.js`
`TrackClick` (provided by static) was recently replaced with `GemTrackClick` (provided by govuk_publishing_components) after the analytics scripts have been ported from static to govuk_publishing_components. This instance has been missed at that point, which causes JS to crash on certain pages across GOV.UK.
This issues has been reported by @ChrisBAshton as the JS crash stopped the video render script in [`government-frontend`](https://www.integration.publishing.service.gov.uk/government/publications/uk-points-based-immigration-system-employer-information)
<table>
</td></tr>
</table>
> Fix tracking in details.js

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
* Fix tracking in `details.js` ([PR #1962](https://github.com/alphagov/govuk_publishing_components/pull/1962))
> Release 24.4.1

- app/views/govuk_publishing_components/components/_list.html.erb
- spec/components/list_spec.rb
The list component used the `sanitize` method. This has been swapped for the `raw` method. 
Tests to ensure that attributes on markup passed into component are unaltered have been added.
The sanitize method strips out elements and attributes that are not in an allowlist from a string, and then allows the string to be added as markup rather than being added as a string. This could strip out `data-` and other useful attributes given to the list component.
The `raw` method doesn't alter the markup - so any string passed into the component will be used verbatim. Since the strings being given to the list component come from within an application, we can presume these to be trustworthy.
None.
> Swap `sanitize` for `raw` in list component

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/_all_components_print.scss
This file imports "govuk/base" which is required to resolve a GOV.UK Frontend warning. This is attempt 2 following https://github.com/alphagov/govuk_publishing_components/pull/1934, this tries to be a more modest fix.
Before:
```
I, [2021-03-08T10:25:39.692458 #79055]  INFO -- : Writing /Users/kevindew/govuk/govuk_publishing_components/spec/dummy/public/assets/component_guide/visual-regression-7a6fbecb638d5f96b24d97212b0044b0b3d9e195c0ea5543612dba4347f5ec2e.js.gz
WARNING: Importing items from the core layer without first importing `base` is deprecated, and will no longer work as of GOV.UK Frontend v4.0.
on line 2:3 of node_modules/govuk-frontend/govuk/core/_links.scss
from line 1:9 of node_modules/govuk-frontend/govuk/core/_all.scss
from line 4:9 of …
```
> Fix GOV.UK Frontend deprecation warning for component-guide print stylesheet

- CHANGELOG.md
- app/views/govuk_publishing_components/components/_summary_list.html.erb
- spec/components/summary_list_spec.rb
Change how the edit/delete links are rendered in the summary list component. They were added inside a list, even if there was only one link. This change only renders the links inside a list if there is more than one of them.
This change applies to the links that can appear at the top of the component as well as the similar links that can appear on each row.
This was highlighted in a recent accessibility audit where only one link was present in a summary list component. A single link (already in a DD element) doesn't need wrapping in a list.
None. But here's an illustrative screenshot.
Trello card: https://trello.com/c/lNkwruEi/647-fix-accessibility-issues-raised-by-dac
> Remove lists from summary list action links

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/lib/header-navigation.js
- app/views/govuk_publishing_components/components/_search.html.erb
- app/views/govuk_publishing_components/components/docs/search.yml
- app/views/govuk_publishing_components/components/layout_header/_search.html.erb
- config/locales/en.yml
- spec/components/search_spec.rb
Adds the ability to set the visually hidden text in the search box button component.
Updates layout heading to use the search box component with the button text "Search GOV.UK".
Duplicate buttons on a page - for example, two buttons for different forms that both have the text "Search" - can lead to confusion for people who use assistive tech. Screen readers can collate all of the forms and buttons on a page, so duplicate text would make it harder to understand which button did what. Voice control relies on unique text, so saying "Click search" may end up with the wrong search button being clicked. 
No visual changes; the visually hidden text will be customisable:
And the layout header text has been updated:
> Update search box button

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/components/reorderable-list.js
- app/assets/stylesheets/govuk_publishing_components/_all_components.scss
- app/assets/stylesheets/govuk_publishing_components/components/_reorderable-list.scss
- app/views/govuk_publishing_components/components/_reorderable_list.html.erb
- app/views/govuk_publishing_components/components/docs/reorderable_list.yml
- govuk_publishing_components.gemspec
- package.json
- spec/components/reorderable_list_spec.rb
- spec/javascripts/components/reorderable-list-spec.js
- yarn.lock
A list of items that can be reordered
List items can be reordered by drag and drop or by using the up/down buttons. On small viewports the drag and drop feature is disabled to prevent being triggered when scrolling on touch devices.
This component uses SortableJS - a JavaScript library for drag and drop interactions. When JavaScript is disabled a set of inputs will be shown allowing users to provide an order index for each item.
This is used by publishing tools to allow reordering of lists such as steps in step by step, entries in timelines and order of visual presentation of attachments.
This is a port/extension of the work that @alex-ju has done on the content publisher app.
https://govuk-publis-add-reorde-g116bw.herokuapp.com/component-guide/reorderable_list …
> Adds Reorderable lists component

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
Includes:
* Remove lists from summary action links ([PR #1956](https://github.com/alphagov/govuk_publishing_components/pull/1956))
* Fix GOV.UK Frontend deprecation warning for component-guide print stylesheet ([PR #1961](https://github.com/alphagov/govuk_publishing_components/pull/1961))
* Update search box button ([PR #1957](https://github.com/alphagov/govuk_publishing_components/pull/1957))
* Adds Reorderable lists component ([PR #1905](https://github.com/alphagov/govuk_publishing_components/pull/1905))
> Release 24.5.0

- CHANGELOG.md
- app/views/govuk_publishing_components/components/_summary_list.html.erb
- app/views/govuk_publishing_components/components/docs/summary_list.yml
- spec/components/summary_list_spec.rb
- link titles for 'change' and 'delete' links by default are automatically generated based on the text 'Change/Delete [thing]' but this causes problems when the thing and the link text don't naturally follow
- adding in the option to pass explicit title attributes for the links
We've got a situation in Accounts where the text doesn't work with the automatically generated titles, so adding an option to pass explicit ones seems useful.
None.
> Add title option to summary list links

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/_summary-list.scss
- app/views/govuk_publishing_components/components/_summary_list.html.erb
- app/views/govuk_publishing_components/components/docs/summary_list.yml
- spec/components/summary_list_spec.rb
Does the following:
- adds an option to remove the visually hidden span the component automatically adds into link text, containing the row or overall name
- adds an option for a wider layout for the field name
The first change is because I have a situation where the text doesn't work for the default behaviour. The text would be `Change GOV.UK can send you feedback emails` - which doesn't make sense. Instead I'd like to be able to pass custom text without the component automatically appending visually hidden text that doesn't make sense.
The second change is because again the text I need to put in the component doesn't look great with the current layout.
No change for the first change, new layout option looks like this.
Trello card: …
> Summary list changes

- CHANGELOG.md
- app/views/govuk_publishing_components/components/_summary_list.html.erb
- app/views/govuk_publishing_components/components/docs/summary_list.yml
- spec/components/summary_list_spec.rb
Remove the title attributes from the links in the summary list component. These are automatically generated based on the link text and the thing they refer to, or passed to the component directly (a change I recently added).
We don't usually use the title attribute for links on GOV.UK, instead relying on visually hidden text within the link text. What's strange is that this component already does this, so the title attribute seems an unnecessary addition, particularly when the original component in the Design System doesn't have title attributes on links - https://design-system.service.gov.uk/components/summary-list/.
There's also evidence that screen readers treat it in various ways. Specifically https://www.deque.com/blog/text-links-practices-screen-readers/ highlights this, and this …
> Remove title attribute from summary list

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/components/accordion.js
Rework the anchor link navigation functionality of the accordion component to remove the hash from the id when navigating and use `getElementById` instead of `querySelector ` when searching for those anchor ids.
There is a pre-existing feature in manuals frontend that allows for the navigation between footnotes. These anchor links are marked up using the format of `fnref:[footnote number]`. [Example of this in use](https://www.gov.uk/guidance/drivers-hours-goods-vehicles/1-eu-and-aetr-rules-on-drivers-hours). `querySelector` doesn't like that colon in id queries because it [interferes with existing CSS syntax](https://bugzilla.mozilla.org/show_bug.cgi?id=883044). This change allows it to work and fixes this bug in manuals frontend. …
> Rework accordion anchor link nav to allow for colon anchors

- CHANGELOG.md
- app/views/govuk_publishing_components/components/_summary_list.html.erb
- app/views/govuk_publishing_components/components/docs/summary_list.yml
- spec/components/summary_list_spec.rb
- `link_text_no_enhance` for row links was being checked against the overall links for the component, so passing the parameter for the row when not passing it for the overall links had no effect
- tests were not specific enough to spot this
- now corrected
It weren't working.
None.
> Fix bug in summary list link text

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
* Fix bug in summary list link text ([PR #1978](https://github.com/alphagov/govuk_publishing_components/pull/1978))
> Version 24.6.1

- app/assets/stylesheets/component_guide/application.scss
Adds some padding to the simple component preview, to make component previewing on 'preview' and 'preview all' screens better.
I started work on a problem with the search component and found that on the 'preview all' screen the component on a dark background doesn't show the dark/blue background. Turns out that's because on those screens there's no padding, and the component completely covered the dark/blue background.
Yes, it indents the previews a little bit, but it does that on the main page already and I think being able to see the preview properly in context is worth it.
Before | After
> Fix component preview

- CHANGELOG.md
- app/views/govuk_publishing_components/components/docs/contextual_sidebar.yml
- lib/govuk_publishing_components/presenters/contextual_navigation.rb
- spec/components/contextual_sidebar_spec.rb
Rescope Brexit CTA to `en`/`cy` locale only
We want to show the Brexit CTA on pages written in English or Welsh.
[Trello card](https://trello.com/c/lbZWSsY9)
[Example of a page affected by this change, rendered by `government-frontend`](https://www.gov.uk/government/speeches/pursuing-the-elimination-of-the-syrian-chemical-weapons-programme.ar)
<table>
</td></tr>
</table>
> Rescope Brexit CTA to en/cy locale only

- CHANGELOG.md
- spec/javascripts/components/accordion-spec.js
Adds Jasmine tests for the accordion js
Addresses https://github.com/alphagov/govuk_publishing_components/issues/1960
> Add js tests for accordion component

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/_search.scss
Change the search component's label so that it looks less broken. This is surprisingly complex. There are several variants to consider:
- default behaviour
- on a blue background
- without a border, typically on a black background (referred to in the code as on a white background, confusingly)
For each variant of the component, we have to consider the following conditions.
- JS enabled: the label overlays the input, disappearing when clicked
- JS disabled: the label appears prior to the input (this is where the problem is)
- linearized: the label appears prior to the input, but JS may be enabled or disabled
The linearized state was highlighted in a past accessibility audit as not being displayed properly. A fix was applied. To see this page state, choose `Linearize Page` in the …
> Fix search component label background

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/_layout-for-public.scss
- app/assets/stylesheets/govuk_publishing_components/components/_layout-header.scss
- app/views/govuk_publishing_components/components/_layout_for_public.html.erb
- app/views/govuk_publishing_components/components/_layout_header.html.erb
- app/views/govuk_publishing_components/components/docs/layout_for_public.yml
- app/views/govuk_publishing_components/components/layout_header/_navigation_items.html.erb
- spec/components/layout_for_public_spec.rb
- spec/dummy/app/views/layouts/dummy_public_layout.html.erb
- spec/dummy/app/views/welcome/public_example.html.erb
Updates and tweaks to public layout to prepare it for use.
Added slots for the emergency banner and the global bar - these slots are just spaces that raw HTML will be added to the page. Whilst both the banner and the bar are [componentised in Static][1], moving those components to the components gem is outside of the scope of this pull request.
The blue border from the header component has been switched off, as the emergency banner needs to go between the black header and the blue bar - the header component didn't offer the ability to do this, so the blue bar is now an element in the public layout component. This was an easier path than editing the widely used header component.
The global bar has the blue header border built into it, which can clash with the fixed width blue border. A CSS …
> Allow emergency banner and global bar in public layout component

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/components/details.js
- app/assets/javascripts/govuk_publishing_components/modules.js
- spec/javascripts/govuk_publishing_components/modules.spec.js
- Amend JS modules initialiser code to account for the case where a GOVUK JS module has a GOVUK Frontend counterpart module which also needs to be initialised
- Add GOVUK Frontend's Details JS module to our own GOVUK Modules object so that the module can be initialised with the other modules
As part of the Accounts team's DAC report it was flagged that the `details` element was not functional in Internet Explorer and assistive tech was not able to interact with this component as expected.
Some investigation revealed that:
1. this is well known issue where all versions of Internet Explorer and Edge (pre-chromium) don't fully support details/summary: https://caniuse.com/details
2. on the Design System's version of the details component, the issue would not occur, which would suggest that …
> Add GOVUK Frontend Details module to GOVUK Modules and amend modules.js `start` function

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
* Add GOVUK Frontend Details module to GOVUK Modules and amend `modules.js` start function ([PR #1985](https://github.com/alphagov/govuk_publishing_components/pull/1985))
* Rescope Brexit CTA to en/cy locale only ([PR #1984](https://github.com/alphagov/govuk_publishing_components/pull/1984))
* Add JavaScript tests for accordion component ([PR #1977](https://github.com/alphagov/govuk_publishing_components/pull/1977))
* Fix search component label background ([PR #1983](https://github.com/alphagov/govuk_publishing_components/pull/1983))
* Allow emergency banner and global bar in public layout component ([PR #1978](https://github.com/alphagov/govuk_publishing_components/pull/1915))
> Release 24.7.0

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/_title.scss
- app/views/govuk_publishing_components/components/_title.html.erb
- spec/components/title_spec.rb
Instead of extending `govuk-heading-xl` in the Sass, this change updates the title component to use the `.govuk-heading-xl` in the markup. This allows importing of just the title component without any unnecessary styles.
Extending `%govuk-heading-l` forced the typography `core/typography` Sass from GOV.UK Frontend to be included - this caused unnecessary CSS to be included in the compiled stylesheet.
Removing the use of `extend` gives us a smaller stylesheet - for example, we can only import the `govuk_frontend_support` (which provides mixins, variables, and other, uh, _things_ for subsequent stylesheets but compiles to no CSS) and the title component stylesheet. 
For example:
```css
@import "govuk_publishing_components/component_support";
@import …
```
> Remove Sass `extend` from title component

- CHANGELOG.md
- app/views/govuk_publishing_components/components/_layout_footer.html.erb
- lib/govuk_publishing_components/presenters/public_layout_helper.rb
- spec/components/layout_footer_spec.rb
Update the default footer links in the [public layout component][1] to the current set as used on www.gov.uk
Added a condition to stop a single link in a multiple-width column from wrapping.
The default links were out of date.
Note - the colours of the live footer links are using the [older colour palette from `govuk_template`](https://github.com/alphagov/govuk_template/blob/134e8b910c5175d5f94b1f5c48fdc342bb5065c2/source/assets/stylesheets/_footer.scss#L17-L18), not the current more accessible colour palette from the [GOV.UK Design System](https://design-system.service.gov.uk/styles/colour/).
Before:
After:
What's currently live on www.gov.uk:
[1]: https://govuk-publis-update-foo-byame3.herokuapp.com/component-guide/layout_for_public
> Update default footer links

- CHANGELOG.md
- app/views/govuk_publishing_components/components/docs/button.yml
- lib/govuk_publishing_components/presenters/button_helper.rb
- spec/components/button_spec.rb
Change the `margin_bottom` option for the button component
- now accepts govuk-spacing scale value for variable margin
- also still accepts former option of `true` to add a custom margin class, so this isn't a breaking change
- will remove the 'true' option later
I wanted to use the `shared_helper` for this, but the button component has its own helper and I couldn't figure out how to call the one from the other. Instead, I've semi-replicated the code from the shared helper into the button, which probably works better for now as we need to preserve the existing 'true' option anyway, for backwards compatibility.
Note that this change also applies to the info text. When the button is given a margin, it's applied to the button. When info text is present, that margin is applied to the info …
> Change button margin option

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/lib/cookie-functions.js
Add a new cookie into the list of allowed cookies. This is being used for a personalisation experiment and is likely to be temporary.
None.
Trello card: https://trello.com/c/qm6BnJiO/680-public-holidays-location-experiment-fe
> Add a new cookie

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
Releases:
* Add cookie ([PR #1999](https://github.com/alphagov/govuk_publishing_components/pull/1999)) PATCH
* Change button margin option ([PR #1998](https://github.com/alphagov/govuk_publishing_components/pull/1998)) MINOR
* Add auditing to applications ([PR #1949](https://github.com/alphagov/govuk_publishing_components/pull/1949)) PATCH
* Update auditing ([PR #1996](https://github.com/alphagov/govuk_publishing_components/pull/1996)) PATCH
* Update default footer links ([PR #1989](https://github.com/alphagov/govuk_publishing_components/pull/1989)) PATCH
* Remove Sass `extend` from title component ([PR #1994](https://github.com/alphagov/govuk_publishing_components/pull/1994)) PATCH
> Release 24.8.0

- CHANGELOG.md
- Gemfile.lock
- app/assets/stylesheets/govuk_publishing_components/components/_success-alert.scss
- app/views/govuk_publishing_components/components/_success_alert.html.erb
- app/views/govuk_publishing_components/components/docs/success_alert.yml
- config/locales/en.yml
- spec/components/success_alert_spec.rb
Updates the [success alert component](https://components.publishing.service.gov.uk/component-guide/success_alert) to be inline with the design system [success variant of the notification banner component](https://design-system.service.gov.uk/components/notification-banner/).
This is a final piece of work to make sure that our cookie banner and general cookie strategy is inline with design system guidance. The design system [cookie page](https://design-system.service.gov.uk/patterns/cookies-page/) uses their notifications banner so this is just to make sure we're consistent.
[Card](https://trello.com/c/B3zI99d8/654-make-sure-cookies-page-is-in-line-with-design-system-guidance)
[Relevant page](https://www.gov.uk/help/cookies)
> Update success notice component

- CHANGELOG.md
- app/views/govuk_publishing_components/components/_success_alert.html.erb
- app/views/govuk_publishing_components/components/docs/success_alert.yml
- spec/components/success_alert_spec.rb
- Adds a hashed ID to the success alert heading ID
- Add the option to set a custom ID for the title and the `aria-labelledby`
- Removes an unnecessary `div` from the success alert markup
- Adds some guidance advising devs to pass sanitised/raw'd markup to the `description` attribute
In response to comments made by Alex post-merge on https://github.com/alphagov/govuk_publishing_components/pull/1929
> Tidy up success alert markup

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/_image-card.scss
- app/views/govuk_publishing_components/components/_image_card.html.erb
- app/views/govuk_publishing_components/components/docs/image_card.yml
- lib/govuk_publishing_components/presenters/shared_helper.rb
- spec/components/image_card_spec.rb
Adds an option to the image card to change the link size if needed. Uses a copy of the code from the heading helper, put into the shared helper, to do this.
(I'd change the heading component to use this new shared helper code but it's slightly different, I'll come back to it later)
Note that the link size is automatically the correct size for the 'large' version of the image card component, but can be overridden if needed.
The new GOV.UK roadmap page is going to use this component and it needs the links to be a different size.
No changes to the default state of the component, but here it is with the next option applied.
> Image card link size option

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
* Image card link size option ([PR #2007](https://github.com/alphagov/govuk_publishing_components/pull/2007))
* Update success notice component ([PR #1929](https://github.com/alphagov/govuk_publishing_components/pull/1929))
* Tidy up success alert markup ([PR #2004](https://github.com/alphagov/govuk_publishing_components/pull/2004))
> Release 24.9.0

- CHANGELOG.md
- lib/govuk_publishing_components/presenters/contextual_navigation.rb
We don't want the Brexit branding on pages tagged to these topics
> Change to the exceptions list for Brexit branding

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
Includes:
* Change to the exceptions list for Brexit branding #2011
> Release 24.9.1

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/components/accordion.js
- app/views/govuk_publishing_components/component_guide/show.html.erb
- app/views/govuk_publishing_components/components/_accordion.html.erb
- app/views/govuk_publishing_components/components/docs/accordion.yml
- config/locales/en.yml
- spec/javascripts/components/accordion-spec.js
User facing: Moves some loose content into our translation file.
Docs facing: Tidies up some of the accordion documentation, specifically removing unnecessary quote marks on single line content.
Principally best practice changes. Serving our content via translation files allows us to easily serve alternative content by locale in the event that it's required.
Addresses https://github.com/alphagov/govuk_publishing_components/issues/1941 and @andysellick's comment on https://github.com/alphagov/govuk_publishing_components/pull/1946
> Tidy up untranslated content and formatting on accordion docs

- .github/workflows/visual-regression-tests.yml
- CHANGELOG.md
- Gemfile.lock
- app/views/govuk_publishing_components/component_guide/index.html.erb
- govuk_publishing_components.gemspec
- package.json
- spec/spec_helper.rb
- spec/visual_regression_tests/all_components.rb
- spec/visual_regression_tests/all_components_spec.rb
- yarn.lock
Visual regression testing compares screenshots, highlighting any changes made. Taking the screenshots is reasonably easily, but the storage and approval of any changes is more difficult. Enter Percy - a useful tool to do both store the screenshots and approve them. 
Percy is run in a GitHub Action which is triggered when a pull request is marked as **ready for review**. This is to cut down on the number of screenshots taken - a single round of visual regression tests takes about 300 screenshots. Triggering this on every push would likely use up all of our allowance.
Percy has been set up to only use one browser, but due to a known bug with Percy this won't happen until Percy can compare against the main branch.
With the number of components contained in this repo, it can be useful to run …
> Add visual regression testing tool Percy

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/lib/govspeak/magna-charta.js
- app/assets/stylesheets/govuk_publishing_components/components/_action-link.scss
- app/assets/stylesheets/govuk_publishing_components/components/_button.scss
- app/assets/stylesheets/govuk_publishing_components/components/_contextual-sidebar.scss
- app/assets/stylesheets/govuk_publishing_components/components/_highlight-boxes.scss
- app/assets/stylesheets/govuk_publishing_components/components/_previous-and-next-navigation.scss
- app/assets/stylesheets/govuk_publishing_components/components/_print-link.scss
- app/assets/stylesheets/govuk_publishing_components/components/_related-navigation.scss
- app/assets/stylesheets/govuk_publishing_components/components/_share-links.scss
- app/assets/stylesheets/govuk_publishing_components/components/_step-by-step-nav-related.scss
- app/assets/stylesheets/govuk_publishing_components/components/_subscription-links.scss
- app/assets/stylesheets/govuk_publishing_components/components/_translation-nav.scss
- app/assets/stylesheets/govuk_publishing_components/components/govspeak/_button.scss
- app/assets/stylesheets/govuk_publishing_components/components/govspeak/_charts.scss
- app/assets/stylesheets/govuk_publishing_components/govuk_frontend_support.scss
- app/views/govuk_publishing_components/components/_highlight_boxes.html.erb
- app/views/govuk_publishing_components/components/_previous_and_next_navigation.html.erb
- app/views/govuk_publishing_components/components/_print_link.html.erb
- app/views/govuk_publishing_components/components/_share_links.html.erb
- app/views/govuk_publishing_components/components/_step_by_step_nav_related.html.erb
- app/views/govuk_publishing_components/components/_subscription_links.html.erb
- app/views/govuk_publishing_components/components/_translation_nav.html.erb
- app/views/govuk_publishing_components/components/contextual_sidebar/_brexit_cta.html.erb
- lib/govuk_publishing_components/presenters/related_navigation_helper.rb
- spec/components/step_by_step_nav_related_spec.rb
- spec/features/step_nav_helper_spec.rb
Removes the use of `@extend` from the 
* subscription links
* step by step
* related navigation
* contextual sidebar
* Magna Charta
* highlight boxes
* translation navigation
* share links
* print link
* previous and next link
* image card
components' stylesheets and moves the extended classes into the markup.
To enable the component to be used when only importing `frontend_support`.
The subscription links, step by step, related navigation, contextual sidebar, and Magna Charta components all `@extend` parts of GOV.UK Frontend, so they need 
```scss
@import "govuk_publishing_components/component_support";
```
in order to work. This increases the size of the stylesheets being served. For example:
```scss
@import "govuk_publishing_components/component_support";
@import …
```
> Remove `@extend` from component Sass

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/_layout-header.scss
- app/views/govuk_publishing_components/components/_layout_header.html.erb
Fix layout-header by removing overrides
The new layout header component is currently only used (via static) in [collections](https://www.gov.uk/transition) and [finder-frontend](https://www.gov.uk/transition-check/questions) – part of the Accounts journey. We currently have an issue with the alignment of this component with the main container and it seems like removing these overrides fixes the issue.
<table>
</td></tr>
</td></tr>
</td></tr>
</table>
> Remove grid overrides in layout-header 

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
* Tidy up untranslated content and formatting on accordion docs ([PR #1958](https://github.com/alphagov/govuk_publishing_components/pull/1958)) PATCH
* Add visual regression testing tool Percy ([PR #1013](https://github.com/alphagov/govuk_publishing_components/pull/1013)) PATCH
* Remove `@extend` from component Sass ([PR #2002](https://github.com/alphagov/govuk_publishing_components/pull/2002)) PATCH
* Remove grid overrides in layout-header ([PR #2013](https://github.com/alphagov/govuk_publishing_components/pull/2013)) PATCH
> Release 24.9.2

- CHANGELOG.md
- app/views/govuk_publishing_components/components/feedback/_yes_no_banner.html.erb
- config/locales/en.yml
- spec/components/feedback_spec.rb
Updates wording of issue reporting button on feedback component from...
>There is something wrong with this page
to...
>Report a problem with this page
This is in response to feedback from the content community on the feedback component wording to clearly communicate what the button is for to users.
[Card](https://trello.com/c/rasDOIGP/583-update-wording-of-theres-something-wrong-with-this-page-button-to-match-keiths-suggestion)
| --- | --- |
| ![Screenshot 2021-04-20 at 10 16 51](https://user-images.githubusercontent.com/64783893/115371726-23209f80-a1c2-11eb-8b1e-e5fb81650b9f.png) | ![Screenshot 2021-04-20 at 10 17 11](https://user-images.githubusercontent.com/64783893/115371685-1ac86480-a1c2-11eb-9873-8e2f5d67e463.png) |
> Change wording of report a problem button on feedback component

- app/views/govuk_publishing_components/components/docs/success_alert.yml
Adds some guidance to the success alert documentation for if you're using links in your success alert content.
To comply with Design System guidance on this topic. More info here https://github.com/alphagov/govuk_publishing_components/issues/2008
> Update success alert docs to include links guidance

- CHANGELOG.md
- app/views/govuk_publishing_components/components/related_navigation/_section.html.erb
- lib/govuk_publishing_components/presenters/related_navigation_helper.rb
Remove the `govuk-link` class from headings in the component. This was being inserted because of a recent change to stop using Sass's `extend` feature. Unfortunately in this case the method for generating classes that had been given the `govuk-link` class was being used for both links and headings, where inserting the `govuk-link` class by default wasn't correct.
Fixes https://github.com/alphagov/govuk_publishing_components/issues/2018
Fixes a very small visual bug with the headings, returning to the intended visual appearance. See the linked issue for details.
> Remove govuk-link class from headings

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/_contextual-sidebar.scss
- app/views/govuk_publishing_components/components/contextual_sidebar/_brexit_cta.html.erb
- config/locales/cy.yml
- config/locales/en.yml
Removing the Check, Change, Go traffic light section of the Brexit navigation.
We're removing this to avoid overlap with the new rules around Coronavirus travel which also uses a red, amber, green style. 
https://trello.com/c/vNhkoqGr/1462-remove-the-check-change-go-visual-in-the-brexit-sidebar-navigation-to-avoid-confusion-with-upcoming-rag-guidance
- [example page on review app](https://government-f-test-brexi-phy2vc.herokuapp.com/guidance/free-courses-for-jobs)
- [current page on GOV.UK](https://www.gov.uk/guidance/free-courses-for-jobs)
> Remove traffic light indicators from Brexit nav

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/_contextual-sidebar.scss
- app/views/govuk_publishing_components/components/contextual_sidebar/_brexit_cta.html.erb
- config/locales/cy.yml
- config/locales/en.yml
Convert Brexit CTA into a standard link. Follow up on #2024.
Now that we don't have any additional graphics that need to be incorporated in this navigation element, we can convert it into a standard navigation link, similar to the other ones in the contextual sidebar.
No visual changes except for focus state – see below
<table>
</td></tr>
</table>
[Trello card](https://trello.com/c/vNhkoqGr)
> Convert Brexit CTA into a standard link

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
* Remove govuk-link class from headings ([PR #2020](https://github.com/alphagov/govuk_publishing_components/pull/2020))
* Change wording of report a problem button on feedback component ([PR #2021](https://github.com/alphagov/govuk_publishing_components/pull/2021))
* Remove traffic light indicators from Brexit nav ([#PR2024](https://github.com/alphagov/govuk_publishing_components/pull/2024))
* Convert Brexit CTA into a standard link ([#PR2026](https://github.com/alphagov/govuk_publishing_components/pull/2026))
> Release 24.9.3

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/analytics/scroll-tracker.js
**What:**
Set up scroll tracking on the PCR test start page. https://www.gov.uk/get-coronavirus-test
We would be interested in understanding how far users scroll down the page by %
How far do users scroll?
How many users scroll to the green button?
How many read the content underneath the green button?
We're interested in whether the large amount of guidance on the page is confusing people and causing them to miss the green button, which is towards the bottom of the page. We're also interested in how many people read the information below the green button. 
**Why:**
So that we understand how the start page is currently performing, and decide what iteration or future research is needed,
**Who to work with:**
Rob and Harriet are gathering insights for the PCR start page
Ronan and Hannah are …
> Set up scroll tracking for the PCR test start page

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
* Set up scroll tracking for the PCR test start page ([PR #2028](https://github.com/alphagov/govuk_publishing_components/pull/2028))
> Bump version to 24.9.4

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/_notice.scss
- app/views/govuk_publishing_components/components/_notice.html.erb
Update notice component to not use `@extend` on links inside the component - swapped out `@extend`ing `govuk-link` for a lower-level `@include` of the govuk link styles for no visual difference.
Using `@extend` means that the `component_support` Sass file is required, can lead to accidental unnecessary CSS without realising it, and is incompatible with the `gem_layout` in Static.
None.
> Update notice component to not use `@extend`

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/components/show-password.js
- app/views/govuk_publishing_components/components/_show_password.html.erb
- app/views/govuk_publishing_components/components/docs/show_password.yml
- spec/components/show_password_spec.rb
- spec/javascripts/components/show-password-spec.js
Allow data attributes to be passed to the show password component. This basically passes them to the input component, which the show password component wraps (interestingly the ability to pass data attributes to the input component doesn't appear to be documented, but you can do it, leading to a possible discussion about components not only wrapping other components but relying on aspects of their API).
However, the complexity is that I don't want data attributes on the input, I want them on the show/hide button. This is generated by JS, so I've added a bit to the script to check for any data attributes that start with `data-button-` and move them onto the button. It's a bit convoluted, but it works, and I'm not sure how else to do it without hard coding something.
We want to add tracking …
> Add data attributes to show password component

- package.json
- yarn.lock
Update the Percy agent dev dependency from v0.9.0 to v0.28.6.
This dependency is ignored by dependabot to reduce pull request noise, but has meant that this hasn't been updated in so long that a security update is required.
None.
> Update Percy agent dependency

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/_accordion.scss
- app/assets/stylesheets/govuk_publishing_components/components/_search.scss
- app/assets/stylesheets/govuk_publishing_components/components/_step-by-step-nav.scss
- app/assets/stylesheets/govuk_publishing_components/components/helpers/_px-to-em.scss
The [`em()` function][1] converts from pixels to em and is identical to the [`govuk-em()` function][2]. Swapping the functions means no change in functionality. The `govuk-em()` function is included in the `govuk_frontend_support` Sass.
Added a `@warn` message to say that the `em()` function could be removed in a future major release.
Both functions are identical and can be swapped by changing the function name with no difference in output. This reduces the amount of helpers we have to maintain.
[1]: https://github.com/alphagov/govuk_publishing_components/blob/037ce27f3e05973c60d1522bcd113677cc6e7122/app/assets/stylesheets/govuk_publishing_components/components/helpers/_px-to-em.scss
[2]: https://github.com/alphagov/govuk-frontend/blob/c8d2deddc2cf7fa6d116f2af320b322f23856689/package/govuk …
> Swap out Sass `em()` function for `govuk-em()`

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/components/accordion.js
Updating to use polyfill version for `forEach` for IE11
The Accordion on the gem docs was being visually duplicated.
Before
After 
_"`querySelectorAll()` is a method which return a `NodeList`. And on [Internet Explorer](
https://caniuse.com/mdn-api_nodelist_foreach), `foreach()` only works on Array objects. (It works with NodeList with ES6, not supported by IE11)."_ [ref](https://stackoverflow.com/questions/55741747/javascript-foreach-loops-not-working-on-ie11)
[Related PR](https://github.com/alphagov/govuk_publishing_components/pull/1937)
> Resolve IE11 accordion gem doc duplication

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
Includes:
* Resolve IE11 accordion gem doc duplication ([PR #2036](https://github.com/alphagov/govuk_publishing_components/pull/2036))
* Add data attributes to show password component ([PR #2025](https://github.com/alphagov/govuk_publishing_components/pull/2025))
* Update documentation about component conventions and visual regression testing ([PR #2015](https://github.com/alphagov/govuk_publishing_components/pull/2015))
* Remove `@extend` from notice component styles ([PR #2030](https://github.com/alphagov/govuk_publishing_components/pull/2030))
* Swap out Sass `em()` function for `govuk-em()` ([PR #2034](https://github.com/alphagov/govuk_publishing_components/pull/2034))
> Release v24.10.0

- .gitignore
- CHANGELOG.md
- Gemfile.lock
- app/views/govuk_publishing_components/components/_government_navigation.html.erb
- app/views/govuk_publishing_components/components/_layout_header.html.erb
- app/views/govuk_publishing_components/components/_metadata.html.erb
- app/views/govuk_publishing_components/components/_previous_and_next_navigation.html.erb
- app/views/govuk_publishing_components/components/_step_by_step_nav.html.erb
- app/views/govuk_publishing_components/components/_step_by_step_nav_related.html.erb
- app/views/govuk_publishing_components/components/_subscription_links.html.erb
- app/views/govuk_publishing_components/components/_success_alert.html.erb
- app/views/govuk_publishing_components/components/layout_header/_navigation_items.html.erb
- app/views/govuk_publishing_components/components/metadata/_sentence.html.erb
- app/views/govuk_publishing_components/components/related_navigation/_section.html.erb
- config/locales/en.yml
- govuk_publishing_components.gemspec
- spec/spec_helper.rb
This PR adds the [i18n-coverage gem](https://github.com/hiptest/i18n-coverage) to monitor untested i18n keys. I've then removed used the coverage reports to identify and remove unused keys. See commits for details.
Trello: https://trello.com/c/Z3Pitrfg/2454-identify-and-remove-unused-keys-in-locale-files-5
N/A
> Remove unused i18n keys

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/analytics/pii.js
- spec/javascripts/govuk_publishing_components/analytics/pii.spec.js
Fixing the postcode regex to not match UUIDs
The postcode regex that we use often matches UUIDs that are in page URL query strings. These UUIDs are used to show different types of navigation on a page, so are significant for analysis terms.
I've attempted to fix this by adding word boundaries around the regex. Matching a sequence of characters that look like postcode format in a longer string seems a bit eager.
The example provided by the performance analyst was:
https://www.gov.uk/search/services?parent=%2Ftransition&topic=d6c2de5d-ef90-45d1-82d4-5f2438369eea
is being stripped to:
https://www.gov.uk/search/services?parent=/transition&topic=[postcode]5d-ef90-45d1-82d4-5f2438369eea
which is not useful.
https://trello.com/c/fxEriQnM/1489-redact-pii-from-ga-in-a-less-aggressive-manner
None
> Update postcode regex for PII stripping

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/_govspeak.scss
- app/assets/stylesheets/govuk_publishing_components/components/govspeak/_advisory.scss
- app/assets/stylesheets/govuk_publishing_components/components/govspeak/_attachment.scss
- app/assets/stylesheets/govuk_publishing_components/components/govspeak/_button.scss
- app/assets/stylesheets/govuk_publishing_components/components/govspeak/_call-to-action.scss
- app/assets/stylesheets/govuk_publishing_components/components/govspeak/_charts.scss
- app/assets/stylesheets/govuk_publishing_components/components/govspeak/_contact.scss
- app/assets/stylesheets/govuk_publishing_components/components/govspeak/_example.scss
- app/assets/stylesheets/govuk_publishing_components/components/govspeak/_footnotes.scss
- app/assets/stylesheets/govuk_publishing_components/components/govspeak/_form-download.scss
- app/assets/stylesheets/govuk_publishing_components/components/govspeak/_fraction.scss
- app/assets/stylesheets/govuk_publishing_components/components/govspeak/_highlight-answer.scss
- app/assets/stylesheets/govuk_publishing_components/components/govspeak/_images.scss
- app/assets/stylesheets/govuk_publishing_components/components/govspeak/_information-callout.scss
- app/assets/stylesheets/govuk_publishing_components/components/govspeak/_legislative-list.scss
- app/assets/stylesheets/govuk_publishing_components/components/govspeak/_place.scss
- app/assets/stylesheets/govuk_publishing_components/components/govspeak/_stat-headline.scss
- app/assets/stylesheets/govuk_publishing_components/components/govspeak/_steps.scss
- app/assets/stylesheets/govuk_publishing_components/components/govspeak/_summary.scss
- app/assets/stylesheets/govuk_publishing_components/components/govspeak/_tables.scss
- app/assets/stylesheets/govuk_publishing_components/components/govspeak/_typography.scss
- app/assets/stylesheets/govuk_publishing_components/components/govspeak/_warning-callout.scss
Adds the `govspeak` class alongside the `gem-c-govspeak` class - this makes sure that the `govspeak` has the same output as `gem-c-govspeak` for minimal additional CSS.
There are many many many places where the older `govspeak` class is used on elements that wrap around content, rather than `gem-c-govspeak`. This class comes as part of the content from the content store (eg [in `details.body` in the cabinet office content][1].
Adding the legacy class as a fix is easier and safer that changing the myriad of places where this is added - around [7K places across alphagov][2]).
This is not the ideal fix - that would be to change Whitehall et al to output `<div class="gem-c-govspeak">` -  this will do for now, and will help ensure that there are no unstyled elements whilst this change occurs. …
> Add legacy `govspeak` class alongside gem govspeak

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
Includes:
- Remove unused i18n keys ([PR #2038](https://github.com/alphagov/govuk_publishing_components/pull/2038))
- Update postcode regex for PII stripping ([PR #2043](https://github.com/alphagov/govuk_publishing_components/pull/2043))
- Add legacy `govspeak` class alongside gem-c-govspeak ([PR #2044](https://github.com/alphagov/govuk_publishing_components/pull/2044))
> Release 24.10.1

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/_metadata.scss
- app/views/govuk_publishing_components/components/_metadata.html.erb
- config/locales/en.yml
- spec/components/metadata_spec.rb
Update's the design of the [metadata block component](https://components.publishing.service.gov.uk/component-guide/metadata) along with some general tidying. The specifics:
- Restyles the data term and definition on desktop so that there is no longer a gap between the two
- Removes the colon next to the "published" and "updated at" terms
- Creates translation keys which previously didn't exist
- Give the associated files a bit of a spring clean
This design existed in government frontend but was [accidentally overwritten](https://github.com/alphagov/government-frontend/pull/2026) by work by govuk accessibility during our component update work. This change benefits screen magnification users as it will be easier for them to reach information when zoomed in.
A more detailed note from our …
> Update design of metadata component

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/analytics/scroll-tracker.js
I learned that our `scroll-tracker` script uses a large list of URLs and headings that are often outdated so I manually checked each page and remove the ones that don't fire events anymore because of redirects or content changes.
The approach clearly has a massive flaw around maintenance, not to mention that PAs probably have no idea whether the URLs and headings are not in sync anymore or people don't reach a certain section which can potentially result in ill-informed data-based decisions.
After clean-up, we add a new entry for the results page on `next-steps-for-your-business` flow.
Because we ship code that has no effect on any page.
[Trello card](https://trello.com/c/rwfj9zjQ/426-implement-ga-tracking-of-sections-in-viewport)
> Update scroll tracker config entries

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
* Allow modules to start after cookie consent ([PR #2041](https://github.com/alphagov/govuk_publishing_components/pull/2041))
* Fix travel advice pages to use parent breadcrumbs ([PR #2050](https://github.com/alphagov/govuk_publishing_components/pull/2050))
* Refactor heading logic in radio component ([PR #2051](https://github.com/alphagov/govuk_publishing_components/pull/2051))
* Update design of metadata component ([PR #2046](https://github.com/alphagov/govuk_publishing_components/pull/2046))
* Update scroll tracker config entries ([PR #2052](https://github.com/alphagov/govuk_publishing_components/pull/2052))
> Version 24.10.2 release

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
* Remove phase banner restrictions ([PR #2057](https://github.com/alphagov/govuk_publishing_components/pull/2057))
> Release 24.10.3

- app/assets/stylesheets/govuk_publishing_components/components/_print-link.scss
Keep print button styles in line with other buttons
In https://github.com/alphagov/govuk_publishing_components/pull/1735 we tried to bring the print button in line with other button elements, so we're removing the underline for this component on any states and regardless of the element used (button or anchor).
<table>
</td></tr>
</table>
> Keep print button styles in line with other buttons

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/_show-password.scss
Update the button styling for the [show password component](https://components.publishing.service.gov.uk/component-guide/show_password) to use the latest link styles on the button text.
Part of ongoing work by the govuk frontend community to use the latest link styles from the design system. The show password component uses text styling within it's main button that simulates the style of a link so we're applying the link styles here for consistency.
| --- | --- |
| ![Screenshot 2021-05-18 at 15 22 32](https://user-images.githubusercontent.com/64783893/118668697-042b2280-b7ed-11eb-9db1-c23b7d382a51.png) | ![Screenshot 2021-05-18 at 15 22 58](https://user-images.githubusercontent.com/64783893/118668734-0ab99a00-b7ed-11eb-9547-d293df7415ee.png) |
> Update link styles for show password component

- app/assets/stylesheets/govuk_publishing_components/components/_share-links.scss
- app/views/govuk_publishing_components/components/_share_links.html.erb
Share Links have new Design System styles
Underline link styles have changed on the Design System adjusting Share Links gem.
> Update share links to have new underline styles

- CHANGELOG.md
- app/views/govuk_publishing_components/components/_machine_readable_metadata.html.erb
- lib/govuk_publishing_components/presenters/machine_readable/page.rb
- spec/components/machine_readable_metadata_spec.rb
For content that has been withdrawn, prefixes the `og:title` tag with '[Withdrawn]'.
https://trello.com/c/7OxshPDC/2498-2-add-withdrawn-to-ogtitle-tag
> The prefix is currently added to the title metatag, but not og:title. The latter is used when content is shared on social media etc, so in those cases it's not clear to users that content has been withdrawn.
> Add [Withdrawn] to the og:title tag of withdrawn content

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/_subscription-links.scss
- app/views/govuk_publishing_components/components/_subscription_links.html.erb
Update link styles for subscription links component
As part of rolling out the new link styles from `govuk-frontend`
<table>
</td></tr>
</td></tr>
</table>
> Update link styles for subscription links

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/components/reorderable-list.js
- app/assets/javascripts/govuk_publishing_components/lib/trigger-event.js
Some work was done to allow cookie dependent modules to start immediately when the user consents to cookies. https://github.com/alphagov/govuk_publishing_components/pull/2041 
To make this possible, some functionality was introduced to trigger a custom cookie consent event when consent is given. It seems like some of the code that was introduced causes a JS error on IE11 specifically. 
The error appears to be related to the `initCustomEvent` method. Namely, it seems like IE11 does not like when this method is called with less than the required 4 arguments, and consequently throws an error.
This passes `null` as a 4th argument, which should appease IE11 without causing issues in other browsers.
> Fix IE11 initCustomEvent error

- CHANGELOG.md
- app/views/govuk_publishing_components/components/docs/inset_text.yml
Use realistic/suggested markup when passing a block to the inset text component
Reviewing the inset text for new link styles
<table>
</td></tr>
</table>
> Update inset text block example

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/_inverse-header.scss
- app/views/govuk_publishing_components/components/docs/inverse_header.yml
Removed direct styling on any anchors within the block (as it can cause style leakage) and improve examples to give us a bit more confidence when reviewing the component.
Reviewing the inverse header for new link styles in the component guide and in apps.
<table>
</td></tr>
</table>
<table>
<tr><th>Default</th><th>Hover</th></tr>
</td></tr>
</table>
<table>
<tr><th>Default</th><th>Hover</th></tr>
</td></tr>
</table>
> Remove direct anchor styling on inverse header component

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/_action-link.scss
- app/assets/stylesheets/govuk_publishing_components/components/_contents-list.scss
- app/assets/stylesheets/govuk_publishing_components/components/_image-card.scss
- app/views/govuk_publishing_components/components/_action_link.html.erb
- app/views/govuk_publishing_components/components/_contents_list.html.erb
- app/views/govuk_publishing_components/components/_image_card.html.erb
- lib/govuk_publishing_components/presenters/contents_list_helper.rb
- spec/components/contents_list_spec.rb
Update the [action link](https://components.publishing.service.gov.uk/component-guide/action_link), [contents list](https://components.publishing.service.gov.uk/component-guide/contents_list) and [image card](https://components.publishing.service.gov.uk/component-guide/image_card) components so that they are using the new link styles.
Additionally adds underlines to links that previously didn't have underlines on the action link component.
Part of work by the govuk frontend community to update our gem to use new link styles from GOV.UK frontend.
Action link underlines are being applied because this ensures consistency, whether the text is in front of a light background, or even a dark background.
[Card for action links underlines](https://trello.com/c/GroJtbez/725-add-underline-throughout- …
> Update action link, contents list and image card components to use new link styles

- CHANGELOG.md
- app/views/govuk_publishing_components/components/_government_navigation.html.erb
- app/views/govuk_publishing_components/components/docs/government_navigation.yml
Adds the following classes to links on the [government navigation](https://components.publishing.service.gov.uk/component-guide/government_navigation) component. The classes it adds are:
- `govuk-link`
- `govuk-link--no-underline`
- `govuk-link--inverse`
Part of ongoing work by the govuk frontend community to ensure we are using the new link styles from the altest release of govuk frontend.
This is not a full implementation of the new link styles due to clashes with styles in the header from govuk-toolkit, our legacy implementation of what is now govuk frontend. There's no value in trying to fix this now as it would require either an update to the archived govuk-toolkit repo or a set of convoluted override styles between the gem and static. The decision to not implement this fully is …
> Add govuk-link classes to government navigation links

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/components/feedback.js
- app/views/govuk_publishing_components/components/docs/feedback.yml
- spec/javascripts/components/feedback-spec.js
Remove jQuery code from the feedback component's JavaScript, and replace with vanilla JS.
There are two things that might be a problem with this PR:
**Ajax**
Firstly, this component used jQuery's ajax functionality. We've only got a few scripts that do this, and there are a few options for what to replace it with (`XMLHttpRequest`, [`fetch`](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch)). We should have a consistent approach for this.
I've chosen `XMLHttpRequest` because I'm more familiar with it, but `fetch` might be better. I don't want this conversation to block this PR - I think it's more important we remove jQuery, and if we have to, we can come back later and fix up the consistency (as I said, it's only a few scripts that do this).
**Internet Explorer** …
> Remove jQuery from the feedback component

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/components/accordion.js
If the URL of a page with an accordion on it has a location hash in the URL that doesn't match an actual accordion section, an error can occur as described in issue https://github.com/alphagov/govuk_publishing_components/issues/2086
This partly fixes this problem by checking for an actual value for the `data-anchor-navigation` attribute, however this might not be a solution to the whole problem.
Noticed in the component auditing pages (locally) the accordion was breaking if tabs were changed and the page reloaded.
None.
> Fix accordion anchor link navigation bug

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/helpers/_markdown-typography.scss
Update the [govspeak component](https://components.publishing.service.gov.uk/component-guide/govspeak) to use the latest link styles from the latest govuk frontend release.
Part of ongoing work by the govuk frontend community to ensure that all components are using new link styles from govuk frontend so that users can reap the benefits of them.
This PR also includes a separate changelog line for https://github.com/alphagov/govuk_publishing_components/pull/2073 as that PR should've included a changelog line but it got missed before merge. 
| --- | --- |
| ![Screenshot 2021-05-19 at 11 32 20](https://user-images.githubusercontent.com/64783893/118799553-c2ef4d00-b896-11eb-91d9-1459b47446ec.png) | ![Screenshot 2021-05-19 at 11 32 …
> Add govuk-link-common mixin to govspeak links

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/_accordion.scss
Update the accordion hover states so it uses the new hover states from [GOV.UK Frontend v3.12.0](https://github.com/alphagov/govuk-frontend/releases/tag/v3.12.0).
This couldn't be automatically updated alongside by bumping because the accordion needs the hover states on text within the button, this required a number of bespoke changes.
Slight tweak to hover of the 'Show all sections' link - the hover state visual change is now triggered by hovering the whole button, not just the text.
To bring the accordion component up to date, alongside all of the other components that can't be automatically updated.
| State | Before | After | 
| - | - | - |
| Show all link hover | ![image](https://user-images.githubusercontent.com/1732331/118957485-7704dc80-b958-11eb-9b43-c071b438f035.png) | …
> Update accordion link hover to new styles

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/_previous-and-next-navigation.scss
- app/views/govuk_publishing_components/components/_previous_and_next_navigation.html.erb
Amends the hover state for the [previous and next navigation component](https://components.publishing.service.gov.uk/component-guide/previous_and_next_navigation), specifically applies the new `govuk-link` hover decoration to the label element and to the title element when a label isn't present.
Part of ongoing work by the govuk frontend community to ensure we are using the new link styles from the latest govuk frontend release.
This change specifically is an accessibility enhancement as, besides the slight background change, there is no clear indicator that the state of the component has changed.
| State | Before | After |
| With label | ![Screenshot 2021-05-20 at 17 55 46](https://user-images.githubusercontent.com/64783893/119019803-7b9bb600-b995-11eb-9f32-b18fc679bb9 …
> New link styles for prev next navigation

- CHANGELOG.md
- lib/govuk_publishing_components/presenters/content_breadcrumbs_based_on_taxons.rb
- lib/govuk_publishing_components/presenters/content_item.rb
- spec/lib/govuk_publishing_components/presenters/content_breadcrumbs_based_on_taxons_spec.rb
- When a page is tagged to a taxon, use the url_override field of that taxon in the page breadcrumbs. If the taxon doesn't have a url_override set, then use the base_path as before. 
- We would like to be able to set a url_override field on taxons to customise the url of the page in content tagger. Related PR's are: https://github.com/alphagov/govuk-content-schemas/pull/1059 and https://github.com/alphagov/content-tagger/pull/1204
> Use url_override in breadcrumbs

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/_organisation-logo.scss
Update the hover state for the [organisation logo component](https://components.publishing.service.gov.uk/component-guide/organisation_logo)
Part of ongoing work by the govuk frontend community to implement the new link styles from the latest release of govuk frontend.
This additionally applies a minor redesign to the component's states based on design work by the govuk accessibility team to improve consistency o link behaviour across govuk. [Card](https://trello.com/c/djz1Sxy3/740-update-organisation-component-to-be-consistent-throughout-govuk-and-remove-any-style-overrides).
| State | Before | After |
| default | ![Screenshot 2021-05-21 at 11 07 13](https://user-images.githubusercontent.com/64783893/119122758-c6b1d980-ba26-11eb-8518-4fa4538be0bf.png) | ![Screenshot …
> Update organisation logos hover state

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/_accordion.scss
- app/assets/stylesheets/govuk_publishing_components/components/_step-by-step-nav.scss
Apples the latest link styles from govuk frontend to the [step by step navigation component](https://components.publishing.service.gov.uk/component-guide/step_by_step_nav).
Part of ongoing work by the govuk frontend community to ensure that we are using the new link styles from the latest release of govuk frontend.
This change also includes a minor tweak to the "show all" button on this component and the accordion component focus states so that the thick underline from the new hover state doesn't interfere visually with the small focus state.
| State | Before | After |
| All sections button hover | ![Screenshot 2021-05-24 at 11 50 04](https://user-images.githubusercontent.com/64783893/119337707-0ecf3700-bc87-11eb-908a-be82340c6806.png) | ![Screenshot 2021-05-24 at 11 …
> New link styles for step by step nav

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
* Add `[Withdrawn]` to the beginning of the `og:title` meta tag for withdrawn pages ([PR #2066](https://github.com/alphagov/govuk_publishing_components/pull/2066))
* Fix accordion anchor link navigation bug ([PR #2087](https://github.com/alphagov/govuk_publishing_components/pull/2087))
* Remove jQuery from the feedback component ([PR #2062](https://github.com/alphagov/govuk_publishing_components/pull/2062))
* Remove `display: none` rules from component print stylesheets, and use the `govuk-!-display-none-print` class instead. ([PR #1561](https://github.com/alphagov/govuk_publishing_components/pull/1561))
* Fix IE11 `initCustomEvent` error ([PR #2079](https://github.com/alphagov/govuk_publishing_components/pull/2079))
> Release 24.11.0

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
Releasing fix 
- Update shape of tracking link ([PR #2101](https://github.com/alphagov/govuk_publishing_components/pull/2101))
> Release 24.11.1

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
Releases version 24.12.0.
Trello card: https://trello.com/c/jEj62y5d
> Release version 24.12.0

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/_all_components.scss
- app/assets/stylesheets/govuk_publishing_components/components/_accordion.scss
- app/assets/stylesheets/govuk_publishing_components/components/_action-link.scss
- app/assets/stylesheets/govuk_publishing_components/components/_contents-list.scss
- app/assets/stylesheets/govuk_publishing_components/components/_image-card.scss
- app/assets/stylesheets/govuk_publishing_components/components/_inverse-header.scss
- app/assets/stylesheets/govuk_publishing_components/components/_organisation-logo.scss
- app/assets/stylesheets/govuk_publishing_components/components/_previous-and-next-navigation.scss
- app/assets/stylesheets/govuk_publishing_components/components/_print-link.scss
- app/assets/stylesheets/govuk_publishing_components/components/_share-links.scss
- app/assets/stylesheets/govuk_publishing_components/components/_show-password.scss
- app/assets/stylesheets/govuk_publishing_components/components/_step-by-step-nav.scss
- app/assets/stylesheets/govuk_publishing_components/components/_subscription-links.scss
- app/assets/stylesheets/govuk_publishing_components/components/helpers/_markdown-typography.scss
- app/views/govuk_publishing_components/components/_action_link.html.erb
- app/views/govuk_publishing_components/components/_contents_list.html.erb
- app/views/govuk_publishing_components/components/_government_navigation.html.erb
- app/views/govuk_publishing_components/components/_image_card.html.erb
- app/views/govuk_publishing_components/components/_previous_and_next_navigation.html.erb
- app/views/govuk_publishing_components/components/_share_links.html.erb
- app/views/govuk_publishing_components/components/_subscription_links.html.erb
- app/views/govuk_publishing_components/components/docs/government_navigation.yml
- app/views/govuk_publishing_components/components/docs/inset_text.yml
- app/views/govuk_publishing_components/components/docs/inverse_header.yml
- lib/govuk_publishing_components/presenters/contents_list_helper.rb
- spec/components/contents_list_spec.rb
Applies the new link styles from the latest release of govuk frontend.
Part of work by the govuk frontend community to ensure that we are using the new link styles from govuk frontend.
This PR is the amalgamation of several smaller PRs to get the new link styles working across all our components. You can see these individual PRs including visual changes in the changelog updates in this PR.
This PR additionally includes a minor reversion of focus/hover states introduced in https://github.com/alphagov/govuk_publishing_components/pull/2092. These changes were added too hastily and undermine standard design system behaviour of not triggering hover states when an item is focussed.
> Apply new link styles to our components

- app/assets/stylesheets/govuk_publishing_components/components/_organisation-logo.scss
- app/views/govuk_publishing_components/components/_organisation_logo.html.erb
Setting the organisation's margin to zero as the component inherited the browser's default margins when used as a heading.
Also tidied up the component template to use `content_tag` instead of interpolating the tags, and added a nicer way of checking for an appropriate heading level.
- Set the organisation logo component's margins to zero
- Swapped to using `content_tag` instead of interpolating the element type
- Switched to a nice and more readable way of checking that the heading level is appropriate
If used as a heading the organisation logo would inherit the default margin set by the browser - setting it to zero avoids this inheritance.
Previously the outer element was either a `div` or heading element - and this was interpolated (for example `<<% element_type %>>` and `</<% …
> Reset organisation logo margin

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
* Update link styles for show password component ([PR #2074](https://github.com/alphagov/govuk_publishing_components/pull/2074))
* Update link styles for subscription links ([PR #2075](https://github.com/alphagov/govuk_publishing_components/pull/2075))
* Update inset text block example ([PR #2085](https://github.com/alphagov/govuk_publishing_components/pull/2085))
* Remove direct anchor styling on inverse header component ([PR #2084](https://github.com/alphagov/govuk_publishing_components/pull/2084))
* Update action link, contents list and image card components to use new link styles ([PR #2071](https://github.com/alphagov/govuk_publishing_components/pull/2071))
* Add govuk-link classes to government navigation links ([PR #2081](https://github.com/alphagov/govuk_publishing_components/pull/ …
> Bump version to 24.13.0

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/analytics/scroll-tracker.js
- config/locales/cy.yml
- config/locales/en.yml
- lib/govuk_publishing_components/presenters/public_layout_helper.rb
- spec/features/contextual_navigation_spec.rb
- spec/lib/govuk_publishing_components/presenters/content_breadcrumbs_based_on_priority_spec.rb
We renamed the taxon today to reflect the language that people use. There is a redirect in place so the links will all still work, but the scroll tracking is currently broken because it's fixed to the URL not the content ID.
https://trello.com/c/wxR5o06H/1539-implement-brexit-landing-page-url-change
> Rename /transition to /brexit

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
Updates Brexit links in various places, and fixes scroll tracking on /brexit
> Bump version to 24.13.1

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
Includes:
* Add alternate Brexit callout text ([PR #2115](https://github.com/alphagov/govuk_publishing_components/pull/2115))
> Release 24.13.2

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/lib/header-navigation.js
- app/views/govuk_publishing_components/components/_search.html.erb
- spec/components/search_spec.rb
Adds click track events on the open/close of the search box in mobile view and the submit button.
As part of gathering some baseline data ahead of updating the header design.
None
[Trello](https://trello.com/c/CwPwNE60/321-implement-analytics-tracking-on-the-existing-headers)
> Add event tracking to search elements in header

- CHANGELOG.md
- lib/govuk_publishing_components/presenters/content_breadcrumbs_based_on_priority.rb
If the priority taxon is Brexit we want the action to be "superBreadcrumb Brexitbusinessandcitizen". If the priority taxon is one of the Brexit subtaxons (business and citizen), we'd like it to be "superBreadcrumb Brexitbusiness" and "superBreadcrumb Brexitcitizen", respectively.
To prepare tracking and enable dashboard creation for the new Brexit pages.
[Trello card](https://trello.com/c/RqR5gkX2)
Manually tested in `government-frontend`; found it challenging to figure out if and where a unit test might be added.
> Add custom tracking action to Brexit superbreadcrumbs

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/analytics/analytics.js
- app/assets/javascripts/govuk_publishing_components/analytics/custom-dimensions.js
- app/assets/javascripts/govuk_publishing_components/components/checkboxes.js
- app/assets/javascripts/govuk_publishing_components/components/contextual-guidance.js
- app/assets/javascripts/govuk_publishing_components/components/reorderable-list.js
- app/assets/javascripts/govuk_publishing_components/lib/govspeak/magna-charta.js
- app/assets/javascripts/govuk_publishing_components/lib/trigger-event.js
- spec/javascripts/components/accordion-spec.js
- spec/javascripts/components/checkboxes-spec.js
- spec/javascripts/components/contextual-guidance-spec.js
- spec/javascripts/components/modal-dialogue-spec.js
- spec/javascripts/components/step-by-step-nav-spec.js
- spec/javascripts/govuk_publishing_components/analytics/analytics.spec.js
- spec/javascripts/govuk_publishing_components/lib/cookie-functions-spec.js
- spec/javascripts/govuk_publishing_components/lib/trigger-event-spec.js
Make (most of) our jasmine tests for JavaScript pass in Internet Explorer, currently aiming at IE10+.
We're removing jQuery across GOV.UK and we need confidence that the replacement code will work in all the browsers we support, especially when JS often has different ways (new/old) of doing the same thing. It would be good to be able to run our tests in all browsers and know they should pass.
Currently there are 188 failing tests. This PR fixes all but 13 of them, so there's still some work to do, but the changes are getting too big to review and I want to get some of these fixes out pronto.
A lot of the failing tests seem to be due to syntax issues within the tests themselves, rather than our actual JS, so adding a few lines to replace a `forEach` loop with a `for` loop doesn't feel like …
> Make jasmine tests pass in Internet Explorer

- CHANGELOG.md
- app/views/govuk_publishing_components/components/_government_navigation.html.erb
- spec/components/government_navigation_spec.rb
Add tracking data attributes to elements in the government_navigation menu header (which mirrors what is in [Whitehall](https://github.com/alphagov/whitehall/pull/6129)).
As part of gathering some baseline data ahead of updating the header design.
None
[Trello](https://trello.com/c/CwPwNE60/321-implement-analytics-tracking-on-the-existing-headers)
> Add tracking to government navigation

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
* Add tracking to government navigation ([PR #2127](https://github.com/alphagov/govuk_publishing_components/pull/2127))
* Make jasmine tests pass in Internet Explorer ([PR #2090](https://github.com/alphagov/govuk_publishing_components/pull/2090))
* Allow a custom link to be used on the header logo ([PR #2114](https://github.com/alphagov/govuk_publishing_components/pull/2114))
* Add custom tracking action to Brexit superbreadcrumbs ([PR #2118](https://github.com/alphagov/govuk_publishing_components/pull/2118))
> Version 24.13.4

- CHANGELOG.md
- app/views/govuk_publishing_components/components/_government_navigation.html.erb
The data module wasn't set so the Javascript wasn't being applied from #2127
> Fix click tracking in government_navigation

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/components/contextual-guidance.js
- spec/javascripts/components/contextual-guidance-spec.js
As discussed in https://github.com/alphagov/govuk_publishing_components/pull/2090#discussion_r647559873, the contextual guidance component contained an option that wasn't documented, or tested (until very recently, in the same PR) or used. The option allowed contextual guidance to be permanently hidden.
This PR removes that option.
None.
> Remove hide-only option from contextual guidance

- CHANGELOG.md
- lib/govuk_publishing_components/presenters/content_breadcrumbs_based_on_priority.rb
- spec/features/contextual_navigation_spec.rb
- spec/lib/govuk_publishing_components/presenters/content_breadcrumbs_based_on_priority_spec.rb
Add a super bread crumb to content tagged to the [brexit](https://content-tagger.publishing.service.gov.uk/taxons/634fd193-8039-4a70-a059-919c34ff4bfc) [child](https://content-tagger.publishing.service.gov.uk/taxons/614b2e65-56ac-4f8d-bb9c-d1a14167ba25) taxons.
We think it is more useful to direct users to either the Brexit business page, or the Brexit individuals page, rather than the Brexit landing page. 
- ### Tagged to Brexit parent taxon OR tagged to both child taxons
- ### Tagged to Brexit: guidance for individuals
- ### Tagged to Brexit: guidance for businesses
> Brexit child taxon superbreadcrumbs

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/components/accordion.js
- app/assets/javascripts/govuk_publishing_components/components/checkboxes.js
- app/assets/javascripts/govuk_publishing_components/components/contextual-guidance.js
- app/assets/javascripts/govuk_publishing_components/components/cookie-banner.js
- app/assets/javascripts/govuk_publishing_components/components/copy-to-clipboard.js
- app/assets/javascripts/govuk_publishing_components/components/details.js
- app/assets/javascripts/govuk_publishing_components/components/feedback.js
- app/assets/javascripts/govuk_publishing_components/components/govspeak.js
- app/assets/javascripts/govuk_publishing_components/components/modal-dialogue.js
- app/assets/javascripts/govuk_publishing_components/components/print-link.js
- app/assets/javascripts/govuk_publishing_components/components/reorderable-list.js
- app/assets/javascripts/govuk_publishing_components/components/show-password.js
- app/assets/javascripts/govuk_publishing_components/components/step-by-step-nav.js
- docs/javascript-modules.md
- spec/javascripts/components/accordion-spec.js
- spec/javascripts/components/checkboxes-spec.js
- spec/javascripts/components/contextual-guidance-spec.js
- spec/javascripts/components/cookie-banner-spec.js
- spec/javascripts/components/copy-to-clipboard-spec.js
- spec/javascripts/components/details-spec.js
- spec/javascripts/components/feedback-spec.js
- spec/javascripts/components/govspeak-spec.js
- spec/javascripts/components/modal-dialogue-spec.js
- spec/javascripts/components/print-link-spec.js
- spec/javascripts/components/reorderable-list-spec.js
- spec/javascripts/components/show-password-spec.js
- spec/javascripts/components/step-by-step-nav-spec.js
Use the `init` API to initialise modules.
- To converge to a single JavaScript pattern across GDS (aligning the current scripts with the ones we currently have in `govuk-frontend`)
- To be able to port components upstream (in `govuk-frontend`) without needing to refactor the code
- To initialise [JavaScript modules without requiring jQuery](https://trello.com/c/sghHecNi/91-remove-jquery-dependency)
JavaScript modules in GOV.UK are actually design patterns for keeping pieces of code independent of other components. We currently have 3 design patterns for writing JavaScript in GOV.UK applications.
Mostly found in legacy scripts, either migrated from Toolkit, Elements, or written in the same era.
```
GOVUK.Modules.TestModule = function () {
var that = this
that.start = function ($element) { …
```
> Use the`init` API to initialise modules

- CHANGELOG.md
- lib/govuk_publishing_components/presenters/contextual_navigation.rb
Will exclude [more pages with start buttons on](https://www.gov.uk/api/content/find-coronavirus-support) from having navigation on that might interrupt their service journey.
Until recently, smart_answers used transactions as their start pages, which is why they haven't been included previously.
https://trello.com/c/A7LMRDFc/1579-stop-brexit-sidebar-navigation-from-appearing-on-smart-answers
> Add smart_answer to the document types excluded from Brexit navigation

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
* Fix click tracking in government_navigation ([PR #2129](https://github.com/alphagov/govuk_publishing_components/pull/2129))
> Version 24.13.5

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/rum-loader.js.erb
- app/assets/javascripts/govuk_publishing_components/vendor/lux/lux-polyfill.js
- app/assets/javascripts/govuk_publishing_components/vendor/lux/lux.js
- app/views/govuk_publishing_components/components/_layout_for_public.html.erb
- config/initializers/assets.rb
- docs/real-user-metrics.md
- spec/components/layout_for_public_spec.rb
Adds the real user metrics to the public layout component by adding the LUX scripts. This includes:
- Adding tests to ensure both LUX scripts are present in the public layout component _only_ when a user has allowed usage tracking cookies
- Adding `lux` and `lux-polyfill` to the assets precompile list
- Updating the LUX script to ensure that the image beacon is used
- Updating the LUX script to add GDS's Speedcurve user ID number - usually this is appended to the script `src` with a query string, but that doesn't work in this instance as Rails adds a fingerprint to the filename that prevents the script from finding itself
- Prettifying `lux-polyfill` to make it slightly easier to see what's going on; this is compressed when going through the asset pipeline
- Adding documentation …
> Add real user metrics using Speedcurve's LUX

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
Includes:
- Add real user metrics using Speedcurve's LUX ([PR 2135](https://github.com/alphagov/govuk_publishing_components/pull/2135))
> Release v24.14.0

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
Includes:
* Fix wrong label value for event tracking on menu button ([PR #2139](https://github.com/alphagov/govuk_publishing_components/pull/2139))
> Release v24.14.1

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/vendor/lux/lux.js
- docs/real-user-metrics.md
LUX defaults to 100% of events being sent - setting this to 1% will reduce the number of events to the same level that has been set in Speedcurve's admin settings.
Issue on static - https://github.com/alphagov/static/issues/2516
Approximately 29 million events were sent over the course of one day, of which only only 1% were analysed. To avoid the unnecessary sending of events we can only send 1% of events and set Speedcurve to analyse them all.
1. Got to https://govuk-publis-update-lux-j6z85j.herokuapp.com/public/
2. Accept all cookies
3. Open browser console, and type `LUX.getDebug()`
An array is returned, one of which shows the sampling rate of 1%, as shown in the screenshot below:
> Set LUX sampling to 1%
