README.md

* Update README to reflect correct lines to add to config regarding GovukPublishingComponents

Update publishing component references

---

CHANGELOG.md
lib/govuk_publishing_components/version.rb

* Allow components to use application view helpers PR #3

Version 0.2.0

---

CHANGELOG.md
lib/govuk_publishing_components/version.rb

* Include body and accessibility acceptance criteria on component pages PR #6
* Fix load ordering bug which would sometimes cause the component guide to use the app’s layout PR #5

Version 0.3.0

---

CHANGELOG.md
lib/govuk_publishing_components/version.rb

* Remove ApplicationRecord files from gem PR #8

Version 0.3.1

---

app/assets/stylesheets/govuk_publishing_components/component_guide.scss
app/views/govuk_publishing_components/component_guide/component_doc/_call.html.erb
app/views/layouts/govuk_publishing_components/application.html.erb

Added an issue to follow this up and increase the contrast: https://github.com/alphagov/govuk_publishing_components/issues/11
Before
After
After (if CDN fails, or JavaScript fails)

Pretty print component snippet

---

CHANGELOG.md
lib/govuk_publishing_components/version.rb

- Fix overlap issue with code snippets (PR #15)

Version 0.4.1

---

CHANGELOG.md
lib/govuk_publishing_components/version.rb

* Relax slimmer version (PR #20)

Version 0.4.2

---

CHANGELOG.md
lib/govuk_publishing_components/version.rb

- Add component generator (PR #24)

Version 0.6.0

---

docs/component_conventions.md

Expanding our current component conventions documentation to include the use of BEM.

Add documentation on use of BEM

---

lib/generators/govuk_publishing_components/templates/component.yml.erb

- should be accessibility_criteria, not acceptance_criteria

Fix accessibility in generator yml template

---

CHANGELOG.md
lib/govuk_publishing_components/version.rb

Add preview pages to component guide (PR #27)

Version 0.8.0

---

CHANGELOG.md
lib/govuk_publishing_components/version.rb

* Add aXe accessibility testing javascript to component guide pages (PR #33)
* Mark strings in YAML fixtures as HTML safe (PR #36)
* Refactor internal structs to use classes (PR #34)

Version 0.9.0

---

CHANGELOG.md
lib/govuk_publishing_components/version.rb

All documentation will need updating when upgrading (see PR #37):
* Rename fixtures to examples in YAML documentation
* Nest example data within a named block to give examples more features

Version 1.0.0

---

CHANGELOG.md
lib/govuk_publishing_components/version.rb

Fixes issue around page scrolling unexpectedly.
* Add context param to aXe so that options are passed correctly

Version 1.0.1

---

CHANGELOG.md
lib/govuk_publishing_components/version.rb

* Allow gem to be used with static (PR #43)

Version 1.1.0

---

CHANGELOG.md
lib/govuk_publishing_components/version.rb

Show incomplete warnings from aXe in the component guide (PR #40)

Version 1.2.0

---

CHANGELOG.md
lib/govuk_publishing_components/version.rb

- add optional descriptions for component examples

Version 1.3.0

---

app/models/govuk_publishing_components/shared_accessibility_criteria.rb
spec/component_guide/component_guide_spec.rb

Fixes grammar in shared accessibility acceptance criteria for link.

Fix shared accessibility criteria grammar

---

CHANGELOG.md
lib/govuk_publishing_components/version.rb

* Add integration tests for apps to use when testing their component guide (PR #68)

Version 1.8.0

---

app/assets/stylesheets/govuk_publishing_components/application.scss
app/assets/stylesheets/govuk_publishing_components/component-highlight.scss
app/models/govuk_publishing_components/component_example.rb
app/views/govuk_publishing_components/component_guide/component_doc/_call.html.erb
app/views/layouts/govuk_publishing_components/application.html.erb
govuk_publishing_components.gemspec
spec/component_guide/component_guide_spec.rb

Fix syntax highlighting

---

CHANGELOG.md
lib/govuk_publishing_components/version.rb

- Remove cookie and survey banner using CSS instead of setting cookies (PR #71)
- Fix syntax highlighting styles (PR #70 and #73)

Version 1.8.1

---

CHANGELOG.md
lib/govuk_publishing_components/version.rb

Force cookie and survey banner styling (PR #76)

Version 1.8.2

---

CHANGELOG.md
lib/govuk_publishing_components/version.rb

* Use local govuk_components for static's component guide (PR #74)

Version 1.9.0

---

CHANGELOG.md
lib/govuk_publishing_components/version.rb

Add visual diff tool to component guide

Version 1.10.0

---

README.md
docs/accessibility_acceptance_criteria.md
docs/component_conventions.md
docs/component_principles.md

Based on pending blog post:
https://trello.com/c/AfCe5ciz/113-accessibility-acceptance-criteria
https://github.com/fofr/paulrhayes.com/pull/19

Add guidance on accessibility acceptance criteria

---

.rubocop.yml
Rakefile
app/assets/stylesheets/govuk_publishing_components/application.scss
app/views/govuk_publishing_components/component_guide/show.html.erb
govuk_publishing_components.gemspec
lib/tasks/govuk_publishing_components_tasks.rake
spec/component_guide/component_example_spec.rb
test/dummy/app/views/components/_test-component-with-no-accessibility-criteria.html.erb
test/dummy/app/views/components/docs/test-component-with-no-accessibility-criteria.yml

Add violation warning when accessibility criteria aren't supplied (fully linted). @vanitabarrett @fofr

Accessibility warning

---

CHANGELOG.md
lib/govuk_publishing_components/version.rb

Use lead paragraph component from static.

Version 1.12.1

---

CHANGELOG.md
lib/govuk_publishing_components/version.rb

As part of https://trello.com/c/yo9dWRM8/242-create-a-radio-button-component

Release 2.0.0 breaking release

---

CHANGELOG.md
lib/govuk_publishing_components/version.rb

- fix iphone bugs and text only zoom problem, and print styles (PR #108)

Version 3.0.1

---

CHANGELOG.md
lib/govuk_publishing_components/version.rb

- Add styles for active link where active link is in a choice list, and fix focus states on same in Firefox (PR #110)

Version 3.0.2

---

README.md
docs/moving-components-upstream-into-this-gem.md

Rendered: https://github.com/alphagov/govuk_publishing_components/blob/c644f6c0878522941e2a47154178899d8cefb1f0/docs/moving-components-upstream-into-this-gem.md

Document how to move components upstream

---

Gemfile.lock
Rakefile
app.json
govuk_publishing_components.gemspec
spec/dummy/config/application.rb

This makes sure we can run this app on Heroku. See individual commits for details.

Fix Heroku review apps

---

CHANGELOG.md
lib/govuk_publishing_components/version.rb

Releasing all pending changes, prior to some breaking changes relating to the task list components which have yet to be merged.

Release version 4.1.1

---

CHANGELOG.md
lib/govuk_publishing_components/version.rb

We've renamed task lists to step by step nav and changed the schema it
expects.

Bump major version

---

CHANGELOG.md
app/assets/javascripts/govuk_publishing_components/components/step-by-step-nav.js
app/assets/stylesheets/govuk_publishing_components/components/_step-by-step-nav-header.scss
app/assets/stylesheets/govuk_publishing_components/components/_step-by-step-nav.scss
app/views/govuk_publishing_components/components/_step_by_step_nav.html.erb
app/views/govuk_publishing_components/components/_step_by_step_nav_header.html.erb
app/views/govuk_publishing_components/components/docs/step_by_step_nav.yml
app/views/govuk_publishing_components/components/docs/step_by_step_nav_header.yml
lib/govuk_publishing_components/components/step_by_step_nav_helper.rb
spec/components/step_by_step_nav_header_spec.rb
spec/components/step_by_step_nav_spec.rb
spec/javascripts/components/step-by-step-nav-spec.js

A variety of changes relating to accessibility following feedback from our trip to DAC.
Also includes a small change to the analytics, removing a redundant tracking call.
Trello cards: 
- https://trello.com/c/t2UnqDX0/461-fix-agreed-accessibility-issues-with-step-by-step-navigation
- https://trello.com/c/tc1P7cuE/450-minor-change-to-tracking-on-step-by-step-remove-tasklistlinkclicked

Step nav accessibility changes

---

app/views/govuk_publishing_components/components/_feedback.html.erb

Adds method="post" to the forms so that they pass data correctly when JS is disabled.

Fix feedback component when JS is disabled

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

For https://trello.com/c/FxxChPUj/257-add-navigation-sidebar-component-to-govuk-publishing-components-gem

Bump to version 5.2.0

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

Includes:
* Feedback: changes to the event tracking (PR #184)
* Related Navigation: accessibility improvements (PR #182)

Release 5.2.1

---

CHANGELOG.md
lib/govuk_publishing_components/version.rb

We're adding helpers for the step by step navigation components

Bump minor version

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

Update gem version number

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

Related to #202 & #212 
Trello
* https://trello.com/c/mQIFPn2V/99-document-list
* https://trello.com/c/xfcxY63h

Bump gem version to 5.5.2

---

CHANGELOG.md
lib/govuk_publishing_components/version.rb

Add optional flags for spacing around document list component (PR #217)

Version 5.5.5

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

Add optional margin top flag for feedback component (PR #222)

Version 5.5.6

---

CHANGELOG.md
app/assets/javascripts/govuk_publishing_components/all_components.js
app/assets/javascripts/govuk_publishing_components/application.js
docs/install-and-use.md
spec/dummy/app/assets/javascripts/application.js

This means all apps will include the same Javascript, promoting consistency between applications.

Expose a single manifest file for javascripts

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

Includes the search component, moved from static.

Bump gem to version 6.4.0

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

This is 7.0.0 rather than 7.1.0, as I see there hasn't been a 7.0.0 release yet.

Bump to 7.0.0

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

Includes some new components from static.

Update to 7.1.0

---

app/views/govuk_publishing_components/components/docs/input.yml

- describedby option was incorrectly called
- demonstration of value option added

Improve form input component documentation

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

Includes:
- model for organisation pages branding for components
- changes to subscription links component

Version 7.2.0

---

app.json
app/views/govuk_publishing_components/components/_breadcrumbs.html.erb

This was accidentally added in a rebase.

Fix extra %> in the breadcrumbs component

---

app/views/govuk_publishing_components/components/_contextual_breadcrumbs.html.erb
app/views/layouts/govuk_publishing_components/application.html.erb
spec/component_guide/component_index_spec.rb
spec/component_guide/static_component_guide_spec.rb
spec/dummy/app/views/govuk_component/breadcrumbs.raw.html.erb
spec/features/contextual_navigation_spec.rb

The component is now available here rather than in static.

Use new breadcrumbs component in contextual breadcrumbs

---

CHANGELOG.md

Improve CHANGELOG

---

docs/component_conventions.md

- add guidance for images
- add guidance for helper code

Update component conventions

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

Updating version to 9.1.0

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

Minor additions to the branding model for components.
---
https://govuk-publishing-compon-pr-373.herokuapp.com/component-guide/

Version 9.2.2

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Add metadata to image card component (PR #377)
* Modify share links component (PR #376)
* Remove underline on image card title link (PR #375)
---
https://govuk-publishing-compon-pr-378.herokuapp.com/component-guide/

Version 9.2.3

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

https://govuk-publishing-compon-pr-383.herokuapp.com/component-guide/

Version 9.3.1

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

bump version to 9.5.1

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Attempt to improve Google snippet display (PR #424)
* Add JavaScript detection, HTML5 shim and IE8 stylesheet to admin layout (PR #419)
---
https://govuk-publishing-compon-pr-425.herokuapp.com/component-guide/

Version 9.5.2

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Change breadcrumb class name (PR #435)
* Add admin component for select (PR #434)
* Extend the double dot problem solution (PR #432)
---
https://govuk-publishing-compon-pr-438.herokuapp.com/component-guide/

Version 9.6.0

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/_inset-text.scss
app/views/govuk_publishing_components/components/_inset_text.html.erb
app/views/govuk_publishing_components/components/docs/inset_text.yml
spec/components/inset_text_spec.rb

Add experimental inset text component based on GOVUK Frontend
[Trello card](https://trello.com/c/bzeKhadE)
---
https://govuk-publishing-compon-pr-449.herokuapp.com/component-guide/inset-text

Add inset text component

---

app/views/govuk_publishing_components/components/docs/machine_readable_metadata.yml
lib/govuk_publishing_components/presenters/machine_readable/organisation_schema.rb
lib/govuk_publishing_components/presenters/schema_org.rb

This will be used on organisation pages.
https://trello.com/c/6BoLT4c6

Support Organisation schema.org data

---

app/views/govuk_publishing_components/components/_button.html.erb
lib/govuk_publishing_components.rb
lib/govuk_publishing_components/presenters/button_helper.rb

Move all of the variables into the class and use better view helpers to create the tags.

Refactor button component

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Step by step component, Google snippet improvement (PR #461)
* Add tabs component (PR #455)
* Adds styling for singular related step by step navs (PR #458)
* Add schema.org `isPartOf` links from articles to step by steps (PR #384)
---
https://govuk-publishing-compon-pr-464.herokuapp.com/component-guide/

Update to version 9.9.0

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Add data attributes and spellcheck support for textarea component (PR #468)
* Add data attributes support for input component (PR #469)

Version 9.11.0

---

Gemfile.lock
package-lock.json

Ensure lockfiles are up-to-date

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Allow custom tags in `<head>` for admin layout (PR #480)
* Adds taxonomy list component (PR #476)

Version 9.13.0

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Add the 'about' property for the schema.org schema for an Article with live taxons (PR #482)
* Improve step by step component double dot problem solving code (PR #473)
---
https://govuk-publishing-compon-pr-483.herokuapp.com/component-guide/

Version 9.14.0

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Update tabs component to make the heading inside the panel optional and to add a modifier for panel without border (PR #485)
* Add secondary and secondary quiet modifiers to button component (PR #484)

Version 9.15.0

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Allow target attribute for links generated with the button component (PR #488)
* Add Google Tag Manager script as component (PR #489)

Version 9.16.0

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/_success-alert.scss
app/views/govuk_publishing_components/components/_success_alert.html.erb
app/views/govuk_publishing_components/components/docs/success_alert.yml
spec/components/all_components_spec.rb
spec/components/success_alert_spec.rb

This will be used in content publisher to support flash messages with bodies.
https://trello.com/c/9szY348f

Support a description for Success Alert component

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Add Copy to clipboard component (PR #494)
* Bugfix for Radios component (PR #496)
* Fix for Google Tag Manager component (PR #497)
* Support a description for Success Alert component (PR #499)

Release 9.17

---

CHANGELOG.md
app/assets/javascripts/govuk_publishing_components/components/initial-focus.js
app/assets/stylesheets/govuk_publishing_components/_all_components.scss
app/assets/stylesheets/govuk_publishing_components/components/_error-alert.scss
app/views/govuk_publishing_components/components/_error_alert.html.erb
app/views/govuk_publishing_components/components/_success_alert.html.erb
app/views/govuk_publishing_components/components/docs/error_alert.yml
spec/components/error_alert_spec.rb

This is largely duplicated from the success alert component.

Add error alert component

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Show relevant step by step nav based on user journey (PR #501)
* Add Error alert component (PR #503)
* Add experimental panel component based on GOV.UK Frontend (PR #507)
* Adds step by step content ID to links inside steps (PR #502)
* Pass through label params from textarea component (PR #508)
https://govuk-publishing-compon-pr-509.herokuapp.com/component-guide/

Release 9.18.0

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

Releases recent changes to error_summary component

Release version 9.19.0

---

app/views/govuk_publishing_components/components/_input.html.erb

https://trello.com/c/l8MAts3s/205-build-the-index-page-with-filtering
This changes the input component so that any params for the label are passed through directly.

Pass through label params for input

---

CHANGELOG.md
lib/govuk_publishing_components/version.rb

Pass through label params to input component.

Release 9.20

---

CHANGELOG.md
Gemfile.lock
app/assets/stylesheets/govuk_publishing_components/_all_components.scss
app/assets/stylesheets/govuk_publishing_components/components/_file-upload.scss
app/views/govuk_publishing_components/components/_file_upload.html.erb
app/views/govuk_publishing_components/components/docs/file_upload.yml
spec/components/file_upload_spec.rb

This PR adds file upload component based on GOV.UK Frontend
[Trello card](https://trello.com/c/CoEtwAl4)
---
https://govuk-publishing-compon-pr-515.herokuapp.com/component-guide/file-upload

Add file upload component

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Add file upload component based on GOV.UK Frontend (PR #515)
* Use divs for the alert message bodies (PR #517)

Release 9.21.0

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

9.22.0
==
Contains just one change: #516

Version 9.22.0

---

CHANGELOG.md
lib/govuk_publishing_components/version.rb

Bump to version 9.24.0

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

Bump to 9.25.0
---
https://govuk-publishing-compon-pr-528.herokuapp.com/component-guide/

Bump to version 9.25.0

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Add table component (PR #531)
* Add destructive modifier to button component (PR #523)

Release 9.26.0

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

bump version to 9.28.0

---

app/views/govuk_publishing_components/components/docs/step_by_step_nav.yml

Trello: https://trello.com/c/k2hI1CsM
Details the rules for when and how and step by step is shown in the side bar of a content page.
---

Add documentation about tracking step by step journeys with the query string

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

There are breaking changes. Please, read the CHANGELOG.md file.
---

Bump version to 10.0.0

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Add isPartOf schema to content with document collections (PR #542)
---
https://govuk-publishing-compon-pr-544.herokuapp.com/component-guide/

Bump version to 10.1.0

---

CHANGELOG.md
lib/govuk_publishing_components.rb
lib/govuk_publishing_components/app_helpers/environment.rb
spec/lib/app_helpers/environment_spec.rb

This code is used in content-publisher and content-data-admin, so we should put it here.

Add environment helper

---

spec/components/all_components_spec.rb
spec/components/contextual_sidebar_spec.rb
spec/components/google_tag_manager_script_spec.rb
spec/components/taxonomy_navigation_spec.rb

This makes sure that all components have a test file.

Add consistent spec files for all components

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_admin_analytics.html.erb
app/views/govuk_publishing_components/components/docs/admin_analytics.yml
spec/components/admin_analytics_spec.rb
spec/components/all_components_spec.rb

The code for this was taken from govuk_admin_template and intends to replace that functionality.
https://trello.com/c/05wMNlxg

Add admin analytics component

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_layout_for_admin.html.erb
app/views/govuk_publishing_components/components/docs/layout_for_admin.yml
spec/components/layout_for_admin_spec.rb

This removes some duplication between applications.

Allow product name to be set in browser title

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Fix regression for buttons in govspeak section (PR #582)
* Add character count component based on GOV.UK Frontend (PR #583)

Release v-12.2.0

---

startup.sh

Conditionally installs gems on startup and allows the application to be run against live backing services.

Startup improvements

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

Also updates the changelog to be consistent with previous versions, and removes internal-only changes that won't be useful for people updating an application.
https://trello.com/c/eqcMykln

Release version 12.3.0

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

Bump to version 12.5.0

---

CHANGELOG.md
lib/govuk_publishing_components/version.rb

Bump version number to 12.7.0

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

https://govuk-publishing-compon-pr-617.herokuapp.com/component-guide/

Bump version to 12.7.1

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

There are no breaking changes.
---
https://govuk-publishing-compon-pr-618.herokuapp.com/component-guide/

Bump to version 12 8 0

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

---
https://govuk-publishing-compon-pr-624.herokuapp.com/component-guide/

bump to 12.9.0

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

Bump version to v12.9.1

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

bump to 12.10.0

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

---
https://govuk-publishing-compon-pr-630.herokuapp.com/component-guide/checkboxes

Bump to 12.11.0

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

Bump version to 12.12.0

---

CHANGELOG.md
app/views/govuk_publishing_components/components/docs/checkboxes.yml

https://govuk-publishing-compon-pr-638.herokuapp.com/component-guide/

Corrects name for checkboxes documentation

---

app/assets/javascripts/govuk_publishing_components/components/checkboxes.js
app/assets/javascripts/govuk_publishing_components/components/copy-to-clipboard.js
app/assets/javascripts/govuk_publishing_components/components/feedback.js
app/assets/javascripts/govuk_publishing_components/components/initial-focus.js
app/assets/javascripts/govuk_publishing_components/components/step-by-step-nav.js

Rewriting some of the component javascript files so their self executing functions are written in a consistent way. This change should not impact any functionality.
Also fixing some linting errors, mostly missing semicolons.
---
https://govuk-publishing-compon-pr-641.herokuapp.com/component-guide/

Standardise component javascript

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

Co-Authored-By: Edward Kerry <edward.kerry@digital.cabinet-office.gov.uk>
---
https://govuk-publishing-compon-pr-648.herokuapp.com/component-guide/

Bump to version 12.14.1

---

Gemfile.lock

I missed doing this as part of 8da39a9

Bump Gemfile.lock

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

Includes:
* Update components for finders (PR #643)
---
https://govuk-publishing-compon-pr-653.herokuapp.com/component-guide/

Version 12.16.0

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Add inverse option to metadata component (PR #657)
* Modify warning text component (PR #655)
---
https://govuk-publishing-compon-pr-658.herokuapp.com/component-guide/

Version 12.18.0

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Tabs supports data attributes on the tab element (PR #660)
* Details supports data attributes on root element (PR #660)
* Copy to clipboard supports data attributes for the input element (PR #660)
* Put nested checkboxes into lists to add support for screen readers (PR 642)
https://govuk-publishing-compon-pr-661.herokuapp.com/component-guide/

Version 12.19.0

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

Trello: https://trello.com/c/yRnJfrDN/487-deployment-of-remaining-data-attributes-for-consistent-event-tracking-in-gtm
https://govuk-publishing-compon-pr-663.herokuapp.com/component-guide/

Bump to 12.20.0

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

https://govuk-publishing-compon-pr-669.herokuapp.com/component-guide/

Version 12.21.0

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

Bump version to 13.1
---
https://govuk-publishing-compon-pr-675.herokuapp.com/component-guide/

Bump gem version to 13.1

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

Includes:
* Add guard for user agent and url being nil in feedback (PR #677)
---
https://govuk-publishing-compon-pr-678.herokuapp.com/component-guide/

Version 13.2.0

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Put margin bottom on autocomplete (PR #680)
* Adds hidden class to conditional reveals for radio to resolve flicker issue (PR #679)
* Limit hint styles to checkboxes (PR #681)
---
https://govuk-publishing-compon-pr-682.herokuapp.com/component-guide/

bump version to 13.3.0

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

Includes:
* Allow heading on single checkbox (PR #686)
---
https://govuk-publishing-compon-pr-687.herokuapp.com/component-guide/

Version 13.5.0

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

Includes some very minor changes:
* Add value check to accessible autocomplete custom onConfirm function (PR #693)
* Move all commonly used imports into all_components.scss (PR #683)
---
https://govuk-publishing-compon-pr-694.herokuapp.com/component-guide/

Version 13.5.1

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

Includes:
* Improve autocomplete appearance without js (PR #695)
* Adds tracking to select component (PR #690)

Version 13.5.2

---

Gemfile.lock
lib/govuk_publishing_components/version.rb

Changes included:
- allow navigation items to only show in collapsed menu (PR #691)
---
https://govuk-publishing-compon-pr-705.herokuapp.com/component-guide/

Version 13.5.4

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

Includes:
* Add search to component guide (PR #706)

Bump to 13.6.0

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

Includes:
* Extend toggle module (PR #712)
---
https://govuk-publishing-compon-pr-713.herokuapp.com/component-guide/

Version 13.6.1

---

CHANGELOG.md

Update changelog for changes in #731

Update changelog with latest change (#731)

---

CHANGELOG.md
app/views/govuk_publishing_components/components/docs/notice.yml

https://trello.com/c/HcfYSpjX/634-allow-notice-component-to-accept-html

Clarify block example for notice component

---

CHANGELOG.md
lib/govuk_publishing_components/version.rb

https://trello.com/c/HcfYSpjX/634-allow-notice-component-to-accept-html

Bump version to 15.1.0

---

Gemfile.lock

Sorry for missing this @andysellick - thanks for pointing it out :-).

Forgot to update the Gemfile.lock with new version

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Add margin option to subscription links (PR #748)
* Add multiple selection option to autocomplete (PR #723)

Version 15.2.0

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Update skip-link to allow custom link text (PR #755)
* Support an embed option on examples to allow embedding a component in a particular HTML context (PR #747)

Version 15.3.0

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/_accessible-autocomplete.scss
app/views/govuk_publishing_components/components/_accessible_autocomplete.html.erb
spec/components/accessible_autocomplete_spec.rb

- simplify markup, fix classname and remove redundant test

Refactor accessible autocomplete

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_details.html.erb
spec/components/details_spec.rb

This PR adds custom margin to the details component.

Add a margin_bottom option to details component

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

Bump version to 16.2.0

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

Bump to version 16.3.0

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

Bump gem to version 16.4.0

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

Bump gem version to 16.5.0

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_government_navigation.html.erb
spec/components/government_navigation_spec.rb

Fixes small issue in test for new link to consultations in navigation header

Fixes issue in test for consultations header link

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

This PR upgrades the publishing components from version `16.6.0` to `16.7.0`.

Upgrade to 16.7.0

---

package-lock.json
package.json

This PR updates axe-core to latest version (3.2.2)

Update axe-core to 3.2.2

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Fix margin spacing for small form subscription links (PR #808)

Patch release v16.9.1

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

https://trello.com/c/4kQa7EZO/762-allow-users-embed-videoshttps://trello.com/c/4kQa7EZO/762-allow-users-embed-videos

Bump version to 16.10.0

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

Includes:
- Revert the cookie banner tracking which was added in v16.12.0 (PR #839)

Version 16.4.1

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

- Add attachment (experimental) component (PR #842)

Version 16.16.0

---

CHANGELOG.md

Version 16.17.0

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_radio.html.erb
app/views/govuk_publishing_components/components/docs/radio.yml
spec/components/radio_spec.rb

Add inline radio button option

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

Includes:
- Add new version of (experimental) cookie banner (PR #845)
- Add inline variation for button component (PR #845)

Version 16.18.0

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Adds support to allow parent finder to show as breadcrumbs (PR #831)

Bump to version to 16.19.0

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

We've added the SearchResultsPage schema.

Bump to 16.20.0

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Add request different format section to attachment component (PR #858)
* Fix broken call to content_type fallback method (PR #869)

Release 16.21.0

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

Includes:
* Update inline button styling on mobile (PR #872)

Version 16.22.0

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_attachment.html.erb
app/views/govuk_publishing_components/components/_attachment_link.html.erb
app/views/govuk_publishing_components/components/docs/attachment.yml
app/views/govuk_publishing_components/components/docs/attachment_link.yml
spec/components/attachment_link_spec.rb
spec/components/attachment_spec.rb

https://trello.com/c/1mY4fPN1/857-analytics-for-attachments

Enable passing data attributes to attachments

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

https://trello.com/c/1mY4fPN1/857-analytics-for-attachments

Bump version to 16.23.0

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

Note that #888 is not a breaking change

Bump to 16.24.0

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_modal_dialogue.html.erb
app/views/govuk_publishing_components/components/docs/modal_dialogue.yml

https://trello.com/c/1mY4fPN1/857-analytics-for-attachments

Support data attributes on modal dialogue

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

https://trello.com/c/B9rVHJTh/876-audit-potential-maintenance-issues-with-gtm

Bump version to 16.25.0

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

Small change that adds some missing schema information to search actions.

Bump patch version

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

Includes:
* Make inline buttons 50% width from mobile - tablet (PR #898)

Version 16.28.0

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Accept error_items on date input component (PR #907)
* Accept items on error message component (PR #907)

Bump to version 16.29.0

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Update feedback component error handling (PR #918)
* Support data attributes for error summary items (PR #924)
* Disable youtube embeds if campaign cookies turned off (PR #919)
* Add aria-live flag to notice component (PR #911)
* BREAKING: Check the consent cookie before setting cookies (PR #916)
* Override vertical align: top for inline buttons (PR #912)
* Change cookie banner text to green (PR #912)
* Accessibility and design fixes for cookie banner (#912)

Version 17.0.0

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_cookie_banner.html.erb
spec/components/cookie_banner_spec.rb

Adds tracking to the 'hide' button on the new cookie banner

Add tracking to the new cookie banner

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Fix resetting cookie mechanism for new banner #935

Version 17.1.1

---

README.md

Hot off the back of https://github.com/alphagov/govuk_publishing_components/pull/933 (and I forgot ;-).

Update README to refer to new binstub

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

Tweaks to step by step styles, modal dialogs and addition of ministers to organisation schemas.

Bump to 17.2.0

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Add inverse option to contextual breadcrumbs (PR #943)
* Adds support for secondary content items for step by step (PR #900)
* Adds missing tests for related to step navs (PR #900)
* Adds missing tests for also part of step navs component (PR #900)

Gem version 17.4.0

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

Includes:
* Increase spacing between inline buttons on desktop (PR #946)

Version 17.5.0

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

Includes:
* Add landmark to cookie banner (PR #949)
* Cookie banner confirmation message is read automatically to screenreaders (PR #949)

Version 17.6.0

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

Includes:
* Fix confirmation message being read to screenreaders (PR #952)
* Hide 'Accept Cookies' button when Javascript not available (PR #948)

Version 17.6.1

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

Includes:
- An inverse option for the phase banner (PR #954)

Version 17.7.0

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

Includes:
- Remove old cookie banner code and new_cookie_banner flag (PR #959)

Version 17.8.0

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_table.html.erb
app/views/govuk_publishing_components/components/docs/table.yml
lib/govuk_publishing_components/app_helpers/table_helper.rb
spec/components/table_spec.rb

https://trello.com/c/B9rVHJTh/876-audit-and-fix-gtm-ga-issues

Enable data attributes for table headers

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

https://trello.com/c/B9rVHJTh/876-audit-and-fix-gtm-ga-issues
This creates a new version in order to release support for data attributes on table headers.

Bump version to 17.10.0

---

Gemfile.lock
govuk_publishing_components.gemspec

Upgrade govuk_test to v1

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

Changes:
- Add support for description text (PR #971)
- Stop duplicate links within feedback form (PR #981)
- Add spacing to the feedback form (PR #981)

Bump version to 17.13.0

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Add no underline option to document list component (PR #990)

Version 17.15.0

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Restore missing field to feedback survey form (PR #998)
* Use div elements for hint messages (PR #996)

Version 17.17.0

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

Includes:
* Replace accessible media player with Youtube player (PR #908)

Version 17.18.0

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Replace subscription links images with SVG (PR #1008)
* Change subscription links CSS (PR #1007)

Version 17.19.1

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Add full width option to select component (PR #1012)
* Change statistics header link to link to new finder (PR #1015)

Version 17.20.0

---

CHANGELOG.md
spec/components/feedback_spec.rb
spec/javascripts/components/feedback-spec.js

This ensures that tests will fail if required fields are removed from the component HTML.
Co-Author: @benthorner

Add tests for feedback form fields

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Add tests for email feedback form (PR #1017)
* Fix for select height zoom problem (PR #1018)
* Add `lang` attribute option to subscription links (PR #1019)

Version 17.21.0

---

docs/pull_request_template.md

Removes 'n' from the pull request template link for Heroku deploys:
```
https://govuk-publishing-compon-pr-[PR-NUMBER].herokuapp.com/
```
to
```
https://govuk-publishing-compo-pr-[PR-NUMBER].herokuapp.com/
```
The link was wrong.
None.

Remove erroneous 'n'.

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Expand share links component (PR #1046)
* Add locale option so `lang` attribute can be used on related links (PR #1026)
* Rejigs related navigation line height to avoid focus state overlap (PR #1045)

Version 18.1.0

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Restore node_modules gem dependencies (PR #1048)

Version 18.1.1

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Fix nested checkboxes js (PR #1065)
* Fix image card responsiveness (PR #1055)
* Make contextual title accept and present lang parameter (PR #1056)
* Add summary-list component based on GOV.UK Frontend (PR #1061)

Version 18.2.0

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* `value` and `name` can be set on button component (PR #1059)
* Consolidate input aria documentation and tests (PR #1062)

Version 18.3.0

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Adjust share links column width (PR #1074)

Version 18.3.1

---

CHANGELOG.md

I messed up the conflict resolution in https://github.com/alphagov/govuk_publishing_components/pull/1076 - apologies.

Fix CHANGELOG conflict resolution

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

We've added the FAQPage schema.

Bump to 20.1.0

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Fix data attributes in delete summary list item ([PR #1103](https://github.com/alphagov/govuk_publishing_components/pull/1103))

Version 20.2.2

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Fieldset custom legend size ([PR #1134](https://github.com/alphagov/govuk_publishing_components/pull/1134))

Version 21.2.0

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

We've added some features here, but no breaking changes

Bump to 21.3.0

---

app/assets/javascripts/component_guide/accessibility-test.js
app/assets/javascripts/govuk_publishing_components/dependencies.js
config/initializers/assets.rb

Reverts alphagov/govuk_publishing_components#1162

Revert "Fix assets references"

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

Version 21.6.1

---

app/views/govuk_publishing_components/components/_document_list.html.erb

This makes the code easier to understand.

Rename variable for clarity

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Change tags and styling for feedback component ([PR #1207](https://github.com/alphagov/govuk_publishing_components/pull/1207))

Release version 21.13.2

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

Includes:
- Fix header environment label layout on mobile
[PR #1212](https://github.com/alphagov/govuk_publishing_components/pull/1212)
- Fix Feedback component layout on mobile ([#1211](https://github.com/alphagov/govuk_publishing_components/pull/1207))

Release v21.13.3

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Fix checkbox small option ([#1221](https://github.com/alphagov/govuk_publishing_components/pull/1221))

Version 21.13.5

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_cookie_banner.html.erb

Fix cookies url

---

app/views/govuk_publishing_components/components/docs/cookie_banner.yml

Update to troubleshooting tips
The cookie which determines whether a cookie banner is shown to users has changed

Update cookie name

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_document_list.html.erb

Fix stray closing tag in document list component

Fix markup in document list

---

app/assets/javascripts/component_guide/accessibility-test.js
package-lock.json
package.json
spec/javascripts/govuk_publishing_components/AccessibilityTestSpec.js

Update axe-core to 3.4.1 and remove a workaround set in place to deal with scrolling when an SVG element is present. Fixes https://github.com/alphagov/govuk_publishing_components/issues/1230
Keep dependencies updated.

Update axe-core to 3.4.1

---

app/views/govuk_publishing_components/components/contextual_sidebar/_brexit_cta.html.erb

Trello: https://trello.com/c/ktTNSwAa/398-spike-how-to-update-taxons-so-brexit-becomes-transition
A part of performing tests for potential migrations. Content TBC.
**Before**
**After**

Update contextual sidebar to transition content

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

A relaxation of the rules around step by step navigation.

Bump to 21.21.2

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

Tweaks to step by step sidebar navigation styles.

Bump patch version to 21.21.3

---

package-lock.json
package.json
spec/javascripts/govuk_publishing_components/AccessibilityTestSpec.js

Keeping dependencies up to date and fix lately failing builds

Update axe-core to 3.5.0

---

CHANGELOG.md
docs/install-and-use.md

- following change to sass imports for individual components
We've got a new way of importing sass for components. This change updates the documentation to reflect that.
None.

Update Sass documentation

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_input.html.erb
app/views/govuk_publishing_components/components/docs/input.yml
spec/components/date_input_spec.rb
spec/components/input_spec.rb

Improve numeric input
As described in the [Design System guidance for numbers](https://design-system.service.gov.uk/components/text-input/#numbers)
[Trello card](https://trello.com/c/H3T7JWtS)

Improve numeric inputs

---

app/assets/stylesheets/govuk_publishing_components/components/_layout-footer.scss
app/views/govuk_publishing_components/components/_layout_footer.html.erb

https://trello.com/c/4cNAp5dV/212-implement-footer-with-hardcoded-classes-for-2-1-column-width
1) Adds divs with layout classes as wrappers to the unordered
lists to make alignment across rows work. 
2) Tweaks spacing to accommodate this and to give sections more
breathing space at mobile view sizes.
Fixes existing alignment issues

Fix alignment and spacing on footer

---

CHANGELOG.md
lib/govuk_publishing_components/presenters/machine_readable/article_schema.rb
lib/govuk_publishing_components/presenters/machine_readable/creative_work_schema.rb

We're had feedback to say that we should use name and text instead of
headLine and description generally.

Correct CreativeWork implementation

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/helpers/_brand-colours.scss

We were using the wrong hex code yellow.

Update to correct yellow

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Add application stylesheet where needed ([PR #1436](https://github.com/alphagov/govuk_publishing_components/pull/1436))

Version 21.38.5

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

Releases https://github.com/alphagov/govuk_publishing_components/pull/1438

Version 21.38.6

---

CHANGELOG.md
app/assets/javascripts/govuk_publishing_components/lib/govspeak/youtube-link-enhancement.js

Fixes issue with channel id being added incorrectly

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

Bump to 21.41.0

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Change title component context ([PR #1464](https://github.com/alphagov/govuk_publishing_components/pull/1464))
* Expand scope of suggested sass functionality ([PR #1461](https://github.com/alphagov/govuk_publishing_components/pull/1461))

Version 21.41.3

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Allow summary list custom link text ([PR #1483](https://github.com/alphagov/govuk_publishing_components/pull/1483))

Version 21.44.0

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/_input.scss
app/views/govuk_publishing_components/components/_input.html.erb
app/views/govuk_publishing_components/components/docs/input.yml
spec/components/input_spec.rb

Add a new suffix option to the input component. 
Users were entering data which was unusable, i.e entering text when we desired numbers. This change will help us indicate to users how we would like them to input data. 
Latest Chrome, Firefox, Safari
Latest Edge
IE 11
IE 10
IE9
IE8
[Trello card](https://trello.com/c/7VVBYT7z/257-add-suffix-to-input-fields-on-product-details-question)
Co-Authored-By: @alex-ju

Add suffix to inputs

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

**Version update**
Had to edit the changelog to reflect that suffixes were implemented in this version as opposed to version 21.43.0.

Version 21.45.0

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Add action link component ([PR #1497](https://github.com/alphagov/govuk_publishing_components/pull/1497))
* Add `id` to checkboxes component ([PR #1503](https://github.com/alphagov/govuk_publishing_components/pull/1503))

Version 21.47.0

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

21.50.0
Add is_page_heading to select ([PR #1516](#1516))

bump to version 21.50.0

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Tweak action link ([PR #1518](https://github.com/alphagov/govuk_publishing_components/pull/1518))

Version 21.50.1

---

Gemfile.lock

Run bundle for the last release

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Find components within components ([PR #1541](https://github.com/alphagov/govuk_publishing_components/pull/1541))

Version 21.55.1

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Fix layout on input with prefix/suffix ([PR #1581](https://github.com/alphagov/govuk_publishing_components/pull/1581))

Release 21.56.2

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Add component auditing ([PR #1589](https://github.com/alphagov/govuk_publishing_components/pull/1589))
* Check that details component exists (to fix bug created in #1597) ([PR #1602](https://github.com/alphagov/govuk_publishing_components/pull/1602))

Version 21.59.0

---

app/assets/stylesheets/govuk_publishing_components/components/_step-by-step-nav-header.scss
app/views/govuk_publishing_components/components/_step_by_step_nav_header.html.erb

Fix hover state for step nav header when it is not a link.
Fixes https://github.com/alphagov/govuk_publishing_components/issues/1563
See issue.

Fix step nav header hover state

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

Change bar chart numbers and colours to be accessible ([PR #1608](https://github.com/alphagov/govuk_publishing_components/pull/1608))

Version 21.60.1

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

Gem version 21.60.2

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

Release version 21.60.3 of this gem

Bump Gem to version 21.60.3

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Fix the on blue logic for the search component ([PR #1663](https://github.com/alphagov/govuk_publishing_components/pull/1663))

Version 21.63.2

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

Version 21.66.4

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Remove jQuery from select.js ([PR #1670](https://github.com/alphagov/govuk_publishing_components/pull/1670))
* Add language attribute to feed box ([PR #1706](https://github.com/alphagov/govuk_publishing_components/pull/1706))
* Replace feedback component links with buttons ([PR #1699](https://github.com/alphagov/govuk_publishing_components/pull/1699)) MINOR
* Extend contents list component ([PR #1710](https://github.com/alphagov/govuk_publishing_components/pull/1710))

Update version to 21.67.0

---

README.md

Document SCSS linting setup for this project pointing to stylelint-config-gds.
Remove separator to make the badges fit in one line on wide screens.
Allow a quicker IDE setup for people starting on this project.

Add stylelint badge

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

Update version to 21.67.1

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Adding hover styling for action link ([PR #1728](https://github.com/alphagov/govuk_publishing_components/pull/1728))
* Feed subscription link accessibility fix ([PR #1721](https://github.com/alphagov/govuk_publishing_components/pull/1721))
* Update search component input label ([PR #1727](https://github.com/alphagov/govuk_publishing_components/pull/1727))

Update version to 21.68.1

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Change analytics calls ([PR #1757](https://github.com/alphagov/govuk_publishing_components/pull/1757))

Version 23.2.0

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

Bump version to 23.5.0

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

Inclues:
- Fix to resolve input zoom-text overlap PR #1793

Update to v23.7.3

---

CHANGELOG.md
app/views/govuk_publishing_components/components/docs/button.yml
lib/govuk_publishing_components/presenters/button_helper.rb
spec/components/button_spec.rb

Solid secondary buttons styles from GOVUK design systems
User research has shown that solid secondary buttons worked well

Add support for secondary solid buttons

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_contextual_sidebar.html.erb
app/views/govuk_publishing_components/components/docs/contextual_sidebar.yml
lib/govuk_publishing_components/presenters/contextual_navigation.rb

Hide the transition countdown for a certain page
As requested in https://trello.com/c/wAYobOiJ

Disable the transition countdown on a certain page

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

Update publishing components version to 23.9.2

Bump to 23.9.2

---

CHANGELOG.md
app/controllers/govuk_publishing_components/audit_controller.rb
app/models/govuk_publishing_components/audit_applications.rb
app/models/govuk_publishing_components/audit_comparer.rb
app/views/govuk_publishing_components/audit/show.html.erb
spec/component_guide/audit_applications_spec.rb
spec/component_guide/audit_comparer_spec.rb
spec/dummy/app/assets/javascripts/a-n-other.js
spec/dummy/app/assets/javascripts/application.js

Add a few more applications to the auditing (the new accounts system, and DGU).
Also add in a simple check to look for any instances of jQuery in applications.
Thought this might be useful.

Extend component auditing

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Get analytics code ready for use in production ([PR #1767](https://github.com/alphagov/govuk_publishing_components/pull/1767))

Version 23.12.0

---

Gemfile.lock

This should have been done in that PR.

Bring Gemfile.lock up to date with #1861

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Update document list component with description text modifier and amended design ([PR #1883](https://github.com/alphagov/govuk_publishing_components/pull/1883))
* Fix footer classes ([PR #1898](https://github.com/alphagov/govuk_publishing_components/pull/1898))
* Update document list component with description text modifier and amended design ([PR #1883](https://github.com/alphagov/govuk_publishing_components/pull/1883))

Update version to 23.14.0

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

Includes: 
* Fix bugs on the feedback component ([PR #1900](https://github.com/alphagov/govuk_publishing_components/pull/1900))
* Add data attributes to layout footer component ([PR #1904](https://github.com/alphagov/govuk_publishing_components/pull/1904))
* Add option to remove border from document list items ([PR #1907](https://github.com/alphagov/govuk_publishing_components/pull/1907))
* Update layout header component ([PR #1902](https://github.com/alphagov/govuk_publishing_components/pull/1902))

Update version to 23.15.0

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Remove title attribute from summary list ([PR #1973](https://github.com/alphagov/govuk_publishing_components/pull/1973))
* Summary list changes ([PR #1971](https://github.com/alphagov/govuk_publishing_components/pull/1971))

Version 24.6.0

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

https://trello.com/c/Nbg0L98D/2427-2-ensure-we-have-the-necessary-foreign-languages-locale-files-for-govukpublishingcomponents

Bump version to 24.7.1

---

CHANGELOG.md

Move #2038 from v24.10.0 to Unreleased
The pull request wasn't part of the v24.10.0 release.
None.

Small correction to changelog

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Add event tracking to header elements ([#2110](https://github.com/alphagov/govuk_publishing_components/pull/2110) )

Version 24.13.3

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_government_navigation.html.erb

These didn't match the destination URLs.
Fixes wrong data attribute values for analytics tracking.
Part of work for gathering some baseline data ahead of updating the header design.
None

Fix header tracking labels

---

CHANGELOG.md
app/assets/javascripts/govuk_publishing_components/lib/header-navigation.js

Trello: https://trello.com/c/CwPwNE60/321-implement-analytics-tracking-on-the-existing-headers
Fixes changes that were added in #2110 
As part of gathering some baseline data ahead of updating the header design.
None

Fix wrong label value for event tracking on menu button

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Add links to privacy and accessibility statements in layout footer component

Release 24.16.1

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

Includes:
- Adjust crown alignment in the heading component (#2134)

Release v24.18.2

---

CHANGELOG.md
config/locales/en.yml

Amended to after some reflection and also to match Style Guide.

Update copy for Explore Super Menu Header

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

This release includes:
* Add analytics tags to super navigation header ([PR # 2244](https://github.com/alphagov/govuk_publishing_components/pull/2244))
* Update copy for Explore Super Menu Header ([PR #2247](https://github.com/alphagov/govuk_publishing_components/pull/2247))
* Add hover style for govspeak mc button ([PR #2239](https://github.com/alphagov/govuk_publishing_components/pull/2239))
* Load YouTube video instantly when cookies are accepted ([PR #2241](https://github.com/alphagov/govuk_publishing_components/pull/2241))
* Add dropdown menu to the super navigation header component ([PR #2223](https://github.com/alphagov/govuk_publishing_components/pull/2223))

Release v25.2.0

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_layout_super_navigation_header.html.erb

Fix a tiny typo on declaration of tracking module on super nav header.
Tracking doesn't work otherwise.

Fix typo in tracking module on super navigation header

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Fix track click link tracking ([PR #2265](https://github.com/alphagov/govuk_publishing_components/pull/2265))
* Add language tag for Welsh link in public layout template ([PR #2258](https://github.com/alphagov/govuk_publishing_components/pull/2258))
* Revert "Fix cookie banner issue (IE10)" ([PR #2267](https://github.com/alphagov/govuk_publishing_components/pull/2267))

Version 25.3.1

---

app/views/govuk_publishing_components/components/docs/inverse_header.yml

Corrects some small spelling errors and capitalisations.
So that the words and spelled and capitalised correctly.
None for the components.

Correct minor spelling errors

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

Bumps the gem version to 27.3.1.

Bump gem version to 27.3.1

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_image_card.html.erb
spec/components/image_card_spec.rb

Reverts alphagov/govuk_publishing_components#2335

Revert "Raise argument error on image card component"

---

docs/pull_request_template.md

Adds a reminder to have visual changes reviewed by Designers.
We need to get the review done earlier in our workflow.

Add note to have Designers review visual changes

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Add signup link component ([PR #2525](https://github.com/alphagov/govuk_publishing_components/pull/2525))

Version 27.20.0

---

README.md
docs/component_conventions.md
docs/install-and-use.md
docs/javascript-modules.md
docs/testing-components.md
docs/upgrade-govuk-frontend.md

A few minor tweaks on our docs for more accurate code highlight, a broken link and some formatting.
To keep our docs tidy

A few tweaks on docs

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Add select component hint ([PR #2594](https://github.com/alphagov/govuk_publishing_components/pull/2594))
* Add name attribute to hidden spam input in feedback component ([PR #2586](https://github.com/alphagov/govuk_publishing_components/pull/2586))

Release 28.5.0

---

CHANGELOG.md
app/assets/javascripts/govuk_publishing_components/vendor/lux/lux-reporter.js

Upgraded Speedcurve RUM script to version 300.
In order to not break the real user metrics reporting this script needs to be kept up to date.
None.

Update real user metrics LUX.js to v300

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

Release 28.8.0

---

app/views/govuk_publishing_components/components/_lead_paragraph.html.erb
spec/components/lead_paragraph_spec.rb

Update `lead_paragraph`
Clean up prompted by [this PR](https://github.com/alphagov/govuk_publishing_components/pull/2679/)
NA

Remove new line

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

Release 28.9.2

---

README.md

The branch has been renamed to main

Fix references to master CI badge

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

Release 29.5.0
- Add DFE, DWP and DVSA emails to attachment accessible format request pilot [PR #2736]

Release 29.5.0

---

CHANGELOG.md
config/locales/en.yml

Updated the link path for the Ukraine Call To Action

Update link path for Ukraine CTA

---

CHANGELOG.md

Minor CHANGELOG formatting alterations

---

app/views/govuk_publishing_components/components/_summary_list.html.erb

Small clean up of some of the code in the summary list component.
I was going to do more, but my work on this has stalled as I got busy again, so need to push this out.
None.

Summary list component code cleaning

---

CHANGELOG.md
app/assets/javascripts/govuk_publishing_components/vendor/lux/lux-reporter.js

Update the LUX reporter script from v300 to v301.
If the version of the script gets too old, no data will be able to be sent to Speedcurve. Since we self host this script, we need to make sure that it's the latest version.
None.

Update LUX reporter script to v301

---

CHANGELOG.md

Fix the changelog.
A recent branch merge after a change to the changelog resulted in git incorrectly merging the two.
None.

Correcting changelog

---

README.md
app/views/govuk_publishing_components/components/docs/accordion.yml
docs/auditing.md
spec/javascripts/components/accordion-spec.js

Minor tweaks to some of our documentation.
Some areas of our documentation were not as clear as they could be.
Changes to docs only.

Improve documentation

---

CHANGELOG.md
config/locales/en.yml

Changing the popular links in the search bar to match the popular links on the homepage
Adding the check benefits link to popular links is a request from content.

Update popular links in the super navigation header

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Update the list of popular links in the super navigation header ([PR #2845](https://github.com/alphagov/govuk_publishing_components/pull/2845))
* Add timer field in attempt to reduce spam on feedback component ([PR #2830](https://github.com/alphagov/govuk_publishing_components/pull/2830))

Version 29.13.0

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

Add js search to table component ([PR #2803](https://github.com/alphagov/govuk_publishing_components/pull/2803))

Version 29.15.0

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Update GA4 analytics page view data structure ([PR #2878](https://github.com/alphagov/govuk_publishing_components/pull/2878))

Version 29.15.3

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

Version 30.3.0

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Fix underline on organisation logo component ([PR #2949](https://github.com/alphagov/govuk_publishing_components/pull/2949))
* Integrate GA4 analytics code with cookie consent mechanism ([PR #2915](https://github.com/alphagov/govuk_publishing_components/pull/2915))

Version 30.5.0

---

CHANGELOG.md
config/locales/en.yml

Update the popular links on the search bar at the top of the page
Request from Anna Sherrington via 2nd line. Related frontend PR: https://github.com/alphagov/frontend/pull/3382

Update popular links on search bar

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Refactor analytics code snippets ([PR #2980](https://github.com/alphagov/govuk_publishing_components/pull/2980))
* Add optional gtag snippet ([PR #2979](https://github.com/alphagov/govuk_publishing_components/pull/2979))

Version 30.7.2

---

CHANGELOG.md
app/assets/javascripts/govuk_publishing_components/vendor/lux/lux-reporter.js

Update to LUX version 302, from version 301.
New release.
No change.

Update to LUX 302

---

docs/real-user-metrics.md

Updates the RUM docs.
None.
Trello card: https://trello.com/c/9ZffH7Gn/49-understand-real-user-monitoring-rum

Update RUM documentation

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Feedback component visual updates ([PR #2894](https://github.com/alphagov/govuk_publishing_components/pull/2894))

Version 31.2.0

---

docs/analytics/track-click.md
spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-link-tracker.spec.js
spec/javascripts/govuk_publishing_components/analytics/track-click.spec.js

Adds a test and small documentation update for https://github.com/alphagov/govuk_publishing_components/pull/3042
None.

Add track link test

---

docs/pull_request_template.md

https://trello.com/c/LZctyIYq/3007-automatically-add-extra-instructions-to-dependabot-prs-for-rails-1

Add instructions for upgrading Rails

---

docs/pull_request_template.md

Reverts alphagov/govuk_publishing_components#3067
https://trello.com/c/LZctyIYq/3007-automatically-add-extra-instructions-to-dependabot-prs-for-rails-1

Revert "Add instructions for upgrading Rails"

---

CHANGELOG.md
app/assets/javascripts/govuk_publishing_components/vendor/lux/lux-reporter.js

Update to the newest version of RUM, as detailed here: https://github.com/alphagov/govuk_publishing_components/blob/main/docs/real-user-metrics.md
See previous PR for comparison if needed: https://github.com/alphagov/govuk_publishing_components/pull/3009
Version 304 has just been released.
None.

Update to LUX 304

---

CHANGELOG.md

Fixing changelog entry.
This entry got into the wrong release list following an auto merge by git.
None.

Fixing changelog following auto merge error

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/govuk_frontend_support.scss

Add a new brand colour for the Department for Energy

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

Update version 34.10.0

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/govuk_frontend_support.scss

Reverts alphagov/govuk_publishing_components#3252

Revert changes for new brand colour for Department for Energy Security and Net Zero

---

app/assets/javascripts/govuk_publishing_components/lib/trigger-event.js
docs/lib/trigger_event.md

Add some documentation for `window.GOVUK.triggerEvent`.
Someone asked me how this worked recently and I couldn't remember, so I thought it might be worth writing a short description.
None.

Document the triggerEvent code

---

config/locales/en.yml

Update link on Invasion of Ukraine sidebar
Requested via Slack https://gds.slack.com/archives/CADKZN519/p1677166407299649?thread_ts=1677165710.071309&cid=CADKZN519
N/A
N/A 
N/A

Update link on Invasion of Ukraine sidebar

---

docs/publishing-to-rubygems.md

Clarification on the release process.
To make sure that everyone is informed of the process and is aware when a new release is being made.
None.

Amend new release documentation

---

CHANGELOG.md

Fix the broken link in the changelog for release 34.13.0 and update changelog entry to match the PR name

Fix broken link in the changelog

---

CHANGELOG.md
docs/set-up-individual-component-css-loading.md

Update AssetHelper documentation
Correct documentation references for `add_view`, `add_view_stylesheet` and `add_stylesheet_path`.
None

Update AssetHelper documentation

---

CHANGELOG.md
app/assets/javascripts/govuk_publishing_components/vendor/lux/lux-reporter.js
docs/real-user-metrics.md

Update to version 307 of LUX.
New version, see the [lux documentation](https://github.com/alphagov/govuk_publishing_components/blob/main/docs/real-user-metrics.md#how-to-update-to-a-new-version) for more details.
None.

Update to Lux 307

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/helpers/_brand-colours.scss

Add brand colour for DSIT
This colour needs to be added as a new department has been set up

Add brand colour for DSIT

---

CHANGELOG.md
app/assets/javascripts/govuk_publishing_components/components/step-by-step-nav.js
app/views/govuk_publishing_components/components/_layout_footer.html.erb
app/views/govuk_publishing_components/components/_layout_super_navigation_header.html.erb
lib/govuk_publishing_components/presenters/layout_footer_helper.rb
spec/components/layout_footer_spec.rb
spec/components/layout_super_navigation_header_spec.rb
spec/javascripts/components/step-by-step-nav-spec.js
spec/lib/govuk_publishing_components/components/layout_footer_helper_spec.rb

Fix the `index_total` parameter in step by steps, site footer and site header. See individual commits for details.
We've changed how the index parameters work recently and these changes are to meet that.
None.
Trello card: https://trello.com/c/6hEwEVkq/526-fix-indextotal-parameters

Fix GA4 index_total parameter in various places

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

Releases version 35.3.3 of the gem.

Bump version to 35.3.3

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

Releases version 35.3.4 of the gem.

Bump version to 35.3.4

---

CHANGELOG.md
app/assets/javascripts/govuk_publishing_components/vendor/lux/lux-reporter.js

Updating to the latest version of LUX (from 308 to 309). Has been checked and tested [according to the docs](https://github.com/alphagov/govuk_publishing_components/blob/main/docs/real-user-metrics.md#testing).
See https://github.com/alphagov/govuk_publishing_components/blob/main/docs/real-user-metrics.md for full details.
None.

Upgrade LUX to version 309

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Change how GA4 schema construction works ([PR #3436](https://github.com/alphagov/govuk_publishing_components/pull/3436))
* Add GA4 scroll tracker ([PR #3464](https://github.com/alphagov/govuk_publishing_components/pull/3464))
* Ensure search forms have their text sent to GA4 in lowercase ([PR #3504](https://github.com/alphagov/govuk_publishing_components/pull/3504))
* Add GA4 HTML attachment tracking to attachment component ([PR #3500](https://github.com/alphagov/govuk_publishing_components/pull/3500))
* Add functionality for preventing the redaction of publicly available information ([PR #3509](https://github.com/alphagov/govuk_publishing_components/pull/3509))
* Ensure extra spaces are removed from search forms ([PR #3512](https://github.com/alphagov/govuk_publishing_components/pull/35 …

Version 35.12.0

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

Trello: https://trello.com/c/mwQET0e0/2153-add-link-to-the-benefits-smart-answer-to-the-browse-benefits-page

Bump version 35.15.4

---

CHANGELOG.md
app/assets/javascripts/govuk_publishing_components/vendor/lux/lux-reporter.js
docs/real-user-metrics.md

Update to the latest version of the real user monitoring script, and update the documentation. Have updated and tested according to our [documentation for LUX](https://github.com/alphagov/govuk_publishing_components/blob/main/docs/real-user-metrics.md).
We need to keep this script up to date or it'll stop working. Also some things changed recently, updating the documentation to reflect this.
None.

Update LUX to version 312

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/_layout-super-navigation-header.scss
app/views/govuk_publishing_components/components/_layout_super_navigation_header.html.erb
app/views/govuk_publishing_components/components/_search.html.erb
app/views/govuk_publishing_components/components/docs/search.yml
spec/components/search_spec.rb

[Relevant Trello Card](https://trello.com/c/jvsCcVz1/2178-tweaks-to-apply-to-the-header-on-desktop-m-l)
[Relevant Trello Card](https://trello.com/c/XufISUQy/2179-homepage-look-and-feel-hover-state-bug-s-m)
Requested adjustments to homepage navbar
For both menus
-  Change gutter of navbar on homepage on mobile so it is 24px like the gutter in the homepage.
-  Make font sizes of the link description in the navbar 19px 
-  update margin-top for large navbar.
For the expanded links menu
- Increase padding top to govuk-spacing(8)
- Change spacing between description and link to 10px
For the expanded search menu
- Increase padding top to govuk-spacing(8)
- Remove margin-bottom from search component
- Change search box padding bottom to govuk-spacing(8)
- Change popular list total margin bottom …

Adjustments to the navbar for the homepage

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Make global relative links absolute ([PR #3699](https://github.com/alphagov/govuk_publishing_components/pull/3699))
* Remove duplicate GA4 tracking ([PR #3781](https://github.com/alphagov/govuk_publishing_components/pull/3781))
* Delete unused builds folder ([PR #3778](https://github.com/alphagov/govuk_publishing_components/pull/3778))

Version 37.1.1

---

CHANGELOG.md
app/assets/javascripts/govuk_publishing_components/components/cross-service-header.js
app/assets/stylesheets/govuk_publishing_components/components/_cross-service-header.scss

Update [Cross Service Header](https://components.publishing.service.gov.uk/component-guide/cross_service_header) component with the latest changes from https://github.com/govuk-one-login/service-header.
https://components-gem-pr-3831.herokuapp.com/component-guide/cross_service_header/default/preview.
Ensure consistency in code across two repositories.
None.

Update Cross Service Header component

---

CHANGELOG.md
app/assets/javascripts/govuk_publishing_components/analytics-ga4/ga4-auto-tracker.js
app/assets/javascripts/govuk_publishing_components/analytics-ga4/ga4-event-tracker.js
app/assets/javascripts/govuk_publishing_components/analytics-ga4/ga4-form-tracker.js
app/assets/javascripts/govuk_publishing_components/analytics-ga4/ga4-link-tracker.js
app/assets/javascripts/govuk_publishing_components/analytics-ga4/ga4-scroll-tracker.js
app/assets/javascripts/govuk_publishing_components/analytics-ga4/ga4-smart-answer-results-tracker.js
app/assets/javascripts/govuk_publishing_components/analytics/auto-scroll-tracker.js
app/assets/javascripts/govuk_publishing_components/load-analytics.js
docs/javascript-modules.md
spec/javascripts/govuk_publishing_components/analytics-ga4/init-ga4.spec.js

Fix which cookies are used for initialising analytics modules.
The wrong one was being used.
None.

Fix analytics consent

---

CHANGELOG.md
app/assets/javascripts/govuk_publishing_components/vendor/lux/lux-reporter.js

Update to LUX 313 from version 312. 
See https://github.com/alphagov/govuk_publishing_components/blob/main/docs/real-user-metrics.md for details.
None.

Update LUX to 313

---

docs/analytics-ga4/ga4-all-trackers.md
spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-specialist-link-tracker.spec.js

Just spotted these as part of some other work, a missing space in the trackers docs (which made it a little unreadable) and the indentation of this block of markup in the link test was inconsistent and too far.
Because I want the world to be tidy.
None.

Fix some really tiny things

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

- Update layout_for_admin component to take custom asset filenames [PR #3993](https://github.com/alphagov/govuk_publishing_components/pull/3993)

Version 38.1.1

---

CHANGELOG.md
app/assets/javascripts/govuk_publishing_components/vendor/lux/lux-reporter.js

Update to LUX 314 from version 313.
See https://github.com/alphagov/govuk_publishing_components/blob/main/docs/real-user-metrics.md for details.
None.

Update LUX to 314

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Remove Oxford comma from metadata component ([PR #4012](https://github.com/alphagov/govuk_publishing_components/pull/4012))
* Add null check for input element ([PR #4022](https://github.com/alphagov/govuk_publishing_components/pull/4022))

Version 38.3.1

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Disable Universal Analytics ([PR #4083](https://github.com/alphagov/govuk_publishing_components/pull/4083))

Version 39.2.0

---

CHANGELOG.md
app/assets/javascripts/govuk_publishing_components/vendor/lux/lux-reporter.js

Update to the newest version of LUX. See https://github.com/alphagov/govuk_publishing_components/blob/main/docs/real-user-metrics.md#how-to-update-to-a-new-version for full details.
This seems to be quite a significant change since the last version (3.14) so there are a lot of changes in the diff. I've tried to reformat them as cleanly as possible to minimise this, but it is a large change nonetheless. I've tested it as per the procedure and it appears to be working correctly.
If we don't update LUX will stop working.
None.
Trello card: https://trello.com/c/vf2DrJR8/210-update-lux-script

Update to LUX 4.0.20

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

Add brand colour for MHCLG (https://github.com/alphagov/govuk_publishing_components/pull/4100)

Release 39.2.4

---

CHANGELOG.md
app/assets/javascripts/govuk_publishing_components/vendor/lux/lux-reporter.js

Updates to the latest version of LUX, as documented here: https://github.com/alphagov/govuk_publishing_components/blob/main/docs/real-user-metrics.md
Have tested it using SpeedCurve's online parser, which weirdly suggests that its detected `v4.0.20`, which is incorrect, so I'm not quite sure what's going on there, but there are clearly some changes in this new version, so I'm certain this code is needed.
New version.
None.

LUX version 4.0.23

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Update card component styles ([PR #4141](https://github.com/alphagov/govuk_publishing_components/pull/4141))

Version 41.1.1

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Ensure that organisation logos always print ([PR #4162](https://github.com/alphagov/govuk_publishing_components/pull/4162))
* Fix some layout_header search visual bugs ([PR #4156](https://github.com/alphagov/govuk_publishing_components/pull/4156))
* Fix issue with using special characters in content-list ([PR #4157](https://github.com/alphagov/govuk_publishing_components/pull/4157))
* Add 'Chat entry' component ([PR #4151](https://github.com/alphagov/govuk_publishing_components/pull/4151))
* Update and/or add component print styles ([PR #4073](https://github.com/alphagov/govuk_publishing_components/pull/4073))
* Move crown logo svgs into partials ([PR #4164](https://github.com/alphagov/govuk_publishing_components/pull/4164))

Version 42.1.0

---

CHANGELOG.md
app/assets/javascripts/govuk_publishing_components/vendor/lux/lux-reporter.js

Update LUX script, as described in https://github.com/alphagov/govuk_publishing_components/blob/main/docs/real-user-metrics.md#how-to-update-to-a-new-version
If we don't upgrade within a certain timeframe this will stop working.
None.

LUX version 4.0.26

---

docs/analytics-ga4/analytics.md

Improve the wording of the analytics documentation, specifically around adding extra code alongside the existing analytics code and modules.
We've been having some problems getting this to work and I couldn't clearly recall how any of this fit together, so clarifying it now while I remember.
None.

Improve analytics documentation

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Remove unused cookies from cookie category ([PR #4234](https://github.com/alphagov/govuk_publishing_components/pull/4234))
* Allow custom name attribute on password input ([PR #4238](https://github.com/alphagov/govuk_publishing_components/pull/4238))
* Fix sortable table header issue on mobile ([PR #4233](https://github.com/alphagov/govuk_publishing_components/pull/4233))

Bump version to 43.3.0

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Add chart component ([PR #4301](https://github.com/alphagov/govuk_publishing_components/pull/4301))
* Add inverse option for organisation logo ([PR #4284](https://github.com/alphagov/govuk_publishing_components/pull/4284))
* New options for contents-list component ([PR #4305](https://github.com/alphagov/govuk_publishing_components/pull/4305))

Version 44.4.0

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_emergency_banner.html.erb
app/views/govuk_publishing_components/components/docs/emergency_banner.yml

- Adds the component wrapper to the `emergency banner` component
- https://trello.com/c/qH4NyWJw/364-add-component-wrapper-to-more-components#comment-66fe6e7c9757203502c5ea6d
None.

Add component wrapper to emergency banner component

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Layout super nav header: Correct URL for search form ([PR #4341](https://github.com/alphagov/govuk_publishing_components/pull/4341))
* Add support for data attributes in Summary List and Summary Card rows ([PR #4331](https://github.com/alphagov/govuk_publishing_components/pull/4331))

Release version 44.9.0

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Layout super nav header: Correct name for search input ([PR #4347](https://github.com/alphagov/govuk_publishing_components/pull/4347))

Release 44.9.1

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Chart component accessibility improvements ([PR #4344](https://github.com/alphagov/govuk_publishing_components/pull/4344))
* Add new custom analytics tracker for search and use in layout super nav header ([PR #4354](https://github.com/alphagov/govuk_publishing_components/pull/4354))

Release 44.10.0

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/_chat-entry.scss
app/views/govuk_publishing_components/components/_chat_entry.html.erb
config/locales/en.yml
spec/components/chat_entry_spec.rb

Chat entry component design changes
- Add 'New' header tag 
- Update heading copy
Design requirements

Chat entry component design changes

---

CHANGELOG.md
app/assets/javascripts/govuk_publishing_components/vendor/lux/lux-reporter.js

LUX 4.0.28

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Support Welsh devolved nations component ([PR #4440](https://github.com/alphagov/govuk_publishing_components/pull/4440))
* Use component wrapper on previous and next component ([PR #4463](https://github.com/alphagov/govuk_publishing_components/pull/4463))
* Use component wrapper on related nav component ([PR #4466](https://github.com/alphagov/govuk_publishing_components/pull/4466))

Version 46.2.0

---

docs/component_conventions.md

Updates to the print styles documentation. [Trello](https://trello.com/c/sx41Eg5M/337-document-our-print-css-approach)
We've recently improved our print stylesheets which introduced some new standards and conventions.

Update print styles documentation

---

app/models/govuk_publishing_components/component_doc.rb
app/views/govuk_publishing_components/components/docs/heading.yml
app/views/govuk_publishing_components/components/docs/inverse_header.yml
docs/test-a-branch-of-the-gem.md

- Fix broken links to design system documentation
- Fix GitHub searches for app components
- Update the "Test a branch of the components gem" documentation
Help ensure the documentation is easy to follow and works as expected when used.

Documentation fixes

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Fix RTL support in metadata component ([PR #4596](https://github.com/alphagov/govuk_publishing_components/pull/4596))

Version 51.1.1

---

CHANGELOG.md
app/assets/javascripts/govuk_publishing_components/vendor/lux/lux-reporter.js
docs/real-user-metrics.md

- Updates LUX to `4.0.30`
- Also updated the docs, as I think they were out of date (I can't find `dist/lux.js` within their repo so I added build instructions instead.)
-  In the docs I've also added a way to find out what lines need to be updated in the script using a diff check, which might make things a bit simpler. I added this as I initially copied and pasted the whole `lux.js` file over, when in reality only a few lines needed changing and I spent a lot of time trying to fix the formatting when I copied the whole updated file over. 
- However if you think what I've added is too brittle of a way of updating LUX I can remove it. Though if that's the case I think there may need to be some more guidance on how to fix the formatting, as I didn't know of an automatic way to format the …

Update LUX to v4.0.30

---

CHANGELOG.md

Changelog update was missed in PR 4630

Update changelog with missed PR

---

app/views/govuk_publishing_components/components/_layout_for_public.html.erb
spec/components/layout_for_public_spec.rb

Turn off the blue bar below the header
https://trello.com/c/3EkNY2Bs/3254-prepare-a-pr-to-turn-off-the-blue-border-at-the-bottom-of-the-header

Turn off the blue bar below the header

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/_layout-super-navigation-header.scss

Delete unused CSS from layout super navigation component
https://trello.com/c/mKyTK3U3/3358-remove-unused-css-in-super-navigation-layout-header

Delete unused CSS from layout super navigation component

---

app/assets/stylesheets/govuk_publishing_components/components/_feedback.scss

Update feedback component background colour
**Review URL**: https://components-gem-pr-4766.herokuapp.com/component-guide/feedback/default/preview
https://trello.com/c/g62sA8Vn/3439-update-background-colour-of-the-feedback-component

Update feedback component background colour

---

app/assets/stylesheets/govuk_publishing_components/components/_layout-header.scss
app/assets/stylesheets/govuk_publishing_components/components/_layout-super-navigation-header.scss

Update layout header component heights
Review URLs:
- [Super navigation header](https://components-gem-pr-4790.herokuapp.com/component-guide/layout_super_navigation_header)
- [Header](https://components-gem-pr-4790.herokuapp.com/component-guide/layout_header)
https://trello.com/c/oVceps41/3464-update-the-super-navigation-header-component-height

Update layout header component heights

---

app/assets/stylesheets/govuk_publishing_components/components/_layout-super-navigation-header.scss
app/views/govuk_publishing_components/components/_layout_for_public.html.erb
app/views/govuk_publishing_components/components/_layout_super_navigation_header.html.erb
app/views/govuk_publishing_components/components/docs/layout_for_public.yml
app/views/govuk_publishing_components/components/docs/layout_super_navigation_header.yml
spec/components/layout_super_navigation_header_spec.rb

Add option to increase spacing around the homepage logo
https://trello.com/c/KYHiDTkM/3437-review-homepage-padding-and-spacing

Add option to increase spacing around the homepage logo

---

CHANGELOG.md
app/assets/javascripts/govuk_publishing_components/analytics-ga4/ga4-page-views.js
spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-page-views.spec.js

Add `user-id` to `page_view` tracked event.
Requested change from Publishing PA team. Addresses WHIT-2306.

Add `user-id` to `page_view` tracked event

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Add spaces to phone number PII redaction ([PR #4937](https://github.com/alphagov/govuk_publishing_components/pull/4937))

Release version 59.1.1
