alphagov/govuk_publishing_components

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
Includes:
* Set LUX's sampling rate to 1% ([PR 2145](https://github.com/alphagov/govuk_publishing_components/pull/2145))
> Release v24.15.0

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/lib/header-navigation.js
- spec/javascripts/components/header-navigation-spec.js
There is already tracking in place to see how users use the search toggle - this adds tracking for the menu toggle.
Since the functionality for the toggling of the menu comes from GOV.UK Frontend, this needed to be a separate event listener added to specifically send events to analytics.
This can be removed when the AB test has been completed.
The tests proved impossible to get passing without a substantial rewrite of the header navigation JavaScript itself - the tests have been added but skipped in case inspiration strikes at a later date.
To enable analysis of how users use the menu and the search on smaller screens.
None
> Added tracking for the header menu toggle

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
Includes:
* Added tracking for the header menu toggle ([PR #2143](https://github.com/alphagov/govuk_publishing_components/pull/2143))
> Release v24.15.1

- CHANGELOG.md
- lib/govuk_publishing_components/presenters/content_breadcrumbs_based_on_priority.rb
- spec/lib/govuk_publishing_components/presenters/content_breadcrumbs_based_on_priority_spec.rb
We want to add a custom dimension to the data sent to GA when a user clicks a superbreadcrumb for one of the brexit taxon pages.
To make it easier to analyse the data.
None
Trello: https://trello.com/c/v6Qc6Erc/1582-capture-the-audience-type-on-brexit-pages-as-a-custom-dimension-in-ga
> Add a Custom dimension to Brexit super breadcrumbs

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/vendor/lux/lux.js
A lot of these changes are down to a different minifier that renames variables.
From Speedcurve's change log:
- v216:
- Ensures LUX.beaconMode is not overwritten in SPAs
- v215:
- Reinstates buffered long tasks with corrected PerformanceObserver logic
- Rewrite JS page label logic to use Function() rather than eval() to prevent local scope access, for better performance, and to decrease bundle size.
To ensure that our self-hosted version of LUX is up-to-date.
None.
> Update LUX JavaScript from v214 to v216

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
Includes:
* Update LUX JavaScript from v214 to v216 (PR #2152)
* Add a custom dimension to clicks on super breadcrumbs tagged to a brexit taxon (PR #2149)
> Release v24.15.2

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/vendor/lux/lux.js
Turns off LUX's debug mode and removes a `console.log`.
The logging serves no purpose on production as it logs into the browser console - it can be safely removed and turned off.
None.
> Turn off LUX's debug mode

- CHANGELOG.md
- app/views/govuk_publishing_components/components/layout_header/_search.html.erb
Previous data tracking events added to the search button weren't included in the new public layout template as they didn't need to until frontend applications began using the newer template in production. Well they do now!
This is part of work to baseline data of usage of navigation elements before a redesign.
None
> Add tracking on search submit to public layout

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/analytics/scroll-tracker.js
Add scroll tracking to the brexit child taxon pages. 
So we can measure user engagement with these pages.
None
> Add scroll tracking to the brexit child taxon pages

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
* Add tracking on search submit to public layout ([PR #2157](https://github.com/alphagov/govuk_publishing_components/pull/2157))
* Turn off LUX's debug mode ([PR #2156](https://github.com/alphagov/govuk_publishing_components/pull/2156))
> Release 24.15.3

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/analytics/scroll-tracker.js
Add scroll tracking to /guidance/import-and-export-goods-using-preference-agreements
To monitor user engagement.
None
Trello: https://trello.com/c/OD132cuZ/1610-add-scroll-depth-tracking-to-new-rules-of-origin-triage-page
> Add scroll tracking to /guidance/import-and-export-goods-using-preference-agreements

- CHANGELOG.md
- app/views/govuk_publishing_components/components/_layout_for_public.html.erb
- app/views/govuk_publishing_components/components/docs/layout_for_public.yml
- spec/components/layout_for_public_spec.rb
Adjust `layout_for_public` component to accept an optional `product_name` parameter, as well as an option to hide the feedback component. 
Both of these features are needed for the account homepage which is being moved over from `govuk-account-manager-prototype` to `frontend`: https://github.com/alphagov/frontend/compare/msw/account-home-page.
The account manager uses a different site header from the rest of GOVUK. Some main differences are:
- the account related navigation links in the header
- the “Account” product name next to the home link/logo
- the home link directs the user back to the account homepage (as opposed to other pages on GOVUK where the home link will link back to the GOVUK homepage)
- account pages also don't use the side-wide feedback component
This was not an issue on …
> Amend layout_for_public component

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
* Allow custom font size on action links ([PR #2162](https://github.com/alphagov/govuk_publishing_components/pull/2162))
* Add scroll tracking to /guidance/import-and-export-goods-using-preference-agreements ([PR #2165](https://github.com/alphagov/govuk_publishing_components/pull/2165))
* Amend layout_for_public component ([PR #2160](https://github.com/alphagov/govuk_publishing_components/pull/2160))
> Release 24.16.0

- CHANGELOG.md
- app/views/govuk_publishing_components/components/docs/layout_footer.yml
This adds links to the privacy statement and accessibility statement to the layout footer metadata.
These exist on the live site where the footer isn't presented by the public layout, presumably they were updated after this version was forked.
Before:
After:
> Add links to privacy and accessibility statements

- app/assets/javascripts/govuk_publishing_components/components/button.js
- app/assets/javascripts/govuk_publishing_components/components/character-count.js
- app/assets/javascripts/govuk_publishing_components/components/checkboxes.js
- app/assets/javascripts/govuk_publishing_components/components/details.js
- app/assets/javascripts/govuk_publishing_components/components/error-summary.js
- app/assets/javascripts/govuk_publishing_components/components/layout-header.js
- app/assets/javascripts/govuk_publishing_components/components/radio.js
- app/assets/javascripts/govuk_publishing_components/components/tabs.js
- app/assets/javascripts/govuk_publishing_components/modules.js
- app/views/govuk_publishing_components/components/_checkboxes.html.erb
- app/views/govuk_publishing_components/components/_details.html.erb
- spec/javascripts/components/checkboxes-spec.js
- spec/javascripts/components/details-spec.js
- spec/javascripts/govuk_publishing_components/modules.spec.js
Allow multiple JavaScript modules on a certain element.
To allow components using scripts from both `govuk-frontend` and `govuk_publishing_components` to work as intended. This fixes a bug where the checkboxes and details components only load the `govuk-frontend` scripts as a result of [converging to a single module system](https://github.com/alphagov/govuk_publishing_components/pull/2095).
This PR proposes a uniform notation between the `data-module` values (e.g. "govuk-checkboxes" or "gem-checkboxes") and the JavaScript module names (`GovukCheckboxes` and `GemCheckboxes`) with the possibility to apply multiple modules on a certain element. This makes the modules system a bit less 'magical' in the sense that its behaviour is more predictable instead of trying to automatically initialise …
> Allow multiple JavaScript modules on a certain element

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/lib/govspeak/all.js
- app/assets/javascripts/govuk_publishing_components/vendor/polyfills/all.js
This pull request adds a `all.js` file in each folder that uses `require_tree` for the govspeak and polyfill folders.
A recent change meant that `include` was needed for individual JavaScript files in the [polyfill][1] and [govspeak][2] folders - this was to avoid Static _and_ frontend applications from loading the same JavaScript file twice on the same page.
But this means that any additions to these folders will be left out and have to manually added to each of the frontend applications again. Unfortunately `require_tree` is only available for local files - so the frontend applications can not `require_tree` for folders in the gem.
Adding `require_tree` in a file means that this can be used in each frontend application, doesn't need manually updating, and ensures that any additions to …
> Add faux `require_tree` for Govspeak and polyfills

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
* Allow multiple JavaScript modules on a certain element ([PR #2170](https://github.com/alphagov/govuk_publishing_components/pull/2170))
* Add Brexit variation to action links ([PR #2172](https://github.com/alphagov/govuk_publishing_components/pull/2172))
* Add faux `require_tree` for Govspeak and polyfills ([PR #2173](https://github.com/alphagov/govuk_publishing_components/pull/2173))
> Release 24.17.0

- CHANGELOG.md
- app/views/govuk_publishing_components/components/_radio.html.erb
- app/views/govuk_publishing_components/components/docs/radio.yml
- docs/component_conventions.md
- spec/components/radio_spec.rb
Adds the margin_bottom option to the radio component, using the shared helper.
Also expands the documentation for the shared helper, because I had to look through code to remember how to do this.
Need this option for the radio component on the coronavirus landing page.
Trello card: https://trello.com/c/eE62ythU/447-coronavirus-timeline-frontend
> Add margin bottom to radio component

- CHANGELOG.md
- app/views/govuk_publishing_components/components/docs/layout_footer.yml
- lib/govuk_publishing_components/presenters/public_layout_helper.rb
This updates the meta block on alternate variants of the footer to bring them in line with the change made in [PR #2165](https://github.com/alphagov/govuk_publishing_components/pull/2165)
> Update meta links in layout footer variants

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
* Add margin bottom to radio component ([PR #2175](https://github.com/alphagov/govuk_publishing_components/pull/2175))
* Add privacy and accessibility links to the layout footer ([PR #2177](https://github.com/alphagov/govuk_publishing_components/pull/2177))
> Release 24.18

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/analytics/custom-dimensions.js
- lib/govuk_publishing_components/presenters/content_breadcrumbs_based_on_priority.rb
- lib/govuk_publishing_components/presenters/meta_tags.rb
- spec/components/meta_tags_spec.rb
- spec/lib/govuk_publishing_components/presenters/content_breadcrumbs_based_on_priority_spec.rb
1. Remove custom dimension 111 from clicks to the Brexit superbreadcrumb
2. Add custom dimension 111 to the GA payload for page views when a page is displaying a brexit superbreadcrumb
Request from PA
> Add custom dimension to segment page views by Brexit audience type

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
Includes:
* Update LUX to activate when usage cookies are accepted (#2154)
* Add custom dimension to segment page views by Brexit audience type (#2186)
> Release v24.18.1

- CHANGELOG.md
- app/views/govuk_publishing_components/components/_character_count.html.erb
Changes the locale key used in the character count component to use the correct one.
This wrong key was used in a51250be8.
We are currently presenting `{:body=>"You can enter up to %{number} %{type}", :type=>{:characters=>"characters", :words=>"words"}}` when it should say `You can enter up to n [characters|words]`.
> Use correct locale key for character count component

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
This releases the fix in https://github.com/alphagov/govuk_publishing_components/pull/2189.
> Bump version to 24.18.3

- CHANGELOG.md
- config/locales/cy.yml
- spec/components/brexit_cta_spec.rb
As we prepare to launch the Brexit-related guidance in Welsh we received translations for a few components used on the page. We've also updated the key order for transition subitems to align it with the .en locale
For language consistency across the page.
No visual changes (aside from content being updated, of course)
[Trello card](https://trello.com/c/0chnMRTQ)
> Add Welsh translations for topics, transition and tabs

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/analytics/custom-dimensions.js
- app/views/govuk_publishing_components/components/_contextual_breadcrumbs.html.erb
- lib/govuk_publishing_components/presenters/meta_tags.rb
- spec/components/contextual_breadcrumbs_spec.rb
- Update CD 111 to track the audience on page views of all pages tagged to a brexit (priority) taxon. 
- Add CD 112 to track the audience on page views for pages tagged to a brexit (priority) taxon AND showing the brexit superbreadcrumb.
Request from PA
None
- both brexit-superbreadcrumb and brexit-audience are set. 
- only the brexit-audience is set.
> Update custom dimension tracking for brexit superbreadcrumbs

- app/views/govuk_publishing_components/components/docs/checkboxes.yml
Give working examples for the checkbox name
Checkboxes in Rails have a bit of a configuration quirk. If you don't add `[]` to the name, only the last selected value is passed to the controller, rather than an array of all of the selected values.
The name needs to be backed by indicating that the checkbox param is an array in the controller.
For example, if the checkbox is called `nationality[]`, then you need to do the permit as:
```
params.permit(nationality: [])
```
N/A
> Give working examples for the checkbox name

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
Includes:
* Add Welsh translations for topics, transition and tabs ([PR #2193](https://github.com/alphagov/govuk_publishing_components/pull/2193))
* Add custom dimension for pages displaying the Brexit superbreadcrumb ([PR #2197](https://github.com/alphagov/govuk_publishing_components/pull/2197))
> Bump version to 24.18.4

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/components/details.js
- app/views/govuk_publishing_components/components/_details.html.erb
- app/views/govuk_publishing_components/components/docs/details.yml
- spec/components/details_spec.rb
- spec/javascripts/components/details-spec.js
- move the tracking attributes onto the summary element rather than the whole component
- this prevents collisions from occurring if we want to track links or other elements that appear inside the details element, using the gem-track-click script
I recently needed to track radio buttons inside a details component and the tracking was either not firing or firing twice, the second track being from the details component. This is partly because the `gem-track-click` tracking script attempts to traverse up the DOM if it can't find what it's trying to track, which was then colliding with the tracking on the details component... it was all very confusing. 
The solution is to move the tracking from the details component to the summary element within, which is actually the thing being tracked …
> Change tracking on details component

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/analytics/scroll-tracker.js
Add scroll tracking to the welsh versions of the brexit child taxon pages.
Request from PA
None
> Add scroll tracking for brexit child taxon pages in welsh

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/_action-link.scss
Adjust the size and positioning of the Brexit variation of action link
We'd like the Brexit arrow to scale down (along with the text) on narrow screens
<table>
</td></tr>
</table>
> Fix arrow size on Brexit variation of action link

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
* Add scroll tracking to Welsh Brexit child taxon pages ([PR #2201](https://github.com/alphagov/govuk_publishing_components/pull/2201))
* Fix arrow size on Brexit variation of action link ([PR #2203](https://github.com/alphagov/govuk_publishing_components/pull/2203))
> Release 24.18.5

- app/views/govuk_publishing_components/components/docs/layout_header.yml
The option to override the default layout header logo link was introduced some time back, but it was not documented in the component guide.
> Add missing layout_header documentation

- CHANGELOG.md
- lib/govuk_publishing_components/app_helpers/environment.rb
- spec/lib/govuk_publishing_components/app_helpers/environment_spec.rb
This PR switches the `Environment` app helper to use the `GOVUK_ENVIRONMENT_NAME` when getting the current environment for use in the layout header component. The reason for this change is that we're removing the `ERRBIT_ENVIRONMENT_NAME` environment variable in favour of `GOVUK_ENVIRONMENT_NAME`, with the former being an overhang from the days when GOV.UK used Errbit. The `GOVUK_ENVIRONMENTS` variable is refactored from a hash to an array, as we no longer have a weird edge case where the name of the integration environment is different to the acceptance environment that the method returns; there will be a performance impact with this as we're no longer doing a constant-time lookup, but given the number of environments this should be negligible.
It also refactors the associated tests and …
> Switch environment app helper to use GOVUK_ENVIRONMENT_NAME

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/_all_components.scss
- app/assets/stylesheets/govuk_publishing_components/components/_intervention.scss
- app/views/govuk_publishing_components/component_guide/index.html.erb
- app/views/govuk_publishing_components/components/_intervention.html.erb
- app/views/govuk_publishing_components/components/docs/intervention.yml
- config/locales/en.yml
- spec/components/intervention_spec.rb
A new component called "intervention" which will be used for showing personalised content (based on previous browsing). The component's content is hardcoded for now, as this is an MVP which will be used only in the Start a Business area of gov.uk 
The data labs' Personalisation Without an Account project includes showing users recommended content, based on their behaviour on www.gov.uk
Visual design for new component
> Intervention component

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
Includes: 
* Switch environment app helper to use GOVUK_ENVIRONMENT_NAME
* Add intervention component 
* Fix misaligned crown in heading component properly
> Bump version to 24.19.0

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/lib/trigger-event.js
- spec/javascripts/govuk_publishing_components/lib/trigger-event-spec.js
Expands the trigger event script to allow the following:
- allow a keyCode to be passed (yes, this is deprecated, but it works right now)
- allow 'bubbles' and 'cancelable' to be set, previously defaulted to true
The first thing is needed for some tests in finder-frontend (e.g. https://github.com/alphagov/finder-frontend/blob/main/spec/javascripts/live_search_spec.js#L291). The second thing seems like a logical addition.
None.
> Expand trigger event script options

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
* Add inverse option for govspeak ([PR #2207](https://github.com/alphagov/govuk_publishing_components/pull/2207))
* Expand trigger event script options ([PR #2199](https://github.com/alphagov/govuk_publishing_components/pull/2199))
> Version 24.20.0

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/_document-list.scss
- app/views/govuk_publishing_components/components/_document_list.html.erb
- spec/components/document_list_spec.rb
The document list component was recently updated to use the new `govuk-frontend` link styles, but I spotted a couple of problems.
- fixes With only link variant, by removing overflow hidden (was clipping bottom border off focussed link)
- fixes With parts variant, by adding extra styles in and improving spacing beneath link (hover was wrong and hover + focus had a double underline)
- remove general link style in favour of using govuk-link class in template
Improving consistency for our link styles.
Before | After
> Fix new link styles on document list

- CHANGELOG.md
- a build fail with the release of 24.20.0 meant that PR 2179 was actually included in that release, but the changelog didn't say so, this corrects that
-
> Correcting changelog

- CHANGELOG.md
- lib/govuk_publishing_components/presenters/content_breadcrumbs_based_on_priority.rb
- lib/govuk_publishing_components/presenters/meta_tags.rb
- spec/components/contextual_breadcrumbs_spec.rb
- spec/components/meta_tags_spec.rb
- spec/lib/govuk_publishing_components/presenters/content_breadcrumbs_based_on_priority_spec.rb
Improve the tracking of pages tagged to a brexit priority taxon. 
If a page is tagged to a priority brexit taxon, we want it to contain a meta tag for the brexit audience type (`govuk:brexit-audience`), and send the value of that meta tag to GA as custom dimension 112. Currently this will not happen if the page is also tagged to a higher priority taxon (eg coronavirus child taxons).
The [brexit_audience](https://github.com/alphagov/govuk_publishing_components/blob/bb7d37240a898b38ab3e70d669c6187459e9f3e1/lib/govuk_publishing_components/presenters/content_breadcrumbs_based_on_priority.rb#L46-L52) method is used by the meta_tag presenter to [decide](https://github.com/alphagov/govuk_publishing_components/blob/bb7d37240a898b38ab3e70d669c6187459e9f3e1/lib/govuk_publishing_components/presenters …
> Add meta tag to all content tagged to Brexit

- config/initializers/assets.rb
- spec/javascripts/support/jasmine.yml
The visual regression testing JavaScript was removed in #2033 - these references to the deleted file were missed. This fixes that omission.
It was a bit annoying as this caused 404 errors to be noted in the console when running Jasmine in the browser.
None.
> Remove references to visual regression JavaScript

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/analytics/scroll-tracker.js
Adds scroll tracking to the following pages:
- https://www.gov.uk/guidance/red-amber-and-green-list-rules-for-entering-england
- https://www.gov.uk/guidance/travel-abroad-from-england-during-coronavirus-covid-19
- https://www.gov.uk/guidance/travel-to-england-from-another-country-during-coronavirus-covid-19
- https://www.gov.uk/find-travel-test-provider
We want to know if users are scrolling on these pages.
None.
Trello card: https://trello.com/c/BSAZSZnI/479-add-scroll-tracking-to-travel-pages
> Add scroll tracking to travel advice pages

- CHANGELOG.md
- app/views/govuk_publishing_components/components/_layout_for_public.html.erb
- app/views/govuk_publishing_components/components/docs/layout_for_public.yml
- spec/components/layout_for_public_spec.rb
Add `omit_footer_navigation` to `layout_for_public`.
This feature is required to update `service-manual-frontend` (https://www.gov.uk/service-manual) to the new layout.
👉 [Preview the component with this flag on](https://govuk-publis-gem-layout-jaztpm.herokuapp.com/component-guide/layout_for_public/omit_footer_navigation/preview)
> Allow the public layout to render without the footer navigation

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
* Add scroll tracking to travel advice pages ([PR #2217](https://github.com/alphagov/govuk_publishing_components/pull/2217))
* Fix new link styles on document list ([PR #2211](https://github.com/alphagov/govuk_publishing_components/pull/2211))
* Make sure custom dimension 112 is sent for all pages tagged to Brexit ([PR #2212](https://github.com/alphagov/govuk_publishing_components/pull/2212))
* Allow the public layout to render without the footer navigation ([PR #2218](https://github.com/alphagov/govuk_publishing_components/pull/2218))
> Version 24.21.0

- CHANGELOG.md
- lib/govuk_publishing_components/presenters/content_breadcrumbs_based_on_priority.rb
This prevents an error from being thrown when `priority_brexit_taxon` is nil because there isn't relevant taxon tagged to the content item
> Fix issue where priority_brexit_taxon is nil

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
* Fix issue where metatag component throws an error when priority_brexit_taxon isn't available. ([PR #2227](https://github.com/alphagov/govuk_publishing_components/pull/2227))
> Version 24.21.1

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/print/_attachment.scss
- app/assets/stylesheets/govuk_publishing_components/components/print/_back-link.scss
- app/assets/stylesheets/govuk_publishing_components/components/print/_feedback.scss
- app/assets/stylesheets/govuk_publishing_components/components/print/_layout-footer.scss
- app/assets/stylesheets/govuk_publishing_components/components/print/_layout-header.scss
- app/assets/stylesheets/govuk_publishing_components/components/print/_metadata.scss
- app/assets/stylesheets/govuk_publishing_components/components/print/_search.scss
- app/assets/stylesheets/govuk_publishing_components/components/print/_share-links.scss
- app/assets/stylesheets/govuk_publishing_components/components/print/_skip-link.scss
- app/assets/stylesheets/govuk_publishing_components/components/print/_subscription-links.scss
- app/assets/stylesheets/govuk_publishing_components/components/print/_translation-nav.scss
- spec/component_guide/component_index_spec.rb
Not long ago, there was some refactoring to remove `display: none` rules from component stylesheets in favour of using the `govuk-!-display-none-print` class instead: alphagov/govuk_publishing_components#1561
As a consequence of that refactoring process, some of the component print stylesheets which previously used to contain CSS are now empty files  ([Example](https://github.com/alphagov/govuk_publishing_components/blob/9213c4fc722900eda91c722cbb1af69ecacdafb7/app/assets/stylesheets/govuk_publishing_components/components/print/_back-link.scss)). These empty files could not be removed immediately as they were referenced in many applications' print stylesheets  ([Example](https://github.com/alphagov/govuk-account-manager-prototype/blob/7858b55afcddc2f855d909abd051838d95f21f13/app/assets/sty …
> Delete empty print stylesheets

- spec/dummy/config/application.rb
This applies whatever the current Rails version config defaults to this
app. This has been done to bring the defaults up to date (6.1) in such
a way that we don't need to maintain this number.
The reason this has been applied is because we are experiencing a bug
with sentry-rails where a file is failing to load (stack trace below). I
discovered this seems to be an issue with the classic Rails autoloader
whilst it seems resolved with Zeitwerk.
Keeping the Rails defaults up-to-date also seems a logical step to
making testing with Rails versions more accurate.
Stack trace:
```
LoadError: No such file to load -- sentry/send_event_job.rb
/Users/kevindew/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/activesupport-6.1.4/lib/active_support/dependencies.rb:332:in `require' …
```
> Use current Rails version for configuration defaults

- CHANGELOG.md
- app/views/govuk_publishing_components/components/_title.html.erb
- app/views/govuk_publishing_components/components/docs/title.yml
- spec/components/title_spec.rb
This removes the ability to add a link to the contextual text that sometimes appears above a title. 
In many cases where this was used there were already breadcrumbs serving the same purpose and meaning duplicate links. Additionally, the link was not obvious unless hovered meaning there was no realistic was for most users to know it was there. 
THIS IS A BREAKING CHANGE. If an app updates to this version with attempts to link the context then the context hash will be exposed:
The following PRs cover removing all the examples I'm aware of and this version of the components should not be used until they are merged:
https://github.com/alphagov/government-frontend/pull/2117
https://github.com/alphagov/whitehall/pull/6120
https://github.com/alphagov/collections/pull/2463
> Remove ability to link context text on titles

- CHANGELOG.md
- app/views/govuk_publishing_components/components/_radio.html.erb
- app/views/govuk_publishing_components/components/docs/radio.yml
- spec/components/radio_spec.rb
This removes all mentions of the `is_page_heading` option from the radio component.
Recently, the ability to pass a custom heading level to the radio component was introduced: https://github.com/alphagov/govuk_publishing_components/pull/1951 
Since specifying a custom heading level is now an option, the `is_page_heading` parameter became redundant. This parameter simply dictates that the radio component legend heading should be a `h1` of size `xl` by default.
It is possible to achieve the same result using `heading_level` and/or `heading_size` instead.
Whenever we need this component to have a h1 in the future, we can simply use the `heading_level` option (in combination with `heading_size`, if necessary).
This issue is recorded here …
> Remove `is_page_heading` parameter from radio component

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/components/intervention.js
- app/assets/stylesheets/govuk_publishing_components/components/_intervention.scss
- app/views/govuk_publishing_components/components/_intervention.html.erb
- config/locales/en.yml
- spec/components/intervention_spec.rb
- spec/javascripts/components/intervention-spec.js
* Intervention component: adjust the design and add GA code
We need to track when the user sees the component and what action they take upon seeing it
> Intervention: add tracking code and design tweaks

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
* **BREAKING:** Remove ability to link contextual text on titles ([PR #2192](https://github.com/alphagov/govuk_publishing_components/pull/2192))
* Delete empty print stylesheets ([PR #2225](https://github.com/alphagov/govuk_publishing_components/pull/2225))
* **BREAKING:** Remove `is_page_heading` parameter from radio component ([PR #2061](https://github.com/alphagov/govuk_publishing_components/pull/2061))
* Intervention: add tracking code and design tweaks ([PR #2224](https://github.com/alphagov/govuk_publishing_components/pull/2224))
* **BREAKING:** Remove deprecated `em()` Sass mixin ([PR #2220](https://github.com/alphagov/govuk_publishing_components/pull/2220))
You must make the following changes when you migrate to this release:
- Replace `em()` calls with `govuk-em()`
* …
> Version 25.0.0

- CHANGELOG.md
- app/views/govuk_publishing_components/components/_fieldset.html.erb
- app/views/govuk_publishing_components/components/_input.html.erb
- app/views/govuk_publishing_components/components/_label.html.erb
- app/views/govuk_publishing_components/components/_radio.html.erb
- app/views/govuk_publishing_components/components/_search.html.erb
- app/views/govuk_publishing_components/components/_select.html.erb
- app/views/govuk_publishing_components/components/_summary_list.html.erb
- app/views/govuk_publishing_components/components/docs/search.yml
- lib/govuk_publishing_components/presenters/shared_helper.rb
- spec/components/search_spec.rb
The search component doesn't allow for the text size of the label to be adjusted. This allows the `label_size` parameter that will alter the label tet size, as long as it's set to `xl`, `l`, `m`, or `s`.
This doesn't override the current default - if no label size is given, then this
component's label will be the same as before.
Setting `label_size` forces `inline_label` to be `false`.
The explore header needed a differently sized label.
There was a requirement to set the text size of the label - but without overriding the current default.
No changes to existing versions.
`xl` version:
`l` version:
`m` version:
`s` version:
> Allow label sizes in search component

- app/assets/javascripts/govuk_publishing_components/modules.js
- should do exactly the same thing, but be slightly easier to read and understand
Discussions around this subject recently revealed confusion between the two `if` statements in this code, specifically what the difference between them is - it's hard to spot the `!` in the middle of the rest of the statements. Restructuring it like this hopefully makes it clearer what the code is doing.
None.
> Simplify the modules code

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/_notice.scss
- app/views/govuk_publishing_components/components/_notice.html.erb
- app/views/govuk_publishing_components/components/docs/notice.yml
- config/locales/en.yml
- spec/components/notice_spec.rb
Between the [notice](https://components.publishing.service.gov.uk/component-guide/notice), [success](https://components.publishing.service.gov.uk/component-guide/success_alert) and [error alert](https://components.publishing.service.gov.uk/component-guide/error_alert) components, we've got a mix of styles and approaches. 
Ideally these would all be one component, with modifiers applied to generate variations. 
This is a step towards that goal.
The GOV.UK version of the notification component currently deviates from the Design System version. 
This adopts Design System classes and styles for this component, only keeping few CSS overrides that are necessary for our usage of this component. 
Instead of applying the "Important" banner style across the board, it has been suggested by the GOVUK …
> Update notice component to better match DS notification banner

- CHANGELOG.md
- app/views/govuk_publishing_components/components/_title.html.erb
- app/views/govuk_publishing_components/components/docs/title.yml
- spec/components/title_spec.rb
Move the caption inside of the h1.
Currently, the context is missed when page titles are read by screen readers. This way when users navigate through headings with a screenreader will hear the title with context announced.
https://trello.com/c/gPFqiwZa/799-update-headings-for-smart-answers-outcome
> Add option to nest context within the h1 for title component

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
* Convert a tags to buttons on load in header-navigation js ([PR #2235](https://github.com/alphagov/govuk_publishing_components/pull/2235))
* Allow label sizes for search component label ([PR #2236](https://github.com/alphagov/govuk_publishing_components/pull/2236)) MINOR
* Update notice component to better match DS notification banner ([PR #2214](https://github.com/alphagov/govuk_publishing_components/pull/2214))
* Add option to nest context within the h1 for title component ([PR #2226](https://github.com/alphagov/govuk_publishing_components/pull/2226))
> Version 25.1.0

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/govspeak/_charts.scss
This fixes issue #2106 which highlights that govspeak charts buttons
(which function as a toggle between chart and table views) are missing a
relevant hover style.
Update the background and text colours on hover to match the hover state
of other similar button styles (for instance, the [print button](https://components.publishing.service.gov.uk/component-guide/print_link)).
https://user-images.githubusercontent.com/7116819/127658882-8017cf71-2a09-4b70-a35c-ab56d82cce4a.mov
https://user-images.githubusercontent.com/7116819/127658875-f1d834ad-4e0a-4c75-a667-47da43dc3bfd.mov
-----
Closes #2106 
-----
**NOTE:** several components contain a similar button style to this one, and they all have separate CSS to achieve more or less the same thing (a white background, grey border button with blue …
> Add hover style for govspeak mc button

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/lib/govspeak/youtube-link-enhancement.js
`YoutubeLinkEnhancement` checks if the user has accepted all cookies, and progressively enhances a youtube link into an embedded video if that condition is met.
This check occurs when the module is initialised on page load.
Therefore, if a user who has not yet accepted cookies lands on a page containing a YouTube video, then clicks "Accept cookies" in the cookie banner in order to watch said video, they would have to refresh the page in order for the video to load.
This is not ideal and can lead to confusion or frustration.
This introduces an additional check for the case in which cookies have not been accepted on initialisation, which listens for the `'cookie-consent'` event ([first introduced not too long ago](https://github.com/alphagov/govuk_publishing_components/commit/777a381d2ccb67f …
> Load Youtube video instantly when cookies are accepted

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/components/layout-super-navigation-header.js
- app/views/govuk_publishing_components/components/_layout_super_navigation_header.html.erb
- spec/javascripts/components/layout-super-navigation-header-spec.js
Add new analytics tags for the super navigation header.
So that we can track user engagement with the new navigation header during the upcoming A/B test.
[Card](https://trello.com/c/tzaEtEhO/320-implement-analytics-tracking-on-the-new-menu-bar-header)
> Add analytics tags to super navigation header

- CHANGELOG.md
- app/views/govuk_publishing_components/components/_layout_super_navigation_header.html.erb
Add tracking to links within sections on the super navigation header
To track user interaction for an upcoming A/B test by the govuk explore team.
[Card](https://trello.com/c/tzaEtEhO/320-implement-analytics-tracking-on-the-new-menu-bar-header)
> Add link tracking to super navigation header

- CHANGELOG.md
- app/views/govuk_publishing_components/components/_layout_super_navigation_header.html.erb
Fix a couple of typos and incorrect tracking attributes in the super navigation tracking.
Missed during prior review.
> Fix typos in super navigation link tracking

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/_layout-super-navigation-header.scss
- Adds more specific selectors to override the generic `a:link` styles coming from `govuk-layout`.
- Swaps `rem` for `px` as the base font size for the `core_layout` template is different to the base font size in the `gem_layout` template.
Frontend applications that use the `core_layout` template were seeing blue links and tiny icons in the header - this fixes those problems so that the different templates can use the super navigation header and have it look consistent.
Before:
After:
> Update super navigation styles to avoid `govuk-layout` clashes

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
* Add link tracking to super navigation header ([PR #2249](https://github.com/alphagov/govuk_publishing_components/pull/2249))
* Fix typos in super navigation link tracking ([PR #2251](https://github.com/alphagov/govuk_publishing_components/pull/2251))
* Update super navigation styles to avoid `govuk-layout` clashes ([PR #2250](https://github.com/alphagov/govuk_publishing_components/pull/2250))
> Bump gem version to 25.2.1

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
* Fix typo in tracking module on super navigation header ([PR #2253](https://github.com/alphagov/govuk_publishing_components/pull/2253))
> Bump gem version to 25.2.2

- CHANGELOG.md
- app/views/govuk_publishing_components/components/_layout_super_navigation_header.html.erb
Add tracking to section heading links when there aren't any section children, thus the link is displayed by default, and fix a typo.
To make tracking work for govuk explore.
> Fix final issues with tracking on super nav header

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
* Fix final issues with tracking on super nav header ([PR #2256](https://github.com/alphagov/govuk_publishing_components/pull/2256))
> Bump gem version to 25.2.3

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/components/cookie-banner.js
- app/assets/stylesheets/component_guide/application.scss
- app/assets/stylesheets/govuk_publishing_components/components/_cookie-banner.scss
- app/views/govuk_publishing_components/components/_cookie_banner.html.erb
- spec/javascripts/components/cookie-banner-spec.js
It seems that IE10 does not support the `hidden` attribute. 
This is causing some issues with the cookie banner component: when the confirmation banner is visible (upon rejecting/accepting cookies), the cookie choice panel should disappear, which does not happen in <IE10.
This attempts to fix the issue by using CSS to hide elements accordingly when the `hidden` attribute is present (as opposed to toggling `display` with JS).
Additionally, switch from using property dot notation to set hidden to true/false, to using `setAttribute` because although the former worked in other major browsers, IE10 seemed to ignore it (perhaps due to the distinction between [properties](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/hidden) and …
> Fix cookie banner issue (IE10)

- app/assets/javascripts/govuk_publishing_components/lib/header-navigation.js
- app/views/govuk_publishing_components/components/layout_header/_navigation_items.html.erb
- app/views/govuk_publishing_components/components/layout_header/_search.html.erb
Updates the event being fired by the search toggle from `menuOpened` and `menuClosed` to `searchOpened` and `searchClosed`.
It'd be nice to have a more elegant way of doing this, but this fixes a problem that needs to be fixed quickly.
This will differentiate the events being fired by the menu and the search toggles to allow for more accurate analysis of users interactions.
None.
> Update search toggle tracking

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/_layout-for-public.scss
- app/views/govuk_publishing_components/components/_layout_for_public.html.erb
- app/views/govuk_publishing_components/components/docs/layout_for_public.yml
- app/views/govuk_publishing_components/components/layout_for_public/_account-feedback-footer.html.erb
- app/views/govuk_publishing_components/components/layout_for_public/_account-layout.html.erb
- app/views/govuk_publishing_components/components/layout_for_public/_account-navigation.html.erb
- config/locales/en.yml
- lib/govuk_publishing_components/presenters/public_layout_helper.rb
- spec/component_guide/component_index_spec.rb
- spec/components/layout_for_public_spec.rb
Update `layout_for_public` component to support GOVUK Account components.
Some account-related components, contents, and CSS are repeated across different apps on GOVUK.
The first instance of this was when we [relocated the account homepage from the govuk-account-manager-app to the frontend app](https://github.com/alphagov/frontend/pull/2841), which meant that some of the page furniture and content was duplicated between those apps.
More recently, the accounts team are working towards the goal of single page notifications which will enable users who have linked their email notifications address and their GOVUK account email address to manage their email subscriptions through their account. 
Part of this work is making the email management pages (rendered by `email-alert-frontend`) look …
> Extend layout for public with account components

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/analytics/track-click.js
- spec/javascripts/govuk_publishing_components/analytics/track-click.spec.js
Modify `GemTrackClick` so that if no `data-track-label` attribute is provided, the text of the link clicked will be used.
- this will allow tracking to be added to a wrapping element containing links managed outside of an editable template
We want to add tracking to links within an element where the content is managed outside of the template (e.g. a YML file) and the content is subject to change, without having to keep ensuring the links have the right data attributes. This allows us to add the module, action and event attributes to the parent, and the script will automatically use the text of the clicked link as the label.
None.
Trello card: https://trello.com/c/Q6kr2nFK/551-add-ga-tracking-codes-to-fcdo-call-out-box-of-covid-info
> Extend track click script

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
Includes:
* Extend track click script (https://github.com/alphagov/govuk_publishing_components/pull/2263)
* Fix cookie banner issue (IE10) (https://github.com/alphagov/govuk_publishing_components/pull/2231)
* Extend layout for public with account components (https://github.com/alphagov/govuk_publishing_components/pull/2255)
* Update search toggle tracking (https://github.com/alphagov/govuk_publishing_components/pull/2262)
> Release v25.3.0

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/analytics/track-click.js
- spec/javascripts/govuk_publishing_components/analytics/track-click.spec.js
Modify the track click script so that link tracking without a label explicitly given should use the link href, not the text of the link.
The logic of the code works as follows:
- if `track-links-only` is specified, only clicks on links are tracked
- link href is acquired and stored, if a label is specified, that is used, otherwise it falls back to the href
If normal tracking is happening:
- link href is acquired and stored (but might not return anything as it might not be a link)
- if a label is specified, that is used, otherwise it falls back to the href, which if it doesn't exist (if it's not a link) no label is included in the GA event
We want to track links in an element by only putting tracking on the element, not the individual links (as they are content controlled and subject to …
> Fix track click link tracking

- CHANGELOG.md
- lib/govuk_publishing_components/presenters/public_layout_helper.rb
Add language tag for Welsh link in public layout template -
```
<li class="govuk-footer__inline-list-item">
<a class="govuk-footer__link" lang="cy" href="/cymraeg">Rhestr o Wasanaethau Cymraeg</a>
</li>
```
Fail of WCAG SC 3.1.2
> Add language tag for Welsh link in public layout template

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/components/cookie-banner.js
- app/assets/stylesheets/component_guide/application.scss
- app/assets/stylesheets/govuk_publishing_components/components/_cookie-banner.scss
- app/views/govuk_publishing_components/components/_cookie_banner.html.erb
- spec/javascripts/components/cookie-banner-spec.js
This reverts commit b17d981710413c39afe077d8e7cc87ee00a30d65.
> Revert "Fix cookie banner issue (IE10)"

- CHANGELOG.md
- app/views/govuk_publishing_components/components/docs/image_card.yml
- lib/govuk_publishing_components/presenters/image_card_helper.rb
- spec/components/image_card_spec.rb
Adding lazy loading option to [image card](https://components.publishing.service.gov.uk/component-guide/image_card) providing a default to `auto`
As part of [this PR](https://github.com/alphagov/whitehall/pull/6236) realised that `loading="lazy"` was an attribute that exists on the image. [This had a measurable improvement on performance](https://github.com/alphagov/whitehall/pull/4979). 
In order to maintain use of this attribute _and_ use the [image card componen](https://components.publishing.service.gov.uk/component-guide/image_card)t adding the option to the gem
No visual changes, however visual representation of code update below:
---
Ref: https://web.dev/browser-level-image-lazy-loading/
[`auto`] has been added as the "default lazy-loading behaviour of the browser, which is the …
> Add lazy loading

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
This release includes:
* Add lazy loading to image card ([#2270](https://github.com/alphagov/govuk_publishing_components/pull/2270))
* GOVUK.Modules.start can accept DOM elements ([#2260](https://github.com/alphagov/govuk_publishing_components/pull/2260))
> Release v25.4.0

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/_step-by-step-nav-header.scss
Applying a custom `line-height` on a `<span>` doesn't have any effect, as it's an inline element. We are setting the property on the parent `<h2>` element instead, as it's a block element.
This fixes a reported issue on mobile where the browser default `<h2>` `line-height` is inherited by the `<span>` element.
<table>
</td></tr>
</td></tr>
</table>
> Fix `line-height` on step-by-step nav header

- CHANGELOG.md
- app/views/govuk_publishing_components/components/_layout_for_public.html.erb
- spec/components/layout_for_public_spec.rb
Add a `draft_watermark` option to the `layout_for_public` component.
[A `draft` class](https://github.com/alphagov/static/blob/main/app/views/root/_base.html.erb#L8) is used to apply a watermark when previewing documents in publishing application. [A smokey test is currently failing](https://deploy.integration.publishing.service.gov.uk/job/Smokey/32866/console) as this class is missing in applications using the new `gem_layout`.
The class, styling, and the associated asset should all be brought in line with our current conventions, but this will require a breaking change as we have [many instances](https://github.com/search?q=org%3Aalphagov+body.draft&type=code) where this `.draft` class is checked to exists.
No visual changes at the component level.
[Trello …
> Enable draft on public layout

- CHANGELOG.md
- app/views/govuk_publishing_components/components/_image_card.html.erb
Adding underline to links within [image card](https://components.publishing.service.gov.uk/component-guide/image_card) headings
As the image card heading, in this context, is linked this restores the underline as this offers more affordance this is a link than just colour alone meeting [WCAG 1.4.1](https://www.w3.org/TR/WCAG20-TECHS/F73.html)
> Link underlines or some other non-color visual distinction are required (when the links are discernible to those with color vision).
[Prompted from work on this PR](https://github.com/alphagov/whitehall/pull/6243) it was noticeable that in situ that links are absent from these linked headlines on the image card.
> Restore underline on image card header link

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
* Fix `line-height` on step-by-step nav header ([PR #2273](https://github.com/alphagov/govuk_publishing_components/pull/2273))
* Enable draft on public layout ([PR #2274](https://github.com/alphagov/govuk_publishing_components/pull/2274))
* Bump `govuk-frontend` from 3.12.0 to 3.13.0 ([PR #2164](https://github.com/alphagov/govuk_publishing_components/pull/2164))
* Restore underline on image card header link ([PR #2277](https://github.com/alphagov/govuk_publishing_components/pull/2277))
> Release 25.5.0

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/components/layout-super-navigation-header.js
Removes the window resize listener inside the `updateStates` function, which itself was used with a window resize or matchMedia listener.
When moving from mobile to desktop view, and resizing the window to exactly 769 pixels wide the layout was broken. This was because the listener to change the layouts was added at this breakpoint, but the function wouldn't be fired until the _next_ resize event one pixel later.
Since this was a `resize` listener being fired by another resize or matchMedia listener it could be removed and replaced with firing the function.
Example of the visual glitch:
Before at 769 pixels wide:
After at 769 pixels wide:
> Fix navigation header layout error that occurs when resizing browser window

- app/assets/stylesheets/govuk_publishing_components/components/_layout-super-navigation-header.scss
Updates the borders and hover states of the navigation header buttons and links.
The hover states and borders of the navigation header links and toggle buttons were inconsistent.
| - | - |
| ![image](https://user-images.githubusercontent.com/1732331/130478912-c32033bb-46f4-491c-aa71-9d07406049ea.png) | ![image](https://user-images.githubusercontent.com/1732331/130479137-560cbdb8-5aac-4145-a790-1ced481937f9.png) |
Before:
After:
> Fix inconsistent navigation header hover states

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/analytics/track-click.js
- docs/analytics.md
- docs/track-click.md
- spec/javascripts/govuk_publishing_components/analytics/track-click.spec.js
- allows us to specify an element class within which link clicks will be tracked
- caters for the situation where we want to track specific links within a govspeak block and can't get to the source, except from a high level parent element
This PR also adds some documentation for this script, since it's been having some new features lately.
We want to track link clicks in the second grey box on pages like https://www.gov.uk/foreign-travel-advice/spain (underneath 'Summary') but that box and all the text below it is managed through a publishing interface, so we can only apply tracking stuff to a parent element. This allows us to provide the classname of the grey box so that only links clicked in that box are tracked.
None.
Trello card: …
> Add element tracking to track click

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/_layout-super-navigation-header.scss
Removed the search toggle button hover state when the button was focussed.
The hover state differed between the navigation toggle buttons and the search toggle buttons - this is now consistent in that there is now no visual change when a focussed element is hovered.
Before - search toggle focussed and hovered:
After - search toggle focussed and hovered:
> Fix navigation header search toggle focus hover states

- .github/dependabot.yml
- CHANGELOG.md
- Gemfile.lock
- app/views/govuk_publishing_components/components/layout_for_public/_account-feedback-footer.html.erb
- app/views/govuk_publishing_components/components/layout_for_public/_account-layout.html.erb
- app/views/govuk_publishing_components/components/layout_for_public/_account-navigation.html.erb
- govuk_publishing_components.gemspec
- lib/govuk_publishing_components.rb
Change the account parts of the public layout component to use [the `GovukPersonalisation::Urls` module](https://www.rubydoc.info/gems/govuk_personalisation/0.7.0/GovukPersonalisation/Urls), which we have introduced as a consistent way to link to account-related pages across apps.
This is a breaking change, because it introduces a dependency on [the govuk_personalisation gem](https://rubygems.org/gems/govuk_personalisation), which has a dependency on `rails ~> 6`, whereas govuk_publishing_components currently has a dependency on `rails >= 5.0.0.1`, so any Rails 5 users will need to upgrade to Rails 6.  This shouldn't be a problem for GOV.UK, as we are already using Rails 6 for everything.
We currently link to account-related URLs in a few apps, and have adopted different practices in …
> Add a dependency on govuk_personalisation, and use it to generate account URLs in the account layout

- CHANGELOG.md
The last link under version **24.11.0** doesn't look right: https://github.com/alphagov/govuk_publishing_components/blob/master/CHANGELOG.md#24110
> Fix link formatting in CHANGELOG.md

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/_document-list.scss
- app/views/govuk_publishing_components/components/_document_list.html.erb
Remove class composition in favour of attribute declaration on `gem-c-document-list__children` elements.
Class composition (in this case `gem-c-document-list__children`  with `govuk-list`) means that when we have the same attribute (let's say `margin-top`) the order of precedence is dictated by where these class definitions are presented in the compiled CSS files – known as document order. Document order makes styling flakey as when swapping a component in or out or changing the order of SCSS imports we may end up with different styling. This happened in https://github.com/alphagov/finder-frontend/pull/2616 when switching to the new `gem_layout` where the document-list SCSS import is followed by [error-summary](https://github.com/alphagov/govuk_publishing_components/blob/master/app/assets/ …
> Fix document list children

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/govspeak/_images.scss
- app/views/govuk_publishing_components/components/docs/govspeak.yml
Reset margins for govspeak images
govspeak images use a `<figure>` element without resetting the margin resulting in a shifted image
<table>
</td></tr>
</table>
> Reset margins for govspeak images

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/_layout-for-public.scss
Fix global banner wrapper in public layout
The `global-banner-wrapper` element is rendered whether or not there is an active global banner as it's a slot for other elements such as the survey banner. When there is no content in this container, because of the negative margin-top it pulls the element below (often the back link or the breadcrumbs) higher up than it should be. By setting a `min-height` we make sure no layout alteration happen in this scenario, while it scales up when content is presented within the container.
<table>
</td></tr>
</table>
> Fix global banner wrapper in public layout

- CHANGELOG.md
- app/views/govuk_publishing_components/components/_image_card.html.erb
- app/views/govuk_publishing_components/components/docs/image_card.yml
- lib/govuk_publishing_components/presenters/image_card_helper.rb
- spec/components/image_card_spec.rb
Resolves #2295 
An additional - no link option was added to `extra_links` within [image card](https://components.publishing.service.gov.uk/component-guide/image_card) making it confusing in terms of the naming, consider `extra_links_no_links` this has been updated to `list` so it makes more sense - `extra_list_no_links`
None
Breaking change - impacting `collections` - [linked PR](https://github.com/alphagov/collections/pull/2524)
> Rename "extra links" within image_card

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
* **BREAKING:** Rename extra_links to extra_details (image card) ([PR #2300](https://github.com/alphagov/govuk_publishing_components/pull/2300))
* Create devolved nations component ([PR #2280](https://github.com/alphagov/govuk_publishing_components/pull/2280))
* Fix document list children ([PR #2296](https://github.com/alphagov/govuk_publishing_components/pull/2296))
* Reset margins for govspeak images ([PR #2297](https://github.com/alphagov/govuk_publishing_components/pull/2297))
* Fix global banner wrapper in public layout ([PR #2294](https://github.com/alphagov/govuk_publishing_components/pull/2294))
> Release 27.0.0

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/_all_components.scss
- app/assets/stylesheets/govuk_publishing_components/components/_big-number.scss
- app/views/govuk_publishing_components/components/_big_number.html.erb
- app/views/govuk_publishing_components/components/docs/big_number.yml
- spec/components/big_number_spec.rb
Adds the big number component to the component library
We have a couple of fragmented instances of this pattern across govuk which meets our criteria for componentisation.
You can read more on the reasoning, along with a spec for the API and the markup in the comments, here: https://github.com/alphagov/govuk_publishing_components/issues/2221
| Link | Before | After |
| https://www.gov.uk/ | ![Screenshot 2021-08-20 at 16 23 15](https://user-images.githubusercontent.com/64783893/130258213-36fd46b5-a214-46d4-b3d0-b3188866d95d.png) | ![Screenshot 2021-08-20 at 16 23 26](https://user-images.githubusercontent.com/64783893/130258234-5ed38a24-dbf8-407a-80b9-4d04588c2b24.png) |
> Add big number component

- CHANGELOG.md
- app/views/govuk_publishing_components/components/_layout_for_public.html.erb
- spec/components/layout_for_public_spec.rb
Add missing [`govuk-template` class](https://design-system.service.gov.uk/styles/page-template/) to public layout. 
This class set the overall page background colour to the same colour as used by the footer to give the illusion of a long footer, prevents automatic text sizing, as we already cater for small devices and would like the browser to stay on 100% text zoom by default and Force the scrollbar to always display in IE, to prevent horizontal page jumps as content height changes.
<table>
</td></tr>
</table>
> Add missing `govuk-template` class to public layout

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/_layout-super-navigation-header.scss
Fixes the sticky hover state seen on touchscreen devices by unsetting hover states when a touchscreen device is being used.
Card: https://trello.com/c/fZ9bs2G0
A stick hover state is seen on some touchscreen devices - when a button is selected, the hover state is also triggered. This caused the search button in the navigation header to look hovered when the focus state moved on. Fixing this makes the interface easier to understand, as the states of the buttons are no longer muddled.
> Fix sticky hover on search button in navigation header

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/_layout-super-navigation-header.scss
- app/views/govuk_publishing_components/components/_layout_super_navigation_header.html.erb
- config/locales/en.yml
Changes the layout of list of links in the navigation to use CSS grid layout so that it can be alphabetically ordered vertically, rather than horizontally.
Card: https://trello.com/c/BLSqfgij
Lists are easier to scan when each column is alphabetically sorted vertically. This is possible to do automagically with CSS columns, but Chrome doesn't like CSS columns when links are using `text-decoration-thickness` ([Issue on GOV.UK Frontend][1]; [Issue on Chromium][2]) - so another solution was needed.
[CSS Grid Layout has support going back to IE 10][3] and allows for vertical columns as long as the number of items in the columns are known - so when the navigation is updated the CSS controlling the grid needs to be updated.
| - | - |
| …
> Reorder the navigation lists vertically

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
Includes:
* Add big number component ([PR #2278](https://github.com/alphagov/govuk_publishing_components/pull/2278))
* Add missing `govuk-template` class to public layout ([PR #2307](https://github.com/alphagov/govuk_publishing_components/pull/2307))
* Fix sticky hover on search button in navigation header([PR #2304](https://github.com/alphagov/govuk_publishing_components/pull/2304))
* Reorder the navigation lists vertically ([PR #2303](https://github.com/alphagov/govuk_publishing_components/pull/2303))
> Release v27.1.0

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
* Add new scroll tracking ([PR #2305](https://github.com/alphagov/govuk_publishing_components/pull/2305))
* Update crown fallback image ([PR #2313](https://github.com/alphagov/govuk_publishing_components/pull/2313)) PATCH
* Remove heading and use strong in step nav header ([PR #2311](https://github.com/alphagov/govuk_publishing_components/pull/2311))
> Release 27.2.0

- CHANGELOG.md
- app/views/govuk_publishing_components/components/_layout_for_public.html.erb
- app/views/govuk_publishing_components/components/_layout_super_navigation_header.html.erb
- app/views/govuk_publishing_components/components/docs/layout_super_navigation_header.yml
- spec/components/layout_super_navigation_header_spec.rb
Adds the `logo_link` parameter to the navigation header.
So the navigation header can have a custom link for the crown logo, which make the behaviour of the other header and will stop it from breaking the smoke tests.
None.
> Allow custom logo link in navigation header

- CHANGELOG.md
- app/views/govuk_publishing_components/components/_big_number.html.erb
- app/views/govuk_publishing_components/components/docs/big_number.yml
- spec/components/big_number_spec.rb
Amends the data attributes functionality on the big number component to allow for attr's to be applied when no link is present. Currently, data attributes are only applied to the `a` tag generated if an `href` attribute is passed. This applies attributes to the `span` containing the number if they are present.
Part of getting the big numbers onto [the departments page](https://www.gov.uk/government/organisations). This page has a live search which updates the current implementation of the big numbers. Currently, the big number component can't work with this functionality in a robust manner.
> Allow data attributes to be applied to big numbers when no link is present

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
Includes:
* Allow custom logo link in navigation header ([PR #2320](https://github.com/alphagov/govuk_publishing_components/pull/2320)) MINOR
* Allow data attributes to be applied to big numbers when no link is present ([PR #2321](https://github.com/alphagov/govuk_publishing_components/pull/2321))
> Release v27.3.0

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
* Add blue arrow option to action link ([PR #2330](https://github.com/alphagov/govuk_publishing_components/pull/2330))
> Version 27.4.0

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/analytics/scroll-tracker.js
Remove scroll tracking on some pages. Scroll tracking is no longer required on these pages, specifically:
- information-for-the-public is now redirected
- coronavirus-press-conference is withdrawn content
- green-list-rules is also redirected
This is part of the work to migrate from the old scroll tracker to the new one.
None.
Trello card: https://trello.com/c/sdugtMbX/643-migrate-to-new-scroll-tracker
> Remove scroll tracking on pages

- CHANGELOG.md
- app/views/govuk_publishing_components/components/layout_for_public/_account-layout.html.erb
- config/locales/en.yml
Changes `layout_for_public` account variation to use the correct link to DI's contact form for feedback
So that GOVUK account pages are in line with DI account pages
----
https://trello.com/c/vIjbnGSj/1087-account-pages-tidy-up-for-launch
> Amend account layout phase banner link

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
* Amend account layout phase banner link ([PR #2397](https://github.com/alphagov/govuk_publishing_components/pull/2397))
> Bump gem to 27.10.1

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/analytics/explicit-cross-domain-links.js
- spec/javascripts/govuk_publishing_components/analytics/explicit-cross-domain-links.spec.js
The `cookie_consent` param should also have a value of 'not-engaged' when `cookies_preferences_set` is `null`.  
The reason for this change can be observed by doing the following:
1. clear your browser cookies for gov.uk –  when you refresh the page the cookie banner should appear
2. resist the immediate urge to reject (or accept) cookies 😄
3. visit https://www.gov.uk/brexit and check the `href` of the sign in link – the query string on the link is `cookie_consent=reject`, when it should probably be `cookie_consent=not-engaged`
This adjusts the explicit cross domain links script to always append `cookie_consent=not-engaged` unless `cookies_preferences_set` is explicitly set to 'true'.
> Adjust cookie_consent parameter conditions

- CHANGELOG.md
- app/views/govuk_publishing_components/components/_admin_analytics.html.erb
- app/views/govuk_publishing_components/components/_government_navigation.html.erb
- app/views/govuk_publishing_components/components/_highlight_boxes.html.erb
- app/views/govuk_publishing_components/components/_taxonomy_list.html.erb
Raise deprecation warnings on unused components that we plan to retire in 28.0.0
I've been pondering whether or not to raise these using `ActiveSupport`, but thinking that we use `govuk_publishing_components` outside the Rails realm (e.g. developer docs using Middleman) I'm getting skeptical about it. 
Happy to hear suggestions for a more effective approach.
We plan to retire a few components that are not being used and we don't plan to use them in the near future.
> Raise deprecation warnings on unused components

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
Includes:
* Raise deprecation warnings on unused components: `admin_analytics`, `government_navigation`, `highlight_boxes` and `taxonomy_list` ([PR #2362](https://github.com/alphagov/govuk_publishing_components/pull/2362))
* Adjust cookie_consent parameter conditions ([PR #2399](https://github.com/alphagov/govuk_publishing_components/pull/2399))
> Bump gem to 27.10.2

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
Release  v27.10.3, which includes:
* Update navigation header focus states (take two) (#2401)
> Release v27.10.3

- Gemfile.lock
- Rakefile
- govuk_publishing_components.gemspec
- spec/dummy/Rakefile
This PR includes Rails Translation Manager and sets the actual Gem root when called by RTM.
Supersedes https://github.com/alphagov/rails_translation_manager/pull/17.
More info in the commits ->
---
Trello:
https://trello.com/c/k4rrt3UG/2686-update-csv-import-rails-translation-manager-3
> Include Rails Translation Manager and set correct root

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/_layout-super-navigation-header.scss
Adds underlines to links on the [super navigation](https://components.publishing.service.gov.uk/component-guide/layout_super_navigation_header) no-js mobile view.
So that no-js mobile users are able to identify the headings as links.
[Card](https://trello.com/c/D0tQKcxN/574-underlines-on-no-js-version-of-menu)
Below for js disabled view. No visual changes for js enabled view.
| --- | --- |
| ![Screenshot 2021-11-02 at 12 52 15](https://user-images.githubusercontent.com/64783893/139850773-af356c00-90ec-4584-9b35-c37ac7a393fd.png) | ![Screenshot 2021-11-02 at 12 51 05](https://user-images.githubusercontent.com/64783893/139850793-861391d9-7567-4ebf-9c9b-2623aab229dd.png) |
> Add underlines to mobile menu links on super navigation no-js view

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/_layout-super-navigation-header.scss
Add black border to the bottom of the [super navigation](https://components.publishing.service.gov.uk/component-guide/layout_super_navigation_header) search button. This change is only applied on desktop when the search menu is closed.
So that it doesn't blend into the blue bar above the covid banner.
[Card](https://trello.com/c/tGotQ6ab/569-add-separator-to-search-icon)
| --- | --- |
| ![Screenshot 2021-11-02 at 17 06 27](https://user-images.githubusercontent.com/64783893/139912962-ce9be04c-92f9-4a8a-bcb5-eee787694be4.png) | ![Screenshot 2021-11-02 at 17 06 11](https://user-images.githubusercontent.com/64783893/139913001-93412a97-435e-4011-929a-94523f5703d6.png) |
> Add black border to the bottom of the closed header search button

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/_layout-super-navigation-header.scss
Rem units are not meant to be used in compatibility mode (in conjunction with legacy dependencies such as `govuk_template`) as the `font-size` for the root element is not controlled. Hence we wrap these declarations and only apply them when rem units are set to be used by `govuk-frontend`.
To fix the font size when the super navigation header is used in compatibility mode (e.g. https://www.gov.uk/search).
<table>
</td></tr>
</table>
> Fix font size on super navigation header

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
Includes:
* Add underlines to mobile menu links on super navigation no-js view (PR #2404)
* Add black border to the bottom of the closed header search button (PR #2405)
* Fix font size on super navigation header (PR #2407)
> Release v27.10.4

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/analytics/explicit-cross-domain-links.js
- app/assets/javascripts/govuk_publishing_components/components/cookie-banner.js
- spec/javascripts/components/cookie-banner-spec.js
On a [Zendesk ticket](https://govuk.zendesk.com/agent/tickets/4757358) we received on the Accounts team, a user reports a bug with the cookie banner JavaScript on GOV.UK Accounts which can cause the rest of the JavaScript on the page to fail. From the ticket:
> GOVUK.getConsentCookie() tries to get a cookie called 'cookies_policy'. I looked at the cookies for the GOV.UK Account domain and found that I only had a 'cookie_preferences_set' cookie, but not a 'cookie_policy' cookie, which is why cookieConsent was null.
> I tried viewing the page in an Incognito window, and found the cause of the problem. 'cookie_policy' is set when I first load the page, but 'cookie_preferences_set' is only set when I click a button in the cookie consent banner. Both cookies are set to expire after a year. …
> Prevent `cookies_policy` cookie related issues 

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
Corrects the changelog as #2406 was accidentally included under `27.10.4`
Includes
* Prevent `cookies_policy` cookie related issues ([PR #2406](https://github.com/alphagov/govuk_publishing_components/pull/2406))
> Bump gem to 27.10.5 and correct CHANGELOG

- docs/component_principles.md
Add some information about component translation to our documentation.
We don't have any, as referenced in https://github.com/alphagov/govuk_publishing_components/issues/18.
Fixes https://github.com/alphagov/govuk_publishing_components/issues/18
None.
> Add some documentation for component translation

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/_layout-super-navigation-header.scss
- app/views/govuk_publishing_components/components/_layout_super_navigation_header.html.erb
Update the design of the menu button, seen in mobile view on the [super navigation header](https://components.publishing.service.gov.uk/component-guide/layout_super_navigation_header) ([public page for in situ example](https://components.publishing.service.gov.uk/public)), specifically:
- Replaces the top to bottom borders around the menu button with "pipes"
- Revises the behaviour so that on open, the menu button no longer displays an "x" but instead cotinues to show "menu" with a reversed chevron.
Part of the explore team's iteration of the new navigation header. The altered appearance on open is to ensure that the button is consistent in its behaviour with other toggle buttons in the same component.
[Card](https://trello.com/c/nCcmmUuA/562-update-mobile-menu-button)
[Test …
> Update the design of the mobile menu button on the super navigation

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/_layout-super-navigation-header.scss
- app/views/govuk_publishing_components/components/search/_search_icon.html.erb
Updates the search icon SVG positioning and the bottom border colour (desktop only) of the search button on the [super navigation header](https://components.publishing.service.gov.uk/component-guide/layout_super_navigation_header).
- So that magnifying glass element of the search icon is more centred
- To iterate on https://github.com/alphagov/govuk_publishing_components/pull/2405, reducing the perceived thickness of the border due to the contrast between the black and the blue
| View | Before | After |
| Desktop | ![Screenshot 2021-11-03 at 16 49 18](https://user-images.githubusercontent.com/64783893/140118149-17c38c1a-46fe-4978-8b16-84889e7c34ba.png) | ![Screenshot 2021-11-03 at 16 49 06](https://user-images.githubusercontent.com/64783893/140118127-4d4ca55d-5938-4820- …
> Update positioning and border colour on super navigation search button

- app/assets/stylesheets/govuk_publishing_components/components/_layout-super-navigation-header.scss
- app/views/govuk_publishing_components/components/_layout_super_navigation_header.html.erb
- config/locales/en.yml
- spec/components/layout_super_navigation_header_spec.rb
Move the "Departments" link into the "Government activity" submenu.
The "Departments" link to wasn't being as well used as predicted, with users not finding what they wanted when clicking on the link. This means it could be moved to under the "Government activity" menu, with the hope that it stops being distracting and increases user engagement with the topics menu.
Before:
After:
Before:
After:
> Move "Departments" into "Government Activity" menu

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/_all_components.scss
- app/assets/stylesheets/govuk_publishing_components/components/_single-page-notification-button.scss
- app/views/govuk_publishing_components/components/_single_page_notification_button.html.erb
- app/views/govuk_publishing_components/components/docs/single_page_notification_button.yml
- config/locales/en.yml
- spec/components/single_page_notification_button_spec.rb
Create the button component for [single page notifications](https://www.figma.com/file/9RzsNFl3iYBXM5QfKO2HkE/Detailed-notifications-%2B-account?node-id=40%3A5830).
The intention is to attach this button to the metadata block component (only the [variation with a link to see all updates](https://components.publishing.service.gov.uk/component-guide/metadata/updated_with_links_to_see_details/preview)) and [published dates](https://government-frontend.herokuapp.com/component-guide/published-dates) component (again, only the variation that has a list of updates).
The button comes with two states:
- the default state (user is either logged out, or is logged in and does not already receive email notifications for the current page)
- the "subscribed" state (user is logged in and has email …
> Add single page notification component

- app/models/govuk_publishing_components/shared_accessibility_criteria.rb
Add shared accessibility criteria for buttons in components.
We've got shared accessibility criteria for links but nothing else. I realised that lots of components have buttons in, and this could save us some effort.
The criteria are the same as for links, which feels a little repetitive except that each criteria specifically talks about links and buttons. Also some components have buttons, some have links, some have both.
> Add shared accessibility criteria for button

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
Includes:
* Bump `govuk-frontend` from 3.13.0 to 3.14.0 ([PR #2334](https://github.com/alphagov/govuk_publishing_components/pull/2334 ))
* Add single page notification component ([PR #2293](https://github.com/alphagov/govuk_publishing_components/pull/2293))
* Update the design of the mobile menu button on the super navigation ([PR #2382](https://github.com/alphagov/govuk_publishing_components/pull/2382))
* Update positioning and border colour on super navigation search button ([PR #2413](https://github.com/alphagov/govuk_publishing_components/pull/2413))
> Release v27.11.0

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/_layout-super-navigation-header.scss
Adjusts the spacing on the navigation header mobile layout.
https://trello.com/c/tfMzKE9j/625-adjust-spacing-on-menu
To better balance the layout of the links and / or buttons.
| Before | After | 
| - | - |
| ![](https://user-images.githubusercontent.com/1732331/140739918-900ee574-2744-4a1c-9211-ba951846571c.png) | ![](https://user-images.githubusercontent.com/1732331/140739572-921325ef-1dbb-4353-9f2d-ebe6ea32b940.png) |
| ![](https://user-images.githubusercontent.com/1732331/140739934-f08ebb32-53cd-43dc-bc43-5acab989c5ef.png) |  ![](https://user-images.githubusercontent.com/1732331/140739473-c61946bc-092d-44a5-b66b-3ebf52cf89b2.png) |
> Add more spacing in the navigation header mobile layout

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/_layout-super-navigation-header.scss
This changes the height of the navigation header to match the GOV.UK Frontend header.
Also fixes `:focus:hover` state for browsers that support `:focus-visible` - to support both `:focus` and `:focus-visible` we need to add the styles for both `:focus` and `:focus-visible` - then undo the styles `:focus` styles for browsers that support `:focus-visible`. This means that any undone styles need to be re-addded back - and the `:focus:hover` state was previously missed.
In the far distant past and for reasons unknown the black bar in the header component was adjusted to be a different height to the height of the GOV.UK Frontend / Design System header component. This meant that when a user goes from www.gov.uk to a service, the header would change height - which is not the seamless experience …
> Adjust navigation header black bar height

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/_accordion.scss
- app/assets/stylesheets/govuk_publishing_components/components/_layout-super-navigation-header.scss
- app/assets/stylesheets/govuk_publishing_components/components/mixins/_prefixed-transform.scss
Adds a shared mixin for css `transform` options that includes prefixed versions of the attribute for use by the [super nav](https://components.publishing.service.gov.uk/component-guide/layout_super_navigation_header) and [accordion](http://govuk-publishing-components.dev.gov.uk/component-guide/accordion) components.
Fixes https://github.com/alphagov/govuk_publishing_components/issues/2419
- This is not an extensive mixin for the `transform` attribute. It only meets how we're using it currently (in these 2 components, only using `translateY`, `rotate` and `scale`)
- A more extensive solution would be to use an autoprefixer. Will make an issue to this effect.
[Card](https://trello.com/c/HMp5VYUV/624-fix-chevrons-in-menu-and-accordions-for-ie9)
Before:
After:
Before:
After:
Before:
After:
> Fix chevron rotation for the super navigation header and accordion components on IE9

- CHANGELOG.md
- app/views/govuk_publishing_components/components/_input.html.erb
- app/views/govuk_publishing_components/components/_search.html.erb
- app/views/govuk_publishing_components/components/docs/input.yml
- spec/components/input_spec.rb
- spec/components/search_spec.rb
Adds `enterkeyhint` option to set the `enterkeyhint` attribute on the input element in the input component.
Sets the `enterkeyhint` attribute to `search` on the input and button elements in the search component.
The `enterkeyhint` attribute can be used to ask virtual keyboards to display a different word or icon for the enter key - for example, 'search' or 'next'.
See the [spec for more details](https://html.spec.whatwg.org/multipage/interaction.html#attr-enterkeyhint).
| - | - |
| ![997A43DA-98AA-4764-A222-04AEBC0ABD21](https://user-images.githubusercontent.com/1732331/140961098-9ccfdaff-d1c7-49ad-8845-b24f2bba356a.PNG) | ![AABF79FB-BAE3-401F-A001-DFB9CE005BD0](https://user-images.githubusercontent.com/1732331/140961104-e33902ab-67a1-4ec9-bd4e-33d621edc9d3.PNG) |
> Add `enterkeyhint` attribute to input and search

- spec/dummy/config/application.rb
Defines the locales actually in use, in the application. This has been
done as a prerequisite for the Rails Translation Manager changes [1].
[1]: https://github.com/alphagov/rails_translation_manager/pull/12
Trello:
https://trello.com/c/Ma1ygjNc/2567-add-automated-tests-to-check-translations-5
> Define available locales

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/_layout-super-navigation-header.scss
Reduce the weight of super navigation header chevrons from 2px to 3px.
Recommendation from our designer so that the chevrons don't look as heavy.
[Card](https://trello.com/c/3TsCU55d/631-chevrons-are-a-bit-heavy-make-them-2px)
Before:
After:
Before:
After:
Before:
After:
> Reduce the weight of super navigation header chevrons

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
Includes:
* Add more spacing in the navigation header mobile layout ([PR #2421](https://github.com/alphagov/govuk_publishing_components/pull/2421 ))
* Adjust navigation header black bar height ([PR #2422](https://github.com/alphagov/govuk_publishing_components/pull/2422 ))
* Fix chevron rotation for the super navigation header and accordion components on IE9 ([PR #2429](https://github.com/alphagov/govuk_publishing_components/pull/2429))
* Add `enterkeyhint` attribute to input and search ([PR #2426](https://github.com/alphagov/govuk_publishing_components/pull/2426 ))
* Retire the Brexit checker part of the Brexit call to action ([PR #2432](https://github.com/alphagov/govuk_publishing_components/pull/2432)) (patch change)
* Reduce the weight of super navigation header chevrons ([PR …
> Release v27.12.0

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/_layout-super-navigation-header.scss
Adds `margin: 0` to the super navigation mobile menu button to explicitly specify that the button has no margin
Safari adds a 2px margin to either side of buttons by default which creates a tiny visual snaffu for the super nav UI on mobile.
[Card](https://trello.com/c/dnfepAma/635-4-small-issue-with-pipe-on-mobile-when-search-is-open-safari)
Before:
After:
> Add an explicit margin zero to the super navigation mobile menu button

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/_layout-super-navigation-header.scss
- config/locales/en.yml
Remove Brexit as an item under the topics menu on the super navigation header.
The Brexit landing page is being wound down. This has been approved by the Brexit team.
[Card](https://trello.com/c/EQXkO2fv/637-remove-brexit-link-from-topics)
Before:
After:
> Remove brexit as a topic from the super navigation header

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/_layout-super-navigation-header.scss
Makes the following amendments to the super nav:
- Applies the pseudo underline to the mobile menu button
- Reduces the weight of the pseudo underline
- Nudges the chevron on open down by 1px
- So that the mobile menu button follows the "open" behaviour of buttons on desktop
- So that the pseudo underlines are inline with design system link style hover thickness (3px)
- So that the chevrons aren't floating too high on open
[Card](https://trello.com/c/U5BwCztJ/632-mobile-menu-open-show-the-active-doo-dad-blue-bottom-border-as-we-have-on-desktop)
Before:
After:
Before:
After:
Before:
After:
> Update the pseudo underline mixin and its usage on the super navigation header

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/components/layout-super-navigation-header.js
Fixes #2430 - the layout would become disjointed as width that triggered CSS changes was different to the width that triggered JavaScript changes _only if_ the scrollbar was permanently visible. This was due to the use of `window.innerWidth` which reports the width of the viewport including the width of the scrollbar. Using `document.documentElement.clientWidth` reports the width of the viewport sans any bars.
Because layout bugs are not good to have.
https://user-images.githubusercontent.com/1732331/141364868-c5008dbd-112f-4d65-baed-b7f9a1da83ce.mov
https://user-images.githubusercontent.com/1732331/141364778-3fd75cee-e1b3-4d59-bd35-699a14554127.mov
> Fix layout glitch seen when scrollbar is permanently visible

- CHANGELOG.md
- lib/govuk_publishing_components/presenters/contextual_navigation.rb
We removed the direct link from hub pages to the checker in https://github.com/alphagov/govuk_publishing_components/pull/2432 but we now want to remove the Brexit sidebar nav completely from these two pages ([businesses](https://www.gov.uk/guidance/brexit-guidance-for-businesses) and [individuals](https://www.gov.uk/guidance/brexit-guidance-for-individuals-and-families)) to stop circular journeys.
We can remove the logic around "brexit_start_page_content_id" because that page hasn't existed for a while.
> Don't show Brexit side nav on hub pages

- CHANGELOG.md
- lib/govuk_publishing_components/presenters/button_helper.rb
- spec/components/button_spec.rb
Add `draggable="false"` as an attribute for links styled to look like buttons.
Fixes https://github.com/alphagov/govuk_publishing_components/issues/1558
> Add draggable=false to links disguised as buttons

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/mixins/_margins.scss
- app/views/govuk_publishing_components/components/_metadata.html.erb
- app/views/govuk_publishing_components/components/docs/metadata.yml
- spec/components/metadata_spec.rb
1. Add `margin_bottom` option to the metadata component, because sometimes there is a need to adjust the margins of the metadata component (more specifically, it will be necessary to adjust the spacing when we add the [email notification button](https://components.publishing.service.gov.uk/component-guide/single_page_notification_button) under the metadata component)
2. Update margin mixins to use the standard `govuk-spacing` scale – for some reason, the `responsive-bottom-margin` and `responsive-top-margin` mixins were using `govuk-spacing(6) * 1.5` values (probably because the standard spacing scale does not support 45px spacing). 
This replaces `govuk-spacing(6) * 1.5` with `govuk-spacing(7)` which translates to 40px which is just 5px less and should not make for a noticeable …
> Add `margin_bottom` option to the metadata component and update margin mixins to use the standard GOVUK spacing scale

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/_layout-super-navigation-header.scss
- app/views/govuk_publishing_components/components/_layout_super_navigation_header.html.erb
- config/locales/en.yml
Updates the layout of the "Government activity" submenu in the navigation header.
Example page: https://components-gem-pr-2442.herokuapp.com/public
Because "Departments" seemed odd when placed on its own row it was rejigged to go as part of the main list. This also meant that the CSS for both the "Topics" and "Government activity" could be better aligned as the grid layout was the same.
| Screen size | Before | After |
| - | - | - |
| < 360px | ![](https://user-images.githubusercontent.com/1732331/141329480-5c535847-b0f0-47f0-9b27-fcad50b3e5f9.png) | ![](https://user-images.githubusercontent.com/1732331/141341707-649d14c4-cf20-4073-afd6-aafe500a1a7d.png) |
| >= 360px | ![](https://user-images.githubusercontent.com/1732331/141329409-ef1672be-33a4-4234-a3fd-24301e7568b7.png) | …
> Update "Government activity" submenu layout

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/govuk_frontend_support.scss
DLUHC = Department for Levelling Up, Housing and Communities
Adds the brand colour for DLUHC.
The colour has a contrast ratio of 14.75, so not adding a websafe colour for this organisation.
The same change has been made in [govuk-frontend](https://github.com/alphagov/govuk-frontend/pull/2434), however we need to also make the change here until the next release of govuk-frontend.
[Zendesk ticket](https://govuk.zendesk.com/agent/tickets/4712566)
> Add organisation colour for Department for Levelling Up, Housing and Communities (DLUHC)

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
* Add brand colour for Department for Levelling Up, Housing and Communities (DLUHC) ([PR #2454](https://github.com/alphagov/govuk_publishing_components/pull/2454))
* Add `margin_bottom` option to the metadata component and update margin mixins to use the standard GOVUK spacing scale ([PR #2450](https://github.com/alphagov/govuk_publishing_components/pull/2450))
* Tweak to sidebar navigation on Brexit hub pages ([PR #2449](https://github.com/alphagov/govuk_publishing_components/pull/2449))
* Add an explicit margin zero to the super navigation mobile menu button ([PR #2445](https://github.com/alphagov/govuk_publishing_components/pull/2445))
* Remove brexit as a topic from the super navigation header ([PR #2446](https://github.com/alphagov/govuk_publishing_components/pull/2446))
* Update the …
> Version 27.13.0

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/components/single-page-notification-button.js
- app/views/govuk_publishing_components/components/_single_page_notification_button.html.erb
- app/views/govuk_publishing_components/components/docs/single_page_notification_button.yml
- lib/govuk_publishing_components.rb
- lib/govuk_publishing_components/presenters/single_page_notification_button_helper.rb
- spec/components/single_page_notification_button_spec.rb
- spec/dummy/config/routes.rb
- spec/javascripts/components/single-page-notification-button-spec.js
The single page notification button exists in two states: [default (unsubscribed)](https://components.publishing.service.gov.uk/component-guide/single_page_notification_button/default) and [already subscribed](https://components.publishing.service.gov.uk/component-guide/single_page_notification_button/already_subscribed).
If a user is authenticated and already subscribed to email notifications on the current page, the button should say "Stop getting emails about this page". To request the  user data for this layer of personalisation, there is a need to bypass the CDN, however it is not practical to serve all such requests from origin (especially on relatively high traffic pages such as the ones it is likely this feature will be added to).
As such the solution we've landed on is to use JS …
> Get single page notification button from personalisation API on load

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
Includes:
* Get single page notification button from personalisation API on load ([PR #2443](https://github.com/alphagov/govuk_publishing_components/pull/2443))
> Bump gem to 27.14.0

- CHANGELOG.md
- app/views/govuk_publishing_components/components/_big_number.html.erb
Removes a stray `href` from the big number API presets
This is a repeated value and is therefore redundant!
> Remove redundant API value from big number component

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/_layout-super-navigation-header.scss
- app/views/govuk_publishing_components/components/_layout_super_navigation_header.html.erb
Remove `govuk-list` from navigation header component, and add `list-style: none` to the component class.
The use of `govuk-list` was slightly problematic - the class was being appearing
after the component styles in some applications due to the application CSS being
later in the cascade that the CSS from Static - so the component spacing would
be overridden.
The only thing that was not being override was `list-style`, so this declaration
was added to the class in the component and `govuk-list` was removed.
|  | Before | After | 
| - | - | - |
| Topics | ![www gov uk_ (2)](https://user-images.githubusercontent.com/1732331/142851422-351887ab-3111-48b1-b4bd-dbba9cfcf6d6.png) | ![frontend dev gov uk_ (8)](https://user-images.githubusercontent.com/1732331/142851417-7a650f04-c4f3-4fc2-bd23-b8f88 …
> Remove use of `govuk-list` from navigation header

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
Includes:
* Remove redundant API value from big number component ([PR #2459](https://github.com/alphagov/govuk_publishing_components/pull/2459))
* Remove use of `govuk-list` from navigation header ([PR #2460](https://github.com/alphagov/govuk_publishing_components/pull/2460))
> Release 27.14.1

- spec/components/heading_spec.rb
- spec/components/list_spec.rb
- spec/components/subscription_links_spec.rb
- spec/components/title_spec.rb
All the uses of `[class='^=class-name']` have been replaced with the correct formatting: `[class^='class-name']`.
As [highlighted by @owenatgov in another review][1], there were selectors in the spec that weren't formatted correctly - so they were potentially able to giving false negatives and needed fixing.
[1]: https://github.com/alphagov/govuk_publishing_components/pull/2462#discussion_r755090045
> Fix selectors in spec

- CHANGELOG.md
- app/views/govuk_publishing_components/components/_search.html.erb
- app/views/govuk_publishing_components/components/docs/search.yml
- spec/components/search_spec.rb
- Updates search component documentation to mention `margin_bottom` parameter - only the documentation was added here, not the functionality.
- Adds the ability to change the spacing between the label and the input
- Allows the search label to be wrapped in a heading - similar to [the `isPageHeading` setting in GOV.UK Frontend's Nunjucks macro.][1] This is best used in conjunction with `label_size`.
The documentation for the `margin_bottom` attribute was missing, so needed to be added.
The spacing between the label and the input needed to be more flexible to allow for the updated homepage layout.
Having the label wrapped as a heading will allow for a the structure of the page to make semantic sense without needing unnecessary repetition - for example, a heading saying "Search" followed by …
> Update search component

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/analytics/auto-scroll-tracker.js
- docs/analytics/auto_scroll_tracker.md
- spec/javascripts/govuk_publishing_components/lib/auto-scroll-tracker-spec.js
Extend the functionality of the new scroll tracking script, to provide new features. Specifically:
- allows specific URLs to be targeted or excluded from scroll tracking, where a template renders more than one URL
- allows specific URLs to track custom percentage positions or specific headings only
Attempts to migrate scroll tracking from the old script to the new script have highlighted features that require implementation.
None.
Trello card: https://trello.com/c/sdugtMbX/37-migrate-to-new-scroll-tracker
> Extend new scroll tracker functionality

- CHANGELOG.md
- config/locales/en.yml
We were pointing to a 404. This address matches what's in the [Design System footer](https://design-system.service.gov.uk/components/footer/)
None
> Fix link to Crown Copyright

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/components/single-page-notification-button.js
- app/views/govuk_publishing_components/components/_single_page_notification_button.html.erb
- lib/govuk_publishing_components/presenters/single_page_notification_button_helper.rb
- spec/components/single_page_notification_button_spec.rb
1. The data attributes for tracking were not named correctly. 
The `data-label` attribute  should be `data-track-label`, `data-action` should be `data-track-action`, `data-category` should be `data-track-category`.
2. Apply `data-module=gem-track-click` attribute to a wrapper div instead of the form itself. The reason for this is that
the form gets dynamically swapped out with the form returned from the personalisation endpoint. If `data-module=gem-track-click` was applied to the form, then in order for click tracking to fire correctly after the JS update has occurred, the track click module would have to be re-started on the updated form, which is not ideal. 
This is a workaround which can be credited to @andysellick
> Fix single page notification button data attributes for tracking

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/analytics/explicit-cross-domain-links.js
- app/assets/javascripts/govuk_publishing_components/components/cookie-banner.js
- docs/javascript-modules.md
- spec/javascripts/govuk_publishing_components/analytics/explicit-cross-domain-links.spec.js
- spec/javascripts/govuk_publishing_components/modules.spec.js
Amend `explicit-cross-domain-links` code to account for the possibility of someone accepting/rejecting cookies on the page that the cross-domain link is present. 
This was raised as a bug on the Brexit page, where the **Sign in** link is a cross-domain link (leading to DI Sign In territory). 
If someone has interacted with the cookie banner on this page, the link treats them as if they have not, i.e the `?cookie_consent=not_engaged` parameter remains unchanged, and the GA parameter is not added (if they have accepted cookies). The setting applies only after the page is reloaded.
https://user-images.githubusercontent.com/7116819/143051955-22e6eb6a-f22f-48b1-b2e1-e6e59df52665.mov
https://user-images.githubusercontent.com/7116819/143052834-1f00cbc2-b2fe-41a6-8948-89e97a4e5b67.mov
Upon …
> Amend `explicit-cross-domain-links.js` code

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
* Update search component ([PR #2462](https://github.com/alphagov/govuk_publishing_components/pull/2462))
* Fix link to Crown Copyright in footer ([PR #2475](https://github.com/alphagov/govuk_publishing_components/pull/2475))
* Fix single page notification button data attributes for tracking ([PR #2471](https://github.com/alphagov/govuk_publishing_components/pull/2471))
* Amend `explicit-cross-domain-links.js` code ([PR #2464](https://github.com/alphagov/govuk_publishing_components/pull/2464))
> Bump gem to 27.14.2

- CHANGELOG.md
- app/views/govuk_publishing_components/components/_button.html.erb
- lib/govuk_publishing_components/presenters/button_helper.rb
- spec/components/button_spec.rb
Update start button to link info text below
"If you provide information text to a button, the text is rendered underneath the button but not linked to it in any way. This means it won't be read out to screenreader users when they focus on the button, and they could miss important information."
Closes #2083 
https://user-images.githubusercontent.com/71266765/143418992-921ca3f9-f737-4964-bf35-a64b877ebfd7.mov
> Update Start button so info text is associated

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/_layout-super-navigation-header.scss
Updates the hover state of the search link and search toggle button to have the same underline thickness as the other toggle buttons / links.
For visual consistency.
JavaScript unavailable before: ![](https://user-images.githubusercontent.com/1732331/143874714-66011d5c-9fd3-40ab-873c-f20459959043.png)
JavaScript unavailable after: ![](https://user-images.githubusercontent.com/1732331/143874717-86c2ab91-ce57-4c82-ba56-89a8727bc379.png)
JavaScript available before:
JavaScript available after:
> Update nav header search hover state underline

- app/views/govuk_publishing_components/components/docs/radio.yml
Update radio examples to include a heading attribute (which renders as a legend within the fieldset).
As a first step in promoting a more accessible version of radios – see #1215
https://components-gem-pr-2485.herokuapp.com/component-guide/radio
> Update radio examples to include a heading attribute

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/_layout-super-navigation-header.scss
Update navigation header link / toggle button spacing for the desktop layout.
Ticket: https://trello.com/c/aZhaaNyT
Preview page: https://components-gem-pr-2483.herokuapp.com/public
To make the spacing in the desktoplayout look more balanced.
Preview page: https://components-gem-pr-2483.herokuapp.com/public
> Update navigation header toggle button spacing

- app/views/govuk_publishing_components/components/docs/layout_for_public.yml
As of [over a month ago](https://github.com/alphagov/govuk_publishing_components/commit/89aa073d3685a7cc67246960818330613c467d6a), the account navigation no longer includes a separate "security" link so
the documentation should reflect that.
> Update layout_for_public component documentation

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
Update to 27.15.0
* Update Start button so info text is associated ([PR #2476](https://github.com/alphagov/govuk_publishing_components/pull/2476))
* Remove whitespace from pseudo-element content ([PR #2482](https://github.com/alphagov/govuk_publishing_components/pull/2482))
* Update navigation header toggle button spacing ([PR #2483](https://github.com/alphagov/govuk_publishing_components/pull/2483))
* Update search toggle / link hover state underline thickness ([PR #2484](https://github.com/alphagov/govuk_publishing_components/pull/2484))
> Release 27.15.0

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/_big-number.scss
Updates the [big number](https://components.publishing.service.gov.uk/component-guide/big_number) component to not use the design system's [`govuk-font`](https://components.publishing.service.gov.uk/component-guide/big_number) sass mixin.
Currently, the govuk-font mixin enforces responsive typography when in this case we want it to maintain the same font between screen sizes. Additionally, the current label font size is 16px which reverts to 14px on mobile, an inaccessible font size. We use a similar approach on the super navigation header, check that component for examples if you're curious about this.
- https://trello.com/c/5VUAmVR7/682-3homepage-big-numbers-on-tablet-fix-sizing
- https://trello.com/c/RU79pucB/688-homepage-mobile-big-numbers-are-not-big
There is no visual change to the …
> Remove use of govuk-font from the big number component

- CHANGELOG.md
- app/views/govuk_publishing_components/components/_intervention.html.erb
- app/views/govuk_publishing_components/components/docs/intervention.yml
- config/locales/en.yml
- lib/govuk_publishing_components/presenters/intervention_helper.rb
- spec/components/intervention_spec.rb
- spec/lib/govuk_publishing_components/components/intervention_helper_spec.rb
Adds a parameter to the Intervention banner to allow links to open in a new tab.
In order to drive users to another online task, we don't want to completely hijack their original flow on GOV.UK. Adding the option to open links in a new tab helps to address this.
> Add support to open Intervention links in new tab

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/_big-number.scss
A follow on from https://github.com/alphagov/govuk_publishing_components/pull/2493 to use design system mixins and variables in as many places as possible whilst not using `govuk-font`.
Following the merging of 2493, Ollie Byford from the design system team left some comments noting the existence of mixins like `govuk-typography-common` and how they would be useful here. See his review on 2493 for details.
- https://trello.com/c/5VUAmVR7/682-3homepage-big-numbers-on-tablet-fix-sizing
- https://trello.com/c/RU79pucB/688-homepage-mobile-big-numbers-are-not-big
Will not be including visual changes as the only change is the difference in colour from system black (#000000) to the design system "black" which isn't perceivable to the naked eye.
> Use the correct mixins for applying font in the big number component

- CHANGELOG.md
- app/views/govuk_publishing_components/components/_success_alert.html.erb
- app/views/govuk_publishing_components/components/docs/success_alert.yml
- spec/components/success_alert_spec.rb
The GOV.UK success alert component has a fixed bottom margin which is fine in most use cases of this component.
Recently, however, the success alert component has been added to the top of publication pages whose content has a large margin on the top.
The result is that the visual space between the success alert and the content of the page is excessive, hence the need to introduce this option to the component.
---
https://trello.com/c/Z2eem0IC
> Add margin_bottom option to success alert

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/analytics/custom-dimensions.js
- spec/javascripts/govuk_publishing_components/analytics/custom-dimensions.spec.js
Remove jQuery from the analytics `custom dimensions` script. This script is used to get and set the various `dimension` attributes added to an analytics event. This includes getting information from the browser (e.g. status code, gaClientId, device pixel ratio) and dimensions from meta tags set by GOV.UK content.
Also adds a test for this file, as one didn't exist 😬 
None.
> Remove jQuery from custom dimensions

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
Includes:
* Remove jQuery from custom dimensions ([PR #2473](https://github.com/alphagov/govuk_publishing_components/pull/2473))
* Use the correct mixins for applying font in the big number component ([PR #2494](https://github.com/alphagov/govuk_publishing_components/pull/2494))
* Remove use of govuk-font from the big number component ([PR #2493](https://github.com/alphagov/govuk_publishing_components/pull/2493))
* Add `margin_bottom` option to success alert ([PR #2492](https://github.com/alphagov/govuk_publishing_components/pull/2492))
> Bump gem to 27.16.0

- docs/analytics/track-click.md
Update `track-click.md` to mention that `data-track-label` is optional, but recommended as per
GA documentation.
> Add note to `track-click.md`

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/_layout-super-navigation-header.scss
Adds options to the `pseudo-underline` mixin within the super nav header to allow them to take different `left` and `right` attributes based on the button using the mixin.
Led by a bug report from Stephen McCarthy that the underline on the mobile menu button looks a bit weird.
The reason I've made the choice to alter how the mixin is initiated rather than just change the spacing is that this initial spacing is a conscious choice made in https://github.com/alphagov/govuk_publishing_components/pull/2483 This maintains the intent of 2483 whilst fixing this issue.
[Card](https://trello.com/c/SkO1xxdS/703-fix-pseudo-underline-on-mobile-menu-button)
> Alter use of pseudo-underline mixin to allow for different button sizes

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/analytics/explicit-cross-domain-links.js
- app/assets/javascripts/govuk_publishing_components/components/cookie-banner.js
- docs/javascript-modules.md
- spec/javascripts/govuk_publishing_components/analytics/explicit-cross-domain-links.spec.js
- spec/javascripts/govuk_publishing_components/modules.spec.js
It has transpired that the `explicit-cross-domain-links.js` script was not
set up correctly which is breaking our cross domain tracking currently.
The source of the issue is the `_ga` parameter which contains a timestamp
which actually expires and becomes invalid after two minutes.
The way the script worked previously was that the relevant cross-domain
links and forms on the page were decorated with the `_ga` and
`cookie_consent` parameters on page load. Doing it on page load is an
issue due to the time-sensitive nature of the `_ga` parameter, as
mentioned above.
This changes the way the script works so that instead of decorating
crossdomain links and forms with additional parameters on page load, we
decorate them when they are interacted with.
Besides ensuring that the `_ga` param is …
> Re-work `explicit-cross-domain-links.js`

- app/assets/stylesheets/govuk_publishing_components/components/govspeak/_tables.scss
https://trello.com/c/SXYdqORT/852-review-govspeak-table-and-possibly-other-components
- It's not consistent with Component Guide and the Design System
- Not adhering to accessibility standards
- Could other components in Govspeak have the same issue as well?
<table role="table">
<thead>
<tr>
<th>Before (inputs)</th>
<th>After (desktop)</th>
</tr>
</thead>
<tbody>
<tr>
<td valign="top"><a target="_blank" rel="noopener noreferrer" href="https://user-images.githubusercontent.com/87758239/143206338-3cd63031-2c5a-4299-bbc2-6b5a0575958c.png"><img src="https://user-images.githubusercontent.com/87758239/143206338-3cd63031-2c5a-4299-bbc2-6b5a0575958c.png" width="360" style="max-width: 100%;"></a></td>
<td valign="top"><a target="_blank" rel="noopener noreferrer" …
> Update govspeak table styles

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/_big-number.scss
Reinstates the use of `govuk-font` for [big number labels](https://components.publishing.service.gov.uk/component-guide/big_number/with_labels) so that it is 19px on desktop and 16px on mobile (change managed by the font mixin).
Recommendations by our designer as part of the new homepage work. The larger label will generally make it more legible on desktop.
[Card](https://trello.com/c/ilFWAf2G/699-sort-out-label-font-on-big-number-component)
> Increase big number label size

- CHANGELOG.md
- config/locales/en.yml
Changes `consultation` to `consultations` in the menu.
[Trello card](https://trello.com/c/2nJZcJO6/696-nav-menu-content-updates)
(NOTE font issue will be fixed in another PR)
> Fix typo in menu

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
Includes:
* Alter use of pseudo-underline mixin to allow for different button sizes ([PR #2501](https://github.com/alphagov/govuk_publishing_components/pull/2501))
* Re-work explicit-cross-domain-links.js ([PR #2502](https://github.com/alphagov/govuk_publishing_components/pull/2502))
* Update govspeak table styles ([PR #2470](https://github.com/alphagov/govuk_publishing_components/pull/2470))
* Increase big number label size ([PR #2506](https://github.com/alphagov/govuk_publishing_components/pull/2506))
* Fix typo in menu([#2503](https://github.com/alphagov/govuk_publishing_components/pull/2503))
> Bump gem to 27.17.0

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/_layout-super-navigation-header.scss
Transport was not explicitly set on the menu items, so if viewing in Heroku for example the menu styling would appear broken.
> Fix font for menu paragraphs

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/_search.scss
- app/views/govuk_publishing_components/components/_search.html.erb
- app/views/govuk_publishing_components/components/docs/search.yml
- spec/components/search_spec.rb
Adds `large-mobile` as an option for the `size` attribute on the [search component](https://components.publishing.service.gov.uk/component-guide/search). This means that the "large" styles, previously applied to all screen sizes via `size: "large"`, will only be applied to the search component on mobile.
Recommendation from our designer as part of the homepage work to make sure that the search box looks nice between screen sizes.
[Card](https://trello.com/c/Ss9cKnkL/702-homepage-stretch-goal-smaller-search-bar-on-desktop)
> Add large mode on mobile only to search component

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/analytics/explicit-cross-domain-links.js
`String.prototype.includes()` is not supported in all major browsers. Swap
it for `indexOf()` which benefits from better browser support.
Fixes #2451
> Replace use of `includes()` in `explicit-cross-domain-links.js` with `indexOf()` alternative

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/_layout-super-navigation-header.scss
- app/assets/stylesheets/govuk_publishing_components/components/mixins/_grid-helper.scss
Replace the grid mixins from the super nav sass into a separate mixin file and update the grid helper in line with the most recent updates made during the new homepage work (https://github.com/alphagov/frontend/blob/main/app/assets/stylesheets/mixins/_grid-helper.scss).
The new homepage is using the same grid setup as the super nav. This will allow us to distribute the mixin between the super nav and the homepage to repeat code repetition.
> Port the grid_helper sass mixin to the components gem

- CHANGELOG.md
- config/locales/en.yml
Update the popular links section of the super navigation menu.
To keep this content in line with the "Popular on GOV.UK" section of the homepage.
[Card](https://trello.com/c/n1wwl3Mx/709-update-the-popular-on-govuk-links-in-the-menu-bar-and-devise-process-for-this-in-future)
> Update super nav popular links

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/components/single-page-notification-button.js
- app/assets/stylesheets/govuk_publishing_components/components/_single-page-notification-button.scss
- app/views/govuk_publishing_components/components/_single_page_notification_button.html.erb
- lib/govuk_publishing_components/presenters/single_page_notification_button_helper.rb
- spec/components/single_page_notification_button_spec.rb
- spec/javascripts/components/single-page-notification-button-spec.js
Fix flash of unpersonalised content that can happen to the Single page
notification button when someone is logged in and has subscribed to
notifications on the current page.
This feature has been designed with the personalisation bit as a JS
enhancement. A JS request is made to a personalisation endpoint on page
load, which returns a response based on which the button reflects the
subscription status of the current user to the current page.
The swap from old button to updated button should happen in a near
instant in ideal conditions, but can be more obvious in certain
instances (such as if someone's internet connection is not good)
This aims to work around this problem by initially hiding the button
when JS is enabled, then making it visible immediately when XHR has
completed. …
> Fix single page notification button flash of unpersonalised content

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
* Remove jQuery from page-content ([PR #2505](https://github.com/alphagov/govuk_publishing_components/pull/2505))
* Replace use of `includes()` in `explicit-cross-domain-links.js` with `indexOf()` alternative [PR #2515](https://github.com/alphagov/govuk_publishing_components/pull/2515)
* Fix font for menu paragraphs [PR #2509](https://github.com/alphagov/govuk_publishing_components/pull/2509)
* Add large mode on mobile only to search component ([PR #2510](https://github.com/alphagov/govuk_publishing_components/pull/2510))
* Port the grid_helper sass mixin to the components gem ([PR #2517](https://github.com/alphagov/govuk_publishing_components/pull/2517))
* Update super nav popular links ([PR #2519](https://github.com/alphagov/govuk_publishing_components/pull/2519))
* Fix single page …
> Release version 27.18.0

- CHANGELOG.md
- app/views/govuk_publishing_components/components/_intervention.html.erb
- app/views/govuk_publishing_components/components/docs/intervention.yml
- spec/components/intervention_spec.rb
Add a param to the component to hide the banner by default. This allows for logic in both the backend or Javascript to manipulate that component easily to display it based on whatever logic.
We want to selectively display a link to an online tree test for specific topics on GOV.UK. Adding this flag allows us to control whether to display the banner for our user research recruitment.
Related PR: https://github.com/alphagov/collections/pull/2630
[Trello card](https://trello.com/c/1o6QiDxC/646-add-banner-for-user-research-exercise-to-selected-pages)
> Add flag to hide Intervention Banner component

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/_contextual-sidebar.scss
- app/views/govuk_publishing_components/components/_contextual_sidebar.html.erb
- app/views/govuk_publishing_components/components/contextual_sidebar/_covid_cta.html.erb
- app/views/govuk_publishing_components/components/docs/contextual_sidebar.yml
- config/locales/en.yml
- lib/govuk_publishing_components/presenters/contextual_navigation.rb
- spec/components/contextual_sidebar_spec.rb
- spec/components/covid_cta_spec.rb
- spec/features/contextual_navigation_spec.rb
- spec/lib/govuk_publishing_components/presenters/contextual_navigation_spec.rb
Trello: https://trello.com/c/Vq3rAdyX
The COVID CTA has be implemented in addition to the existing Brexit CTA (rendered within the contextual sidebar component. The reason for this is that we have been asked to keep the Brexit CTA on ‘importing and exporting pages’. Displays both the Brexit and COVID CTA’s (in that order) on the importing and exporting pages.
The content is:
**COVID-19 vaccinations**
[Book your coronavirus vaccination and booster dose on the NHS website](https://www.nhs.uk/conditions/coronavirus-covid-19/coronavirus-vaccination/)
Also adds tracking to the element with the following values:
- Event action 1.0 coronavirus
- Event Category: relatedLinkClicked
- Event Label [link]
The COVID CTA will for the most part replace the Brexit CTA on most pages with a few exceptions. …
> Add COVID CTA to contextual sidebar component

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
* Fix `help-notice` spacing in `call-to-action` ([PR #2536](https://github.com/alphagov/govuk_publishing_components/pull/2536))
* Add COVID CTA to contextual sidebar component ([PR #2535](https://github.com/alphagov/govuk_publishing_components/pull/2535))
* Add flag to hide Intervention Banner component [#2516](https://github.com/alphagov/govuk_publishing_components/pull/2516)
* Image card component design and API updates [PR #2530](https://github.com/alphagov/govuk_publishing_components/pull/2530)
> Release 27.19.0

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/_all_components.scss
- app/assets/stylesheets/govuk_publishing_components/components/_signup-link.scss
- app/views/govuk_publishing_components/components/_signup_link.html.erb
- app/views/govuk_publishing_components/components/docs/signup_link.yml
- spec/components/signup_link_spec.rb
Add the signup link component from `collections`.
- unchanged apart from `app-c` CSS class prefix changing to `gem-c` and tweaks to the test structure to make it run here
We want to use it in a smart-answer that's currently under development. Once this component has been moved from `collections` to here in the gem, we'll remove the one in `collections` and point it at this one.
Trello card: https://trello.com/c/i3brOfzz/431-add-multiple-country-select-question-type-to-smart-answers
> Add signup link component

- CHANGELOG.md
- config/locales/en.yml
Remove the link in the search section of the header menu: `Sign in to your personal tax account`.
This is a duplicate of the link further down in the same list: `Personal tax account: sign in` which is our preferred wording.
[Card](https://trello.com/c/DoDlY3ou/719-remove-sign-in-to-you-personal-tax-account-from-search-menu)
> Remove duplicate link in menu header

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/components/feedback.js
- app/assets/stylesheets/govuk_publishing_components/components/_feedback.scss
- app/views/govuk_publishing_components/components/docs/feedback.yml
- app/views/govuk_publishing_components/components/feedback/_problem_form.html.erb
- app/views/govuk_publishing_components/components/feedback/_survey_signup_form.html.erb
- app/views/govuk_publishing_components/components/feedback/_yes_no_banner.html.erb
- spec/component_guide/component_index_spec.rb
- spec/javascripts/components/feedback-spec.js
There is an issue whereby the feedback assets (CSS and JS) are currently shipped twice:
- from the application e.g. `government-frontend`
- from `static`.
The assets should only be imported from static. However, at the moment, if we remove the assets at the application level then there are style problems where the feedback component styles are overridden by subsequent imports. An example is documented here: https://github.com/alphagov/whitehall/pull/6240#issuecomment-977888889.
For now, to test locally, it's necessary to:
- update the Gemfile for `gem 'govuk_publishing_components', path: '../govuk_publishing_components'` at **both** the application level (e.g. `government-frontend`) and `static`
- import the textarea component styles `@import …
> Update feedback component to fix accessibility issues

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/analytics/download-link-tracker.js
- spec/javascripts/govuk_publishing_components/analytics/download-link-tracker.spec.js
Removes jQuery from the download link tracker, which tracks clicks on links to downloadable assets.
It works as follows. Once users consent to analytics, the tracker attaches a click event listener to all pages on the body element. If the clicked element is a link (or inside a link) that matches a particular selector, a tracking event is fired to GA.
The download link tracker is called in `static-analytics.js` and the selector passed is `'a[href*="/government/uploads"], a[href*="assets.publishing.service.gov.uk"]'`. Broadly, these match links to downloadable assets.
I've had to change the code more than I expected to remove jQuery owing to how easy it is to attach an event listener to multiple elements in jQuery compared to the relative complexity of that in vanilla JS. This change has …
> Remove jQuery from download link tracker

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/analytics/external-link-tracker.js
- spec/javascripts/govuk_publishing_components/analytics/external-link-tracker.spec.js
Removes jQuery from the external link tracker. This is a script that sends a tracking event when a consenting user clicks on a link to a page that isn't on www.gov.uk.
I've had to restructure this code quite a bit, partly because of the way event listeners work in JS vs jQuery and partly because the tests kept failing. 
The reason behind this was the `click` event listener was persisting between tests with the previous value for customDimension, so the test was technically passing but failing because the click event was occurring multiple times. This was originally solved with jQuery by using the `off` event listener remove, but in JS you have to pass the function that attached the listener, which was far more complex. Instead, the options are now attached to the external link tracker …
> Remove jQuery from external link tracker

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/analytics/google-analytics-universal-tracker.js
- app/assets/javascripts/govuk_publishing_components/lib/extend-object.js
- spec/javascripts/govuk_publishing_components/lib/extend-object-spec.js
Remove jQuery from Google Analytics Universal Tracker. This is the main script in the analytics code that contains all the things the rest of it depends on, like trackPageView and trackEvent, plus it also contains the snippet of JS from GA that makes everything work.
None.
> Remove jQuery from Google Analytics Universal Tracker

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/analytics/scroll-tracker.js
**NOTE** this PR depends upon this one: https://github.com/alphagov/collections/pull/2639
Remove scroll tracking from pages in `collections`, specifically:
- https://www.gov.uk/brexit
- https://www.gov.uk/coronavirus
These pages will be updated to use the new scroll tracker. Because the existing scroll tracker is initialised in the gem and the new one is initialised at an application level, this PR can only be merged and deployed into a new version of the gem when `collections` is updated to use the new scroll tracker, otherwise we risk having either no scroll tracking on these pages or double the scroll tracking. Note that this also needs to be co-ordinated with deploying to `static`, as that's where the analytics code is included.
Twofold:
- we built a [new scroll …
> Remove scroll tracking from collections

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/analytics/scroll-tracker.js
**NOTE** this PR depends upon this one: https://github.com/alphagov/frontend/pull/3104
Remove scroll tracking from pages in `frontend`, specifically:
- https://www.gov.uk/find-travel-test-provider
These pages will be updated to use the new scroll tracker. Because the existing scroll tracker is initialised in the gem and the new one is initialised at an application level, this PR can only be merged and deployed into a new version of the gem when `frontend` is updated to use the new scroll tracker, otherwise we risk having either no scroll tracking on these pages or double the scroll tracking. Note that this also needs to be co-ordinated with deploying to `static`, as that's where the analytics code is included.
Twofold:
- we built a [new scroll …
> Remove scroll tracking from frontend

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
* **BREAKING:** Update feedback component to fix accessibility issues ([PR #2435](https://github.com/alphagov/govuk_publishing_components/pull/2435))
You must make the following changes when you migrate to this release:
- Upgrade `static` to the latest version before you upgrade your application
* **BREAKING:** Remove deprecated components: `admin_analytics`, `government_navigation`, `highlight_boxes` and `taxonomy_list` ([PR #2458](https://github.com/alphagov/govuk_publishing_components/pull/2458))
* Remove scroll tracking from government-frontend ([PR #2548](https://github.com/alphagov/govuk_publishing_components/pull/2548))
* Remove scroll tracking from frontend ([PR #2546](https://github.com/alphagov/govuk_publishing_components/pull/2546))
* Remove scroll tracking from collections …
> Release 28.0.0

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/components/metadata.js
- app/views/govuk_publishing_components/components/_metadata.html.erb
- spec/javascripts/components/metadata-spec.js
On some publications, the metadata component has a "See all updates" link. This is an in-page link which jumps to the list of updates at the bottom of the page like so: 
https://user-images.githubusercontent.com/7116819/148392637-026ed708-bd57-427c-9ebc-91497b2390e9.mov
This is on purpose in order to get around having the list of update notes at the top of the page. The reason for this is that the list of notes can be quite long and so it would not be ideal to have this list before the main content of the publication page as even when hidden behind a visibility toggle, once it's been expanded such a list could take a lot of scrolling to get past and inconvenience some users.
There was some feedback in UR (this was UR for a tangential bit functionality on a publication page) that suggested …
> Tweak metadata component "See all updates" interaction

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/analytics.js
- app/assets/javascripts/govuk_publishing_components/analytics/custom-dimensions.js
- app/assets/javascripts/govuk_publishing_components/analytics/static-analytics.js
Remove jQuery from `static-analytics.js`.
Also now includes the commit from this PR: https://github.com/alphagov/govuk_publishing_components/pull/2553
None.
> Remove jQuery from static analytics

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/analytics/mailto-link-tracker.js
- spec/javascripts/components/metadata-spec.js
- spec/javascripts/govuk_publishing_components/analytics/mailto-link-tracker.spec.js
Removes jQuery from the mailto link tracker, a script that tracks consenting clicks on links that point to an email address e.g. `<a href="mailto:someone@somewhere.something">Email me</a>`.
This script is similar to the [external link tracker](https://github.com/alphagov/govuk_publishing_components/pull/2538) and the [download link tracker](https://github.com/alphagov/govuk_publishing_components/pull/2534) once jQuery has been removed, so maybe once all these PRs are complete some kind of consolidation could be done.
None.
> Remove jQuery from mailto-link-tracker

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
Includes:
* Remove jQuery from mailto-link-tracker ([PR #2542](https://github.com/alphagov/govuk_publishing_components/pull/2542))
* Remove jQuery from static analytics ([PR #2526](https://github.com/alphagov/govuk_publishing_components/pull/2526))
* Remove unused scrolltracker ([PR #2551](https://github.com/alphagov/govuk_publishing_components/pull/2551))
* Tweak metadata component "See all updates" interaction ([PR #2552](https://github.com/alphagov/govuk_publishing_components/pull/2552))
* Change accordion language ([PR #2338](https://github.com/alphagov/govuk_publishing_components/pull/2338))
> Bump gem to 28.1.0

- CHANGELOG.md
- app/views/govuk_publishing_components/components/_metadata.html.erb
Using `#history` is too generic and causing problems as described in this issue https://github.com/alphagov/govuk_publishing_components/issues/600
This changes the href to something less generic. 
To prevent this being a breaking change in `government-frontend`, I opened [this PR](https://github.com/alphagov/government-frontend/pull/2330) which temporarily adds a container with the updated id around the `published-dates` component.  
Once the change in this PR has been rolled out to `government-frontend`, the additional container can be removed, and the id of the component wrapper updated from "history" to "full-publication-update-history".
Opened on behalf of @danacotoran
> Make metadata component "See all updates" link href less generic

- CHANGELOG.md
- app/views/govuk_publishing_components/components/_big_number.html.erb
- app/views/govuk_publishing_components/components/docs/big_number.yml
- spec/components/big_number_spec.rb
Applies the shared helper, which includes standardised `margin_bottom` behaviour, to [the big number component](https://components.publishing.service.gov.uk/component-guide/big_number).
Fixes https://github.com/alphagov/govuk_publishing_components/issues/2479
[Card](https://trello.com/c/u0DGQWQY/724-add-margin-bottom-to-big-number-component-and-apply-to-the-homepage)
> Apply margin bottom helper to big number component

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
* Make metadata component "See all updates" link href less generic ([PR #2562](https://github.com/alphagov/govuk_publishing_components/pull/2562))
* Update feedback component to add "display none" to "maybe" (spam prevention) button ([PR #2568](https://github.com/alphagov/govuk_publishing_components/pull/2568))
* Apply margin bottom helper to big number component ([PR #2566](https://github.com/alphagov/govuk_publishing_components/pull/2566))
> Release 28.2.0

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/analytics/auto-track-event.js
- app/assets/javascripts/govuk_publishing_components/analytics/pii.js
- app/assets/javascripts/govuk_publishing_components/analytics/track-click.js
- app/assets/javascripts/govuk_publishing_components/components/checkboxes.js
- app/assets/javascripts/govuk_publishing_components/components/details.js
- app/assets/javascripts/govuk_publishing_components/lib/govspeak/barchart-enhancement.js
- spec/javascripts/components/details-spec.js
- spec/javascripts/govuk_publishing_components/analytics/auto-track-event.spec.js
- spec/javascripts/govuk_publishing_components/analytics/track-click.spec.js
Remove the remaining bits of jQuery from the components gem. Actually, this doesn't quite remove all the jQuery as `modules.js` still requires it as it expects either a JS node or a jQuery object to be passed to it, but apart from that, I think this now removes all the jQuery.
None.
> Remove almost the last of the miscellaneous jQuery

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/analytics/auto-scroll-tracker.js
Fixes the following problem with the scroll tracker.
- even though the tests pass, when run on an actual page the percentage tracking for 100% sometimes wasn't firing
- I think this was due to a rounding problem when the page height was a fraction rather than a whole number, the position of 100% was always slightly below what could be actually scrolled to
- the solution is to subtract one pixel from each calculated percentage position, which ensures that the page can be scrolled down far enough that the 100% percentage scroll track event can fire
None.
> Fix a bug in the scroll tracker

- CHANGELOG.md
- app/views/govuk_publishing_components/components/feedback/_problem_form.html.erb
- app/views/govuk_publishing_components/components/feedback/_yes_no_banner.html.erb
https://trello.com/c/I0WfBF4P/1011-update-feedback-component-to-resolve-spam-problem
There has been an increase in spam coming from the feedback component from the 6th of Jan, which seems to coincide with the deployment of the new feedback component. https://govuk.zendesk.com/agent/tickets/4834840
**Solution - multiple changes**
- Changed the _Maybe_ button to be a link. Bots that click 'Maybe' will be redirected elsewhere (to the contact page)
- Replaced HTML comments with Ruby comments e.g. `<% # Maybe button exists only to try and capture clicks by bots %>` which may make it harder for more advanced bots to identify elements added for spam bots only
- Added fake (honeypot) input field
- The input field includes a pattern attribute that will fail (and generate HTML validation) for …
> Update feedback component to resolve spam problem

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/_layout-super-navigation-header.scss
- app/views/govuk_publishing_components/components/_layout_super_navigation_header.html.erb
A couple of changes to the super nav header:
- Implement `spans` within the desktop buttons to create a visual pipe effect between buttons on desktop, like we have on mobile
- Change the colour of pipes to the design system `mid-grey`
- nudge the chevrons ever so slightly away from their respective buttons
This is to solve a problem where the desktop buttons appear to have a big gap between them when it's simply the width of the buttons which we need to maintain for the purpose of focus and open states. Solution produced alongside a designer.
[Card](https://trello.com/c/GHzPAVUT/725-desktop-padding-has-left-the-spacing-on-topics-and-gov-activity-inconsistent-timebox)
> Add pipes between buttons on super nav header

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
* Fix a bug in the scroll tracker ([PR #2554](https://github.com/alphagov/govuk_publishing_components/pull/2554))
* Add check to big number to convert plus suffixes to subscript elements ([PR #2570](https://github.com/alphagov/govuk_publishing_components/pull/2570))
* Update feedback component to resolve spam problem ([PR #2574](https://github.com/alphagov/govuk_publishing_components/pull/2574))
=======
* Add pipes between buttons on super nav header ([PR #2575](https://github.com/alphagov/govuk_publishing_components/pull/2575))
> Release 28.3.0

- .github/workflows/visual-regression-tests.yml
- Gemfile.lock
- govuk_publishing_components.gemspec
- package.json
- spec/visual_regression_tests/all_components_spec.rb
- yarn.lock
This upgrades the visual regression test action to take advantage of the new (non-deprecated) Percy CLI and Percy-Capybara gem update.
Replacing `@percy/agent` will also get rid of two (and a half) security alerts that Dependabot has flagged.
The previously used `@percy/exec-action` action is deprecated, and no longer maintained. The `@percy/agent` Node dependency is no longer actively maintained. Both of these are risks, so the workflow should be updated to us the current and maintained `@percy/cli`.
None.
> Upgrade visual regression test action

- app/views/govuk_publishing_components/components/_accordion.html.erb
- app/views/govuk_publishing_components/components/_action_link.html.erb
- app/views/govuk_publishing_components/components/_details.html.erb
- app/views/govuk_publishing_components/components/_heading.html.erb
- app/views/govuk_publishing_components/components/_hint.html.erb
- app/views/govuk_publishing_components/components/_list.html.erb
- app/views/govuk_publishing_components/components/_notice.html.erb
- app/views/govuk_publishing_components/components/_print_link.html.erb
- app/views/govuk_publishing_components/components/_search.html.erb
- app/views/govuk_publishing_components/components/_subscription_links.html.erb
- app/views/govuk_publishing_components/components/_textarea.html.erb
- app/views/govuk_publishing_components/components/_title.html.erb
Remove unneeded brackets around calls to the shared helper. Changes:
- `classes << (shared_helper.get_margin_bottom)`
to
- `classes << shared_helper.get_margin_bottom`
I noticed this a while ago and it's been bugging me.
None.
> Remove unneeded brackets from shared helper calls

- CHANGELOG.md
- app/views/govuk_publishing_components/components/_select.html.erb
- app/views/govuk_publishing_components/components/docs/select.yml
- spec/components/select_spec.rb
Adds a option for a hint to the select component.
- based on the Design system
- an optional hint attribute, with optional hint id
- the aria-describedby attribute of the select points to the hint, if an error is also present the describedby attribute includes both hint and error IDs
During this work I noticed that there's a lot of code in the template and some other refactoring that should be looked at (e.g. the helper file isn't named correctly - it's `select.rb` instead of `select_helper.rb`) but I think I'll do that separately to not over-complicate this PR.
Needed in `smart-answers`.
Trello card: https://trello.com/c/P0YMGgDs/594-add-hint-to-select-component
> Add select component hint

- app/views/govuk_publishing_components/components/feedback/_problem_form.html.erb
https://trello.com/c/H8jJvUxV/1021-feedback-component-server-side-fix-for-spam-problem
Add name attribute to hidden (`giraffe`) - "honeypot" input which is needed to access the form data from params in the controller.
It seems likely that by resolving a number of accessibility issues (https://trello.com/c/MOshcFm1/771-update-feedback-component-to-hide-and-show-content-in-a-more-robust-way) we have inadvertently made it easier for spam bots to access the feedback component forms and client side changes have not resolved the problem. 
Should be deployed before:  https://github.com/alphagov/feedback/pull/1354
> Add name attribute to hidden spam input in feedback component

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/_share-links.scss
- app/views/govuk_publishing_components/components/docs/share_links.yml
Update line-height of share icons text _"Share on email to someone you know"_
Visual correction [noted from this PR](https://github.com/alphagov/govuk_publishing_components/pull/2567)
Before > After
Content update - "Share on email to someone you know" updated to "Email"
> Share icons line-height

- Gemfile.lock
- govuk_publishing_components.gemspec
Pin rails to ~6
Jenkins fails consistently on any current or old branch when testing with ruby 2.7 – the only workaround I could find after a day of investigations is to pin rails to 6 (as 7 seems to be causing the issue), so I'm proposing  this to unblock current work
> Pin rails to 6

- CHANGELOG.md
- app/views/govuk_publishing_components/components/_inset_text.html.erb
- app/views/govuk_publishing_components/components/docs/inset_text.yml
- spec/components/inset_text_spec.rb
Adds options to control the margin top and bottom for the inset text component. Previously both were hard coded as 30px.
Need some more flexibility when using it in smart-answers.
Trello card: https://trello.com/c/LUeE9FAO/641-product-team-template-card
> Add margin top and bottom option to inset text

- spec/javascripts/govuk_publishing_components/FilterComponentsSpec.js
Clear DOM remnants after `FilterComponentsSpec`
We clear the search input after this test suite, but not the generate list of components, leaving a few DOM elements behind which can potentially interfere with other tests.
> Clear DOM remnants after FilterComponentsSpec

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
* Add margin top and margin bottom to inset text ([PR #2616](https://github.com/alphagov/govuk_publishing_components/pull/2616))
* Bump `govuk-frontend` from 3.14.0 to 4.0.0 ([PR #2355](https://github.com/alphagov/govuk_publishing_components/pull/2533))
* Change JavaScript modules from start to init ([PR #2605](https://github.com/alphagov/govuk_publishing_components/pull/2605))
* Share icons line-height ([PR #2602](https://github.com/alphagov/govuk_publishing_components/pull/2602))
* Update conditional reveal ([PR #2602](https://github.com/alphagov/govuk_publishing_components/pull/2612))
* Update Accordion design ([PR #2581](https://github.com/alphagov/govuk_publishing_components/pull/2581))
* Update step-by-step design ([PR #2601](https://github.com/alphagov/govuk_publishing_components/pu …
> Version 28.6.0

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/components/feedback.js
https://trello.com/c/7G5XEeyS/995-feedback-component-issue-error-message-briefly-shown-on-form-submission-and-then-goes-away
On form submission, the **Form error alert / summary component** is briefly shown, before the form is submitted.
1) I think this can be resolved with on* event handler properties and specifically `loadend`. The `loadend` event is fired when a request has completed, whether successfully (on load) or unsuccessfully (on abort or error). https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/loadend_event.
This removes the need to check for individual `readyState` changes (through `onreadystatechange`) which is why the error alert / summary component is currently seen (described below). 
For a successful submission, we can check for a HTTP status code of 200. …
> Hide feedback component error summary on submission

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
Includes:
* Update real user metrics LUX.js to v300 ([PR #2637](https://github.com/alphagov/govuk_publishing_components/pull/2637))
* Remove `header-navigation.js` ([PR #2632](https://github.com/alphagov/govuk_publishing_components/pull/2632))
* Add support for Rails 7; add support for Ruby 3.0 and 3.1; and drop support for Ruby 2.6 ([PR #2642](https://github.com/alphagov/govuk_publishing_components/pull/2642))
> Release v28.7.0

- .github/workflows/ci.yml
- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
This adds a yarn install step to the GitHub Action to release this gem. It then bumps the gem version to 28.7.1.
The release of 28.7.0 was missing the node_modules dependency, which was a consequence of us trying out a GitHub Actions release process for the first time. 
None
> Fix release GitHub Action and release 28.7.1

- CHANGELOG.md
- spec/components/accordion_spec.rb
- spec/features/accordion_spec.rb
Update testing on the accordion
Tests [introduced in this PR](https://github.com/alphagov/govuk_publishing_components/pull/2581) were not actually checking against a rendered page.
Testing run against this URL
http://govuk-publishing-components.dev.gov.uk/accordionexample
> Update accordion tests

- CHANGELOG.md
- app/views/govuk_publishing_components/components/_attachment.html.erb
- app/views/govuk_publishing_components/components/docs/attachment.yml
- lib/govuk_publishing_components/presenters/attachment.rb
- spec/components/attachment_spec.rb
- spec/lib/govuk_publishing_components/presenters/attachment_spec.rb
A small number of organisation are taking part in a pilot scheme to use a new form for users to request accessible formats, rather than sending an email.
If an attachment's alternative_format_contact_email is included in the list of pilot organisation emails, and the provided attachment data includes the attachment ID and the parent content items content ID, then a link to the form is rendered instead of an invitation to email.
To allow various consuming applications to provide minimal extra details (the attachment ID and parental content ID) and present a link to the new, more accessible, form.
[trello](https://trello.com/c/JESTQ5fd/1093-accessible-format-request-add-check-for-organisation-pilot-involvement-to-govukpublishingcomponents)
> Allow attachments to display a link to request accessible format form for pilot orgs

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/analytics/page-content.js
- spec/javascripts/govuk_publishing_components/analytics/page-content.spec.js
Improve the analytics custom dimensions code.
- more specifically, the PageContent code called from custom dimensions to supply custom dimensions 26 and 27
- on mainstream browse pages, they should report not only the number of sections and total number of links in the two right hand columns (if visible) but also the left hand column, if that is the only column
- also the code to identify the application and page as collections and browse assumed the meta tag content was 'collections', which is true on live but in Dev for some reason it was 'Collections', which made testing this difficult, so have lowercased that identifier to make it more certain
- also added tests for these two new columns
We're fixing the analytics on the browse page so we can understand it better before making any …
> Improve custom dimensions code

- CHANGELOG.md
- Gemfile.lock
- app/models/govuk_publishing_components/component_docs.rb
- govuk_publishing_components.gemspec
- lib/govuk_publishing_components/version.rb
- spec/components/all_components_spec.rb
This PR drops the gem's dependency on `psych >= 4`.
It was breaking downstream applications that had come to implicitly depend on the Psych version that [comes with the Ruby standard library](https://stdgems.org/psych/). This isn't an unreasonable assumption for applications to make, and this gem's explicit dependence on Psych 4 meant that applications expecting to have Psych 3 were tripping over the breaking API changes between the two versions.
For example, see alphagov/content-publisher#2464.
None.
> Drop Psych 4 dependency

- app/assets/stylesheets/govuk_publishing_components/components/_document-list.scss
Increases the font size & updates to [secondary colour](https://design-system.service.gov.uk/styles/colour/) on the [`document_list` component](https://components-gem-pr-2650.herokuapp.com/component-guide/document_list)
As part of on-going work to improve accessibility
https://components-gem-pr-2652.herokuapp.com/component-guide/document_list
> Increase font-size on document list

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/_all_components.scss
- app/assets/stylesheets/govuk_publishing_components/_all_components_print.scss
- app/assets/stylesheets/govuk_publishing_components/components/_cards.scss
- app/assets/stylesheets/govuk_publishing_components/components/print/_cards.scss
- app/views/govuk_publishing_components/components/_cards.html.erb
- app/views/govuk_publishing_components/components/docs/cards.yml
- spec/components/cards_spec.rb
The Find & View team created a local cards component for the homepage in [`frontend`](https://github.com/alphagov/frontend).
The component renders cards, each with a link and a description, as an unordered list element and visually presents it as a grid. It doesn't use the [GOV.UK Design System grid](https://design-system.service.gov.uk/styles/layout/#grid-system) but sets its own so that it can separately target desktop, tablet and mobile columns.
This PR:
- Ports the code over from  `frontend` 
- Updates markup to follow BEM conventions
- Adds print styles
- Adds automated template tests
- Allow the grid to be overridden to use two columns on desktop (this variant is currently used in the government activity sections of the homepage)
- Allows heading and subheading levels to be …
> Add cards component

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
* Add 'Invasion of Ukraine' CTA to pages tagged to the topical event ([PR #2657](https://github.com/alphagov/govuk_publishing_components/pull/2657))
> Release 28.9.0

- CHANGELOG.md
- config/locales/en.yml
- Update the list of popular links (to include Invasion of Ukraine) on the super navigation header component, so that it matches the list of popular links on the homepage. See https://github.com/alphagov/frontend/pull/3155
- Adding Invasion of Ukraine to popular links is a request from content and SMT colleagues.
> Update popular links

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
* Update the list of popular links in the super navigation header ([https://github.com/alphagov/govuk_publishing_components/pull/2660](https://github.com/alphagov/govuk_publishing_components/pull/2660))
* Remove Brexit call to action from contextual sidebar ([https://github.com/alphagov/govuk_publishing_components/pull/2518](https://github.com/alphagov/govuk_publishing_components/pull/2518))
> Release 28.9.1

- package.json
Trello: https://trello.com/c/21VMx1NV/264-migrate-apps-to-use-jasmine-browser-runner
In the time since PR 2625 [1] was merged we've learnt that the webdrivers
gem is going to cause a problem for the GOV.UK development environment,
govuk-docker, when running on M1 macs.
We have decided to change tact and focus on installing a chromedriver on
the underlying machine rather than using webdrivers as a source of this
software [2] [3]. This seems extra pragmatic now that we have Javascript
dependencies also using chromedriver.
A step towards this is removing this intertwining of Ruby webdriver
dependency from this repo's yarn tests.
The effect merging this will have is:
- The build will continue to pass in GitHub Actions CI - chromedriver is
installed
- Users running jasmine tests in …
> Don't use webdrivers for yarn chromedriver

- CHANGELOG.md
- app/views/govuk_publishing_components/components/_summary_list.html.erb
- app/views/govuk_publishing_components/components/docs/summary_list.yml
- spec/components/summary_list_spec.rb
Update [`summary_list`](https://components.publishing.service.gov.uk/component-guide/summary_list) - adds a modifier class of `--no-actions` to empty rows only when there is a mix of rows with and without actions
[Prompted from 4.0 update](https://github.com/alphagov/govuk-frontend/blob/main/CHANGELOG.md#update-the-html-for-summary-lists), some rows within `summary_list` have an "action" that include links like "`change`, `edit`"  
Only applies 
> if you have a mix of rows with and without actions, add the govuk-summary-list__row--no-actions modifier class to the rows without actions
Inline with Design System / [GOVUK Frontend 4.0 update](https://github.com/alphagov/govuk_publishing_components/pull/2533)
> If you're not using Nunjucks macros, do not include an empty <span …
> Update summary list

- CHANGELOG.md
- app/views/govuk_publishing_components/components/_input.html.erb
- app/views/govuk_publishing_components/components/docs/input.yml
- spec/components/input_spec.rb
Update `inputs` to include `spellcheck=""false"` by default - allows the option to be changed to `true` when required
Inline with [GOVUK Design System Guidance](https://design-system.service.gov.uk/patterns/email-addresses/), noted as part of accessible format request epic
Many inputs like `email` and `name` have no value being spellchecked due to their nature.  However other fields do, allows this option to be manually passed if required.
NA
Docs have been updated, code formatting added + `autocomplete` has been moved to be grouped next to email as this is highly recommended to be used in conjunction
> Add spellcheck to input 

- .github/workflows/ci.yml
Update the `ci.yml` gem publishing workflow if statement to work on the `main` branch, rather than being on the `master` branch.
We want to rename the `master` branch with `main` to match the other repositories in the alphagov organisation.
Once this has been merged in this repo can then [rename the `master` branch][1] to `main`, and then publish the gem from the `main` branch.
None.
[1]: https://github.com/github/renaming#renaming-existing-branches
> Update RubyGems publishing to use `main` branch

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/_previous-and-next-navigation.scss
- app/assets/stylesheets/govuk_publishing_components/components/govspeak/_warning-callout.scss
Increase `font-size` on [`previous_and_next_navigation`](http://govuk-publishing-components.dev.gov.uk//component-guide/previous_and_next_navigation/preview)
As part of on-going work to improve accessibility and wider upcoming DS `font-size` increase work
Related PRs
https://github.com/alphagov/govuk_publishing_components/pull/2652
https://github.com/alphagov/govuk_publishing_components/pull/2650
Small adjustment on warning / important icon - rendering size was not correct, pixel off meant it was blurry
> Increase font-size of previous and next navigation

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/analytics.js
- app/assets/javascripts/govuk_publishing_components/analytics/cross-domain-tracking.js
- spec/javascripts/govuk_publishing_components/analytics/analytics.spec.js
- spec/javascripts/govuk_publishing_components/analytics/cross-domain-tracking.spec.js
- spec/javascripts/govuk_publishing_components/analytics/external-link-tracker.spec.js
- spec/javascripts/govuk_publishing_components/analytics/google-analytics-universal-tracker.spec.js
**NOTE: a new version of the gem containing this PR cannot be deployed to `static` unless it is part of [this PR]() to remove the same code**
Migrates the [cross domain tracking script](https://github.com/alphagov/static/blob/main/app/assets/javascripts/modules/cross-domain-tracking.js) and [its associated test](https://github.com/alphagov/static/blob/main/spec/javascripts/modules/cross-domain-tracking.spec.js) from `static`, and adds it to the analytics code.
Also changes some of the existing analytics test files to create a dummy `setDimension` object if one doesn't already exist. I was getting race condition errors running the tests until these lines were added - I'm not exactly sure why this migration was causing those errors, but there's a long history of the analytics tests …
> Migrate cross domain tracking script from static

- CHANGELOG.md
- app/views/govuk_publishing_components/components/_cards.html.erb
- app/views/govuk_publishing_components/components/docs/cards.yml
- app/views/govuk_publishing_components/components/docs/list.yml
- spec/components/cards_spec.rb
Update [`cards` component](http://govuk-publishing-components.dev.gov.uk/component-guide/cards/) tracking to be more flexible so values can be passed more easily. 
Closes [2565](https://github.com/alphagov/govuk_publishing_components/issues/2656)
NA (language adjustment flagged on visual regression)
Related PR - https://github.com/alphagov/collections/pull/2673
Part of wider epic - "Build new page templates for GOV.UK Browse"
Small adjustment to [`list`](https://components.publishing.service.gov.uk/component-guide/list) docs.
Related PR: small adjustment to [`lead_paragraph`](https://github.com/alphagov/govuk_publishing_components/pull/2681) prompted during review
>  Update card tracking

- CHANGELOG.md
- app/views/govuk_publishing_components/components/docs/attachment.yml
- lib/govuk_publishing_components/presenters/attachment.rb
- spec/components/attachment_spec.rb
- spec/lib/govuk_publishing_components/presenters/attachment_spec.rb
The pilot scheme is being paused so we are temporarily removing the participating emails from the attachment component.
This will prevent links to the accessible format request form being displayed on inaccessible attachments, and instead display the mail_to link.
> Remove emails from accessible format request pilot

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/rum-loader.js
- app/views/govuk_publishing_components/components/_layout_for_public.html.erb
This removes the sole use of an embedded ruby file for JavaScript file generation. It replaces this with the variable being embedded as a data attribute that is retrieved at runtime.
Mixing Ruby and JavaScript can cause a variety of challenges and limits the portability of the script. This script has been changed to instead use a data attribute on the script tag rather than needing embedded Ruby.
The immediate problem I had to resolve with this is that this didn't work properly with Sprockets 4. However as mixing Ruby and JavaScript is an undesirable approach I felt it best to decouple this.
None
> Don't use embedded Ruby for rum-loader

- CHANGELOG.md
- Gemfile.lock
- Rakefile
- app/assets/config/govuk_publishing_components_manifest.js
- app/assets/config/manifest.js
- config/initializers/assets.rb
- govuk_publishing_components.gemspec
- spec/dummy/Rakefile
- spec/dummy/app/assets/config/manifest.js
- spec/dummy/config/initializers/assets.rb
This updates the asset configuration of this gem so that applications that depend on it can upgrade to Sprockets 4, but does not force them. It also updates the Gemfile.lock and the dummy so that the application equivalent of this is running on Sprockets 4. It also uses a Sprockets manifest approach to configuring the files for pre-compiling.
This release will support version 3 and 4 of Sprockets but we may find that we need to eventually pin this as needing Sprockets 4 as we are losing implicit testing of Sprockets 3 here, and in time this compatibility may just break. I didn't make that change now as I didn't want to push out a release that required immediate manual effort from developers to upgrade to, but a future step could be to deprecate Sprockets 3 usage.
Most GOV.UK apps that …
> Provide compatibility with Sprockets 4

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/_layout-super-navigation-header.scss
Add border to bottom of search icon on the [`layout_super_navigation_header`](https://components.publishing.service.gov.uk/component-guide/layout_super_navigation_header) when JS is disabled
> The blue search toggle button has a hairline border at the bottom/ When JavaScript is turned off, the search link should be visually identical - but it lacks the dark bottom border
Closes https://github.com/alphagov/govuk_publishing_components/issues/2674
> Add border to search icon when JS disabled

- CHANGELOG.md
- lib/govuk_publishing_components/presenters/attachment.rb
Add HMRC's accessible format email to attachment's list of department emails taking part in the accessible format request pilot.
[trello](https://trello.com/c/7vyvANlE/1172-accessible-format-request-add-links-to-form-for-hmrc-documents-ready-for-user-testing)
> Add HMRC to accessible format request pilot

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
Includes:
* Remove "priority breadcrumbs" ([#2666](https://github.com/alphagov/govuk_publishing_components/pull/2666))
This removes the super/priority breadcrumb from contextual navigation. It's not a breaking change because standard breadcrumbs replace them.
> Release 29.1.0

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/analytics/page-content.js
- app/views/govuk_publishing_components/components/_cards.html.erb
Add tracking `dimension26` and `dimension32` for tracking sections and number of links
New [variant browse pages](https://github.com/alphagov/collections/pull/2673) have been designed and built that are based in `collections` need analytics added for Browse Level 0 & 1.
NA
Passes the number of sections and links, for ref - 
This is being added as part of an AB test.  Depending on the outcome and changes this may need to be either a) removed b) altered
> Add variant tracking to card component

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/analytics/analytics.js
- app/assets/javascripts/govuk_publishing_components/components/accordion.js
- app/assets/stylesheets/govuk_publishing_components/components/_accordion.scss
- app/views/govuk_publishing_components/components/_accordion.html.erb
- app/views/govuk_publishing_components/components/docs/accordion.yml
- docs/analytics/analytics.md
Add click event tracking for [Accordion's](https://components.publishing.service.gov.uk/component-guide/accordion) "Show all sections" button behind a feature flag.
Also, add click event tracking for each section, also behind a feature flag.
For PA's to track when button is interacted with for new GOVUK Explore, Browse Pages AB variant. Replicates bespoke functionality found on `/coronavirus`.
Example capture on `collections`
https://user-images.githubusercontent.com/71266765/160830285-f25dcd8a-47a8-4c74-8b88-8129cdd8c8a9.mov
https://user-images.githubusercontent.com/71266765/160697806-59bd56b0-5b4b-4ffd-a014-82e3877a6cea.mov
Issue raised to capture tracking testing that is missing from this PR.
https://github.com/alphagov/govuk_publishing_components/issues/2694
Related PRs …
> Add tracking on the accordion

- CHANGELOG.md
- lib/govuk_publishing_components/presenters/attachment.rb
Remove HMRC's alternative format request email address from the list of organisations taking part in the pilot scheme.
Following user research the pilot scheme is now closed for a short period.
[trello](https://trello.com/c/nHsb8wlv/1177-accessible-format-request-turn-off-the-pilot-again)
> Remove HMRC from accessible format request pilot in attachment

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
Release 29.2.0
* Remove HMRC email from attachment for accessible format request pilot ([PR #2710](https://github.com/alphagov/govuk_publishing_components/pull/2710))
* Remove the last traces of jQuery ([PR #2702](https://github.com/alphagov/govuk_publishing_components/pull/2702))
* Add tracking on the accordion ([#2693](https://github.com/alphagov/govuk_publishing_components/pull/2693))
> Release 29.2.0

- CHANGELOG.md
- lib/govuk_publishing_components/presenters/public_layout_helper.rb
Trello: https://trello.com/c/eb6MoA95
Remove the config for the Coronavirus and Brexit footers
As we move to endemic and Coronavirus team winds down, we are removing Coronavirus navigation/ product debt.
This gem needs to be updated in [static](https://github.com/alphagov/static) for the changes to the footer in the layout to take effect.
> Remove Coronavirus and Brexit footers

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
Includes
- https://github.com/alphagov/govuk_publishing_components/pull/2685
This removes the coronavirus header and footer
> Release version 29.3.0

- CHANGELOG.md
- lib/govuk_publishing_components/presenters/meta_tags.rb
- spec/components/meta_tags_spec.rb
The documents types listed below will now include the `<meta name="govuk:static-analytics:strip-postcodes" content="true">` meta tag.
- transaction
- local_transaction
- place
- special_route
This will ensure that postcodes strings are replaced with "[postcode]" in any pages with these document types.
To stop personal postcode data from being sent to Google Analytics.
I deployed the changes to integration and tested the pages below using the [Google Analytics Debugger](https://chrome.google.com/webstore/detail/google-analytics-debugger/jnkmfdileelhofjcijamephohjechhna?hl=en) browser extension for Google Chrome, the differences in the "location" being sent to GA are shown below.
| Integration | Live |
| ----------- | ----------- |
| …
> Strip postcodes from more document types in meta_tags component

- CHANGELOG.md
- config/locales/en.yml
Update the list of popular links (to include Moving to the the UK from Ukraine) on the super navigation header component, so that it matches the list of popular links on the homepage. See https://github.com/alphagov/frontend/pull/3196
Adding Moving to the UK from Ukraine to popular links is a request from content and SMT colleagues.
> Update popular links in the super navigation headers

- CHANGELOG.md
Add that https://github.com/alphagov/govuk_publishing_components/pull/2722 was merged into main to the changelog.
This was not included in the original PR. My apologies!
> update changelog with merge of #2722

- CHANGELOG.md
- lib/govuk_publishing_components/presenters/attachment.rb
This PR adds DWP, DfE and DVSA accessible format request email addresses to the list of emails taking part in the pilot
> Add DWP, DfE and DVSA to accessible format request pilot email list

- docs/real-user-metrics.md
Beacon mode was removed from LUX in version 300 [1]
[1]: https://support.speedcurve.com/changelog/rum-update-luxjs-v300
> Replace LUX beacon mode documenation

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
Release 29.6.0
* Updated link for the Ukraine Invasion Call To Action #2739 ([PR #2739](https://github.com/alphagov/govuk_publishing_components/pull/2739))
* Use locale files to generate header links in public_layout instead of constant in public_layout_helper #2719 ([PR #2719](https://github.com/alphagov/govuk_publishing_components/pull/2719))
> Release 29.6.0

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/lib/govspeak/magna-charta.js
- spec/javascripts/govuk_publishing_components/lib/govspeak/magna-charta-spec.js
Improve the error handling for stacked charts when the table source HTML does not include the required table header elements.
Without the error handling, not only will the Chart will not be rendered, but any remaining JavaScript will not be run after the error, leading to further issues with other components in the bundled JS file.
| **Before**  | **After** |
| ----------- | ----------- |
| If the table header elements are not present, the chart is not rendered, however the "toggleLink" button is still displayed with misleading text | If the table header elements are not present, the chart and toggleLink button are not rendered |
| <img width="852" alt="Screenshot 2022-04-14 at 09 55 27" src="https://user-images.githubusercontent.com/28779939/163350971-7669c3b2-5b32-4aaa-9ac9-c3d971d66cb6. …
> Fix JS bug in MagnaCharta for stacked charts

- CHANGELOG.md
- config/locales/en.yml
Remove Coronavirus link from the menu bar.
This change was requested by the Covid team.
> remove coronavirus topic from menu bar

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/_layout-super-navigation-header.scss
Updates the `columns` mixin with the updated number of items in the list of topics in the navigation header.
An [item was removed from the topics listed in the navigation header][removed], which requires the CSS grid layout to be rejigged to avoid lopsided columns.
[removed]: https://github.com/alphagov/govuk_publishing_components/pull/2745
> Realign list of topics in navigation header

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
Release 29.7.0
* Auditing enhancements ([PR #2428](https://github.com/alphagov/govuk_publishing_components/pull/2428))
* Fix JS bug in MagnaCharta for stacked charts ([PR #2731](https://github.com/alphagov/govuk_publishing_components/pull/2731))
* Remove coronavirus topic from menu bar ([PR #2745](https://github.com/alphagov/govuk_publishing_components/pull/2745))
* Realign list of topics in navigation header ([PR #2750](https://github.com/alphagov/govuk_publishing_components/pull/2750))
> Release 29.7.0

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/_cards.scss
- app/views/govuk_publishing_components/components/_cards.html.erb
Add a wrapper to the content of the card component.
When testing for how usable the collections pages were with a magnifier tool, I noticed that there was a difference to how the cards were implemented in the govuk_publishing_components gem to how they were implemented on GOV.UK itself. The cards on GOV.UK have a wrapper containing the sub-heading and description so that the area of the card that acts as a link is only the portion of the card containing text and not the entire area of the card. This means there is a space between each card above and below on the grid. In the govuk_publishing_components implementation of the card, there is no wrapper which means the entire card acts as a link and so there is no spacing above and blow each card on the grid. This could potentially make the …
> add wrapper to the component card to ensure link spacing

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/analytics/explicit-cross-domain-links.js
- app/assets/javascripts/govuk_publishing_components/modules.js
- spec/javascripts/govuk_publishing_components/analytics/explicit-cross-domain-links.spec.js
It was noted that cross-domain linking between the account and the DI domain stopped working around 25th March.
Around that time, a lot of good work was done around removing jQuery from GOVUK. As part of that work there were some [changes](https://github.com/alphagov/govuk_publishing_components/commit/613cfcc8f71c96d8099bf28dd51231f48bbec3b9) to the script which starts the modules in `govuk_publishing_components` where support for legacy modules was removed.
The explicit-cross-domain-links script was still using `start()` to initialise so it stopped working around that time. This changes it to `init()`.
To test: on this page https://www.gov.uk/email/subscriptions/single-page/new?topic_id=keeping-a-pet-pig-or-micropig, when you click **Create a GOV.UK account or sign in**, the URL of the …
> Update cross domain linking script to use init

- CHANGELOG.md
I accidentally left PR #2747 under `29.7.0` when it should be under
`Unreleased` (rebase gone wrong)
> Correct mistake in CHANGELOG.md

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/analytics-ga4.js
- app/assets/javascripts/govuk_publishing_components/analytics-ga4/gtm-click-tracking.js
- spec/javascripts/govuk_publishing_components/analytics-ga4/gtm-click-tracking.spec.js
Add a generic script for pushing data to the dataLayer for Google Tag Manager. This is an initial approach that may change over time.
- adds generic Google Tag Manager 'click to track' script, that depends upon there being a dataLayer to work
- dataLayer is currently only initialised using the GTM component and environment variables, so should only work on integration
- the analytics-ga4 script is currently not included anywhere, this will be included conditionally in static based on the same environment variables, to avoid code being deployed to live
Right now we're concerned with not doing anything that adds any code to the public site, so these scripts will only be included in static in development environments and on integration.
The script also includes one approach to dealing with …
> Add GTM analytics click tracking

- app/assets/javascripts/govuk_publishing_components/components/accordion.js
Spotted a `console.log` in the accordion.js, removing.
Not needed in production - looks like it was added for debug and accidentally left in.
None.
> Remove console.log

- CHANGELOG.md
- lib/govuk_publishing_components/presenters/attachment_helper.rb
DWP are being removed from the accessible format request pilot scheme.
[trello](https://trello.com/c/RTiwn1cB/1251-make-live-after-12-april-330pm-remove-dwp-from-the-request-accessible-format-pilot)
> Remove DWP email from accessible format request pilot

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
Release 29.8.0
* Add GTM analytics click tracking (https://github.com/alphagov/govuk_publishing_components/pull/2760)
* Add wrapper to the component card to ensure link spacing (https://github.com/alphagov/govuk_publishing_components/pull/2753)
* Add new logic for counting links/sections on a second level browse page on page view #2733 (https://github.com/alphagov/govuk_publishing_components/pull/2733)
* Update cross domain linking script to use init (https://github.com/alphagov/govuk_publishing_components/pull/2747)
* Remove DWP email from attachment accessible format request pilot(https://github.com/alphagov/govuk_publishing_components/pull/2764)
* Add HTTP protocol measurement to RUM (https://github.com/alphagov/govuk_publishing_components/pull/2769)
> Release 29.8.0

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/vendor/lux/lux-measurer.js
Fix the HTTP protocol reporting into Speedcurve RUM as Safari was not reporting any data.
This used `DOMContentLoaded` to make sure that `performance.getEntriesByType()` was not undefined. However, this was not reporting anything in Safari. It appears that the event listener was being added after the event was fired.
Checking the `readyState` of the document lets us see whether the document is loading or ready - and then, depending on the state, either the `load` event has a listener attached or the measurement is done immediately.
Adds extra check to make sure that `performance.getEntriesByType` is not undefined - so can be used without throwing an error.
Monitoring the type of HTTP connection that a user's using will allow us to see how the different HTTP protocols affect performance - …
> Fix HTTP protocol reporting in Safari

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
* Update LUX to v301 ([PR #2773](https://github.com/alphagov/govuk_publishing_components/pull/2773))
* Fix http protocol reporting in Safari ([PR #2781](https://github.com/alphagov/govuk_publishing_components/pull/2781))
> Release 29.9.0

- CHANGELOG.md
- app/views/govuk_publishing_components/components/_layout_footer.html.erb
- lib/govuk_publishing_components/presenters/public_layout_helper.rb
- spec/lib/govuk_publishing_components/components/public_layout_helper_spec.rb
Add new data-attributes to links in the footer. For most links in the footer, this involves a new helper method which works out what data attributes a link should have and then adds it to the hash that is used to generate each link. The only exception to this is the copyright and license links. As they have html that is hardcoded in the locale file, they have hardcoded data-tracking variables in their parent element.
The new data-attributes added to the links in the footer allow the region of the footer to be more easily determined from analytics themselves rather than having to check on the template. The attributes are in the following format and are on all links in the footer (including the copyright links). 
```
data-track-category: footerClicked
// this depends on where in the footer …
```
> Tracking changes for the footer

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/analytics/page-content.js
- spec/javascripts/govuk_publishing_components/analytics/page-content.spec.js
Update the conditional statement in `page-content.js `which checks to see if a page is a new browse page. Change logic of counting sections in Browse Level 2 templates to count the number of sections instead of returning the value '1'.
The values of metatags for new browse pages were changed which made previously written conditional statements in `page-content.js `always return false. The conditional statements have been updated to use the new metatag values so that now counting of sections/links should work on all browse page levels.
Initially the logic for counting sections on Browse Level 2 templates assumed that default pages consisted of 1 section. This is sometimes not the case (there can be related topics) so the logic has been changed to count the number of sections on the page. …
> Update analytics logic for new browse page metatags

- CHANGELOG.md
- app/controllers/govuk_publishing_components/audit_controller.rb
- app/controllers/govuk_publishing_components/component_guide_controller.rb
- app/models/govuk_publishing_components/audit_comparer.rb
- app/views/govuk_publishing_components/audit/_applications.html.erb
- app/views/govuk_publishing_components/component_guide/index.html.erb
- docs/auditing.md
- spec/component_guide/audit_comparer_spec.rb
If present, use data from `static` to make warnings about missing assets in applications more accurate. Specifically:
- if `static` includes an asset and the application doesn't, no longer raise a warning (asset not actually missing)
- if `static` includes an asset and the application does as well, raise a new warning (asset is duplicated)
We only need to do this for certain applications, specifically the ones that use `static` (`static` is included in the auditing as well, so obviously we need to not compare `static` with itself).
The warnings in the auditing sometimes contained false positives, which made the warnings generally less reliable. Once we've made the auditing more reliable we can start to, well, rely on it more.
The result of this work is that most of the applications in the …
> Make auditing check static for missing assets

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/govspeak/_attachment.scss
Adding CSS for SVG attachment thumbnail icons now being used by Whitehall.
We've added some SVG icons to Whitehall in alphagov/whitehall#6550 as a transitional step towards using the attachment components. However, because they're not rendered by whitehall itself, the CSS to style these icons needs to be available in other frontend apps, so this would appear to be the correct place for it (although adding to the legacy Whitehall-supporting css is obviously not ideal).
This is actually trying to remain close to the style of the attachment component, without depending on the component 
The original icon that we're replacing:
The icon properly styled, when the CSS in this PR is applied:
The icon improperly styled:
> Add SVG thumbnail styles for Whitehall

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/_layout-super-navigation-header.scss
Small set of design tweaks for the global navbar. These include
- reducing the height of the border (pipes)
- changing the colour of the chevron on hover so that it is the same colour as the text and the pipes
- adding a thin light grey border to the bottom of the menu background
Requested by the Find and View Explore Team. Small changes to bring navbar more in line with the designs.
Reviewed with Gracie and design changes here approved.
[Relevant Trello Card](https://trello.com/c/H6UF1kC6/882-small-amends-to-the-sitewide-menu)
> Small amends to sitewide menu

- CHANGELOG.md
- app/views/govuk_publishing_components/components/_character_count.html.erb
- app/views/govuk_publishing_components/components/_date_input.html.erb
- app/views/govuk_publishing_components/components/_input.html.erb
- spec/components/input_spec.rb
Make some minor changes to our component markup following the release of `govuk-frontend` 4.1.0, specifically:
- remove 'aria-live' attribute from character count component (not needed anymore)
- remove 'pattern' attribute from date input component (not needed anymore)
We don't import markup for components from `govuk-frontend`, we've hard coded it into `.erb` templates and heavily modified it. This means that when we get a new release of `govuk-frontend` we need to check the release notes to see if anything has changed. For this release only two minor things have changed.
- https://github.com/alphagov/govuk-frontend/releases/tag/v4.1.0
- https://github.com/alphagov/govuk_publishing_components/blob/main/docs/upgrade-govuk-frontend.md
None.
> GOVUK Frontend 4.1.0 updates

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/analytics-ga4/gtm-click-tracking.js
- app/assets/javascripts/govuk_publishing_components/components/accordion.js
- app/views/govuk_publishing_components/components/_accordion.html.erb
- app/views/govuk_publishing_components/components/docs/accordion.yml
- docs/analytics-gtm/gtm-click-tracking.md
- spec/components/accordion_spec.rb
- spec/javascripts/components/accordion-spec.js
- spec/javascripts/govuk_publishing_components/analytics-ga4/gtm-click-tracking.spec.js
Extend the GTM click tracking, specifically:
- if an element contained an expanding element (indicated by the aria-expanded attribute) information about that was included in the dataLayer push
- this now checks if the clicked element itself has that attribute
- will be used on the accordion show/hide all element
Also updates the accordion component:
- allows data attributes to be added to the show/hide all link
- this means we can trigger the GTM click tracking on this element and include the expanded/collapsed state, all without any custom analytics code in the component
We want to track the state of expanding/collapsing elements on user interaction. At the moment there's some custom code that does this, but we should be able to do it by passing data attributes and having the overall …
> Extend GTM analytics click tracking

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/_all_components_print.scss
- app/assets/stylesheets/govuk_publishing_components/components/print/_organisation-logo.scss
Sets a width for the organisation logo component when being printed so that it is not excessively large if image used for organisation logo is a large image. This resolves issue https://github.com/alphagov/govuk_publishing_components/issues/2374.
When printing a page with the organisation logo component, there was no width set on the image so it would be printed at the size of the image itself. This meant if the image was large then the image would appear much larger than it had on the page itself. A potential fix would be to hide the organisation logo when printing but as the organisation logo is the only indication on the page when printed that the page is originating from an organisation I thought it was important to retain it.
N.B. this is print view only
> Fix print styles for organisation logos

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
* Extend GTM analytics click tracking ([PR #2786](https://github.com/alphagov/govuk_publishing_components/pull/2786))
* GOVUK Frontend 4.1.0 updates ([PR #2794](https://github.com/alphagov/govuk_publishing_components/pull/2794))
* Fix print styles for organisation logos ([PR #2751](https://github.com/alphagov/govuk_publishing_components/pull/2751))
* Change "governmentActivityLink" to "governmentactivityLink" ([PR #2798](https://github.com/alphagov/govuk_publishing_components/pull/2798))
> Version 29.11.0

- docs/adr/0001-record-architecture-decisions.md
- docs/adr/0002-google-analytics-4-tracking-and-code-location.md
We should document the design decisions related to this project.
An [Architecture Design Record](https://cognitect.com/blog/2011/11/15/documenting-architecture-decisions) is an ideal - and structured - way to do this and is also the GOV.UK preferred approach.
So that others know why a particular decision was taken, what options were also considered and why they were rejected.
None
[Trello](https://trello.com/c/Z59PS5na/44-create-an-adr-to-document-the-decision-around-analytics-code-location)
> Add Architecture Design Records 

- CHANGELOG.md
- app/views/govuk_publishing_components/components/_layout_footer.html.erb
Remove gem-track-click from parent container of layout_footer. Add gem-track-click to the specific elements that contain links and also add 'data-track-links-only'.
Previously gem-track-click was added to the parent element of layout_footer. As we need to add seperate gem-track-clicks to the copyright links that are generated from the locale files in order to track them, this resulted in double events when the copyright links were clicked. Also added data-track-links-only because when non links were being clicked it was triggering a tracked click event.
> Add gem-track-click to specific sections of layout_footer

- app/assets/javascripts/govuk_publishing_components/vendor/lux/lux-measurer.js
Fixes #2804 by adding an extra check to make sure that a variable exists before seeing what its length is.
Also removes an unnecessary use of `JSON.parse` and  `JSON.stringify`.
We'd like to be able to use `window.performance` in IE without it throwing an error. Whilst the specific `PerformanceResourceTiming.nextHopProtocol` isn't supported in IE[^1], some parts of `PerformanceResourceTiming` are[^2] - so an extra check is needed before querying `nextHopProtocol`'s length.
The use of `JSON.parse(JSON.stringify())` was to see what the contents of the performance object were at a specific point in time whilst debugging  - this isn't required for the production code.
None.
This needs a couple of steps to make sure that it's working.
1. Visit the public template page locally …
> Fix LUX error in IE 11

- .github/workflows/visual-regression-tests.yml
- package.json
- yarn.lock
Updates the Percy CLI dependency to the latest available version.
This is an internal change that doesn't affect any component or part of a component's API.
This is a change to a GitHub Action - and so can't be tested locally (to the best of knowledge anyways). The workflow's successful competion (https://github.com/alphagov/govuk_publishing_components/runs/6915614376?check_suite_focus=true) should verify that this dependency update has worked.
Percy is the visual regression testing tool that is used to compare screenshots for the components in this repo. The Percy CLI is a dependency and isn't bumped by dependabot - so needs a manual upgrade by running `yarn add @percy/cli`.
None.
> Upgrade Percy

- CHANGELOG.md
- app/views/govuk_publishing_components/components/_layout_super_navigation_header.html.erb
Improve the accessibility of the main menu by changing `<p>` elements to `<hX>` elements. [Trello](https://trello.com/c/W317oTLq/1067-fix-menubar-items-that-use-p-tags-in-titles-and-not-heading-elements)
Paragraph elements aren't announced by screen-readers in the same way as heading elements. This can hinder screen-reader users from properly navigating the page. This small fix helps those users by triggering a heading announcement.
Not applicable
> Change menubar P elements to use H elements

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/components/accordion.js
- app/views/govuk_publishing_components/components/docs/accordion.yml
The function that fires an analytics event when an accordion is opened or closed can now be passed optional tracking options. This means custom dimensions can now be specified when a user clicks on an accordion section.
Similar to how link clicks can also append custom dimensions to the analytics event, a request was made that accordion open and close should also include the position (index) of the accordion on the page when clicked. This change means this dimension and any others can be easily added to the accordion open/close event.
[Relevant Trello Card](https://trello.com/c/1Y6WwRZh/1075-add-tracking-for-position-of-accordion-section-on-new-browse-level-2-curated-topics)
> Add Options to Accordion Section Tracking

- docs/analytics/track-click.md
Improve the documentation for the `gem-track-click` module. Specifically add headings for each example, clarify some of the example markup, and tweak some of the descriptions.
Mainly because I keep needing to refer to this doc and there were no headings for the specific examples that I could give a direct link to.
None.
> Improve track click documentation

- app/assets/javascripts/govuk_publishing_components/components/accordion.js
- app/controllers/govuk_publishing_components/audit_controller.rb
- app/models/govuk_publishing_components/audit_comparer.rb
Remove manuals frontend from audits, note that manuals-frontend features are now for government-frontend
Manuals-frontend now retired
https://trello.com/c/OtjBZRjL/1131-manuals-deprecate-manuals-frontend
> Remove references to manuals-frontend

- app/views/govuk_publishing_components/components/_layout_super_navigation_header.html.erb
Remove `data-module="gem-track-click"` from each of the links in the footer, add `data-module="gem-track-click"` to the parent header component instead. 
Click tracking can be initialised on a parent component instead of each individual component. The previous implementation meant that for each clickable link in the header the module for tracking links was being initialised unnecessarily. Using this alternative approach has benefits such as reducing the number of event listeners by 31 and decreasing memory usage. 
Fixes https://github.com/alphagov/govuk_publishing_components/issues/2819
> Remove gem-track-click for individual links, use in header instead

- CHANGELOG.md
- app/views/govuk_publishing_components/components/_attachment.html.erb
- app/views/govuk_publishing_components/components/docs/attachment.yml
- lib/govuk_publishing_components/presenters/attachment_helper.rb
- spec/components/attachment_spec.rb
- spec/lib/govuk_publishing_components/presenters/attachment_spec.rb
Support for the Request Accessible Format form is being removed.
All participating departments have pulled out of the pilot, so removing code makes sense while we rethink. It may be reinstated from the git history, or if the pilot does not recur, we keep the code tidy by removing it.
No visual changes, but With Accessible Format Request form option has been removed from items rendered for visual regression check.
https://trello.com/c/iZEzpeFy/1340-remove-dfe-from-the-accessible-format-pilot
> Remove code for accessible format request pilot.

- CHANGELOG.md
- app/views/govuk_publishing_components/components/_error_alert.html.erb
- app/views/govuk_publishing_components/components/docs/error_alert.yml
- spec/components/error_alert_spec.rb
Can now add id as a parameter to the error alert component.
When trying to [add an anchor link to the location form in frontend](https://github.com/alphagov/frontend/pull/3263/), noticed that I could not add an id to the error alert component. Now id is accepted as a param and can be set on error alert.
[Related Trello Card](https://trello.com/c/rCnJ2YEg/1086-fgm-help-and-advice-postcode-search-anchor-link-when-an-error-occurs)
Needed to be merged before https://github.com/alphagov/frontend/pull/3263
> Add id attribute to error alert component

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/analytics-ga4/gtm-click-tracking.js
- spec/javascripts/govuk_publishing_components/analytics-ga4/gtm-click-tracking.spec.js
Hi @andysellick 
Would you be able to approve this PR if all is OK?
Thanks :+1:
Adds an if statement to check wether `aria-expanded` is inside an accordion component
Without this, imagine you had the following HTML:
```HTML
<div data-gtm-event-name="event3-name" data-gtm-attributes='${JSON.stringify(attributes)}' class="clickme">
<div class='content'>
abc
</div>
<div class='accordion'>
<button aria-expanded="false">Show</button>
</div>
</div>
```
Clicking on the parent div would trigger the accordion click tracking to run, since it has a nested `aria-expanded` element inside it. We only want that tracking to run when the accordion is clicked.
> Fix issue with detecting aria-expanded

- CHANGELOG.md
- lib/govuk_publishing_components/presenters/meta_tags.rb
- spec/components/meta_tags_spec.rb
Add check to meta_tags to make sure primary_publisher is not an empty array before attempting to access a hash in the array.
Tests were intermittently failing on collections and after some digging, it was discovered that this was because that the random schema generated for tests can occasionally result in `primary_publishing_organisation` being set to an empty array. This would cause accessing the key of the first hash of the array in `meta_tags` to fail which would mean tests would fail. This commit adds `.blank?` to the primary_publisher check which means that if the array is empty then an error will not be caused by this line. This fixes the collections tests but in theory should also fix other intermittently failing tests in other applications.
> Check if primary_publisher nil OR empty in meta_tags

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/analytics-ga4/gtm-page-views.js
- app/assets/javascripts/govuk_publishing_components/analytics/custom-dimensions.js
- lib/govuk_publishing_components/presenters/meta_tags.rb
- spec/components/meta_tags_spec.rb
- spec/javascripts/govuk_publishing_components/analytics-ga4/gtm-click-tracking.spec.js
- spec/javascripts/govuk_publishing_components/analytics-ga4/gtm-page-views.spec.js
- spec/javascripts/govuk_publishing_components/analytics/custom-dimensions.spec.js
Rename some of the attributes used by GA4 page views.
Trying to clean up some of the code and standardise the names. Ideally the name of something in the content item would persist through to the metadata, the JS and on into GA4, rather than being slightly different at various stages, which could cause confusion in future.
None.
Trello cards: 
- https://trello.com/c/mizG5QKy/4-add-tracking-page-views
- https://trello.com/c/GDLkrUws/335-page-views-data-naming-inconsistencies
> Standardise some analytics attributes

- app/assets/javascripts/govuk_publishing_components/analytics-ga4/gtm-click-tracking.js
- spec/javascripts/govuk_publishing_components/analytics-ga4/gtm-click-tracking.spec.js
Changes the name of the state attribute in the new GA4 code to action.
- rename is to avoid ambiguity
- will also need updating in applications where data attributes are passed
None.
Trello card: https://trello.com/c/BRyCFCVf/334-uistate-should-be-uiaction
> Rename GA4 analytics attribute state to action

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
* Standardise some analytics attributes ([PR #2831](https://github.com/alphagov/govuk_publishing_components/pull/2831))
* Check if primary_publisher nil OR empty in meta_tags ([PR #2829](https://github.com/alphagov/govuk_publishing_components/pull/2829))
* Add date of birth autocomplete option for date input ([PR #2802](https://github.com/alphagov/govuk_publishing_components/pull/2802))
> Version 29.12.1

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/components/feedback.js
- spec/javascripts/components/feedback-spec.js
Hi @andysellick 
Would you be able to review this PR? 
Not sure if it needs new tests, and if so what the tests would be.
Thanks :+1:
Adds:
- A timer hidden field to see how quickly the form is submitted. Uses `setInterval` to update the field.
- A paste count hidden field and listener which detects how many pastes are inserted into the form `textarea`.
- A keypress count hidden field and listener which detects how many keypresses are inserted into the form `textarea`.
It then works in combination with the backend to filter out the spam: https://github.com/alphagov/feedback/pull/1452
We are experimenting using JS to provide metadata which might help reduce spam on the feedback component.
> Add new fields for spam detection

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/components/accordion.js
- app/views/govuk_publishing_components/components/docs/accordion.yml
- spec/javascripts/components/accordion-spec.js
Adds ability to add extra options to the click anayltics event for showing/hiding all the sections of an accordion.
In a [previous PR ](https://github.com/alphagov/govuk_publishing_components/pull/2813)I added the ability to add extra options to click events for opening sections in an accordion but I did not include the Show/Hide All Sections button. For tracking purposes it means that if an attribute is not passed in an event, then an event cannot be filtered on that attribute. Therefore adding the ability to pass attributes to the Show/Hide All Sections button means it can be more easily inlcuded in searches/filters on click events.
[Relevant Trello Card](https://trello.com/c/hDJRk2hS/1096-add-tracking-for-position-of-show-hide-all-sections-in-accordion-on-new-browse-level-2-curated-topi …
> Add extra options for show/hide all sections accordion click

- CHANGELOG.md
- app/models/govuk_publishing_components/audit_applications.rb
- app/models/govuk_publishing_components/audit_comparer.rb
- app/views/govuk_publishing_components/audit/_components.html.erb
- spec/component_guide/audit_applications_spec.rb
- spec/component_guide/audit_comparer_spec.rb
Adds links to the file locations of components included in applications to the auditing pages of the component guide, in the 'Components' tab.
- previously the 'components by application' section of the auditing listed the components, how many applications used them, and the names of those applications
- now lists the above, plus links to the specific files where the components are used (in github)
- also updates this part of the auditing to only match applications where the component is included in ruby or templates, previously matched for any instance (which meant false positives e.g. would say an application was using a component even if it only included the component asset)
I think this is going to be useful.
> Add file locations to component audits

- app/assets/javascripts/govuk_publishing_components/components/accordion.js
- spec/features/accordion_spec.rb
Refactor some things in the accordion code. Specifically:
- remove some variables that weren't used
- stop having class name variables that don't start with `.` except it's needed every time the variable is used
- rename the class name and element selector variables to clearly distinguish them
- remove the class that was added on JS initialisation as it doesn't do anything except allow a test to pass - we should have a better way of testing our code than that
I made some unrelated changes in the accordion recently and this was bothering me. 
I'm 99.9% certain the variables I've removed aren't used but worth double checking. I think we used to have the ability to pass translated text to the component for the 'show/hide' and 'show/hide all' links (since they're created by JS, which can't …
> Refactor the accordion component code

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/analytics-ga4.js
- app/assets/javascripts/govuk_publishing_components/analytics-ga4/gtm-click-tracking.js
- app/assets/javascripts/govuk_publishing_components/analytics-ga4/gtm-page-views.js
- app/assets/javascripts/govuk_publishing_components/analytics-ga4/gtm-schemas.js
- docs/analytics-gtm/analytics.md
- docs/analytics-gtm/gtm-click-tracking.md
- spec/javascripts/govuk_publishing_components/analytics-ga4/gtm-click-tracking.spec.js
- spec/javascripts/govuk_publishing_components/analytics-ga4/gtm-page-views.spec.js
Rework the code based on changes to the GA4 schema. This includes:
- the creation of a new file that contains the schema for events, which is then used by the event click tracking script (hopefully we can use it for other schemas as well)
- restructuring of the page view data
- some new documentation
- miscellaneous other changes (see commit messages for details)
We're redesigning the data schema for events.
None.
Trello card: https://trello.com/c/obytEbqo/153-update-existing-code-with-schema-changes
> GA4 analytics schema rework

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/govspeak/_charts.scss
- app/views/govuk_publishing_components/components/docs/govspeak.yml
https://trello.com/c/z28rKuYm/1189-implementation-of-updated-bar-chart-colour-change
- Update the colour palette for the [Govspeak content](https://components.publishing.service.gov.uk/component-guide/govspeak) component to a new palette of 6 colours (reduced from 8)
- Update data visualisation colours guidance to match https://gss.civilservice.gov.uk/policy-store/data-visualisation-colours-in-charts/#section-5
To meet the colour contrast requirements for adjacent colours (as set out in WCAG 2.1).
https://www.w3.org/WAI/WCAG21/Understanding/non-text-contrast.html
<table role="table">
<thead>
<tr>
<th>Before</th>
<th>After</th>
</tr>
</thead>
<tbody>
<tr>
<td valign="top"><a target="_blank" rel="noopener noreferrer" href="https://user-images.githubusercontent.com/87758239/168851536-f7c1557a …
> Change colour palette in graphs to match GSS guidance

- CHANGELOG.md
- app/views/govuk_publishing_components/components/docs/image_card.yml
- lib/govuk_publishing_components/presenters/image_card_helper.rb
https://trello.com/c/iz7WJaeG/1404-include-width-and-height-size-attributes-on-image-card-component-2869
Include width and height size attributes on image card component
See https://github.com/alphagov/govuk_publishing_components/issues/2863
https://user-images.githubusercontent.com/87758239/180429698-4196bf45-9d87-4918-8da0-c8cf0e50aa9f.mov
https://user-images.githubusercontent.com/87758239/180429818-c858cddb-a3c6-4c80-8123-672b6c2b9623.mov
> Include width and height size attributes on image card component

- CHANGELOG.md
- app/views/govuk_publishing_components/components/docs/image_card.yml
- lib/govuk_publishing_components/presenters/image_card_helper.rb
Reverts alphagov/govuk_publishing_components#2869
> Revert "Include width and height size attributes on image card component"

- app/views/govuk_publishing_components/components/docs/image_card.yml
- the image used for the large image card configuration example wasn't large, so didn't clearly show what the intent of the option was
- adding a large image to make better use of the space
Before | After
------- | ------
> Use a large image for the large example

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
* GA4 analytics schema rework ([PR #2864](https://github.com/alphagov/govuk_publishing_components/pull/2864))
* Change colour palette in graphs to match GSS guidance ([PR #2782](https://github.com/alphagov/govuk_publishing_components/pull/2782))
> Version 29.15.2

- app/models/govuk_publishing_components/audit_applications.rb
- app/models/govuk_publishing_components/audit_comparer.rb
- app/views/govuk_publishing_components/audit/_components.html.erb
- app/views/govuk_publishing_components/audit/_items_in_applications.html.erb
- spec/component_guide/audit_applications_spec.rb
- spec/component_guide/audit_comparer_spec.rb
- spec/dummy/lib/test_file_3.rb
Extend the auditing to include details of where applications are referencing code from the gem.
We've had more than one instance where changing something in the gem has caused an error in an application because the application relied upon that code. This can give developers insight into where gem code is being used outside of the gem, and hopefully avoid similar future errors.
Extra bit added to the bottom of the 'components' tab of the auditing page.
> Add helper use to auditing

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/analytics-ga4/gtm-page-views.js
- spec/javascripts/govuk_publishing_components/analytics-ga4/gtm-page-views.spec.js
Change the data structure/schema of a GTM page view.
- sub object should be `page_view` rather than `page`
Because I got it wrong the first time.
None.
> Update GA4 analytics page view data structure

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
* **BREAKING:** Remove the "PrimaryLinks" JS Module and related tests ([PR #2866](https://github.com/alphagov/govuk_publishing_components/pull/2866))
> Version 30.0.0

- CHANGELOG.md
- spec/javascripts/govuk_publishing_components/AccessibilityTestSpec.js
https://trello.com/c/SWhTi6ne/1417-remove-unused-test-for-axe-core-in-govuk-publishing-components
Remove axe-core workaround test.
The upgrade to [axe-core 3.4.1 fixed the issue](https://github.com/alphagov/govuk_publishing_components/commit/26d3443a691e55dac96658175709cfd5717cbba1), which required the workaround, and the test can be deleted.
> Remove axe-core workaround test

- app/views/govuk_publishing_components/components/docs/accordion.yml
- docs/analytics-gtm/gtm-click-tracking.md
Rewrite the documentation for applying click tracking to accordion 'show all sections' links. This in response to https://github.com/alphagov/collections/pull/2886, where the need for better documentation was identified.
None.
Trello card: https://trello.com/c/L9L67OKk/339-fix-accordion-example-and-json-parsing-in-publishing-components
> Improve GTM analytics click tracking docs

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/analytics-ga4/gtm-page-views.js
- spec/javascripts/govuk_publishing_components/analytics-ga4/gtm-page-views.spec.js
Remove time from GA4 page view data.
- page views include values for when the page was updated, which are strings of date followed by time, these are taken from the corresponding metatags on each page
- time is not needed, so stripping from the GA4 data
Note that this code is enabled only in integration.
None.
Trello card: https://trello.com/c/52O14FNY/346-strip-times-from-date-values-in-pageview-parameters
> Remove times from GA4 analytics page views

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/analytics-ga4/gtm-click-tracking.js
- app/assets/javascripts/govuk_publishing_components/analytics-ga4/gtm-page-views.js
- app/assets/javascripts/govuk_publishing_components/analytics-ga4/gtm-schemas.js
- spec/javascripts/govuk_publishing_components/analytics-ga4/gtm-click-tracking.spec.js
- spec/javascripts/govuk_publishing_components/analytics-ga4/gtm-page-views.spec.js
Change the GA4 tracking code so that empty values passed to GA4 are now `null` and not `n/a`.
Had a brief thought about using `undefined` instead of `null` but decided on `null` on the basis that null is an assignment value, meant for assigning to a variable as a representation of no value (apparently).
Note that this code is only enabled on integration.
Currently we're sending `n/a` values for any event_data parameters that don't have a value in order to nullify previously passed data. We believe that GA4 will automatically return `(not set)` for any dimensions that don't have a value. So we think it's safe to not track a value at all, rather than tracking `n/a`.
None.
Trello card: https://trello.com/c/HoDiZaWd/348-push-null-values-rather-than-n-a-in-eventdata-parameters
> Update GA4 schema to use null instead of 'n/a' for undefined values

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/analytics-ga4/gtm-page-views.js
- spec/javascripts/govuk_publishing_components/analytics-ga4/gtm-page-views.spec.js
Fix the value for `language` of the page in page views in the GA4 analytics code.
Note that this is only implemented on integration.
Language was incorrectly being reported as `en` on non English language pages.
None.
Trello card: https://trello.com/c/lYTIDjZg/345-content-language-should-not-always-be-en
> Fix GA4 analytics language on page views

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
* Fix GA4 analytics language on page views ([PR #2892](https://github.com/alphagov/govuk_publishing_components/pull/2892))
* Update GA4 schema to use null instead of 'n/a' for undefined values ([PR #2889](https://github.com/alphagov/govuk_publishing_components/pull/2889))
* Remove times from GA4 analytics page views ([PR #2891](https://github.com/alphagov/govuk_publishing_components/pull/2891))
* Remove axe-core workaround test ([PR #2882](https://github.com/alphagov/govuk_publishing_components/pull/2882))
* Move the emergency_banner from static ([PR #2795](https://github.com/alphagov/govuk_publishing_components/pull/2795))
> Version 30.1.0

- app/models/govuk_publishing_components/audit_applications.rb
Fixes a bug in the component auditing, in the section that shows where components are used in applications.
- fixes a bug where file paths that contained a + character were being cut short, resulting in incorrect links to component references in applications
- example was `guide.html+print.erb` in government-frontend, which was incorrectly coming out as `guide.html`
Was generating links to files that didn't exist.
None.
> Fix auditing path cleaning

- CHANGELOG.md
- app/views/govuk_publishing_components/component_guide/example.html.erb
- app/views/govuk_publishing_components/component_guide/show.html.erb
- app/views/govuk_publishing_components/components/_print_link.html.erb
- app/views/govuk_publishing_components/components/docs/print_link.yml
- spec/components/print_link_spec.rb
Allow a `data-module` to be passed to the print link component. This is required for adding a tracking module to the component. This change ensures that the `data-module` set by the component is preserved, and adds missing tests for the passing of data attributes in general.
Also fixes an issue in the component guide where the options shown for components where data attributes can be passed were being unnecessarily inflated by those options also set in the component itself i.e. example might have one data attribute passed, but also include data attributes set in the component template itself, leading to misleading example code snippets.
We're adding tracking to the print link component, which currently requires wrapping it in a DIV with a data module on it, would be simpler to pass the …
> Expand print link component

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/analytics-ga4/gtm-click-tracking.js
- spec/javascripts/govuk_publishing_components/analytics-ga4/gtm-click-tracking.spec.js
Hi @andysellick 
Would you be able to approve this? Though, I'm wondering if we should let our new dev James review it first as a task, and if there any requested changes we can see if he would like to make them. Thanks :+1:
This makes it so our GTM event click tracker grabs the `href` of a tab when it is clicked. For example, if a 'More information' tab is clicked, the value of the url key should be: `url: #more-information` 
This uses `event.target` to ensure that an `<a>` tag was clicked on. You can't use the existing `target` variable as this has already traversed up the DOM due to the use of `.closest`, so it wouldn't let us know if what was clicked on was the tab itself - it just gives us the element with `data-ga4` on it.
When clicking tabs, the `url` value in our GTM schema was …
> Ensure tab clicks grab the tabs href for gtm

- CHANGELOG.md
- app/views/govuk_publishing_components/components/_accordion.html.erb
- app/views/govuk_publishing_components/components/docs/accordion.yml
- spec/components/accordion_spec.rb
Allow the accordion to be passed a custom value for `data-module`. The accordion already fills this in with its own module, so this must be preserved alongside whatever is passed.
Because we want to add tracking to accordions without having to wrap them in extra elements just to add the `data-module` attribute. Also because I already told @gclssvglx accordions can do this and it turns out they couldn't.
None.
> Allow accordion to accept custom data module

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/analytics-ga4.js
- app/assets/javascripts/govuk_publishing_components/analytics-ga4/ga4-page-views.js
- spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-page-views.spec.js
The `sendPageView` object has been moved into the `analyticsGA4` object to make the structure of our analytics modules more consistent.
To improve consistency across tracking module implementations.
None.
> Update sendPageView object location

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
* Allow accordion to accept custom data module ([PR #2908](https://github.com/alphagov/govuk_publishing_components/pull/2908))
* Expand print link component ([PR #2900](https://github.com/alphagov/govuk_publishing_components/pull/2900))
* Add link click tracking ([PR #2904](https://github.com/alphagov/govuk_publishing_components/pull/2904))
* Ensure tab clicks grab the tabs href for gtm ([PR #2884](https://github.com/alphagov/govuk_publishing_components/pull/2884))
* Update gtm naming conventions ([PR #2906](https://github.com/alphagov/govuk_publishing_components/pull/2906))
* Update sendPageView object location ([PR #2909](https://github.com/alphagov/govuk_publishing_components/pull/2909))
> Version 30.2.0

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/analytics-ga4/ga4-event-tracker.js
- spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-event-tracker.spec.js
Rename the GA4 module `GA4EventTracker` to `Ga4EventTracker`.
The modules system takes the value of a found `data-module` attribute e.g. `ga4-event-tracker` and converts it into camel case in order to find the actual module to execute. Since this module started with two upper case letters it couldn't be found, because it was converting it into `Ga4EventTracker`.
This is an unfortunate consequence of having to convert one type of string to another, and I still can't remember why we do it like this.
None.
> Rename GA4EventTracker to Ga4EventTracker

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
* Rename GA4EventTracker to Ga4EventTracker ([PR #2911](https://github.com/alphagov/govuk_publishing_components/pull/2911))
> Version 30.2.1

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/analytics-ga4/ga4-link-tracker.js
- spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-link-tracker.spec.js
Hi @JamesCGDS - would you be able to look at this PR? Thanks :+1:
- Changes `event: analytics` to `event: event_data` in the external link tracking GTM object (as requested by analysts.)
- Makes sure that anchor links (jump links), such as `#other-ways-to-apply` are not treated as external links.
- The `event` key was changed so that the data is properly tracking the the analytics dashboard.
- The anchor links should not be treated as external links, as they just jump to a location on the same page you're already on.
None.
> Fix bugs with gtm external link tracking

- app/views/govuk_publishing_components/components/docs/textarea.yml
This adds an example of how to pass data attributes to text areas.
The option is available but isn't documented.
> Add example for passing data attributes to textarea

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/analytics/page-content.js
- spec/javascripts/govuk_publishing_components/analytics/page-content.spec.js
Add links and sections count tracking for Cost of living hub
We need to add tracing to populate custom dimensions 26 (number of sections) and 27 (number of links) on the Cost of living hub pages as requested by a performance analyst.
`data-track-count="accordionSection"` is already added to the accordion sections https://github.com/alphagov/collections/blob/241b33a/app/views/cost_of_living_landing_page/show.html.erb#L22
`data-track-count="contentLink"` will be added to links within accordions and links within inset text on the page.
Meta tag `navigation-page-type` will be added to the Cost of living page.
[Trello](https://trello.com/c/0pjp3DgK/1288-add-meta-tags-that-power-custom-dimensions-m)
n/a
> Add links and sections count tracking for Cost of living hub

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/components/checkboxes.js
- app/views/govuk_publishing_components/components/_checkboxes.html.erb
- lib/govuk_publishing_components/presenters/checkboxes_helper.rb
- spec/components/checkboxes_spec.rb
- spec/javascripts/components/checkboxes-spec.js
Remove GOV.UK specific code for handling the [exclusive checkboxes option](https://components.publishing.service.gov.uk/component-guide/checkboxes/checkbox_with_exclusive_item).
This is already included in `govuk-frontend` as of v.3.13.0.
Fixes https://github.com/alphagov/govuk_publishing_components/issues/2167
None.
> Remove GOV.UK specific code for handling exclusive checkboxes

- app/views/govuk_publishing_components/component_guide/show.html.erb
This matches the default contents item with the heading text.
The reference to default doesn't really exist anywhere, this matches the whole list of contents with the headings.
> Match content item with heading label

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/_layout-footer.scss
- app/assets/stylesheets/govuk_publishing_components/components/_layout-super-navigation-header.scss
- config/locales/en.yml
New links to the Cost of living hub have been added to the navbar and to the footer. Both of these elements were designed with a specific number of children in mind so therefore minor stylistic adjustments had to be made.
The number of rows in the navbar topics toggle menu has had to be increased to avoid the splitting of the grid into three columns.
A new selector has been added to the layout footer which ensures that the number of items in each column is correctly balanced when there is an odd number of links.
The Cost of living hub has recently been added to the homepage and we want links to it on the sidewide navbar and footer.
> Add Cost of Living hub links to side wide navbar and footer

- CHANGELOG.md
- Gemfile.lock
- app/models/govuk_publishing_components/component_example.rb
- govuk_publishing_components.gemspec
- spec/component_guide/component_example_spec.rb
- spec/dummy/app/views/components/_test-component-with-hash-key.html.erb
- spec/dummy/app/views/components/docs/test-component-with-hash-key.yml
This change adds the awesome_print package to pretty print the rails code. This is a more stable solution and allows us to use things like `:or` keys.
We found that the pretty_data function was changing `:or` keys to `"or"` strings. This caused copy and pasting of the code to fail as "or" would cause the component to throw an error.
https://components-gem-pr-2934.herokuapp.com/public
> Change the way we generate pretty print data for our documentations

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
* Modify GTM values for download links in response to analyst review ([PR #2923](https://github.com/alphagov/govuk_publishing_components/pull/2923/))
* Add Cost of Living hub links to side wide navbar and footer ([PR #2939](https://github.com/alphagov/govuk_publishing_components/pull/2939))
* Change the way we generate pretty print data for our documentations ([PR #2934](https://github.com/alphagov/govuk_publishing_components/pull/2934))
> Version 30.4.0

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/_layout-super-navigation-header.scss
- app/views/govuk_publishing_components/components/_layout_super_navigation_header.html.erb
Add extra styles to the navbar link so that when JS is disabled it still looks the same as it would when JS is enabled.
When JS was disabled, the links in the navbar had different styling to the links in the navbar when JS is enabled. The border to the left and right of the first link was missing and the underline underneath the text when hovered over was the wrong size. 
[Relevant Trello Card](https://trello.com/c/AexGt58j/766-piping-and-grey-underline-broken-on-header-buttons-without-javascript)
> Resolve visual differences in navbar when JS not enabled

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
* Revert addition of `awesome_print` gem ([PR #2943](https://github.com/alphagov/govuk_publishing_components/pull/2943))
* Resolve visual differences in navbar when JS not enabled ([PR #2756](https://github.com/alphagov/govuk_publishing_components/pull/2756))
> Version 30.4.1

- app/views/govuk_publishing_components/component_guide/show.html.erb
- spec/component_guide/component_example_spec.rb
This change adds all headings in the page as part of the content list
This allows users to have a whole page structural overview rather than just a list of components.
> Add all headings to content list

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/analytics-ga4.js
- app/assets/javascripts/govuk_publishing_components/analytics-ga4/ga4-event-tracker.js
- app/assets/javascripts/govuk_publishing_components/analytics-ga4/ga4-link-tracker.js
- app/assets/javascripts/govuk_publishing_components/analytics-ga4/ga4-page-views.js
- app/assets/javascripts/govuk_publishing_components/analytics-ga4/init-ga4.js
- docs/analytics-gtm/analytics.md
- spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-event-tracker.spec.js
- spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-link-tracker.spec.js
- spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-page-views.spec.js
- spec/javascripts/govuk_publishing_components/analytics-ga4/init-ga4.spec.js
Integrate the GA4 code with the cookie consent mechanism. Currently GA4 just runs on page load, but limited only to integration.
Adds an init script to the `window.GOVUK.analyticsGA4` object, which when called (from `static`) will make the GA4 analytics code work. Currently, this does the following.
- checks for the consent cookie
- if found, sets `window.GOVUK.analyticsGA4.consent` to `true` for use later
- any JS in the `window.GOVUK.analyticsGA4.analyticsModules` object will have its `init` function called, if one exists
- this includes all of the GA4 code including pageviews (all restructured as part of this PR)
This means a pageview (and all the rest of the analytics code) should happen on the page where consent is given, without needing a page reload. This is important otherwise …
> Integrate GA4 analytics code with cookie consent mechanism

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/_organisation-logo.scss
Fix the underline on the organisation logo component.
This appears to be being caused by a [bug in Chromium](https://bugs.chromium.org/p/chromium/issues/detail?id=1359501&q=underline&can=2) related to the use of `position: relative` and `top: 3px` - the underline on the element is not adjusted, meaning that the text is pushed down 3px, slightly overlapping the underline (if you increase the value for `top` you can make the underline eventually appear above the text).
The bug has only been recently reported but we don't really need to have this CSS on this element - the same effect can be achieved by increasing the padding above the element by 3px.
Tested in various Chromes and Chrome on mobile.
Before | After
> Fix underline on organisation logo component

- config/locales/en.yml
These match the links on the homepage, which were updated in https://github.com/alphagov/frontend/pull/3366
The links in the menu should match the ones on the homepage
> Update popular links for London Bridge

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
* Update popular links for London Bridge ([PR #3366](https://github.com/alphagov/frontend/pull/3366))
> Version 30.5.1

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/analytics-ga4.js
- app/assets/javascripts/govuk_publishing_components/analytics-ga4/ga4-core.js
- app/assets/javascripts/govuk_publishing_components/analytics-ga4/init-ga4.js
- spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-core.spec.js
- spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-event-tracker.spec.js
- spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-link-tracker.spec.js
- spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-page-views.spec.js
- spec/javascripts/govuk_publishing_components/analytics-ga4/init-ga4.spec.js
- spec/javascripts/helpers/SpecHelper.js
- include the code snippet from Google in our code for running GTM as part of our new analytics code
- note that this will not work without the id, auth and preview values, which have to be created separately before the analytics code is called in `static`
Note that none of this code will be executed in production yet. This also depends upon the correct environment variables being set for the GTM code variables (see related PR, not ready yet).
How this works:
- `static` includes `analytics-ga4.js` (only on integration)
- `static` gets the GTM variables for `id`, `auth` and `preview` from environment variables using the functionality available through `js.erb` and sets them as JS variables inside the `window.analyticsGA4.vars` object
- `static` then calls `window.GOVUK.analyticsGA4.init()` …
> Use Google snippet for GTM in analytics JavaScript

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
* Use Google snippet for GTM in analytics JavaScript ([PR #2951](https://github.com/alphagov/govuk_publishing_components/pull/2951))
> Version 30.5.2

- spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-core.spec.js
- spec/javascripts/govuk_publishing_components/analytics-ga4/init-ga4.spec.js
- sometimes the core test would fail because window.dataLayer was already full of things when the test was run, when it was expecting it to start empty
- the reason for this was the init GA4 tests, which were repeatedly initialising the link tracker code, which adds event listeners to the DOM
- when other tests ran and clicked anywhere, those event listeners were firing and adding things to window.dataLayer
- the link tests already cleaned up after themselves by shutting down the event listeners, so the fix was to repeat that in the init GA4 tests
- note that these tests were already passing because we were cleaning out window.dataLayer manually, but this is better because it avoids potential similar problems in the future with other new tests
None.
> Fix intermittent failing analytics test

- app/assets/javascripts/govuk_publishing_components/analytics-ga4/init-ga4.js
- spec/javascripts/govuk_publishing_components/analytics-ga4/init-ga4.spec.js
Hi @andysellick - would you be able to approve this when you get a chance? Thanks :+1:
Ensures the `cookie-consent` event listener is removed after the `init-ga4.spec.js` tests.
We were adding a `cookie-consent` listener in our tests, which initialises our GA4 modules when the event is fired. However `cookie-functions-spec.js` fires `cookie-consent` events, which caused multiple instances of GTM to be initialised, breaking our tests as multiple click listeners/page view listeners were active.
None.
> Fix cookie-consent events breaking GA4 tests

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/analytics-ga4/ga4-core.js.erb
- spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-core.spec.js
Adds a blocklist to the Google Tag Manager initialisation. This is a custom blocklist for GOV.UK that should prevent anyone from adding custom code through GTM's web interface
None.
Trello card: https://trello.com/c/vrMj18et/353-integrate-gtm-with-cookie-consent-mechanism
> Add GA4 analytics GTM blocklist

- CHANGELOG.md
- app/views/govuk_publishing_components/components/_intervention.html.erb
- spec/components/intervention_spec.rb
Replace unused classes in intervention component.
The component has selectors for `govuk-link gem-c-intervention__suggestion-link` and `govuk-link gem-c-intervention__dismiss` which are only used for targeting in tests but has no specific styling.
> Remove unused classes in intervention component

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/_image-card.scss
- app/views/govuk_publishing_components/components/docs/image_card.yml
- lib/govuk_publishing_components/presenters/image_card_helper.rb
https://trello.com/c/iz7WJaeG/1404-include-width-and-height-size-attributes-on-image-card-component-2869
Include width and height size attributes on image card component
- https://components-gem-pr-2895.herokuapp.com/component-guide/image_card
- https://components-gem-pr-2895.herokuapp.com/component-guide/image_card/large_version
See https://github.com/alphagov/govuk_publishing_components/issues/2863
https://user-images.githubusercontent.com/87758239/183419165-41224472-c3b2-4bb2-bf3a-3e786f6b190f.mov
https://user-images.githubusercontent.com/87758239/183419124-d9d54a1b-3a6c-4e23-b06d-772eefce2f3b.mov
https://www.integration.publishing.service.gov.uk/government/organisations/attorney-generals-office (which includes the image component with `large` and standard options) in -
> Include size attributes on image card component

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
* Add GA4 analytics GTM blocklist ([PR #2962](https://github.com/alphagov/govuk_publishing_components/pull/2962))
* GA4 analytics add single dataLayer push function ([PR #2960](https://github.com/alphagov/govuk_publishing_components/pull/2960))
* Remove unused classes in intervention component ([PR #2920](https://github.com/alphagov/govuk_publishing_components/pull/2920))
* Include size attributes on image card component ([PR #2895](https://github.com/alphagov/govuk_publishing_components/pull/2895))
> Version 30.6.0

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
* Add require version ([PR #2965](https://github.com/alphagov/govuk_publishing_components/pull/2965))
> Version 30.6.1

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/analytics-ga4.js
- app/assets/javascripts/govuk_publishing_components/analytics-ga4/ga4-enhanced-ecommerce-tracker.js
- spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-enhanced-ecommerce-tracker.spec.js
This PR adds enhanced ecommerce tracking scripts that will gather data on pages such as search and push this data to the `dataLayer` where it can be accessed by Performance Analysts.
Caveat: on lines `90` and `91`, `internalLinksDomain` and `internalLinksDomainWithoutWww` are set directly because otherwise `isExternalLink` will return an error. This implementation is temporary and will be fixed following a refactor of the `ga4-link-tracker` code by @AshGDS (https://github.com/alphagov/govuk_publishing_components/pull/2961).
These changes are being made as part of our migration to GA4.
N/A
> Add ecommerce tracking

- app/assets/javascripts/govuk_publishing_components/analytics-ga4/ga4-enhanced-ecommerce-tracker.js
- spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-enhanced-ecommerce-tracker.spec.js
When initialising ecommerce tracking, the `Ga4EnhancedEcommerceTracker.init()` function relies on a default parameter being set to a boolean. As this is an ES6 feature, it has been removed.
Using ES6 features can cause compatibility issues with older browsers and so it has been removed.
N/A
> Remove usage of default parameters

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/analytics-ga4/ga4-page-views.js
- app/assets/javascripts/govuk_publishing_components/analytics-ga4/ga4-schemas.js
- spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-event-tracker.spec.js
- spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-page-views.spec.js
Hi @andysellick 
Would you be able to approve this? Thanks :+1:
- This will make our GA4 code push any unset values as `undefined` instead of `null`.
- This should now display unset values as `(not set)` instead of `""` in the GA4 dashboard.
- I had to remove `var nullValue` from the page view tests, as `standardx` didn't like us setting a `var` to `undefined`
- Ecommerce has not been touched, because `we should set any missing values to undefined rather than null - except for the ecommerce parameters (and any other edge cases where [Jeff] may recommend against it.)`
None.
> Change GTM push of unset values from 'null' to 'undefined'

- CHANGELOG.md
- app/views/govuk_publishing_components/components/_feedback.html.erb
- app/views/govuk_publishing_components/components/feedback/_yes_no_banner.html.erb
- spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-event-tracker.spec.js
Hi @andysellick @JamesCGDS 
Would you be able to approve this PR if all is OK?
Thanks :+1:
- Adds `data-module="ga4-event-tracker"` to the feedback component parent `<div>`
- Adds a `data-ga4` JSON to the feedback component Yes/No buttons so that they are tracked on click by `ga4-event-tracker.js`
- They are needed to fulfil the MVP requirement of tracking the clicks on the Yes/No buttons
- I've hard coded the English versions of "Yes" "No" and "Is this page useful?" in the `JSON`. In the live feedback component, these strings are potentially translated into 60+ other languages, depending on what language the user's browser is set to. I'm assuming we should always send English to GA4, otherwise the analysts would have to collate all these different languages in the dashboard just to see …
> Add click tracking to Yes/No buttons on feedback component

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
* Change GTM push of unset values from 'null' to 'undefined' ([PR #2971](https://github.com/alphagov/govuk_publishing_components/pull/2971))
* Add click tracking to Yes/No buttons on feedback component ([PR #2964](https://github.com/alphagov/govuk_publishing_components/pull/2964))
* Update popular links on search bar ([PR #2972](https://github.com/alphagov/govuk_publishing_components/pull/2972))
> Version 30.7.0

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
* Add new cookies set by gtag ([PR #2975](https://github.com/alphagov/govuk_publishing_components/pull/2975))
* Refactor ga4-link-tracker and add new features ([PR #2961](https://github.com/alphagov/govuk_publishing_components/pull/2961))
> Version 30.7.1

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/analytics-ga4/ga4-core.js.erb
- spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-core.spec.js
Add the ability to switch GA4 from GTM to Gtag.
- if an environment variable for gtag has been set in static and passed as a variable attached to the window.GOVUK.analyticsGA4.vars object, use gtag instead of GTM
- this is for testing on integration, we will only add the gtag env var on there for now
- note that this code snippet for gtag is adapted from the GTM one, since the gtag one from Google involves <script> tags, rather than the convenience of a self executing function that creates the <script> tags and appends them to the DOM. However, both original snippets do essentially the same thing, so the GTM one has been adapted to suit and should perform exactly the same task as the original gtag snippet recommended by Google
Corresponding PR to use this in `static` is here: …
> Add optional gtag snippet

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/analytics-ga4/ga4-core.js.erb
- spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-core.spec.js
- spec/javascripts/govuk_publishing_components/analytics-ga4/init-ga4.spec.js
Rewrite the code from Google that pulls in Tag Manager, so that if the `auth` and `preview` variables are not present, we don't pass them as part of the script URL.
Apparently the snippet with the extra bits in should never be used in a live site, because environments (the snippet we were using) are expensive in terms of performance, so we should avoid sending too much traffic to them - environment endpoints can become overloaded and shut down.
None.
Trello card: https://trello.com/c/zpERINGm/223-rewrite-google-snippets
> Refactor analytics code snippets

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/analytics-ga4/ga4-core.js.erb
Fix up some linting issues in GA4-core.
- because this file is a .js.erb it was ignored by our linter
- but it turns out it had some linting problems, which were only picked up later when the gem with this code in was installed in an application and included, built and then linted, causing errors
- linting issues addressed
Just tried to build `static` with the gem containing this unlinted code and it broke 😞 
None.
Trello card: https://trello.com/c/zpERINGm/223-rewrite-google-snippets
> Lint ga4-core

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
* Lint ga4-core ([PR #2982](https://github.com/alphagov/govuk_publishing_components/pull/2982))
> Version 30.7.3

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/components/accordion.js
- spec/javascripts/components/accordion-spec.js
Update the accordion component to only look for a target element within the module itself, not the entire document.
This fixes a bug when `anchor_navigation` is set to `true` and an ID is passed in for an element that exists on the page, but is not contained within the accordion component.
For example: https://www.gov.uk/guidance/how-to-publish-on-gov-uk/creating-and-updating-pages#section-title
Fixes: https://github.com/alphagov/govuk_publishing_components/issues/2086
Trello: https://trello.com/c/q5P6u7id/1507-ps-17-accordion-anchor-link-navigation-breaks-with-invalid-anchor
There was also a need to escape the colon character when using `querySelector`, for example `$this.module.querySelector('#fnref:1')` would throw an error [^1]
[^1]: [Bugzilla - querySelector doesn't work if the ID …
> Fix bug when getting target element from URL hash

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
* Fix bug when getting target element from URL hash in accordion component ([PR #2985](https://github.com/alphagov/govuk_publishing_components/pull/2985))
* **BREAKING:** Update GA4 naming conventions ([PR #2987](https://github.com/alphagov/govuk_publishing_components/pull/2987))
* Stop using .erb for ga4-core ([PR #2984](https://github.com/alphagov/govuk_publishing_components/pull/2984))
> Version 31.0.0

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/analytics-ga4/ga4-ecommerce-tracker.js
- docs/analytics-ga4/analytics.md
- docs/analytics-ga4/ga4-ecommerce-tracker.md
This PR adds documentation for the `ga4-ecommerce-tracker.js` script.
To keep the code for the GA4 implementation well documented.
N/A
> Add ecommerce tracking documentation

- CHANGELOG.md
- app/views/govuk_publishing_components/components/_emergency_banner.html.erb
- spec/components/emergency_banner_spec.rb
Small adjustments to the template of emergency banner for accessibility reasons.
When the emergency banner was deployed on GOV.UK, some changes were made based on the feedback from an accessibility specialist. These changes involved removing the role attribute from the parent div and changing the element of the parent div to a section. This is to avoid any accidental duplication of roles on any page of GOV.UK. In accordance with this change, the aria-label has been changed to aria-labelledby instead.
Co-author with @maxf who made the changes to static (which will be removed when[ the emergency banner static PR](https://github.com/alphagov/static/pull/2788) has been merged).
> Use section for emergency banner

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/presenters/machine_readable/creative_work_schema.rb
- lib/govuk_publishing_components/presenters/machine_readable/page.rb
- lib/govuk_publishing_components/presenters/machine_readable/potential_search_action_schema.rb
Plek 4.1 [1] deprecates the Plek.current method. This resolves this gem emitting deprecation warnings.
This also updates the Gemfile.lock of this gem to use the new version.
[1]: https://github.com/alphagov/plek/pull/92
> Resolve Plek.current deprecations

- CHANGELOG.md
- app/assets/stylesheets/component_guide/application.scss
- app/views/govuk_publishing_components/component_guide/component_doc/_component.html.erb
Remove the "Example" grey box from component previews. The :before pseudo class is now only used by `.component-guide-preview--violation` and `.component-guide-preview--warning`
The "Example" grey box shown for each component preview was causing the axe-core colour-contrast check to report as "incomplete". We would then advise that the component needs to be manually checked.
The "Example" grey box was being nested within the component itself, so was also being included as part of the accessibility test. The accessibility test would then report as incomplete, because the "Example" element uses the :before pseudo class to set both the `color` and `background-color` which cannot be tested using axe-core.
This change reduces the number of manual checks required overall, for example on the …
> Fix axe-core false positives for `color-contrast` tests

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
* Update to LUX 302 ([PR #3009](https://github.com/alphagov/govuk_publishing_components/pull/3009))
* Fix axe-core false positives for color-contrast tests ([PR #3007](https://github.com/alphagov/govuk_publishing_components/pull/3007))
> Version 31.1.1

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/analytics-ga4/ga4-core.js
- spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-core.spec.js
Discovered this problem during testing. The blocklist has to come first or it doesn't work.
- make it so that the blocklist is the very first thing that is added to the dataLayer when GTM initialises
- otherwise it doesn't work
None.
> Move the GTM blocklist code

- .github/workflows/visual-regression-tests.yml
Replace the ignore file list YAML anchor with an actual list.
GitHub Actions doesn't currently support YAML anchors, so this list of files and paths to ignore needs to be written twice - once for the pushes and once  or the pull requests.
This caused the YAML file to halt the running of the workflow - so visual regression tests weren't being run.
None.
> Replace YAML anchor with list to fix VRT action

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/analytics-ga4/ga4-link-tracker.js
- app/assets/javascripts/govuk_publishing_components/analytics-ga4/ga4-schemas.js
- app/views/govuk_publishing_components/components/_share_links.html.erb
- docs/analytics-ga4/ga4-link-tracker.md
- spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-link-tracker.spec.js
Hi @andysellick / @JamesCGDS - would either (or both) of you be able to approve this PR? 
Also, do you think this is too many changes in one branch? I like to tackle multiple tickets at a time, but I appreciate that some people would treat each commit as a separate PR.
Thanks :+1:
- Strips out `_gl` and `_ga` query parameters from being pushed with link clicks
- Adds a `link_domain` field which tracks what protocol and domain the clicked link is pointing to (e.g. `https://www.gov.uk` or `https://example.com`)
- Adds a `link_path_parts` object which stores strings. These are the clicked link's path, split at every 100 characters.
- Changes the `link_method` key to just be `method`.
- Strips line breaks and multiple spaces in link text before being pushed to the dataLayer.
- Updates the …
> Fix issues with GA4 link tracking identified by performance analysts

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
* Move the GTM blocklist code ([PR #3011](https://github.com/alphagov/govuk_publishing_components/pull/3011))
* Fix issues with GA4 link tracking identified by performance analysts ([PR #3004](https://github.com/alphagov/govuk_publishing_components/pull/3004))
> Version 31.1.2

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/_feedback.scss
- app/views/govuk_publishing_components/components/feedback/_problem_form.html.erb
- app/views/govuk_publishing_components/components/feedback/_survey_signup_form.html.erb
- app/views/govuk_publishing_components/components/feedback/_yes_no_banner.html.erb
- config/locales/en.yml
- spec/javascripts/components/feedback-spec.js
Cosmetic changes to the feedback component. [[Trello]](https://trello.com/c/kHCz2XVL/1046-iterate-and-implement-the-design-update-to-the-feedback-component-s)
[Research suggested](https://docs.google.com/presentation/d/1_9VoSf_E-RtU2TuapSyIOAFTR1okpd05q8jzZds-AAQ/edit#slide=id.ga3daf72c81_0_153) that a number of issues need resolving longer term. However, in the short term we are improving the component cosmetically to address several concerns:
* The component is too bulky
* Users are distracted by the component on shorter pages
* Users can mistake the component as being part of a form that they need to fill in
**Initial state**
**YES**
**NO**
**REPORT**
**START**
**YES**
**NO**
**REPORT**
> Feedback component visual updates

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/analytics-ga4/ga4-event-tracker.js
- app/views/govuk_publishing_components/components/_layout_super_navigation_header.html.erb
- docs/analytics-ga4/ga4-event-tracker.md
- spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-event-tracker.spec.js
Hi @andysellick / @JamesCGDS 
Would one of you (or both) be able to review this? Thanks :+1:
- Adds tracking to the dropdown menus of the GOV.UK super navigation header. These are the dropdowns for `Topics`, `Government Activity`, the `Search` button, and the `Menu` button on mobile (the `Menu` button  expands and collapses the whole menu on mobile.)
- This uses `ga4-event-tracker` which listens for a click on all `ga4-event-tracker` modules, then checks for a `data-ga4` data attribute JSON on the `event.target` and pushes it to GTM if it exists.
This is the element in question:
Desktop:
Mobile:
The GTM object which is output when clicking one of these dropdowns looks like this:
```JSON
{
"event": "event_data",
"event_data": {
"event_name": "select_content",
"type": "super navigation …
```
> Add tracking to super navigation header dropdowns

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/analytics-ga4/ga4-ecommerce-tracker.js
- app/assets/javascripts/govuk_publishing_components/analytics-ga4/ga4-page-views.js
- docs/analytics-ga4/ga4-ecommerce-tracker.md
- spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-ecommerce-tracker.spec.js
- spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-page-views.spec.js
This PR contains two key changes:
- Fixes a bug where the `referrer` property on the `page_view` object was not updating correctly after dynamic page updates
- Adds a new `dynamic` property to the `page_view` object
When a user is on a search results page and applies a filter, the URL of the page changes and PA's need to be able to track the URLs a user has visited using the `page_view.referrer` property. In the current implementation, however, the `page_view.referrer` property was not updating and remained the same whenever a dynamic update was triggered. This PR ensures that the `page_view.referrer` property is updated correctly by using a parameter that it receives from [`live_search.js`](https://github.com/alphagov/finder-frontend/blob/e0e8f32000f708b2b2a67983d49f45d9f04c27f8/app/asset …
> Fix search referrer bug

- CHANGELOG.md
- app/views/govuk_publishing_components/components/feedback/_problem_form.html.erb
- app/views/govuk_publishing_components/components/feedback/_survey_signup_form.html.erb
- app/views/govuk_publishing_components/components/feedback/_yes_no_banner.html.erb
Adds GA4/GTM tracking to the remaining buttons in the feedback component.
Part of the GA4 migration work.
None.
Trello card: https://trello.com/c/EmWLC6DE/379-add-tracking-feedback-remaining-elements
> Add GA4 analytics tracking to remaining feedback component buttons

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/components/layout-super-navigation-header.js
When the user sets scrollbars to always show in MacOS at system level ('System Preferences' > 'General' > 'Show scroll bars': 'Always'), the super navigation header doesn't calculate the viewport width correctly in Chrome and Firefox.
This is because `document.documentElement.clientWidth` which is used to calculate the viewport width and switch styles on/off doesn't account for the forced Mac scrollbar in Chrome and Firefox, leading to the component rendering incorrectly in when the viewport is ~768-784px wide. The same calculation had previously used `window.innerWidth` but [this was found to have caused issues in Safari](https://github.com/alphagov/govuk_publishing_components/issues/2430). Hence it was replaced by `document.documentElement.clientWidth` but this is now causing the above …
> Calculate viewport width correctly for navbar in Chrome and Firefox when Mac scrollbars are enabled

- CHANGELOG.md
- app/assets/javascripts/component_guide/accessibility-test.js
- spec/javascripts/govuk_publishing_components/AccessibilityTestSpec.js
Delete removed `restoreScroll` Axe API option.
The option has been removed. See https://github.com/dequelabs/axe-core/issues/2388.
> Delete removed `restoreScroll` Axe API option

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
* Calculate viewport width correctly for navbar in Chrome and Firefox when Mac scrollbars are enabled ([PR #3016](https://github.com/alphagov/govuk_publishing_components/pull/3016))
* Include the words 'opens in new tab' as part of the share link ([PR #3028](https://github.com/alphagov/govuk_publishing_components/pull/3028)) 
* Delete removed `restoreScroll` Axe API option ([PR #3029](https://github.com/alphagov/govuk_publishing_components/pull/3029))
> Release version 32.1.0

- CHANGELOG.md
- app/views/govuk_publishing_components/components/_share_links.html.erb
- app/views/govuk_publishing_components/components/docs/share_links.yml
- spec/components/share_links_spec.rb
Extend the share links component to allow optional data attributes to be passed to the parent and the individual links.
Note that the component already includes a `data-module` of `gem-track-click` by default, this is preserved now even if another value for module is passed.
We want to track this component in the new GA4 world and passing attributes like this is our approach.
> Share links allow data attributes

- app/views/govuk_publishing_components/components/_phase_banner.html.erb
The URL `/service-manual/phases/ideal-alphas` refers to [a page from the original Service Manual][1] before the content was migrated in 2016.
Since the content was migrated, that URL now redirects to `/service-manual/agile-delivery/how-the-alpha-phase-works`.
Update the link in the alpha banner to point to the same place.
[1]: https://github.com/alphagov/government-service-design-manual/blob/master/service-manual/phases/ideal-alphas.md
Avoids an unnecessary redirect.
> Update link for alpha phase to avoid redirect

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/components/single-page-notification-button.js
- app/views/govuk_publishing_components/components/_single_page_notification_button.html.erb
- app/views/govuk_publishing_components/components/docs/single_page_notification_button.yml
- lib/govuk_publishing_components/presenters/single_page_notification_button_helper.rb
- spec/javascripts/components/single-page-notification-button-spec.js
Co-authored with @hannako 
There is a tight coupling between the single page notification button component and the Account API which this PR unpicks. The account API is [returning the full button HTML ](https://github.com/alphagov/account-api/blob/8706f606fa41a5ac44fa602f3da8482d3b0ee9f6/app/controllers/personalisation/check_email_subscription_controller.rb#L31-L46) when there is a govuk_account session present. This makes it hard to extend the functionality of the component as any changes would need to be duplicated in account api.
This PR modifies the JavaScript that receives the API response to now only update the necessary button attributes instead of expecting to receive the entire button HTML and replacing the whole button. Specifically, the PR:
- Updates the tracking attribute on …
> Set attributes for single page notification button based on Account API response

- CHANGELOG.md
- app/views/govuk_publishing_components/components/docs/single_page_notification_button.yml
- lib/govuk_publishing_components/presenters/single_page_notification_button_helper.rb
- spec/components/single_page_notification_button_spec.rb
Allow the single page notification button to accept custom subscribe and unsubscribe text.
Trello : https://trello.com/c/gpch42Uc/1456-enable-custom-text-for-the-single-page-notification-button-component-l
There is some initial User Research which suggests the default text of "Get emails about this page" is confusing if the button is added to a document collection, which is a collection of pages.
https://trello.com/c/CLaB78Qh/1280-spike-adding-single-page-notifications-with-custom-button-text-to-collections-time-box-2-days
> Allow customisation of single page notification button

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/analytics-ga4/ga4-event-tracker.js
- app/assets/javascripts/govuk_publishing_components/components/accordion.js
- app/views/govuk_publishing_components/components/_accordion.html.erb
- app/views/govuk_publishing_components/components/docs/accordion.yml
- docs/analytics-ga4/ga4-event-tracker.md
- spec/components/accordion_spec.rb
- spec/javascripts/components/accordion-spec.js
- spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-event-tracker.spec.js
Hi @andysellick / @JamesCGDS 
Would you be able to review this? Thanks 👍 
Previously we were passing a GTM object to each accordion's render statement inside of a frontend app's template. See an example here:
https://github.com/alphagov/collections/blob/2304bf53592f39e35270413fdb27c00c7cb3190a/app/views/world_wide_taxons/accordion.html.erb#L31 
Instead, it's simpler to just pass a boolean - `ga4_tracking: true` - in the accordion render of these frontend apps, and then we handle the GTM object in one place inside of `govuk_publishing_components` instead.
We were also using the accordion's class to check wether we tracked `aria-expanded`. We are now using a data attribute for this, called `data-ga4-expandable`
This isn't a breaking change as the old code is still in the repo, as that code …
> Simplify the way ga4 tracking is added to accordions

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/analytics-ga4/ga4-page-views.js
- spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-page-views.spec.js
This PR renames `page_view.section` and `page_view.themes` to `page_view.browse_topic` and `page_view.taxonomy_level1` respectively.
For now, these properties will be set by meta tags using the old values (i.e. `<meta name="govuk:section">` and `<meta name="govuk:themes">`) because updating the meta tags at this time will cause the UA tracking to break. Therefore, the meta tags will be updated after UA has been removed.
This change has been requested by PA's.
Trello card for renaming `section` to `browse_topic`: https://trello.com/c/bCtjIIL7/340-rename-section-to-browsetopic
Trello card for renaming `themes` to `taxonomy_level1`: https://trello.com/c/vaOo3M8D/341-rename-themes-to-taxonomylevel1
N/A
> Rename section and themes property names

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
* **BREAKING** Refactor GA4 analytics event and link trackers ([PR #3057](https://github.com/alphagov/govuk_publishing_components/pull/3057))
* Share links allow data attributes ([PR #3072](https://github.com/alphagov/govuk_publishing_components/pull/3072))
* Update to LUX 304 ([PR #3070](https://github.com/alphagov/govuk_publishing_components/pull/3070))
* Set attributes for single page notification button based on Account API response ([PR #3071](https://github.com/alphagov/govuk_publishing_components/pull/3071))
* Support custom text for the single page notification button component ([PR #2935](https://github.com/alphagov/govuk_publishing_components/pull/2935))
* Add `aria-controls` and `aria-describedby` attribute options to the button component ([PR …
> Version 33

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/vendor/lux/lux-reporter.js
Update to version 305 of LUX.
New version, see the [lux documentation](https://github.com/alphagov/govuk_publishing_components/blob/main/docs/real-user-metrics.md#how-to-update-to-a-new-version) for more details.
None.
> Update to LUX 305

- CHANGELOG.md
- app/assets/javascripts/component_guide/accessibility-test.js
Remove unused `include: [selector]`, from option from axe-core options parameter
See https://github.com/alphagov/govuk_publishing_components/issues/3020
> Remove unused axe-core option from options parameter

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/analytics-ga4/ga4-ecommerce-tracker.js
This PR refactors ecommerce tracking to use the `sendData()` function in `ga4-core.js` when pushing to the `dataLayer` (as opposed to calling `window.dataLayer.push()` directly).
To maintain consistency in how we push data to the `dataLayer`.
N/A
> Minor ecommerce tracking refactor

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/components/step-by-step-nav.js
- app/views/govuk_publishing_components/components/_step_by_step_nav.html.erb
- app/views/govuk_publishing_components/components/docs/step_by_step_nav.yml
- spec/components/step_by_step_nav_spec.rb
- spec/javascripts/components/step-by-step-nav-spec.js
Hi @andysellick & @JamesCGDS - would you be able to approve this if everything is OK?
Thanks :+1:
- Adds GTM tracking to the step by step nav component. It uses the same GTM object as the accordion tracking but with `type: step by step` instead.
- It is enabled by adding `ga4_tracking: true` when the component is rendered on a page.
- When `ga4_tracking: true` exists, it adds `data-module="ga4-event-tracker" data-ga4-expandable`.  When this module is initialised, any child element that has `data-ga4-event` on it gets tracked on click. Therefore we add `data-ga4-event` where needed, which holds the JSON data we want to send to GTM on click. `data-ga4-expandable` is also added as this signals the `ga4-event-tracker` to track the value of `aria-expanded` and add it to the GTM object as …
> Add step by step nav GA4 tracking

- CHANGELOG.md
- app/views/govuk_publishing_components/components/feedback/_problem_form.html.erb
- app/views/govuk_publishing_components/components/feedback/_survey_signup_form.html.erb
Update the tracking attributes in the feedback component following a recent change to `ga4-event-tracker`, `data-ga4` attributes should now be called `data-ga4-event`.
None.
> Update feedback component tracking

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
Hi @andysellick, would you be able to approve this? Thanks :+1:
* Update feedback component tracking ([PR #3099](https://github.com/alphagov/govuk_publishing_components/pull/3099))
* Update to LUX 305 ([PR #3096](https://github.com/alphagov/govuk_publishing_components/pull/3096))
* Add the keyboard shim for link buttons ([PR #3027](https://github.com/alphagov/govuk_publishing_components/pull/3027))
* Remove unused axe-core option from options parameter ([PR #3094](https://github.com/alphagov/govuk_publishing_components/pull/3094))
* Minor ecommerce tracking refactor ([PR #3098](https://github.com/alphagov/govuk_publishing_components/pull/3098))
* Add step by step nav GA4 tracking ([PR #3052](https://github.com/alphagov/govuk_publishing_components/pull/3052))
> Version 33.1.0

- spec/javascripts/components/cookie-banner-spec.js
- spec/javascripts/components/feedback-spec.js
- spec/javascripts/components/layout-super-navigation-header-spec.js
- spec/javascripts/components/modal-dialogue-spec.js
- spec/javascripts/components/step-by-step-nav-spec.js
- spec/javascripts/helpers/SpecHelper.js
This PR removes the following `jasmine-jquery` helper functions and replaces them with a vanilla JS alternative:
- `toBeVisible()`
- `toContainElement()`
- `toContainText()`
- `toExist()`
- `toHaveAttr()`
The `jasmine-jquery` helper functions were causing [errors when running tests](https://github.com/alphagov/govuk_publishing_components/issues/2902) and so they have been replaced with a vanilla JS alternative. This also removes our tests' reliance on the `jasmine-jquery` library (which is no longer actively maintained).
N/A
> Remove jasmine jquery from tests 1

- spec/javascripts/components/checkboxes-spec.js
- spec/javascripts/components/cookie-banner-spec.js
- spec/javascripts/components/copy-to-clipboard-spec.js
- spec/javascripts/components/details-spec.js
- spec/javascripts/components/feedback-spec.js
- spec/javascripts/components/initial-focus-spec.js
- spec/javascripts/components/layout-super-navigation-header-spec.js
- spec/javascripts/components/metadata-spec.js
- spec/javascripts/components/modal-dialogue-spec.js
- spec/javascripts/components/single-page-notification-button-spec.js
- spec/javascripts/components/step-by-step-nav-spec.js
- spec/javascripts/components/table-spec.js
- spec/javascripts/components/toggle-input-class-on-focus-spec.js
- spec/javascripts/govuk_publishing_components/lib/govspeak/magna-charta-spec.js
- spec/javascripts/helpers/SpecHelper.js
- spec/javascripts/helpers/jasmine-jquery-2.0.5.js
Hi @JamesCGDS / @andysellick would you be able to approve this? Thanks :+1:
This PR removes the following `jasmine-jquery` helper functions and replaces them with a vanilla JS alternative:
- toBeDisabled()
- toBeHidden()
- toHaveClass()
- toHaveText()
- setFixtures() - this has just been copied over from `jasmine-jquery` instead of rewritten
This is being merged into `remove_jasmine_jquery_from_tests` first so there's no `CHANGELOG.md` commit.
The `jasmine-jquery` helper functions were causing https://github.com/alphagov/govuk_publishing_components/issues/2902 and so they have been replaced with a vanilla JS alternative. This also removes our tests' reliance on the `jasmine-jquery` library (which is no longer actively maintained).
> Remove jasmine jquery from tests 2

- CHANGELOG.md
- app/views/govuk_publishing_components/components/_label.html.erb
- app/views/govuk_publishing_components/components/docs/label.yml
- spec/components/label_spec.rb
[Trello ticket link](https://trello.com/c/oGsq2F3m/828-add-accessibility-improvements-to-preview-govspeak-component)
Add the `id` attribute option to the label component
Part of a body of work to improve accessibility of the [Preview Govspeak](https://github.com/alphagov/whitehall/blob/main/app/views/components/_govspeak-editor.html.erb) component in Whitehall (see [this PR](https://github.com/alphagov/whitehall/pull/7104)). In order for the Preview button to reference the label with `aria-describedby` the label must have an `id` attribute.
> Add `id` attribute option to the label component

- app/assets/javascripts/govuk_publishing_components/analytics-ga4/ga4-core.js
- spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-core.spec.js
Remove unused GTAG code from the GA4 analytics code.
No longer in use.
None.
Trello card: https://trello.com/c/gnixI84y/295-remove-gtag
> Remove GTAG code

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/analytics-ga4/ga4-event-tracker.js
- docs/analytics-ga4/ga4-event-tracker.md
- spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-event-tracker.spec.js
- adjusts the event tracker to include the text of the tracked element in the analytics by default
- the tracked value for text can still be overridden by adding a value to the data attribute
- brings the event tracker functionality more in line with how the link tracker behaves
Some print page buttons haven't been explicitly given a text value, so they're not including the text of the button in tracking. Seems more efficient to reconfigure the event tracker to automatically get the text instead of updating all the instances of tracking on the print page button.
None.
Trello card: https://trello.com/c/QFQG5IKA/363-change-some-values-on-printpage-events
> Make GA4 event tracker automatically get element text

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/analytics-ga4/ga4-page-views.js
- spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-page-views.spec.js
This PR renames the following parameters in the `page_view` object:
- `taxon_slug` to `taxonomy_main`
- `taxon_id` to `taxonomy_main_id`
- `taxon_slugs` to `taxonomy_all`
- `taxon_ids` to `taxonomy_all_ids`
The order of the parameters has also been modified slightly at the request of the PA's.
This change has been requested by PA's.
Related trello ticket: https://trello.com/c/vaOo3M8D/341-rename-themes-to-taxonomylevel1
N/A
> Rename taxon parameters

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
* Use setAttribute to add GA4 JSONs to step by step nav ([PR #3131](https://github.com/alphagov/govuk_publishing_components/pull/3131))
* Add `id` attribute option to the label component ([PR #3093](https://github.com/alphagov/govuk_publishing_components/pull/3093))
* Make GA4 event tracker automatically get element text ([PR #3137](https://github.com/alphagov/govuk_publishing_components/pull/3137))
* Rename taxon parameters ([PR #3139](https://github.com/alphagov/govuk_publishing_components/pull/3139))
* Use one button in navbar ([PR #3058](https://github.com/alphagov/govuk_publishing_components/pull/3058))
> Version 34.1.0

- CHANGELOG.md
- app/views/govuk_publishing_components/components/_cookie_banner.html.erb
The cookie banner is currently nested in two very similar regions:
```
<div id="global-cookie-message" role="region" aria-label="cookie banner" [...]>
<div class="govuk-cookie-banner js-banner-wrapper" role="region" aria-label="Cookies on GOV.UK">
```
That means there is a region announced as “cookie banner” which includes the another region called “Cookies on GOV.UK”.
This is confusing to screen reader users. Landmarks should be used sparingly and reflect the structure of the page. This structure should only be announced as one region.
By removing the `region` and `aria-label` from the outer element, we retain the full functionality of the component without needing to change the structure itself. Now only one region will be announced.
> Remove the redundant region role from the cookie banner

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/helpers/_brand-colours.scss
Change brand colour for No. 10 to be govuk-black instead of bright-purple.
As part of the new redesign of No. 10's page, the link colour is to be changed to black. The links are styled using brand__color, so there this needs to be updated to the new colour.
> Change brand colour for No. 10 to be govuk-black

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
* Update component auditing following print style changes ([PR #3128](https://github.com/alphagov/govuk_publishing_components/pull/3128))
* Remove the redundant region role from the cookie banner ([PR #3075](https://github.com/alphagov/govuk_publishing_components/pull/3075))
* Change brand colour for No. 10 to be govuk-black ([PR #3143](https://github.com/alphagov/govuk_publishing_components/pull/3143))
> Version 34.1.1

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
* Bump govuk-frontend from 4.4.0 to 4.4.1 ([PR #3147](https://github.com/alphagov/govuk_publishing_components/pull/3147))
> Version 34.1.2

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/_image-card.scss
Increase the space beneath list items on the image_card component.
To improve readability of multiple links.
> Increase space beneath list items on the image_card component

- CHANGELOG.md
- app/views/govuk_publishing_components/components/feedback/_yes_no_banner.html.erb
Trello: https://trello.com/c/lxxx5XLZ/178-govuk-has-a-half-implemented-content-security-policy-csp
This removes the usage of inline styles (`style="display:none;"`) on the feedback component.
To improve users security we intend to disallow the use of unsafe inline styles by the content security policy [1].
From my research these attributes were added as an idea that they may help reduce spam [2], however this did not resolve the spam problem and further attempts were made [3]. However this code was left in.
The process to update the CSP will take a while, we will first remove global offences like the below, then later remove unsafe-inline from the CSP with report-only on so we can discover if we have other offences and finally turn on the CSP. This should give us amble time to discover if …
> Remove inline styling from feedback component

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
* Remove inline styling from feedback component ([PR #3159](https://github.com/alphagov/govuk_publishing_components/pull/3159))
* Increase space beneath list items on the image_card component ([PR #3153](https://github.com/alphagov/govuk_publishing_components/pull/3153))
> Version 34.1.3

- spec/component_guide/component_example_accessibility_testing_spec.rb
- spec/dummy/app/views/components/_test-component-with-a11y-incomplete-warning.html.erb
- spec/dummy/app/views/components/docs/test-component-with-a11y-incomplete-warning.yml
This updates the test component with an accessibility incomplete warning to no longer use inline styles and a data:image.
We are intending to remove both the ability to set inline styles and the ability to use data images in the GOV.UK Content Security Policy [1]. This is because both of them offer potential security risks.
However a problem was that this test component relied on both of these. After much digging I found a different issue that could trigger an incomplete accessibility warning and I've converted the test to use that.
[1]: https://github.com/alphagov/govuk_app_config/blob/9b01e06d889be266501714e0dc0fc70a86e7e240/lib/govuk_app_config/govuk_content_security_policy.rb#L32-L65
None
> Replace data:image based test for a CSP friendly one

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
* Update the list of popular links in the super navigation header ([PR #3167](https://github.com/alphagov/govuk_publishing_components/pull/3167))
* Replace input search icon data:image with file asset ([PR #3163](https://github.com/alphagov/govuk_publishing_components/pull/3163))
> Version 34.2.0

- app/controllers/govuk_publishing_components/application_controller.rb
Fixes #2834 
This removes the CSP customisation that allowed unsafe_eval for viewing the components gem.
This use of unsafe_eval was required when we were using axe-core < 3.31 [1]. We are now using version 4.6.1 so can remove this code.
[1]: https://github.com/dequelabs/axe-core/pull/1707
None
> Remove the content security policy unsafe eval customisation

- spec/features/contextual_navigation_spec.rb
This resolves a number of tests that fail intermittently (see below). These tests would fail based on random schema generation, the failure would occur when the random document type selected for the placeholder schema was html_publication, which has an additional request to the content store [1].
This can be resolved by switching the schema that is used by default to not have randomly selected document types. This allows avoiding non-deterministic behaviour.
Intermittent tests:
```
rspec ./spec/features/contextual_navigation_spec.rb:25 # Contextual navigation There's a mainstream browse page tagged
rspec ./spec/features/contextual_navigation_spec.rb:38 # Contextual navigation The page has curated related items
rspec ./spec/features/contextual_navigation_spec.rb:87 # Contextual navigation …
```
> Fix flaky contextual navigation tests

- CHANGELOG.md
- app/views/govuk_publishing_components/components/_google_tag_manager_script.html.erb
- app/views/govuk_publishing_components/components/_layout_for_admin.html.erb
- app/views/govuk_publishing_components/components/_layout_for_public.html.erb
- app/views/govuk_publishing_components/components/feedback/_problem_form.html.erb
- app/views/layouts/govuk_publishing_components/application.html.erb
This changes the approach to adding inline script to components. If an app has a [Rails nonce configured][3] this will add the nonce attribute to the script tags. If an app does not have a nonce generator configured then the script tag will not be given a nonce attribute. In order to implement this fully to GOV.UK there will also be changes needed in Slimmer to inject nonces into layouts, which will come later.
This has been put together so that govuk_publishing_components can have the aspirational CSP for GOV.UK implemented before other apps, so that any indiscretions don't get introduced into components.
Before:
```
<script>
document.body.className = ((document.body.className) ? document.body.className + ' js-enabled' : 'js-enabled');
</script>
```
After (with nonce generator …
> Support Rails Content Security Policy nonce on inline JavaScript

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/_subscription-links.scss
- app/views/govuk_publishing_components/components/_subscription_links.html.erb
Removes the border-bottom from 'Get Emails' subscription link from the subscription links component in the 'with copyable feed' variant. Restores the default link underline style.
This was a request from a designer and is part of the No. 10 organisation page redesign.
> Restyle subscription link

- CHANGELOG.md
- app/views/govuk_publishing_components/components/_error_message.html.erb
- app/views/govuk_publishing_components/components/_hint.html.erb
- app/views/govuk_publishing_components/components/_input.html.erb
- app/views/govuk_publishing_components/components/_label.html.erb
- app/views/govuk_publishing_components/components/_textarea.html.erb
- app/views/govuk_publishing_components/components/docs/error_message.yml
- app/views/govuk_publishing_components/components/docs/hint.yml
- app/views/govuk_publishing_components/components/docs/input.yml
- app/views/govuk_publishing_components/components/docs/label.yml
- app/views/govuk_publishing_components/components/docs/textarea.yml
- spec/components/error_message_spec.rb
- spec/components/hint_spec.rb
- spec/components/input_spec.rb
- spec/components/label_spec.rb
- spec/components/textarea_spec.rb
Extends input and textarea components to accept a value for the `dir` attribute
In a previous piece of work (see[ Add RTL support for attachments](https://trello.com/c/RT5RbtmT/896-add-rtl-support-for-attachments)) we added support for right-to-left languages to the attachments pages on the Whitehall publishing app. This was done by adding a class to the parent of the `input` and `textarea` elements that would be used by CSS to render the text correctly. It became clear that it would be a more elegant and semantic solution to achieve this by use of the `dir` attribute of the elements. In addition this is recommended practice for instances where CSS is not loaded. 
Currently these components do not accept a value for that attribute so the changes here update these components accordingly. …
> Extend the `input` and `textarea` components to use the `dir` attribute

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/_feedback.scss
The focus state of the Yes/No buttons in the feedback component are not different enough compared to the non-focus state to be fully accessible. [Trello](https://trello.com/c/ZHN94FVx/1496-feedback-component-button-focus-states-not-fully-accessible-s)
It will be difficult for people with visual impairments to distinguish the two states.
This might fail [WCAG 2.4.11 Focus Appearance](https://www.w3.org/TR/WCAG22/#focus-appearance) (which might become a new success criterion in WCAG 2.2). The yellow/grey doesn’t pass (1.2:1) and the reduction of 1px to the bottom doesn’t help enough.
It also nearly fails [WCAG 1.4.11 Non-text Contrast](https://www.w3.org/TR/WCAG21/#non-text-contrast) but technically passes because the bottom border changes its width a tiny bit.
[GOV.UK](http://gov.uk/) …
> Improve accessibility of button focus states

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
* Support Rails Content Security Policy nonce on inline JavaScript ([PR #3173](https://github.com/alphagov/govuk_publishing_components/pull/3173))
* Restyle subscription link ([PR #3177](https://github.com/alphagov/govuk_publishing_components/pull/3177))
* Change "+" to "Show" in related navigation and metadata block components ([PR #3038](https://github.com/alphagov/govuk_publishing_components/pull/3038))
* Extend the `input` and `textarea` components to use the `dir` attribute ([PR #3081](https://github.com/alphagov/govuk_publishing_components/pull/3081))
* Improve accessibility of button focus states ([PR #3146](https://github.com/alphagov/govuk_publishing_components/pull/3146))
> Version 34.3.0

- CHANGELOG.md
- app/views/govuk_publishing_components/components/_contextual_footer.html.erb
- app/views/govuk_publishing_components/components/_contextual_sidebar.html.erb
- app/views/govuk_publishing_components/components/_related_navigation.html.erb
- app/views/govuk_publishing_components/components/docs/contextual_footer.yml
- app/views/govuk_publishing_components/components/docs/contextual_sidebar.yml
- app/views/govuk_publishing_components/components/docs/related_navigation.yml
- app/views/govuk_publishing_components/components/related_navigation/_section.html.erb
- lib/govuk_publishing_components/presenters/page_with_step_by_step_navigation.rb
- lib/govuk_publishing_components/presenters/related_navigation_helper.rb
- spec/components/related_navigation_spec.rb
Adds Google Analytics 4 tracking to the sidebar and footer sections using the existing [ga4-link-tracker](https://github.com/alphagov/govuk_publishing_components/blob/main/docs/analytics-ga4/ga4-link-tracker.md).
The [Related Navigation component](https://components.publishing.service.gov.uk/component-guide/related_navigation) shows a series of links. It is usually seen in the sidebar of a page but not exclusively. It includes some logic for which sections are displayed in different contexts, which is used when it is wrapped by other components.
- adds a `ga4_tracking` option that then adds relevant attributes to links as well as adding `ga4-link-tracker` into the `data-module` attribute
- changes how JS modules for tracking are enabled. UA tracking is enabled by default, so this change …
> Add GA4 tracking to related navigation

- spec/dummy/config/initializers/content_security_policy.rb
This customises the content security policy (CSP) configuration for the dummy app of the component gem to use the CSP that GOV.UK is working towards applying. This only affects running the component gem as an app so not a change for users of this gem.
It is expected to be removed in the near future once the GOV.UK global CSP applies the same rules, and won't have negative effects if the GOV.UK CSP is changed without this changing.
This has been done so that developers working with the component gem are working with the rules we are aiming for to avoid any regressions and learn of any problems.
None
> Use upcoming CSP rules when using component gem

- CHANGELOG.md
- app/views/govuk_publishing_components/components/docs/emergency_banner.yml
- app/views/govuk_publishing_components/components/docs/intervention.yml
- app/views/govuk_publishing_components/components/docs/layout_header.yml
- app/views/govuk_publishing_components/components/docs/previous_and_next_navigation.yml
- app/views/govuk_publishing_components/components/docs/translation_nav.yml
Disable axe-core rules for issues highlighted in component guide:
- `duplicate-id-aria`
- `duplicate-id`
- `landmark-unique`
The issues are highlighted because there are multiple instances of components, per page, in the component guide.
It's unlikely these issues would ever be seen because typically only one of these components would be deployed on any page e.g. **emergency banner**, **layout header**.
> Disable axe-core rules for issues highlighted in component guide

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
* Add GA4 tracking to related navigation ([PR #3179](https://github.com/alphagov/govuk_publishing_components/pull/3179))
* Add Youtube Embed Support to the ImageCard Component ([PR #3156](https://github.com/alphagov/govuk_publishing_components/pull/3156))
* Remove dependency on .js.erb and puppet for loading our analytics ([PR #3145](https://github.com/alphagov/govuk_publishing_components/pull/3145))
* Disable axe-core rules for issues highlighted in component guide ([PR #3180](https://github.com/alphagov/govuk_publishing_components/pull/3180))
> Version 34.4.0

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/dependencies.js
Hi @andysellick,
Would you be able to approve this if all is OK? 
Thanks :+1:
We want the analytics to load in if it hasn't been already, which is why we check for `undefined` values, and load in analytics if the values are undefined.
However, our tests do not import `load-analytics.js` by default, so having a nested check like `window.GOVUK.analyticsGa4.vars` resulted in an error in our tests, as `window.GOVUK.analyticsGa4` didn't exist, so we couldn't run a check on `window.GOVUK.analyticsGa4.vars` without the JS crashing.
Therefore I have added extra if statements which ensure this code only runs when we can guarantee that `load-analytics.js` has been imported.
I've checked this against the Jasmine tests in `frontend`, `finder-frontend`, and `government-frontend` and they're now …
> Fix bug where analytics tries to init in tests which don't import it

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
* Fix bug where analytics tries to init in tests which don't import it ([PR #3185](https://github.com/alphagov/govuk_publishing_components/pull/3185))
> Version 34.4.1

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/analytics/auto-scroll-tracker.js
- app/assets/javascripts/govuk_publishing_components/dependencies.js
- Moves our modules to start after analytics has loaded, copying the order it ran in `static`.
- Ensures `window.GOVUK.analyticsVars` and `window.GOVUK.analyticsGa4` exist before other code runs.
- Some of the modules required Universal Analytics to exist, so we should load our analytics first to reduce the risk of crashing JavaScript. I have also ensured auto-scroll-tracker isn't relying on a different module initialising window.GOVUK.analyticsVars.
`AutoScrollTracker` crashed because it tried to access `window.GOVUK.analyticsVars` before it existed, which broke the accordions in `collections`.
None.
> Load modules after analytics has loaded

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
* Load modules after analytics has loaded ([PR #3187](https://github.com/alphagov/govuk_publishing_components/pull/3187))
> Version 34.4.2

- .github/workflows/ci.yml
- Gemfile.lock
Ruby 3.2 was released on December 25th 2022
> Test against Ruby 3.2

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/modules.js
- spec/javascripts/govuk_publishing_components/modules.spec.js
- wraps the initialisation of module JavaScript on a page with a try/catch block, so that if an error occurs in one module initialisation continues to the next without aborting and breaking all of the JS that follows
We've had some recent problems where an error in a single bit of JS caused all of the following JS to also fail.
None.
All credit goes to @AshGDS for thinking of this idea.
> Catch errors when modules initialised

- CHANGELOG.md
- app/views/govuk_publishing_components/components/_image_card.html.erb
- spec/components/image_card_spec.rb
This PR adds `ga4-link-tracker` to the `data-module` attribute on the `_image_card` component.
We are adding tracking to links on the homepage, which uses image cards.
[Trello card](https://trello.com/c/WAST3s6v/392-add-tracking-homepage)
N/A
> Add ga4-link-tracker to image card

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/load-analytics.js
Change console.error to console.warn as it breaks Smokey tests.
Domains such as [assets.integration.publishing.service.gov.uk](http://assets.integration.publishing.service.gov.uk/) try to load our analytics but they aren't listed as a domain which loads our GA4. So the `console.error` would display. But smokey seems to treat a `console.error` as the JavaScript breaking.
None.
> Change console.error to console.warn as it breaks Smokey tests

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
* Change console.error to console.warn as it breaks Smokey tests ([PR #3210](https://github.com/alphagov/govuk_publishing_components/pull/3210))
> Version 34.5.1

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
* Revert load-analytics commits due to Smokey test failure ([PR #3212](https://github.com/alphagov/govuk_publishing_components/pull/3212))
> Version 34.6.0

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/load-analytics.js
- spec/javascripts/govuk_publishing_components/load-analytics.spec.js
We missed the assets domain off of our list of GOVUK domains, so both UA and GA4 are not running on these types of links:
https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/1006267/Annex_B_-_Example_CSV_file_-_Appeals_in_vocational_and_technical_qualifications_-_guide_to_the_data_submission_process.csv/preview
Our tracking should be running on this domain
None.
> Add our 'assets' domain as a domain that should run our analytics

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/govspeak/_tables.scss
- app/views/govuk_publishing_components/components/docs/govspeak.yml
Trello: https://trello.com/c/lxxx5XLZ/178-govuk-has-a-half-implemented-content-security-policy-csp
This change is made to support the proposed change in: https://github.com/alphagov/govspeak/pull/268, which is made to allow for GOV.UK to use a Content Security Policy that can help prevent Cross-site scripting (XSS) attacks. This change will need to be merged and released first.
This adds three classes that can be used within `.gem-c-govspeak table` to set the text alignment of cells. These are required because the Govspeak output for text aligned cells is going to change from an inline style (`<td style="text-align: right;">item</td>`) to a class (`<td class="cell-text-right">item</td>`)
Class naming wise, I didn't use a BEM approach as there did not to be precedent for it in the classes …
> Add classes to align text in Govspeak tables

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/_document-list.scss
- app/views/govuk_publishing_components/components/_document_list.html.erb
- app/views/govuk_publishing_components/components/docs/document_list.yml
- spec/components/document_list_spec.rb
https://trello.com/c/dhg330gw/1785-remove-grey-top-border-on-the-top-item-on-the-list-on-specialist-finders
Add an option `remove_top_border_from_first_child` to remove the top border from the first item of a document list.
**Review URL**
https://components-gem-pr-3221.herokuapp.com/component-guide/document_list/without_top_border_on_first_list_element/preview
On some finder pages e.g. [Air Accidents Investigation Branch reports](https://www.gov.uk/aaib-reports) a double border can be seen when no sort options are present.
The current `remove_top_border` option removes the top border from every item. The new option `remove_top_border_from_first_child` will remove the top border from the first item only.
Will need to adjust padding in …
> Add document list component option to remove first item top border

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/analytics-ga4/init-ga4.js
- spec/javascripts/govuk_publishing_components/analytics-ga4/init-ga4.spec.js
Wraps the initialisation of each GA4 analytics module in a try/catch block, which means that any errors in the initialisation of a module will not prevent any following modules from initialising.
Follows on from this [similar change](https://github.com/alphagov/govuk_publishing_components/pull/3190) to the main modules systems, which prevents an individual module failing from stopping all following modules from initialising.
None.
> Add GA4 modules error checking

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
* Add GA4 modules error checking ([PR #3228](https://github.com/alphagov/govuk_publishing_components/pull/3228))
* Add classes to align text in Govspeak tables ([PR #3217](https://github.com/alphagov/govuk_publishing_components/pull/3217))
* Make links bold at all viewports on navbar menu ([PR #3219](https://github.com/alphagov/govuk_publishing_components/pull/3219))
* Add our 'assets' domain as a domain that should run our analytics ([PR #3224](https://github.com/alphagov/govuk_publishing_components/pull/3224))
* Add document list component option to remove first item top border ([PR #3221](https://github.com/alphagov/govuk_publishing_components/pull/3221))
* Allow a tracked ga4 link to be hardcoded via its ga4-link JSON ([PR #3227](https://github.com/alphagov/govuk_publishing_components/ …
> Version 34.7.0

- CHANGELOG.md
- lib/govuk_publishing_components/presenters/related_navigation_helper.rb
- spec/components/contextual_footer_spec.rb
- spec/components/related_navigation_spec.rb
- spec/lib/govuk_publishing_components/presenters/related_navigation_helper_spec.rb
We are currently creating the URL of World Location related links by using the World Location's name.
However there are multiple examples where the name does not match the slug (e.g. an acronym in the slug, but spelt out in full in the name).
This was attempted to be solved by hardcoding a list of special cases, but that list has now become out of date.
Since the content item already includes the base path (which will always be up-to-date), we should use that and remove the list of exceptions.
There are currently broken related links on documents that link to World Locations.
> Use the base path for World Location related links

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
Bumps the gem to version 34.7.1.
This includes a bug fix for world location related links.
> Bump version to 34.7.1

- CHANGELOG.md
- app/views/govuk_publishing_components/components/_details.html.erb
- app/views/govuk_publishing_components/components/docs/details.yml
- spec/components/details_spec.rb
Add aria attributes to the Details component.
As part of the work to make the organisations page on GOV.UK more accessible. There is currently the following issue with the page:
> On the Departments, agencies and public bodies page, multiple buttons are present which began with the phrase "Works with" and contain the number of agencies or public bodies the organisation worked with. Many of these buttons have the same text occurring multiple times. For example, there are 23 occurrences of Works with 1 public body each of which relate to different department, agency or public body. Therefore, it's unclear in many instances which button related to which department, agency or public body which makes it difficult for screen reader users to differentiate between them.
@hannalaakso did some …
> Add aria attributes to Details component

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/analytics-ga4.js
- app/assets/javascripts/govuk_publishing_components/analytics-ga4/ga4-event-tracker.js
- app/assets/javascripts/govuk_publishing_components/analytics-ga4/ga4-form-tracker.js
- app/assets/javascripts/govuk_publishing_components/analytics-ga4/ga4-link-tracker.js
- app/assets/javascripts/govuk_publishing_components/analytics-ga4/ga4-schemas.js
- app/assets/javascripts/govuk_publishing_components/analytics-ga4/ga4-specialist-link-tracker.js
- docs/analytics-ga4/ga4-form-tracker.md
- spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-form-tracker.spec.js
Adds a script to track form submissions in GA4. Should be clearly documented in the `md` file, brief summary:
- requires `data-ga4-form` attribute on the form, containing some information
- fires on form submission
- identifies answer(s) chosen by searching through label elements to find inputs (label first, because we need the label text and a label is linked to an input using the `for` attribute, but not vice versa)
- redacts any answers given in a text input, to prevent the collection of PII
Originally tried to use `formData` for this, which isn't fully supported by IE11. Fallback was that IE11 users wouldn't have their answers recorded. However the syntax for accessing formData was causing IE11 to throw an error, so have switched to a more traditional approach.
Needed for smart …
> Add GA4 Form tracker

- CHANGELOG.md
- lib/govuk_publishing_components/presenters/related_navigation_helper.rb
- spec/components/contextual_footer_spec.rb
- spec/components/related_navigation_spec.rb
- spec/lib/govuk_publishing_components/presenters/related_navigation_helper_spec.rb
From raised Zendesk ticket: https://govuk.zendesk.com/agent/tickets/5207548
The [PR implementing the change](https://github.com/alphagov/govuk_publishing_components/pull/3102/commits/727cf81008226df642c832b0a11da14394538723) in how we fetch base_paths for world_locations caused the world location related links to redirect back to the same page. 
This occurred as the logic was changed to fetch the `base_path` from the links hash but the `base_path` isn't part of the included attributes for world locations and so the path (href) was blank [1] which causes the behaviour of redirecting back to the original page.
`base_paths` generated by parameterising the title is still flawed as it generates some broken links, however most links should now work after this revert. We should implement the …
> Revert world locations base_path change

- CHANGELOG.md
- app/views/govuk_publishing_components/components/_single_page_notification_button.html.erb
- app/views/govuk_publishing_components/components/docs/single_page_notification_button.yml
- lib/govuk_publishing_components/presenters/single_page_notification_button_helper.rb
- spec/components/single_page_notification_button_spec.rb
Support non account sign up flow from the single page notification button component
If the `skip_account` attribute is set:
- The form action of the component will be set to `/email-signup`. This is a route served by email-alert-frontend which does not enforce the GOV.UK account.  It's used by the [subscription links component ](https://components.publishing.service.gov.uk/component-guide/subscription_links) on [topic pages](https://www.gov.uk/topic/benefits-credits/child-benefit) and other doc types. The default form action will remain `/email/subscriptions/single-page/new`, which is the endpoint served my email-alert-frontend that enforces the GOV.UK account )
- Two params will be added to the request
-  `single_page_subscription` that will be used by email alert frontend to set the …
> Update single page notification button to support skipping GOV.UK account

- README.md
- docs/test-a-branch-of-the-gem.md
Adding documentation for testing a branch of the gem.
- was originally in dev docs, but multiple people expressed an inability to find it
- removing from dev docs (originally at https://docs.publishing.service.gov.uk/manual/test-a-branch-of-the-components-gem.html)
- adding it here to the gem will automatically include it in dev docs anyway
- copied with no changes
None.
> Add documentation for testing a branch

- CHANGELOG.md
- config/locales/en.yml
- spec/components/layout_for_public_spec.rb
Link name changes for GOV.UK One Login
GOV.UK One Login official name change on 9th February 2023.
https://trello.com/c/EbkPjP8y/1817-thursday-9th-feb-email-alerts-pr-approvals-for-digital-identity-accounts-team
> GOV.UK account name change

- CHANGELOG.md
- app/views/govuk_publishing_components/components/docs/single_page_notification_button.yml
Small copy update in component publishing guide
GOV.UK Account now GOV.UK One Login, maintain consistent use.
> Tweak text in component guide

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
* Update Component Guide skip_account to mention GOV.UK One Login ([PR #3247](https://github.com/alphagov/govuk_publishing_components/pull/3247))
* Update "Account" copy to "GOV.UK One Login" ([PR #3246](https://github.com/alphagov/govuk_publishing_components/pull/3246))
> Release v34.9.1

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/analytics-ga4.js
- app/assets/javascripts/govuk_publishing_components/analytics-ga4/ga4-auto-tracker.js
- docs/analytics-ga4/ga4-auto-tracker.md
- spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-auto-tracker.spec.js
Adds a GOVUK JavaScript module that when attached to a page with the right data attributes sends data to GA4 when the page loads. Initially for use on error pages in smart answers to send an event detailing the error.
Needed for the GA4 work with smart answers.
None.
Trello card: https://trello.com/c/xf2dDOBN/407-add-tracking-smart-answers-formerror
> Add GA4 auto tracker

- CHANGELOG.md
- app/views/govuk_publishing_components/components/_contextual_sidebar.html.erb
- app/views/govuk_publishing_components/components/contextual_sidebar/_ukraine_cta.html.erb
- app/views/govuk_publishing_components/components/docs/contextual_sidebar.yml
- spec/components/contextual_sidebar_spec.rb
Adds tracking to the Ukraine CTA on pages such as: https://www.gov.uk/foreign-travel-advice/ukraine
This tracking is based on the tracking already implemented for the Related Navigation component, but uses 'Invasion of Ukraine' as the value for `section`. The link index is based on the link position but is always prefixed with `1` because there is only one list of links in this section.
None.
Trello card: https://trello.com/c/ml0rt88c/420-add-tracking-to-ukraine-call-out-box
> Add GA4 tracking to contextual sidebar Ukraine CTA

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/analytics-ga4/ga4-core.js
- app/assets/javascripts/govuk_publishing_components/analytics-ga4/ga4-page-views.js
- spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-page-views.spec.js
Hi @andysellick / @JamesCGDS - could one of you review this please? Thanks :+1:
Converts two PageView values from strings into objects. These objects contain their string split up into 5 parts, with each part being 100 character segments of the original string.
GA4 only allows strings to be a maximum of 100 characters. There are two pageview values that sometimes contain strings that are over 100 characters. For example, on https://gov.uk/business-support-helpline you have:
```JSON
{
"taxonomy_all": "finance-support,premises-rates,company-closure-administration-liquidation-and-insolvency,contract-working-hours,dismissals-redundancies,food-and-farming-industry,producing-distributing-food-food-labelling,recruiting-hiring,recruiting-hiring,redundancies-dismissals,sale-goods-services-data,scie …
```
> Use string splitter on taxonomyAll and taxonomyAllIds pageview values

- app/assets/javascripts/govuk_publishing_components/analytics-ga4/ga4-core.js
Adds an error check to the populateLinkDomain function in ga4-core.
- code assumed that regex to get domain would succeed, but future work for the intervention banner where a link has a href of ?hide-intervention=true caused this code to error
- now checks to see if the regex was successful before returning anything
None.
> Add error checking for populateLinkDomain

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/_layout-super-navigation-header.scss
Although some of the links on navbar use larger clickable areas on mobile viewports, this does not take into account users using touchscreens at larger viewports. This PR increases the touch areas for topic links in mobile viewport, topic links in desktop viewport and popular links in all viewports. It uses the already existing mixin in the layout-super-navigation-header.
For users who have trouble controlling their mouse, having the touch target limited to the link itself (for example the links in the Topics section of the menu) means it can be tricky to select with an unsteady hand. Could also make it difficult to click links if user a using a large touchscreen.
[Relevant Trello Card](https://trello.com/c/AMSVEJpN/1572-touch-targets-for-selecting-links-in-menu-could-be-bigger-s)
> Increase clickable area for links in navbar

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/analytics-ga4/ga4-core.js
- spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-core.spec.js
- Previously we were checking if a URL was relative by the presence of a slash at the start of the href. We would also check if a URL was an anchor link by the presence of a `#` at the start of the href.
- This method was not accounting for all cases of relative hrefs. For example, a href starting with `?` is a valid relative href.
- Therefore, we now check if the href is relative or an anchor link by the lack of a domain name at the start of the href. In other words, if the href doesn't contain http://domain.example, https://domain.example, or //domain.example, then we assume the href is a relative href or anchor link.
This should cover all the types of relative hrefs and anchor links. Our tests pass against all these examples of relative URLs from RFC 1808 …
> Cover all types of relative hrefs in hrefIsRelative function

- CHANGELOG.md
- app/views/govuk_publishing_components/components/related_navigation/_section.html.erb
- lib/govuk_publishing_components/presenters/related_navigation_helper.rb
- Ensures that the `section` value on our Related Navigation tracking is always English so that we can understand the text in the analytics dashboard.
- The headings on our Related Navigation `section` elements get translated, however for the purpose of analysis we always want it to be English, so that everything is tracked under the same label even if they are translated. This keeps the analytics under one label instead of different labels for each language.
None.
> Force English text on our GA4 related navigation section tracking

- CHANGELOG.md
- app/views/govuk_publishing_components/components/_breadcrumbs.html.erb
- app/views/govuk_publishing_components/components/docs/breadcrumbs.yml
- lib/govuk_publishing_components/presenters/breadcrumbs.rb
- spec/components/breadcrumbs_spec.rb
Hi @JamesCGDS, would you be able to review this? Thanks :+1:
- Adds the `ga4-link-tracker` to our Breadcrumbs component.
- It's one of the interactions on our to do list.
- I didn't create a boolean called `ga4_tracking: true` that toggles wether tracking is enabled. My thinking is that if we used a `ga4_tracking` boolean, we would have to add `ga4_tracking: true` to each frontend app, which might become a challenge to deploy and maintain, as some apps have multiple breadcrumb renders (e.g. `collections` has 6.) As well as this, the UA tracking doesn't have a toggler (it is always enabled by default on all breadcrumbs), so just adding the ga4 stuff directly into the component without a toggler replicates the existing functionality we have for tracking.
None.
> Add GA4 tracking to our breadcrumbs

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/analytics-ga4/ga4-core.js
- app/assets/javascripts/govuk_publishing_components/analytics-ga4/ga4-smart-answer-results-tracker.js
This PR contains two small changes to the smart answers results tracking:
- Moves a call to `textContent()` a little later in the code as this was causing errors when calling it on a node that didn't exist
- Checks that elements with a `data-ga4-ecommerce-path` data attribute exist before tracking results and attaching event listeners
Prevents this code from erroring and running where it isn't needed
N/A
> Fix smart answer results tracking

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
* Increase clickable area for links in navbar ([PR #3238](https://github.com/alphagov/govuk_publishing_components/pull/3238))
* Cover all types of relative hrefs in hrefIsRelative function ([PR #3251](https://github.com/alphagov/govuk_publishing_components/pull/3251))
* Force English text on our GA4 related navigation section tracking ([PR #3259](https://github.com/alphagov/govuk_publishing_components/pull/3259))
* Add ga4 tracking smart answer results ([PR #3235](https://github.com/alphagov/govuk_publishing_components/pull/3235))
* Add GA4 tracking to our breadcrumbs ([PR #3257](https://github.com/alphagov/govuk_publishing_components/pull/3257))
* Make Navbar Menu Relatively Positioned Instead of Absolutely Positioned ([PR #3201](https://github.com/alphagov/govuk_publishing_components/pul …
> Version 34.11.0

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/analytics-ga4/ga4-form-tracker.js
- app/views/govuk_publishing_components/components/_layout_super_navigation_header.html.erb
- docs/analytics-ga4/ga4-form-tracker.md
- spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-form-tracker.spec.js
Adds tracking to the search box inside the site header.
Also modifies the GA4 form tracker to include an option to not redact text in text inputs (and search inputs) and applies this to the search box, so that we include user searches in tracking data.
Part of the GA4 implementation work.
None.
Trello card: https://trello.com/c/LNE9OTXb/427-add-tracking-search-box-on-the-header-menu-bar
> Apply GA4 tracking to site header search box

- app/assets/javascripts/govuk_publishing_components/analytics-ga4/ga4-form-tracker.js
- the form tracker (when configured to collect values from text inputs) strips PII from that value
- this only included the default things (see PII doc for list) and not dates or postcodes
- changing this to use PII strip override, which redacts everything possible
Part of the GA4 work, plus we don't want to collect any PII.
None.
Trello card: https://trello.com/c/LNE9OTXb/427-add-tracking-search-box-on-the-header-menu-bar
> Enable strip PII override in GA4 form tracker

- CHANGELOG.md
- app/views/govuk_publishing_components/components/docs/related_navigation.yml
- app/views/govuk_publishing_components/components/related_navigation/_section.html.erb
- spec/components/related_navigation_spec.rb
- on related navigation, [where world locations exceed 5 items](https://components.publishing.service.gov.uk/component-guide/related_navigation/with_extensive_world_locations), a toggle link to display the rest is shown
- add GA4 tracking to this link, where GA4 tracking has been enabled
Example URL: https://www.gov.uk/guidance/appoint-someone-to-deal-with-customs-on-your-behalf
Part of the GA4 work.
None.
Trello card: https://trello.com/c/OhcANGS4/422-add-tracking-show-more-interaction-click-on-related-content
> Add GA4 tracking to related navigation component 'show more' link

- CHANGELOG.md
- app/models/govuk_publishing_components/audit_components.rb
- app/views/govuk_publishing_components/audit/_components.html.erb
- spec/component_guide/audit_components_spec.rb
- spec/dummy_gem/app/views/govuk_publishing_components/components/_test_component.html.erb
Expands the component auditing to audit which components use some of our shared helper code, specifically the brand helper, component wrapper helper, heading helper and shared helper. 
You can find this by running the component guide locally and following the 'audit' link from the main page.
The component wrapper helper is probably going to take on some of the work of the shared helper, so we'll eventually be migrating code from one to the other, so it's helpful to know which components use it.
Also generally useful to know which components rely on different bits of code.
New section added to the auditing page:
> Add helpers by component to auditing

- CHANGELOG.md
- lib/govuk_publishing_components/presenters/related_navigation_helper.rb
Instead of "en" otehrwise this test in Frontend:
https://github.com/alphagov/frontend/actions/runs/4235734374/jobs/7359722094#step:7:19
was broken. I fixed the test as part of https://github.com/alphagov/frontend/pull/3551/commits/94f20061d045bd0c1ab0e03b138827f255066027 but that depends on this PR.
> Set ga 4 related links locale as :en

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
* Set up individual component CSS loading, **Note:** this change is experimental, it will be used in the `frontend` application first, please do not implement this feature in other applications ([PR #3342](https://github.com/alphagov/govuk_publishing_components/pull/3342))
* Set ga 4 related links locale as :en ([PR #3273](https://github.com/alphagov/govuk_publishing_components/pull/3273))
> Version 34.13.0

- CHANGELOG.md
- app/views/govuk_publishing_components/components/_contextual_breadcrumbs.html.erb
- app/views/govuk_publishing_components/components/_step_by_step_nav_header.html.erb
- app/views/govuk_publishing_components/components/docs/contextual_breadcrumbs.yml
- app/views/govuk_publishing_components/components/docs/step_by_step_nav_header.yml
- docs/analytics-ga4/ga4-link-tracker.md
- lib/govuk_publishing_components/presenters/breadcrumb_selector.rb
- lib/govuk_publishing_components/presenters/page_with_step_by_step_navigation.rb
- spec/lib/govuk_publishing_components/presenters/page_with_step_by_step_navigation_spec.rb
Adds tracking to the super breadcrumb.
In order to provide the capability of toggling GA4 tracking on and off, a `ga4_tracking` boolean is passed to the `step_by_step_nav_header` component (the component responsible for rendering the super breadcrumb) where it is used to determine whether GA4 data attributes should be included in the HTML. In order for this to work, a `ga4_tracking` parameter has been added to the `page_with_step_by_step_navigation` and `breadcrumb_selector` presenters (without these changes, the template would return an error stating that the incorrect number of parameters had been passed).
N/A
Trello card: https://trello.com/c/AM5JCKEd/430-add-tracking-to-super-breadcrumbs
> Add GA4 tracking to the super breadcrumb

- CHANGELOG.md
- app/views/govuk_publishing_components/components/_contextual_sidebar.html.erb
- app/views/govuk_publishing_components/components/_step_by_step_nav_related.html.erb
- app/views/govuk_publishing_components/components/docs/contextual_sidebar.yml
- app/views/govuk_publishing_components/components/docs/step_by_step_nav_related.yml
- spec/components/step_by_step_nav_related_spec.rb
Adds tracking to links in the step by step "Part of" heading in the related navigation sidebar.
This component is rendered by calling the `contextual_sidebar` component, which already has had the `ga4_tracking` boolean added wherever it is called as part of previous GA4 PR's. In other words, the only PR required to activate this tracking is this one and won't require PR's for enabling tracking to be raised in other applications.
N/A
Trello card: https://trello.com/c/I0gafCaw/429-add-tracking-for-part-of-step-by-steps-related-content
> Add ga4 tracking to 'part of' heading

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
* Change how GA4 index parameter works ([PR #3277](https://github.com/alphagov/govuk_publishing_components/pull/3277))
* Add GA4 tracking to the super breadcrumb ([PR #3272](https://github.com/alphagov/govuk_publishing_components/pull/3272))
* Add ga4 tracking to 'part of' heading ([PR #3284](https://github.com/alphagov/govuk_publishing_components/pull/3284))
> Version 34.14.0

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/analytics-ga4/ga4-link-tracker.js
- app/assets/javascripts/govuk_publishing_components/analytics-ga4/pii-remover.js
- spec/javascripts/govuk_publishing_components/analytics-ga4/pii-remover.spec.js
Dates were being recorded on change response events - this PR redacts them
When changing a form response on smart answers, dates that are in string format are being recorded and this is a PII issue. Therefore, this PR redacts the dates and replaces them with `[date]` (e.g. `1 January 1990` is replaced with `[date]`).
Addresses a PII issue.
N/A
Trello card: https://trello.com/c/dWFDOLAV/433-smart-answer-bugs-formchangeresponse
> Fix smart answer PII issue

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/components/accordion.js
- app/views/govuk_publishing_components/components/_accordion.html.erb
- spec/components/accordion_spec.rb
- spec/javascripts/components/accordion-spec.js
- in line with changes to the index parameter, explicitly define index as index_section, remove index_total and use that value for index_section_count
Part of the GA4 migration work.
None.
Trello card: https://trello.com/c/8tNN5gGX/426-change-the-index-parameter
> Update accordion index parameter

- CHANGELOG.md
- app/models/govuk_publishing_components/audit_applications.rb
- app/models/govuk_publishing_components/audit_comparer.rb
- app/views/govuk_publishing_components/audit/_applications.html.erb
- spec/component_guide/audit_applications_spec.rb
- spec/component_guide/audit_comparer_spec.rb
Resolves a few issues with the component auditing. Specifically:
- fixes a silent problem introduced when the data structure changed in a recent update
- removes print stylesheet auditing, as we no longer have separate print styles for components
- adds a count to the component references found in applications
Mentions of print stylesheets have been removed from the auditing pages.
Counts have been added to the lists of components in applications:
> Fix component auditing

- CHANGELOG.md
- app/views/govuk_publishing_components/components/_step_by_step_nav.html.erb
- app/views/govuk_publishing_components/components/docs/step_by_step_nav.yml
- lib/govuk_publishing_components/presenters/step_by_step_nav_helper.rb
- spec/components/step_by_step_nav_spec.rb
Adds link tracking to the step by step navigation links. Uses the `ga4-link-tracker`.
You can test it by running `collections` with a local version of publishing components and going to http://127.0.0.1:3070/learn-to-drive-a-car. You will then see the `ga4-link` attribute on the links within each step.
I've used the new `index` way of tracking, so let me know if I've implemented it incorrectly.
It's on our list of things to implement.
Trello card: https://trello.com/c/TI06lTIG/431-add-tracking-step-by-step-links
None.
> Add GA4 tracking to step by step links

- CHANGELOG.md
- app/views/govuk_publishing_components/components/_tabs.html.erb
- app/views/govuk_publishing_components/components/docs/tabs.yml
- spec/components/tabs_spec.rb
- previously relied on manually passing data attributes per tab from the application to the component
- but no actual need for this, attributes can be determined inside the component, and simply activated by setting ga4_tracking to true
- does not represent a breaking change as options can be switched over later once this is deployed
Example of current tracking on tabs for comparison: https://www.gov.uk/bank-holidays
Should make enabling tracking on tabs simpler.
None.
Trello card: https://trello.com/c/OSeC4N43/261-epic-technical-debt
> Add GA4 tracking option to tabs component

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
* Fix redaction bug in GA4 form tracker ([PR #3300](https://github.com/alphagov/govuk_publishing_components/pull/3300))
* Add GA4 tracking option to tabs component ([PR #3296](https://github.com/alphagov/govuk_publishing_components/pull/3296))
* Fix component auditing ([PR #3292](https://github.com/alphagov/govuk_publishing_components/pull/3292))
* Fix smart answer PII issue ([PR #3291](https://github.com/alphagov/govuk_publishing_components/pull/3291))
* Update accordion index parameter ([PR #3290](https://github.com/alphagov/govuk_publishing_components/pull/3290))
* Add GA4 tracking to step by step links ([PR #3289](https://github.com/alphagov/govuk_publishing_components/pull/3289))
* **BREAKING** Expand use of component wrapper helper ([PR …
> Version 35.0.0

- CHANGELOG.md
- lib/govuk_publishing_components.rb
- lib/govuk_publishing_components/railtie.rb
This fixes a problem I encountered when running Govspeak with the current version of the component gem:
```
Error:
GovspeakAttachmentTest#test_renders_an_attachment_component_for_a_found_attachment:
ActionView::Template::Error: undefined method `add_gem_component_stylesheet' for #<ActionView::Base:0x00000000002da0>
```
This error occurs because the views in this gem require the methods from GovukPublishingComponents::AppHelpers::AssetHelper and if they are only added if Rails exists then this gem will error. Govspeak is a user of this gem that does not have rails.
As this app is tested in a Rails environment it's very hard to write a test that exposes this issue and can cover a regression therefore I've not added one.
None
> Always require AssetHelpers so gem can operate without Rails

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/helpers/_markdown-typography.scss
Update the text color for code examples in the component guide. The new color used is taken from the [Design System documentation](https://design-system.service.gov.uk/components/back-link/) and increases the color contrast from 4.34 to 4.51.
Improve legibility of the text and ensure that we meet [WCAG AA accessibility requirements](https://www.w3.org/WAI/WCAG21/Understanding/contrast-minimum.html).
https://gds-way.cloudapps.digital/manuals/accessibility.html#poor-colour-contrast
---
Fixes: https://github.com/alphagov/govuk_publishing_components/issues/3018
> Ensure color contrast in code examples meets accessibility requirements

- CHANGELOG.md
- app/views/govuk_publishing_components/components/_error_summary.html.erb
- app/views/govuk_publishing_components/components/docs/error_summary.yml
Update error summary to use [component wrapper helper](https://github.com/alphagov/govuk_publishing_components/blob/main/docs/component-wrapper-helper.md)
Resolves an issue whereby the data attribute for `module: "govuk-error-summary"` is overwritten when the same option is passed to the component. For example:
```
<%= render "govuk_publishing_components/components/error_summary", {
data_attributes: {
module: "auto-track-event"
},
} %>
```
None
See https://github.com/alphagov/frontend/pull/3562
> Update error summary to use component wrapper helper

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/_layout-super-navigation-header.scss
- config/locales/en.yml
- spec/components/layout_super_navigation_header_spec.rb
Remove 'Cost of living support' from navbar and footer added in https://github.com/alphagov/govuk_publishing_components/pull/2939
The custom navigation page was replaced by a guide.
https://trello.com/c/j34Whcl4/1709-shut-down-cost-of-living-navigation-page-l
> Remove 'Cost of living support' from navbar and footer

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
* Remove links and sections count tracking for retired Cost of living hub page ([PR #3315](https://github.com/alphagov/govuk_publishing_components/pull/3315))
* Update the list of popular links in the super navigation header ([PR #3316](https://github.com/alphagov/govuk_publishing_components/pull/3316))
> Release 35.1.1

- CHANGELOG.md
- app/models/govuk_publishing_components/audit_applications.rb
- app/models/govuk_publishing_components/audit_comparer.rb
- app/views/govuk_publishing_components/audit/_applications.html.erb
- spec/component_guide/audit_applications_spec.rb
- spec/component_guide/audit_comparer_spec.rb
Update the auditing so that it suppresses warnings relating to missing stylesheets for applications that use the new per page component asset loading model. This model is currently only implemented in `frontend`, but will be rolled out to other applications soon.
Also do some minor cleaning up of the UI, including adding a notice for the above where relevant.
To remove misleading auditing warnings.
Example of what `frontend` looks like in the auditing now:
> Make auditing aware of new asset loading model

- CHANGELOG.md
- app/views/govuk_publishing_components/components/_step_by_step_nav_related.html.erb
- spec/components/step_by_step_nav_related_spec.rb
This PR adds "Part of" to the `section` parameter for links that appear under the "Part of" header in the contextual sidebar. Previously, `section` was `undefined`.
GA4 migration bug fix requested by PA's.
[Trello card](https://trello.com/c/I0gafCaw/429-add-tracking-for-part-of-step-by-steps-related-content)
N/A
> Ga4 part of heading tracking fix

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/analytics-ga4/ga4-core.js
- app/assets/javascripts/govuk_publishing_components/analytics-ga4/ga4-link-tracker.js
- spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-core.spec.js
- spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-link-tracker.spec.js
[PR #3277](https://github.com/alphagov/govuk_publishing_components/pull/3277) changed the structure of GA4 `index` attributes on HTML elements. This PR updates our JS to use the new `index` approach.
This PR also includes a minor refactor of how `data.index` is set.
[Trello card](https://trello.com/c/evfeFHKx/496-ga4-informationclick-index-bug)
N/A
> Ga4 fix index

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/components/step-by-step-nav.js
- app/views/govuk_publishing_components/components/_layout_super_navigation_header.html.erb
- spec/components/layout_super_navigation_header_spec.rb
- spec/javascripts/components/step-by-step-nav-spec.js
Update parts of the GA4 code to reflect recent changes in the `index` parameter, specifically the new additional parameter, `index_section_count`, which is the number of sections in the thing being tracked.
Applied to:
- site header
- step by step
Part of the GA4 migration work.
None.
Trello card: https://trello.com/c/16ngDhBP/493-change-the-index-parameter-part-2-indexsectioncount
> Update GA4 index parameter

- CHANGELOG.md
- lib/govuk_publishing_components/presenters/component_wrapper_helper.rb
- spec/lib/govuk_publishing_components/components/component_wrapper_helper_spec.rb
Improve the component wrapper helper in the following ways.
- let it recognise if blank or nil values are passed for certain things. Previously it was possible to pass `nil` as an ID attribute, at which point the wrapper would error because `nil` is not a valid HTML ID, rather than simply ignoring it
- improve the error messages to include the thing that is causing the error, in order to make troubleshooting issues easier
`Frontend` had a bit of code where `nil` was being [passed to a component as an ID](https://github.com/alphagov/frontend/commit/44a16abd2888cb0dddbb4a2d01f5a75477bbb089), which was causing the build to fail. This change should prevent similar errors in the future.
None.
> Make the component wrapper more robust

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
* Update to Lux 307 ([PR #3329](https://github.com/alphagov/govuk_publishing_components/pull/3329))
* Drop support for Ruby 2.7 ([PR #3310](https://github.com/alphagov/govuk_publishing_components/pull/3310))
* Update GA4 index parameter ([PR #3297](https://github.com/alphagov/govuk_publishing_components/pull/3297))
* Make the component wrapper helper more robust ([PR #3324](https://github.com/alphagov/govuk_publishing_components/pull/3324))
* Make auditing aware of new asset loading model ([PR #3318](https://github.com/alphagov/govuk_publishing_components/pull/3318))
* Ga4 part of heading tracking fix ([PR #3321](https://github.com/alphagov/govuk_publishing_components/pull/3321))
* Ga4 fix index ([PR #3313](https://github.com/alphagov/govuk_publishing_components/pull/3313))
* Fix search …
> Version 35.2.0

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/analytics-ga4/ga4-core.js
- app/assets/javascripts/govuk_publishing_components/analytics-ga4/init-ga4.js
- docs/analytics-ga4/analytics.md
- spec/javascripts/govuk_publishing_components/analytics-ga4/init-ga4.spec.js
Sets the GA4 data attributes for attachment links via JavaScript, instead of setting them directly on the attachment links' HTML.
Initially we were going to set our GA4 data attributes directly on each attachment links' HTML - as shown in https://github.com/alphagov/whitehall/pull/7481. However, as the HTML lives in `whitehall`, deploying the new HTML to our servers requires us to republish 45k+ documents which takes a bit of time.
This could become an issue if we constantly need to make changes to the data attributes, as we'd need to republish 45k documents every time. It also feels a bit like technical debt to implement something that would require 45k republishes to update.
Therefore, in `whitehall` we are going to set an attribute called `data-ga4-attachment-links` on the HTML of each …
> Add data attributes to attachment links using JS

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/analytics-ga4/ga4-core.js
- app/assets/javascripts/govuk_publishing_components/analytics-ga4/ga4-link-tracker.js
- app/views/govuk_publishing_components/components/_accordion.html.erb
- spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-core.spec.js
- spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-link-tracker.spec.js
This PR adds GA4 tracking to accordion links. 
This PR also includes a change to the `setIndex` function and it will now combine `data-ga4-index` (our method of adding `index_link` to links that are generated by content publishers ([further details here)](https://github.com/alphagov/govuk_publishing_components/pull/3262)) with the `index` property if it exists on a parent element.
The change to `setIndex` has been made because in some scenarios, such as accordion links, we need to set `data-ga4-link` on a parent element due to the links being generated by a content publisher. Within `data-ga4-link`, an `index` property may already exist and contain values such as `index_section` and `index_section_count`. In order to prevent this data from being overwritten with …
> Ga4 accordion link tracking

- app/assets/javascripts/component_guide/application.js
- app/assets/javascripts/govuk_publishing_components/components/intervention.js
- app/assets/javascripts/govuk_publishing_components/lib/cookie-functions.js
- app/views/govuk_publishing_components/components/_intervention.html.erb
- app/views/govuk_publishing_components/components/docs/intervention.yml
- lib/govuk_publishing_components/presenters/intervention_helper.rb
- spec/components/intervention_spec.rb
- spec/javascripts/components/intervention-spec.js
- spec/lib/govuk_publishing_components/components/intervention_helper_spec.rb
The dismiss feature was never working on the intervention button. This PR adds that missing functionality.
See https://components-gem-pr-3101.herokuapp.com/component-guide/intervention/with_dismiss_link/preview
Fixes https://github.com/alphagov/govuk_publishing_components/issues/3097
[Trello](https://trello.com/c/MIwoWClW/1514-bug-fix-dismiss-button-on-intervention-banner-component-for-research-panel-recruitment-banner-m)
Fixes https://github.com/alphagov/govuk_publishing_components/issues/3097
https://user-images.githubusercontent.com/424772/211383759-d25f1045-3ea3-4966-9afb-07ec278a6366.mov
https://user-images.githubusercontent.com/424772/211383925-994944de-7097-4503-8d8c-0abc75fea583.mov
### Cookies
https://user-images.githubusercontent.com/424772/219225646-e03a8db1-c64c-4cbc-a0ef-56d12 …
> Fix intervention dismiss

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
* Add data attributes to attachment links using JS [(PR #3330)](https://github.com/alphagov/govuk_publishing_components/pull/3330)
* Ga4 accordion link tracking ([PR #3328](https://github.com/alphagov/govuk_publishing_components/pull/3328))
* Fix GA4 Step Nav link tracking bug ([PR #3334](https://github.com/alphagov/govuk_publishing_components/pull/3334))
> Version 35.3.0

- CHANGELOG.md
- app/views/govuk_publishing_components/components/_contextual_sidebar.html.erb
- app/views/govuk_publishing_components/components/_related_navigation.html.erb
- app/views/govuk_publishing_components/components/contextual_sidebar/_ukraine_cta.html.erb
- app/views/govuk_publishing_components/components/related_navigation/_section.html.erb
- lib/govuk_publishing_components/presenters/related_navigation_helper.rb
- spec/components/contextual_sidebar_spec.rb
- spec/components/related_navigation_spec.rb
Update the GA4 `index` parameter on the related navigation and contextual sidebar components. Specifically:
- break the `index` parameter into `index_section` and `index_link` sub parameters
- add a new `index_section_count` sub parameter
- add the `index_total` parameter
Part of the GA4 migration. We've changed how the index parameters should work, this is to reflect that.
None.
Trello card: https://trello.com/c/16ngDhBP/493-change-the-index-parameter-part-2-indexsectioncount
> Update GA4 index parameter on related navigation

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
* Add brand colour for DSIT Add brand colour for DSIT (https://github.com/alphagov/govuk_publishing_components/pull/3349)
* Update GA4 index parameter on related navigation (https://github.com/alphagov/govuk_publishing_components/pull/3346)
> Bump to 35.3.1

- app/controllers/govuk_publishing_components/audit_controller.rb
- service manual frontend has been retired and merged with (government-frontend? I think) so we no longer need to include it in the component auditing
None.
> Remove service manual frontend from auditing

- spec/dummy/config/initializers/content_security_policy.rb
These two rules are no longer needed as the rule changes were released in govuk_app_config v5, this app is using v7.
This also resolves an issue where img_src had the wrong rules because it modified policy.style_src rather than policy.img_src.
This should resolve the issue with: https://github.com/alphagov/govuk_publishing_components/pull/3332#pullrequestreview-1390248657
> Remove superfluous CSP declarations

- CHANGELOG.md
- app/views/govuk_publishing_components/components/_attachment.html.erb
- app/views/govuk_publishing_components/components/docs/attachment.yml
- lib/govuk_publishing_components/presenters/attachment_helper.rb
- spec/components/attachment_spec.rb
[Trello card](https://trello.com/c/QX2nA0SV/1176-add-support-for-custom-thumbnails-to-the-attachment-govukpublishingcomponent)
Update the Attachment component to accept new parameter for custom thumbnails.
We want to remove attachment rendering functionality out of Whitehall and instead use the functionality provided by the Govspeak gem (it uses govuk_publishing_components to render attachments so we need to update the Attachment component here to support PDF preview thumbnails).
The will be no visual change - thumbnails for PDF attachments should be rendered the same way as with previous implementation.
> Update the Attachment component to accept a thumbnail parameter

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
* Fix GA4 index_total parameter in various places ([PR #3358](https://github.com/alphagov/govuk_publishing_components/pull/3358))
> Version 35.3.2

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/components/cookie-banner.js
- app/assets/stylesheets/govuk_publishing_components/components/_cookie-banner.scss
- app/views/govuk_publishing_components/components/_cookie_banner.html.erb
- spec/components/cookie_banner_spec.rb
- spec/components/layout_for_public_spec.rb
- spec/javascripts/components/cookie-banner-spec.js
Align the Cookie Banner in the govuk_publishing_components to the Cookie Banner in the Design System. This involved:
- Replacing the partial with the same HTML as the Design System Cookie Banner
- Reworking how the JS hides/shows confirmation messages
- Removing unnecessary classes now the HTML is the same as the Design System Cookie Banner
- Updating the tests to make sure they still work, including adding new test for the focus after the user has made a choice
The Cookie Banner in govuk_publishing_components has different HTML to the Cookie Banner in the Design System. This is despite the fact that the they both resemble each other and have no differences in functionality. Ideally they should be using the same mark-up and classes as the Design System implementation is backed up by …
> Make Cookie Banner Implementation More Like Design System Implementation

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/helpers/_brand-colours.scss
[Trello card](https://trello.com/c/rtK4IWUx/1206-update-department-of-business-trade-branding-labels-in-publishing-components)
This change should be removed after relevant govuk-frontend release.
We are updating the labelling of Department of International Trade to Department for Business & Trade.
This is part of the Supporting Government changes work (departments updates).
> Add organisation brand colour for Department for Business & Trade

- CHANGELOG.md
- config/locales/cy.yml
Adds the Welsh translation for "Sharing will open the page in a new tab".
A department (DVLA) have noticed the text is in the wrong language on their Welsh organisation page and on their Welsh news stories.
Zendesk ticket: https://govuk.zendesk.com/agent/tickets/5318644
> Add Welsh translation for `all_opens_in_new_tab`

- CHANGELOG.md
- lib/govuk_publishing_components/presenters/breadcrumbs_helper.rb
- spec/components/breadcrumbs_spec.rb
This PR makes a very small change to the GA4 event `type` parameter when tracking breadcrumbs and changes it to `breadcrumb` rather than `breadcrumbs`.
Requested by PA's
[Trello card](https://trello.com/c/Fwv2tyhJ/514-rename-breadcrumb)
N/A
> Rename type breadcrumbs to breadcrumb

- CHANGELOG.md
- app/assets/stylesheets/component_guide/application.scss
- app/views/govuk_publishing_components/component_guide/example.html.erb
- app/views/govuk_publishing_components/component_guide/preview.html.erb
- app/views/govuk_publishing_components/component_guide/show.html.erb
- app/views/layouts/govuk_publishing_components/application.html.erb
- docs/install-and-use.md
- lib/govuk_publishing_components/app_helpers/asset_helper.rb
- spec/component_guide/component_example_spec.rb
- spec/dummy/config/environments/test.rb
- spec/features/asset_helper_spec.rb
- Call `render_component_stylesheets` to load stylesheets individually
- Update application.css used in the component guide to request only the minimum number of stylesheets required to render components correctly
- Remove `config.assets.digest = false` setting in `test.rb`, this allows the default value of `true` to be used - https://guides.rubyonrails.org/configuring.html#config-assets-digest
- Check if the frontend rendering application is using an application.css stylesheet before including it in the component guide view templates
- Ensure component previews work in rendering applications that are loading stylesheets individually
- Removing `config.assets.digest = false` fixes a failing test when using the individual loading of stylesheets feature in the gem and matches the default …
> Fix component guide previews for application components

- CHANGELOG.md
- app/views/govuk_publishing_components/components/_related_navigation.html.erb
- app/views/govuk_publishing_components/components/related_navigation/_section.html.erb
- spec/components/contextual_footer_spec.rb
This PR addresses a bug where the `index` parameters were not aggregating when a `contextual sidebar` and a `contextual footer` were rendered together on a page. Combining the index properties of 2 different components could be complex and so the simplest fix was to provide a differentiation between `contextual sidebar` and `contextual footer` components in the `type` parameter so that the `index` properties need not be aggregated.
Requested by PA's.
[Trello card](https://trello.com/c/dYtGpIpv/502-indexcount-is-different-for-related-content-and-contextual-footer)
N/A
> Conditionally set GA4 type in related navigation

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/analytics-ga4/init-ga4.js
- spec/javascripts/govuk_publishing_components/analytics-ga4/init-ga4.spec.js
https://trello.com/c/IsRPgFh9/559-change-html-attachment-type-to-attachment-on-attachment-navigation-clicks
Change type 'html attachment' to just 'attachment'
This change is being made because we're going to add data-ga4-attachment-link to every attachment link, so soon it won't just be html attachments being tracked with this type.
None.
> Change type 'html attachment' to just 'attachment'

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/analytics-ga4/ga4-core.js
- outputs details of analytics data pushed to the datalayer, to aid with debugging analytics events on any system particularly between pages
- to use, set the variable in the console: window.GOVUK.analyticsGa4.showDebug = true, then set the console to preserve log, then do a thing to trigger an event
I've been finding that the browser tools for debugging analytics events aren't 100% reliable, and this will help in some situation.
None.
Outputs into the console something like the below. I've tried to format it so it's readable - if you just output the object and go to another page, it doesn't persist the content of the object, so it's not accessible.
> Add GA4 debugging assistance

- CHANGELOG.md
- config/locales/en.yml
Update popular on GOV.UK links in top search bar to match those in the [homepage body](https://github.com/alphagov/frontend/blob/main/config/locales/en.yml#L382-L392) 
Popular links should be consistent across the site. It's a pain that they are set in different places.
> Update popular on govuk

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/helpers/_brand-colours.scss
[Trello card](https://trello.com/c/rtK4IWUx/1206-update-department-of-business-trade-branding-labels-in-publishing-components)
This is reverting changes done in https://github.com/alphagov/govuk_publishing_components/pull/3361
Changes can be removed as relevant govuk-frontend update is released.
> Remove custom brand colours for Department for Business And Trade

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
Releases version 35.3.5 of the gem.
This will include:
* Add GA4 debugging assistance ([PR #3388](https://github.com/alphagov/govuk_publishing_components/pull/3388))
* Remove custom brand colours for Department for Business And Trade ([PR #3391](https://github.com/alphagov/govuk_publishing_components/pull/3391))
* Conditionally set GA4 type in related navigation ([PR #3390](https://github.com/alphagov/govuk_publishing_components/pull/3390))
* Change type 'html attachment' to just 'attachment' ([PR #3382](https://github.com/alphagov/govuk_publishing_components/pull/3382))
* Update popular on gov.uk links in search bar ([PR #3385](https://github.com/alphagov/govuk_publishing_components/pull/3385))
> Bump version to 35.3.5

- app/assets/stylesheets/govuk_publishing_components/components/_search.scss
- app/assets/stylesheets/govuk_publishing_components/components/govspeak/_attachment.scss
- the govuk-if-ie8 mixin is deprecated and being removed from govuk-frontend in v5
- we don't support Internet Explorer 8 anymore, so removing this seems like the cleanest course of action
Was causing this warning to appear at compile time:
```
WARNING: The govuk-if-ie8 mixin is deprecated and will be removed in v5.0. To silence this warning, update $govuk-suppressed-warnings with key: "ie8"
on line 49:5 of node_modules/govuk-frontend/govuk/tools/../settings/_warnings.scss, in mixin `-warning`
from line 37:12 of node_modules/govuk-frontend/govuk/tools/_ie8.scss, in mixin `govuk-if-ie8`
from line 48:18 of app/assets/stylesheets/govuk_publishing_components/components/govspeak/_attachment.scss
from line 4:9 of app/assets/stylesheets/govuk_publishing_components/components/_govspeak.scss
from …
```
> Remove deprecated IE8 mixin

- docs/generate-a-new-component.md
- lib/generators/govuk_publishing_components/component_generator.rb
- update the application component generator code to explicitly replace hyphens with underscores in component names to follow our component naming conventions
- also [update the documentation](https://github.com/alphagov/govuk_publishing_components/blob/main/docs/generate-a-new-component.md) for this to clarify what should be done
We noticed recently that components in applications don't always follow our component conventions, which makes it harder to audit components. See issue: https://github.com/alphagov/govuk_publishing_components/issues/3369
None.
> Update component generator and guidance

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/analytics-ga4/ga4-link-tracker.js
- app/assets/javascripts/govuk_publishing_components/analytics-ga4/ga4-specialist-link-tracker.js
- spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-link-tracker.spec.js
- spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-specialist-link-tracker.spec.js
Add the PII Remover to the link trackers text/urls
https://trello.com/c/YZrXpxh0/570-fix-inconsistency-with-pii-remover
The implementation guide has this `//PII Cleansed` on all the URLs for link clicks, and a few of the `text` values. I'm not sure how often PII is going to show up on our `GA4LinkTracker` (since we usually determine where this is used) but I'm adding it just so it's in sync with the implementation guide.
`mailto:` links aren't PII cleansed since the PAs said it's useful for the email to come through on those links.
None.
> Ensure PIIRemover is running on GA4 link clicks

- CHANGELOG.md
- app/views/govuk_publishing_components/components/_hint.html.erb
- app/views/govuk_publishing_components/components/_label.html.erb
- app/views/govuk_publishing_components/components/docs/hint.yml
- spec/components/hint_spec.rb
- Replace hardcoded hint component by using the render method, instead of hardcoding it in the label component view template
- Add a new `is_radio_label_hint` input, setting this to `true` will add the `govuk-radios__hint` class to apply the correct styling when the label is used on a radio input
- margin-bottom will now only be applied if it is passed as an input, it will not default to margin-bottom-3, instead it will default to the margin used in the design system
- To ensure that any future changes to the hint component are reflected when used in the `label` component view template
- Allow the `hint` component stylesheet to be included when used within the `label` component view template, this happens automatically when using the render method
Trello: …
> Update hint component

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/_layout-super-navigation-header.scss
Remove blue background from search button in layout_super_navigation_header.
As a result of Design sessions with the GOV.UK design team, it was noticed that the background of the search button is black on mobile, and blue on desktop – which adds an unnecessary inconsistency. The proposed solution was Remove the blue background from desktop, and add a divider between the Menu and the Search elements.
[Relevant Trello Card](https://trello.com/c/q8HGC7LF/1765-remove-blue-background-from-search-icon-in-menu-header-s)
> Remove the blue background from search button

- CHANGELOG.md
- lib/govuk_publishing_components/presenters/related_navigation_helper.rb
- spec/components/related_navigation_spec.rb
- spec/lib/govuk_publishing_components/presenters/related_navigation_helper_spec.rb
Navigation helper: Within related navigation links, world Locations paths are now generated based on the base path if it is provided in the content item. Not a breaking change since if there is no base path provided, it will fall to previous behaviour of generating the slug based on page title. The special cases list has been removed since it is out of date.
Making it more flexible to deal with cases in related navigation links where there are pages where the name does not match the slug. e.g. "UK and NATO" / "uk-joint-delegation-to-nato".
The special cases list was out of date, with the new update now we should just default to using the base path if it is already being provided. This should fix some broken links
No breaking changes.
> [Fixes] World Locations Links From Base Path

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
* Add auditing of application components to component auditing ([PR #3374](https://github.com/alphagov/govuk_publishing_components/pull/3374))
* Fix GA4 index parameters on step nav show/hide all control ([PR #3397](https://github.com/alphagov/govuk_publishing_components/pull/3397))
* Update to LUX 308 ([PR #3394](https://github.com/alphagov/govuk_publishing_components/pull/3394))
* Ensure PIIRemover is running on GA4 link clicks ([PR #3402](https://github.com/alphagov/govuk_publishing_components/pull/3402))
* Update hint component ([PR #3405](https://github.com/alphagov/govuk_publishing_components/pull/3405))
* [Fixes] World Locations Links From Base Path ([PR #3396](https://github.com/alphagov/govuk_publishing_components/pull/3396))
* Remove the blue background from search button ([PR …
> Version 35.4.0

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/analytics-ga4/ga4-form-tracker.js
- spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-form-tracker.spec.js
Hi @andysellick, would you be able to approve this if all is OK? Thanks :+1:
Allow the a `text` value to be set in a `data-ga4-form` JSON, which prevents the form input being used as the `text` value.
For local transactions (https://www.gov.uk/rubbish-collection-day) the PAs want to track the `text` value for a `form_submit` event as the text of the submit button(Find). Therefore this change makes it so that if the data-ga4-form JSON already contains text, it will be used.
https://trello.com/c/2qmN8Wjg/546-form-events-formsubmit-formerror-formcomplete-and-informationclick-on-localtransaction-format
None.
> Allow ga4-form-tracker text to be overridden

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/analytics-ga4/ga4-link-tracker.js
- app/assets/javascripts/govuk_publishing_components/analytics-ga4/ga4-specialist-link-tracker.js
- spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-link-tracker.spec.js
- spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-specialist-link-tracker.spec.js
Set GA4 link text to `'image'` if there is no link text, and they are clicking on an image link
https://trello.com/c/Psw0vf3r/550-blank-text-being-sent-when-user-opens-a-file-or-html-attachment-by-clicking-on-the-image
Without this, the `text` value sent to the dataLayer is an empty string.
None
> Set GA4 link text to 'image' if there is only an image and no link text

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
* Allow ga4-form-tracker text to be overridden ([PR #3409](https://github.com/alphagov/govuk_publishing_components/pull/3409))
* Change GA4 share values ([PR #3407](https://github.com/alphagov/govuk_publishing_components/pull/3407))
* Add GA4 index_section_count to step by step links ([PR #3410](https://github.com/alphagov/govuk_publishing_components/pull/3410))
* Set GA4 link text to 'image' if there's only an image and no link text ([PR #3404](https://github.com/alphagov/govuk_publishing_components/pull/3404))
> Version 35.5.0

- CHANGELOG.md
- app/assets/stylesheets/component_guide/application.scss
- app/views/govuk_publishing_components/components/docs/contextual_guidance.yml
- app/views/govuk_publishing_components/components/docs/fieldset.yml
- app/views/govuk_publishing_components/components/docs/inverse_header.yml
- app/views/govuk_publishing_components/components/docs/modal_dialogue.yml
- app/views/govuk_publishing_components/components/docs/textarea.yml
- Fix and improve rendering for several components in the component guide
- Remove several hardcoded examples in the component guide
- Remove import of `lead-paragraph` stylesheet in application.scss
- Fix the `textarea` - [With aria attributes](https://components.publishing.service.gov.uk/component-guide/textarea/with_aria_attributes) component example. The `contextual-guidance` component now renders when focusing the textarea in the component guide example.
When calling the render method, we ensure that any required stylesheets are automatically requested. By using this approach in `inverse-header.yml`, we ensure the required stylesheets are requested. Using this approach, we no longer need to import the `lead-paragraph` stylesheet into application.scss for the component guide to render …
> Remove hardcoded examples in the component guide

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/helpers/_markdown-typography.scss
- app/views/govuk_publishing_components/components/docs/govspeak.yml
This removes setting list-style on ordered lists to instead allow the
use of the type attribute on an ordered list to specify the list-style.
I couldn't determine why this style was needed. Current browsers style
this as list-style decimal by default and I can't find any code this
undoes. It could be that previously this was to undo an earlier
override, but it would be very unconventional for current GOV.UK to
style an `ol` without a class so this seems unlikely.
The motivation for making this change is to support some niche behaviour
used by publishers that will become disabled. Currently some advanced
published have managed to published ordered lists that are alphabetical
or roman numeral prefixed by use of an `ol` element with a style
attribute. This will not be available with the role …
> Remove list-style for govspeak ordered lists

- app/assets/stylesheets/govuk_publishing_components/components/_select.scss
Remove a height adjustment for selects that was needed because of an old issue in GOV.UK Frontend which has since been fixed.
This was [introduced in August 2019][1] to mitigate an [issue in GOV.UK Frontend where the height of a select component was set in pixels, which meant it did not scale if users changed the text size in their browser][2].
That issue [was fixed in GOV.UK Frontend][3] and [released as part of v3.3.0][4] in October 2019. Since then the height of a select component has been set in rem (as long as compatibility mode is not enabled) which means this adjustment can be removed.
[1]: https://github.com/alphagov/govuk_publishing_components/pull/1018
[2]: https://github.com/alphagov/govuk-frontend/issues/1519
[3]: https://github.com/alphagov/govuk-frontend/pull/1574
[4]: …
> Remove unnecessary select height adjustment

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/analytics-ga4/ga4-page-views.js
When conducting a search on a finder application (e.g. https://www.gov.uk/search/all?), the `referrer` parameter on the `pageView` object does not redact PII. (Instructions to recreate the issue have been left on this [trello card](https://trello.com/c/hs46dfAY/591-pii-coming-through-in-referrer-property-on-pageview-object))
PII issue fix.
[Trello card](https://trello.com/c/hs46dfAY/591-pii-coming-through-in-referrer-property-on-pageview-object)
N/A
> Fix PII on referrer parameter

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/analytics-ga4/ga4-core.js
- app/views/govuk_publishing_components/components/_layout_super_navigation_header.html.erb
- spec/components/layout_super_navigation_header_spec.rb
- spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-auto-tracker.spec.js
- spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-core.spec.js
- spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-event-tracker.spec.js
- spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-link-tracker.spec.js
- Sets any unused index keys in the `index` object to `undefined` if they aren't being used in the `index: {}` object.
- Updates the GOVUK Logo index values
- The PAs noticed that sometimes index values were being persisted between dataLayer pushes. This was because we aren't setting the indexes to `undefined` if they don't exist. Therefore, an `index_link`, `index_section` or `index_section_count` from a previous event could be included with the current event.
- Updates the GOVUK Logo index in accordance with this card: https://trello.com/c/SRFZ68d4/566-fix-index-on-govuk-link-click-nav-event-in-header-menu-bar
None.
> Fix some issues with GA4 indexes

- CHANGELOG.md
- app/views/govuk_publishing_components/components/_step_by_step_nav_related.html.erb
- spec/components/step_by_step_nav_related_spec.rb
Fixes incorrect GA4 data for the `pretitle` (in this case 'Also part of') on the step by step nav related component on pages like: https://www.gov.uk/guidance/appoint-someone-to-deal-with-customs-on-your-behalf
- had been partly done, but component outputs two slightly different chunks of markup depending on the number of links passed to it, and only one chunk had been modified to include the right pretitle value in the GA4 data
- also updating test as pretitle had been omitted
None
Trello card: https://trello.com/c/DNTld882/531-amend-section-parameter-to-say-also-part-of-step-by-steps-related-content
> Fix GA4 tracking on step nav related

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/analytics-ga4/ga4-auto-tracker.js
- app/assets/javascripts/govuk_publishing_components/analytics-ga4/ga4-core.js
- app/assets/javascripts/govuk_publishing_components/analytics-ga4/ga4-event-tracker.js
- app/assets/javascripts/govuk_publishing_components/analytics-ga4/ga4-link-tracker.js
- docs/analytics-ga4/ga4-link-tracker.md
- spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-auto-tracker.spec.js
- spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-core.spec.js
- spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-event-tracker.spec.js
- spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-link-tracker.spec.js
This code was used to convert string values for the GA4 index parameter into sub attributes such as index_section, index_link. It was originally written to be future proof i.e. if passed an object that already contained these sub attributes, it just returned it. At this point nothing is using it, so it's redundant.
This code is no longer needed as all instances of code that uses an index parameter now has it as sub attributes already.
None.
Trello card: https://trello.com/c/TDGHW9cX/438-remove-index-processing-code
> Remove GA4 index parsing code

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
* Remove GA4 index parsing code ([PR #3434](https://github.com/alphagov/govuk_publishing_components/pull/3434))
* Fix GA4 tracking on step nav related ([PR #3431](https://github.com/alphagov/govuk_publishing_components/pull/3431))
* Remove hardcoded examples in the component guide ([PR #3418](https://github.com/alphagov/govuk_publishing_components/pull/3418))
* Remove list-style for govspeak ordered lists ([PR #3413](https://github.com/alphagov/govuk_publishing_components/pull/3413))
* Fix some issues with GA4 indexes ([PR #3426](https://github.com/alphagov/govuk_publishing_components/pull/3426))
* Fix PII on referrer parameter ([PR #3430](https://github.com/alphagov/govuk_publishing_components/pull/3430))
* Add GA4 tracking for content navigation ([PR …
> Version 35.6.0

- CHANGELOG.md
- app/assets/stylesheets/component_guide/application.scss
- app/views/govuk_publishing_components/components/_character_count.html.erb
- app/views/govuk_publishing_components/components/_feedback.html.erb
- app/views/govuk_publishing_components/components/_layout_super_navigation_header.html.erb
- app/views/govuk_publishing_components/components/_radio.html.erb
- app/views/govuk_publishing_components/components/_search.html.erb
- app/views/govuk_publishing_components/components/_select.html.erb
- app/views/layouts/govuk_publishing_components/application.html.erb
- lib/govuk_publishing_components/app_helpers/asset_helper.rb
- spec/features/asset_helper_spec.rb
- spec/lib/govuk_publishing_components/app_helpers/asset_helper_spec.rb
Fully implement loading of individual stylesheets in component guide.
- Remove import of stylesheets used in static from application.scss
- Update asset_helper.rb to ensure all component stylesheets are requested when viewing the component guide
- Ensure stylesheets are requested in the expected order, for example, the `button` stylesheet should always be requested before the `feedback` stylesheet in the [feedback component](https://github.com/alphagov/govuk_publishing_components/pull/3379/files#diff-467712c9048ef82f631d6018dc019d21a911b8c5dedbfe37a512b84cea69045eR2)
The components in the gem should render correctly when using the individual loading of stylesheets feature in any application.
Without this change, applications would need to import all the stylesheets we import in static - …
> Fully implement loading of individual stylesheets in component guide

- CHANGELOG.md
- app/views/govuk_publishing_components/components/_attachment.html.erb
- app/views/govuk_publishing_components/components/attachment/_thumbnail_document.html.erb
- app/views/govuk_publishing_components/components/attachment/_thumbnail_generic.html.erb
- app/views/govuk_publishing_components/components/attachment/_thumbnail_html.html.erb
- app/views/govuk_publishing_components/components/attachment/_thumbnail_spreadsheet.html.erb
- app/views/govuk_publishing_components/components/docs/attachment.yml
- lib/govuk_publishing_components/presenters/attachment_helper.rb
- spec/components/attachment_spec.rb
This commit adds support for HTML and external attachments to the Attachment component.
So far, the Attachment component has only been able to represent file attachments – i.e. attachments which have a 'content type' and a thumbnail that changes depending on the type of file it is.
This change acts as an enabler for us to switch off custom rendering of embedded attachments in the Whitehall Publisher app. It also ports across the HTML attachment thumbnail SVG which is currently [held in Whitehall][1].
I've also taken the opportunity to tighten up the tests to specify which thumbnail should appear for the various different types of attachments. This just supplements existing tests rather than explicitly testing them independently.
I've also fixed a minor styling bug which was present, where …
> Add support for HTML and external attachment types

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/_layout-for-public.scss
- app/views/govuk_publishing_components/components/_layout_for_public.html.erb
- app/views/govuk_publishing_components/components/docs/layout_for_public.yml
- lib/govuk_publishing_components/presenters/public_layout_helper.rb
- spec/components/layout_for_public_spec.rb
Add a new option `blue_bar_background` for public_layout. Add new option `blue_bar` for public_layout. Rework logic for blue bar appearance in the public_layout. Add tests for the blue bar background and the blue bar logic.
There are [instances of pages on collections](https://www.gov.uk/browse) that have a coloured background in the heading section. This meant that the blue bar (which is rendered in the public_layout) had to be rendered by collections otherwise it would result in a gap between the blue bar and coloured section. This solution seemed fine until we had a recent deployment of the global bar. As the global bar includes a blue bar, it meant that the Browse pages had two blue bars. They therefore needed to be removed while the global bar was present and then added back again …
> Add option for blue bar background to public_layout

- CHANGELOG.md
- app/views/govuk_publishing_components/components/_metadata.html.erb
- spec/components/metadata_spec.rb
- There are 'see all updates' links that are rendered via the metadata component. For example on [this page](https://www.gov.uk/hmrc-internal-manuals/self-assessment-claims-manual/sacm1005) 
- The link can be rendered in two ways.
- This PR formats the existing GA4 link tracking, as it looked like the formatting was wrong.
- This PR also adds GA4 tracking to the second way  the link can be rendered (i.e. adds `data-ga4-link` onto `<dd class="gem-c-metadata__definition">`.
- This PR also adds tests for the new tracking.
It's part of the content navigation GA4 work - https://trello.com/c/C9M2EJQu/553-content-navigation-chapter-headings-next-previous-view-a-printable-version-navigation-and-show-hide-updates-interaction
None.
> Add ga4-link attribute for other 'see all updates' link

- CHANGELOG.md
- app/views/govuk_publishing_components/components/_step_by_step_nav_related.html.erb
- spec/components/step_by_step_nav_related_spec.rb
This PR makes a change to the `type` parameter of elements that appear at the top and bottom of a `Part of` sidebar. Previously, the `type` was set to `related content` but this has now changed to `part of`.
Example (top):
Example (bottom):
GA4 bug fix.
[Trello card](https://trello.com/c/oXi9yaRO/598-part-of-also-part-of-showing-event-type-related-content-rather-than-part-of)
N/A
> Change GA4 type

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/_document-list.scss
- app/views/govuk_publishing_components/components/_document_list.html.erb
- app/views/govuk_publishing_components/components/docs/document_list.yml
- spec/components/document_list_spec.rb
**NOTE** this PR is linked to [changes in collections](https://github.com/alphagov/collections/pull/3301), which relies on this change.
- remove top and bottom margin options (undocumented and soon to be not used)
- add shared helper for margin bottom, and document
- change CSS to prevent last list item from setting the bottom margin of the component
The document list component had no bottom margin on the parent item by default. However, every list item in it had a bottom margin of 25px, which meant that the 25px of bottom margin extended out of the parent list, effectively setting the bottom margin of the component.
(for reference, this is a weird CSS thing where if a child has bottom margin it will escape from the parent unless the parent has padding (or any number of other things, …
> Refactor document list component

- CHANGELOG.md
- lib/govuk_publishing_components/app_helpers/asset_helper.rb
- spec/lib/govuk_publishing_components/app_helpers/asset_helper_spec.rb
Update the `viewing_component_guide?` method to use the safe navigation operator in asset_helper.rb
This will fix the issue below when using the AssetHelper in the smart answers rendering application.
```
undefined method `path' for nil:NilClass
```
The issue in smart answers is that the AssetHelper tries to check if we are viewing the component guide, it does this by checking if the request path contains "component-guide", however the "request" object is not available when trying to render govspeak outside of the component-guide.
This only appears to happen in smart answers, using govspeak in another rendering application does not cause any issues.
Using this approach, calling `!viewing_component_guide?` will return `false` if the request object is not available, even if the component …
> Use safe navigation operator in asset_helper.rb

- CHANGELOG.md
- app/views/govuk_publishing_components/components/_accordion.html.erb
On https://www.gov.uk/guidance/find-a-skills-bootcamp/updates if you expand an accordion or click on a child link, the dataLayer is passing through the link's `section`, or the accordion heading `text` value with HTML inside of it. If you click the whitespace next to a child link a JS error will appear as well. This PR fixes that.
It also corrects a `ga4-track-links-only` typo which resulted in JS errors, since the link tracker was trying to grab a `href` on non-link elements.
- Fixes a JS error (it didn't seem to affect other tracking on the page, it just output an error in the console.)
- https://trello.com/c/ABnBc5Wy/590-html-markup-appearing-in-section-parameter
None.
> Fix GA4 accordion tracking bugs

- CHANGELOG.md
- app/views/govuk_publishing_components/components/_single_page_notification_button.html.erb
- app/views/govuk_publishing_components/components/docs/single_page_notification_button.yml
- spec/components/single_page_notification_button_spec.rb
This PR adds GA4 tracking to the `single_page_notification_button` component (see example screenshot below).
The `single_page_notification_button` component can appear twice on a page - once at the top and once in the contextual footer ([example](https://www.gov.uk/guidance/travel-to-england-from-another-country-during-coronavirus-covid-19)). Whilst the component consists of a form and a submit button, it has been treated as a link in GA4 tracking terms as certain parameters such as `link_path_parts` and `link_domain` rely on functions that are only present in the `linkTracker` module (and therefore is unsuitable for the `eventTracker`).
[Trello card](https://trello.com/c/iP21pmuk/565-subscribe-get-emails-about-this-page-stop-getting-emails-about-this-page-button …
> Add ga4 tracking to single page notifications button

- CHANGELOG.md
- app/views/govuk_publishing_components/components/docs/notice.yml
Update HTML in Notice example to remove line break elements and replace with unordered list (to represent the two links).
WCAG 2.2 2.5.8 fail (Target Size (Minimum) (Level AA)). See https://w3c.github.io/wcag/understanding/target-size-minimum.html.
See https://github.com/alphagov/govuk_publishing_components/issues/3439
> Update notice component example

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/analytics-ga4/ga4-link-tracker.js
- spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-link-tracker.spec.js
Would you be able to approve this if all is OK? Thanks :+1:
- When the user clicks a link that is an image, we want our GA4 `text` value to be `'image'`.
- To do this, we were running a `querySelector` on the link, to see if it contained an `<img>` or `<svg>`.
- This only works if the `event.target` comes back as the link, as that allows us to do the `querySelector` which checks for the nested image elements.
- The issue we had was that sometimes the `event.target` comes back as the image itself, not the parent link. Therefore running `.querySelector` would not do anything as you were already on the furthest nested element.
- Therefore, we need to also do a `.closest()` so that if the event target is the image itself, we still can set the link text to `'image'`.
- The PAs want to track …
> Ensure GA4 link text is 'image' when the event target is an image

- CHANGELOG.md
- app/views/govuk_publishing_components/components/_single_page_notification_button.html.erb
- lib/govuk_publishing_components/presenters/single_page_notification_button_helper.rb
- spec/components/single_page_notification_button_spec.rb
Prior to this PR, if `skip_account` is present, the form action for the single page notification button is the non-govuk-acount signup endpoint, and the params necessary for that route are added to the request.
If `skip_account` is `nil`, the default form action is set that enforces the govuk_account 
New changes:
Instead of [checking if `skip_account` is present](https://github.com/alphagov/govuk_publishing_components/blob/7aecb57136a75439e5d8262cf7b5950ef2e1d3bd/lib/govuk_publishing_components/presenters/single_page_notification_button_helper.rb#L64), [check if `skip_account == "true"`](https://github.com/alphagov/govuk_publishing_components/blob/b36cc86680060aabc503a2be97239f56773a104d/lib/govuk_publishing_components/presenters/single_page_notification_button_helper.rb#L83-L85)
When …
> Improve single page notification button helper

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
* Update single page notification button ([PR #3471](https://github.com/alphagov/govuk_publishing_components/pull/3471))
* Fix GA4 accordion tracking bugs ([PR #3461](https://github.com/alphagov/govuk_publishing_components/pull/3461))
* Add ga4 tracking to single page notifications button ([PR #3443](https://github.com/alphagov/govuk_publishing_components/pull/3443))
* Update notice component example ([PR #3465](https://github.com/alphagov/govuk_publishing_components/pull/3465))
* Ensure GA4 link text is 'image' when the event target is an image ([PR #3462](https://github.com/alphagov/govuk_publishing_components/pull/3462))
> Version 35.9.0

- CHANGELOG.md
- app/views/govuk_publishing_components/components/_attachment.html.erb
- app/views/govuk_publishing_components/components/docs/attachment.yml
- spec/components/attachment_spec.rb
The Attachment component defaults to having no margin-bottom.
However sometimes we need it to have a margin-bottom value, for example when rendering a list of attachments on a document. Otherwise the components look too 'squashed up'.
This has previously been worked around by [wrapping the component in a container element][1] with margin bottom. But this feels a bit hacky and becomes trickier when we don't have so much control over the way the markup around the component (for example, when it's been embedded within a Govspeak document).
[1]: https://github.com/alphagov/government-frontend/blob/0bec9a842902db2a7353d28400fa7bf5d7008c8b/app/views/content_items/_attachments.html.erb#L18-L23
To make the attachment usable within Whitehall and Govspeak, without needing extra wrapper `<div>`s to …
> Add margin_bottom param to Attachment component

- .github/workflows/ci.yml
- .github/workflows/visual-regression-tests.yml
This makes a number of consistency updates to the GitHub actions for this gem. Most notably it changes how workflows run as per: https://docs.publishing.service.gov.uk/manual/test-and-build-a-project-with-github-actions.html#when-the-ci-workflow-should-run to only run on pull request and a push to main. Should you wish to run it before opening a PR you can run the workflow directly from the actions UI.
Aside from this there a few other rather bengin consistency tweaks - see commits for details
To make this project more consistent with GOV.UK approach and save on using surplus GitHub Actions
None
> Improved consistency across GitHub Actions

- CHANGELOG.md
- app/views/govuk_publishing_components/components/_contents_list.html.erb
- app/views/govuk_publishing_components/components/_metadata.html.erb
- spec/components/contents_list_spec.rb
- spec/components/metadata_spec.rb
- Instead of using `ga4-track-links-only` for the contents link tracking, I'm setting the GA4 attributes on each link instead. This is because using `ga4-track-links-only` didn't work properly for our requirement of trying to merge the indexes but also merging `index_total`. So it's easier to add the attributes to each link instead.
- Adds `action` to the `See all updates` link tracking, which was missed.
- Changes requested in https://github.com/alphagov/government-frontend/pull/2801
None.
> GA4 content navigation fixes

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/_attachment.scss
Fixes a styling issue where long strings of text for external links do not wrap onto a new line.
The approach used to fix the issue is the same as that used in the Design System - https://github.com/alphagov/govuk-frontend/blob/49a3eb389eec89e004873ddfeb8c1f9aa1d572e4/packages/govuk-frontend/src/govuk/components/summary-list/_index.scss#L64-L68
The long string of text was not contained and overlapped with other elements on the page.
Tested in the browsers below using BrowserStack:
- Chrome
- FireFox
- Safari
- Safari iOS
- IE11
The issue still exists in IE11, but it is worth noting that this issue existed before the recent change to use the attachment component from the gem.
I will create a separate issue for IE11, so this can be looked into separately.
> Fix attachment metadata styling issue

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
* GA4 content navigation fixes ([PR #3495](https://github.com/alphagov/govuk_publishing_components/pull/3495))
* Fix feedback component spacing ([PR #3470](https://github.com/alphagov/govuk_publishing_components/pull/3470))
* Fix attachment metadata styling issue ([PR #3501](https://github.com/alphagov/govuk_publishing_components/pull/3501))
* Improve the govspeak table layout when text direction is right-to-left ([PR #3466](https://github.com/alphagov/govuk_publishing_components/pull/3466))
**Note**: Updated the changelog as the govspeak table layout change will be included in this release
> Release 35.11.0

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/analytics-ga4/ga4-form-tracker.js
- spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-form-tracker.spec.js
Hi @JamesCGDS or @andysellick would you be able to approve this? Thanks :+1:
I had made a change in finder frontend (ga4-finder-tracker) to ensure that search terms come through in lowercase. However the search terms also need to be in lowercase when they come from one of the search forms on GOVUK such as the header menu bar, or the search box on the homepage. Therefore, this ensures the form text is lowercase if the form contains `action: 'search'`.
https://trello.com/c/F7gCCetP/617-search-terms-to-be-lower-cased
None.
> Ensure search forms have their text sent to GA4 in lowercase

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/analytics-ga4/ga4-core.js
- app/assets/javascripts/govuk_publishing_components/analytics-ga4/ga4-link-tracker.js
- spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-link-tracker.spec.js
This PR adds functionality for preventing redaction by detecting a `data-ga4-do-not-redact` attribute on elements that contain information that we don't want redacted. For example, all email addresses are currently redacted however, in some cases, we don't want to redact this information e.g. when the email address is publicly available contact information and surfaced within a set of results [(example)](https://www.gov.uk/disabled-students-allowances-assessment-centre#results).
Requested by PA's.
[Trello card](https://trello.com/c/nDZmuHH1/622-public-email-address-redacted-on-place-forms)
N/A
> Add functionality for preventing the redaction of publicly available information

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/analytics-ga4/ga4-form-tracker.js
- spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-form-tracker.spec.js
Ensures extra spaces are removed from search terms on search forms.
I removed extra spaces on search terms in Finder Frontend, but this needs to be done for the header menu bar search forms, and  the homepage search forms etc.
[Trello card](https://trello.com/c/EE2V1XmQ/618-remove-invisible-spaces-from-search-terms)
None.
> Ensure extra spaces are removed from search forms

- CHANGELOG.md
- app/views/govuk_publishing_components/components/_tabs.html.erb
- app/views/govuk_publishing_components/components/docs/tabs.yml
- spec/components/tabs_spec.rb
Adds an option to the tabs component to make the tabs act as links, instead of switching between hidden elements on the same page.
Note that for the purposes of tracking there has to be a bit of logic involved to switch from the GA4 event tracker to the link tracker. We're not actually tracking tabs as links anywhere on GOV.UK so this tracking is a bit unnecessary but it feels like more of a complete change if this is included now.
We have a tabs component in `collections-publisher` that looks exactly the same as this tabs component, but acts as links. If we add this option to the gem component we can reuse it in that application and remove a redundant component.
Related to issue https://github.com/alphagov/govuk_publishing_components/issues/3487
> Add link option to tabs component

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/analytics-ga4.js
- app/assets/javascripts/govuk_publishing_components/analytics-ga4/ga4-schemas.js
- app/assets/javascripts/govuk_publishing_components/analytics-ga4/ga4-scroll-tracker.js
- docs/analytics-ga4/ga4-scroll-tracker.md
- spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-scroll-tracker.spec.js
Adds a scroll tracker for GA4.
This code is based on the existing UA scroll tracker, which was rewritten relatively recently to be more efficient, with a few alterations, specifically:
- data is now collected and pushed to the dataLayer
- 'markers' can be used to track, in addition to the existing percentage and heading tracking options
See the included documentation for full details.
None.
Trello card: https://trello.com/c/BEPuXcrG/607-scroll-tracking-heading-type-home-page
> Add GA4 scroll tracker

- CHANGELOG.md
- app/controllers/govuk_publishing_components/audit_controller.rb
- app/models/govuk_publishing_components/audit_comparer.rb
Remove licence finder from list of audited applications in controller and comparer.
Licence finder application is now retired, searches are handled by Finder Frontend.
https://trello.com/c/1VXQW5I1/2127-epic-retire-original-licence-finder-application
> Remove licence-finder from list of audited applications.

- CHANGELOG.md
- app/models/govuk_publishing_components/component_wrapper_helper_options.rb
- app/views/govuk_publishing_components/components/_heading.html.erb
- app/views/govuk_publishing_components/components/docs/heading.yml
- app/views/govuk_publishing_components/components/docs/single_page_notification_button.yml
- app/views/govuk_publishing_components/components/docs/tabs.yml
- docs/component-wrapper-helper.md
- lib/govuk_publishing_components/presenters/component_wrapper_helper.rb
- spec/lib/govuk_publishing_components/components/component_wrapper_helper_spec.rb
Extend the component wrapper helper to support adding a `lang` attribute to components, e.g. `<div lang="cy">`.
Update the heading component to use the component wrapper helper.
Update other component documentation.
We want to pass data attributes to the heading component in another application (to do scroll tracking on the homepage), and switching it to using the component wrapper helper seemed like the simplest option. Except then it turned out that the heading component required a `lang` option, which wasn't supported, so this was added.
None, apart from small changes in the component guide to reflect this change.
Trello card: https://trello.com/c/BEPuXcrG/607-scroll-tracking-heading-type-home-page
> Extend component wrapper helper and use on heading component

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/_document-list.scss
- app/views/govuk_publishing_components/components/_document_list.html.erb
- spec/components/document_list_spec.rb
Fix inconsistent focus state on [document list component](https://components.publishing.service.gov.uk/component-guide/document_list/with_context/preview).
See https://components-gem-pr-3468.herokuapp.com/component-guide/document_list/with_context/preview
See https://github.com/alphagov/govuk_publishing_components/issues/1193
<table role="table">
<thead>
<tr>
<th>Before (focused)</th>
<th>After (focused)</th>
</tr>
</thead>
<tbody>
<tr>
<td valign="top"><a target="_blank" rel="noopener noreferrer" href="https://github.com/alphagov/govuk_publishing_components/assets/87758239/fcb91dc9-4bc0-4c19-8c1d-8e79519b59ea"><img src="https://github.com/alphagov/govuk_publishing_components/assets/87758239/fcb91dc9-4bc0-4c19-8c1d-8e79519b59ea" width="360" style="max-width: 100%;"></a></td>
<td …
> Fix inconsistent focus state on document list component

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/_search.scss
Add a transparent outline to the search button in all modes, and to form inputs in the blue background mode. This way Windows high contrast mode renders an outline for the elements, which helps to distinguish them from their background and makes them easier to identify. 
This does not result in any visual changes in the standard contrast mode.
We remove the default border from the search button in all modes, and the default border from from form input elements in the blue background mode, in order to comply with the GOV.UK design. 
However, this meant that these elements didn't have a visible outline in Windows high contrast mode which could make them difficult to distinguish from their background, or to identify. (This wasn't an issue in Firefox when users changes the default browser …
> Render an outline for search button and input in Windows high contrast mode

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/analytics-ga4/ga4-scroll-tracker.js
- spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-scroll-tracker.spec.js
Fix a problem with the scroll tracker, specifically:
- in some cases the percentage scroll mode doesn't work for the 100% scroll position
- I think this is being caused by the potential for a horizontal scrollbar, so the cleanest solution is to subtract 20px from the overall calculated page height prior to percentage position calculation, making all of the percentage positions very slightly further up the page, but allowing the 100% position to be reachable in all tested scenarios
Thanks to @AshGDS for his invaluable help in figuring out this problem 👏 
Sometimes the 100% scroll track event doesn't fire, because even if you're at the bottom of the page the calculated 100% position is slightly further away, and unreachable.
None.
> Fix 100% scroll problem

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/analytics-ga4/ga4-page-views.js
- spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-page-views.spec.js
- Adds `ab_test` value to the GA4 Pageview
- Not sure if I've put it in the right 'place' in the object (as I can see attributes are being grouped via line breaks)
- Not sure if the test is overkill
- Requested by PAs
- https://trello.com/c/3LnlkGK0/630-page-view-enhancement-new-abtest-attribute
None.
> Add GA4 pageview meta tag: ab_test

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
* Add GA4 pageview meta tag: ab_test ([PR #3523](https://github.com/alphagov/govuk_publishing_components/pull/3523))
* Wrap the text of `start` buttons in a `span` ([PR #3478](https://github.com/alphagov/govuk_publishing_components/pull/3478))
> Version 35.13.1

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/analytics-ga4/ga4-page-views.js
- spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-page-views.spec.js
- Adds `navigation_page_type` attribute to the GA4 Pageview object
- Requested by the PAs
- Trello card: https://trello.com/c/mqBb4kQ4/631-page-view-enhancement-new-navigationpagetype-attribute
None.
> Add navigation-page-type GA4 pageview attribute

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/analytics-ga4/ga4-scroll-tracker.js
- docs/analytics-ga4/ga4-scroll-tracker.md
- spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-scroll-tracker.spec.js
Section attribute when tracking headings and markers should contain the same value as text, was missed during original implementation.
None.
Trello card: https://trello.com/c/BEPuXcrG/607-scroll-tracking-heading-type-home-page
> Add section attribute to scroll tracking

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/_select.scss
Adjust the select component 'full width' styling to fix a problem.
- where the full width option is used in a confined space, the select element can extend outside of the width of the containing element
- noticed on [topic filters on search pages](https://www.gov.uk/search/all?keywords=minister&level_one_taxon=d6c2de5d-ef90-45d1-82d4-5f2438369eea&order=relevance)
Tested in Edge, IE11, Chrome, Firefox, Opera, Safari.
Before | After
------ | -------
Fixes https://github.com/alphagov/govuk_publishing_components/issues/3525
> Fix select width overlap bug

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/analytics-ga4/ga4-core.js
- spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-core.spec.js
- allow an index_total to be set and collected, to override a calculated index_total, normally determined by the number of links found in the element
- used in a rare situation on taxon pages where we want to use the setIndexes functionality but also need to adjust the index_total to account for an extra link
See related PR.
None.
Trello card: https://trello.com/c/DqMNdDNz/652-change-type-of-explore-sub-topics-links-to-subtopic-list
> Adjust core functions setIndexes

- CHANGELOG.md
- docs/set-up-individual-component-css-loading.md
Update the documentation for loading component stylesheets individually:
- Update heading levels
- Change example PR from `frontend` to `government-frontend`, this change was done later and is a better example
- Remove reference to stylesheets loading in alphabetical order, this is no longer the case
- Update section on "Increased header size" and add links to relevant docs
Ensure documentation is accurate
> Update the documentation for loading component stylesheets individually

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/analytics-ga4/ga4-page-views.js
- spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-page-views.spec.js
Adds some new attributes to the GA4 pageview.
None.
Trello cards:
- https://trello.com/c/cdDrc3Yl/629-page-view-enhancement-new-navigationlisttype-attribute
- https://trello.com/c/kv150IuU/632-page-view-enhancement-new-stepnavs-attribute
> GA4 pageview changes

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/analytics-ga4/ga4-scroll-tracker.js
- spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-scroll-tracker.spec.js
- code adds an event listener for 'dynamic-page-update' event, which resets all of the nodes to alreadySeen = false
- this event can then be triggered by code elsewhere, in order to 'reset' scroll tracking on any given page
- initial use is for search pages, where users change their search filters, page dynamically updates and so scroll tracking only works the first time, now if the search code triggers that event, the scroll tracker will reset
Scroll tracking works correctly on search pages until users change their filters. At that point the user is effectively on a new page (content and URL change) and we want the scroll tracking to 'reset' (i.e. if the user has scrolled to the bottom of the page previously, we want to also record that happened after the search filters are changed). …
> Add a reset option into the GA4 scrolltracker

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/analytics-ga4/ga4-form-tracker.js
- spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-form-tracker.spec.js
- when handling text inputs, form tracker didn't know about some input type values that it is required to recognise, specifically 'email' and 'number'
- other input types exist but are currently not in use on GOV.UK, but can now be more easily added if required
None.
Trello card: https://trello.com/c/TXQOqtZ0/628-email-subscriptions-manage-subscriptions-sign-in-change-unsubscribe-forms
> Expand GA4 form tracker

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/analytics-ga4.js
- app/assets/javascripts/govuk_publishing_components/analytics-ga4/ga4-schemas.js
- app/assets/javascripts/govuk_publishing_components/analytics-ga4/ga4-video-tracker.js
- app/assets/javascripts/govuk_publishing_components/lib/govspeak/youtube-link-enhancement.js
- docs/analytics-ga4/ga4-video-tracker.md
- spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-schemas.spec.js
- spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-scroll-tracker.spec.js
- spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-video-tracker.spec.js
Adds tracking for Youtube videos for GA4. See included documentation for details.
None.
Trello card: https://trello.com/c/zQiODIUm/607-investigate-how-ga4-tracking-will-work-for-video
> Add GA4 video tracking

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
* Add a reset option into the GA4 scrolltracker ([PR #3544](https://github.com/alphagov/govuk_publishing_components/pull/3544))
* Expand GA4 form tracker ([PR #3546](https://github.com/alphagov/govuk_publishing_components/pull/3546))
* Adjust core functions setIndexes ([PR #3541](https://github.com/alphagov/govuk_publishing_components/pull/3541))
* GA4 pageview changes ([PR #3542](https://github.com/alphagov/govuk_publishing_components/pull/3542))
* Fix select width overlap bug ([PR #3538](https://github.com/alphagov/govuk_publishing_components/pull/3538))
* Add section attribute to scroll tracking ([PR #3537](https://github.com/alphagov/govuk_publishing_components/pull/3537))
* Add navigation-page-type GA4 pageview attribute ([PR …
> Version 35.13.2

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/analytics-ga4/ga4-page-views.js
- app/views/govuk_publishing_components/components/_emergency_banner.html.erb
- app/views/govuk_publishing_components/components/docs/emergency_banner.yml
- spec/components/emergency_banner_spec.rb
- spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-page-views.spec.js
- Adds GA4 tracking to the emergency banner component.
- More specifically, it adds `emergency_banner: true` to the `pageview` if the emergency banner is rendered. It also adds the `ga4-link-tracker`. Both of these rely on `ga4_tracking: true` so we can toggle the tracking on and off on the banner.
- I've checked it in a local version of `static`, the `pageview` attribute is added correctly.
- https://trello.com/c/yH88Twnv/661-banners-emergency-banner-element-visibility-and-navigation
- It adds a "With GA4 tracking" to the component examples
> Add GA4 tracking to the emergency banner

- CHANGELOG.md
- app/views/govuk_publishing_components/components/_attachment.html.erb
- spec/components/attachment_spec.rb
I mistakenly tracked file attachments with `event_name: navigation` when they need `event_name: file_download`. This PR fixes that.
https://trello.com/c/MHFXw6H2/552-change-filedownloads-on-attachment-pages-to-have-attachment-instead-of-generic-download-type#comment-64db9a3327d6c9305d38c4e7
None.
> Ensure file attachments have the GA4 event_name 'file_download'

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/analytics-ga4/ga4-page-views.js
- app/views/govuk_publishing_components/components/_phase_banner.html.erb
- app/views/govuk_publishing_components/components/docs/phase_banner.yml
- spec/components/phase_banner_spec.rb
- spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-page-views.spec.js
- Adds GA4 tracking to the phase banner component.
- More specifically, it adds `phase_banner: alpha/beta/undefined` to the `pageview` if the phase banner is rendered. It grabs `alpha` `beta`  based on the value of the `data-ga4-phase-banner` attribute, for example: `data-ga4-phase-banner=beta`. This PR also adds the `ga4-link-tracker` to the banner. 
- Both of these rely on `ga4_tracking: true` so we can toggle the tracking on and off on the banner.
- I've checked it in a local version of `static`. The `pageview` attribute is added correctly fortunately (there was speculation in the implementation guide that this wouldn't be possible.) I believe this is working because our pageview fires after DOMContentLoaded so it doesn't matter where a banner is in the DOM.
- …
> Add GA4 tracking to the phase banner

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/analytics-ga4/ga4-core.js
- Change `replaceAll()` to `replace()` in GA4 link tracker's `removeCrossDomainParams` function.
- `replaceAll()` is not supported in IE11. Instead you can use `replace()` as long as you use a global regex pattern, which we already are using in this case. See here: https://stackoverflow.com/a/13340151
None.
> Use replace() instead of replaceAll() in removeCrossDomainParams() 

- app/views/layouts/govuk_publishing_components/application.html.erb
Adds the version number of the gem into the header of the component guide.
This is occasionally useful. For example when checking the [online version of the component guide](https://components.publishing.service.gov.uk/component-guide) to see if changes have been updated, or checking the version of the gem in a locally running application to see if it really is running what you think it's running.
Before | After
------ | -------
> Add version to component guide

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
* Add GA4 tracking to the emergency banner ([PR #3549](https://github.com/alphagov/govuk_publishing_components/pull/3549))
* Ensure file attachments have the GA4 event_name 'file_download' ([PR #3553](https://github.com/alphagov/govuk_publishing_components/pull/3553))
* Add GA4 tracking to the phase banner ([PR #3552](https://github.com/alphagov/govuk_publishing_components/pull/3552))
* Use replace() instead of replaceAll() in removeCrossDomainParams() ([PR #3555](https://github.com/alphagov/govuk_publishing_components/pull/3555))
> Version 35.14.0

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/analytics-ga4/ga4-page-views.js
- app/views/govuk_publishing_components/components/_devolved_nations.html.erb
- app/views/govuk_publishing_components/components/docs/devolved_nations.yml
- lib/govuk_publishing_components/presenters/devolved_nations_helper.rb
- spec/components/devolved_nations_spec.rb
- spec/components/emergency_banner_spec.rb
- spec/components/phase_banner_spec.rb
- spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-page-views.spec.js
- Adds GA4 tracking to the devolved nations banner component.
- More specifically, it adds `devolved_nations_banner: 'England'/'England, Scotland, Wales'/'Scotland, Wales'/etc/undefined` to the `pageview` if the banner is rendered. It grabs this value based on the value of the `data-ga4-devolved-nations-banner` attribute, for example: `data-ga4-devolved-nations-banner=England, Scotland, Wales`. This PR also adds the `ga4-link-tracker` to the banner. 
- Both of these rely on `ga4_tracking: true` so we can toggle the tracking on and off on the banner.
- I had to write a Ruby function to grab the nations for `data-ga4-devolved-nations-banner`, and for the link tracker's `section`. This is because I needed to ensure the English text for the countries was always used. I also used `gsub` to …
> Add GA4 tracking to devolved nations banners

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/analytics-ga4/ga4-page-views.js
- spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-page-views.spec.js
- replaces Google Analytics tracking parameters in URLs with `_ga=[id]` or `_gl=[id]` when creating GA pageviews
- has to happen prior to PII being stripped as they occasionally get mistaken for dates, which would break this redaction
- vaguely related: refactor the get referrer code to make it easier to read and insert the GA param redaction
To clean up the location data in GA4.
None.
Trello card: https://trello.com/c/2hJRUoDM/660-redact-strip-ga-and-gl-trackers-from-page-location-and-page-referrer-values
> Redact GA params from pageview data

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/_layout-super-navigation-header.scss
- app/views/govuk_publishing_components/components/_layout_super_navigation_header.html.erb
- app/views/govuk_publishing_components/components/docs/cards.yml
- config/locales/en.yml
- spec/components/layout_super_navigation_header_spec.rb
In the footer and navbar, change all instances of `Topics` to `Services and information`.
Part of a series of changes being made to the homepage.
[Relevant Trello Card](https://trello.com/c/uUTQPB0r/1991-live-test-3-change-topics-to-services-and-information-on-homepage-header-footer-m)
> Change "Topics" to "Services and information"

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
* Change "Topics" to "Services and information" ([PR #3570](https://github.com/alphagov/govuk_publishing_components/pull/3570))
* Redact GA params from pageview data ([PR #3568](https://github.com/alphagov/govuk_publishing_components/pull/3568))
* Add GA4 tracking to devolved nations banners ([PR #3556](https://github.com/alphagov/govuk_publishing_components/pull/3556))
* Add GA4 tracking to the cookie banner ([PR #3564](https://github.com/alphagov/govuk_publishing_components/pull/3564))
> Version 35.15.0

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/_accordion.scss
Add new rule to override content-visibility in print styles.
The accordions should be expanded when printed. On browsers that support content visibility, the content was still hidden. The addition of this rule fixes this and ensures that printed pages will show all accordion sections.
> Add new rule to fix accordion print style

- CHANGELOG.md
- app/views/govuk_publishing_components/components/_attachment.html.erb
- spec/components/attachment_spec.rb
- Previously, we had our GA4 JSON attribute on the parent element of the attachment links (the `<section>` tag.)
- This meant that every link within this element would be tracked with the same attributes listed in the JSON.
- We don't want to do this anymore, as we realised there are links that we don't want tracked in this way (e.g. email links can be nested in the attachments.)
- Therefore, we move the `ga4_link` JSON onto the `data_attributes` hash. This hash is used by the attachment thumbnail link, and the attachment title link. And this is good as we only want the tracking on those links.
http://0.0.0.0:3212/component-guide/attachment
- https://trello.com/c/MHFXw6H2/552-change-filedownloads-on-attachment-pages-to-have-attachment-instead-of-generic-download-type
None.
> Fix GA4 bug - all attachments links tracked with the same JSON

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/vendor/lux/lux-reporter.js
Updating to new version of LUX as per https://github.com/alphagov/govuk_publishing_components/blob/main/docs/real-user-metrics.md
Slightly odd upgrade this time around - some of the `__ENABLE_POLYFILLS` stuff has been stripped out, and in some cases replaced with apparently redundant wrapping `{}` braces, which I don't quite understand. There's also a few comments where the indentation has been the same for the last few updates and I've been doggedly preserving our indentation to reduce the diff, but it doesn't seem worth keeping that up.
None.
> LUX version 311

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/_govspeak.scss
- app/views/govuk_publishing_components/components/layout_for_public/_account-layout.html.erb
Add rule to add link expansion to a elements in govspeak.
Standard practice for print styles is that links should be expanded to show url. For all links with 'govuk-link' class this was working as expected but links rendered by govspeak don't have the 'govuk-link' class applied and so these styles were not being applied.
> Add expansion to print style for govspeak links

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
* Add new rule to fix accordion print style ([PR #3582](https://github.com/alphagov/govuk_publishing_components/pull/3582))
* Fix GA4 bug - all attachments links tracked with the same JSON ([PR #3577](https://github.com/alphagov/govuk_publishing_components/pull/3577))
* LUX version 311 ([PR #3572](https://github.com/alphagov/govuk_publishing_components/pull/3572))
* Enable GA4 tracking on the phase banner ([PR #3588](https://github.com/alphagov/govuk_publishing_components/pull/3588))
* Add expansion to print style for govspeak links ([PR #3584](https://github.com/alphagov/govuk_publishing_components/pull/3584))
> Version 35.15.1

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/analytics-ga4/ga4-core.js
- app/assets/javascripts/govuk_publishing_components/analytics-ga4/ga4-event-tracker.js
- app/assets/javascripts/govuk_publishing_components/analytics-ga4/ga4-link-tracker.js
- spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-core.spec.js
- spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-event-tracker.spec.js
- spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-link-tracker.spec.js
- Ensures the page path is added to anchor links tracked by the `ga4-link-tracker` and `ga4-event-tracker`
- For example, `#england-and-wales` will become `/bank-holidays#england-and-wales` in the GA4 dashboard.
- I also cleaned up the link tracker slightly as we kept repeating `window.GOVUK.analyticsGa4.core.trackFunctions`, let me know your thoughts.
- Will add CHANGELOG when the pending release PR is live
https://trello.com/c/7thzJTbm/672-include-page-path-in-anchor-links
None.
> Prepend page path when tracking anchor links in GA4

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/vendor/lux/lux-reporter.js
- docs/real-user-metrics.md
Fix an error in the live real user monitoring script relating to the unusual way in which we use this script.
- to reproduce, clear cookies, reload page then accept cookies, error of `Uncaught TypeError: Cannot read properties of null (reading 'pop')` will occur
- this refers to the `getCustomerId()` function, which if `LUX.customerid` is not defined will attempt to determine it from the source URL of the LUX script, something like `lux.js?id=1234`
- we don't get our customerid this way, instead we hard code it into this file, because we host our own copy of the LUX script (see the documentation for more detail and background on this), so the script failed, because there was nothing to find
- instead we remove this part of the `getCustomerId()` function and simply return `LUX.customerid`. …
> Fix error in LUX script

- CHANGELOG.md
- Gemfile.lock
- lib/govuk_publishing_components/version.rb
* Fix error in LUX script ([PR #3592](https://github.com/alphagov/govuk_publishing_components/pull/3592))
* Prepend page path when tracking anchor links in GA4 ([PR #3590](https://github.com/alphagov/govuk_publishing_components/pull/3590))
> Version 35.15.2

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/analytics-ga4/ga4-core.js
- spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-core.spec.js
The results count heading contained new line characters and extra spaces, so splitting via the space character to parse the integer broke. This was fixed by using our `removeLinesAndExtraSpaces` function. 
I checked it on a local version of finder-frontend and the search results count is coming through now.
https://trello.com/c/MXhpmk9c/659-fix-search-results-count-on-viewitemlist-event
None.
> Fix bug with GA4 search results count

- CHANGELOG.md
- app/assets/stylesheets/govuk_publishing_components/components/_cards.scss
The existing grid setup forced every row to be the same height as the tallest row. But this causes large gaps of whitespace if one content item is larger than all the others, and a peculiar behaviour for the first row where it would always collapse, leaving row heights inconsistent.
Removing `grid-template-rows: auto` prevents the first row collapsing and removes the whitespace anomalies for the other rows.
Note that this change also requires guidance to be provided for content authors to ensure that each content item is of similar length which helps keeps the row heights consistent.
[Trello Link](https://trello.com/c/z4SoPSlt/1883-spacing-bug-on-some-browse-pages)
After reviewing the usage of the grid, designers and content authors preferred to fix the presentation of rows to be …
> Fix row spacing on topics browse pages

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/analytics-ga4/ga4-page-views.js
- spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-page-views.spec.js
Improve the code that strips/redacts `_gl` URL parameters when recording the URL for pageviews in GA4.
The [previous code](https://github.com/alphagov/govuk_publishing_components/pull/3568) assumed that `_gl` parameters were the same as `_ga` parameters. Turns out they're not - they can also contain letters, uppercase letters, asterisks and dashes. And also the character combination `_ga`, which is frankly just confusing.
None.
Trello card: https://trello.com/c/2hJRUoDM/660-redact-strip-ga-and-gl-trackers-from-page-location-and-page-referrer-values
> Improve GA URL parameter stripping

- CHANGELOG.md
- app/assets/javascripts/govuk_publishing_components/analytics-ga4/ga4-page-views.js
- app/views/govuk_publishing_components/components/_intervention.html.erb
- app/views/govuk_publishing_components/components/docs/intervention.yml
- spec/components/cookie_banner_spec.rb
- spec/components/devolved_nations_spec.rb
- spec/components/emergency_banner_spec.rb
- spec/components/intervention_spec.rb
- spec/components/phase_banner_spec.rb
- spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-page-views.spec.js
Hi @andysellick - would you be able to review this? I recommend looking commit by commit for this one. Thanks.
- Adds GA4 tracking to the intervention banner component.
- More specifically, it adds `intervention: 'true'/undefined` to the `pageview` if the banner is present. It sets this value based on the presence of `data-ga4-intervention-banner` in the DOM.
- The `ga4-link-tracker` is added to the element's "suggested" link.
- The `ga4-event-tracker` is added to the "Hide this message" link as we want to track it as `select_content` instead of a link.
- All of these rely on `ga4_tracking: true` so we can toggle tracking on and off on the banner.
- I also fixed a bug with the examples in the component guide. The `with_data_attributes` example implied that you can add …
> Add GA4 tracking to the intervention banner
