alphagov/govuk_publishing_components

app/controllers/govuk_publishing_components/application_controller.rb
spec/component_guide/component_guide_spec.rb
test/dummy/app/helpers/example_helper.rb
test/dummy/app/views/components/_test-component-with-helper.html.erb
test/dummy/app/views/components/docs/test-component-with-helper.yml

Previously a component that used it’s own app’s view helpers would error on the component guide with: `undefined method`
* Add example of component using a helper
* Write test against component
* Include Rails.application.helpers in ApplicationController to make those helper methods available when rendering the component through this Engine. https://stackoverflow.com/questions/9232175/#comment44856151_19453140
Note this does the opposite of a conventional gem: It needs things from the application to render views, rather than providing methods to an app.

Allow components to use application view helpers

---

app/controllers/govuk_publishing_components/component_guide_controller.rb
spec/component_guide/component_guide_spec.rb
test/dummy/app/controllers/welcome_controller.rb
test/dummy/app/views/welcome/index.html.erb
test/dummy/config/routes.rb

Depending on load ordering the value of “ApplicationController” can vary.
See: https://github.com/rails/rails/issues/12168
If you visited an application page before visiting the component guide, the guide would render within the host application’s layout rather than the gem’s.
* Be explicit about which ApplicationController we want to use
* Include what was a failing test to demonstrate fix
Hat-tip to @h-lame for pointing me in the right direction.

Explicitly extend namespaced controller

---

README.md
app/assets/stylesheets/govuk_publishing_components/component_guide.scss
app/models/govuk_publishing_components/component_doc.rb
app/views/govuk_publishing_components/component_guide/fixture.html.erb
app/views/govuk_publishing_components/component_guide/show.html.erb
govuk_publishing_components.gemspec
lib/govuk_publishing_components/engine.rb
spec/component_guide/component_guide_spec.rb
test/dummy/app/views/components/docs/test-component.yml

* Don't process all components every pageload
* Use govspeak to turn markdown into HTML
* Use govspeak (static) component to render HTML
* Style headings based on class not with default styles to avoid risk of affecting component partials and to make re-use easier
https://trello.com/c/qIwQRSai/35-1-gem-render-body-markdown-as-html
https://trello.com/c/gCTvBkD1/36-1-gem-render-accessibility-acceptance-criteria-and-update-documentation

Render accessibility criteria and body on component page

---

app/models/govuk_publishing_components/application_record.rb
test/dummy/app/models/application_record.rb

govuk_publishing_components doesn’t use ActiveRecord
This file was included as boilerplate when the gem was generated.
Without this fix the govuk_publishing_components gem doesn't run on Heroku when used with government-frontend (https://github.com/alphagov/government-frontend/pull/416):
> 2017-07-28T14:08:21.579099+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/govuk_publishing_components-0.3.0/app/models/govuk_publishing_components/application_record.rb:2:in '<module:GovukPublishingComponents>': uninitialized constant GovukPublishingComponents::ActiveRecord (NameError)
2017-07-28T14:08:21.579101+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/govuk_publishing_components-0.3.0/app/models/govuk_publishing_components/application_record.rb:1:in `<top (required)>'

Remove ApplicationRecord file

---

app/assets/stylesheets/govuk_publishing_components/component_guide.scss

- some code examples were taller than 300px, caused overflow problem
- moving max height from container to pre fixes
Changes this:
to this:

Fix height problem with code snippet examples

---

govuk_publishing_components.gemspec

We can’t upgrade slimmer on government-frontend to v11 without first relaxing the versions this gem needs.

Relax slimmer requirements

---

README.md
app/views/layouts/govuk_publishing_components/application.html.erb
lib/govuk_publishing_components/config.rb
spec/lib/config_spec.rb

Some components require print styles to render correctly.
Add an option to include print styles in the component guide. Apps handle print stylesheets differently – make this a configuration option without a default.

Add an optional print stylesheet to component guide

---

app/controllers/govuk_publishing_components/component_guide_controller.rb
app/models/govuk_publishing_components/component_doc.rb
app/models/govuk_publishing_components/component_doc_resolver.rb
app/models/govuk_publishing_components/component_fixture.rb
app/views/govuk_publishing_components/component_guide/component_doc/_call.html.erb
app/views/govuk_publishing_components/component_guide/component_doc/_preview.html.erb
app/views/govuk_publishing_components/component_guide/preview.html.erb

A small refactor to switch from structs to classes.
Specifically:
* split ComponentDoc model into ComponentDoc and ComponentDocResolver
* makes monkey patching the gem from an app easier (eg govuk-component-guide WIP: https://github.com/alphagov/govuk-component-guide/compare/component-gem#diff-bb6adab3eaf25dfc303b4f34455f5be9)
Addresses some of @alecgibson’s original review comments in https://github.com/alphagov/govuk_publishing_components/pull/1#discussion_r128566361

Split ComponentDoc into ComponentDoc and ComponentDocResolver

---

docs/component_conventions.md

The official BEM docs state that classes do not need to reflect the nested nature of the DOM. We need to update our own BEM docs to include this for other devs, as it can be easily missed. http://getbem.com/faq/#css-nested-elements

Update BEM docs to include flattened structure

---

app/models/govuk_publishing_components/component_fixture.rb
app/views/govuk_publishing_components/component_guide/component_doc/_preview.html.erb
app/views/govuk_publishing_components/component_guide/preview.html.erb
spec/component_guide/component_guide_spec.rb
test/dummy/app/views/components/_test-component-with-html-params.html.erb
test/dummy/app/views/components/docs/test-component-with-html-params.yml

Allow HTML strings to be written in YAML and rendered in the component guide as examples.
It is preferable to mark our trusted YAML strings as html_safe than to require `.html_safe` be included within each component. Safe HTML blocks are acceptable arguments to a component.

Mark fixture data as HTML safe

---

app/assets/javascripts/govuk_publishing_components/accessibility-test.js
spec/javascripts/govuk_publishing_components/AccessibilityTestSpec.js

The restoreScroll option was not being passed properly, I think this may
be an axe bug but this work around fixes the issue by double specifying where
axe should run.

Add context param to aXe so that options are passed correctly

---

app/assets/javascripts/govuk_publishing_components/accessibility-test.js
app/assets/stylesheets/govuk_publishing_components/application.scss
app/views/govuk_publishing_components/component_guide/component_doc/_component.html.erb
app/views/govuk_publishing_components/component_guide/component_doc/_preview.html.erb
app/views/govuk_publishing_components/component_guide/preview.html.erb
spec/component_guide/component_guide_spec.rb
spec/javascripts/govuk_publishing_components/AccessibilityTestSpec.js

In some cases, aXe is unable to definitely say whether there has been an accessibility error/violation. In these cases, it reports the potential error as 'incomplete', meaning it requires a manual check [(see more info here)](https://www.deque.com/blog/introducing-axe-2-1-7/). We want to show these underneath the relevant component so that developers are aware of what might require a manual check.

Display incomplete warnings from aXe in component guide

---

app/models/govuk_publishing_components/component_doc_resolver.rb
app/models/govuk_publishing_components/component_example.rb
app/views/govuk_publishing_components/component_guide/example.html.erb
app/views/govuk_publishing_components/component_guide/show.html.erb
docs/component_conventions.md
spec/component_guide/component_guide_spec.rb
test/dummy/app/views/components/_test-component-with-example-description.html.erb
test/dummy/app/views/components/docs/test-component-with-example-description.yml

- 'description' can be added to yml files at the same point as 'data' and 'context'
- description is output using govspeak in the same way as main description and accessibility_criteria
https://trello.com/c/2M84sEvg/133-improve-description-of-components-examples-1

Add descriptions to component examples

---

app/assets/stylesheets/govuk_publishing_components/application.scss
app/models/govuk_publishing_components/component_example.rb
app/views/govuk_publishing_components/component_guide/component_doc/_component.html.erb

Allow components to be viewed on a govuk-blue background
For example:

Add dark background context to gem

---

docs/component_conventions.md

We have added a dark-background context to the gem, so we need to update the docs.

Update docs to include background context

---

app/assets/stylesheets/govuk_publishing_components/application.scss
app/views/govuk_publishing_components/component_guide/index.html.erb

- adds links to component guide homepage linking to conventions and principles
https://trello.com/c/iVZWGnZA/131-1-link-to-principles-and-conventions-from-the-component-guide

Link to principles, conventions in component guide

---

README.md

We load the gem in a specific way to ensure it's not run in production.
Thanks again to @whoojemaflip 🚀

Add instructions on how to require the gem

---

app/assets/javascripts/govuk_publishing_components/vendor/matches-polyfill.min.js

This is not something that upsets government-frontend but static throws errors around
not having matches in CI.

Add Element#matches polyfill

---

app/controllers/govuk_publishing_components/application_controller.rb
spec/component_guide/component_guide_spec.rb

To enable our visual diff tool to work, we need to set X-Frame-Options to ALLOWALL so that the component guide can be embedded into an iframe.

Set X-Frame-Options to ALLOWALL

---

app/models/govuk_publishing_components/component_doc_resolver.rb
app/models/govuk_publishing_components/shared_accessibility_criteria.rb
docs/component_conventions.md
spec/component_guide/component_guide_spec.rb
test/dummy/app/views/components/_test-component-with-shared-accessibility-criteria-only.html.erb
test/dummy/app/views/components/_test-component-with-shared-accessibility-criteria.html.erb
test/dummy/app/views/components/docs/test-component-with-shared-accessibility-criteria-only.yml
test/dummy/app/views/components/docs/test-component-with-shared-accessibility-criteria.yml

- common accessibility criteria defined in the gem can be referenced in yml in components to save copying and pasting and reduce duplication
- shared_accessibility_criteria is a list
- only one defined at the moment, 'link'
- components can include accessibility_criteria, shared_accessibility_criteria, or both
https://trello.com/c/qS1pfVle/132-2-accessibility-criteria-universal-criteria-for-all-components

Add shared accessibility criteria

---

app/assets/javascripts/govuk_publishing_components/accessibility-test.js
spec/javascripts/govuk_publishing_components/AccessibilityTestSpec.js

Easiest to review with `?w=1` to ignore whitespace changes.
Our integration tests in government-frontend couldn't easily check that aXe was present and running on each page. If aXe itself had an error we swallowed the error and CI would report that as "no accessibility errors".
Refactoring to fix this unveiled one of these false positives: a problem with restoreScroll on pages with SVGs – a bug in aXe itself. Added a tweak to prevent this from erroring in the future. See: https://github.com/dequelabs/axe-core/issues/525
Use body class to indicate accessibility tests have run and their state.  Classes can be used in integration tests to confirm tests are running.
See: https://github.com/alphagov/government-frontend/compare/assert-axe-runs

Make it clear when aXe has failed, succeeded or found errors

---

app/controllers/govuk_publishing_components/application_controller.rb
spec/component_guide/component_guide_spec.rb

I have split this into a separate PR to https://github.com/alphagov/govuk_publishing_components/pull/61 so the Visual Diff Tool can be properly tested once this is merged.
This will allow the visual diff tool to correctly compare component guide pages without the banners adding noise to diff. We've set the path to '/component-guide' so the cookie only applies on routes on or below /component-guide.

Remove cookie and survey banners from guide

---

README.md
lib/govuk_publishing_components/minitest/component_guide_test.rb

Allow apps to include a component guide integration test that checks:
* all component examples render without error
* there are no accessibility errors on any of the previews
It asserts that the tests are available and have run. Any violations will throw a JS error.
Reviewers note: I wanted to include a test for the minitest test helpers. However, we have an intentionally failing test – a component with known accessibility errors, which I can't easily mock, stub or expect. That work is saved in a gist here: https://gist.github.com/fofr/ea3b60362f1cdf200c3090f6df98bc88

Add integration test helpers for component guide

---

app/assets/stylesheets/govuk_publishing_components/application.scss
app/controllers/govuk_publishing_components/application_controller.rb
spec/component_guide/component_guide_spec.rb

Cookies set in #65 to remove cookie/survey banners in the guide are not always being applied. It may be easier to hide the banners using CSS.

Fix for removal of cookie/survey banner in guide

---

app/assets/stylesheets/govuk_publishing_components/application.scss

The cookie/survey banners have a display: none styling on which overrides the styling in the gem.
Need to add !important flag to force this styling.

Override default styling of cookie banner to hide

---

README.md
app/assets/javascripts/govuk_publishing_components/visual-regression.js
spec/javascripts/govuk_publishing_components/VisualRegressionSpec.js
spec/javascripts/support/jasmine.yml

Add a JS/CSS visual diff tool which allows developers to compare local dev pages to live for visual regressions.
The tool relies on mix-blend-mode and filters which aren't supported in IE or Edge. In these cases, the tool simply overlays the live page onto the local page:
**Note: the tool relies on X-Frame-Options being set to ALLOWALL on live pages. Therefore the tool may not be able to be run on all GOV.UK pages.**

Add visual diff JS tool

---

app/assets/javascripts/govuk_publishing_components/accessibility-test.js
spec/component_guide/component_example_accessibility_testing_spec.rb
test/dummy/app/views/components/_test-component-with-duplicate-ids.html.erb
test/dummy/app/views/components/docs/test-component-with-duplicate-ids.yml
test/dummy/config/initializers/new_framework_defaults.rb

Components sometimes contain IDs. These get repeated on the component
guide page. This repetition is not representative of actual usage,
leading to a false positive accessibility failure.
This specifically affects the document_footer component in static where
we rely on a specific component ID to link to from elsewhere in the
page – so it can’t be dynamic and unique with each use.

Disable duplicate ID rule in axe tests

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/application.scss

This would flash a box around the component on hover. Box shadows look
out of place and the effect can be confusing, especially with
components that have a solid background.
The `govuk-` namespace is deprecated.

Remove component guide hover styles

---

app/assets/javascripts/govuk_publishing_components/accessibility-test.js
app/assets/stylesheets/govuk_publishing_components/application.scss
app/views/govuk_publishing_components/component_guide/component_doc/_preview.html.erb
spec/component_guide/component_example_accessibility_testing_spec.rb
spec/javascripts/govuk_publishing_components/AccessibilityTestSpec.js
test/dummy/app/views/components/_test-component-with-a11y-incomplete-warning.html.erb
test/dummy/app/views/components/docs/test-component-with-a11y-incomplete-warning.yml

* Refactor incomplete warnings JS to work with both incomplete and violations
* Improve typography of HTML output - large text and increased spacing between text
* Update to cope better with multiple reasons (eg an image without an alt tag can have many possible solutions)
* Add integration tests for both warnings and violations

Render accessibility violations in component guide

---

app/views/govuk_publishing_components/component_guide/component_doc/_call.html.erb
spec/component_guide/component_example_spec.rb

We were missing a comma, I've updated the tests so they're more complete, easier to read and update.
Fixes https://github.com/alphagov/govuk_publishing_components/issues/85

Fix how to call snippets so they're correct

---

lib/tasks/govuk_publishing_components_tasks.rake

When running bundle exec rake, if an app uses the govuk_publishing_components gem, it will warn if component files exist (html.erb) without corresponding docs (.yml)
**Example:**

Warn if components exist without docs

---

CHANGELOG.md
lib/govuk_publishing_components/version.rb

Incorporates accessibility warnings:
https://github.com/alphagov/govuk_publishing_components/pull/90

Version 1.12.0

---

app/assets/stylesheets/govuk_publishing_components/application.scss
app/views/govuk_publishing_components/component_guide/show.html.erb
test/dummy/app/views/govuk_component/lead_paragraph.raw.html.erb

- Replace code that renders first paragraph in examples
- Remove redundant CSS
- Stub lead_paragraph for testing

Use lead paragraph component

---

Rakefile
govuk_publishing_components.gemspec

For: https://trello.com/c/QtpGwa2A/288-improve-feedback-on-github-for-changes-to-govuk-content-schemas
Mostly this is to support the changes to `buildProject` proposed in https://github.com/alphagov/govuk-puppet/pull/6821 although the changes should be generally useful.

Allow asset compilation in production mode and add assets clobber

---

README.md
app/assets/javascripts/govuk_publishing_components/accessibility-test.js
app/models/govuk_publishing_components/component_doc.rb
app/models/govuk_publishing_components/component_doc_resolver.rb
app/views/govuk_publishing_components/component_guide/component_doc/_preview.html.erb
app/views/govuk_publishing_components/component_guide/preview.html.erb
spec/javascripts/govuk_publishing_components/AccessibilityTestSpec.js
test/dummy/app/views/components/_test-component-with-duplicate-ids.html.erb
test/dummy/app/views/components/docs/test-component-with-duplicate-ids.yml

When trying to add a radio button component to government-frontend I was hitting a rule since they're not in a fieldset, I want to be able to remove this.
I've made it so you can see the id you need to use in the error/frontend, and allowed you to use that id to exclude rules.
Adds to the original test that was making sure the `duplicate-id` rule doesnt throw an error.
https://trello.com/c/yo9dWRM8/242-create-a-radio-button-component

Allow excluded rules to be specified

---

app/assets/stylesheets/components/_task-list-print.scss
app/assets/stylesheets/components/_task-list.scss

A few visual-related changes:
- iphone was having difficulty with the white background on the inner element of the numbers (added so numbers are still legible when text only is zoomed) where it was overflowing slightly and corrupting the outer circle. This white background has now been replaced with a similar effect achieved with text shadow.
- overflow hidden removed from overall component to prevent clipping of beginning of logic text ('or', 'and') in some steps, which is aligned to grow to the left when text only is zoomed, to prevent overlap onto the step titles.
- overflow hidden was previously added to solve a problem with iphone 4 where the final part of the line down the side of the task list 'escaped' the component (it was ignoring the calc'ed height). Now overflow hidden is …

Fix task list appearance

---

app/assets/stylesheets/components/_task-list.scss
app/views/components/docs/task_list.yml

Fix active styles for choice lists (no before image but the big dot wasn't on the line):
Fix outline styles for Firefox, before:
After:
Tested in IE8+, Edge 14+, latest Chrome, latest Firefox.

Fix task list active link

---

app/assets/javascripts/govuk_publishing_components/visual-regression.js
app/models/govuk_publishing_components/component_doc_resolver.rb

Components were being ordered by their filename but displayed their name in the component list. For some components such as “Form label”
(label.html.erb), the component wasn’t appearing where expected.
* Always sort the list of components by name

Sort components by name

---

Procfile
README.md

https://trello.com/c/HSre7K10/453-style-the-mvp-email-collection-page-needed-by-jan
The #publishing-frontend team want to be able to work on the gem without
having to mount it into another Rails application first. We can use the
dummy Rails app the test suite uses to achieve this.
Other PR: https://github.com/alphagov/govuk-puppet/pull/7014

Add a Procfile so we can run as a govuk::app in puppet

---

CHANGELOG.md
lib/govuk_publishing_components/version.rb

The ES6 issue is causing problems for uglifier version bumps on (for example) [government-frontend](https://github.com/alphagov/government-frontend/pull/648)

Bump version

---

app/models/govuk_publishing_components/component_example.rb
app/views/govuk_publishing_components/component_guide/component_doc/_call.html.erb
app/views/govuk_publishing_components/component_guide/component_doc/_component.html.erb
docs/component_conventions.md
spec/component_guide/component_example_spec.rb
spec/dummy/app/views/components/_test-component-with-block.html.erb
spec/dummy/app/views/components/docs/test-component-with-block.yml

ERB's render method accepts a block, which is useful for components which
embed multiple components for a specific purpose (eg. a content list with
a back-to-top link).
The component guide should be able to render the docs for this type of component
so this PR adds the ability to configure the component guide with a specific example data key:
```yaml
examples:
default:
data:
block: |
<div><%= some_local_thing %></div>
```

Support components accepting blocks

---

CHANGELOG.md
lib/govuk_publishing_components/version.rb

Bump version because https://github.com/alphagov/govuk_publishing_components/pull/117

Bump version to 3.1.0

---

app/assets/stylesheets/components/_fieldset.scss
app/assets/stylesheets/components/_label.scss
app/assets/stylesheets/components/_radio.scss
app/assets/stylesheets/components/helpers/_clearfix.scss
app/assets/stylesheets/components/helpers/_px-to-em.scss
app/assets/stylesheets/components/helpers/_variables.scss
app/assets/stylesheets/govuk_publishing_components/application.scss
app/views/components/_fieldset.html.erb
app/views/components/_label.html.erb
app/views/components/_radio.html.erb
app/views/components/docs/fieldset.yml
app/views/components/docs/label.yml
app/views/components/docs/radio.yml
config/locales/en.yml
spec/components/fieldset_test_spec.rb
spec/components/label_test_spec.rb
spec/components/radio_test_spec.rb

Moves form related components needed in [email-alert-frontend](https://github.com/alphagov/email-alert-frontend) into the gem so they can be used across applications.
We're avoiding [static](https://github.com/alphagov/static) here since these pages need strong integration tests within the applications they are used in, and `static` mocks components.
These were originally implemented in the following pull requests to `government-frontend`
- [Radio and label](https://github.com/alphagov/government-frontend/pull/552)
- [Fieldset](https://github.com/alphagov/government-frontend/pull/561)
We'll move the error related components later to make the PR smaller.
We will do a follow up PR to remove these components from `government-frontend`
As part of …

Move form components into gem

---

CHANGELOG.md
app/assets/stylesheets/components/_task-list.scss
app/views/components/_task_list.html.erb
app/views/components/docs/task_list.yml
spec/components/task_list_spec.rb

Change how the 'get help with this step' link works, specifically:
- restyle the link to be bold so it stands out more (users missed it in lab)
- add a 'heading' element into the task list content, works like a paragraph but outputs a heading (needed for 'get help' section in main task lists)
- change get help link functionality to be a per-step option, not a global (all steps) option, necessary because only some steps need a get help link
Get help section (showing new heading element):
Get help link (now bold):
- [Trello card](https://trello.com/c/0z6EzxSr/403-add-the-get-help-link-to-the-small-task-list-component-and-the-task-list-page)

Rework get help link

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/application.scss
app/views/govuk_publishing_components/component_guide/component_doc/_call.html.erb

Styles for p and list tags inside the component-doc class were not needed and causing layout of component examples to break in some circumstances.
These styles were used inside the wrapping element for the opening text and 'How to call this example' and 'How it looks' sections of the component guide, for example on the [preview page](https://government-frontend.herokuapp.com/component-guide/task_list/or_then) and [main component detail page](http://collections.dev.gov.uk/component-guide/task_list).
Example of the problem these styles were causing, this is the task list...
Should look like this...
Fixes #106

Remove unneeded component guide styles

---

CHANGELOG.md
app/assets/stylesheets/components/_task-list-print.scss
app/views/layouts/govuk_publishing_components/application.html.erb

Update print styles so the task list looks better when printed.
Specifically, add in spacing and lines and number circles to print stylesheet so that printed version more closely (but not exactly) resembles screen version, for consistency.
Also change component guide so main stylesheet is delivered to screen, not 'all' (was causing problems when showing both screen and print stylesheets).
Looks like this in print view:
Trello card: https://trello.com/c/9CD3dY7r/409-add-task-list-print-styles-to-apps

Improve task list component print styles

---

CHANGELOG.md
lib/govuk_publishing_components/version.rb

* Remove unneeded CSS from component guide (PR #126)
* Add heading element into task list component and change get help link behaviour (PR #113)
* Improve task list print styles (PR #125)
* Move form components into gem (PR #116)

Bump gem to 3.2.0

---

CHANGELOG.md
config/locales/cy.yml
spec/components/radio_test_spec.rb

This was missed when moving this component upstream from `government-frontend`
See https://github.com/alphagov/government-frontend/pull/671#discussion_r159884811

Fix radio component not including welsh translation

---

app/assets/stylesheets/components/_back-link.scss
app/assets/stylesheets/govuk_publishing_components/application.scss
app/views/components/_back_link.html.erb
app/views/components/docs/back_link.yml
config/locales/cy.yml
config/locales/en.yml
spec/components/back_link_spec.rb
spec/components/radio_test_spec.rb

https://trello.com/c/HSre7K10/453-style-the-mvp-email-collection-page-needed-by-jan
Add Back Link component
Moved from government-frontend for use in email-alert-frontend
Also renames the namespace to `gem`
Originally implemented in alphagov/government-frontend#568

Extract the back_link component to govuk_publishing_components

---

README.md
startup.sh

Allow app to be started from VM like other apps:
`./startup.sh` or `./startup.sh —live`
Dummy app will be available at:
http://dev.gov.uk:3212/component-guide
http://publishing-components.dev.gov.uk/component-guide

Add startup script to match frontend apps

---

CHANGELOG.md
lib/govuk_publishing_components/version.rb

* Namespace hosted components with `govuk_publishing_components` (PR
#136)
* References to components hosted in gem need to point to
`govuk_publishing_components/components` rather than `/components`.
This includes stylesheets, partials and javascripts.
* References to task list print styles must be updated to point at
the new /print subdirectory

Version 4.0.0

---

app/assets/javascripts/govuk_publishing_components/components/error-summary.js
app/assets/stylesheets/govuk_publishing_components/application.scss
app/assets/stylesheets/govuk_publishing_components/components/_error-summary.scss
app/views/govuk_publishing_components/components/_error_summary.html.erb
app/views/govuk_publishing_components/components/docs/error_summary.yml
spec/components/error_summary_spec.rb
spec/javascripts/components/error-summary-spec.js

We’d like to use this in email-alert-frontend
https://trello.com/c/HSre7K10/453-style-the-mvp-email-collection-page-needed-by-jan
Screenshot demonstrating the focus on page load:

Extract the error_summary component from government-frontend

---

CHANGELOG.md
lib/govuk_publishing_components/version.rb

https://trello.com/c/HSre7K10/453-style-the-mvp-email-collection-page-needed-by-jan
I'd like to update government-frontend to use the latest version of this gem. It makes sense to release the error summary changes before I do this so I can make all the updates in one go.

Release version 4.1.0

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/_task-list-related.scss
app/views/govuk_publishing_components/components/_task_list_related.html.erb
spec/components/task_list_related_spec.rb

Task list related links component had the old pub-c namespace for CSS, not the new gem namespace, gem-c. Whoops.

[DO NOT MERGE] Fix task list related component namespace

---

app.json

Heroku needs uglifier, which is a development dependency. Setting this environment variable will make Heroku install the development dependencies too. I got https://github.com/alphagov/govuk_publishing_components/pull/149 working by doing this manually, but having it in app.json will make it work for Review apps too.

Make sure we bundle development gems too on Heroku

---

Rakefile

It appears that RSpec is not available until it's been required.  This was causing rspec tests to not be run as part of `bundle exec rake` or `bundle exec rake spec`.
(I'm not sure whether this fixes the problem it was originally changed to resolve.)

Fix RSpec tests in CI

---

app/assets/stylesheets/govuk_publishing_components/application.scss
app/assets/stylesheets/govuk_publishing_components/components/_input.scss
app/assets/stylesheets/govuk_publishing_components/components/helpers/_variables.scss
app/views/govuk_publishing_components/components/_input.html.erb
app/views/govuk_publishing_components/components/docs/input.yml
spec/components/input_spec.rb

This imports the `input` component from [email-alert-frontend](https://github.com/alphagov/email-alert-frontend). We intend to use this in the new survey component, which has a number of forms (https://github.com/alphagov/govuk_publishing_components/pull/151).
The code is unchanged, except for changing the class names from `pub-c-*` to `gem-c-*`.
Component preview:
👉 https://govuk-publishing-compon-pr-152.herokuapp.com/component-guide/input
https://trello.com/c/oRLXhaTU

Port input field component

---

CHANGELOG.md
app/assets/javascripts/govuk_publishing_components/components/task-list.js
app/assets/stylesheets/govuk_publishing_components/components/_task-list.scss
app/views/govuk_publishing_components/components/_task_list.html.erb
app/views/govuk_publishing_components/components/docs/task_list.yml
lib/govuk_publishing_components/components/task_list_helper.rb
spec/components/task_list_spec.rb
spec/javascripts/components/task-list-spec.js

To simplify the task list component code we are removing the concept of groups of steps. Instead, the task list data will simply be a series of steps, some of which can be configured to have the 'and' or 'or' appearance.
This means removing one of the nested arrays in the data structure, so that a task list is now defined by an array of objects, not an array of an array of objects.
i.e.
`
steps: [
{
title: 'A step'
}
]
`
instead of
`
groups: [
[
{
title: 'A step'
}
]
]
`
**Breaking changes**
- data passed to component as 'groups' is now 'steps'
- steps that should be marked as 'and' instead of being numbered must now explicitly have the logic parameter, otherwise they'll just be given numbers
- any other references to groups such as 'highlight_group' are now steps, e.g. 'highlight_step' …

Remove groups from component

---

CHANGELOG.md
app/assets/javascripts/govuk_publishing_components/components/step-by-step-nav.js
app/views/govuk_publishing_components/components/_step_by_step_nav.html.erb
app/views/govuk_publishing_components/components/_step_by_step_nav_header.html.erb
app/views/govuk_publishing_components/components/_step_by_step_nav_related.html.erb
app/views/govuk_publishing_components/components/docs/step_by_step_nav.yml
app/views/govuk_publishing_components/components/docs/step_by_step_nav_header.yml
app/views/govuk_publishing_components/components/docs/step_by_step_nav_related.yml
spec/components/step_by_step_nav_header_spec.rb
spec/components/step_by_step_nav_related_spec.rb
spec/components/step_by_step_nav_spec.rb
spec/javascripts/components/step-by-step-nav-spec.js

Add the option to all step nav components to pass an id that will be included in all GA events as dimension96.
Trello card: https://trello.com/c/J3VzLCnk/493-add-unique-id-parameter-to-step-nav-components-for-dimension96-tracking

Add unique tracking id option to step by step nav

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_input.html.erb
app/views/govuk_publishing_components/components/docs/input.yml
spec/components/input_spec.rb

Hello :wave:
This allows the rendered HTML to be `<input type="email" />` or whatever
other incarnation may be needed. By default this will be text.
There's potential here that you could hit some rendering issues by
putting in something wacky here, but it feels too restrictive to try
prevent that here.
See the [rendered component](https://govuk-publishing-compon-pr-165.herokuapp.com/component-guide/input)

Support different input types for Input component

---

app/models/govuk_publishing_components/component_doc.rb
app/views/govuk_publishing_components/component_guide/show.html.erb

This adds a link to GitHub code search (scoped to alphagov) for components. It allows you to easily find places where a certain component is used.
https://trello.com/c/hIWEcXAo

Add link to GitHub to find component usage

---

CHANGELOG.md
app/assets/javascripts/govuk_publishing_components/components/feedback.js
app/assets/stylesheets/govuk_publishing_components/_all_components.scss
app/assets/stylesheets/govuk_publishing_components/_all_components_print.scss
app/assets/stylesheets/govuk_publishing_components/component_guide_print.scss
app/assets/stylesheets/govuk_publishing_components/components/_feedback.scss
app/assets/stylesheets/govuk_publishing_components/components/print/_feedback.scss
app/controllers/govuk_publishing_components/application_controller.rb
app/views/govuk_publishing_components/components/_feedback.html.erb
app/views/govuk_publishing_components/components/docs/feedback.yml
app/views/layouts/govuk_publishing_components/application.html.erb
config/initializers/assets.rb
spec/components/feedback_spec.rb
spec/javascripts/components/feedback-spec.js
spec/javascripts/support/jasmine.yml
spec/javascripts/vendor/mock-ajax.js

Build the new feedback form to go at the foot of all GOV.UK pages. This is based on the code from the Service Manual but with some changes, as this version requires additional functionality.
Ultimately this component will be moved to the publishing components gem, but I started building it in static so getting it reviewed here because the commit history might prove useful to that.
Initial state:
Users have three options:
1. click 'yes' (page is useful) records a GA event and shows a 'thanks for your feedback' message
2. click 'no' (page is not useful) opens a form to take an email address to send a link to a survey to. This is a rework of the form that currently appears underneath the header of GOV.UK for some users at some times (you can trigger this by visiting GOV.UK and running …

Add feedback component

---

app/assets/stylesheets/govuk_publishing_components/components/_input.scss

The bank holidays page is using an older layout, which includes [the button CSS](https://github.com/alphagov/static/blob/79d29b6a4221874ead27e67d007704a6be166a57/app/assets/stylesheets/helpers/_buttons.scss#L91-L122). This contains a style rule on the `input` element, rather than a class.
To make the  styles for the `input` component work on these layouts we need to make the component more specific (unfortunately). We also reset the margin to override the styles from buttons.css.
Paired with @andysellick on this.
https://trello.com/c/8TC3AEms

Make input work on older layouts

---

app/assets/stylesheets/govuk_publishing_components/components/_feedback.scss

The input/label component used in this component has a font size of core-19, which is bigger than the core-16 design for the rest of this component. This PR brings the other fonts inside these forms inline with the input/label component. Elements are:
- headings and error headings
- paragraphs and error paragraphs
- close buttons
This may be slightly controversial as it goes against the design, but I figure consistency with the rest of our components is a good idea and the larger font size is much easier to read.
Haven't changed the font size of the initial state of the component.
Before:
After:
https://trello.com/c/8TC3AEms

Make form contents font sizes consistent

---

app/assets/stylesheets/govuk_publishing_components/components/_feedback.scss
app/views/govuk_publishing_components/components/_feedback.html.erb

- make close button position consistent
- improve layout of link "don't have an email address" by putting on newline on mobile and improving spacing on tablet and above
Before:
After:
https://trello.com/c/8TC3AEms

Improve feedback component layout on mobile

---

app/assets/javascripts/govuk_publishing_components/components/feedback.js
app/assets/stylesheets/govuk_publishing_components/components/_feedback.scss
app/views/govuk_publishing_components/components/_feedback.html.erb
app/views/govuk_publishing_components/components/_input.html.erb
app/views/govuk_publishing_components/components/docs/feedback.yml
app/views/govuk_publishing_components/components/docs/input.yml
spec/components/input_spec.rb
spec/javascripts/components/feedback-spec.js

Changes in response to [accessibility review of the feedback component](https://github.com/alphagov/govuk_publishing_components/pull/163#issuecomment-366267858)
Issues addressed:
- 2, expanded the input component used by the feedback component to include an aria-describedby attribute, then set to the id of the describing paragraph. Have only tested this in VO on Safari.
- 3, have set focus back to the initial 'is something wrong' prompt on form close.
- 5, can't do much against the GOV.UK font mixins, but I've removed the explicit definition on the initial 'is something wrong' text so it's at least consistent compared with the links next to it (i.e. all of them are now resizable)
I don't currently have fixes for the remaining issues, @selfthinker happy to discuss further.

Fix feedback component accessibility issues

---

app/views/govuk_publishing_components/components/_related_navigation.html.erb
app/views/govuk_publishing_components/components/docs/related_navigation.yml

Based on feedback from the accessibility team this
- Moves the navigation header inside the navigation element
- Removes the aside/complementary semantics
The accessibility team have agreed that the navigation component should be marked up as navigation and not as tangential content (see [Trello card](https://trello.com/c/S96QAn30/274-improve-accessibilty-context-of-related-navigation-link-grouping)).

Improve accessibility of related navigation

---

app/assets/javascripts/govuk_publishing_components/components/feedback.js
app/views/govuk_publishing_components/components/_feedback.html.erb
spec/javascripts/components/feedback-spec.js

Changes to the GA tracking on the new feedback component for GOV.UK.
Link for testing: https://govuk-publishing-compon-pr-184.herokuapp.com/component-guide/feedback/preview
- Trello card: https://trello.com/c/3RTCSaMA/8-change-the-ga-tracking-for-is-there-anything-wrong-with-this-page-cta
- Component guide: https://govuk-publishing-compon-pr-184.herokuapp.com/component-guide/feedback

Change feedback tracking

---

Gemfile.lock
govuk_publishing_components.gemspec

This isn't actually used.
cc @emmabeynon

Drop govuk-content-schema-test-helpers dependency

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/_feedback.scss

- make spacing generally a bit better on desktop
- make spacing bigger on mobile between yes and no
- make 'anything wrong' link collapse to left on mobile and increase top spacing
**Before (desktop):**
**After (desktop):**
**Before (mobile):**
**After (mobile):**
Trello card: https://trello.com/c/Z3n0hmzi/6-hit-targets-for-yes-no-and-is-there-anything-wrong-too-small-on-mobile

Improve feedback link spacing

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/_feedback.scss

- set font size for 'is this page useful?' and links beside it
- various apps have styles that were affecting the component, defining them explicitly like this should help
- does prevent an earlier accessibility fix to allow text resizing in the browser settings to work, but since that doesn't work in the rest of the component where we already defined font sizes, or even in the rest of GOV.UK, this doesn't seem like a huge concern
Trello card: https://trello.com/c/vKfhGFtn/4-font-sizing-on-frontend-whitehall

Set feedback component font sizes for initial state

---

spec/component_guide/component_index_spec.rb
spec/dummy/config/routes.rb

Means review apps can be visited directly without needing to append the
component guide URL to the end.
Links to Heroku review apps in Github PRs will work as expected.
eg https://govuk-publishing-compon-pr-189.herokuapp.com/

Redirect dummy app root to component guide

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/_feedback.scss

Trello card: https://trello.com/c/T3ez6Xxk/12-often-no-space-between-content-and-component

Add spacing above feedback component

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_feedback.html.erb

Add role="button" to the 'No' and 'Is anything wrong with this page?' links for screen reader users.
Trello card: https://trello.com/c/mTVAGvjC/13-feedback-survey-control-needs-to-be-a-button-or-link-with-rolebutton

Add role button to links

---

app/assets/stylesheets/govuk_publishing_components/components/_feedback.scss

I suspect that this was caused by https://github.com/alphagov/govuk_publishing_components/pull/190, but can't be sure.

Feedback component: Fix styling on pages with older layouts

---

CHANGELOG.md
Gemfile.lock
govuk_publishing_components.gemspec
lib/govuk_publishing_components.rb
lib/govuk_publishing_components/step_nav.rb
lib/govuk_publishing_components/step_nav_helper.rb
spec/dummy/app/controllers/step_nav_controller.rb
spec/dummy/app/lib/services.rb
spec/dummy/app/views/step_nav/show.html.erb
spec/dummy/config/initializers/gds_api.rb
spec/dummy/config/routes.rb
spec/features/step_nav_helper_spec.rb
spec/lib/step_nav_helper_spec.rb

There is a version of this in govuk_navigation_helpers which provided similar assistance when we were using hard coded step navigation configuration held in the gem.  We are retiring that approach for two reasons:
- govuk_navigation helpers is too closely coupled to govuk_publishing_components so we need to move [those coupled things](https://github.com/alphagov/govuk_navigation_helpers/blob/master/lib/govuk_navigation_helpers/step_nav_content.rb) out of that gem and into this one.
- we can now use linked `part_of_step_navs` content to power the step nav configuration so we can get move away from hardcoded files.
`step_nav` is fairly barebones, but I intend to expand this in future to replace [the current equivalent in collections](https://github.com/alphagov/collections/blob/086758a7ec50e …

Add step by step navigation component helpers

---

CHANGELOG.md
Gemfile.lock
app/assets/stylesheets/govuk_publishing_components/_all_components.scss
app/assets/stylesheets/govuk_publishing_components/components/_document-list.scss
app/views/govuk_publishing_components/components/_document_list.html.erb
app/views/govuk_publishing_components/components/docs/document_list.yml
spec/components/document_list_spec.rb

The new topic pages will need to use the document-list component to display a list of content items.
We therefore need to move the component into govuk_publishing_components so it can be accessed by the Collections app (where topic pages will live)

Move document_list component from government-frontend

---

CHANGELOG.md
lib/govuk_publishing_components/version.rb

Add document_list component from government-frontend, so that it can be used by collections. This is not a breaking change, but it is not backwards compatible with previous versions of the component. (PR #199)

Release 5.4.0

---

Gemfile.lock
lib/govuk_publishing_components/step_nav.rb
lib/govuk_publishing_components/step_nav_helper.rb
spec/features/step_nav_helper_spec.rb
spec/lib/step_nav_helper_spec.rb

To enable us to preview pages at all stages of the content design process we
need to be able to handle step by step navs with zero steps.
This adds tests and adjusts the show_sidebar logic to handle this.
We allow zero steps in https://github.com/alphagov/govuk-content-schemas/pull/734

Allow step by step nav pages with 0 steps

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

For https://trello.com/c/nGtzTPCu/283-update-government-frontend-to-use-relatednavigation-component

Bump to 5.4.1

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/_all_components.scss
app/assets/stylesheets/govuk_publishing_components/components/_inverse-header.scss
app/views/govuk_publishing_components/components/_inverse_header.html.erb
app/views/govuk_publishing_components/components/docs/inverse_header.yml
spec/components/inverse_header_spec.rb

This component is a wrapper header to be used on topic and list pages:
https://trello.com/c/g2MMWMQr/110-blue-header
Component Guide Link: https://govuk-publishing-compon-pr-203.herokuapp.com/component-guide/inverse_header

Add inverse header component

---

lib/govuk_publishing_components/components/related_navigation_helper.rb
spec/lib/related_navigation_helper_spec.rb

For https://trello.com/c/nGtzTPCu/283-update-government-frontend-to-use-relatednavigation-component
Some work unrelated to this PR has flagged that there are occasions where an
ordered related link may not be tagged to a mainstream browse pages, and the
current implementation does not handle this gracefully, so we update it to
better handle this edge case.

Handle related items not tagged to mainstream browse pages

---

app/assets/stylesheets/govuk_publishing_components/components/_inverse-header.scss
app/views/govuk_publishing_components/components/_inverse_header.html.erb
app/views/govuk_publishing_components/components/docs/inverse_header.yml
spec/components/inverse_header_spec.rb

In this commit I have added the option to pass a flag to the component
to indicate if the header component will cover the full width of the
page. If so, the left-right padding is removed for the header so it’s 
content can line up with the rest of the content on the page.
I also added a bottom margin of 30px to the component.
https://trello.com/c/xfcxY63h/122-correct-page-header-component-padding

Add option to removed side padding if full width

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/_document-list.scss
app/views/govuk_publishing_components/components/_document_list.html.erb
app/views/govuk_publishing_components/components/docs/document_list.yml
spec/components/document_list_spec.rb

We want to make use of the document list component on topic pages. For mainstream services, we want to show a description of the document rather than metadata.
In the future, we may also want to supply additional metadata for each document, such as organisation and collection the document belongs to. This PR refactors the component to stop it being limited to only updated date and document type
Component Guide Link: https://govuk-publishing-compon-pr-202.herokuapp.com/component-guide/document_list

Update document list with description

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/_inverse-header.scss
app/views/govuk_publishing_components/components/docs/inverse_header.yml

Tests for accessibility in other apps failed where the inverse header component in isolation didn't have the required context to make its example content render in white. Since the point of an inverse state is to have light on dark, I have updated the component to be more opinionated about white text. This would require overrides if white weren't desired but all planned implementations currently use white anyway. Unfortunately, this has required me to colour the "a" tag as the component is unaware of what CSS classes might be applied.

Enforce white text and links for inverse header component

---

CHANGELOG.md
lib/govuk_publishing_components.rb

Because I didn't put in a changelog, 5.5.3 got accidentally released as a minor version (while https://github.com/alphagov/govuk_publishing_components/pull/206 is super breaking). 
This PR makes the changes backwards compatible so that apps don't have to update.
We'll do the updating at a later time, when there are more breaking changes to ship at the same time. That hopefully minimises the impact.

Make changes released in 5.5.3 backwards compatible

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/_document-list.scss
app/views/govuk_publishing_components/components/_document_list.html.erb
spec/components/document_list_spec.rb

We require the document list component to have top and bottom margins around it on topic pages. This commit allows us to set `margin_bottom` and `margin_top` flags to set this spacing.

Add margin spacing to document list

---

CHANGELOG.md
Gemfile.lock
app/assets/stylesheets/govuk_publishing_components/components/_feedback.scss
app/views/govuk_publishing_components/components/_feedback.html.erb
spec/components/feedback_spec.rb

Topic pages need the feedback component to be flush with the bottom of the taxon grid. We therefore need to be able to add a flag to remove the top margin in these cases
Example use on a topic page:

Add margin_top flag to feedback component

---

CHANGELOG.md
Gemfile.lock
app.json
app/views/govuk_publishing_components/components/_contextual_breadcrumbs.html.erb
app/views/govuk_publishing_components/components/_contextual_sidebar.html.erb
app/views/govuk_publishing_components/components/docs/contextual_breadcrumbs.yml
app/views/govuk_publishing_components/components/docs/contextual_sidebar.yml
govuk_publishing_components.gemspec
lib/govuk_publishing_components.rb
lib/govuk_publishing_components/presenters/contextual_navigation.rb
lib/govuk_publishing_components/presenters/navigation_type.rb
lib/govuk_publishing_components/presenters/related_navigation_helper.rb
spec/dummy/app/controllers/application_controller.rb
spec/dummy/app/controllers/welcome_controller.rb
spec/dummy/app/views/layouts/application.html.erb
spec/dummy/app/views/welcome/contextual_navigation.html.erb
spec/dummy/config/routes.rb
spec/features/contextual_navigation_spec.rb
spec/features/step_nav_helper_spec.rb
spec/lib/presenters/related_navigation_helper_spec.rb
spec/spec_helper.rb
startup.sh

This PR adds 2 new components: the contextual breadcrumbs and contextual sidebar. The idea behind the new components is that they encapsulate all of the logic for the breadcrumbs and sidebars. They only take a content item as input and make the decisions what to show based on that.
https://govuk-publishing-compon-pr-228.herokuapp.com/component-guide/contextual_sidebar
https://govuk-publishing-compon-pr-228.herokuapp.com/component-guide/contextual_breadcrumbs
I hope we can achieve the following:
- Have a single place that makes the decisions about sidebar & breadcrumbs. This avoids confusion about the what we should show and makes it easier to understand and and communicate this.
- Avoid duplication between applications: currently the taxonomy logic is duplicated in government-frontend and …

Create contextual navigation components

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/_document-list.scss

We added the top and bottom margin flags for the document list component for use on topic pages.
However, the margin values are too large - we need to shrink them to work with our designs.

Reduce spacing for margins on document list

---

spec/features/contextual_navigation_spec.rb

This always checks the last bit of the breadcrumbs, which should be the parent. Avoids failing tests when the random content generator adds a parent to the parent.

Make integration test more robust

---

CHANGELOG.md
app/assets/javascripts/govuk_publishing_components/components/feedback.js
spec/javascripts/components/feedback-spec.js

- was in original feedback form but I missed it when developing the new one
- is appended on page load with JS
Trello card: https://trello.com/c/vNYebDCP/193-new-feedback-component-does-not-pass-referrer

Restore 'referer' field to feedback component form submission

---

CHANGELOG.md
lib/govuk_publishing_components/version.rb

- Restore 'referer' field to feedback component form submission (PR #232)
- Create single breadrumb and sidebar contextual navigation components. Not a breaking change, but you can drop govuk_navigation_helpers as a dependency now.
- You can now add require a single Javascript to include all components, just like CSS.
- Update document list component with smaller margin spacing (PR #234)

Version 5.6.0

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_step_by_step_nav.html.erb
app/views/govuk_publishing_components/components/docs/step_by_step_nav.yml
lib/govuk_publishing_components/presenters/step_by_step_nav_helper.rb
spec/components/step_by_step_nav_spec.rb

- modify data structure so substeps themselves have contents, rather than occurring in a sequence of elements and relying on the template to close the substep div
- move substep generation into the helper rather than the template
**WARNING**: this is a breaking change. No live step nav currently uses substeps, but the publishing tool is currently using the old data structure.
Old data structure:
```
{
type: 'substep',
optional: true
},
(elements inside the substep)
```
New:
```
{
type: 'substep',
optional: true,
contents: [
(elements inside the substep)
]
},
```
Trello card: https://trello.com/c/PdxP84XT/410-refactor-task-list-component-code

Improve step nav substep creation

---

app/views/govuk_publishing_components/components/_step_by_step_nav_related.html.erb
app/views/govuk_publishing_components/components/docs/step_by_step_nav.yml
app/views/govuk_publishing_components/components/docs/step_by_step_nav_header.yml
app/views/govuk_publishing_components/components/docs/step_by_step_nav_related.yml
lib/govuk_publishing_components/app_helpers/step_nav.rb
lib/govuk_publishing_components/app_helpers/step_nav_helper.rb
spec/components/step_by_step_nav_related_spec.rb
spec/lib/app_helpers/step_nav_helper_spec.rb

This prefills the `tracking_id` for step nav components introduced in #162 with the <del>slug</del> <ins>content_id</ins> of each step nav.
It also corrects the use of that option in the `step_by_step_nav_related` component to be set per step nav and not per the whole component.
We need this to be able to differentiate between different step navs as soon as a page is shared between two or more step navs.
[Trello card](https://trello.com/c/xzXqnQgf)

Prefill step nav tracking_id

---

app/assets/javascripts/govuk_publishing_components/components/step-by-step-nav.js

Remove unnecessary JS from the step nav component.
- this was a hangover from the original code where the element in question was a link, not a button
- allowed users to open the link in a new tab, but buttons don't allow this
https://trello.com/c/PdxP84XT/350-refactor-task-list-component-code
Please check thoroughly as I am currently somewhat sleep-deprived although my [GCS](https://en.wikipedia.org/wiki/Glasgow_Coma_Scale) is at least 13.

Remove preventLinkFollowingForCurrentTab code

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/_step-by-step-nav-related.scss

Change to make the links in the step nav related links component more consistently styled with the rest of the site.
Before:
After:

Restore underline to step nav related links links

---

app/assets/javascripts/govuk_publishing_components/components/step-by-step-nav.js
app/assets/stylesheets/govuk_publishing_components/components/_step-by-step-nav.scss
lib/govuk_publishing_components/presenters/step_by_step_nav_helper.rb
spec/components/step_by_step_nav_spec.rb
spec/features/step_nav_helper_spec.rb
spec/javascripts/components/step-by-step-nav-spec.js

This refers to links that appear within the content of an expandable section of a step by step nav. Links always appear inside a list.
- existing classes were __links (ul/ol), __link (li), __link-item (a)
- new classes are __list (ul/ol), __list-item (li), __link (a)
Trello card: https://trello.com/c/PdxP84XT/350-refactor-task-list-component-code

Improve list and link classnames

---

CHANGELOG.md
Gemfile.lock
app/assets/stylesheets/govuk_publishing_components/components/_inverse-header.scss
app/views/govuk_publishing_components/components/docs/inverse_header.yml

Trello: https://trello.com/c/0pbli2e8/152-tech-debt-replace-publication-header-component-with-inverse-header-component
In Component Guide: https://govuk-publishing-compon-pr-238.herokuapp.com/component-guide/inverse_header
As the publication header and inverse header components are so similar, it makes sense to consolidate the two into one component.
To do this, we need to make a few spacing changes to the inverse header component so it works within the HTML publication layout.
This change should not break any current uses of the inverse header, e.g: on topic pages
**Before:**
**After:**
This is how it will look on HTML publications:

Tweak spacing for using inverse header on html pub

---

spec/features/contextual_navigation_spec.rb

The contextual navigation tests for step by step nav were failing intermittently. I **_think_** this may be because they were getting a random step by step example from govuk content schemas which didn't always match/contain the data it was expecting to construct a step by step.
This changes the content schemas lookup to always get the same step_by_step_nav example.
**Note: I'm not 100% sure this will fix the issue as it was difficult to test. Welcome to other suggestions.**

Integration test fix

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/_feedback.scss

When the link was visited (i.e. user had visited `/contact/govuk`, the
`:visited` styles would be more specific than the focus styles provided
by govuk_template, meaning the link would stay white and be hard to
read.
Steps to reproduce:
* Visit: https://www.gov.uk/contact/govuk
* Visit https://www.gov.uk/government/publications/vat-information-sheet-0218-impact-on-existing-cost-share-groups-following-changes-to-hmrcs-policy
* Focus "Is there anything wrong with the page"

Fix visited link colour on focus for white feedback links

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/_input.scss
app/assets/stylesheets/govuk_publishing_components/components/_label.scss
app/views/govuk_publishing_components/components/_input.html.erb
app/views/govuk_publishing_components/components/docs/input.yml
app/views/govuk_publishing_components/components/docs/label.yml

Spotted on https://github.com/alphagov/email-alert-frontend/pull/183 where the error message wasn't showing in red as expected.
* Rearrange styling classes so that correct red text and borders apply to field
* Update documentation to clarify why hint text is not inside a label
See: https://govuk-publishing-compon-pr-241.herokuapp.com/component-guide/input

Fix error styles on input component

---

CHANGELOG.md
lib/govuk_publishing_components.rb
lib/govuk_publishing_components/app_helpers/taxon_breadcrumbs.rb
spec/lib/app_helpers/taxon_breadcrumbs_spec.rb

These breadcrumbs are shown on the new finder pages (finder-frontend) and the new topic pages (collections).
cc @steventux @leenagupte 
https://trello.com/c/WJlqy3VD

Add shared helper for taxon breadcrumbs

---

Gemfile.lock
govuk_publishing_components.gemspec
lib/govuk_navigation_helpers.rb
lib/govuk_navigation_helpers/breadcrumbs.rb
lib/govuk_navigation_helpers/configuration.rb
lib/govuk_navigation_helpers/content_item.rb
lib/govuk_navigation_helpers/curated_taxonomy_sidebar_links.rb
lib/govuk_navigation_helpers/grouped_related_links.rb
lib/govuk_navigation_helpers/related_items.rb
lib/govuk_navigation_helpers/rummager_taxonomy_sidebar_links.rb
lib/govuk_navigation_helpers/services.rb
lib/govuk_navigation_helpers/taxon_breadcrumbs.rb
lib/govuk_navigation_helpers/taxonomy_sidebar.rb
spec/govuk_navigation_helpers/breadcrumbs_spec.rb
spec/govuk_navigation_helpers/content_item_spec.rb
spec/govuk_navigation_helpers/related_items_spec.rb
spec/govuk_navigation_helpers/taxon_breadcrumbs_spec.rb
spec/govuk_navigation_helpers/taxonomy_sidebar_spec.rb

This commit merges in the govuk_navigation_helpers gem so that we can drop the dependency.
In subsequent PRs we'll merge in the classes properly and make everything part of the same namespace, but I think this is worthwhile as a first PR.
https://trello.com/c/WJlqy3VD

Merge in govuk_navigation_helpers

---

lib/govuk_navigation_helpers.rb
lib/govuk_publishing_components/presenters/contextual_navigation.rb
spec/govuk_navigation_helpers/breadcrumbs_spec.rb
spec/govuk_navigation_helpers/related_items_spec.rb
spec/govuk_navigation_helpers/taxon_breadcrumbs_spec.rb
spec/govuk_navigation_helpers/taxonomy_sidebar_spec.rb

This removes some indirection by using `TaxonomySidebar`, `TaxonBreadcrumbs`, `Breadcrumbs` directly. It will make future refactoring easier.
Follows the merging in of govuk_navigation_helpers (https://github.com/alphagov/govuk_publishing_components/pull/244).

Use NavigationHelper classes directly

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

Breaking because it moves govuk_navigation_helpers into this app and renames its classes.

Release 6.0.0

---

app/views/govuk_publishing_components/components/docs/contextual_sidebar.yml

This resolves the contextual_sidebar looking broken in the component guide as the data for it didn't cause anything to render.
Before: 
After:

Add links to contextual_sidebar example

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/_inverse-header.scss
app/views/govuk_publishing_components/components/_inverse_header.html.erb
app/views/govuk_publishing_components/components/docs/inverse_header.yml
spec/components/inverse_header_spec.rb

This will be set on topic pages so the breadcrumb renders in a consistent place with the rest of GOV.UK.
**Before:**
**After:**
Component Guide: https://govuk-publishing-compon-pr-260.herokuapp.com/component-guide/inverse-header
Topic Page: https://www.gov.uk/education
Other GOV.UK page with breadcrumbs for comparison: https://www.gov.uk/student-finance

Add padding-top flag to inverse header

---

lib/govuk_publishing_components/presenters/navigation_type.rb
spec/features/contextual_navigation_spec.rb

Travel advice is not tagged to mainstream, but it has related links. This causes the taxonomy sidebar to be rendered.
I think this is a temporary solution and we should probably consider checking for the presence of `ordered_related_links` rather than mainstream browse.
https://govuk.zendesk.com/agent/tickets/2646969

Always use the related links sidebar for travel advice

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/_document-list.scss

Fixes https://github.com/alphagov/government-frontend/issues/744
When the list is against another component with a border it can look like there is a missing list item. Removing the border fixes this issue until we redesign the list styles.
https://govuk-publishing-compon-pr-266.herokuapp.com/component-guide/document_list

Remove bottom border for last item in document lists

---

CHANGELOG.md
app/assets/javascripts/govuk_publishing_components/components/success-alert.js
app/assets/stylesheets/govuk_publishing_components/_all_components.scss
app/assets/stylesheets/govuk_publishing_components/components/_success-alert.scss
app/assets/stylesheets/govuk_publishing_components/components/helpers/_variables.scss
app/views/govuk_publishing_components/components/_success_alert.html.erb
app/views/govuk_publishing_components/components/docs/success_alert.yml

Trello: https://trello.com/c/QJ4DK2YQ/740-add-flashes-to-subscription-management
This adds in a component that can be used to report back to users when a
successful situation has occured - such as them submitting a form and we
informing that this was successful.
@fofr here's a draft of the component. I wasn't too sure if I wanted to specify a data-module attribute or tabindex. I'm assuming I don't need the aria labelled by since it's only a single paragraph.

Component for a success alert

---

CHANGELOG.md
app/views/govuk_publishing_components/components/docs/step_by_step_nav.yml

Add a link in the documentation for the step by step navigation component to the research and testing done during its development.
Trello card: https://trello.com/c/Ax13WPYH/574-add-link-to-evidence-from-step-nav-component-guide

Add link to research

---

CHANGELOG.md
app/assets/javascripts/govuk_publishing_components/components/step-by-step-nav.js
app/views/govuk_publishing_components/components/_step_by_step_nav.html.erb
config/locales/en.yml
spec/javascripts/components/step-by-step-nav-spec.js

Step by step navigation component has JS appended elements 'show' and 'hide' on all steps, plus 'show/hide all' button. Currently all that text is hard coded into the JS, which means it can't be translated in Rails.
- move text from JS to data attributes within the component template
- add translation stuff for the text (although it's still all in English)
- also simplify how the text is stored in JS and remove unnecessary distinction between 'Show all' in FE and 'Show All' in analytics - now both 'Show all'
No visual changes to the component.
Trello card: https://trello.com/c/PdxP84XT/410-refactor-task-list-component-code

Move text for JS appended elements into step nav template

---

lib/govuk_publishing_components/presenters/related_navigation_helper.rb
spec/lib/presenters/related_navigation_helper_spec.rb

Currently we display only 2 browse pages in the sidebar: the parent of the page and the parent's parent (which are mostly browse pages).
I think the original intention of the sidebar was to show all browse pages tagged to the current page. This PR implements that.
Simplifies [the sidebar logic](https://docs.google.com/document/d/1DQRTt0AYuPXSHkYvpcwPEEUDc3MHN2VubgYJA-hzeOM/edit#heading=h.vyiueh7ptm4n) somewhat.
https://govuk-publishing-components.herokuapp.com/contextual-navigation/register-to-vote-armed-forces
https://govuk-publishing-compon-pr-273.herokuapp.com/contextual-navigation/register-to-vote-armed-forces
https://trello.com/c/Lhe0zC9Z

Show all mainstream browse pages in the sidebar

---

app/assets/stylesheets/govuk_publishing_components/components/_related-navigation.scss
app/assets/stylesheets/govuk_publishing_components/components/_step-by-step-nav-related.scss
app/views/govuk_publishing_components/components/_contextual_sidebar.html.erb
app/views/govuk_publishing_components/components/_step_by_step_nav_related.html.erb
app/views/govuk_publishing_components/components/docs/contextual_sidebar.yml
lib/govuk_publishing_components/presenters/contextual_navigation.rb

Currently, when the page is tagged to 2,3 or 4 step by step lists, the sidebar will only show links to those steps by steps and hide the navigation that would otherwise be there.
I think it's a good change to make because this way we don't lose the normal navigation once a page is added to a step by step. It also makes the [logic for the sidebar](https://docs.google.com/document/d/1DQRTt0AYuPXSHkYvpcwPEEUDc3MHN2VubgYJA-hzeOM/edit) simpler. In the future we can integrate the code as well, making the components simpler.
There is 1 page that will be affected: https://www.gov.uk/book-driving-test
https://govuk-publishing-components.herokuapp.com/contextual-navigation/book-driving-test
https://govuk-publishing-compon-pr-275.herokuapp.com/contextual-navigation/book-driving-test …

Show "normal" navigation in addition to step by step, make sidebars consistent

---

app/views/govuk_publishing_components/components/_feedback.html.erb

When you click "No" in the feedback component you're asked to fill in your email address so we can send you a survey. The survey link we currently send (https://www.smartsurvey.co.uk/s/gov-uk) is the default survey that is also present in the blue banner. This makes analysing the data very difficult.
This commit makes the component use a different survey_id, which is created in https://github.com/alphagov/feedback/pull/371. Don't merge this until that PR is deployed.

Use a different survey from the footer

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_search.html.erb
spec/components/search_spec.rb

The use of `html_safe` here caused a XSS vulnerability. It is currently fixed in finder-frontend (https://github.com/alphagov/finder-frontend/pull/480).
It's also possible to insert HTML without doing html_safe by using a capture block, so to avoid recurrence of the bug we'll remove `html_safe` here entirely. This will make sure we don't have to explicitly sanitise the input.

Remove use of `html_safe` in search

---

app/assets/stylesheets/govuk_publishing_components/_all_components.scss
app/assets/stylesheets/govuk_publishing_components/components/_heading.scss
app/views/govuk_publishing_components/components/_heading.html.erb
app/views/govuk_publishing_components/components/docs/heading.yml
spec/components/heading_test_spec.rb

Add the heading component from government-frontend to the components gem.
- no changes to component, other than changing class from 'app' to 'gem'
A separate PR will be created to remove it from government-frontend.
Trello cards:
- https://trello.com/c/VseooNjM/18-move-the-heading-component-to-the-gem
- https://trello.com/c/iehFbdw0/54-modify-component-heading

Add heading component

---

app/assets/stylesheets/component_guide/all_components.scss
app/assets/stylesheets/component_guide/all_components_print.scss
app/views/layouts/govuk_publishing_components/application.html.erb
config/initializers/assets.rb

- applications include the styles for the components as part of the application's css, but static does not
- this means gem components viewed in the static component guide are not styled, which can cause accessibility errors to trigger
- adds logic and a couple of stylesheets to pull in the component styles if static is the application
This is a temporary (and slightly ugly) measure while all the components are migrated from static into the gem. If there's a cleaner way of doing it please let me know.

Make components CSS available to static in the component guide

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/_all_components.scss
app/assets/stylesheets/govuk_publishing_components/components/_translation-nav.scss
app/views/govuk_publishing_components/components/_translation-nav.html.erb
app/views/govuk_publishing_components/components/docs/translation-nav.yml
config/locales/en.yml
spec/components/translation_nav_test_spec.rb

Moving from government-frontend to the gem. A separate PR will be raised to remove it from government-frontend. No changes to the component other than changing the CSS namespace from app-c to gem-c.
Trello cards:
- https://trello.com/c/ehg2nkE9/53-modify-component-translation-nav
- https://trello.com/c/0zt60phw/20-move-the-translation-nav-component-to-the-gem

Add translation nav component

---

lib/govuk_publishing_components/app_helpers/taxon_breadcrumbs.rb

When looking at a taxon, it's useful to see the breadcrumbs regardless
of the phase it's in as without the breadcrumbs it's hard to navigate
up the taxonomy.
Therefore, apply the restriction regarding the phase only if the
content item isn't a taxon.

Show breadcrumbs on non live taxons

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/_all_components.scss
app/assets/stylesheets/govuk_publishing_components/components/helpers/_organisation-colours.scss
app/views/govuk_publishing_components/components/_document_list.html.erb
app/views/govuk_publishing_components/components/docs/document_list.yml
docs/component_branding.md
lib/govuk_publishing_components.rb
lib/govuk_publishing_components/presenters/brand_helper.rb

This PR follows the discussion over [this RFC](https://github.com/alphagov/govuk_publishing_components/pull/287) to add department colour branding to components. 
The main point of discussion in the RFC centred around using colour specific classes instead of department ones, to avoid duplication and make the classnames more meaningful. I have decided not to implement this for the following reasons:
- coming up with classnames based on colours is hard i.e. `colour--light-red`, `colour--lighter-red` doesn't scale well if new colours are needed later, and neither does `colour--red-1`, `colour--red-2` etc.
- changing the backend so all the organisations could have this different approach to branding would have involved a lot of work that we don't have time for this mission
I've written the …

Add department colours to components

---

CHANGELOG.md
app/assets/javascripts/govuk_publishing_components/lib/toggle.js
app/assets/stylesheets/govuk_publishing_components/components/_subscription-links.scss
app/views/govuk_publishing_components/components/_subscription-links.html.erb
app/views/govuk_publishing_components/components/docs/subscription-links.yml
config/locales/en.yml
spec/components/subscription_links_spec.rb
spec/javascripts/components/toggle-spec.js

The subscription links component is going to be used on the new organisation pages, but needs a few extra features adding.
- add option to change link text
- add option to turn feed link into a toggle to display an input box containing a link
- includes toggle.js from static, included without changes (apart from the namespace) as a module outside of the component (so it can be used by other components if required)
Component guide link: https://govuk-publishing-compon-pr-294.herokuapp.com/component-guide/subscription-links
Trello card: https://trello.com/c/NjgS3vym/55-modify-component-subscription-links

Modify subscription links component

---

CHANGELOG.md
app.json
app/views/govuk_publishing_components/components/docs/meta_tags.yml
lib/govuk_publishing_components/presenters/meta_tags.rb
spec/components/meta_tags_spec.rb

This is built from the base_path of the content item which means it strips out any query parameters or fragments.
[Trello Card](https://trello.com/c/J67JSy8r/148-investigate-how-to-implement-canonical-tags-for-government-frontend-to-help-remove-duplicate-urls-2-hour-timebox)

Add a canonical URL meta tag

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_document_list.html.erb
docs/component_branding.md
lib/govuk_publishing_components.rb
lib/govuk_publishing_components/app_helpers/brand_helper.rb
lib/govuk_publishing_components/presenters/brand_helper.rb
spec/components/document_list_spec.rb
spec/lib/app_helpers/brand_helper_spec.rb

Improve the colour branding model following @tijmenb 's comments on the [PR to add it](https://github.com/alphagov/govuk_publishing_components/pull/296).
Note that there are a few components that have started using this model already, I'll need to rebase and update these PRs once this change is approved.
- https://github.com/alphagov/govuk_publishing_components/pull/298
- https://github.com/alphagov/govuk_publishing_components/pull/299
- https://github.com/alphagov/collections/pull/651

Iterate branding model

---

CHANGELOG.md
app/views/govuk_publishing_components/components/docs/input.yml

This is to fix the failing build currently happening with https://github.com/alphagov/collections/pull/651 which is being caused by version 7.2.0 of the components gem. That PR will need a new version of this gem once this PR has been merged in order to pass the build tests.
- test was rendering a page where it couldn't find the ID being used in the example for the aria-describedby attribute, so Axe was throwing an accessibility error
- can't add an arbitrary ID into the page, so now using the id of the main wrapper, which prevents the error occurring
- documentation updated to explain this

Fix automated a11y test error with input

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Fix automated a11y test error with input (PR #303)
* Add an optional `canonical` meta tag (PR #302)
* Iterate branding model (PR #300)
PR 300 is a fairly major change but its not in use on production yet.

Version 7.3.0

---

app/assets/stylesheets/govuk_publishing_components/components/_radio.scss

This component doesn't work in some situations (https://github.com/alphagov/frontend/pull/1509#discussion_r187015238). The clickable area of the radio button is about half the size that it should be.
According to @andysellick in https://github.com/alphagov/frontend/pull/1509#discussion_r187015238:
> Seems to be that the component is inadvertently relying upon some core styles for inputs, which includes font-size: inherit. As a test, if you replace these two lines with that, the input comes out at the right size. Suggest we make an adjustment to the component to define an
explicit font size so this works in isolation - might be able to move the font size declaration for the label higher up so it applies to the whole component.

Fix spacing issue in radio buttons

---

CHANGELOG.md
app.json
app/views/govuk_publishing_components/components/docs/meta_tags.yml
lib/govuk_publishing_components/presenters/meta_tags.rb
spec/components/meta_tags_spec.rb

This reverts commit b53fa52329520c848ac0f9577f9f1fc500d9d7ed, reversing changes made to 8f9ed427d7fd6ae2fab198825b1055b77291fd7a.
After adding this we realised that it would be better placed for the individual frontend applications to add the canonical tag as they work closer to the content and would understand how to generate different canonical URLs depending on document type and various other factors.
Although we could choose to leave it in here, we felt it would be better for apps to be explicit about the tag rather than having a default which might cause more harm than good.
[Trello Card](https://trello.com/c/J67JSy8r/148-investigate-how-to-implement-canonical-tags-for-government-frontend-to-help-remove-duplicate-urls-2-hour-timebox)

Revert canonical URL meta tag

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_button.html.erb
app/views/govuk_publishing_components/components/_taxonomy_navigation.html.erb
app/views/govuk_publishing_components/components/related_navigation/_section.html.erb
lib/govuk_publishing_components/presenters/step_by_step_nav_helper.rb
spec/components/all_components_spec.rb

This is a follow up to an [incident last month][repo] where we found a XSS vulnerability caused by `html_safe` being called on untrusted user input (see https://github.com/alphagov/finder-frontend/pull/480 and follow ups). 
To avoid recurrence, this PR makes sure that 1) we're never calling `html_safe` so that everything is escaped by default, 2) we can't use it anymore. This makes escaping and calling `html_safe` the exclusive responsibility of the application. 
See the individual commits for details. 
[repo]: https://docs.google.com/document/d/1HDpDuEtmR0PVt2Te5OgMGb6MnLlPU1s6Rhlt9Qhva1Y/edit#heading=h.v4arcxojubbv

Avoid usage of html_safe

---

app/assets/stylesheets/govuk_publishing_components/_all_components.scss
app/assets/stylesheets/govuk_publishing_components/components/_breadcrumbs.scss
app/assets/stylesheets/govuk_publishing_components/components/mixins/_back-arrow.scss
app/assets/stylesheets/govuk_publishing_components/components/mixins/_touch-friendly-links.scss
app/views/govuk_publishing_components/components/_breadcrumbs.html.erb
app/views/govuk_publishing_components/components/docs/breadcrumbs.yml
app/views/govuk_publishing_components/components/docs/inverse_header.yml
spec/components/breadcrumbs_spec.rb

This moves over [the breadcrumbs component from static](https://govuk-static.herokuapp.com/component-guide/breadcrumbs).
[Trello Card](https://trello.com/c/t11eJLxC/138-implement-breadcrumb-schema-3)
https://trello.com/c/XLuzv0pB/25-move-the-breadcrumbs-component-to-the-gem

Add breadcrumbs component from static

---

CHANGELOG.md
app/assets/javascripts/govuk_publishing_components/lib/track-share-button-clicks.js
app/assets/stylesheets/govuk_publishing_components/_all_components.scss
app/assets/stylesheets/govuk_publishing_components/components/_share-links.scss
app/views/govuk_publishing_components/components/_share_links.html.erb
app/views/govuk_publishing_components/components/docs/share_links.yml
spec/components/share_links_spec.rb
spec/javascripts/components/track-share-button-clicks-spec.js

Adds the share links component from government-frontend. A separate PR will be raised to remove it from that app.
Only change in this component is the namespace, in CSS from `app-c` to `gem-c` and in JS to `GemTrackShareButtonClicks`.
Component guide link: https://govuk-publishing-compon-pr-308.herokuapp.com/component-guide/share_links
Trello card: https://trello.com/c/NZwDW9xV/89-modify-component-share-links

Add share links component

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_translation-nav.html.erb
app/views/govuk_publishing_components/components/docs/translation-nav.yml
lib/govuk_publishing_components.rb
lib/govuk_publishing_components/presenters/translation_nav_helper.rb
spec/components/translation_nav_test_spec.rb

Adds the following options to the translation nav component:
- branding (to change the colour of the links given a parameter matching a department name, ahead of using this component on organisation pages)
- tracking (to add any passed GA tracking attributes to each link, if passed to the component)
Preview: https://govuk-publishing-compon-pr-298.herokuapp.com/component-guide/translation-nav
Trello card: https://trello.com/c/ehg2nkE9/53-modify-component-translation-nav

Translation nav add brand and tracking

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_breadcrumbs.html.erb
lib/govuk_publishing_components.rb
lib/govuk_publishing_components/presenters/breadcrumbs.rb
spec/components/breadcrumbs_spec.rb

This implements schema data as JSON/LD.
[Trello Card](https://trello.com/c/t11eJLxC/138-implement-breadcrumb-schema-3)

Schema data breadcrumbs

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

Includes the following. Changes to the heading component are breaking (about to create a PR on government-frontend to account for that)
- Use new breadcrumbs component in contextual breadcrumbs (PR #313)
- Add share links component (PR #308)
- The Button component no longer accepts unescaped HTML in the info_text, you'll have to call html_safe on it yourself. Probably the only affected application is frontend (#305)
- Remove optional canonical meta tag (applications can add this tag explicitly if they need it)
- Translation nav add brand and tracking (PR #298)
- Subscription links add colour and tracking (PR #299)
- Iterate heading component (PR #307)

Version 8.0.0

---

lib/govuk_publishing_components/presenters/subscription_links_helper.rb
spec/components/subscription_links_spec.rb

- only show data attributes for controls and expanded if this element is going to actually do that
- was causing an integration test in government-frontend to fail as with the attributes it wasn't rendering visibly

Fix a bug in subscription links attributes

---

app/views/govuk_publishing_components/components/_machine_readable_metadata.html.erb
app/views/govuk_publishing_components/components/docs/machine_readable_metadata.yml
lib/govuk_publishing_components.rb
lib/govuk_publishing_components/presenters/schema_org.rb
spec/components/machine_readable_metadata_spec.rb
spec/lib/presenters/schema_org_spec.rb

This component generates JSON-LD scripts with schema.org schemas.
The name is broad because I expect that we'll expand on this in the future to also include opengraph meta tags (currently only present in government-frontend).
- https://github.com/alphagov/government-frontend/pull/905
- https://github.com/alphagov/frontend/pull/1514
- https://github.com/alphagov/calendars/pull/294
- [Machine readable component](https://govuk-publishing-compon-pr-318.herokuapp.com/component-guide/machine_readable_metadata)
https://trello.com/c/RLQI1IUV

Add Machine readable metadata component

---

app/assets/stylesheets/component_guide/application.scss
app/models/govuk_publishing_components/component_doc.rb
app/models/govuk_publishing_components/component_doc_resolver.rb
app/views/govuk_publishing_components/component_guide/component_doc/_component.html.erb
app/views/govuk_publishing_components/component_guide/component_doc/_component_output.html.erb
app/views/govuk_publishing_components/component_guide/component_doc/_preview.html.erb
app/views/govuk_publishing_components/components/docs/breadcrumbs.yml
app/views/govuk_publishing_components/components/docs/meta_tags.yml

In some cases it's useful to be able to see the resulting HTML of the component. This adds an option to do this and enables it for the meta tags component.
https://govuk-publishing-compon-pr-320.herokuapp.com/component-guide/machine_readable_metadata
https://govuk-publishing-compon-pr-320.herokuapp.com/component-guide/breadcrumbs
https://govuk-publishing-compon-pr-320.herokuapp.com/component-guide/meta_tags

Add option to display the generated HTML for components

---

app/assets/stylesheets/component_guide/application.scss

Follows PR #320, removes excess padding from HTML examples.
Example link: https://govuk-publishing-compon-pr-323.herokuapp.com/component-guide/machine_readable_metadata

Remove padding from HTML code examples

---

CHANGELOG.md

This was missed in https://github.com/alphagov/govuk_publishing_components/pull/324.

Update CHANGELOG for new title component

---

app/controllers/govuk_publishing_components/component_guide_controller.rb
app/models/govuk_publishing_components/component_doc.rb
app/models/govuk_publishing_components/component_doc_resolver.rb
app/models/govuk_publishing_components/component_docs.rb
app/models/govuk_publishing_components/component_example.rb

This refactors the component guide code by minimising the arguments to the constructors, renaming to reveal more meaning and removing some indirection. Read the commits for all the details.

Refactor component guide code

---

app/assets/stylesheets/govuk_publishing_components/components/_lead-paragraph.scss
app/assets/stylesheets/govuk_publishing_components/components/_translation-nav.scss

These components use the `margins` mixin but don't import it explicitly.

Add missing imports for margins

---

docs/component_branding.md

I updated the branding model but evidently didn't proof read my own documentation fully. This should now be correct.
For reviewing, check the [brand helper file](https://github.com/alphagov/govuk_publishing_components/blob/master/lib/govuk_publishing_components/app_helpers/brand_helper.rb) to be sure.

Fix the branding documentation

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_machine_readable_metadata.html.erb
lib/govuk_publishing_components/presenters/machine_readable/article_schema.rb
lib/govuk_publishing_components/presenters/machine_readable/news_article_schema.rb
lib/govuk_publishing_components/presenters/machine_readable/page.rb
lib/govuk_publishing_components/presenters/schema_org.rb
spec/lib/presenters/schema_org_spec.rb

This merges things that currently only live in government-frontend (alphagov/government-frontend#878, alphagov/government-frontend#898) so we can re-use it on other content pages.
To implement this some refactoring was necessary, see the first 4 commits.
https://trello.com/c/Mx5D1JB3/31-add-more-twitter-facebook-things-to-pages

Update Machine readable metadata component to include Facebook, Twitter, SEO things

---

app/views/govuk_publishing_components/components/docs/machine_readable_metadata.yml
lib/govuk_publishing_components/presenters/machine_readable/page.rb

This will allow apps to set the `description` directly, instead of relying on the content item.
Will be used by https://github.com/alphagov/manuals-frontend/pull/392.
https://trello.com/c/gKHoUGuA

Allow description to be overridden

---

lib/govuk_publishing_components/presenters/machine_readable/article_schema.rb

In certain cases this can be an empty string, in which case we'll omit the field entirely.
https://trello.com/c/gKHoUGuA

Only add `articleBody` field when present

---

app/views/govuk_publishing_components/components/docs/machine_readable_metadata.yml
lib/govuk_publishing_components/presenters/machine_readable/person_schema.rb
lib/govuk_publishing_components/presenters/schema_org.rb
spec/components/machine_readable_metadata_spec.rb
spec/lib/presenters/schema_org_spec.rb

This implements http://schema.org/Person. It's to be used on pages like https://www.gov.uk/government/people/theresa-may.
https://trello.com/c/gKHoUGuA

Add Person schema for use on people pages

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/_all_components.scss
app/assets/stylesheets/govuk_publishing_components/_all_components_print.scss
app/assets/stylesheets/govuk_publishing_components/components/_contents-list.scss
app/assets/stylesheets/govuk_publishing_components/components/helpers/_contents-list-helper.scss
app/assets/stylesheets/govuk_publishing_components/components/print/_contents-list.scss
app/views/govuk_publishing_components/components/_contents_list.html.erb
app/views/govuk_publishing_components/components/docs/contents_list.yml
config/locales/en.yml
lib/govuk_publishing_components.rb
lib/govuk_publishing_components/presenters/contents_list_helper.rb
spec/components/contents_list_spec.rb
spec/lib/components/contents_list_helper_spec.rb

We need to use contents lists in the new organisation pages, which are held in collections. A [separate PR has been opened](https://github.com/alphagov/government-frontend/pull/915) to update government-frontend to use this component.
- from government-frontend
- only change is to CSS namespace from app-c to gem-c
Trello card: https://trello.com/c/aDQ8nEKO/90-modify-component-contents-list

Add contents list component

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/_all_components.scss
app/assets/stylesheets/govuk_publishing_components/components/_image-card.scss
app/views/govuk_publishing_components/components/_image_card.html.erb
app/views/govuk_publishing_components/components/docs/image_card.yml
lib/govuk_publishing_components.rb
lib/govuk_publishing_components/presenters/image_card_helper.rb
spec/components/image_card_spec.rb

Adds a new component, image card, intended for use for news articles and people entries on organisation pages. See the [component guide](https://govuk-publishing-compon-pr-322.herokuapp.com/component-guide/image_card) for a full explanation.
Examples in context:
Mobile:
Tested in IE8+, latest Chrome, Firefox, iphone 6, iphone 5, Google Nexus.
Component guide: https://govuk-publishing-compon-pr-322.herokuapp.com/component-guide/image_card
Trello card: https://trello.com/c/v8vHh54c/102-new-component-image-link

Add image card component

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/_all_components.scss
app/assets/stylesheets/govuk_publishing_components/components/_notice.scss
app/views/govuk_publishing_components/components/_notice.html.erb
app/views/govuk_publishing_components/components/docs/notice.yml
spec/components/notice_spec.rb
spec/dummy/app/views/govuk_component/govspeak.raw.html.erb

- from government-frontend
- changed CSS namespace from app-c to gem-c
- test file fairly heavily rewritten
- govspeak template included in dummy app to allow tests to work
- otherwise should be the same as the original component
PR to remove this component from government-frontend is here: https://github.com/alphagov/government-frontend/pull/916
Trello card: https://trello.com/c/vdIdfjHn/121-modify-component-notice

Add notice component

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_contents_list.html.erb
app/views/govuk_publishing_components/components/docs/contents_list.yml
spec/components/contents_list_spec.rb

Expand the contents list component to be used on organisation pages, specifically:
- add option for organisation branding
- add option to hide title
Component guide: https://govuk-publishing-compon-pr-351.herokuapp.com/component-guide/contents_list
Trello card: https://trello.com/c/aDQ8nEKO/90-modify-component-contents-list

Iterate contents list component

---

app/views/govuk_publishing_components/components/docs/notice.yml
spec/components/notice_spec.rb

Will need to be able to add links into notice titles, for organisation pages.
- already possible, added example and guidance to documentation
- added test
---
https://govuk-publishing-compon-pr-352.herokuapp.com/component-guide/
Trello card: https://trello.com/c/vdIdfjHn/121-modify-component-notice

Notice title containing markup option

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/_document-list.scss
app/views/govuk_publishing_components/components/_document_list.html.erb
app/views/govuk_publishing_components/components/docs/document_list.yml
spec/components/document_list_spec.rb

Extends the document list component with the following changes: 
* If only passing link text and path to the component, render that as a link rather than a heading.
* Add option to pass title 'context'
**Context example:**
https://govuk-publishing-compon-pr-355.herokuapp.com/component-guide/document_list

Update document list component

---

CHANGELOG.md
app/views/govuk_publishing_components/components/docs/taxonomy_navigation.yml
config/locales/en.yml
lib/govuk_publishing_components/presenters/taxonomy_navigation.rb
spec/lib/presenters/taxonomy_navigation_spec.rb

Trello card:
https://trello.com/c/3xOhZgEJ/127-removing-policy-links-from-the-taxonomy-sidebar
As policies are planning on being retired we need to remove policy links
from the taxonomy sidebar as there shouldn't be lots of different pages
showing the same content. This is because the same content is tagged to the Brexit
taxon and Brexit policy.
---
https://govuk-publishing-compon-pr-357.herokuapp.com/component-guide/

Remove policies from taxonomy sidebar

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/_document-list.scss
app/views/govuk_publishing_components/components/_document_list.html.erb
spec/components/document_list_spec.rb

The spacing on the document list component was originally set on the context element itself.
This meant that on smaller screens, the context text appeared to be indented from the left when it wrapped onto a new line. By moving the margin to the link title, the context text will appear in line with the link title (on the left) if it wraps.
This also refactors the logic for displaying the link title as a heading or not, so we don't repeat the link HTML twice.
**Before:**
**After:**
---
https://govuk-publishing-compon-pr-363.herokuapp.com/component-guide/document_list
https://govuk-publishing-compon-pr-363.herokuapp.com/component-guide/document_list/with_context

Tweak context spacing on document list component

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/_all_components.scss
app/assets/stylesheets/govuk_publishing_components/components/_organisation-logo.scss
app/views/govuk_publishing_components/components/_organisation_logo.html.erb
app/views/govuk_publishing_components/components/docs/organisation_logo.yml
lib/govuk_publishing_components.rb
lib/govuk_publishing_components/presenters/organisation_logo_helper.rb
spec/components/organisation_logo_spec.rb

- now uses gem-c css namespace
- modified to use a helper method
- gem branding model replaces existing branding mechanism
- test for no link added now included, test names rewritten
- example for without link added to documentation
- crest images still live in whitehall
- css restructured but essentially the same
---
https://govuk-publishing-compon-pr-365.herokuapp.com/component-guide/

Add organisation logo component from static

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Add organisation logo component from static (PR #365)
* Tweaks document list spacing for context text on smaller screens (PR #363)
* Makes heading component use h2 by default (PR #362)
---
https://govuk-publishing-compon-pr-366.herokuapp.com/component-guide/

Version 9.2.0

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/_translation-nav.scss
app/views/govuk_publishing_components/components/_translation-nav.html.erb
app/views/govuk_publishing_components/components/docs/translation-nav.yml
lib/govuk_publishing_components/presenters/translation_nav_helper.rb
spec/components/translation_nav_spec.rb

By default the component has a large margin top, this option allows it to be turned off, something we need for positioning the translation nav on the new org pages.
Trello card: https://trello.com/c/pa4kkZwL/166-modify-component-translation-nav
---
https://govuk-publishing-compon-pr-368.herokuapp.com/component-guide/

Add no margin top option to translation nav

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

Very small update - adding an option to translation nav for no top margin.
---
https://govuk-publishing-compon-pr-369.herokuapp.com/component-guide/

Version 9.2.1

---

app/views/govuk_publishing_components/components/docs/document_list.yml

The document list component was going to be used on the new /government/organisations pages in Collections. However, we've decided that using this component will introduce more limitations.
We therefore need to update this documentation in case it misleads people in the future.
https://govuk-publishing-compon-pr-370.herokuapp.com/component-guide/document_list

Update document list documentation

---

app/assets/stylesheets/govuk_publishing_components/components/helpers/_brand-colours.scss

- prime ministers office brand colours are not included in the list of organisations pulled from frontend toolkit, added manually
- also add hover effect
---
https://govuk-publishing-compon-pr-372.herokuapp.com/component-guide/

Add no10 to the branding model

---

app/assets/stylesheets/govuk_publishing_components/_all_components_print.scss
app/assets/stylesheets/govuk_publishing_components/components/_share-links.scss
app/assets/stylesheets/govuk_publishing_components/components/print/_share-links.scss
app/views/govuk_publishing_components/components/_share_links.html.erb
app/views/govuk_publishing_components/components/docs/share_links.yml
spec/components/share_links_spec.rb

Fix some small issues with the component ahead of using it in the new organisation pages. Specifically:
- added rel="external" to the links for tracking purposes
- removed the `dont-print` style and added specific print styles for this component
- removed the visually hidden 'share on' text as it no longer works in the context of providing custom text to the component, and where it's currently in use the links have a heading above them saying 'share on'
- stop long link names from wrapping beneath the icons
Trello card: https://trello.com/c/wPvE62vw/185-modify-share-links-component
---
https://govuk-publishing-compon-pr-276.herokuapp.com/component-guide/

Modify share links component

---

app/assets/stylesheets/govuk_publishing_components/components/_image-card.scss

Replace with underline on hover.
Trello card: https://trello.com/c/cCRI0WQg/184-modify-image-card-component
---
https://govuk-publishing-compon-pr-375.herokuapp.com/component-guide/

Remove underline on image card title link

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/_image-card.scss
app/views/govuk_publishing_components/components/_image_card.html.erb
app/views/govuk_publishing_components/components/docs/image_card.yml
lib/govuk_publishing_components/presenters/image_card_helper.rb
spec/components/image_card_spec.rb

For use on links to people pages, e.g: https://www.gov.uk/government/organisations/department-for-international-trade (Baroness Fairhead CBE)
https://govuk-publishing-compon-pr-377.herokuapp.com/component-guide/image_card

Add metadata to image card component

---

app/assets/javascripts/component_guide/visual-regression.js
app/assets/stylesheets/component_guide/all_components.scss
app/assets/stylesheets/component_guide/all_components_print.scss
app/assets/stylesheets/govuk_publishing_components/components/govspeak/_attachment.scss
app/assets/stylesheets/govuk_publishing_components/components/govspeak/_call-to-action.scss
app/assets/stylesheets/govuk_publishing_components/components/govspeak/_charts.scss
app/assets/stylesheets/govuk_publishing_components/components/govspeak/_contact.scss
app/assets/stylesheets/govuk_publishing_components/components/govspeak/_example.scss
app/assets/stylesheets/govuk_publishing_components/components/govspeak/_footnotes.scss
app/assets/stylesheets/govuk_publishing_components/components/govspeak/_fraction.scss
app/assets/stylesheets/govuk_publishing_components/components/govspeak/_information-callout.scss
app/assets/stylesheets/govuk_publishing_components/components/govspeak/_legislative-list.scss
app/assets/stylesheets/govuk_publishing_components/components/govspeak/_media-player.scss
app/assets/stylesheets/govuk_publishing_components/components/govspeak/_stat-headline.scss
app/assets/stylesheets/govuk_publishing_components/components/govspeak/_tables.scss
app/assets/stylesheets/govuk_publishing_components/components/govspeak/_typography.scss
app/assets/stylesheets/govuk_publishing_components/components/govspeak/_warning-callout.scss
app/views/govuk_publishing_components/components/docs/button.yml
app/views/govuk_publishing_components/components/docs/contextual_breadcrumbs.yml
app/views/govuk_publishing_components/components/docs/contextual_sidebar.yml
app/views/govuk_publishing_components/components/docs/fieldset.yml
app/views/layouts/govuk_publishing_components/application.html.erb
docs/use-components.md
lib/generators/govuk_publishing_components/component_generator.rb
lib/govuk_publishing_components/config.rb
spec/dummy/app/views/govuk_component/docs/test-static-component.yml
spec/dummy/app/views/govuk_component/test-static-component.raw.html.erb
spec/javascripts/govuk_publishing_components/VisualRegressionSpec.js
spec/lib/config_spec.rb

We've moved all the components to the gem, so we can start removing some of the special cases that were needed to render static's components in the component guide in static. See commits for the details.
https://trello.com/c/pU7YINt1/45-move-all-components-from-static-into-the-gem

Remove special casing for Static

---

config/locales/cy.yml

This is used in (surprise surprise) the [translation-nav component](https://github.com/alphagov/govuk_publishing_components/blob/6dd1858c0dcd0dd48ba930b719db335d5c8186e4/app/views/govuk_publishing_components/components/_translation-nav.html.erb#L9)

Add translations translation for translations to .cy

---

app/views/govuk_publishing_components/components/_image_card.html.erb
app/views/govuk_publishing_components/components/docs/image_card.yml
lib/govuk_publishing_components/presenters/image_card_helper.rb
spec/components/image_card_spec.rb

- as long as extra links are supplied
- required for organisation pages
We need to be able to do this:
---
https://govuk-publishing-compon-pr-382.herokuapp.com/component-guide/image_card

Allow image card component to not have main link

---

app/views/govuk_publishing_components/components/_feedback.html.erb

The heading structure of the feedback component began with a H3 and then included two H2s, so it looked like this:
This PR makes it looks like this: 
It's not ideal that the H2s have duplicate text, but this issue is outside of the scope of this PR.
---
https://govuk-publishing-compon-pr-385.herokuapp.com/component-guide/feedback

Fix heading structure in feedback component

---

app/assets/stylesheets/govuk_publishing_components/components/helpers/_brand-colours.scss

- branding in the toolkit uses red for both the border and link colour and then whitehall ignores the border colour to use black instead
- in our model this meant the red was being used for the border colour, so this addition sets the border colour correctly to black
Fixes this problem:
Trello card: https://trello.com/c/lxiL4E81/211-promotional-orgs-and-their-branding
---
https://govuk-publishing-compon-pr-387.herokuapp.com/component-guide/

Add explicit Civil Service branding

---

app/assets/stylesheets/govuk_publishing_components/components/helpers/_brand-colours.scss

- was not defined, so fell back to blue, which looked a bit odd when you focus on a link that was previously a completely different colour
Fixes this:
---
https://govuk-publishing-compon-pr-389.herokuapp.com/component-guide/

Fix focus states in branding model

---

CHANGELOG.md
lib/govuk_publishing_components/presenters/image_card_helper.rb

Trello: https://trello.com/c/HxtPYK4o/91-urls-are-not-rendered-as-links-in-news-items
Changes image card description from using a p tag to a div tag, so it can support html.
---
https://govuk-publishing-compon-pr-392.herokuapp.com/component-guide/

Support html description

---

app/views/govuk_publishing_components/components/docs/image_card.yml
lib/govuk_publishing_components/presenters/image_card_helper.rb
spec/components/image_card_spec.rb

This change allows the heading tag to be removed from an image card, by passing the `heading_level` parameter as `0`. Note that this does not change the appearance of the component in any way.
---
https://govuk-publishing-compon-pr-394.herokuapp.com/component-guide/

Make heading tag optional on image card

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Make heading tag optional on image card (PR #394)
---
https://govuk-publishing-compon-pr-395.herokuapp.com/component-guide/

Version 9.3.6

---

spec/features/contextual_navigation_spec.rb

These tests sometimes fail because the random generator adds a parent to the current page, which means that the breadcrumb has additional elements. This improves the tests by being more specific about what we expect.

Fix intermittently failing tests

---

.gitignore
CHANGELOG.md
Jenkinsfile
README.md
govuk_publishing_components.gemspec
package-lock.json
package.json
startup.sh

This commit adds GOV.UK Frontend (https://design-system.service.gov.uk/) to the gem.
When we run `npm install` npm will install the library into `node_modules`. This is ignored in git to avoid us having to commit the entire 15.000 lines of code in govuk_frontend. To include it in the distributed version of the gem, the node_modules directory is added to `s.files` in the gemspec. To make the files available during build, we run `npm install` before the tests (see Jenkinsfile).
PRs that actually make use of GOV.UK Frontend will come separately (see https://github.com/alphagov/govuk_publishing_components/pull/371 for how we intend to use it).
https://trello.com/c/R7Ija8dR/16-create-layout-system-for-admin-applications

Add GOV.UK Frontend

---

app/models/govuk_publishing_components/component_doc.rb
app/views/govuk_publishing_components/component_guide/component_doc/_preview.html.erb
app/views/govuk_publishing_components/components/docs/metadata.yml

We'll use this to create a layout component. We can't preview that on the component guide page because it will crash slimmer, which doesn't allow elements like `<head>` to appear in the body.
https://trello.com/c/R7Ija8dR

Make displaying the preview optional

---

CHANGELOG.md
app.json
app/assets/stylesheets/govuk_publishing_components/admin_styles.scss
app/assets/stylesheets/govuk_publishing_components/components/_layout-for-admin.scss
app/views/govuk_publishing_components/components/_layout_for_admin.html.erb
app/views/govuk_publishing_components/components/docs/layout_for_admin.yml
config/initializers/assets.rb
spec/components/layout_for_admin_spec.rb
spec/dummy/app/controllers/welcome_controller.rb
spec/dummy/app/views/layouts/dummy_admin_layout.html.erb
spec/dummy/app/views/welcome/admin_example.html.erb
spec/dummy/config/routes.rb

This component outputs just the basic HTML for a page. It has `<head>` and `<body>` tags, title tag and includes its own CSS. So preview the whole thing, there's also a special page on /admin in the component guide.
In future PRs we'll add a header, footer and the rest of the page furniture.
https://trello.com/c/R7Ija8dR

Add component for the basic page HTML

---

CHANGELOG.md
app/models/govuk_publishing_components/component_doc.rb
app/views/govuk_publishing_components/component_guide/show.html.erb

If a component uses a component from the design system, it can now specify so in the YAML file using the `govuk_frontend_components` key.
This will show links on the component page.
https://trello.com/c/R7Ija8dR

Allow components to link to the Design System

---

app/assets/stylesheets/component_guide/application.scss
app/assets/stylesheets/govuk_publishing_components/admin_styles.scss
app/assets/stylesheets/govuk_publishing_components/components/_layout-footer.scss
app/models/govuk_publishing_components/component_doc.rb
app/views/govuk_publishing_components/component_guide/show.html.erb
app/views/govuk_publishing_components/components/_layout_footer.html.erb
app/views/govuk_publishing_components/components/docs/layout_footer.yml
app/views/govuk_publishing_components/components/docs/layout_for_admin.yml
app/views/layouts/govuk_publishing_components/application.html.erb
spec/components/layout_footer_spec.rb

This implements the footer component from GOV.UK Frontend.
Things of note:
- Even though we don't have custom CSS, we still create a CSS file for this component. This is mainly so it's easy to discover for a developer where the styles come from.
- When the component is `part_of_admin_layout`, we'll show a warning banner. This hopefully makes it clear that the component can't be used on the public frontend (because GOV.UK Frontend isn't available).
[View in component guide](https://govuk-publishing-compon-pr-404.herokuapp.com/component-guide/layout_footer)
https://trello.com/c/k5agy6jw

Add footer component

---

CHANGELOG.md
lib/govuk_publishing_components/presenters/meta_tags.rb
spec/components/meta_tags_spec.rb

Trello: https://trello.com/c/cbRSHmA9/30-add-organisation-id-to-custom-dimensions-in-google-analytics
Adds the govuk:analytics:organisations meta tag if the current page is an org (has an analytics_identifier value in the content item)
https://govuk-publishing-compon-pr-397.herokuapp.com/component-guide

Add organisation meta tag if current page is org

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/_all_components.scss
app/assets/stylesheets/govuk_publishing_components/components/_highlight-boxes.scss
app/views/govuk_publishing_components/components/_highlight_boxes.html.erb
app/views/govuk_publishing_components/components/docs/highlight_boxes.yml
lib/govuk_publishing_components.rb
lib/govuk_publishing_components/presenters/highlight_boxes_helper.rb
spec/components/highlight_boxes_spec.rb

Moves the highlight boxes component from Collections so it can be used by Government Frontend.
https://govuk-publishing-compon-pr-403.herokuapp.com/component-guide/

Add highlight boxes from Collections

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Add experimental Admin layout (PR #371)
* Add the [GOV.UK Frontend](https://design-system.service.gov.uk/) library to the gem (PR #398)
* Allow linking to the Design System on component pages (PR #401)
* Add govuk:analytics:organisations meta tag if the current page is an organisation (PR #397)
* Move the highlight box component from Collections to the gem (PR #403)

Release version 9.4.0

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_notice.html.erb
app/views/govuk_publishing_components/components/docs/notice.yml
spec/components/inverse_header_spec.rb
spec/components/notice_spec.rb
spec/support/components_helper.rb

We currently don't support passing in a block to this component like we do for other components. It'll make it easier to pass in safe HTML to the component.
Also updates the test helper to make this possible.
https://trello.com/c/k5agy6jw

Allow passing in govspeak into notice component 

---

app/views/govuk_publishing_components/components/_layout_for_admin.html.erb
spec/components/layout_for_admin_spec.rb

As this component is intended for admin apps this metatag asks google and
other robots that respect it to not index the page, not index the images
in the page, and not follow the links for indexing.
---
https://govuk-publishing-compon-pr-409.herokuapp.com/component-guide/

Add robots rules

---

app/views/govuk_publishing_components/components/_contextual_breadcrumbs.html.erb
app/views/govuk_publishing_components/components/_contextual_sidebar.html.erb
app/views/govuk_publishing_components/components/_government_navigation.html.erb
app/views/govuk_publishing_components/components/_layout_footer.html.erb
spec/components/all_components_spec.rb

This adds a test to make sure that every component has  a specific formatted class name. This will encourage consistency and codifies that we'll also a d the `gem-c-` class to GOV.UK Frontend-powered components. This makes sure that the browser extension can highlight and link all of our components.
There are a couple of components that have weird class names, so I've added those to `skip` (meaning they should be fixed). For example, the class name for the previous_and_next_navigation component is `gem-c-pagination`, not `gem-c-previous-and-next-navigation` as one might expect.
There are 3 components that don't need a class name, they're in `not_applicable` (which means they will not be fixed).

Add test that components have the correct class

---

app/assets/javascripts/govuk_publishing_components/admin_scripts.js
app/views/govuk_publishing_components/components/_layout_for_admin.html.erb
app/views/layouts/govuk_publishing_components/application.html.erb
config/initializers/assets.rb

Add JavaScript support for admin layout and review app components that are flagged as part_of_admin_layout.
[Trello card](https://trello.com/c/FKQqvGsp)
---
https://govuk-publishing-compon-pr-415.herokuapp.com/component-guide/

Add javascript support for admin layout components

---

app/assets/stylesheets/govuk_publishing_components/admin_styles.scss
app/assets/stylesheets/govuk_publishing_components/components/_layout-header.scss
app/views/govuk_publishing_components/components/_layout_for_admin.html.erb
app/views/govuk_publishing_components/components/_layout_header.html.erb
app/views/govuk_publishing_components/components/docs/layout_for_admin.yml
app/views/govuk_publishing_components/components/docs/layout_header.yml
spec/components/layout_header_spec.rb

This implements the header component from GOV.UK Frontend exemplifying with environment, product name and navigation items.
- Contains [a CSS fix](https://github.com/alphagov/govuk_publishing_components/pull/408/files#diff-e9749171eb74b1f0e663c2b759893bf5R16) that should be removed after [updating to the next govuk-frontend release](https://github.com/alphagov/govuk-frontend/pull/884).
- JavaScript needed for the navigation on mobile devices not added yet, will be part of the admin layout. (l.e. added in https://github.com/alphagov/govuk_publishing_components/pull/415)
[View in component guide](https://govuk-publishing-compon-pr-408.herokuapp.com/component-guide/layout_header)
[Trello card](https://trello.com/c/faHdZDk2)

Add header component

---

CHANGELOG.md
app/assets/javascripts/govuk_publishing_components/components/step-by-step-nav.js
app/assets/javascripts/govuk_publishing_components/lib/history-support.js
app/views/govuk_publishing_components/components/docs/step_by_step_nav.yml
spec/javascripts/components/step-by-step-nav-spec.js

- use sessionStorage, not URL
- can now remember more than one open step
- remove a lot of redundant code (relating to this and not relating to this)
Trello card: https://trello.com/c/pjEOb2FO/702-spike-options-for-remembering-opened-steps
Removes dependence on history.js, fixes https://github.com/alphagov/govuk_publishing_components/issues/396
---
https://govuk-publishing-compon-pr-406.herokuapp.com/component-guide/

Improve step nav 'remember open steps' code

---

app/assets/stylesheets/govuk_publishing_components/components/_previous-and-next-navigation.scss
app/views/govuk_publishing_components/components/_previous_and_next_navigation.html.erb

- Link title text size changed from core-27 to core-19 with font-weight of bold.
- Link label offset to match position of link title text.
- All text and icon now left aligned
We know from our user research that the current next / previous arrows on mainstream guides can be improved.
There's two problems:
- They point to the sidebar content (particularly step by steps) which is confusing
- Users zooming into the page can only see one at a time
One of our goals this quarter is to optimise the user-facing step by step pattern.
Ticket: https://trello.com/c/IELXDsqb/701-improve-the-accessibility-of-the-previous-next-arrows-on-mainstream-guides
--- …

Improve the accessibility of the previous/next arrows on mainstream guides

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/_skip-link.scss
app/views/govuk_publishing_components/components/_layout_for_admin.html.erb
app/views/govuk_publishing_components/components/_skip_link.html.erb
app/views/govuk_publishing_components/components/docs/skip_link.yml
spec/components/skip_link_spec.rb
spec/dummy/app/views/layouts/dummy_admin_layout.html.erb
spec/dummy/app/views/welcome/admin_example.html.erb

This PR:
- adds skip link component based on GOVUK Frontend
- fix: moves the header and footer from the admin layout published in gem to the dummy admin layout in spec
- adds container wrapper and main element to the admin layout
- updates changelog
---
https://govuk-publishing-compon-pr-417.herokuapp.com/admin

Add skip link component and main container to admin layout

---

app/views/govuk_publishing_components/components/_layout_for_admin.html.erb

This has added the cross site forge request headers
However I can't work out how to test it. The required meta tags appear as expected in the example pages, but they aren't there in the context of the rspec test. I suspect this is related to forgery protection being off by default in a test environment, but can't work out how to switch it back on. Input welcome!
---
https://govuk-publishing-compon-pr-418.herokuapp.com/component-guide/

Add anti-forgery meta tags

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Improve step nav 'remember open steps' code (PR #406)
* The Notice component now accepts blocks (PR #407)
* Add experimental layout-header component based on GOV.UK Frontend (PR #408)
* Add robots nofollow meta tag to admin layout (PR #409)
* Improve the accessibility of the previous/next arrows on mainstream guides (PR #410)
* Import and initialise GOV.UK Frontend scripts in the admin layout (PR #415)
* Remove unneeded options from step nav component (PR #416)
* Add experimental skip link component based on GOV.UK Frontend (PR #417)
* Add CSRF meta tag to admin layout (PR #418)

Release version 9.5.0

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/_step-by-step-nav-related.scss

- changes margin bottom on step by step nav related from $gutter * 1.5 to $gutter-half for both desktop and mobile
- adds font size bold-24 for mobile views
On mobile when the step by step nav appears as a footer the sizing of the step by step title is too small and there's a lot of whitespace between the title and the steps beneath.
We should bump up the size of the title and close up the space a little. Check-in with Kate if you need guidance on sizing and spacing.
One of our goals this quarter is to optimise the user-facing step by step pattern.
Ticket: https://trello.com/c/zlQ0Go3P/700-fix-the-step-by-step-title-sizing-and-spacing-on-mobile-when-it-appears-as-a-footer
---
Component guide …

Fix the step by step title sizing and spacing on mobile when it appears as a footer

---

docs/component_conventions.md

This PR:
- fixes the links to GOV.UK Frontend CSS and JavaScript conventions
- updates the GOV.UK Frontend namespace (from `.govuk-c-` to simply `.govuk-`)

Fix govuk-frontend URLs

---

CHANGELOG.md
app/assets/javascripts/govuk_publishing_components/components/step-by-step-nav.js
app/assets/stylesheets/govuk_publishing_components/components/_step-by-step-nav.scss
app/views/govuk_publishing_components/components/_step_by_step_nav.html.erb
spec/javascripts/components/step-by-step-nav-spec.js

Google is currently displaying snippets for some of our step by step pages like this:
This PR attempts to improve the snippet display by:
- wrapping the 'show' elements in brackets (hidden to users, both visually and with aria)
- lowercasing the 'show' elements (using CSS to capitalize, don't know if this will actually work)
This hopefully will produce a snippet more like this:
"Step 2 Update your vehicle's log book (V5C) (show). ... "
---
Trello card: https://trello.com/c/xTkNr64l/712-fix-google-snippet-display
https://govuk-publishing-compon-pr-424.herokuapp.com/component-guide/

Attempt to improve Google snippet display

---

app/assets/stylesheets/govuk_publishing_components/admin_styles.scss

We rely on the govspeak component for styling large blocks of text with headings, paragraphs and links.
---
https://govuk-publishing-compon-pr-427.herokuapp.com/component-guide/

Disable govuk-frontend global styles

---

app/views/govuk_publishing_components/components/_feedback.html.erb

Mask email addresses that happen to be part of the URL (e.g. from email subscription management frontend).  This prevents them from being submitted without the user's knowledge.
https://trello.com/c/jKitCyZI/311-remove-emails-from-ga-events-on-email-alert-frontend-pages

Mask email addresses from the URL submitted with feedback responses

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/_document-list.scss
app/views/govuk_publishing_components/components/docs/document_list.yml

Move the metadata to the right when on a right to left layout. Otherwise it's difficult to see how the metadata is related to the document list item heading
Component guide: https://govuk-publishing-compon-pr-429.herokuapp.com/component-guide/document_list

Improve metadata positioning in doc list for right to left layouts

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

This version includes:
* Improve metadata positioning in document list for rtl layouts (PR #429)
* Add favicon to admin layout (PR #426)
* Disable govuk-frontend global styles (PR #427)
* Mask email addresses from the URL submitted with feedback responses (PR #428)

Version gem 9.5.3

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/_select.scss
app/views/govuk_publishing_components/components/_select.html.erb
app/views/govuk_publishing_components/components/docs/select.yml
spec/components/select_spec.rb

Only works in admin layout
https://trello.com/c/zW7BT3w9/28-add-select-dropdown-component
---
https://govuk-publishing-compon-pr-434.herokuapp.com/component-guide/select

Add select dropdown component based on design system select

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/_breadcrumbs.scss
app/views/govuk_publishing_components/components/_breadcrumbs.html.erb
spec/components/breadcrumbs_spec.rb

- from 'gem-c-breadcrumbs--item' to 'gem-c-breadcrumbs__item'
- was not following BEM convention, 'item' is an element, not a modifier
This should also fix the problem with this component in the 'highlight components' option of the GOV.UK browser extension, see below.
---
https://govuk-publishing-compon-pr-435.herokuapp.com/component-guide/

Change breadcrumb class name

---

CHANGELOG.md
app/assets/javascripts/govuk_publishing_components/components/step-by-step-nav.js
app/views/govuk_publishing_components/components/docs/step_by_step_nav.yml
lib/govuk_publishing_components/presenters/page_with_step_by_step_navigation.rb
spec/javascripts/components/step-by-step-nav-spec.js

The double dot problem occurs where a page occurs more than once in a single step by step navigation. The backend doesn't know which link was clicked, so we use JS to store the clicked link in sessionStorage, then work out which link and step to highlight when the page loads again based on that. The aims are:
- to ensure that no more than one link and one step are highlighted
- to ensure that the last link the user clicked on (assuming it is still in a step by step navigation) is the one that is highlighted
This solution was previously implemented only to handle highlighting of the links themselves, but has been expanded to include the highlighting of the steps as well.
- now handles highlighting of both the links and the steps
- uses the step nav id to create a unique session store …

Extend the double dot problem solution

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/_all_components.scss
app/assets/stylesheets/govuk_publishing_components/components/_back-link.scss
app/views/govuk_publishing_components/components/_back_link.html.erb
spec/components/back_link_spec.rb

The font style for this component is currently coming from govuk_template. This PR updates the component to use GOV.UK Frontend styles which also extends component's compatibility (the left chevron) down to IE8.
&nbsp;&nbsp;<img width="71" alt="screen shot 2018-07-25 at 12 35 39" src="https://user-images.githubusercontent.com/788096/43198645-4f1352b0-9007-11e8-95df-d567d27d70ed.png">
---
https://govuk-publishing-compon-pr-440.herokuapp.com/component-guide/back-link

Update back-link component

---

CHANGELOG.md
app/assets/javascripts/govuk_publishing_components/components/radio.js
app/views/govuk_publishing_components/components/_radio.html.erb
app/views/govuk_publishing_components/components/docs/radio.yml
spec/components/radio_spec.rb

This PR adds conditional reveal support for radios using GOV.UK Frontend scripts.
Because GOV.UK Frontend components are not compatible (they are being initialised differently) with the `GOVUK.Modules` script, I attached them to a `GOVUK.FrontendModules` global.
For example the Radios script can be accessed via `GOVUK.FrontendModules.Radios`.
This PR also contains a `nodeListForEach` utility function to iterate through each module instance on the page (if multiple). This could potentially be replaced by a Polyfill and placed at a higher lever to be shared between components.
---
https://govuk-publishing-compon-pr-441.herokuapp.com/component-guide/radio/conditional/preview

Add conditional reveal support for radios

---

app/assets/stylesheets/govuk_publishing_components/components/_input.scss
app/views/govuk_publishing_components/components/_input.html.erb
spec/components/input_spec.rb

This PR:
- updates the Form input component to use GOV.UK Frontend styles
- uses Rails helpers to generate markup
---
https://govuk-publishing-compon-pr-442.herokuapp.com/component-guide/input

Update input component

---

app/assets/stylesheets/govuk_publishing_components/components/_label.scss
app/assets/stylesheets/govuk_publishing_components/components/_radio.scss
app/views/govuk_publishing_components/components/_input.html.erb
app/views/govuk_publishing_components/components/_label.html.erb
app/views/govuk_publishing_components/components/_radio.html.erb
spec/components/input_spec.rb
spec/components/label_spec.rb
spec/components/radio_spec.rb

This PR:
- updates the [label component](https://govuk-publishing-compon-pr-443.herokuapp.com/component-guide/label) to use GOV.UK Frontend styles
- updates the [radio component](https://govuk-publishing-compon-pr-443.herokuapp.com/component-guide/radio) to use the new label component
- updates the [input component](https://govuk-publishing-compon-pr-443.herokuapp.com/component-guide/input) to use the new label component
Notes:
This PR does not handle the hint and error message updates which will be part of a new PR.
Recommend review commit-by-commit.
[Trello card](https://trello.com/c/nONqbbzg)
---
https://govuk-publishing-compon-pr-443.herokuapp.com/component-guide/

Update label component

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/_layout-header.scss
app/assets/stylesheets/govuk_publishing_components/components/_radio.scss
package-lock.json
package.json

Changes:
- https://github.com/alphagov/govuk-frontend/releases/tag/v1.1.0
- https://github.com/alphagov/govuk-frontend/releases/tag/v1.1.1
- https://github.com/alphagov/govuk-frontend/releases/tag/v1.2.0

Upgrade to GOV.UK Frontend 1.2.0

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Update radio component to use GOV.UK Frontend styles (PR #433)
* Update button component to use GOV.UK Frontend styles (PR #439)
* Update back-link component to use GOV.UK Frontend styles (PR #440)
* Add conditional reveal support for radios using GOV.UK Frontend scripts (PR #441)
* Update input component to use GOV.UK Frontend styles (PR #442)
* Update label component to use GOV.UK Frontend styles (PR #443)
* Upgrade to the latest version of the Design System (PR #444)

Version 9.7.0

---

app/assets/stylesheets/govuk_publishing_components/components/_feedback.scss
app/assets/stylesheets/govuk_publishing_components/components/_input.scss
app/views/govuk_publishing_components/components/_feedback.html.erb

This PR:
- updates the feedback component to use the button components
- applies a stronger selector for inputs; static overwrites the input styles coming from GOV.UK Frontend using `input[type="text"]` as selector, so we need to apply `.govuk-input` styles with a stronger selector until the styles from static will be removed.
Below is an example of how this component is rendered in gov.uk and how it's rendered after the update. While the styles overwrite could be done in the applications I consider it's better to be done here since there are strong chances that this component will be loaded with static styles in other projects.
---
https://govuk-publishing-compon-pr-447.herokuapp.com/component-guide/feedback

Update feedback component

---

app/assets/javascripts/govuk_publishing_components/components/step-by-step-nav.js
spec/javascripts/components/step-by-step-nav-spec.js

- this reverts a change that was intended to make the Google snippet for a step by step page more readable (but didn't work)
- changes '(show)' and '(hide)' links back to just 'show' and 'hide'
- neither of these changes altered the appearance of the component
---
https://govuk-publishing-compon-pr-448.herokuapp.com/component-guide/

Remove brackets from show/hide links

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/_document-list.scss
app/views/govuk_publishing_components/components/_document_list.html.erb

This PR adds resets paddings and margins and adds font styles without having the component rely on the reset CSS.
Here is an example of how the component looks like without reset CSS.
---
https://govuk-publishing-compon-pr-451.herokuapp.com/component-guide/document_list

Add resets to document list

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_contextual_breadcrumbs.html.erb
spec/components/contextual_breadcrumbs_spec.rb

Contextual breadcrumbs will show taxon based breadcrumbs if prioritise_taxon_breadcrumbs is true (defaults to false if not passed) 
---
https://govuk-publishing-compon-pr-457.herokuapp.com/component-guide/
https://govuk-publishing-compon-pr-457.herokuapp.com/component-guide/contextual_breadcrumbs
Trello card
https://trello.com/c/yZfYuiJp/84-use-taxons-breadcrumb-in-b-sample

Add prioritise_taxon_breadcrumbs flag to contextual breadcrumbs

---

app/assets/stylesheets/govuk_publishing_components/components/_error-message.scss
app/assets/stylesheets/govuk_publishing_components/components/_hint.scss
app/assets/stylesheets/govuk_publishing_components/components/_input.scss
app/assets/stylesheets/govuk_publishing_components/components/_radio.scss
app/views/govuk_publishing_components/components/_error_message.html.erb
app/views/govuk_publishing_components/components/_hint.html.erb
app/views/govuk_publishing_components/components/_input.html.erb
app/views/govuk_publishing_components/components/_radio.html.erb
app/views/govuk_publishing_components/components/docs/back_link.yml
app/views/govuk_publishing_components/components/docs/button.yml
app/views/govuk_publishing_components/components/docs/error_message.yml
app/views/govuk_publishing_components/components/docs/hint.yml
app/views/govuk_publishing_components/components/docs/input.yml
app/views/govuk_publishing_components/components/docs/label.yml
app/views/govuk_publishing_components/components/docs/radio.yml
spec/components/error_message_spec.rb
spec/components/hint_spec.rb
spec/components/input_spec.rb
spec/components/radio_spec.rb

This PR adds error message and hint as components and updates the two components using them (input and radio).
The reason for having these as separate components instead of being part of the label component is that they should also be able to be used for fieldsets in legends so decoupling them allows them to be used in other circumstances.
---
[Trello card](https://trello.com/c/4iwUWRwz)
https://govuk-publishing-compon-pr-446.herokuapp.com/component-guide/

Add error message and hint

---

app/assets/stylesheets/govuk_publishing_components/components/_details.scss
app/views/govuk_publishing_components/components/_details.html.erb
app/views/govuk_publishing_components/components/docs/details.yml
spec/components/details_spec.rb

The details component is useful to reveal more detailed information.
https://govuk-publishing-compon-pr-453.herokuapp.com/component-guide/details
https://trello.com/c/d1jqgiXk/54-add-details-component

Add details component

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/_textarea.scss
app/views/govuk_publishing_components/components/_textarea.html.erb
app/views/govuk_publishing_components/components/docs/textarea.yml
spec/components/textarea_spec.rb

Add experimental textarea component based on GOVUK Frontend.
This is dependent on #446.
All unnecessary commits will be removed at rebase.
The only commit that this PR will bring is [7a1013c](https://github.com/alphagov/govuk_publishing_components/pull/450/commits/7a1013c66384d430cc9bdf3c0b546914c25d8d71).
[Trello card](https://trello.com/c/1kjXetZW)
---
https://govuk-publishing-compon-pr-450.herokuapp.com/component-guide/textarea

Add textarea component

---

CHANGELOG.md
lib/govuk_publishing_components/version.rb

This release contains a number of new components as per the changelog.
---
https://govuk-publishing-compon-pr-460.herokuapp.com/component-guide/

Bump version from 9.7.0 to 9.8.0

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_step_by_step_nav.html.erb
spec/components/step_by_step_nav_spec.rb

- hopefully this will add a colon between the words 'Step x' and the title of the step, so the google snippet will look more like: "Step 1: Buy a car"
- should not impact accessibility as the colon has aria hidden on it, voiceover ignores it
---
Trello card: https://trello.com/c/n74CIkZ8/524-review-the-effects-of-the-google-snippet-changes
https://govuk-publishing-compon-pr-461.herokuapp.com/component-guide/

Step by step component, Google snippet improvement

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/_tabs.scss
app/views/govuk_publishing_components/components/_tabs.html.erb
app/views/govuk_publishing_components/components/docs/select.yml
app/views/govuk_publishing_components/components/docs/tabs.yml
spec/components/tabs_spec.rb
spec/dummy/app/controllers/welcome_controller.rb
spec/dummy/app/views/welcome/tabs_example.html.erb
spec/dummy/config/routes.rb
spec/features/tabs_spec.rb

Tabs component added, brought in from the design system. Also implements
a test page containing an example of the component for testing purposes.
---
https://govuk-publishing-compon-pr-455.herokuapp.com/component-guide/

Add tabs component

---

docs/component_conventions.md

Feel free to close this, but I hope this is helpful.
This is documentation explaining a preferred way to construct components that accept HTML based on:
- [an incident involving multiple components](https://github.com/alphagov/govuk_publishing_components/pull/305)
- [a potential vulnerability with the govspeak component](https://github.com/alphagov/govuk_publishing_components/pull/356).

Add guidance for how to pass HTML to components

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/_step-by-step-nav-related.scss
app/views/govuk_publishing_components/components/_step_by_step_nav_related.html.erb

- Increase size of font to be the same size as the step by step headings
- Increase the margin-top for the "part of" text to $gutter-two-third
- Decrease the margin-bottom for the "part of" text to $gutter-one-quarter
- Decrease the margin-bottom of step by step title to $gutter-one-third + 3
Change number 4 is being done as there is a padding of 7px on the show all button which makes the margin-bottom seem much larger.
This should not affect cases where there are multiple step by steps.
Ticket: https://trello.com/c/zlQ0Go3P/700-fix-the-step-by-step-title-sizing-and-spacing-on-mobile-when-it-appears-as-a-footer-s
---
https://govuk-publishing-compon-pr-458.herokuapp.com/component-guide/step_by_step_nav_related

Changes required when there are only one "part of" step by step navs

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/presenters/machine_readable/article_schema.rb
lib/govuk_publishing_components/presenters/machine_readable/how_to_schema.rb
lib/govuk_publishing_components/presenters/machine_readable/page.rb
lib/govuk_publishing_components/presenters/schema_org.rb
spec/lib/presenters/schema_org_spec.rb

- Adds a `HowTo` schema to more accurately (than using `Article`) represent the semantics of this relationship.
- Links content that should show things in a `step-by-step-related` component to those pages by using the [`isPartOf` property](https://schema.org/isPartOf).
The `HowTo` schema implemented here is minimal because we link using [`sameAs`](https://schema.org/sameAs) to the step by step page which has a [fuller schema implemented in collections](https://github.com/alphagov/collections/blob/7e0134d150916d37cef679980a7d13400c583b71/app/models/step_nav.rb#L31-L65).
It seems valid (at least the Google structured data testing tool doesn't object) to be "isPartOf" many things. This fits quite well with what we want to do with step by steps.
We could easily add the step by steps that are …

Add isPartOf to articles that are in a step by step

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_document_list.html.erb
app/views/govuk_publishing_components/components/docs/document_list.yml
spec/components/document_list_spec.rb

Trello: https://trello.com/c/dOhKVSbr/73-stop-document-list-component-using-headings-by-default
This stops rendering the document title as a heading. This was cluttering up pages with lots of H3s which is bad for accessibility.
There shouldn't be any visible difference to the component, but behind the scenes the title is now an <a> tag even if description and metadata are passed in.
https://govuk-publishing-compon-pr-465.herokuapp.com/component-guide/document_list

Remove headings from document list component

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

Includes the following change:
- Stop document list rendering titles as headings (PR #465)
https://govuk-publishing-compon-pr-466.herokuapp.com/component-guide/

Version 9.9.1

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/govspeak/_typography.scss
app/views/govuk_publishing_components/components/_govspeak.html.erb
app/views/govuk_publishing_components/components/_govspeak_html_publication.html.erb
app/views/govuk_publishing_components/components/docs/govspeak.yml
spec/components/govspeak_html_publication_spec.rb
spec/components/govspeak_spec.rb
spec/dummy/app/views/welcome/contextual_navigation.html.erb

https://trello.com/c/BUij6N3Y/361-turn-on-bold-for-whitehall
Do not merge because we'd like to see how this works in various formats in a preview app.
We've been asked to enable bold text for a specific format which tested favourably.
(eg. https://www.gov.uk/guidance/connect-to-govwifi-using-an-android-device)
Instead of enabling bold text by exception this PR enables it entirely for govspeak text containing `<strong>` tags.
---
https://govuk-publishing-compon-pr-463.herokuapp.com/component-guide/

[Do not merge] Enable bold text in govspeak

---

CHANGELOG.md
lib/govuk_publishing_components/version.rb

https://trello.com/c/BUij6N3Y/361-turn-on-bold-for-whitehall
Enables bold styling in govspeak blocks, removes rich govspeak feature (PR #463)
---
https://govuk-publishing-compon-pr-467.herokuapp.com/component-guide/

Bump version to 9.10.0

---

app/views/govuk_publishing_components/components/_textarea.html.erb
spec/components/textarea_spec.rb

This PR adds the following to the textarea component:
-  data attributes (for JavaScript module initialisation - e.g. `data-module`; analytics tracking - e.g. `data-track`)
- spellcheck so we can disable so we can disable browser spell check when needed.
---
https://govuk-publishing-compon-pr-468.herokuapp.com/component-guide/textarea

Update textarea component

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_input.html.erb
spec/components/input_spec.rb

This PR adds the following to the input component:
-  data attributes (for JavaScript module initialisation - e.g. `data-module`; analytics tracking - e.g. `data-track`)
---
https://govuk-publishing-compon-pr-469.herokuapp.com/component-guide/input

Add data-attribute support to input

---

CHANGELOG.md
lib/govuk_publishing_components/presenters/contextual_navigation.rb

This changes the assignment of requested path of document type
"simple_smart_answer" to use the base path of the content item rather
than the requested based path.
This change was done so that the active link would show correctly on
simple smart answers.
Ticket: https://trello.com/c/SaxKuvqK/726-relevant-step-by-step-should-be-open-inside-simple-smart-answers-showing-the-dot-on-the-task-m
---
https://govuk-publishing-compon-pr-472.herokuapp.com/component-guide/

Relevant step by step should now be open inside simple smart answers

---

CHANGELOG.md
lib/govuk_publishing_components/presenters/meta_tags.rb
spec/components/meta_tags_spec.rb

There is a GA custom dimension called "rendering-application" so it makes sense
to call this metatag "publishing-application".
https://trello.com/b/16mTLUnP/platform-health-doing

Rename publishing-app metatag

---

CHANGELOG.md
lib/govuk_publishing_components/version.rb

Renames the publishing-app metatag to publishing-application, to be consistent with rendering-application (PR #471)
https://trello.com/c/vhfMGngX/239-investigate-and-correct-smart-answer-google-analytics-tracking

Version 9.12.1

---

CHANGELOG.md
Gemfile.lock
app/views/govuk_publishing_components/components/_layout_for_admin.html.erb

This PR allows custom tags in the `<head>` of admin layout. This is currently needed to load application styles in admin interfaces.
Updates gemfile.lock missed from #479 which makes Heroku fail on deploys
---
Example of usage in `app/views/layouts/application.html.erb`:
```
<% content_for :head do %>
<%= stylesheet_link_tag "application" %>
<% end %>
<%= render 'govuk_publishing_components/components/layout_for_admin', { ... } do %>
...
<% end %>
```
https://govuk-publishing-compon-pr-480.herokuapp.com/component-guide/layout_for_admin

Allow custom tags in head for admin layout

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/_all_components.scss
app/assets/stylesheets/govuk_publishing_components/components/_document-list.scss
app/assets/stylesheets/govuk_publishing_components/components/_taxonomy-list.scss
app/views/govuk_publishing_components/components/_document_list.html.erb
app/views/govuk_publishing_components/components/_highlight_boxes.html.erb
app/views/govuk_publishing_components/components/_taxonomy_list.html.erb
app/views/govuk_publishing_components/components/docs/taxonomy_list.yml
lib/govuk_publishing_components.rb
lib/govuk_publishing_components/presenters/taxonomy_list_helper.rb
spec/components/document_list_spec.rb
spec/components/taxonomy_list_spec.rb

Trello: https://trello.com/c/PFbuMOGm/100-spike-adapt-highlight-box-component-to-work-in-a-list-of-links
We needed to work out a way to display service links (some of which are a list of highlight boxes, some are a document list) so that they are part of one HTML list. I also tried:
- Adding a flag to remove the `<ul>` from the highlight box and document list components. However, this would require developers to a) wrap the components they're using in a list tag, and b) require them to copy over styling so the elements were displayed appropriately.
Link to the component: https://govuk-publishing-compon-pr-476.herokuapp.com/component-guide/taxonomy_list
I think we'd also be able to use this for [image cards + document list](https://govuk-publishing-compon-pr-476.herokuapp.com/component-guid …

Taxonomy List Component

---

CHANGELOG.md
app/assets/javascripts/govuk_publishing_components/components/step-by-step-nav.js
app/views/govuk_publishing_components/components/docs/step_by_step_nav.yml
spec/javascripts/components/step-by-step-nav-spec.js

- shorten code
- if no sessionStorage value (i.e. user is arriving at the page cold) highlight the first active link and active step, not the last
- expand documentation to clarify how this behaves
See the documentation for full details. Expands the solution to this problem:
---
Trello card: https://trello.com/c/LTzIkmOX/776-optimise-default-open-step
https://govuk-publishing-compon-pr-473.herokuapp.com/component-guide/

Improve step by step component double dot problem solving code

---

CHANGELOG.md
config/routes.rb
lib/govuk_publishing_components/presenters/machine_readable/article_schema.rb
spec/lib/presenters/schema_org_spec.rb

Adds the 'about' property for the schema.org schema for an Article with live taxons
Uses the live taxonomies to which content is tagged to generate an about section for the article schema. This is so 
---
https://govuk-publishing-compon-pr-482.herokuapp.com/component-guide/
Trello
https://trello.com/c/tiEHCuAA/123-implement-adding-about-to-schemaorg-article-schema

Add 'about' to schema.org article schema

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/_all_components.scss
app/assets/stylesheets/govuk_publishing_components/components/_tabs.scss
app/views/govuk_publishing_components/components/_tabs.html.erb
app/views/govuk_publishing_components/components/docs/tabs.yml
spec/components/tabs_spec.rb

Makes the redundant heading inside the panel optional and adds panel without border modifier
---
https://govuk-publishing-compon-pr-485.herokuapp.com/component-guide/tabs

Update tabs component

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/_button.scss
app/views/govuk_publishing_components/components/docs/button.yml
lib/govuk_publishing_components/presenters/button_helper.rb
spec/components/button_spec.rb

This PR adds secondary and secondary quiet modifiers to button component needed for the admin interfaces.
---
https://govuk-publishing-compon-pr-484.herokuapp.com/component-guide/button

Add secondary and secondary quiet modifiers to button component

---

CHANGELOG.md
app/views/govuk_publishing_components/components/docs/button.yml
lib/govuk_publishing_components/presenters/button_helper.rb
spec/components/button_spec.rb

Allow target attribute on links styled as buttons for opening in a new tab.
---
https://govuk-publishing-compon-pr-488.herokuapp.com/component-guide/button

Allow target to be specified for button components

---

app/views/govuk_publishing_components/components/_google_tag_manager_script.html.erb
app/views/govuk_publishing_components/components/docs/google_tag_manager_script.yml
spec/components/all_components_spec.rb

Component to generate the Google Tag Manager script for a given `gtm_id` (mandatory), `gtm_auth` and `gtm_preview` (optional depending on the GTM setup).
This also contains [a cross browser implementation of `doNotTrack`](https://github.com/alphagov/govuk-design-system/pull/296), so users don't have to rely on obscure plugins to block tracking.
[Trello card](https://trello.com/c/wh7K3ul2)

Add Google Tag Manager script as component

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_radio.html.erb
spec/components/radio_spec.rb

Currently, if `conditional` is a symbol, it will always show because this conditional doesn't add the `data-module=radios` attribute. Conversely, if `conditional` is a string it won't be displayed.

Fix bug that prevents conditional content to be shown

---

app/assets/javascripts/govuk_publishing_components/components/copy-to-clipboard.js
app/assets/stylesheets/govuk_publishing_components/_all_components.scss
app/assets/stylesheets/govuk_publishing_components/components/_copy-to-clipboard.scss
app/views/govuk_publishing_components/components/_copy_to_clipboard.html.erb
app/views/govuk_publishing_components/components/docs/copy_to_clipboard.yml
spec/components/copy_to_clipboard_spec.rb

This component will initially be used in the page preview in content publisher to allow users to copy a URL. Once we have it we can then use it to improve the [Subscription links component](https://govuk-publishing-components.herokuapp.com/component-guide/subscription-links/with_copyable_feed_link), which would benefit from the same functionality.
Preview: https://govuk-publishing-compon-pr-494.herokuapp.com/component-guide/copy_to_clipboard
https://trello.com/c/hAfZNnxt/183-add-copy-to-clipboard-component

Create "copy to clipboard" component

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_google_tag_manager_script.html.erb

This PR updates the GTM component to render unencoded ampersands (`&` instead of `&amp;`).
Encoded ampersands doesn't allow preview of GTM tags 😞 
---
https://govuk-publishing-compon-pr-497.herokuapp.com/component-guide/google_tag_manager_script

Render unencoded ampersand in gtm query

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_success_alert.html.erb
app/views/govuk_publishing_components/components/docs/success_alert.yml
spec/components/success_alert_spec.rb

We currently have a really good bug blocking https://github.com/alphagov/content-publisher/pull/220 from being merged.
The success alert component intends to check if there's a block given to the alert component. It does so by checking `yield`. This works in tests, but in the real world there will *always* be a return value of `yield` - either the given block, or the *entire layout of the application*. Which leads to this beauty of a bug, which dupes the entire page inside the success alert:
Unfortunately, we have no way of determining which `yield` we're talking to (`block_given?` is always true), so I think we won't be able to have optional blocks.
https://trello.com/c/i2Fi5qNQ

Avoid using an optional block in success alert component

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_contextual_breadcrumbs.html.erb
app/views/govuk_publishing_components/components/_contextual_sidebar.html.erb
lib/govuk_publishing_components/presenters/contextual_navigation.rb
lib/govuk_publishing_components/presenters/page_with_step_by_step_navigation.rb
spec/features/contextual_navigation_spec.rb
spec/lib/presenters/page_with_step_by_step_navigation_spec.rb

Trello: https://trello.com/c/VOB2ioxF/809-expand-relevant-step-by-step-in-the-sidebar-to-show-the-journey-the-user-is-on-m
As a someone trying to do a thing
I want to see the steps in the step by step journey I am on
So that I know what I need to do next
If a content page is in more than one step nav, we only show a link to all of the step navs. This makes it harder for the user to navigate to the next step in their journey.
Add something to the component that reads this value, so when then the content page is loaded the sidebar component expands the step by step that the user is following.
To make it easier for users to complete the journey they are on. 
I think we should see more linear journeys, and less clicking of the back button.
There are limitations to this solution:
1. If the …

Expand relevant step-by-step to show the journey the user is on 

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_step_by_step_nav.html.erb
lib/govuk_publishing_components/presenters/step_by_step_nav_helper.rb
spec/components/step_by_step_nav_spec.rb
spec/lib/components/step_by_step_nav_helper_spec.rb

As a someone trying to do a thing
I want to see the steps in the step by step journey I am on
So that I know what I need to do next
If a content page is in more than one step nav, we only show a link to all of the step navs. This makes it harder for the user to navigate to the next step in their journey.
Add a parameter to the querystring when the user clicks on a link in a step nav. Then add something to the component that reads this value, so when then the content page is loaded the sidebar component expands the step by step that the user is following.
To make it easier for users to complete the journey they are on. 
I think we should see more linear journeys, and less clicking of the back button.
There are limitations to this solution:
1. If the user comes to a content page with …

Adds step by step content ID to links inside steps

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/_error-summary.scss
app/views/govuk_publishing_components/components/_error_summary.html.erb
app/views/govuk_publishing_components/components/docs/error_summary.yml
spec/components/error_summary_spec.rb

Allow error_summary to render without a 'title'. Now the error_summary requires either a title or at least one item in order to error. An ArgumentError is raised in the case where `{title: false, items: []}`
Previously each item in the error_summary required a href linking to more details for the errors, this change makes the href optional.
---

Update error_summary to make title and hrefs optional

---

app/views/govuk_publishing_components/components/_error_alert.html.erb
app/views/govuk_publishing_components/components/_success_alert.html.erb

We want to put multiple paragraphs into the message body, which isn't possible if the element is a `<p>` already.
https://trello.com/c/VkVrVGeB

Use div's for the alert message bodies

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_contextual_sidebar.html.erb
app/views/govuk_publishing_components/components/_step_by_step_nav_related.html.erb
app/views/govuk_publishing_components/components/docs/step_by_step_nav_related.yml
spec/components/step_by_step_nav_related_spec.rb

When you're on a page that is part of two step by steps and one is expanded the other is displayed underneath as a heading but has no associated content.
When this happens the current orphaned header should be render as a list.
We should provide the option to display this as a list.
Ticket: https://trello.com/c/ul9DX8yu/856-refactor-header-component-to-provide-options-for-head-or-list
---
https://govuk-publishing-compon-pr-516.herokuapp.com/component-guide/step_by_step_nav_related/always_display_as_a_list

Refactor header component to provide options for head or list

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/_highlight-boxes.scss
app/views/govuk_publishing_components/components/_highlight_boxes.html.erb
app/views/govuk_publishing_components/components/docs/highlight_boxes.yml
spec/components/highlight_boxes_spec.rb

https://govuk-publishing-compon-pr-520.herokuapp.com/component-guide/highlight_boxes/half_width

Add half_width flag to highlight boxes

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

Changes in this version:
* Add half_width flag for higlight boxes (PR #520)
https://govuk-publishing-compon-pr-526.herokuapp.com/component-guide/

Version 9.23.0

---

CHANGELOG.md
app/views/layouts/govuk_publishing_components/application.html.erb

This moves the script elements from the HTML head to be just before the
closing body tag.
The reasons for this change are:
- This is a standard practice for not hindering a web page rendering
with blocking scripts
- This allows to embrace the script initialisation approach used by
[GOV.UK Frontend][1]
The need for this is triggered by Content Publisher using the GOV.UK
Frontend initialisation approach and thus the components do not work.
As far as I can tell this shouldn't cause any problems for existing apps
as all of their JS is initialised within `$(document).ready` functions
so will still execute at the same time.
[1]: https://github.com/alphagov/govuk-frontend/blob/master/docs/installation/installing-from-dist.md#2-include-resources
An alternative to this may be to include …

Move javascript initialistation to footer of component guide

---

CHANGELOG.md
lib/govuk_publishing_components/presenters/machine_readable/article_schema.rb
lib/govuk_publishing_components/presenters/machine_readable/has_part_schema.rb
lib/govuk_publishing_components/presenters/schema_org.rb
spec/lib/presenters/schema_org_spec.rb

- Adds hasPart schema to Article schema
- Indicates an item or CreativeWork that is part of this item
https://trello.com/c/Wbc2R5X6/165-add-haspart-schemaorg-property-to-collection-pages
The added schema has been validated by being tested in the Structured Data Testing Tool:
At present this is how the schema looks, when using the Structured Data Testing Tool, showing no errors:
Once the hasPart is deployed, it will append a hasPart section in the Article schema, listing the documents that has been linked to it.
Having the hasPart schema implemented should improve the search results through Google search.
---
https://govuk-publishing-compon-pr-522.herokuapp.com/component-guide/

Add a hasPart schema to collection pages

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/_button.scss
app/views/govuk_publishing_components/components/docs/button.yml
lib/govuk_publishing_components/presenters/button_helper.rb
spec/components/button_spec.rb

https://govuk-publishing-compon-pr-523.herokuapp.com/component-guide/button
As this introduced another class selector for the button, in addition to
the existing 'secondary' and 'secondary-quiet' classes, I thought it
would be cleaner to refactor the decision logic to explicitly choose
which class to apply, rather than implying you can have multiple.
[Trello card](https://trello.com/c/QAEhhJdf/244-build-workflow-for-delete-draft-remove-and-retire-document-m)

Add destructive modifier to button component

---

CHANGELOG.md
app/views/govuk_publishing_components/components/docs/machine_readable_metadata.yml
lib/govuk_publishing_components/presenters/machine_readable/organisation_schema.rb
spec/lib/presenters/schema_org_spec.rb

Adds [parent][1] and [child][2] organisations (if present) to the GovernmentOrganization schema.org information rendered on org pages.
Organisations like [Defra][3] have only child orgs (no parent), [BCMS][4] only have a parent (no children) and some, like [Rural Payments Agency][5] have both.
https://trello.com/c/aoP7LQGh/180-add-parent-and-child-orgs-to-the-governmentorganization-schema
Rural payments agency schema with parent and sub-Organization properties
[1]: https://schema.org/parentOrganization
[2]: https://schema.org/subOrganization
[3]: https://www.gov.uk/government/organisations/department-for-environment-food-rural-affairs
[4]: https://www.gov.uk/government/organisations/rural-payments-agency
[5]: https://www.gov.uk/government/organisations/british-cattle-movement-service
--- …

Add organisation structure schema.org info

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

These changes are small:
- RummagerTaxonomySidebarLinks should not be directly used by anything external
- The org schema changes are minor additions and don't require any opt ins to use
https://trello.com/c/aoP7LQGh/180-add-parent-and-child-orgs-to-the-governmentorganization-schema
---
https://govuk-publishing-compon-pr-534.herokuapp.com/component-guide/

Bump patch version

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_government_navigation.html.erb

Remove `Policies` from the navigation as they are soon to be retired.
This is the governement navbar certain front-ends use (finder-frontend,
government-frontend) which is the same navigation bar whitehall-frontend
uses but the code for whitehalls is in whitehall.
Trello:
https://trello.com/c/e27ECoMb/209-remove-the-policies-link-from-the-content-page-header-applies-to-some-pages

Remove `Policies` from shared nav bar

---

CHANGELOG.md
lib/govuk_publishing_components/presenters/page_with_step_by_step_navigation.rb
spec/lib/presenters/page_with_step_by_step_navigation_spec.rb

We want change how 'Hide navigation' option works.
At the moment when navigation is hidden its hidden for all users. We want to change this so that if a user uses the step by step navigation to get to the page with hidden navigation, the navigation shows.
Lab research has shown the value of showing step by step navigation throughout the journey.
Ticket: https://trello.com/c/SsoemgHH/860-related-to-step-by-step
---
https://govuk-publishing-compon-pr-535.herokuapp.com/component-guide/

Show step by step when disabled but active

---

app/views/govuk_publishing_components/components/docs/related_navigation.yml
lib/govuk_publishing_components/presenters/content_item.rb
lib/govuk_publishing_components/presenters/related_navigation_helper.rb
package-lock.json
spec/components/related_navigation_spec.rb
spec/dummy/app/controllers/welcome_controller.rb
spec/lib/presenters/related_navigation_helper_spec.rb

Remove code related to Policies
Trello card: 
https://trello.com/c/P9Fmi7wX/213-remove-now-unnecessary-code-relating-to-policies-and-policy-areas
As part of the work for the new Single Taxonomy, Policies are being
unpublished, therefore code related to Policies is not needed anymore.

Remove policies related code

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_radio.html.erb
app/views/govuk_publishing_components/components/docs/radio.yml
spec/components/radio_spec.rb

https://trello.com/c/CbTYssq1/478-enable-cross-domain-tracking-for-cysp-govuk-sign-in-pages
In order to track choices made in service sign in pages
across domains we need to expose the destination of the chosen
option.
Related: https://github.com/alphagov/govuk-content-schemas/pull/817
---
https://govuk-publishing-compon-pr-539.herokuapp.com/component-guide/

Add data-tracking-url attribute to radio inputs

---

CHANGELOG.md
lib/govuk_publishing_components/version.rb

https://trello.com/c/CbTYssq1/478-enable-cross-domain-tracking-for-cysp-govuk-sign-in-pages
v10.2.0
* Add data-tracking-url for radio inputs for the purposes of cross domain tracking (PR #539)
---

Bump version to 10.2.0

---

CHANGELOG.md
Gemfile.lock
app/views/govuk_publishing_components/components/docs/image_card.yml
app/views/govuk_publishing_components/components/docs/taxonomy_list.yml
lib/govuk_publishing_components/presenters/image_card_helper.rb
spec/components/image_card_spec.rb

Trello: https://trello.com/c/8UGqW1fT/184-use-time-elements-in-the-image-card-component
**This is a BREAKING CHANGE.**
This PR introduces the following changes:
- Context is now passed to the image component as a hash with a `date` and `text`, rather than a String. These are both optional.
- If a date is passed, it is rendered within a `<time>` element
- If a date and text is passed, the `<time>` element is rendered within a `<p>`, and an `aria-hidden` dash is introduced between the two.
This now matches how we render dates in other components, e.g: [document list](https://govuk-publishing-components.herokuapp.com/component-guide/document_list)
https://govuk-publishing-compon-pr-541.herokuapp.com/component-guide/image_card

Use time element in image card component

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

Includes a __breaking change__ to the image card component.
* This will require an update to usages of the image card component.
The way in which context information is passed to the component has changed from `context: "some context"` to `context: {text: "some context", date: "2017-06-14"`}
https://govuk-publishing-compon-pr-547.herokuapp.com/component-guide/

Version 11.0.0

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_layout_footer.html.erb
app/views/govuk_publishing_components/components/docs/layout_footer.yml
spec/components/layout_footer_spec.rb

This PR adds navigation and meta links to footer component
[Trello card](https://trello.com/c/05wMNlxg)
---
https://govuk-publishing-compon-pr-550.herokuapp.com/component-guide/layout_footer

Add navigation and meta links to footer component

---

app/views/govuk_publishing_components/components/_file_upload.html.erb
app/views/govuk_publishing_components/components/_input.html.erb
app/views/govuk_publishing_components/components/_textarea.html.erb

The `label` attribute should be a hash with keys, but the component guide passes in strings.

Fix label in component guide

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_input.html.erb
app/views/govuk_publishing_components/components/docs/input.yml
spec/components/input_spec.rb

This attribute will be used for the login page to ease the authentication process. It shouldn't be used without user research to back this behaviour.
---
https://govuk-publishing-compon-pr-552.herokuapp.com/component-guide/input/autofocused/preview

Allow autofocus on inputs

---

app/views/govuk_publishing_components/components/docs/machine_readable_metadata.yml
app/views/govuk_publishing_components/components/docs/metadata.yml

In [this PR](https://github.com/alphagov/govuk_publishing_components/pull/400/files#diff-58fe188b00b5e8007bc3deb55a4d728dR12), we mistakenly hid previews for the wrong metadata component. We meant to hide them for the machine-readable metadata component as it has no visible changes.
Should have previews: https://govuk-publishing-compon-pr-559.herokuapp.com/component-guide/metadata
Should only have HTML previews: https://govuk-publishing-compon-pr-559.herokuapp.com/component-guide/machine_readable_metadata

Reinstate previews on metadata component and hide for machine-readable metadata.

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/_related-navigation.scss
app/assets/stylesheets/govuk_publishing_components/components/_taxonomy-navigation.scss
app/views/govuk_publishing_components/components/_taxonomy_navigation.html.erb
app/views/govuk_publishing_components/components/related_navigation/_section.html.erb

Trello: https://trello.com/c/LQKpXVSw/186-audit-components-that-use-a-toggle-and-update-to-hide-the-toggle-link-when-js-is-disabled
Previously, these components would auto-expand all contents when JS was disabled (which is good), but also continue to show the toggle link which would be confusing to users. This PR only shows the toggle link if JS is enabled.
Links:
https://govuk-publishing-compon-pr-551.herokuapp.com/component-guide/related_navigation
https://govuk-publishing-compon-pr-551.herokuapp.com/component-guide/taxonomy_navigation

Fix toggle behaviour when JS disabled

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_layout_header.html.erb
app/views/govuk_publishing_components/components/docs/layout_header.yml
spec/components/layout_header_spec.rb

This is to allow Signon to be called "Signon" again. We'll still use "Publishing" as the default.
Follow up to https://github.com/alphagov/govuk_publishing_components/pull/557.
cc @alex-ju 
https://trello.com/c/05wMNlxg

Make Product name customisable

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

- Fix toggle behaviour in related navigation and taxonomy navigation when JS disabled (PR #551)
- Make "GOV.UK Publishing" the default product name (PR #557 #561)
- Change the colour of production to red (PR #557)
- Add environment tag in the header for all environments (PR #557)

Version 11.2.0

---

Gemfile

This is to help heroku determine which version of Ruby to use.

Specify ruby version in Gemfile

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Append the product name to the browser title (PR #563)
* BREAKING: Remove Slimmer as a dependency
This comprises many minor changes to components so they no longer rely on
Static provided stylesheets.
- If your app uses Slimmer, the component guide will no longer use it and you
can no longer rely on any resets/global rules provided
- If your app removes the Slimmer middleware this will now break as Slimmer
will be an undefined constant
- Apps which the admin layout no longer need to include jQuery as this comes
bundled in the admin scripts.
* Use a purple environment colour on Heroku (#566). Make sure to add a `HEROKU` environment variable to Heroku instances.
* Use a red favicon colour on production (#566)

Bump to version 12.0.0

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/_success-alert.scss

This adds a bottom margin by default to the success alert component.
Trello:
https://trello.com/c/DYwko3da/313-no-margin-below-the-flash-banner-and-the-content-block-below

Add bottom margin to success alert component

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

This fixes a bug where there was no bottom margin on the success-alert
component (PR #573)
---

Update version to 12.0.1

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/_error-alert.scss

This to keep it the same as the success alert component.

Add bottom margin to error component

---

app/views/govuk_publishing_components/components/_layout_for_admin.html.erb
spec/components/layout_for_admin_spec.rb

The emdash is hysterically long, which looks weird.

Use a normal dash for the browser title

---

app/assets/stylesheets/govuk_publishing_components/components/_layout-for-admin.scss
spec/dummy/app/views/welcome/admin_example.html.erb

This fixes a bug from https://github.com/alphagov/govuk_publishing_components/pull/571 that meant that the grid system isn't available in the admin layout component. `govuk-frontend/helpers/grid` just includes some mixins, the actual classes are in `govuk-frontend/objects/grid`.

Allow grid system to be used in admin layout

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_admin_analytics.html.erb
app/views/govuk_publishing_components/components/docs/admin_analytics.yml

This is currently done in Signon, and I'm assuming that this is fine to happen in all admin applications.

Send the current user's organisation to GA

---

app/assets/stylesheets/govuk_publishing_components/components/_button.scss
app/views/govuk_publishing_components/components/docs/button.yml

This PR sets the appropriate background colour when buttons are being focused and updates the examples to use the `<button>` element by default (instead of `<a>`), as it's the recommended way.
[Trello card](https://trello.com/c/fJPJoRJm)
---
https://govuk-publishing-compon-pr-579.herokuapp.com/component-guide/button

Fix focus colour for buttons

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Add option to send the `user_organisation` in admin analytics component (PR #577)
* Add a bottom margin to the error-alert component (PR #578)
* Update the way we include Javascript and Stylesheets in the admin layout
component. Make sure to follow the [installation instructions](docs/install-and-use.md) (PR #571) if your using the admin layout component.
* Fix background colour for focused buttons (PR #579)
---

Release 12.1.0

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/govspeak/_button.scss
app/assets/stylesheets/govuk_publishing_components/components/govspeak/_typography.scss

This PR fixes the styles applied to a button inside a govspeak section and allows the button to be styled using the `govuk-frontend` selectors.
Default
Focus
Default
Focus
---
https://govuk-publishing-compon-pr-582.herokuapp.com/component-guide/govspeak

Fix govspeak button

---

CHANGELOG.md
app/assets/javascripts/govuk_publishing_components/components/character-count.js
app/assets/stylesheets/govuk_publishing_components/_all_components.scss
app/assets/stylesheets/govuk_publishing_components/components/_character-count.scss
app/views/govuk_publishing_components/components/_character_count.html.erb
app/views/govuk_publishing_components/components/_textarea.html.erb
app/views/govuk_publishing_components/components/docs/character_count.yml
package-lock.json
package.json
spec/components/character_count_spec.rb

This PR:
- updates the gem to use govuk-frontend 2.2.0
- adds the new character count component from govuk-frontend
---
https://govuk-publishing-compon-pr-583.herokuapp.com/component-guide/character_count

Add character count component

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/_all_components.scss
app/assets/stylesheets/govuk_publishing_components/components/_warning-text.scss
app/views/govuk_publishing_components/components/_warning_text.html.erb
app/views/govuk_publishing_components/components/docs/warning_text.yml
spec/components/warning_text_spec.rb

Part of:
https://trello.com/c/UrJYOEVF
Design System has a [warning text component](https://design-system.service.gov.uk/components/warning-text/). We should add this component in the shared library (govuk_publishing_components).
Ticket: https://trello.com/c/lJ9w813f/351-add-warning-text-component
---
https://govuk-publishing-compon-pr-588.herokuapp.com/component-guide/

Adds warning text from design systems

---

CHANGELOG.md
lib/govuk_publishing_components/presenters/machine_readable/page.rb
spec/components/machine_readable_metadata_spec.rb

As described in https://github.com/alphagov/govuk-content-schemas/pull/827, we currently expose the image from the page to social media scrapers using this component. This image is often quite small, and unsuitable for services like Twitter.
Whitehall will soon be sending a higher resolution image in `details.image`. This PR makes sure that we use it if it's present.
https://trello.com/c/eqcMykln

Expose the high resolution image in meta tags

---

CHANGELOG.md
app/assets/javascripts/govuk_publishing_components/components/checkboxes.js
app/assets/stylesheets/govuk_publishing_components/_all_components.scss
app/assets/stylesheets/govuk_publishing_components/components/_checkboxes.scss
app/views/govuk_publishing_components/components/_checkboxes.html.erb
app/views/govuk_publishing_components/components/docs/checkboxes.yml
spec/components/checkboxes_spec.rb

https://trello.com/c/V91W6SoB/350-add-checkboxes-component-to-support-attachment-and-taxonomy-workflow
Part of:
https://trello.com/c/Rzd8bdIp
https://trello.com/c/UrJYOEVF
Design System has a [checkboxes component](https://design-system.service.gov.uk/components/checkboxes/). We should add this component in the shared library (govuk_publishing_components) and automatically initialise it using `data-module` attribute.
## Screenshot
---
https://govuk-publishing-compon-pr-590.herokuapp.com/component-guide/

add checkboxes from design systems

---

spec/lib/presenters/schema_org_spec.rb

This was causing downstream failures because govuk_schemas [validates random schemas that have a block applied](https://github.com/alphagov/govuk_schemas/blob/f709a10cd2af63b29c22288fc7e0ad6af426926a/lib/govuk_schemas/random_example.rb#L88).  We're only overriding simple things to assert against here, and the schema tests to validate examples are run elsewhere.
No changelog necessary for this as it affects tests only.

Skip full validation of an org schema

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/_all_components.scss
app/assets/stylesheets/govuk_publishing_components/components/_breadcrumbs.scss
app/views/govuk_publishing_components/components/_breadcrumbs.html.erb
spec/components/breadcrumbs_spec.rb

Part of:
https://trello.com/c/UrJYOEVF
The breadcrumbs component in govuk_publishing_components need to be updated to use govuk-frontend code
Ticket: https://trello.com/c/PXQahpcq/357-update-breadcrumb-component
The only difference between the current component and this update is that previously there was no underline for items which had a link to `#content` on the current page. The new design systems standards show all links with an underline styling.
Also important to notice that I've had to include media-down mixin globally as it was being used by a lot of govspeak helpers but not actually required in these files.
---
https://govuk-publishing-compon-pr-593.herokuapp.com/component-guide/

Updates current breadcrumbs to use design systems

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/_image-card.scss

Trello: https://trello.com/c/QT5ZEcF7/124-bug-expand-image-card-component-to-handle-smaller-images
This tweaks the CSS for the image card large example so that it now handles smaller images more gracefully. This is needed for [one of the topic page MV variants](https://trello.com/c/5hFNt9yn/43-build-in-page-navigation-element). Previously, there would have been a large gap between the small image and the text. Now, the text expands to fill the rest of the space not taken up by the image.
This was tested on an organisation page to ensure it behaves in the same way where the component has already been used.
Component Guide: https://govuk-publishing-compon-pr-605.herokuapp.com/component-guide/image_card/large_version

Handle smaller images in image card large

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Updates current breadcrumbs components to be based on GOV.UK Frontend (PR #593)
* Expands image card component to handle smaller images gracefully (PR #605)
https://govuk-publishing-compon-pr-607.herokuapp.com/component-guide/

Bump version to 12.4.0

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_feedback.html.erb

We have a problem where bots are filling in the feedback component and skewing the results. The theory here is that they are clicking on the first link, so we're introducing a new hidden first link called 'Maybe'.
I haven't added support for JavaScript so if a user were to click it, it would always make a normal browser request. I figure this is fine since we're targeting bots.
https://govuk-publishing-compon-pr-608.herokuapp.com/component-guide/
[Trello Card](https://trello.com/c/4Yo6hC5c/592-set-up-a-honeypot-to-catch-link-clicking-bots)

Add a maybe button to the feedback component

---

CHANGELOG.md
lib/govuk_publishing_components/version.rb

Updates gem version to 12.6
---
https://govuk-publishing-compon-pr-612.herokuapp.com/component-guide/

Bump version number to 12.6

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/_phase-banner.scss
app/views/govuk_publishing_components/components/_phase_banner.html.erb
app/views/govuk_publishing_components/components/docs/phase_banner.yml
spec/components/phase_banner_spec.rb

Phase banner now uses design systems and adds app name support
https://design-system.service.gov.uk/components/phase-banner/
Needed for:
https://trello.com/c/6hvQZTVK/259-update-navigation-header
---
https://govuk-publishing-compon-pr-613.herokuapp.com/component-guide/phase_banner

Phase banner now uses design systems and adds app name support

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_layout_header.html.erb
app/views/govuk_publishing_components/components/docs/layout_header.yml
spec/components/layout_header_spec.rb

Allows layout header to go full width when passed a parameter.
---
https://govuk-publishing-compon-pr-616.herokuapp.com/component-guide/

Add the ability for the layout header to go full width

---

app/assets/stylesheets/govuk_publishing_components/_all_components.scss

Add govspeak-html-publication to _all_components
In some documents with document type `html_publication`, rendered by
`government-frontend`, the correct css styling was not applied because
we were not importing the `govspeak-html-publication` component.
Trello: https://trello.com/c/wPyyRRfH/634-table-styling-on-2018-budget-query-from-hm-treasury
---
https://govuk-publishing-compon-pr-618.herokuapp.com/component-guide/

Add govspeak-html-publication to _all_components

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_error_summary.html.erb
app/views/govuk_publishing_components/components/_file_upload.html.erb
app/views/govuk_publishing_components/components/_input.html.erb
app/views/govuk_publishing_components/components/_radio.html.erb
app/views/govuk_publishing_components/components/_textarea.html.erb
app/views/govuk_publishing_components/components/docs/error_summary.yml
app/views/govuk_publishing_components/components/docs/file_upload.yml
app/views/govuk_publishing_components/components/docs/input.yml
app/views/govuk_publishing_components/components/docs/radio.yml
app/views/govuk_publishing_components/components/docs/textarea.yml
spec/components/error_summary_spec.rb
spec/components/file_upload_spec.rb
spec/components/input_spec.rb
spec/components/radio_spec.rb
spec/components/textarea_spec.rb

https://trello.com/c/4iKDzhBY/417-separate-saving-a-change-from-the-creation-of-a-preview
Currently we support an 'error_message' on a form field, but sometimes a
field can have multiple errors. This adds an alternative 'error_items'
option to the input, textarea, radio and file upload components to
support multiple errors as items of the error summary component.
---

Support multiple errors in form fields

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_checkboxes.html.erb
app/views/govuk_publishing_components/components/docs/checkboxes.yml
spec/components/checkboxes_spec.rb

Add option to checkboxes to allow preselected items
---
https://govuk-publishing-compon-pr-623.herokuapp.com/component-guide/checkboxes/checkbox_items_with_checked_items

Add option to checkboxes to allow preselected items

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_file_upload.html.erb
app/views/govuk_publishing_components/components/_input.html.erb
app/views/govuk_publishing_components/components/_radio.html.erb
app/views/govuk_publishing_components/components/_textarea.html.erb
app/views/govuk_publishing_components/components/docs/file_upload.yml
app/views/govuk_publishing_components/components/docs/input.yml
app/views/govuk_publishing_components/components/docs/radio.yml
app/views/govuk_publishing_components/components/docs/textarea.yml
spec/components/file_upload_spec.rb
spec/components/input_spec.rb
spec/components/radio_spec.rb
spec/components/textarea_spec.rb

Previously we used the error_summary component to render multiple error
items for form fields. Unfortunately this had the udesirable consequence
of showing a big red box around the errors. This changes the approach to
instead concatenate the errors into a single error_message, separated
with "\<br/\>" tags.

Use error_message to render multiple field errors

---

CHANGELOG.md
app/assets/javascripts/govuk_publishing_components/components/checkboxes.js
app/assets/stylesheets/govuk_publishing_components/components/_checkbox.scss
app/assets/stylesheets/govuk_publishing_components/components/_checkboxes.scss
app/views/govuk_publishing_components/components/_checkbox.html.erb
app/views/govuk_publishing_components/components/_checkboxes.html.erb
app/views/govuk_publishing_components/components/docs/checkbox.yml
app/views/govuk_publishing_components/components/docs/checkboxes.yml
spec/components/checkbox_spec.rb
spec/components/checkboxes_spec.rb
spec/javascripts/components/checkboxes-spec.js

- Adds functionality to allow nested checkboxes
- Separates out checkboxes into their own component.
https://govuk-publishing-compon-pr-626.herokuapp.com/component-guide/checkbox
https://govuk-publishing-compon-pr-626.herokuapp.com/component-guide/checkboxes

Add support for nested check boxes

---

app/views/govuk_publishing_components/components/_checkboxes.html.erb
app/views/govuk_publishing_components/components/docs/checkboxes.yml
spec/components/checkboxes_spec.rb

The legend in the checkboxes' fieldset should contain plaintext unless specified, to match the pattern in the GOV.UK Design System:
---
https://govuk-publishing-compon-pr-630.herokuapp.com/component-guide/

Make h1 in legend optional

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_back_link.html.erb
app/views/govuk_publishing_components/components/_panel.html.erb
app/views/govuk_publishing_components/components/docs/back_link.yml
app/views/govuk_publishing_components/components/docs/panel.yml

We need to display custom text on the back link component and this
changes that to allow text to be injected.
The panel component should not render a div for the description if there
isn't one, this fixes that.
---
https://govuk-publishing-compon-pr-628.herokuapp.com/component-guide/

Update back link and panel components

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Corrects name for checkboxes documentation (PR #638)
---
https://govuk-publishing-compon-pr-639.herokuapp.com/component-guide/

bump version to 12.12.1

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_radio.html.erb
app/views/govuk_publishing_components/components/docs/radio.yml
spec/components/radio_spec.rb

Adds the following options to the radio component:
- heading text (adds a legend that looks like a heading)
- is page heading (makes the heading into a H1)
With heading:
With heading as page heading:
---
Trello card: https://trello.com/c/8Z3BCpTU/79-let-radio-component-have-its-legend-as-the-page-heading-and-have-hint-text
https://govuk-publishing-compon-pr-635.herokuapp.com/component-guide/radio

Add heading options to radio component

---

CHANGELOG.md
spec/javascripts/components/checkboxes-spec.js

The nested checkboxes use JavaScript for their associated behaviours.
This adds the tests left as 'to do' in https://github.com/alphagov/govuk_publishing_components/pull/626
---
https://govuk-publishing-compon-pr-636.herokuapp.com/component-guide/

Add tests for checkbox JS

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

Brings in the following changes:
- https://github.com/alphagov/govuk_publishing_components/pull/635
- https://github.com/alphagov/govuk_publishing_components/pull/636
---
https://govuk-publishing-compon-pr-637.herokuapp.com/component-guide/

Bump version to 12.13.0

---

CHANGELOG.md
app/assets/javascripts/govuk_publishing_components/components/accessible-autocomplete.js
app/assets/stylesheets/govuk_publishing_components/_all_components.scss
app/assets/stylesheets/govuk_publishing_components/components/_accessible-autocomplete.scss
app/views/govuk_publishing_components/components/_accessible_autocomplete.html.erb
app/views/govuk_publishing_components/components/docs/accessible_autocomplete.yml
config/initializers/assets.rb
package-lock.json
package.json
spec/components/accessible_autocomplete_spec.rb

This PR adds a new _accessible autocomplete_ component to the publishing components, using the existing accessible autocomplete at https://alphagov.github.io/accessible-autocomplete. 
The new component here adds a label alongside the autocomplete, in addition to support for tracking _if this is specifically enabled_ when creating the component.
No JS tests are included as they would be testing the functionality which has already been tested by the existing autocomplete component, and which can be seen at https://github.com/alphagov/accessible-autocomplete/tree/master/test.
This PR has been demoed to @alex-ju (before the PR was created). It was mentioned that the module system will be retired in the future, but until then the new module created in this PR can remain.
Co-authored-by: Mahmud …

T143 accessible autocomplete

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

Update changelog to reflect release of new autocomplete component.
Version number is updated from `12.13.0` to `12.14.0`.

Bump to version 12.14.0

---

app/views/govuk_publishing_components/components/_checkbox.html.erb

Having the `label` tag inside a code block within the `input` tag makes
the generated html have the `label` element wrapped inside an `input`
element.
This occurs when running `bundle exec rake default` in `finder-frontend`
(which is the command the Jenkins runs). Running `bundle exec cucumber`
does not present the same issue.
The problematic `input` element has both an opening tag and a closing
tag, causing parsing errors in strict mode in this `slimmer` method:
```
def parse_html(html, description_for_error_message)
doc = Nokogiri::HTML.parse(html)
if strict
errors = doc.errors.select {|e| e.error?}.reject {|e| ignorable?(e)}
if errors.size > 0
error = errors.first
message = "In #{description_for_error_message}: '#{error.message}' 
at line #{error.line} col #{error.column} (code …
```

Remove checkbox label from inside code block

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/_textarea.scss
app/views/govuk_publishing_components/components/_textarea.html.erb
app/views/govuk_publishing_components/components/docs/textarea.yml

Trello: https://trello.com/c/M3d7G6YG/501-iterate-character-count-text-and-rules
This adds two new features to the textarea component:
- [Ability to embed extra content into the textarea component formgroup](https://govuk-publishing-compon-pr-649.herokuapp.com/component-guide/textarea/with_extra_elements)
- [Set a maxlength on the textarea](https://govuk-publishing-compon-pr-649.herokuapp.com/component-guide/textarea/with_maxlength)
We intend to use these in content-publisher like so:
```
<%= render "govuk_publishing_components/components/textarea", {
label: {
text: t("documents.edit.form_labels.summary"),
bold: true
},
id: "document_summary",
name: "document[summary]",
value: @document.summary,
rows: 4,
maxlength: 600,
data: {
"contextual-guidance": "document-summary-guidance"
}
} do %> …
```

Iterate textarea component

---

app/assets/javascripts/govuk_publishing_components/components/checkbox.js
app/assets/stylesheets/govuk_publishing_components/_all_components.scss
app/assets/stylesheets/govuk_publishing_components/components/_checkbox.scss
app/assets/stylesheets/govuk_publishing_components/components/_checkboxes.scss
app/views/govuk_publishing_components/components/_checkbox.html.erb
app/views/govuk_publishing_components/components/_checkboxes.html.erb
app/views/govuk_publishing_components/components/_input.html.erb
app/views/govuk_publishing_components/components/docs/checkbox.yml
app/views/govuk_publishing_components/components/docs/checkboxes.yml
app/views/govuk_publishing_components/components/docs/input.yml
spec/components/checkbox_spec.rb
spec/components/checkboxes_spec.rb
spec/components/input_spec.rb
spec/javascripts/components/checkbox-spec.js
spec/javascripts/components/checkboxes-spec.js

We want to use components for form fields in finders, which requires some changes to components to support this. Specifically:
- input component needs `aria-controls` attribute option
- input component needs `id` option (turns out this was already present, but not documented)
- change how `id` option works in checkbox
- add `data-attributes` option to checkbox
- add `aria-controls` option to checkbox using Javascript to apply
- add `margin-bottom` option to checkbox
---
Trello card: https://trello.com/c/fhhTwfLo/178-use-form-element-components-in-finders
https://govuk-publishing-compon-pr-643.herokuapp.com/component-guide/

Update components for finders

---

app/views/govuk_publishing_components/components/_select.html.erb
app/views/govuk_publishing_components/components/docs/select.yml
lib/govuk_publishing_components.rb
lib/govuk_publishing_components/presenters/select.rb
spec/components/select_spec.rb

Adds the ability to pass arbitrary data attributes to the select component, that will be applied to the individual options.
---
https://govuk-publishing-compon-pr-650.herokuapp.com/component-guide/select
Trello card: https://trello.com/c/CF6DmPXk/137-add-sorting-to-the-news-and-communications-finder

Add data attributes to select component

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/_warning-text.scss
app/views/govuk_publishing_components/components/_warning_text.html.erb
app/views/govuk_publishing_components/components/docs/warning_text.yml
spec/components/warning_text_spec.rb

Modify the warning text component so that it:
- doesn't have to have an icon
- has an option to have larger text
- has an option to have highlighted (i.e. red) text
---
https://govuk-publishing-compon-pr-655.herokuapp.com/component-guide/warning_text

Modify warning text component

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/_metadata.scss
app/views/govuk_publishing_components/components/_metadata.html.erb
app/views/govuk_publishing_components/components/docs/metadata.yml
spec/components/metadata_spec.rb

Adds an option to the metadata component so that it can be used on a dark background, such as on pages like:
- https://www.gov.uk/hmrc-internal-manuals/pensions-tax-manual
- https://www.gov.uk/guidance/prevent-groundwater-pollution-from-underground-fuel-storage-tanks
Once this PR has been merged and the gem re-versioned, we can update manuals-frontend to use this option and remove the fix added in https://github.com/alphagov/manuals-frontend/pull/531
---
https://govuk-publishing-compon-pr-657.herokuapp.com/component-guide/metadata/on_a_dark_background

Add inverse option to metadata component

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_copy_to_clipboard.html.erb
app/views/govuk_publishing_components/components/_details.html.erb
app/views/govuk_publishing_components/components/_tabs.html.erb
app/views/govuk_publishing_components/components/docs/copy_to_clipboard.yml
app/views/govuk_publishing_components/components/docs/details.yml
app/views/govuk_publishing_components/components/docs/tabs.yml

Trello: https://trello.com/c/yRnJfrDN/487-deployment-of-remaining-data-attributes-for-consistent-event-tracking-in-gtm
These have been requested by the PA on Publishing Workflow, Andy, for
integrating with google-tag-manager.
https://govuk-publishing-compon-pr-660.herokuapp.com/component-guide/

Support data attributes on copy-to-clipboard, details and tabs components

---

package-lock.json
package.json

Update to govuk-frontend 2.4
See [GOV.UK Frontend changelog](https://github.com/alphagov/govuk-frontend/releases) for details.
Can someone with access to dependabot account help me setup an integration or webhook for govuk-frontend on this repository?
https://govuk-publishing-compon-pr-656.herokuapp.com/component-guide

Update to govuk-frontend 2.4

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_error_alert.html.erb
app/views/govuk_publishing_components/components/_error_summary.html.erb
app/views/govuk_publishing_components/components/docs/error_alert.yml
app/views/govuk_publishing_components/components/docs/error_summary.yml

This is another that is hoped to be tracked by Google Tag Manager for
which we need to inject data attributes.
---
https://govuk-publishing-compon-pr-662.herokuapp.com/component-guide/

Add data attributes to error alert and error summary

---

app/assets/stylesheets/govuk_publishing_components/components/_image-card.scss

Spoke with @markhurrell and we don't want a custom `line-height` for these elements on image-card. I'm fine with the change.
---
https://govuk-publishing-compon-pr-665.herokuapp.com/component-guide/image_card

Remove line-height on description and list

---

app/views/govuk_publishing_components/components/_layout_footer.html.erb
app/views/govuk_publishing_components/components/docs/layout_footer.yml
spec/components/layout_footer_spec.rb

https://trello.com/c/TiZgaPxw/537-open-support-links-in-a-new-tab
Enhancing the layout footer component so that it can make pressing a link open a new window
or change the page of the current window.
- Making use of link_to in _layout_footer.html.erb to handle the target attribute and
explicitly setting target to '' if no target attribute is passed to the component.
- Adding a new example to layout_footer.yml so users can see examples of using the
layout footer component to open links in either the same or a new window.

Make layout footer support spawning new windows for links

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_contextual_breadcrumbs.html.erb
app/views/govuk_publishing_components/components/_contextual_sidebar.html.erb
spec/dummy/app/views/layouts/dummy_admin_layout.html.erb

Comments are only needed to help comprehension of the template code,
they're not needed when templates are used to render HTML view code.
---
https://govuk-publishing-compon-pr-667.herokuapp.com/component-guide/

Use ERB comments not HTML comments in template markup

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_input.html.erb
app/views/govuk_publishing_components/components/docs/input.yml
spec/components/input_spec.rb

Trello: https://trello.com/c/hGmJ5BfV
Content Publisher allows publishers to add an image credit. The intention is to limit the number of characters publishers can use in the image credit.
Sets a maxlength attribute in a similar way to textarea.
---
https://govuk-publishing-compon-pr-670.herokuapp.com/component-guide/

Add optional maxlength to input fields

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/_accessible-autocomplete.scss

Arrow was not appearing on autocomplete, even though we're using the `showAllValues` option - see [autocomplete examples](https://alphagov.github.io/accessible-autocomplete/examples/).
This change fixes this by increasing the z-index on both the arrow svg and the input, so the arrow is visible but does not overlap the click area of the input.
Fixes this:
...to this:
---
https://govuk-publishing-compon-pr-671.herokuapp.com/component-guide/accessible_autocomplete

Fix autocomplete styles

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

**Note that this version contains a potentially breaking change, the removal of the checkbox component.**
* Encode feedback component to ensure UTF-8 characters are rendered (PR #673)
* Fix autocomplete styles (PR #671)
* BREAKING: Merge checkbox components (PR #659)
* Accept a maxlength attribute for input (PR #670)
---
https://govuk-publishing-compon-pr-674.herokuapp.com/component-guide/

Version 13.0.0

---

CHANGELOG.md
Gemfile.lock
app/assets/javascripts/govuk_publishing_components/components/accessible-autocomplete.js

This is necessary for us to use the accessible-autocomplete component in finder-frontend (related PR: https://github.com/alphagov/finder-frontend/pull/740)
For more details see [finder-frontend PR #740](https://github.com/alphagov/finder-frontend/pull/740)
Trello: https://trello.com/c/fkbJr5kX/173-add-autocomplete-to-finders
---
https://govuk-publishing-compon-pr-666.herokuapp.com/component-guide/

Triggers select changed event when onConfirm is called

---

app/views/govuk_publishing_components/components/_feedback.html.erb
spec/components/feedback_spec.rb

There is some potential, especially in tests, for these to be nil
which would throw errors when attempting to encode them to UTF-8.
Now we only encode if we are sure they are strings.
Paired with @Rosa-Fox 
---
https://govuk-publishing-compon-pr-677.herokuapp.com/component-guide/

Add guard for user agent and url being nil in feedback

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/_checkboxes.scss

This changes a style in the checkboxes component relating to hints to limit it to just the checkboxes component. Previously it was too generic and was affecting the text input component as well.
--------
This rule was used in checkboxes in this context...
Here the default margin bottom of 10px on the hints was needed to be removed because these nested checkboxes are already wrapped in a list item that has its own 10px margin bottom. Without this rule if the last nested checkbox had a hint the margin on it gave an extra 10px to the overall margin of the component, changing it from 30px to 40px.
Unfortunately this rule wasn't scoped to the checkboxes component, so it affected the text input as well, making it look like this:
...when it's supposed to look like this:
---
Component guide for …

Limit hint styles to checkboxes

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/_checkboxes.scss
app/views/govuk_publishing_components/components/_checkboxes.html.erb
app/views/govuk_publishing_components/components/docs/checkboxes.yml
lib/govuk_publishing_components/presenters/checkboxes_helper.rb
spec/components/checkboxes_spec.rb

This PR changes the checkboxes component as follows:
- makes the heading (legend) text option mandatory, without which the component will fail to render, as this is an accessibility violation
- provides an option to make the heading (legend) visually hidden if not required
- provides an option to make hint text optional
---
https://govuk-publishing-compon-pr-684.herokuapp.com/component-guide/checkboxes

Change heading/legend/hint options on checkboxes component

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_checkboxes.html.erb
app/views/govuk_publishing_components/components/docs/checkboxes.yml
lib/govuk_publishing_components/presenters/checkboxes_helper.rb
spec/components/checkboxes_spec.rb

- there is a requirement to have a heading/legend on a single checkbox, so if a heading is passed, render it
---
https://govuk-publishing-compon-pr-686.herokuapp.com/component-guide/checkboxes

Allow heading on single checkbox

---

lib/govuk_publishing_components/presenters/machine_readable/article_schema.rb
spec/lib/presenters/schema_org_spec.rb

A topic is more of a "Thing" than it is a "CreativeWork". I'm not sure what difference this will actually make, but it seems conceptually better to me.
I think this is small enough to not need an entry in the change log

Tweak "about" in Article schema

---

lib/govuk_publishing_components/presenters/machine_readable/organisation_schema.rb
spec/lib/presenters/schema_org_spec.rb

They contain the same text, but the body contains markup which is possibly best to avoid for schema text.
The description is not always populated at present, so we still allow fallback.
Related to https://github.com/alphagov/whitehall/pull/4569

Org schemas: prefer description over body

---

CHANGELOG.md
app/assets/javascripts/govuk_publishing_components/components/accessible-autocomplete.js

Use of the accessible autocomplete component in finders required a custom onConfirm function, which was [causing this problem](https://github.com/alphagov/accessible-autocomplete/issues/322).
However, this change was causing the value of the hidden select to be reset to nothing when the blur event occurred on the autocomplete. This PR adds a check to only update the value of the select if the value is not undefined.
This change is necessary for https://github.com/alphagov/finder-frontend/pull/740
---
https://govuk-publishing-compon-pr-693.herokuapp.com/component-guide/accessible_autocomplete

Add value check to accessible autocomplete custom onConfirm function

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_accessible_autocomplete.html.erb
app/views/govuk_publishing_components/components/docs/accessible_autocomplete.yml

The accessible autocomplete component is now being used in finders. When Javascript is disabled it falls back to displaying a standard select element. Unfortunately this is unstyled, so it can look like this...
**Before**
This PR adds the `govuk-select` style to these selects, so they look a lot better when JS is disabled:
**After**
I tried to use the existing select component inside the autocomplete component to achieve this, but the options available on that component weren't compatible, so it seemed simpler to just add the class, as I've done.
---
https://govuk-publishing-compon-pr-695.herokuapp.com/component-guide/accessible_autocomplete

Improve autocomplete appearance without js

---

CHANGELOG.md
app/assets/javascripts/govuk_publishing_components/components/select.js
app/views/govuk_publishing_components/components/_select.html.erb
app/views/govuk_publishing_components/components/docs/select.yml
lib/govuk_publishing_components/presenters/select.rb
spec/components/select_spec.rb
spec/javascripts/components/select-spec.js

Trello: https://trello.com/c/5iPpo7IR/193-add-tracking-to-topic-subtopic-facet
Enables tracking on the select component if track_category and track_action passed.
https://govuk-publishing-compon-pr-690.herokuapp.com/component-guide/select

Add tracking to select component

---

app/views/govuk_publishing_components/components/_feedback.html.erb
spec/components/feedback_spec.rb
spec/javascripts/components/feedback-spec.js

This removes the `user_agent` from the problem report form that the user sees when clicking "Is there anything wrong with this page".
Like https://github.com/alphagov/govuk_publishing_components/pull/698, this is wrong because the page will be cached, so that any subsequent page requests will return the same HTML with the same form fields - and the previous request's user agent.
We can remove this field, because it turns out that the feedback application merges the sent `params` with `technical_attributes`, which [includes the correct user_agent](https://github.com/alphagov/feedback/blob/6f74a9a2887ceff3302a4e8f425aff715dbc3e4a/app/controllers/contact/govuk/problem_reports_controller.rb#L9).
I've confirmed this by creating a ticket with a spoofed UA and checking the support-api database …

Don't send user_agent in problem reports

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/_layout-header.scss
app/views/govuk_publishing_components/components/_layout_header.html.erb
app/views/govuk_publishing_components/components/docs/layout_header.yml
spec/components/layout_header_spec.rb

Needed for https://github.com/alphagov/content-publisher/pull/647
On the content publisher app there are two navigations, primary (layout_header component) and secondary (phase banner component).
On mobile view the phase banner hides the navigation items, however, these still need to be accessible for mobile users. Therefore, we need to add them to the primary navigation bar and hide them unless it's on mobile.
---
https://govuk-publishing-compon-pr-691.herokuapp.com/component-guide/

allow navigation items to only show in collapsed menu

---

app/views/govuk_publishing_components/components/_feedback.html.erb
app/views/govuk_publishing_components/components/feedback/_problem_form.html.erb
app/views/govuk_publishing_components/components/feedback/_survey_signup_form.html.erb

These were actually misnamed in the original PR: the `url_without_pii` was the `path_without_pii`, and the reverse.

Clarify variable names for feedback component

---

lib/govuk_publishing_components/presenters/meta_tags.rb
spec/components/meta_tags_spec.rb

These 2 supertypes aren't used anymore, and are out of date because we're no longer using the supertypes from the content item anymore.
https://trello.com/c/hp5BJD2i

Stop populating meta tags with outdated supertypes

---

app/views/govuk_publishing_components/components/docs/related_navigation.yml
lib/govuk_publishing_components/presenters/related_navigation_helper.rb

The use of keyword arguments was preventing the component guide working.
This was introduced in #606
---
https://govuk-publishing-compon-pr-710.herokuapp.com/component-guide/

Make the related navigation helper compatible with the component guide

---

CHANGELOG.md
app/assets/javascripts/govuk_publishing_components/dependencies.js
app/assets/javascripts/govuk_publishing_components/lib/toggle.js
spec/javascripts/components/toggle-spec.js

Adds a new option to the `gem-toggle` Javascript module, allowing a class to be passed that will be used in the toggle, in place of the default `js-hidden` class. 
Needed for [finders](https://trello.com/c/HeKk9mpK/192-add-progressive-disclosure-to-facets-on-mobile), where I need to toggle the display of facets, but only on mobile. If we use the default `js-hidden` class, the toggle functionality is there on desktop as well, and we don't want that.
Also linted some files, recommend this be reviewed commit by commit.
---
https://govuk-publishing-compon-pr-712.herokuapp.com/component-guide/

Extend toggle module

---

CHANGELOG.md
app/views/govuk_publishing_components/components/docs/button.yml
lib/govuk_publishing_components/presenters/button_helper.rb
spec/components/button_spec.rb

Add an option to the button component to specify the button `type`. Currently defaults to submit (unless it's a link).
---
https://govuk-publishing-compon-pr-711.herokuapp.com/component-guide/button

Add type option to button component

---

app/views/govuk_publishing_components/components/_feedback.html.erb
app/views/govuk_publishing_components/components/feedback/_survey_signup_form.html.erb

At present we send the full URL to the feedback application as `survey_source`. This is unnecessary because the domain is stripped off anyway in the feedback app:
https://github.com/alphagov/feedback/blob/b7b0e84bb4d5d85218e2499cf8ecac19e28e5f3e/app/models/email_survey_signup.rb#L31
Using the path here should prevent some errors where we're rejecting submissions because `survey_source` is an integration or staging URL.

Send path instead of URL to feedback

---

CHANGELOG.md
app/assets/javascripts/govuk_publishing_components/components/accessible-autocomplete.js
app/assets/stylesheets/govuk_publishing_components/components/_accessible-autocomplete.scss

In finder-frontend we have facet tags that appear above search results when users choose search options. The intended functionality is that clicking on these facet tags will remove them from the search, updating the search results and clearing the relevant input.
This is complicated in the case of accessible autocompletes as the code is imported and doesn't have any hooks for doing this externally. Problems:
- externally clearing the value of the autocomplete causes the drop down of suggestions to appear and we can't access the code that controls that
- simulating a user click in the 0th drop down item would work, but it shifts the focus back to the autocomplete, which is confusing
Solution:
- attach our custom `onConfirm` function to the autocomplete's (hidden) select element, so it can …

Extend accessible autocomplete onConfirm function

---

CHANGELOG.md
app/assets/javascripts/govuk_publishing_components/components/accordion.js
app/assets/stylesheets/govuk_publishing_components/_all_components.scss
app/assets/stylesheets/govuk_publishing_components/_all_components_print.scss
app/assets/stylesheets/govuk_publishing_components/components/_accordion.scss
app/assets/stylesheets/govuk_publishing_components/components/print/_accordion.scss
app/views/govuk_publishing_components/components/_accordion.html.erb
app/views/govuk_publishing_components/components/docs/accordion.yml
lib/govuk_publishing_components.rb
lib/govuk_publishing_components/presenters/accordion_helper.rb
package-lock.json
package.json
spec/components/accordion_spec.rb

Adds the Accordion component based on GOV.UK Frontend.
[Card](https://trello.com/c/9KTI0qjV/577-add-accordion-component-as-a-component-and-use-it-for-markdown-styleguide).
This component is required by Content Publisher to hide and show the Govspeak guidance.
---
https://govuk-publishing-compon-pr-714.herokuapp.com/component-guide/accordion/

Add accordion component

---

app/assets/javascripts/govuk_publishing_components/components/accessible-autocomplete.js
spec/javascripts/components/accessible-autocomplete-spec.js

**Third attempt, something is broken with the [previous attempt](https://github.com/alphagov/govuk_publishing_components/pull/715)**
Adds some tests for the accessible autocomplete component. Needed as we have a custom `onConfirm` function that handles tracking and the updating of the hidden select element (we are using the `enhanceSelectElement` [option](https://github.com/alphagov/accessible-autocomplete#progressive-enhancement) in the autocomplete).
---
https://govuk-publishing-compon-pr-716.herokuapp.com/component-guide/accessible_autocomplete/
Trello card: https://trello.com/c/ESZNN5uU/274-add-tests-for-the-autocomplete-component

Add tests for the accessible autocomplete component

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

Includes:
* Extend accessible autocomplete onConfirm function (PR #718)
* Add Accordion component based on GOV.UK Frontend (PR #714)
* Add type option to button component (PR #711)
---
https://govuk-publishing-compon-pr-721.herokuapp.com/component-guide/

Version 13.7.0

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_contextual_breadcrumbs.html.erb
lib/govuk_publishing_components/presenters/contextual_navigation.rb
spec/components/contextual_breadcrumbs_spec.rb

This PR stops the contextual breadcrumbs component from showing taxonomy breadcrumbs when the content being viewed is a specialist document. This allows the content item's finder to be displayed instead, for which the logic already exists in the `breadcrumbs` method of `contextual_navigation.rb`. By making this change, we allow users to more easily navigate to the correct specialist finder if they come from somewhere other than a specialist finder.
Note that if `prioritise_taxon_breadcrumbs` is specified and set to `true` as part of instantiating the contextual breadcrumbs component, it is possible to override the above behaviour.
Solo: @karlbaker02
Example: for a specialist doc at https://www.gov.uk/cma-cases/funerals-market-study
Before:
After:
--- …

Show finder breadcrumb for specialist documents

---

CHANGELOG.md
app/assets/javascripts/govuk_publishing_components/components/accessible-autocomplete.js

Fix autocomplete js:
This fixes an issue where ampersands (and other characters) could not be
matched in the select box, resulting in an empty selection. This failed
silently in the background so the user was submitting blank choices they
were not aware of.
---
https://govuk-publishing-compon-pr-728.herokuapp.com/component-guide/

Fix accessible autocomplete so it can handle HTML entities

---

Gemfile.lock
lib/govuk_publishing_components/version.rb

Bumping gem for bugfix on ampersands in the Accessible Autocomplete. Updated changelog on previous commit.
---
https://govuk-publishing-compon-pr-730.herokuapp.com/component-guide/

Bump gem to version 13.8.1

---

app/assets/stylesheets/govuk_publishing_components/components/_feedback.scss

The contrast of the focused feedback links doesn't meet WCAG criterion 1.4.3 (minimum contrast).
This changes the contrast to use the same <del>slightly darker colour that is also used for other links, copied from [govuk_template](https://github.com/alphagov/govuk_template/blob/master/source/assets/stylesheets/_accessibility.scss#L62-L65)</del> <ins>black-ish colour that is also used for in the Design System and GOV.UK Frontend</ins>.
https://govuk-publishing-compon-pr-731.herokuapp.com/component-guide/

Increase focus contrast of feedback links

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_hint.html.erb
app/views/govuk_publishing_components/components/docs/hint.yml
spec/components/hint_spec.rb

**This PR cannot be merged until finder-frontend has been updated to use this new option, [coming soon](https://github.com/alphagov/finder-frontend/pull/833)**
This PR removes the option to pass an arbitrary class to the hint component and replaces it with an option to pass a number between 0 and 9 to provide variable bottom margin using the [govuk-frontend spacing classes](http://govuk-frontend-review.herokuapp.com/docs/#settings/spacing-variable-govuk-spacing-points).
This removes the potential loss of isolation for the component and replaces it with an option that provides the functionality for which the class option was intended. 
Places where hint is used:
- finder-frontend (where it is given a a govuk-frontend spacing class)
- file upload component, using the default margin
- …

Add govuk-frontend spacing scale to hint

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* BREAKING: Add govuk-frontend spacing scale to hint (PR #724) (PR already in place to cope with this change, see https://github.com/alphagov/finder-frontend/pull/833)
* Increase focus contrast of feedback links (PR #731)
---
https://govuk-publishing-compon-pr-735.herokuapp.com/component-guide/

Update to version 14.0.0

---

app/views/govuk_publishing_components/components/docs/govspeak.yml

Enabling bold styling for strong tags was done in https://github.com/alphagov/govuk_publishing_components/pull/463 . However, an old component guide example was left behind which is now confusing.
---
https://govuk-publishing-compon-pr-738.herokuapp.com/component-guide/govspeak

Remove old reference to bold_unstyled

---

app/assets/javascripts/component_guide/accessibility-test.js
app/assets/stylesheets/component_guide/application.scss

Some axe summaries include HTML, so by constructing the DOM manually we can avoid any issues.
This also adds some typography improvements and headings
Fixes https://github.com/alphagov/govuk_publishing_components/issues/736
---
https://govuk-publishing-compon-pr-737.herokuapp.com/component-guide/

Reformat output accessibility error to avoid injections

---

CHANGELOG.md
app/assets/javascripts/govuk_publishing_components/components/checkboxes.js
app/views/govuk_publishing_components/components/docs/checkboxes.yml
spec/javascripts/components/checkboxes-spec.js

As checkboxes fire their own tracking event it will be necessary to
remove any custom logic in apps that listens for change events
otherwise it will fire twice.
Trello: https://trello.com/c/l6kGfBhh/230-add-missing-facet-tag-email-alert-tracking-and-checkbox-issue
https://govuk-publishing-compon-pr-729.herokuapp.com/component-guide/

Adds custom event category for checkbox change events. Any app with it's own tracking logic for checkboxes will need to remove it

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* BREAKING: Adds custom event category for checkbox change events. Any app with it's own tracking logic for checkboxes will need to remove it (PR #729)
---
https://govuk-publishing-compon-pr-735.herokuapp.com/component-guide/

Bump to version 15.0.0

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_notice.html.erb
app/views/govuk_publishing_components/components/docs/notice.yml
spec/components/notice_spec.rb

https://trello.com/c/HcfYSpjX/634-allow-notice-component-to-accept-html
Previously only paragraph text or Govspeak could be passed to this
component. This adds a 'description_text' option as an alternative,
which is not nested in any other tag.
As with the Govspeak component, it seems better to require the consumer
of this component to specify that the HTML they're passing-in is safe,
so it was necessary to specify this in the tests.
---

Support rendering raw HTML in notice component

---

app/views/govuk_publishing_components/components/_notice.html.erb
app/views/govuk_publishing_components/components/docs/notice.yml
spec/components/notice_spec.rb

https://trello.com/c/HcfYSpjX/634-allow-notice-component-to-accept-html
Previously the notice component would accept a block in order to set the
description_govspeak variable. Turns out this isn't currently used, and
rendering Govspeak within a component is not consistent with the others.
This changes the notice component to accept a block that will now set
the description_html parameter. As this change increases the importance
of this parameter, it makes sense to rename it to just 'description'.
---

Rename notice description_html to description

---

CHANGELOG.md
app/assets/javascripts/govuk_publishing_components/components/accessible-autocomplete.js
app/assets/stylesheets/govuk_publishing_components/components/_accessible-autocomplete.scss
app/views/govuk_publishing_components/components/_accessible_autocomplete.html.erb
app/views/govuk_publishing_components/components/docs/accessible_autocomplete.yml
config/locales/en.yml
package-lock.json
package.json
spec/components/accessible_autocomplete_spec.rb
spec/javascripts/components/accessible-autocomplete-spec.js

Adds multiple selections as an option to the accessible autocomplete.
This is based on a [branch of the autocomplete](https://github.com/alphagov/accessible-autocomplete/tree/add-multiselect-support) so we probably don't want to merge this PR until we've decided whether that's acceptable or if/how we can get this functionality into the main branch.
---
Trello card: https://trello.com/c/gpTK31dA/183-add-multiple-selection-functionality-to-accessible-autocomplete
https://govuk-publishing-compon-pr-723.herokuapp.com/component-guide/accessible_autocomplete

Add multiple selection option to autocomplete

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_subscription-links.html.erb
app/views/govuk_publishing_components/components/docs/subscription-links.yml
spec/components/subscription_links_spec.rb

Adds a margin option to the subscription links component, using the GOV.UK Frontend spacing scale (as previously applied to the hint component).
Needed for https://github.com/alphagov/finder-frontend/pull/881
Trello card: https://trello.com/c/l40K2yBl/353-use-subscription-component-for-email-alerts-and-rss-feed-signup

Add margin option to subscription links

---

CHANGELOG.md
app/models/govuk_publishing_components/component_doc.rb
app/models/govuk_publishing_components/component_example.rb
app/views/govuk_publishing_components/component_guide/component_doc/_call.html.erb
app/views/govuk_publishing_components/component_guide/component_doc/_component_output.html.erb
docs/component_conventions.md
spec/component_guide/component_example_spec.rb
spec/dummy/app/views/components/_test-component-with-embed.html.erb
spec/dummy/app/views/components/docs/test-component-with-embed.yml

Trello: https://trello.com/c/mHrLEKSK/635-allow-govukpublishingcomponents-to-show-contextual-code-around-an-example
The embed option allows for component examples to be illustrated within
contextual HTML. It is intended for components that do not have a visual
presence without some other HTML. The Content Publisher application has
a number of these, such as Contextual Guidance and Input Length
Suggestor, and is likely to have another for modals. These cannot be
viewed inside the component-guide and just appear as empty boxes.
This resolves this by allowing the ability to include an option of
`embed` in a component document file which contains the HTML that is
needed in the vicinity of the component eg:
```
name: Component
embed: |
<button data-trigger-component=true>Click me</button>
<%= …
```

Allow embed option in component docs

---

Gemfile.lock
govuk_publishing_components.gemspec

This will allow Webmock to work correctly with Ruby 2.6

Bump Webmock 3.0.1 => 3.5.1

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_skip_link.html.erb
app/views/govuk_publishing_components/components/docs/skip_link.yml
config/locales/en.yml
spec/components/skip_link_spec.rb

This commit ensures that the default behaviour for this component creates
a skip link to the main page content. It also allows the developer to
specify the link text should they need to have multiple skip links.
By doing this it also brings this component more inline with
GOV.UK Design System https://design-system.service.gov.uk/components/skip-link/

Update skip-link to allow custom link text

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_government_navigation.html.erb
app/views/govuk_publishing_components/components/docs/layout_footer.yml
spec/components/government_navigation_spec.rb

This will change Announcements to News and communications
throughout govuk. This has already been done in whitehall
with https://github.com/alphagov/whitehall/pull/4636,
so this will make things consistent.
Example page that will change once the version has been
bumped and government-frontend deployed:
https://www.gov.uk/government/news/assets-liquidated-an-unhappy-valentine-for-teesside-crook
https://trello.com/c/7NS3f7I8/378-investigate-why-announcements-link-is-persisting-in-whitehall-header-in-some-places

Change Header link from announcements to news and communications

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_inset_text.html.erb
app/views/govuk_publishing_components/components/_label.html.erb
app/views/govuk_publishing_components/components/_radio.html.erb
app/views/govuk_publishing_components/components/_warning_text.html.erb
app/views/govuk_publishing_components/components/docs/label.yml
spec/components/label_spec.rb

**This PR should not be merged before https://github.com/alphagov/govuk_publishing_components/pull/724 (now merged, so we're okay)**
Removing the ability to pass arbitrary classes to several components, which was potentially damaging to component isolation. Specifically:
- inset text (only appears to be [used in email-alert-frontend](https://github.com/search?q=org%3Aalphagov+govuk_publishing_components%2Fcomponents%2Finset_text&type=Code) where the `classes` option is not used)
- warning text ([doesn't appear to be used anywhere?](https://github.com/search?q=org%3Aalphagov+govuk_publishing_components%2Fcomponents%2Fwarning_text&type=Code))
- label ([used in](https://github.com/search?p=1&q=org%3Aalphagov+govuk_publishing_components%2Fcomponents%2Flabel&type=Code) content publisher …

Remove classes option from components

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/_textarea.scss
app/views/govuk_publishing_components/components/_textarea.html.erb
spec/components/textarea_spec.rb

This PR replaces a custom overwrite for the `magin-bottom` with a custom attribute to set a value from the spacing scale which seems to became a common approach in dealing with spacing for components (see #724, #727).
The reason behind this update is that textarea components should, by default, as the rest of the input form fields, have a `govuk-spacing(3)` set to `margin-bottom`.
~~Tests and changelog to be added.~~

Add a margin_bottom option to textarea component

---

app/views/govuk_publishing_components/components/_details.html.erb
app/views/govuk_publishing_components/components/docs/details.yml
spec/components/details_spec.rb

There are situations when we would want a details element to be open when the page is loaded.

Enable rendering an open details element

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/_accessible-autocomplete.scss
app/views/govuk_publishing_components/components/_accessible_autocomplete.html.erb
app/views/govuk_publishing_components/components/docs/accessible_autocomplete.yml
spec/components/accessible_autocomplete_spec.rb

There was an option in the autocomplete component where when it was in multiple mode you could hide the facet tags that it automatically created. This was done because in finders we already had facet tags of our own, so we didn't need duplicates.
Having investigated this in more detail, we've decided that we don't want this option anymore, as it created an accessibility issue, so we're removing it.

Remove autocomplete hide facets option

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/_error-alert.scss
app/assets/stylesheets/govuk_publishing_components/components/_success-alert.scss

This PR updates `error-alert` and `success-alert` components to use the same `margin-bottom` with `error-summary` component.
Error summary uses responsive-margin bottom of 8, which evens the space between the component and the next elements on the page (e.g. title) with the component and the previous element on the page (e.g. back button).
These two components are only being used by [Signon](https://github.com/alphagov/signon/blob/master/app/assets/stylesheets/application.scss#L3) and Content Publisher and this fixes the spacing in both applications.

Update alert components to use consistent bottom margin

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_radio.html.erb
app/views/govuk_publishing_components/components/docs/radio.yml
spec/components/radio_spec.rb

This change is needed for a PR soon to be opened for content-publisher
in which we need to assign some data attributes to a single radio item
instead of the whole element itself (could contain multile items).
Trello:
https://trello.com/c/pcbHvl7B/636-change-note-guidance

Add ability to add data attributes to a single radio button

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

Enable ability to add data attributes to a single radio button:
https://github.com/alphagov/govuk_publishing_components/pull/766
Trello:
https://trello.com/c/pcbHvl7B/636-change-note-guidance

Release version 16.1.0

---

CHANGELOG.md
app/assets/javascripts/govuk_publishing_components/components/checkboxes.js

Rather than setting up an event handler on every individual checkbox, set up delegated event handlers on the wrapper.
This will significantly reduce the number of event handlers being bound on pages with large numbers of checkboxes (like finder-frontend).

Use delegated event handlers for checkboxes

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_back_link.html.erb
app/views/govuk_publishing_components/components/docs/back_link.yml
spec/components/back_link_spec.rb

https://trello.com/c/jsJLqcSa/667-allow-users-to-edit-image-metadata-in-the-context-of-a-modal

Feed data attributes to back link

---

CHANGELOG.md
app/assets/javascripts/govuk_publishing_components/components/checkboxes.js
app/assets/stylesheets/govuk_publishing_components/components/_checkboxes.scss
app/views/govuk_publishing_components/components/_checkboxes.html.erb
lib/govuk_publishing_components/presenters/checkboxes_helper.rb
spec/javascripts/components/checkboxes-spec.js

Checkboxes are being rendered in large numbers in finders, which is slower than we'd like. This PR removes an unneeded `div` from the checkbox markup, which fractionally improves the rendering speed.
Appearance and functionality of the checkboxes should remain exactly the same as it was before. I've checked it in a few browsers, old and new, but would appreciate more pairs of eyes.
This change also removes some redundant CSS and classes, and fixes the simulated markup for checkboxes in the JS spec file.
Trello card: https://trello.com/c/ZvgrsGJv/440-reduce-checkbox-component-markup

Reduce checkboxes markup

---

lib/govuk_publishing_components/presenters/services.rb

For the migration to search-api we're going to re-target the 'search'
alias to search-api.
---
[Trello card](https://trello.com/c/yrq9hZmU/77-point-the-search-alias-to-search-api-if-rummager-is-disabled)

Change Plek(rummager) to Plek(search)

---

docs/component_conventions.md

Documenting the [shared helper code](https://github.com/alphagov/govuk_publishing_components/blob/master/lib/govuk_publishing_components/presenters/shared_helper.rb).

Add shared helper info to conventions doc

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_input.html.erb
app/views/govuk_publishing_components/components/docs/input.yml
app/views/govuk_publishing_components/components/feedback/_survey_signup_form.html.erb
spec/components/input_spec.rb

* Add `autocomplete` attribute option to input component
* Use `autocomplete=email` on feedback component's survey signup form to conform with WCAG criterion 1.3.5 (Identify Input Purpose)
I'm not sure if it also makes sense to add the `autocomplete` attribute option to other form components? Checkboxes and radio buttons probably don't make sense, but selects and textareas might, not sure about file upload.
---
https://govuk-publishing-compon-pr-[733].herokuapp.com/component-guide/

Add `autocomplete` attribute to feedback form and use it on feedback component's survey signup form

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_government_navigation.html.erb
spec/components/government_navigation_spec.rb

Changes link in header to consultations to new policy papers and consultations finder
Uses appropriate parameters to only show closed and open
consultations
Trello: https://trello.com/c/dkz8ZIol/511-change-whitehall-header-link-to-consultations-finder-s

Change link in header to new policy papers and consultations finder

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_search.html.erb
app/views/govuk_publishing_components/components/docs/search.yml
spec/components/search_spec.rb

Not all use cases will need to use 'q' but to ensure backwards compatiblity
I have made it the default.
In finder-frontend we use 'keyword' as the field name.
Ticket: https://trello.com/c/LznDjL1r/505-all-content-update-page-heading-to-search

Allow custom name attribute on search input

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/_search.scss
app/views/govuk_publishing_components/components/_search.html.erb
app/views/govuk_publishing_components/components/docs/search.yml
spec/components/search_spec.rb

We are using this component in finders-frontend and need to be able to suppress the submit button otherwise there will be two submit buttons in the form.
ticket: https://trello.com/c/LznDjL1r/505-all-content-update-page-heading-to-search?menu=filter&filter=label:Finders

Suppress search components submit button 

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

Bumps the gem version to 16.6.0
* Allow custom name attribute on search input (PR #787)
* Suppress search components submit button (PR #786)
* Fixes issue in test for consultations header link (PR #788)

Bumps gem version to 16.6.0

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_input.html.erb
app/views/govuk_publishing_components/components/docs/input.yml
spec/components/input_spec.rb

This PR adds a `width` option to the input component, which allows to set a specific width for an text input based on the number characters that are expected to be inserted. This feature is added primarily as a preparation for the date-input component which will use the input component within.
Currently, the supported values (defined in govuk-frontend) are 2, 3, 4, 5, 10, 20, 30 which implies that the bigger value should be used in case the expected length is between these values.
[Trello card](https://trello.com/c/0ZphzvRd)

Add custom width to inputs

---

spec/javascripts/components/modal-dialogue-spec.js

Missed when migrating the component in #778. I've realised now that we're updating Content Publisher to use the component from the gem.

Add missing tests for the JavaScript in modal dialogue component

---

CHANGELOG.md
app/assets/javascripts/govuk_publishing_components/lib/toggle.js
spec/javascripts/components/toggle-spec.js

This PR adds tracking to toggle.js, which enables analytics to be fired the `$toggle` element if it is set up with `data-track-category` and `data-track-action` attributes.

Add tracking to toggle.js

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/_all_components.scss
app/assets/stylesheets/govuk_publishing_components/components/_date-input.scss
app/views/govuk_publishing_components/components/_date_input.html.erb
app/views/govuk_publishing_components/components/_fieldset.html.erb
app/views/govuk_publishing_components/components/_input.html.erb
app/views/govuk_publishing_components/components/docs/date_input.yml
spec/components/date_input_spec.rb

This PR
- adds the [date input component](https://govuk-publishing-compon-pr-792.herokuapp.com/component-guide/date_input) from `govuk-frontend` and
- updates the input component to allow `error_style` without an `error_message` (so that inputs can be styles with a thick red box without requiring an error message attached to them)
- updates the fieldset component to support `describedby` and `role` attributes required for accessibility enhancements of the date-input component.
[Trello card](https://trello.com/c/0ZphzvRd)

Add date input component

---

CHANGELOG.md
Gemfile.lock
app/assets/javascripts/govuk_publishing_components/components/cookie-banner.js
app/assets/javascripts/govuk_publishing_components/lib/cookie-functions.js
app/assets/javascripts/govuk_publishing_components/lib/header-navigation.js
app/assets/stylesheets/component_guide/application.scss
app/assets/stylesheets/govuk_publishing_components/_all_components.scss
app/assets/stylesheets/govuk_publishing_components/components/_cookie-banner.scss
app/views/govuk_publishing_components/components/_cookie_banner.html.erb
app/views/govuk_publishing_components/components/docs/cookie_banner.yml
spec/components/cookie_banner_spec.rb
spec/javascripts/components/cookie-banner-spec.js

We need to update the cookie banner which is currently part of govuk_template. There was [an attempt to do this update in govuk_template](https://github.com/alphagov/govuk_template/pull/368), but since that's a deprecated repository we shouldn't do any new work or releases on it.
Instead, this PR moves [the remaining `govuk-template.js` scripts](https://github.com/alphagov/govuk_template/blob/master/source/assets/javascripts/govuk-template.js) into `app/assets/javascripts/govuk_publishing_components/lib/` and extracts the cookie banner into its own component.
A follow up PR will come after this, updating static to remove `govuk-template.js` and the associated markup for the cookie banner and replace it with this component.
Update: PR in static https://github.com/alphagov/static/pull/1662 …

Add cookie banner component

---

CHANGELOG.md
app/assets/javascripts/govuk_publishing_components/components/checkboxes.js
spec/javascripts/components/checkboxes-spec.js

There are some cases where you might not want to track the change to the
checkboxes. For example, an event being triggered from another component
which unticks/ticks a checkbox like finder-frontend has. Facet tags
when clicked untickes the relevant checkbox and tracks the change.
https://trello.com/c/7vQb8Yww/434-bug-fix-issue-where-use-of-brexit-checkbox-fires-multiple-ga-events
Will be needed for https://github.com/alphagov/finder-frontend/pull/984

Control when checkboxes change event sends tracking info

---

app/assets/stylesheets/component_guide/application.scss
app/views/govuk_publishing_components/components/_error_message.html.erb
package-lock.json
package.json
spec/components/date_input_spec.rb
spec/components/error_message_spec.rb
spec/components/file_upload_spec.rb
spec/components/input_spec.rb
spec/components/radio_spec.rb
spec/components/textarea_spec.rb

This PR:
- updates this repo to use govuk-frontend v2.9.0 (and pins this version)
- updates the error_message component to add a visually hidden  "Error:" prefix to the message
- adds nta typeface to the component guide (the font is not disabled by default for projects that have compatibility with govuk_template enabled [in an effort to remove a duplicate requests](https://github.com/alphagov/govuk_publishing_components/issues/597) so we'll have to re-enable it for the component guide).
- Prevent accidental multiple submissions of forms - this can be enabled by setting `data-prevent-double-click="true"` on a button component.
- Prefix error messages with a visually hidden "Error:" to make it clearer to users of assistive technologies - updated the error_message component to reflect this …

Update govuk-frontend to 2.9.0

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/_subscription-links.scss
app/views/govuk_publishing_components/components/_subscription-links.html.erb
app/views/govuk_publishing_components/components/docs/subscription-links.yml
spec/components/subscription_links_spec.rb

In finder-frontend, we needed the subscriptions component to be less "shouty" and be less prominent on the page. The component is used in three other repositories. This PR creates a 'small form' version by making the font smaller and not bold.
- updates css to use govuk-frontend mixins
- add small form option and styling
- position icons closer to the text
Component: https://govuk-publishing-compon-pr-803.herokuapp.com/component-guide/subscription-links
Demo: https://govuk-publishing-compon-pr-803.herokuapp.com/component-guide/subscription-links/as_small_form
Ticket: https://trello.com/c/nMB9EUx0/581-update-top-section-of-results-layout

Adds small form option to subscription component

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_subscription-links.html.erb
app/views/govuk_publishing_components/components/docs/subscription-links.yml
spec/components/subscription_links_spec.rb

For some unknown reason this component includes a h2 heading by default.
This means that if a service uses it unexpectedly it will include the heading.
It also stops a team from using this component anywhere else on a page.
By using the 'hide_heading' option, it will suppress the heading when
the component is being rendered.
Component: https://govuk-publishing-compon-pr-804.herokuapp.com/component-guide/subscription-links
Demo: https://govuk-publishing-compon-pr-804.herokuapp.com/component-guide/subscription-links/without_heading
Ticket: https://trello.com/c/nMB9EUx0/581-update-top-section-of-results-layout

Suppress subscription components heading

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Control when checkboxes change event sends Google Analytics tracking info (PR #801)
* Updates govuk-frontend from 2.5.1 to 2.9.0 (PR #794)
* Adds small form option to subscription component (PR #803)

Release v16.8.0

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/_subscription-links.scss
app/views/govuk_publishing_components/components/_subscription-links.html.erb
spec/components/subscription_links_spec.rb

there no need for the far left/right margin to be applied to small form subscription links. If space is needed it can be done by wrapping an element around this component and applying a maring left/right to it

fix margin spacing for small form subscription links

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_cookie_banner.html.erb
app/views/govuk_publishing_components/components/docs/cookie_banner.yml
spec/javascripts/components/cookie-banner-spec.js

Using the full URL triggers the external link tracking on GOV.UK

Use relative url for cookies page

---

CHANGELOG.md
app/assets/javascripts/govuk_publishing_components/components/modal-dialogue.js
app/assets/stylesheets/govuk_publishing_components/components/_modal-dialogue.scss

govuk-frontend v2.8.0 introduces an `overflow-y: scroll` for `.govuk-template` that needs to be overwritten when the modal opens otherwise the content will scroll behind the modal. https://github.com/alphagov/govuk-frontend/pull/1230

 Update the modal component to prevent the page from scrolling behind it when open

---

CHANGELOG.md
lib/govuk_publishing_components/presenters/breadcrumbs.rb
spec/components/breadcrumbs_spec.rb

This makes no change to the markup versions of breadcrumbs.
When using the pattern of [last breadcrumb is current page](https://govuk-publishing-components.herokuapp.com/component-guide/breadcrumbs/last_breadcrumb_is_current_page) structured data is generated that fails the [Google structured data testing tool's validation](https://search.google.com/structured-data/testing-tool/u/0/#url=https%3A%2F%2Fwww.gov.uk%2Fprepare-eu-exit/).  
To fix this, we omit breadcrumb items with no url from the structured data.

Correct breadcrumb structured data for missing URL

---

CHANGELOG.md
app/assets/javascripts/govuk_publishing_components/components/modal-dialogue.js
spec/javascripts/components/modal-dialogue-spec.js

https://trello.com/c/4kQa7EZO/762-allow-users-embed-videos
This adds an API to the modal object to support dynamically changing its
size, in order to accommodate different workflows that are presented in
a single modal instance using the multi-section-viewer component.

Expose API to change modal size to narrow/wide

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

Releasing this fix so we can roll it out in all apps.
- Enforce compatibility with deprecated packages for media print stylesheet (PR #815)

Release v16.10.1

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_checkboxes.html.erb
app/views/govuk_publishing_components/components/_radio.html.erb
app/views/govuk_publishing_components/components/docs/checkboxes.yml
app/views/govuk_publishing_components/components/docs/radio.yml
lib/govuk_publishing_components/presenters/checkboxes_helper.rb
package-lock.json
package.json
spec/components/checkboxes_spec.rb
spec/components/radio_spec.rb

This PR:
- updates this repo to govuk-frontend version 2.10.0
- updates the checkboxes component to have a 'small' option
- updates the radio component to have a 'small' option
[See detailed changelog](https://github.com/alphagov/govuk-frontend/releases/tag/v2.10.0)
Links:
- [small checkboxes](https://govuk-publishing-compon-pr-817.herokuapp.com/component-guide/checkboxes/with_small_checkboxes)
- [small radios](https://govuk-publishing-compon-pr-817.herokuapp.com/component-guide/radio/with_small_radios)
Trello card: https://trello.com/c/wp21yw0C/635-use-small-radios-and-checkboxes-in-finder-frontend

Upgrade to govuk-frontend 2.10.0

---

CHANGELOG.md
app/assets/javascripts/govuk_publishing_components/lib/header-navigation.js

Attach click event listener only to anchors.
This mitigates [an issue](https://github.com/alphagov/govuk-frontend/issues/1270) when we use `js-header-toggle` as a selector for both menu buttons coming from govuk_template (which are marked-up with `<a>`) and for menu buttons coming from govuk-frontend (marked-up with `<button>`). It doesn't affect the overall functionality but when the header component is used, the script coming from govuk_template throws and error since both scripts are attached to the same button.
The incompatibility between the two repos could be resolved in govuk-frontend, but we can prevent it in this gem by being more specific about the elements we attach the event listener to.
Before: https://govuk-publishing-components.herokuapp.com/component-guide/layout_header/wit …

Fix script in header component not being compatible with the govuk_template

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

- Fix script in header component not being compatible with the govuk_template script (PR #818)
- Upgrade to govuk-frontend 2.10.0 (PR #817)

Version 16.11.0

---

CHANGELOG.md
app/assets/javascripts/govuk_publishing_components/components/cookie-banner.js
spec/javascripts/components/cookie-banner-spec.js

Trello: https://trello.com/c/tOKIPmZ3/99-improve-cookie-banner-tracking
Because the cookie banner is now persistent, we'd rather track when it's not shown rather than when it is.

Track when the cookie banner isn't shown

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

Bump gem to include the following change:
- Fire GA event when cookie banner isn't shown, instead of when it is (PR #821) ([Trello](https://trello.com/c/tOKIPmZ3/99-improve-cookie-banner-tracking))

Version 6.12.0

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/_input.scss
app/views/govuk_publishing_components/components/_input.html.erb
app/views/govuk_publishing_components/components/docs/input.yml

We'd like to able to add a icon to an input to show that this is a search input, similar to other inputs in the finder facet. 
At the moment it's all lonely and blank:
And it'd be nice to have a search icon in it:
I've added this in a specific search icon flag `search_icon` - set to true and an extra gem class is added, which sets the icon in the background and adds padding.
Tested in Internet Explorer 9 to 11, plus the rest of the [GDS supported browsers](https://www.gov.uk/service-manual/technology/designing-for-different-browsers-and-devices). IE 8 doesn't display the icon since it's an SVG, but the input still functions correctly.

Add an option to display search icon in input element

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_document_list.html.erb
spec/components/document_list_spec.rb

This will enable us to provide nil as a value in document list
metadata. E.g. public_updated_at: nil. This is useful, as
sometimes we can have nil fields and dont check for them,
which causes errors. We could fix this when using the component
but it is nicer to fix it once here.

Permit Document List metadata fields to be blank

---

CHANGELOG.md
package-lock.json
package.json

* GOV.UK Frontend updated from version 2.10.0 to 2.11.0
[Release notes for GOV.UK Frontend v2.11.0](https://github.com/alphagov/govuk-frontend/releases/tag/v2.11.0)

Update GOV.UK Frontend to 2.11.0

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

- Add an option to display search icon in input element (PR #824)
- Permit Document List metadata fields to have nil values. (PR #828)
- Upgrade to GOV.UK Frontend version 2.11.0. (PR #826)

Version 16.13.0

---

CHANGELOG.md
Gemfile.lock
govuk_publishing_components.gemspec

Trello: https://trello.com/c/zMYmFTPx/801-show-metadata-for-attachments
GDS Api Adapters was a listed as a development dependency for this gem,
however it's required outside dev environment to pull in data from
Rummager [1]. Plek is also used here, so this is flagged as a
dependency.
Arguably both of these stretch beyond what this gem should actually be
doing, so shouldn't be encouraged patterns.
[1]: https://github.com/alphagov/govuk_publishing_components/blob/c1c602af10a3ee1dea24c77357c34b5afc843561/lib/govuk_publishing_components/presenters/services.rb

Add gds-api-adapters and Plek as dependencies

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

- Add attachment link (experimental) component (PR #833)
- Add plek as a dependency (PR #834)
- Provide `GovukPublishingComponents.render` method for rendering components outside of views (PR #832)
- Remove govspeak dependency with kramdown for markdown rendering (PR #827)

Version 16.14.0

---

app/views/govuk_publishing_components/components/docs/attachment_link.yml

A late change to attachment link was the introduction of a filename
attribute that could be passed in for dealing with extensions. I forgot
to add this to examples and it is an encouraged attribute.

Add filename to attachment_link examples

---

spec/components/contextual_footer_spec.rb

Ah tests that rely on random data, what joy you bring...
This fixes a test that has failed quite a few times with:
```
Failures:
1) Contextual footer renders the footer
Failure/Error: assert_select '.gem-c-contextual-footer'
NoMethodError:
undefined method `document' for nil:NilClass
```
The reason this fails is that the component won't render if there is a
particular link case (one part_of_steps_nav link) and if the component
isn't rendered the assert_select doesn't think there is a DOM document
to check.
To verify this resolves the problem I've ran the test 1000 times and it
passed each time.

Fix rogue failing test

---

CHANGELOG.md
app/assets/javascripts/govuk_publishing_components/components/cookie-banner.js
spec/javascripts/components/cookie-banner-spec.js

Removes the cookie banner tracking which fires when the cookie banner is hidden. This would fire an additional event on every user page view, which will build up our analytics events to hit our limit. Instead, we will be adding a custom dimension to the existing pageview event.
This essentially reverts #821.

Revert cookie banner tracking

---

app/assets/stylesheets/govuk_publishing_components/components/_search.scss
app/views/govuk_publishing_components/components/_search.html.erb
app/views/govuk_publishing_components/components/docs/search.yml
spec/components/search_spec.rb

This pull request removes the `hide_search_button` parameter from the search component - this was originally used on the [search all finder](https://gov.uk/search/all), but has since been replaced with an input component to better match the rest of the finder sidebar. See [`finder-frontend` PR 1088](https://github.com/alphagov/finder-frontend/pull/1088) for more info on that.
To avoid bloat creep, this option has been removed as (I think) the search all finder was the only place using this option. If it's being used elsewhere, please comment and I'll close this pull request.

Removes option to not have a submit button on search component

---

CHANGELOG.md
app/assets/stylesheets/component_guide/application.scss
app/assets/stylesheets/govuk_publishing_components/components/_cookie-banner.scss
app/views/govuk_publishing_components/components/_cookie_banner.html.erb

The banner was supposed to not show without Javascript. It did not
display in the component guide, but showed up on the frontend. However
we want the banner to still display, as there are other cookies that
may still be set by servers, and not Javascript.
We also don't show the "Hide this message" link without Javascript.
All are running without Javascript:

Update cookies banner behaviour without Javascript

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/_all_components.scss
app/assets/stylesheets/govuk_publishing_components/components/_attachment.scss
app/views/govuk_publishing_components/components/_attachment.html.erb
app/views/govuk_publishing_components/components/docs/attachment.yml
config/locales/en.yml
lib/govuk_publishing_components/presenters/attachment.rb
spec/components/attachment_spec.rb
spec/lib/govuk_publishing_components/presenters/attachment_spec.rb

For: https://trello.com/c/zMYmFTPx/801-show-metadata-for-attachments
🎉 View in the [component guide](http://govuk-publishing-compon-pr-842.herokuapp.com/component-guide/attachment) 🎉 
This adds a component for an attachment, which is intended to be used by Govspeak and Content Publisher.

Add Attachment component

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/_button.scss
lib/govuk_publishing_components/presenters/button_helper.rb
spec/components/button_spec.rb

As these two styles are identical, this PR removes the CSS from the gem and configures the button component to use GOV.UK Frontend warning button (https://design-system.service.gov.uk/components/button/#warning-buttons). 
👉 https://design-system.service.gov.uk/components/button/#warning-buttons
👉 https://govuk-publishing-compon-pr-848.herokuapp.com/component-guide/button/destructive_button

Replaces gem-c-button--destructive with govuk-button--warning

---

CHANGELOG.md
app/views/govuk_publishing_components/components/docs/button.yml
lib/govuk_publishing_components/presenters/button_helper.rb
spec/components/button_spec.rb

Set `prevent-double-click` data attribute to `true` by default for the button component.
See [original commit](https://github.com/alphagov/govuk-frontend/commit/884e7dd73ad943d71fb701da15626e6a7ad0b933) for more details about how this works.
We discovered in research that users with low digital skills sometimes use double click to trigger an action which may result in unexpected system failures (for example when trying to remove an entity the second attempt fails) or double additions. For this reason we think the best measure is to introduce this preventive measure for all instances of buttons instead of trying to figure out when a system may fail because of it.
[Trello card](https://trello.com/c/JLkfkNxQ)

Prevent double click for buttons

---

CHANGELOG.md
spec/features/contextual_navigation_spec.rb

Trello: https://trello.com/c/uR7v1Rri
Related to:
https://github.com/alphagov/govuk-content-schemas/pull/892
https://github.com/alphagov/govuk-content-schemas/pull/891
Content item types, `facet_groups`, `facets` and `facet_values` were changed to be "base_path-less" in https://github.com/alphagov/govuk-content-schemas/pull/891. 
We did this because, that's how they were already being treated in publishing-api and content-store, but we couldn't add re-usable test examples until this was explicitly stated in `govuk-content-schemas`.
However, this started causing the [feature tests in this app](https://ci.integration.publishing.service.gov.uk/job/govuk_publishing_components/job/master/731/consoleFull) to fail with errors like:
```
Failure/Error: …
```

Update feature tests to use examples from govuk-content-schemas

---

Gemfile.lock
govuk_publishing_components.gemspec

Ruby Sass is deprecated so needs to be replaced with something that is supported. [SassC Rails](https://github.com/sass/sassc-rails) is faster and a drop in replacement, according to its readme, and it seems to be both of these.
Fixes #601.
[Trello ticket](https://trello.com/c/V5y9atIh/80-draft-investigate-swapping-out-sass-rails-for-sassc-rails).

Update to SassC Rails

---

CHANGELOG.md

There was the "wrong type" of space here which stopped the heading being formatted correctly by GitHub

Fix formatting for 16.14.1 heading

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/_attachment.scss
app/views/govuk_publishing_components/components/_attachment.html.erb
app/views/govuk_publishing_components/components/_attachment_link.html.erb
app/views/govuk_publishing_components/components/attachment/_thumbnail_document.svg
app/views/govuk_publishing_components/components/attachment/_thumbnail_generic.svg
app/views/govuk_publishing_components/components/attachment/_thumbnail_spreadsheet.svg
app/views/govuk_publishing_components/components/docs/attachment.yml
lib/govuk_publishing_components/presenters/attachment.rb
spec/components/attachment_spec.rb
spec/lib/govuk_publishing_components/presenters/attachment_spec.rb

Trello: https://trello.com/c/HO5MZZEG/822-show-thumbnails-for-attachment-file-formats
This adds in inline SVGs for the different file types that can be shown as an attachment: document, spreadsheet and generic. It does not include HTML attachments as this component does not support these yet. It also does not allow the concept of passing an image in for a PDF attachment as a [product decision](https://gov-uk.atlassian.net/wiki/spaces/GOVUK/pages/1399422981/Design+documentation+Content+Publisher+Q1+19+20#Designdocumentation%E2%80%93ContentPublisherQ119/20-RemovepreviewfromPDFattachments) has been made to remove that functionality.
This also fixes two small issues: content type wasn't showing when it lacked an abbreviation, and we were still getting the browser default outline on the …

Add SVG thumbnail icons to attachment component

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

- Replace gems version of warning button with GOV.UK Frontend version (PR #848)
- Prevent double click by default for submit buttons (PR #849)
- Add inline SVG icons to attachment component (PR #850)
- Update contextual navigation feature tests to use examples from govuk-content-schemas (PR #847)
https://github.com/alphagov/govuk_publishing_components/pull/851 was wrongly labeled as a release since it only updated the README.md file.

Release v16.17.0

---

CHANGELOG.md
app/assets/javascripts/govuk_publishing_components/components/cookie-banner.js
app/assets/javascripts/govuk_publishing_components/lib/cookie-functions.js
app/assets/stylesheets/govuk_publishing_components/components/_button.scss
app/assets/stylesheets/govuk_publishing_components/components/_cookie-banner.scss
app/views/govuk_publishing_components/components/_cookie_banner.html.erb
app/views/govuk_publishing_components/components/docs/button.yml
app/views/govuk_publishing_components/components/docs/cookie_banner.yml
lib/govuk_publishing_components.rb
lib/govuk_publishing_components/presenters/button_helper.rb
lib/govuk_publishing_components/presenters/cookie_banner_helper.rb
spec/components/button_spec.rb
spec/components/cookie_banner_spec.rb
spec/javascripts/components/cookie-banner-spec.js

This PR introduces a WIP cookie banner which allows users to accept cookies or view the cookie settings page (a new page which will allow users to individually opt-in/opt-out of specified cookie settings. The aim is for this new banner to eventually replace the current banner we have, which doesn't have this functionality.
**To do before merging:**
- ~Add to Changelog~
- ~Write up follow-up cards for the work still to be completed~
- ~Make changes / write follow-up cards for comments on this PR~
- ~Update copy / create card to update copy~
- ~Confirm cookie category names~
- ~Remove "IGNORE test commit"~
This PR introduces the new cookie banner under a flag `new_cookie_banner: true` so that we don't interfere with the current banner while testing. The new banner shouldn't interfere/effect …

MVP add new cookie banner

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/govspeak/_attachment.scss
app/views/govuk_publishing_components/component_guide/component_doc/_component_output.html.erb
app/views/govuk_publishing_components/components/docs/attachment.yml
app/views/govuk_publishing_components/components/docs/attachment_link.yml
app/views/govuk_publishing_components/components/docs/govspeak.yml

Trello: https://trello.com/c/zMYmFTPx/801-show-metadata-for-attachments
This PR does a few things to demonstrate attachment components in a govspeak context (info in commits) and then looks at fixing a styling issue caused by specificity problems between govspeak and attachment component.
Before:
After:

Fix attachment rendering within Govspeak

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_contextual_breadcrumbs.html.erb
lib/govuk_publishing_components/presenters/contextual_navigation.rb
spec/components/contextual_breadcrumbs_spec.rb

Previously only content items that were a specialist document showed it's parent finder as breadcrumb links. This functionality has now been changed to support all documents which have a finder linked.
This work was done as part of the following ticket:
https://trello.com/c/uR7v1Rri/71-update-the-breadcrumbs-of-business-finder-content-to-link-to-the-business-finder

Adds support to allow parent finder to show as breadcrumbs

---

CHANGELOG.md
app/views/govuk_publishing_components/components/docs/machine_readable_metadata.yml
lib/govuk_publishing_components/presenters/machine_readable/search_results_page_schema.rb
lib/govuk_publishing_components/presenters/schema_org.rb
spec/components/machine_readable_metadata_spec.rb

This adds a naive implementation of https://schema.org/SearchResultsPage which
permits us to add basic schema information to finder pages.  Using this approach
also adds other page metadata (contained in the machine_readable_metadata partial).
We're paying more attention to how these are indexed for search because finders
have different requirements for search visibility.  Specialist finders need
to be findable via Google because these search pages are a critical for a subset
of users.
More general search pages have a more nuanced need.  We generally want people
to avoid navigating from Google search to an internal search page unless it
is for a specific reason.
We have already excluded search results page with keywords from being indexed,
and we similarly exclude everything past the …

Add SearchResultsPage schema

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_government_navigation.html.erb
app/views/govuk_publishing_components/components/docs/layout_footer.yml

This PR removes the link to the Whitehall publications finder from the _Government navigation_ component, as it does not map directly to any of the new finders.
Trello: https://trello.com/c/3BuGZK2A

Remove link to Whitehall publications

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

https://trello.com/c/JLkfkNxQ/815-fix-the-double-click-so-actions-are-only-carried-out-once

Bump version to 16.20.1

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/_attachment.scss
app/views/govuk_publishing_components/components/_attachment.html.erb
app/views/govuk_publishing_components/components/docs/attachment.yml
config/locales/en.yml
lib/govuk_publishing_components/presenters/attachment.rb
spec/components/attachment_spec.rb

Add request different format section using the Details component instead of requiring JavaScript for revealing the additional content.
[Trello card](https://trello.com/c/OcuVomSb)

Add request different format to attachment component

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_attachment_link.html.erb
spec/components/attachment_link_spec.rb

Fix broken call to fallback content_type method

---

CHANGELOG.md
app/assets/javascripts/govuk_publishing_components/components/cookie-banner.js
app/assets/javascripts/govuk_publishing_components/lib/cookie-functions.js
app/assets/stylesheets/govuk_publishing_components/components/_cookie-banner.scss
spec/javascripts/components/cookie-banner-spec.js

This PR contains 3 changes:
1. Make 'hide button' font consistent with the rest of the cookie banner
2. Set the default consent to 'on'. This is for user testing and still up for debate - the consent cookie doesn't have any effect on what cookies are set yet. We want to test out if/how users understand implicit consent.
3. Hide the new cookie banner on the cookie settings page (/help/cookies) to avoid circular journeys. The cookie banner contains a link to the cookie settings page. GA analysis has found that a high proportion of users click the link to cookie settings when they're already on that page. The page already lets users accept cookies, so we can just hide the banner to avoid confusion.

Cookie banner tweaks

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/_button.scss
app/views/govuk_publishing_components/components/docs/button.yml

Update the inline button style so they appear adjacent to each other for as long as possible before stacking one on top of the other, so it takes up less vertical space.

Update inline button style

---

CHANGELOG.md
lib/govuk_publishing_components/presenters/machine_readable/organisation_schema.rb
spec/lib/govuk_publishing_components/presenters/schema_org_spec.rb

This indicates to external consumers of the site how to perform a search scoped to a GovernmentOrganization.  This _might_ result in a [sitelinks](https://developers.google.com/search/docs/data-types/sitelinks-searchbox) box pointing at GOV.UK search appearing for organisation searches in Google.
This information will appear in organisation pages like https://www.gov.uk/government/organisations/ministry-of-housing-communities-and-local-government, so should be relevant to external search results that feature those pages.
This follows "Example 3" in https://schema.org/SearchAction and passes the validation checks on https://search.google.com/structured-data/testing-tool/u/0/
https://trello.com/c/4EAytHVV/747-plan-noindexing-of-finder-pages

Add potentialSearchAction to orgs

---

app/assets/stylesheets/govuk_publishing_components/components/_contents-list.scss
app/assets/stylesheets/govuk_publishing_components/components/print/_contents-list.scss

This PR updates the contents list component to use govuk-frontend instead of govuk_frontend_toolkit.
**Notes:**
`$gutter` = `govuk-spacing(6)` = `30px`

Update contents-list component to use govuk-frontend

---

app/assets/stylesheets/govuk_publishing_components/components/_document-list.scss

This PR updates the document list component to use govuk-frontend instead of govuk_frontend_toolkit.
**Notes:**
`$gutter` = `govuk-spacing(6)` = `30px`

Update document-list component to use govuk-frontend

---

app/assets/stylesheets/govuk_publishing_components/components/_error-alert.scss
app/views/govuk_publishing_components/components/docs/error_alert.yml

This PR:
- updates the error-alert component to use govuk-frontend instead of govuk_frontend_toolkit
- uses `govuk-spacing` mixin instead of locally defined `gem-spacing-scale-`
- updates component name for consistency

Update error alert component to use govuk-frontend

---

lib/govuk_publishing_components/presenters/machine_readable/article_schema.rb
lib/govuk_publishing_components/presenters/machine_readable/creative_work_schema.rb
lib/govuk_publishing_components/presenters/machine_readable/search_results_page_schema.rb
lib/govuk_publishing_components/presenters/schema_org.rb

Using `Article` as a base class for most things was fine until we introduced `SearchResultPage`.  `CreativeWork` is the common ancestor of both of these, so makes sense to introduce.
We did not break anything by having the `SearchResultPage` class inherit from `Article` because we didn't use anything in `Article` that was not in `CreativeWork` apart from `articleBody` and that defaulted to empty when our content items didn't include relevant content. It was a bit of a violation
of OO principles though, and feels more prone to error.
By adding `CreativeWork` here, we hopefully ensure that things won't break should we subsequently use specialised properties of `Article`.
Note that we are just reflecting the ancestry of https://schema.org/Article and https://schema.org/SearchResultsPage here …

[refactor] Insert CreativeWork schema as parent of Article and SearchResultsPage

---

CHANGELOG.md
config/locales/cy.yml
spec/components/contents_list_spec.rb

For an organisation about page - when language translation exists not all the page furniture is translated. In this example the 'contents' heading is still showing in English. However, other furniture e.g footer back to top link has the word contents translated properly.
Example page: https://www.gov.uk/government/organisations/animal-and-plant-health-agency/about.cy
Raised in zendesk by AHPA org here: https://govuk.zendesk.com/agent/tickets/2915580
Temp fix in the app itself done here: https://github.com/alphagov/government-frontend/pull/1339

Add contents list heading welsh translation

---

govuk_publishing_components.gemspec

The comment that applied to the inclusion of the webmock gem had become
decoupled.  I've re-attached them and changed the wording of the comment
so that it's hopefully clearer that they belong together.

Fix gemspec comment

---

CHANGELOG.md
lib/govuk_publishing_components/presenters/machine_readable/article_schema.rb
lib/govuk_publishing_components/presenters/machine_readable/organisation_schema.rb
lib/govuk_publishing_components/presenters/machine_readable/page.rb
lib/govuk_publishing_components/presenters/machine_readable/potential_search_action_schema.rb
lib/govuk_publishing_components/presenters/schema_org.rb
spec/lib/govuk_publishing_components/presenters/schema_org_spec.rb

Manuals like [The Highway Code](https://www.gov.uk/guidance/the-highway-code) have an embedded search box which allows searches scoped to that manual.
By advertising this in our machine readable metadata it's more obvious to external consumers of the site that these things are available.
This is part of the work to make our search more visible to external consumers of the site.
Possibly useful to review by commit because the majority of the change is extracting the `potentialSearchAction` schema from organisations to make it available for use in manuals.
https://trello.com/c/4EAytHVV/747-plan-indexing-of-finder-pages

Add SearchAction for manuals

---

app/assets/stylesheets/govuk_publishing_components/components/_radio.scss
app/views/govuk_publishing_components/components/_radio.html.erb

A fix for this was added in [govuk-frontend 2.2.0](https://github.com/alphagov/govuk-frontend/blob/master/CHANGELOG.md#220-feature-release)

Remove radios divider CSS overwrite

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/_notice.scss
app/views/govuk_publishing_components/components/_notice.html.erb
app/views/govuk_publishing_components/components/docs/notice.yml

This PR updates the [Notice component](https://govuk-publishing-compon-pr-884.herokuapp.com/component-guide/notice) to:
- allow rendering without a `title` (used in admin interfaces to play back neutral messages after a user action [Trello card](https://trello.com/c/R1zp5SAu))
- update scss to use govuk-frontend ([Trello card](https://trello.com/c/ajPzDAOX))
- align notice component styles with the standard error-summary component styles (consists in font-size change for the title and usage of mixins to generate responsive paddings and margins for the main container)
- uses helpers (Rails tag helpers and internal SharedHelper - to set custom margins consistently) to generate markup
- updates examples with custom content (using `description` attributes) to use govuk-frontend classes
- …

Update notice component

---

README.md
docs/publishing-to-rubygems.md

Add documentation for publishing to RubyGems.
[See rendered version](https://github.com/alphagov/govuk_publishing_components/blob/add-publishing-docs/docs/publishing-to-rubygems.md)

Add docs for publishing to RubyGems

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_step_by_step_nav_header.html.erb
spec/components/step_by_step_nav_header_spec.rb

We've removed the `partOf` metadata for step by steps which linked back to the "parent" because we were using a partial HowTo schema which is not supported by Google's search indexing process.
This PR adds in machine readable breadcrumbs for pages that show the step by step header which should reinstate some of that experience for search engines.
I didn't want to assert too much on the exact format of the breadcrumbs schema output as they're defined in https://github.com/alphagov/govuk_publishing_components/blob/e3fd7fa321f4a38218a400fa795bb120c4681a4b/lib/govuk_publishing_components/presenters/breadcrumbs.rb (not the step by step header itself) and are used in the contextual breadcrumbs component too.
It's implementing https://schema.org/BreadcrumbList which looks like this in the …

Add machine readable breadcrumbs for step by steps

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_error_summary.html.erb
app/views/govuk_publishing_components/components/docs/error_summary.yml
spec/components/error_summary_spec.rb

This PR allows passing a target attribute for links on error summary component
This feature is used in Content Publisher when the change a users needs to do in order to fix the error is on another page than the current one and we don't want them to loose context.
[Trello](https://trello.com/c/TI9uPeMu)

Allow target on error summary links

---

CHANGELOG.md
config/locales/en.yml
lib/govuk_publishing_components/presenters/machine_readable/article_schema.rb
lib/govuk_publishing_components/presenters/machine_readable/organisation_schema.rb
lib/govuk_publishing_components/presenters/machine_readable/potential_search_action_schema.rb
spec/lib/govuk_publishing_components/presenters/schema_org_spec.rb

This adds some basic context around what the search action's target.
This is important as we may want to add other search actions on things
like org pages which have a number of links to finders.

Add description to SearchAction in schema metadata

---

app/views/govuk_publishing_components/components/docs/attachment.yml
app/views/govuk_publishing_components/components/docs/attachment_link.yml

Trello: https://trello.com/c/BQ5bBkMw/881-wrap-up-technical-loose-ends-on-attachments
As these are now used in production by Content Publisher and Govspeak
these are no longer considered experimental. Hopefully there won't be
need for any drastic API changes to them in the near future.
As these are purely internal changes I don't believe they need a changelog entry.

Remove experimental status of Attachment components

---

app/models/govuk_publishing_components/component_example.rb
spec/component_guide/component_example_spec.rb

Copy-pasting examples with attributes containing HTML caused
those attributes to be rendered incorrectly because Rails automatically
escapes all strings.
This commit finds all attributes containing HTML and adds
the 'sanitize' helper to the code examples allowing them to be copy-pasted as-is.
Screenshot:

Add #sanitize to code examples containing HTML

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/_button.scss
app/assets/stylesheets/govuk_publishing_components/components/_cookie-banner.scss

A design tweak to make inline buttons fill the space from mobile - tablet.

Make inline buttons 50% width from mobile - tablet

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_date_input.html.erb
app/views/govuk_publishing_components/components/_error_message.html.erb
app/views/govuk_publishing_components/components/_file_upload.html.erb
app/views/govuk_publishing_components/components/_input.html.erb
app/views/govuk_publishing_components/components/_radio.html.erb
app/views/govuk_publishing_components/components/_textarea.html.erb
app/views/govuk_publishing_components/components/docs/date_input.yml
app/views/govuk_publishing_components/components/docs/error_message.yml
spec/components/error_message_spec.rb

Trello: https://trello.com/c/rGjDviSL/848-adapt-scheduling-implementation-for-iterated-workflow
This enables the date input field to accept error_items as per the form input components.
It also moves the logic to flatten error_items into a singular string out of individual components and into the error_message components. Refactoring this has allowed fixing a potential XSS issue in the previous common implementation

Support error items on date component and refactor error items logic

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_notice.html.erb
app/views/govuk_publishing_components/components/docs/notice.yml
spec/components/notice_spec.rb

I came across this when trying to use the notice component as a notice telling the user their settings were saved. We scroll to the top of the page so users who can visually see confirmation of their settings. However, in order to get the notice content to be read out correctly for screen reader users, the aria-live needs to be on the section tag of the notice component itself (not a wrapper), hence adding this flag to the component
This will be used on the new cookie settings page, when the user presses "save changes": https://new-cookie-banner.herokuapp.com/help/cookies

Add aria-live flag to notice component

---

CHANGELOG.md
app/assets/javascripts/govuk_publishing_components/components/cookie-banner.js
app/assets/javascripts/govuk_publishing_components/lib/cookie-functions.js
spec/javascripts/components/cookie-banner-new-spec.js
spec/javascripts/components/cookie-banner-spec.js

We need to check what cookies a user has consented to before we set each cookie.
This also tidies up the cookie banner code so the old banner and new banner are more separate. This will make it easier for us to remove the old banner code once the new banner has been deployed.
**Note: the new cookie banner tests currently include a workaround by stubbing the return value of JSON.parse. Without this stubbing, it looks as though the value returned includes escaped quotes, which means an additional JSON.parse is required (but this works fine in the browser).**
Edited to add: it looks like the problem mentioned above could be related to phantomJS. I tried to update our version of jasmine and use chromeheadless instead, but this results in some test failures around step-by-step nav which I'm …

Cookie consent mechanism

---

CHANGELOG.md
app/assets/javascripts/govuk_publishing_components/lib/govspeak/youtube-link-enhancement.js
spec/javascripts/components/govspeak-spec.js
spec/javascripts/govuk_publishing_components/lib/govspeak/youtube-link-enhancement-spec.js

New cookie settings page (https://github.com/alphagov/frontend/pull/1856) will allow users to set certain cookie groups on or off.
When they set `campaigns` cookie to off we need to disable youtube embeds as they store cookies.
If the new cookie settings is not available, we continue to embed the youtube videos
_Note: tests currently include a workaround by stubbing the return value of JSON.parse. Without this stubbing, it looks as though the value returned includes escaped quotes, which means an additional JSON.parse is required (but this works fine in the browser)._
**Campaign cookie turned OFF**
**Campaign cookie turned ON**
**No campaign cookie (current behaviour)**

Disable youtube embeds if campaign cookies are turned off

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/_button.scss
app/assets/stylesheets/govuk_publishing_components/components/_cookie-banner.scss
app/views/govuk_publishing_components/components/_cookie_banner.html.erb
app/views/govuk_publishing_components/components/docs/cookie_banner.yml
lib/govuk_publishing_components/presenters/cookie_banner_helper.rb

Design tweaks and fixes for the cookie banner

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_error_summary.html.erb
app/views/govuk_publishing_components/components/docs/error_summary.yml
spec/components/error_summary_spec.rb

This enables data attributes for individual items of the error summary
component to better support tracking of the multiple items displayed.

Render data attributes with error summary items

---

CHANGELOG.md
app/assets/javascripts/govuk_publishing_components/components/feedback.js

At the moment, the `alphagov/feedback` application responds with a 422 HTTP status if all fields are left empty in the form.
**Current behaviour**
The feedback components javascript was setup to always apply the constructed error message first and then check for the `responseJSON.message` property, which would always return undefined.
This resulted in 422 status error message to never being applied.
This PR updates the logic to account for that.
Resolves: #915 
Trello ticket: https://trello.com/c/r5jiQ7Wk/130-feedback-component-insufficient-error-message-11
**New behaviour** (mock api response)

Update feedback component error handling

---

Gemfile.lock
govuk_publishing_components.gemspec
spec/component_guide/component_example_spec.rb
spec/components/contextual_footer_spec.rb

Capybara 3 brings in some breaking changes - but the only one that seems to have affected Publishing Components is that `has_content` doesn't play nicely with `\n` and newlines. Some tests had to be tweaked to account for this change.

Upgrade to Capybara 3

---

package-lock.json
package.json

Reverts alphagov/govuk_publishing_components#904
We (unfortunately) still need the older version of jQuery, since the newer version hasn't had all of the components tested in it thoroughly.

Revert "Bump jquery from 1.12.4 to 3.4.0"

---

app/assets/javascripts/govuk_publishing_components/lib/cookie-functions.js
spec/javascripts/components/cookie-banner-new-spec.js
spec/javascripts/components/cookie-banner-spec.js
spec/javascripts/govuk_publishing_components/lib/govspeak/youtube-link-enhancement-spec.js

We discovered that changes from recent cookie related changes (like in #916) caused errors in other frontends including static. 
This PR fixes those problems, and we also double check against other frontends.

Fix allowing/denying cookies

---

CHANGELOG.md
app/assets/javascripts/govuk_publishing_components/lib/cookie-functions.js
spec/javascripts/components/cookie-functions-spec.js

When a user removes consent for a particular cookie category we need to delete all cookies of that type. For example: if a user removes consent for usage cookies, we want to delete usage cookies for that user.

Delete cookies when a user remove consent

---

CHANGELOG.md
app/assets/javascripts/govuk_publishing_components/components/cookie-banner.js
app/assets/javascripts/govuk_publishing_components/lib/cookie-functions.js
spec/javascripts/components/cookie-banner-new-spec.js
spec/javascripts/components/cookie-functions-spec.js

Some users will already have acknowledged the old cookie banner, meaning they will have the seen_cookie_message set to true. If we deploy the new cookie banner, these users won't see it.
We therefore need to reset that cookie for users who have not yet seen the new cookie banner.
**Note: this can safely be merged and deployed as it won't have any effect until the new banner is switched on via a flag in Static**

Reset seen_cookie_message for new banner

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Add tracking to the hide button on new cookie banner (PR #928)
* Delete cookies when a user removes consent (PR #923)
* Reset seen_cookie_message if new cookie banner present (PR #925)

Version 17.1.0

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_modal_dialogue.html.erb

Fix the role of the `<dialog>` element to be "dialog" instead of "dialogue" (which is invalid – we may have ended up with this after a find and replace I imagine) and update template to use helpers for generating markup.

Fix dialog element role

---

app/assets/javascripts/govuk_publishing_components/lib/cookie-functions.js
spec/javascripts/components/cookie-functions-spec.js

As a result of a rebase to some previous PRs, a bug got through where the new consent cookie was being set before the new banner was deployed. As we rely on this cookie not being set to reset `seen_cookie_message` and show the new banner to everyone, this needed to be fixed before going live.

Fix resetting cookie mechanism for new banner

---

app/assets/stylesheets/govuk_publishing_components/components/_feedback.scss

This updates the feedback component to use govuk-frontend instead of govuk_frontend_toolkit

Update feedback component to use govuk-frontend

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/_step-by-step-nav.scss

Adds underline to the currently active step link, following user research.
Before:
After:
Also changes the active link 'dot' to a line, to look like this:

Change step by step navigation active step link state

---

CHANGELOG.md
app/views/govuk_publishing_components/components/docs/machine_readable_metadata.yml
lib/govuk_publishing_components/presenters/machine_readable/organisation_schema.rb
spec/lib/govuk_publishing_components/presenters/schema_org_spec.rb

This adds the ministers of an organisation to the [GovernmentOrganization](https://schema.org/GovernmentOrganization) schema which is present on [organisation pages](https://www.gov.uk/government/organisations).  It includes their name, prefix ("Rt Hon" etc.), url of people page and image.
For each role they inhabit we also include the role name, and the url of the role page.
This will enable consumers of organisation pages to more clearly identify the people and roles within an organisation.
[component guide example](https://govuk-publishing-compon-pr-921.herokuapp.com/component-guide/machine_readable_metadata/organisation_schema_with_people)
I've spun up a collections review app so you can see structured data tests for some orgs:
- [Attorney General's …

Add ministers with roles to org schema

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/_document-list.scss
app/views/govuk_publishing_components/components/_document_list.html.erb
app/views/govuk_publishing_components/components/docs/document_list.yml
spec/components/document_list_spec.rb

Adds the following...
Add 'subtext' option, small grey text to appear beneath metadata. This is needed for search results in finders, (where we want to use the document list component). This is not styled other than to match the font size of the description, specific styles will be added in finder-frontend for any elements that will be passed into the subtext area.
Add 'highlight' option, including optional highlight text. This is needed to highlight the 'top result' in finders.
Trello card: https://trello.com/c/DAblviIN/793-investigate-using-more-components-in-finder-frontend
Some examples of what this looks like currently:
- [subtext](https://www.gov.uk/search/all?parent=&keywords=%22every+child+matters%22&level_one_taxon=&manual=&public_timestamp%5Bfrom%5D=&public_timestamp%5Bto%5D=&ord …

Add options to document list component

---

CHANGELOG.md
app/assets/javascripts/govuk_publishing_components/components/cookie-banner.js
app/assets/javascripts/govuk_publishing_components/lib/cookie-functions.js

We had assumed that not passing `days` to `window.GOVUK.cookie()` set a default expiry, but it doesn't set any expiry date (therefore creating a session cookie).
This PR:
- Sets the expiry date of the consent cookie and the `seen_cookie_message` cookie to 1 year
- Adds a default expiry of 30 days to `window.GOVUK.cookie()`

Fix new cookie mechanism not being session based

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

Includes:
* Set the expiry of consent cookie to 1 year (PR #940)
* Sets the default expiry of cookies to 30 days if not specified (PR #940)

Version 17.3.0

---

CHANGELOG.md
app/views/govuk_publishing_components/components/docs/step_by_step_nav.yml
lib/govuk_publishing_components/presenters/page_with_step_by_step_navigation.rb
spec/components/contextual_footer_spec.rb
spec/features/contextual_navigation_spec.rb
spec/lib/govuk_publishing_components/presenters/page_with_step_by_step_navigation_spec.rb

Make it possible for the step by step side bar to appear in the side navigation for all content that uses the contextual navigation.
(Note: we will keep all content the same for the breadcrumbs and side nav as for step by steps elsewhere, we are not changing 'part of' for example.)
Update developer documentation with these changes.
**Logic:**
- If only one secondary step by step and no other step by steps linked - show secondary step by step and expand it
- If multiple secondary step by steps linked and no other step by steps linked - show "Part of" step by step with secondary step by steps
- If multiple secondary step by steps exceed 5 - do not show anything
- If one primary step by step and one/multiple secondary - Show primary and hide secondary
- If multiple primary and one/multiple …

Add the closed step by step for secondary content

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_contextual_breadcrumbs.html.erb
app/views/govuk_publishing_components/components/docs/contextual_breadcrumbs.yml
spec/components/contextual_breadcrumbs_spec.rb

The breadcrumb already has an inverse option, which turns the links white for rendering on a blue background. This PR adds an inverse option to the contextual breadcrumb component, which calls the breadcrumb component.
This is needed in finders where we are adding a blue banner to some finder headers.
Trello card: https://trello.com/c/A6eidvxn/799-implement-blue-topic-page-finder-headers-on-supergroup-finders-when-user-has-come-from-topic-page-l

Add inverse option to contextual breadcrumbs

---

spec/javascripts/components/cookie-banner-new-spec.js
spec/javascripts/components/cookie-functions-spec.js

We added logic in #940 which:
- Set the default expiry of cookies to 30 days, if not explicitly provided. This is because we were caught out by the expiry not being set and ending up with a session cookie instead.
- Set the expiry of the consent cookie to 1 year
- Set the expiry of seen_cookie_message to 1 year, to match the consent cookie
The above change was urgent and we didn't have time to write tests. This PR adds tests for that logic.

Add tests for new cookie expiry date logic

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/_button.scss

Inline buttons did not have any explicit spacing set between them. The only small spacing that appeared was down to (potentially) HTML whitespace.
This sets a margin-right of 10px on inline buttons, forcing the spacing to increase on desktop.
Mobile spacing should remain unchanged.
The spacing between the inline buttons used on the new cookie banner was too small.
**Link:** https://govuk-publishing-compon-pr-946.herokuapp.com/component-guide/cookie-banner

Increase inline button desktop spacing

---

CHANGELOG.md
app/assets/javascripts/govuk_publishing_components/components/cookie-banner.js
app/views/govuk_publishing_components/components/_cookie_banner.html.erb

- Adding `role="region"` and `aria-label="cookie banner"` to the cookie banner.
- Switching focus to the cookie banner confirmation message automatically once a user has clicked "Accept Cookies", to enable the confirmation message to be read automatically to screen-readers.
**Adding `role=region` and `aria-label=cookie banner`:** When running our [accessibility review](https://trello.com/c/X7EnjPLR/192-accessibility-review), we had a warning about the cookie banner not being included in any landmark region. This meant that a user navigating the page by landmark would miss the cookie banner. 
Note: Other landmark roles didn't seem to fit this use case, so I've gone for a generic 'region' with aria-label, but happy to take other suggestions!
**Confirmation message**: without this change, a …

Improve accessibility of the cookie banner

---

docs/pull_request_template.md

Update the Pull Request template to include What / Why / Visual Changes sections
This helps us to:
- set a standard for PR descriptions in the gem
- provides guidance on what to include (it's easy to forget to include the context of a change, for example)
- helps developers from outside your immediate team review the code
- helps new developers to contribute to the gem

Update Pull Request template

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_cookie_banner.html.erb

Removes `aria-live="polite"` as we are now explicitly setting focus on the confirmation message after accepting cookies (done in https://github.com/alphagov/govuk_publishing_components/pull/949).
The combination of `aria-live="polite"` and `aria-label="cookie banner"` doesn't seem to work well together - instead of announcing the confirmation message when accepting cookies, it read out the aria-label instead.

Fix cookie confirmation for screenreaders

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/_cookie-banner.scss

Hide the "Accept Cookies" button in the cookie banner when Javascript is not available
This change ties in with https://github.com/alphagov/frontend/pull/1881
At the moment, when Javascript is not enabled the cookie banner looks no different. However, the 'Accept Cookies' button does not work without Javascript - our cookie consent mechanism is based on Javascript at the moment. We therefore want to hide the "Accept Cookies" button. Users can still click "Cookie Settings" to go to `/help/cookies` and get more information.

Hide 'Accept Cookies' button when Javascript not available

---

app/assets/stylesheets/govuk_publishing_components/components/_govspeak-html-publication.scss
app/assets/stylesheets/govuk_publishing_components/components/govspeak/_advisory.scss
app/assets/stylesheets/govuk_publishing_components/components/govspeak/_attachment.scss
app/assets/stylesheets/govuk_publishing_components/components/govspeak/_call-to-action.scss
app/assets/stylesheets/govuk_publishing_components/components/govspeak/_charts.scss
app/assets/stylesheets/govuk_publishing_components/components/govspeak/_contact.scss
app/assets/stylesheets/govuk_publishing_components/components/govspeak/_example.scss
app/assets/stylesheets/govuk_publishing_components/components/govspeak/_footnotes.scss
app/assets/stylesheets/govuk_publishing_components/components/govspeak/_form-download.scss
app/assets/stylesheets/govuk_publishing_components/components/govspeak/_images.scss
app/assets/stylesheets/govuk_publishing_components/components/govspeak/_information-callout.scss
app/assets/stylesheets/govuk_publishing_components/components/govspeak/_legislative-list.scss
app/assets/stylesheets/govuk_publishing_components/components/govspeak/_place.scss
app/assets/stylesheets/govuk_publishing_components/components/govspeak/_stat-headline.scss
app/assets/stylesheets/govuk_publishing_components/components/govspeak/_steps.scss
app/assets/stylesheets/govuk_publishing_components/components/govspeak/_summary.scss
app/assets/stylesheets/govuk_publishing_components/components/govspeak/_tables.scss
app/assets/stylesheets/govuk_publishing_components/components/govspeak/_typography.scss
app/assets/stylesheets/govuk_publishing_components/components/govspeak/_warning-callout.scss
app/assets/stylesheets/govuk_publishing_components/components/print/_govspeak.scss

This PR updates the **Govspeak content** and **Govspeak content (HTML Publications)** components to use govuk-frontend instead of govuk_frontend_toolkit
To ease the review a bit I attach below comparison screen captures for both components

Update govspeak to use govuk-frontend mixins

---

docs/component_principles.md
docs/generate-a-new-component.md
docs/publishing-to-rubygems.md

Fix component conventions link in [`generate-a-new-component.md`](https://github.com/alphagov/govuk_publishing_components/blob/fix-conventions-link/docs/generate-a-new-component.md)
Update md paths to be absolute so we're not affected by the folder structure
Make sure we don't have broken links in our docs

Fix conventions link

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/_phase-banner.scss
app/views/govuk_publishing_components/components/_phase_banner.html.erb
app/views/govuk_publishing_components/components/docs/phase_banner.yml
spec/components/phase_banner_spec.rb

This adds an inverse mode to the phase banner so it can be used on a blue background.
The phase banner could be displayed over a blue background in an upcoming update to the topic finders ([finder-frontend#1204](https://github.com/alphagov/finder-frontend/pull/1204)). A `inverse` flag has been added that makes the phase banner legible when placed on a blue background.

Add an inverse mode for the phase banner

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/_heading.scss
app/views/govuk_publishing_components/components/_heading.html.erb
app/views/govuk_publishing_components/components/docs/heading.yml
lib/govuk_publishing_components/presenters/heading_helper.rb
spec/components/heading_spec.rb

**This change must not be merged until other PRs are raised to account for the sort-of-but-not-really breaking change that this PR represents. Turns out it's only a problem in collections, have [raised a PR ready for this change](https://github.com/alphagov/collections/pull/1160).**
- component previously used a custom scale to provide a variable bottom margin
- replacing this with the now-standard shared_helper way of doing this
- default options remain the same so there is no visual change in the component
- since the numbers in the two scales are different this will mean updating any instance of the component where a specific margin is called
This change is being done to remove redundant code and standardise how margin bottom is added to components.
No visual changes, but some PRs in …

Use shared_helper for heading margin

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Use shared_helper for heading margin (PR #958) - slightly breaking change for collections, but there's a [PR in place to deal with it](https://github.com/alphagov/collections/pull/1160).

Version 17.9.0

---

app/assets/stylesheets/govuk_publishing_components/components/_translation-nav.scss

Update `translation-nav.scss` to use govuk-frontend mixins and variables
To help [removing the dependency on the deprecated govuk_frontend_toolkit package](https://trello.com/c/ajPzDAOX).

Update translation-nav to use govuk-frontend

---

docs/component_conventions.md

Remove `pub-` prefix from component conventions
We don't use this prefix anymore and we don't have legacy code using it

Remove pub- prefix from component conventions

---

app/views/govuk_publishing_components/components/docs/accordion.yml
app/views/govuk_publishing_components/components/docs/layout_footer.yml
app/views/govuk_publishing_components/components/docs/layout_for_admin.yml
app/views/govuk_publishing_components/components/docs/layout_header.yml
app/views/govuk_publishing_components/components/docs/modal_dialogue.yml
app/views/govuk_publishing_components/components/docs/skip_link.yml
app/views/govuk_publishing_components/components/docs/tabs.yml
docs/develop-component.md

- Update documentation around 'experimental' tag
- Remove experimental tag for header, footer, skip link and admin layout (as they have been used by Content Publisher and Content Data for a year now, have been tested with users and been through rounds of user research)
- Align descriptions for experimental components
Keep the experimental tags up to date.

Update experimental statements

---

CHANGELOG.md
app/assets/javascripts/govuk_publishing_components/components/feedback.js
app/views/govuk_publishing_components/components/_feedback.html.erb
app/views/govuk_publishing_components/components/feedback/_survey_signup_form.html.erb
spec/javascripts/components/feedback-spec.js

Stop hardcoding a GA Client ID
As it stands the hardcoding of a google client id in the feedback footer is making it impossible to link feedback data to GA.
No changes. The only thing that this could have changed would be the no email survey link but I've checked to make sure that it won't.

Stop the hardcoding of a google client ID in the feedback footer

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Stop the hardcoding of a google client ID in the feedback footer (PR #957)

Version 17.11.0

---

CHANGELOG.md
app/assets/javascripts/govuk_publishing_components/components/cookie-banner.js
app/assets/stylesheets/govuk_publishing_components/components/_cookie-banner.scss

Removes all references to `gem-c-cookie-banner--new`
Some places in the code still reference the class `gem-c-cookie-banner--new` because we had to deploy with that code in place due to caching and the way static and frontend apps interact.
It has been a week since we removed the old code, so `gem-c-cookie-banner--new` should no longer be being used anywhere.

Remove new cookie banner references

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/_title.scss
app/views/govuk_publishing_components/components/_title.html.erb
app/views/govuk_publishing_components/components/docs/heading.yml
app/views/govuk_publishing_components/components/docs/hint.yml
app/views/govuk_publishing_components/components/docs/subscription-links.yml
app/views/govuk_publishing_components/components/docs/textarea.yml
app/views/govuk_publishing_components/components/docs/title.yml
spec/components/title_spec.rb

**Do not merge this PR until other PRs have been raised to account for the change in this component. Worst case scenario is that some titles won't have the correct bottom margin, so not exactly a breaking change but we want to catch it nonetheless.**
Updates the title component to use the govuk-spacing-scale for bottom margin, instead of using a custom scale previously defined. Uses the `shared_helper` for this.
This brings this component in line with other components that are now using the same mechanism for a variable bottom margin.
The component previously had a default margin top and bottom of 45px, scaling to 15px on mobile. The govuk spacing scale doesn't have an exact equivalent, so I've gone for the nearest, which is 40px, scaling to 25px on mobile.
For reference when updating …

[DO NOT MERGE] Change title margin option

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Remove references to old `gem-c-cookie-banner--new` class (PR #972)
* Change title margin option (PR #969)

Version 17.12.0

---

CHANGELOG.md
app/assets/javascripts/govuk_publishing_components/components/feedback.js
spec/javascripts/components/feedback-spec.js

https://trello.com/c/RVYM3DPP/1-3-survey-focus-skipping-content-12
This resets the focus back to the link that was activated to
open the form when it is closed.
Currently if the user closes the "not useful" or "something is wrong" feedback
form the focus is lost. This is an accessibility issue as keyboard users end up
back at the start of the page, and screenreader users are unaware of where they
are on the page.

Reset focus when user closes feedback form before submission

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/_tabs.scss

Trello: https://trello.com/c/dnszYbmt/7-accessibility-of-tabs-on-govuk
Moves CSS 'overrides' for the tab component from Frontend into the gem.
Follow on PR in Frontend: https://github.com/alphagov/frontend/pull/1898
The tab styles are affected by `.content-block` styles which are [defined in Static](https://github.com/alphagov/static/blob/a815620cada7ea1c65428c1c3b3ac4dbe28977bf/app/assets/stylesheets/helpers/_text.scss). In Frontend, there are [overrides for this problem](https://github.com/alphagov/frontend/blob/master/app/assets/stylesheets/application.scss#L70). However, they don't work properly with our current tabs on mobile (the left spacing is incorrect). This corrects the overrides and moves them into the gem, so they're in one common place and more visible to those making …

Move tab style overrides to the gem

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

Includes:
* Make some tab component styles more specific to override `.content-block` (PR #978)

Version 17.12.2

---

app/views/govuk_publishing_components/components/_checkboxes.html.erb
app/views/govuk_publishing_components/components/_radio.html.erb
app/views/govuk_publishing_components/components/docs/checkboxes.yml
app/views/govuk_publishing_components/components/docs/radio.yml
lib/govuk_publishing_components/presenters/checkboxes_helper.rb
spec/components/checkboxes_spec.rb
spec/components/radio_spec.rb

Add support for description text
A lot of "one question per page" views on GOV.UK have a description under the title. This means that "hacks" are being put in place to deliver user need.
Example:
https://www.gov.uk/prepare-business-uk-leaving-eu?page=2

Add description text

---

CHANGELOG.md
app/assets/javascripts/govuk_publishing_components/components/feedback.js
app/assets/stylesheets/govuk_publishing_components/components/_feedback.scss
app/views/govuk_publishing_components/components/feedback/_problem_form.html.erb
app/views/govuk_publishing_components/components/feedback/_survey_signup_form.html.erb

Add a check to the feedback form logic so that we don't insert the links if they're already present, to avoid duplication.
The hidden input for GA ID and the "Don't have an email address?" link are inserted using Javascript. This is done when the user clicks 'No' within the feedback form and the form opens. However, there is no check for whether the links have already been inserted. This means that the links are appended each time the user opens the 'No' form.
*Replication Steps:*
- Click "No" on the feedback form.
- Without interacting with the form itself, close the form via the Close button
- Click "No" on the feedback form again
- Duplicate 'Don't have an email address?' links will be visible
Add spacing around the feedback form on small screen sizes

Fix duplicate link bug with feedback form and fix spacing on small viewport

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_checkboxes.html.erb
app/views/govuk_publishing_components/components/_radio.html.erb
spec/components/checkboxes_spec.rb
spec/components/radio_spec.rb

Change paragraph to div for descriptions to support govspeak
Some descriptions that are rendered need to use govspeak to render them.
Having a paragraph breaks the following tests:
```
Scenario: Arrive at the business finder through Q&A              # features/finders.feature:245
Given the business finder QA exists                            # features/step_definitions/filtering_steps.rb:13
When I visit the business finder Q&A                           # features/step_definitions/qa_steps.rb:82
And I select choice "Aerospace"                                # features/step_definitions/qa_steps.rb:94
And I submit my answer                                         # features/step_definitions/qa_steps.rb:56
In backend response: '54:5: ERROR: Unexpected end tag : p' at line 54 col 5 (code 76). …
```

Change paragraph to div for descriptions to support govspeak

---

CHANGELOG.md
app/assets/javascripts/govuk_publishing_components/components/cookie-banner.js
spec/javascripts/components/cookie-banner-spec.js

Update cookie banner component to hide if cross-origin message has `hideCookieBanner` set to `true`.
The cookie banner script listens for cross-origin messages and if they're coming from a `publishing.service.gov.uk` domain and have `hideCookieBanner` set to `true` it hides the banner. 
This behaviour is required for [previewing GOV.UK pages from draft stack in Content Publisher without obstructing the view](https://github.com/alphagov/content-publisher/pull/1240).
[Trello card](https://trello.com/c/QXbQKBG3)

Hide cookie banner if cross-origin message has hideCookieBanner set to true

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

Includes:
* Change paragraph to div for descriptions to support govspeak (PR #985)
* Update cookie banner component to hide if cross-origin message has `hideCookieBanner` set to `true` (PR #988)

bump to version 17.14.0

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/_document-list.scss
app/views/govuk_publishing_components/components/_document_list.html.erb
app/views/govuk_publishing_components/components/docs/document_list.yml
spec/components/document_list_spec.rb

Add an option to the document list component to remove underlines from links.
We intend to use the component for search results in finder-frontend, but the current design doesn't have underlines on the links. Adding them adds to the visual clutter of the search results pages and leads to a much bigger conversation, so it seems more sensible to have this option available.
Option to not have underlines looks like this:

Add no underline option to document list component

---

app/assets/stylesheets/govuk_publishing_components/components/_search.scss

Update `search.scss` to use govuk-frontend mixins and variables
To help [removing the dependency on the deprecated govuk_frontend_toolkit package](https://trello.com/c/ajPzDAOX).

Update search component to use govuk-frontend

---

app/assets/stylesheets/govuk_publishing_components/components/_image-card.scss
app/views/govuk_publishing_components/components/docs/image_card.yml

Update `image-card.scss` to use govuk-frontend mixins and variables and refactor code to be mobile first
Fix source path for [missing image](https://govuk-publishing-components.herokuapp.com/component-guide/image_card/large_version/preview).
To help [removing the dependency on the deprecated govuk_frontend_toolkit package](https://trello.com/c/ajPzDAOX).
No visual changes. Attached desktop and mobile diff (left is master, right is current branch)

Update image-card to use govuk-frontend

---

app/views/govuk_publishing_components/components/_meta_tags.html.erb
lib/govuk_publishing_components/presenters/meta_tags.rb

**Note: this card is for setting up data tracking, it is not about doing the analysis**
We want to be able to track usage of the step by step side bar and the breadcrumb on secondary content.
Is the data tracking in place? What are the metrics we are trying to measure?
Would we be able to answer these questions:
- Does adding step by step navigation make a difference to user journeys (eg next page paths, exits) for *users who land directly* (eg from Google) on a secondary content page with step by step navigation? And compared to users who come from GOV.UK pages?
- Does the step by step navigation being closed make a difference to user journeys compared to the step by step being opened at a certain step, for secondary content?
We want to add a new feature to 'step by step publisher' that …

Set up data tracking for navigation on secondary content

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

Includes:
* Track when primary or secondary step by step are shown (PR #989)
* Update image-card to use govuk-frontend (PR #967)
* Update search to use govuk-frontend (PR #977)

bump version to 17.16.0

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_hint.html.erb
spec/components/radio_spec.rb

Use a block-element for the hint message component.
Enable the component to have either block or non-block elements inside.
The current need is to render a list of items in the hint message for Content Publisher.
[Trello card](https://trello.com/c/OJwGOdvd)

Use div elements for hint

---

CHANGELOG.md
app/assets/javascripts/govuk_publishing_components/components/feedback.js
app/views/govuk_publishing_components/components/_feedback.html.erb
app/views/govuk_publishing_components/components/feedback/_survey_signup_form.html.erb
spec/javascripts/components/feedback-spec.js

The feedback form, when the user clicks 'no' and inputs their email address to receive a survey, is broken, as documented [in this issue](https://github.com/alphagov/govuk_publishing_components/issues/997). This PR restores the missing field.
Feedback form isn't working properly across GOV.UK.
Fixes https://github.com/alphagov/govuk_publishing_components/issues/997

Restore missing field to feedback survey form

---

CHANGELOG.md
app/assets/javascripts/govuk_publishing_components/components/cookie-banner.js
spec/javascripts/components/cookie-banner-spec.js

This is an alternative to the approach taken on #988 (which causes the cookie banner to flicker before removing it). This approach checks if the component is rendered in an iframe and the parent document location is a publishing domain (*.publishing.service.gov.uk) to prevent the cookie banner from being displayed.
This behaviour is required for [previewing GOV.UK pages from draft stack in Content Publisher without obstructing the view](https://github.com/alphagov/content-publisher/pull/1240).
[Trello card](https://trello.com/c/QXbQKBG3)

Remove cross origin approach and detect parent document location

---

lib/govuk_publishing_components/presenters/page_with_step_by_step_navigation.rb

Changes content item to have symbolic keys.
We have to call deep_symbolize_keys because we're often dealing with a
parsed JSON document which will have string keys by default, but our
components use symbol keys and we want consistency.
None
This was not added to change notes as this is a bug fix and does not provide any usefulness in change notes
https://trello.com/c/LU6AAcOk/14-step-by-step-set-up-data-tracking-for-navigation-on-secondary-content

Changes content item to have symbolic keys

---

CHANGELOG.md
config/initializers/assets.rb

This removes the expectation that sprockets is available when the Rails initializers run
Not all applications that consume govuk_publishing_components have sprockets installed. [Publishing API](https://github.com/alphagov/publishing-api/pull/1549) is one of those.
None

Only setup asset precompilation when assets are available

---

docs/pull_request_template.md

Add view changes link to PR template
This will help users view changes easily, this was included in the template previously but has been removed since.

Add view changes link to PR template

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/_tabs.scss

When we added an overwrite that deals with styles leaking from static, we only did the overwrite for the desktop mode.
It is currently missing the [default margin bottom](https://github.com/alphagov/govuk-frontend/blob/master/src/govuk/components/tabs/_tabs.scss#L22) and the [JS-enabled desktop style that removes the default margin](https://github.com/alphagov/govuk-frontend/blob/master/src/govuk/components/tabs/_tabs.scss#L61) resulting in a lack of spacing (see visual changes) between `govuk-tabs__list` and the first container. This PR replicates the code from govuk-frontend in this overwrite (with the hope that at some point will not be needed anymore).
We want to keep the styles in sync with govuk-frontend. 
Before fix
After fix
[Trello card](https://trello.com/c/95Mdb8FV)

Add missing margin to the tabs list overwrite

---

CHANGELOG.md
app/assets/javascripts/govuk_publishing_components/lib/govspeak/youtube-link-enhancement.js

The documentation for the YouTube Player API states that:
> If you are using the IFrame API, which means you are setting the enablejsapi parameter value to 1, you should always specify your domain as the origin parameter value.
https://developers.google.com/youtube/player_parameters#origin
We're currently seeing a Smokey error that suggests the origin is not being set correctly for the player:
```
https://s.ytimg.com/yts/jsbin/www-widgetapi-vfl2284kc/www-widgetapi.js 105 Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://www.youtube-nocookie.com') does not match the recipient window's origin ('https://draft-origin.publishing.service.gov.uk'). (Capybara::Chromedriver::Logger::JsError)
```
I'm not sure if this change will fix the Smokey error, but the …

Add origin to YouTube Player API

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

Includes:
* Remove expectation that sprockets is installed when used in a Rails app (PR #999)
* Fix tabs list overwrite on mobile (PR #1003)
* Set the origin when rendering the YouTube player (PR #1004)

Version 17.19.0

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/_subscription-links.scss

Changes the CSS of subscription links to not use a negative margin on the parent list to compensate for the regular margin around the individual list items; instead, apply right margin only to list items to preserve spacing, but use `last-child` to remove it from the last item (this wouldn't be necessary but in finder-frontend they're right-aligned).
This should fix a long standing issue on finders, where the negative margin causes [this overlap problem](https://www.gov.uk/find-eu-exit-guidance-business?parent=&keywords=&sector_business_area%5B%5D=aerospace&order=topic) on the right of the screen.
There should be no visual changes, however it turns out there's a very small change, because the negative margin on the `ul` was `-7.5px` and the margin on the `li` elements was `10px`. This …

Change subscription links CSS

---

app/views/govuk_publishing_components/components/docs/input.yml

This link 404s, I'm not sure it ever worked.

Correctly link to the text input component in the Design System

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/_select.scss
app/views/govuk_publishing_components/components/_select.html.erb
app/views/govuk_publishing_components/components/docs/select.yml
spec/components/select_spec.rb

Adds a full width option to the select component, which sets the select element itself to be `width: 100%;`.
This isn't included in the Design System for reasons but we're using this component in finder-frontend's search and adding CSS there to make it full width, so it seemed more in line with our component principles to add it into the component itself.
No visual changes unless you select this option, obviously.
https://govuk-publishing-compon-pr-1012.herokuapp.com/select
Trello card: https://trello.com/c/w34QlutZ/910-investigate-adding-an-option-to-the-select-component-for-width-100

Add full width option to select component

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_government_navigation.html.erb
spec/components/government_navigation_spec.rb

Update Statistics header link to point to the new supergroup statistics finder.
Update the statistics link in the header to point to the new supergroup stats finder.
Whitehall finders are being replaced by supergroup finders. The stats finder is the last to be transitioned. 
None
https://trello.com/c/CAtBdn4k/510-change-whitehall-header-link-to-stats-finder-s

Update Statistics header link

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_subscription-links.html.erb
app/views/govuk_publishing_components/components/docs/subscription-links.yml
spec/components/subscription_links_spec.rb

Adds a setting to set the lang attribute set on each link in the 'Subscription links' component.
Subscription links can appear on translated pages, but if there's no available translation when using `t()` it falls back to English. When this is the middle of a section thats marked up as being in another language it causes problems - the screenreaders try to parse the English as another language.
For example - the [Korean version of the page for Scott Wightman](https://www.gov.uk/government/people/scott-wightman.ko)
The circled 'Get email alerts' parent link should have `lang="en"`.
No visual changes - only reflected in the markup.
Before:
After:
- https://govuk-publishing-compo-pr-1019.herokuapp.com/component-guide/subscription-links

Allow language to be set on subscription links

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/_select.scss

This is a fix for a problem noticed during user research where a participant had their phone text size set very high. This resulted in the text in the select component being cropped slightly. This can be reproduced using Firefox's 'zoom text only' option, and it looks like this:
I've raised an [issue in govuk-frontend](https://github.com/alphagov/govuk-frontend/issues/1519) but it's likely that their fix will not help on GOV.UK as we're using compatibility mode for elements and toolkit, and this issue apparently relates to the base font size.
The problem is caused by the height of selects being set at 40px. The best solution seems to be to set the height using `em`, so that it scales with the text size of the select. An alternative is to set it using `rem` but since the component guide …

Fix for select height zoom problem

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/govspeak/_attachment.scss
app/assets/stylesheets/govuk_publishing_components/components/govspeak/_call-to-action.scss
app/assets/stylesheets/govuk_publishing_components/components/govspeak/_charts.scss
app/assets/stylesheets/govuk_publishing_components/components/govspeak/_contact.scss
app/assets/stylesheets/govuk_publishing_components/components/govspeak/_example.scss
app/assets/stylesheets/govuk_publishing_components/components/govspeak/_footnotes.scss
app/assets/stylesheets/govuk_publishing_components/components/govspeak/_fraction.scss
app/assets/stylesheets/govuk_publishing_components/components/govspeak/_information-callout.scss
app/assets/stylesheets/govuk_publishing_components/components/govspeak/_legislative-list.scss
app/assets/stylesheets/govuk_publishing_components/components/govspeak/_media-player.scss
app/assets/stylesheets/govuk_publishing_components/components/govspeak/_stat-headline.scss
app/assets/stylesheets/govuk_publishing_components/components/govspeak/_tables.scss
app/assets/stylesheets/govuk_publishing_components/components/govspeak/_typography.scss
app/assets/stylesheets/govuk_publishing_components/components/govspeak/_warning-callout.scss
app/views/govuk_publishing_components/components/docs/button.yml
app/views/govuk_publishing_components/components/docs/contextual_breadcrumbs.yml
app/views/govuk_publishing_components/components/docs/fieldset.yml
docs/component_conventions.md
spec/dummy/config/routes.rb

The main component guide is now hosted on https://components.publishing.service.gov.uk.
We can't use the crown and font on non *.gov.uk sites. It looks better.

Use components.publishing.service.gov.uk

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_subscription-links.html.erb
spec/components/subscription_links_spec.rb

Checks that the locale attributes being passed into the subscription links components are falsey - if falsey then `nil` is used.
When a `false` was being used as a parameter in the subscription components, it was being cast and used as a string - leading to `lang="false"`. Not a big deal, since (according to the spec) this should be ignored, but worth fixing.
None.
https://govuk-publishing-compo-pr-1021.herokuapp.com/

Normalise falsey values to nil to prevent `lang="false"`

---

app/views/govuk_publishing_components/components/docs/label.yml

- fix typo
- explain that the obvious error with the appearance is okay
Because I read this and thought there was a problem - even though it turned out I'd written it six months ago.
No visual changes. Tiny change so no need for CHANGELOG update.

Fix label documentation for radio option

---

Procfile
app/views/govuk_publishing_components/component_guide/index.html.erb
startup.sh

The dummy app in `spec/dummy` has 2 purposes.
First, it's a sample app that is used in tests to check the functionality of having components inside the application.
Secondly, it is hosted on https://components.publishing.service.gov.uk as  a reference.
This adds a environment variable to the startup scripts for the reference app, so that we can hide the components that are only used for testing.

Hide test components in the dummy app

---

app/views/govuk_publishing_components/components/docs/table.yml

Adds a description to the 'sortable' option for the table component.
It wasn't obvious that this is meant to be handled server side and not by the component itself. I thought it was broken.
No changes.
https://govuk-publishing-compo-pr-[PR-NUMBER].herokuapp.com/component-guide/table
Fixes https://github.com/alphagov/govuk_publishing_components/issues/1031

Clarify table sortable head documentation

---

app/assets/stylesheets/govuk_publishing_components/components/_contents-list.scss

Fixes https://github.com/alphagov/govuk_publishing_components/issues/1032
The dash in contents lists was previously added using a before element containing a dash and a space character, with a negative margin left to draw it out of the containing element and leave the rest of the text indented. Unfortunately this was never quite precise enough and so the first line was indented less than any lines that wrapped below, resulting in the layout inconsistency here (note that 'Lorem' is a few px further left than the lines below).
This change applies absolute positioning to the same element and changes the left margin on the surrounding list element to padding. This removes the inconsistent indenting.
In addition, the before element is given a width smaller than the parent left padding and …

Fix indent bug for wrapped content list links

---

app/assets/stylesheets/govuk_publishing_components/components/_title.scss
app/views/govuk_publishing_components/components/_title.html.erb

Fix focus styles on page title component context link. Fixes https://github.com/alphagov/govuk_publishing_components/issues/1030
They were wrong.
Before:
After:
https://govuk-publishing-compo-pr-[PR-NUMBER].herokuapp.com/component-guide/title

Fix focus style on page title context link

---

app/assets/stylesheets/govuk_publishing_components/components/_image-card.scss

- in small mode (default) overlaying :after link element needs to be positioned 15px from left and right, because small image cards sit next to each other and include their own spacing
- in large mode image card is full width so :after link overlay should be full width, not 15px from left and right
Link overlay in large mode doesn't quite cover the image.
Before (:after element highlighted)
After:
https://govuk-publishing-compo-pr-1039.herokuapp.com/component-guide/image_card

Fix image card overlay link in large mode

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/_contents-list.scss
app/views/govuk_publishing_components/components/_contents_list.html.erb
app/views/govuk_publishing_components/components/docs/contents_list.yml
spec/components/contents_list_spec.rb

We have a need for using the contents list component within a topic page header, which is blue.
https://govuk-publishing-compo-pr-1037.herokuapp.com/component-guide/contents_list/inverse

Add inverse flag to contents list component

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* BREAKING: Update to [govuk-frontend 3.0.0](https://github.com/alphagov/govuk-frontend/releases/tag/v3.0.0) (PR #1010)
You must make the following changes when you migrate to this release:
- Check application's dependencies on deprecated projects (`govuk_frontend_toolkit`, `govuk_elements_rails` and `govuk_template`) and set [compatibility flags](https://govuk-frontend-review.herokuapp.com/docs/#settings/compatibility) appropriately before importing `govuk_publishing_components`. Note that all applications that rely on a layout from static depend indirectly on `govuk_template` and most frontend applications rely on `govuk_frontend_toolkit`. [Example commit](https://github.com/alphagov/calendars/commit/edd649e6c2c7732d4a2e44713dd9463feeaf990b)
- Update [`govuk-colour` …

Breaking Version 18.0.0

---

CHANGELOG.md
govuk_publishing_components.gemspec

We currently ship everything in `node_modules`, which includes the dev dependencies. This changes it to only include in the gem files from govuk-frontend. This will significantly decrease the size of the resulting gem.

Make the gem smaller

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_button.html.erb

Fix how SVG is being rendered in a start button
Because it's currently encoding the SVG tags and it's showing it as code
No visual change in the gem, but in applications:
https://govuk-publishing-compo-pr-1043.herokuapp.com/
Thanks @andysellick for reporting this.

Fix start button

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

Contains a few fixes:
* Make the gem _slimmer_ by only including GOV.UK Frontend (#1041)
* Remove unused image assets previously used in the button component and references to zombie image assets (#1042)
* Fix start button showing SVG code (#1043)

Release 18.0.1

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_related_navigation.html.erb
app/views/govuk_publishing_components/components/docs/related_navigation.yml
app/views/govuk_publishing_components/components/related_navigation/_section.html.erb
lib/govuk_publishing_components/presenters/related_navigation_helper.rb
spec/components/related_navigation_spec.rb
spec/lib/govuk_publishing_components/presenters/related_navigation_helper_spec.rb

Adds a `locale` option for the related navigation component so a [BCP47 language tag](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/lang#Language_tag_syntax) can be used to show what language the link is in.
If the locale passed for the link is the same as the locale for the page, no `lang` attribute will appear. Only when the locale for the link is different to the locale for the page is the `lang` attribute needed.
Trello card: https://trello.com/c/Cjf9IOHK/26-3-mark-language-on-related-links
The related links can sometimes be in different languages to each other and to the page. The example is taken from [Chinese translation of the PM's statement on the EU referendum outcome](https://gov.uk/government/speeches/eu-referendum-outcome-pm-statement-24-june-2016.zh). …

Add locale option to related navigation component

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/_related-navigation.scss

The line height has been reduced from 1.5 to 1.28 for larger screens and to 1.45 for smaller screens to remove the half overlap when a link ran over two lines. Part of #1028.
When a link stretched over two lines, the yellow background of the lower line partially covered the black underline of the upper line. After discussion with @soniaturcotte it was decided that it would be better to reduce the line height to overlap the upper black line completely - increasing the line height to show both the upper and lower underlines led to a set of links with too much space between them.
Before:
After:

Related links focus state fix

---

govuk_publishing_components.gemspec

Restoring some dependencies from `node_modules` - we used to include everything but this was unnecessary so it was reduced to just `govuk-frontend`, but it looks like some other things are also needed.
- axe-core/axe.js
The last versions of the gem (18.1.0 and 18.0.1) appear to be broken because of missing files not included from `node_modules`.

Restore node_modules gem dependencies

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/_share-links.scss
app/views/govuk_publishing_components/components/docs/share_links.yml

It turns out the use of flexbox in this component wasn't quite working as intended. While it was providing some evenly sized columns, the options I'd chosen meant that there was no difference between that and using `float: left` with a fixed width.
New plan: CSS grid with a fallback. This now uses columns that have a minimum width of 200px but expand equally to fill the remaining space, collapsing into fewer columns as the page gets narrower.
CSS grid isn't supported by any version of IE, so the fallback there is to set a min-width of 200px and float each of the column items (and clearfix the parent). There's no browser hack involved, the grid styles override the floating if the browser recognises them and the clearfix is irrelevant.
This PR also simplifies the spacing between the links …

Fix share links columns option layout

---

CHANGELOG.md
govuk_publishing_components.gemspec

Restoring some dependencies from `node_modules` - we used to include everything but this was unnecessary so it was reduced to just `govuk-frontend`, but it looks like some other things are also needed.
- jquery
Follows on from https://github.com/alphagov/govuk_publishing_components/pull/1048
Previous versions of the gem (18.1.0 and 18.0.1) appear to be broken because of missing files not included from `node_modules`. This was fixed in 18.1.1 but investigation suggests that even though jquery wasn't included it is needed. I think it's working without jquery in apps because the apps already pull in jquery from another source, but we should include this for the future.

Restore jquery as gem dependency

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Restore jquery as gem dependency (PR #1051)
* Fix share links columns option layout (PR #1050)

Version 18.1.2

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/_image-card.scss

- when image card drops below 320px (unlikely, admittedly) it collapses into a single column but the margins are broken
- also the sass is a bit confusing
- this commit restructures the sass to make it more readable and fixes this problem
- behaviour should be (for standard image card): from 320px two columns, from 640px one column
- behaviour is perhaps not ideal (mobile with two columns is a little squished in some cases) but changing it is outside scope
- this commit does not change the behaviour, it only fixes the brokenness below 320px
The likelihood of anyone using a device narrower than 320px is very low, but this PR also makes the code more readable. Having said that, I'm not 100% sure I understand the new govuk-frontend V3 mixins for breakpoints and columns.
Before:
After:
I've …

Fix image card responsiveness

---

app/assets/stylesheets/govuk_publishing_components/components/_layout-header.scss
app/views/govuk_publishing_components/components/_layout_header.html.erb

Prevents the header title and logo from overlapping. Partially mends #1029 (this pull request doesn't fix the overlap of the 'Menu' button).
The overlap looked broken and made it difficult to read the links. 
Before:
After:
https://govuk-publishing-compo-pr-1057.herokuapp.com/component-guide/layout_header/with_navigation/preview

Prevent header navigation and title overlapping

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_title.html.erb
app/views/govuk_publishing_components/components/docs/title.yml
spec/components/title_spec.rb

Add ability to pass in a language param for 
Sometimes the page is translated but we don't have a translation for the page type string used in the contextual header, we need to mark this up for semantics and accessibility
https://govuk-publishing-compo-pr-1056.herokuapp.com/

Make contextual title accept and present lang parameter

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/_all_components.scss
app/assets/stylesheets/govuk_publishing_components/components/_summary-list.scss
app/views/govuk_publishing_components/components/_summary_list.html.erb
app/views/govuk_publishing_components/components/docs/summary_list.yml
spec/components/summary_list_spec.rb

This component is based on the [summary list component in govuk-frontend](https://design-system.service.gov.uk/components/summary-list/).
The API was modelled after the [summary component in Content Publisher](https://content-publisher.integration.publishing.service.gov.uk/component-guide/summary) as it should be replaced with this component after it gets released.
This component is used already in Content Publisher and it's needed in Collections Publisher. It's also the only missing component from the Design System
https://govuk-publishing-compo-pr-1061.herokuapp.com/component-guide/summary_list
[Trello card](https://trello.com/c/arYq0tST)

Add summary list component

---

CHANGELOG.md
app/assets/javascripts/govuk_publishing_components/components/checkboxes.js
spec/javascripts/components/checkboxes-spec.js

Checkboxes javascript is broken - checking a parent of a nested group should check all the children, and checking a child should uncheck the parent:
`govuk-frontend` V3 introduced namespacing for component JS prefixed with `govuk-`. We have custom js that acts on that module call, but it wasn't updated.
https://govuk-publishing-compo-pr-1065.herokuapp.com/checkboxes/checkbox_items_with_nested_checkboxes/

Fix nested checkboxes js

---

CHANGELOG.md
app/views/govuk_publishing_components/components/docs/button.yml
lib/govuk_publishing_components/presenters/button_helper.rb
spec/components/button_spec.rb

Adds two optional parameters to the button component to let the `value` and `name` attributes be set.
A button's value is only sent as part of a form when the button is used to submit the form - having multiple buttons set with different values means that we can tell which button submitted a form. 
No visual changes - just code changes.
Before:
```html
<button class="gem-c-button govuk-button" type="submit">
This is the button text
</button>
```
After:
```html
<button 
class="gem-c-button govuk-button" 
type="submit" 
name="this_is_the_name" 
value="this_is_the_value"
>
This is the button text
</button>
```
https://govuk-publishing-compo-pr-1059.herokuapp.com/component-guide/button/with_name_and_value_set

Name and value can be set on button component

---

CHANGELOG.md
app/views/govuk_publishing_components/components/docs/input.yml
spec/components/input_spec.rb

**This PR has been updated and no longer does what it originally did.**
Consolidate the aria attribute documentation for the input component.
A possible future change (for more than just this component) could be to pass any required aria attributes to components rather than having to add new options for each new use case, as below.
```
<%= render "govuk_publishing_components/components/input", {
label: {
text: "This is an example only and may not work with a screen reader"
},
name: "labelledby",
aria: {
describedby: "wrapper",
controls: "wrapper"
}
} %>
```
```
aria ||= []
<%= tag.input name: name,
aria: aria
%>
```
https://govuk-publishing-compo-pr-1062.herokuapp.com/component-guide/input

Consolidate input aria documentation and tests

---

app/views/govuk_publishing_components/components/docs/summary_list.yml

The Summary List component can render with or without a title,
but currently this is not clear from the documentation.
Arises from https://github.com/alphagov/collections-publisher/pull/703#pullrequestreview-280305661.
N/A

Add summary_list example without title property

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/_share-links.scss
app/views/govuk_publishing_components/components/docs/share_links.yml

Make the columns narrower in the 'columns' option for share links.
Before:
After:
This option is only used in one place, where the link text is much smaller and more realistic (e.g. 'Facebook' preceded by 'Share on' in visually hidden text) and this width works much better as the screen gets smaller.
https://govuk-publishing-compo-pr-1074.herokuapp.com/component-guide/share_links/
Trello card: https://trello.com/c/ky5WMr5L/181-look-into-share-links-layout-on-mobile

Adjust share links column width

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_summary_list.html.erb
app/views/govuk_publishing_components/components/docs/summary_list.yml
spec/components/summary_list_spec.rb

The Design System implementation of summary_list allows rendering
without borders between the summary_list rows:
https://design-system.service.gov.uk/components/summary-list#summary-list-without-borders
However, govuk_publishing_components implementation didn't provide
a way of hooking into this. I have now added a 'borderless' field
which defaults to 'false', but when 'true' will add the necessary
class to remove borders.
This is depended on by https://github.com/alphagov/collections-publisher/pull/703 (Trello: https://trello.com/c/qXVCEouI/23-show-the-content-title-slug-introduction-description-using-the-summary-component)
https://govuk-publishing-compo-pr-1073.herokuapp.com/component-guide/summary_list

Allow summary_list to render without borders

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/_all_components.scss
app/assets/stylesheets/govuk_publishing_components/_all_components_print.scss
app/assets/stylesheets/govuk_publishing_components/components/_step-by-step-nav.scss
app/assets/stylesheets/govuk_publishing_components/components/helpers/_variables.scss
app/assets/stylesheets/govuk_publishing_components/components/mixins/_margins.scss
app/assets/stylesheets/govuk_publishing_components/components/print/_step-by-step-nav.scss

@alex-ju i needed to do this for another reason, apologies if I'm duplicating work you've already done.
Remove the last sass dependencies from the gem, which were in the step by step component. Due to the slightly complex nature of this component I've had to write a custom font mixin, as the govuk-frontend mixins have undesired responsive font-sizing behaviour.
The gem still seems to require `govuk_frontend_toolkit` to initialise the JS properly, so I've not removed it fully.
Also improves the print styles for the step nav component.
We want to remove this dependency.
Changes should only affect the step by step navigation component. Visually should be identical, but there do seem to be some very minor differences, which I think is probably due to the font face change. Also had to choose a …

Remove govuk_frontend_toolkit sass dependencies

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/_image-card.scss

Fixes the missing margin beneath the component, as shown here:

Restore margin bottom to the image card

---

Gemfile.lock
govuk_publishing_components.gemspec

Version 3.142.4 of [selenium-webdriver](https://rubygems.org/gems/selenium-webdriver) released on 2nd Sept
has caused problems for one of our tests. Locking into the
previous version (May 21st) fixes the build.
Here is the test this fixes:
```
Failures:
1) Component example with automated testing shows accessibility violations on the page and through browser console
Failure/Error: expect(page.driver.browser.manage.logs.get(:browser).map { |e| e.message if e.message.match(/Accessibility issues/) }).not_to be_empty
Selenium::WebDriver::Error::WebDriverError:
unexpected response, code=404, content-type="text/plain"
unknown command: session/80b61401a648837e27061fca0812c0a8/se/log
```

Fix Jenkins by locking version of selenium-webdriver

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/_all_components.scss
app/assets/stylesheets/govuk_publishing_components/components/_contents-list.scss
app/assets/stylesheets/govuk_publishing_components/components/_related-navigation.scss
app/assets/stylesheets/govuk_publishing_components/components/_share-links.scss
app/assets/stylesheets/govuk_publishing_components/components/mixins/_govuk-template-link-focus-override.scss

This explicitly sets the focus state for some links that otherwise don't inherit all of the necessary styles.
This is to support the work in government-frontend detailed here: https://trello.com/c/0OfIgpul/51-5-update-government-frontend-to-govukpublishingcomponents-v18-with-compatibility-mode-on
Screenshots are taken from examples of the component in use on gov.uk
https://govuk-publishing-compo-pr-1071.herokuapp.com/
Note: The black colour is not coming through on some of these components and I'm still trying to track down why. This PR fixes the contents list including colour, and also fixes the underlines for the other components so seemed worth raising on the way to that full fix.

Explicitly set focus states

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/_all_components.scss
app/views/govuk_publishing_components/components/_summary_list.html.erb
app/views/govuk_publishing_components/components/docs/summary_list.yml
spec/components/summary_list_spec.rb

- Adds option to override 'Edit' link text
- Fixes SASS configuration (looks like it was accidentally removed in #1069)
- Refactors fixture data to use YAML inheritance, as the number of examples are growing
We have a requirement to render a 'Reorder' link in place of an 'Edit' link.
This still makes sense in the context of the screen reader text.
'Edit' is now the default edit link text if none is specified, but can be
overridden with the new 'edit.link_text' property.
Trello: https://trello.com/c/UlgsMO0Q/45-overhaul-the-steps-section-and-move-the-add-step-button-to-it-and-show-it-in-the-summary-component
Fixed CSS import:
|Before|After|
|------|------|
|<img width="973" alt="Screen Shot 2019-09-03 at 08 37 32" src="https://user-images.githubusercontent.com/5111927/64153669-3b924980-ce27 …

Override edit link text on summary-link component

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* **BREAKING:** Remove govuk_frontend_toolkit sass dependencies (PR #1069)
* This will break apps that rely on mixins and variables from govuk_frontend_toolkit - you must replace these with mixins and variables from GOV.UK Frontend
* Restore margin bottom to the image card (PR #1079)
* Allow summary_list to render without borders (PR #1073)
* Explicitly set focus states (PR #1071)
* Override edit link text on summary-link component (#1076)

Version 19.0.0

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/_attachment.scss
app/assets/stylesheets/govuk_publishing_components/components/_document-list.scss
app/assets/stylesheets/govuk_publishing_components/components/_image-card.scss
app/assets/stylesheets/govuk_publishing_components/components/_metadata.scss
app/assets/stylesheets/govuk_publishing_components/components/_organisation-logo.scss
app/assets/stylesheets/govuk_publishing_components/components/_textarea.scss
app/views/govuk_publishing_components/components/_attachment.html.erb
app/views/govuk_publishing_components/components/docs/attachment.yml
app/views/govuk_publishing_components/components/docs/image_card.yml

Some of the components have spacing issues with focus states since the `govuk-frontend` V3 changes, as detailed [in this issue](https://github.com/alphagov/govuk_publishing_components/issues/1028). This PR includes fixes for  those issues.
Changes the following components:
Fixes https://github.com/alphagov/govuk_publishing_components/issues/1028
Document list before:
Document list after:
Image card before:
Image card after:
Textarea before:
Textarea after:
Metadata before:
Metadata after:
Organisation logo before:
Organisation logo after:
https://govuk-publishing-compo-pr-1054.herokuapp.com/component-guide/

Fix components focus state spacing

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_inset_text.html.erb
app/views/govuk_publishing_components/components/docs/inset_text.yml
spec/components/inset_text_spec.rb

Can now pass an arbitrary block to the inset-text component to
have content rendered inset. If both 'text' and a block are
provided, 'text' takes precedence (mutually exclusive).
This is a compromise solution, rather than copying the inset-prompt
component from content-publisher (for use in collections-publisher),
for the reason that under current GOV.UK architecture the component
CSS would be added to the stylesheets for our end users (not just
the users using the publishing app). See:
https://github.com/alphagov/govuk_publishing_components/pull/1077
Once merged, we will use this latest inset-text component and
manually recreate what the inset-prompt component looks like by
passing components to the inset-text component as a block.
Trello: …

Allow inset-text to take a block

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/helpers/_brand-colours.scss

Set the colour of branded links on focus to black, to match the `govuk-frontend` styles.
Fixes https://github.com/alphagov/govuk_publishing_components/issues/1086
Focus states on branded links were incorrect, before:
After:
https://govuk-publishing-compo-pr-1088.herokuapp.com/component-guide/image_card

Set all branded links to correct focus colour

---

app/assets/stylesheets/govuk_publishing_components/components/mixins/_clearfix.scss

Remove [ie-lte](https://github.com/alphagov/govuk_frontend_toolkit/blob/03204449dcbf28c2d48e7f6dd217f6abe9b3a518/stylesheets/_conditionals.scss#L67) mixin from clearfix helper.
The mixin coming from govuk_frontend_toolkit which is not imported anymore.

Remove ie-lte mixin from clearfix helper

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/_contents-list.scss
app/views/govuk_publishing_components/components/_contents_list.html.erb
app/views/govuk_publishing_components/components/docs/contents_list.yml
spec/components/contents_list_spec.rb

Reverts https://github.com/alphagov/govuk_publishing_components/pull/1037
Trello - https://trello.com/c/d9KRrVMb/207-remove-the-contents-list-inverse-option
We no longer need to use the contents list component in a topic page header

Removes the inverse flag for contents list component

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* **BREAKING:** Remove the inverse flag for contents list component ([PR #1090](https://github.com/alphagov/govuk_publishing_components/pull/1090))
* Will stop any inverse flags on the contents list component from working
* Set all branded links to correct focus colour ([PR #1088](https://github.com/alphagov/govuk_publishing_components/pull/1088))
* Fix components focus state spacing ([PR #1054](https://github.com/alphagov/govuk_publishing_components/pull/1054))
* Allow inset-text to take a block ([PR #1078](https://github.com/alphagov/govuk_publishing_components/pull/1078))

Version 20.0.0

---

CHANGELOG.md
app/views/govuk_publishing_components/components/docs/machine_readable_metadata.yml
lib/govuk_publishing_components/presenters/machine_readable/faq_page_schema.rb
lib/govuk_publishing_components/presenters/machine_readable/page.rb
lib/govuk_publishing_components/presenters/schema_org.rb
spec/lib/govuk_publishing_components/presenters/schema_org_spec.rb

This will be used on Guides to present the chapters in an improved way in featured snippets.
Implemented as per: https://developers.google.com/search/docs/data-types/faqpage
SEO improvement.  It allows users to read more of the content in Google, hopefully allowing them to make better decisions about whether to read all the content and thus shortening their journeys.
We will measure the effects of this change.

Add FAQPage schema

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/_related-navigation.scss
app/views/govuk_publishing_components/components/related_navigation/_section.html.erb
lib/govuk_publishing_components/presenters/related_navigation_helper.rb

Increases the line height of the inline links and tweaks the toggle link in the ['extensive' related navigation](https://components.publishing.service.gov.uk/component-guide/related_navigation/with_extensive_world_locations) component.
Partially fixes #1028; and probably shouldn't be merged until #1054 has been merged.
The overlap of the focus state made it look broken and having the focus state of the toggle link stretch across the entire parent element looks slightly odd, as no other link had that behaviour.
Toggle link before:
Toggle link after:
Inline links before:
Inline links after:

Fixes focus state spacing on 'extensive' related navigation links

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/_input.scss

- static has some base styles for input[type="text"], input[type="search"] {} that alter the margin and padding of this component in ways we don't want
- this change overrides those specifically for this component only
- hopefully at some point in the future this can be removed
The input component in `frontend` looks like this, and this change fixes that.
https://govuk-publishing-compo-pr-1094.herokuapp.com/component-guide

Ensure input styles are not overridden by static

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Ensure input styles are not overridden by static ([PR #1094](https://github.com/alphagov/govuk_publishing_components/pull/1094))
* Fixes focus state spacing on 'extensive' related navigation links ([PR #1085](https://github.com/alphagov/govuk_publishing_components/pull/1085))
* Add chevron banner component ([PR #1084](https://github.com/alphagov/govuk_publishing_components/pull/1084))

Version 20.2.0

---

CHANGELOG.md
app/assets/images/govuk_publishing_components/chevron-banner/chevron-banner-focus.svg
app/assets/stylesheets/govuk_publishing_components/components/_chevron-banner.scss

Adds the following fixes:
- Reduces the padding in the chevron banner so the chevron is less distorted on smaller screens
- Fixes the hover state so the background image is only replaced mobile and above
**Improve layout on smaller screens (before)**
**Improve layout on smaller screens (after)**
**Hover state below 320px (before)**
**Hover state below 320px (after)**
https://govuk-publishing-compo-pr-1098.herokuapp.com/component-guide/chevron_banner

Chevron banner tweaks

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/_input.scss

Fixing this:
Caused this:
Fixed by adding an override for the override.
Because I didn't think of this earlier.
https://govuk-publishing-compo-pr-1099.herokuapp.com/component-guide/input

Add input style override override

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Improve chevron banner component ([PR #1098](https://github.com/alphagov/govuk_publishing_components/pull/1098))
* Add input style override override ([PR #1099](https://github.com/alphagov/govuk_publishing_components/pull/1099))

Version 20.2.1

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_summary_list.html.erb
spec/components/summary_list_spec.rb

Fix `data_attributes` on delete summary list item
Because we need data attributes to work on this element
No

Fix data attributes on delete summary list

---

lib/govuk_publishing_components/presenters/machine_readable/faq_page_schema.rb
spec/lib/govuk_publishing_components/presenters/schema_org_spec.rb

We show the whole of a guide's FAQ schema on each of its chapters.  I think this is OK, as long as the URLs that refer to the questions and answers are correct.  (We might change this at some point though)
The canonical URL of each part of a guide is set (correctly) to [the URL of the part](https://tools.ietf.org/html/rfc6596).
The FAQ schema was appending the part slugs to the canonical URL of the page that it was displayed on.  This works well for the default page in a guide, but less well for other chapters in the guide because we end up appending the part slug to the wrong base URL.
When you view https://www.gov.uk/christmas-bonus you get links in the structured
data like:
- https://www.gov.uk/christmas-bonus/eligibility
- https://www.gov.uk/christmas-bonus/how-to-claim
When you view …

Resolve incorrect URLs in chapters using FAQ schemas

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_heading.html.erb
app/views/govuk_publishing_components/components/docs/heading.yml
spec/components/heading_spec.rb

Add the ability to pass a language into the heading component, which is added as a `lang` attribute.
In some apps we are passing in a translated string which is falling back to the default (normally English) because the translation does not exist in the chosen language. In these cases, we want to mark these strings as not being in the chosen language.
https://govuk-publishing-compo-pr-1102.herokuapp.com/

Add lang attribute to heading component

---

spec/javascripts/components/cookie-banner-spec.js

Refactor default cookie consent in tests to help test suite work the same in any environment (including locally) and within our CI.
With the new approach we get and store the `DEFAULT_COOKIE_CONSENT` using the `getCookie` function, then we use this value as basis of comparison within tests.
`getCookie` uses `JSON.stringify` which seems to escape the strings differently when stringified in a web browser/local environment compared to CI. In order to avoid this we use the same `getCookie` function to get the default values before each tests which means that we compare the same objects regardless of how they're encoded by each environment. 
Fixes #1083.

Refactor default cookie consent in tests

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/_cookie-banner.scss

Remove the outline when the element is focused to be read out by screen readers and update the focus state on the hide confirmation message button.
To fix #1014
https://govuk-publishing-compo-pr-1109.herokuapp.com/component-guide/cookie_banner

Fix focus states on cookie-banner confirmation message

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_radio.html.erb
app/views/govuk_publishing_components/components/docs/checkboxes.yml
app/views/govuk_publishing_components/components/docs/radio.yml
lib/govuk_publishing_components/presenters/checkboxes_helper.rb
spec/components/checkboxes_spec.rb
spec/components/radio_spec.rb

Add support for custom heading size on checkboxes and radios when not being used as page heading.
Because we currently hardcode the `--m` size for legends and we need to support `--s` size too for when the components are being used on a page with multiple input groups.
When using checkboxes/radios on a page with more than one form group the headings should match the styling of the labels with the rest of the inputs on the page (which can be achieved by setting an `--s` size to the heading).
Added examples with custom heading size for checkboxes and radio component
https://govuk-publishing-compo-pr-1107.herokuapp.com/component-guide/checkboxes/with_custom_heading_size
https://govuk-publishing-compo-pr-1107.herokuapp.com/component-guide/radio/with_custom_heading_size
[Trello …

Allow custom heading size on checkboxes and radios

---

CHANGELOG.md
config/locales/en.yml
spec/components/attachment_spec.rb

The ODT guidance has been published under a new path. This updates link with attachments to the guidance.

Update ODT guidance link

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Update ODT guidance link ([PR #906](https://github.com/alphagov/govuk_publishing_components/pull/906))
* Fix focus states on cookie-banner confirmation message ([PR #1109](https://github.com/alphagov/govuk_publishing_components/pull/1109))
* Allow custom heading size on checkboxes and radios ([PR #1107](https://github.com/alphagov/govuk_publishing_components/pull/1107))

Release v20.4.0
