CHANGELOG.md
config/locales/en.yml
spec/components/layout_super_navigation_header_spec.rb

Add new link to list of popular links. Update tests that count links in the popular section.
Part of incremental changes being made to the homepage.
[Trello Card](https://trello.com/c/TAHoaSQ9/2025-live-test-4-add-6th-link-to-popular-on-14-sep-dev-work-m)

Add 6th link to popular links

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Improve GA URL parameter stripping ([PR #3603](https://github.com/alphagov/govuk_publishing_components/pull/3603))
* Fix bug with GA4 search results count ([PR #3594](https://github.com/alphagov/govuk_publishing_components/pull/3594))
* Check HTML attribute when populating GA4 language ([PR #3598](https://github.com/alphagov/govuk_publishing_components/pull/3598))
* Add GA4 tracking to the intervention banner ([PR #3567](https://github.com/alphagov/govuk_publishing_components/pull/3567))
* Add 6th link to popular links ([PR #3586](https://github.com/alphagov/govuk_publishing_components/pull/3586))

Version 35.15.3

---

CHANGELOG.md
app/assets/javascripts/govuk_publishing_components/analytics-ga4/ga4-page-views.js
spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-page-views.spec.js

- Adds the `query_string` parameter to our GA4 pageview object
https://trello.com/c/Rb45fH1B/633-search-enhancement-new-attribute-query-string
None.

Add query string to GA4 pageview tracking

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/_action-link.scss
app/views/govuk_publishing_components/components/_action_link.html.erb
app/views/govuk_publishing_components/components/docs/action_link.yml
spec/components/action_link_spec.rb

Uses the existing dark icon but makes it slightly larger as per the
design recommendation for the new benefits calculator link being added
to the browse benefit page.
Related PR: https://github.com/alphagov/collections/pull/3373
Current dark icon is too small and doesn't fit the recommended design.
Large dark icon used for the new action link:
Trello:
https://trello.com/c/mwQET0e0/2153-add-link-to-the-benefits-smart-answer-to-the-browse-benefits-page

Add large dark icon for action link

---

spec/components/machine_readable_metadata_spec.rb
spec/features/contextual_navigation_spec.rb
spec/features/step_nav_helper_spec.rb
spec/lib/govuk_publishing_components/presenters/content_breadcrumbs_based_on_ancestors_spec.rb
spec/lib/govuk_publishing_components/presenters/related_navigation_helper_spec.rb

The placeholder schema was removed in [1], causing CI to fail. Swaps over to using `guide`.
[1]: https://github.com/alphagov/publishing-api/pull/2493

Updates placeholder schema references

---

CHANGELOG.md
Gemfile.lock
app/views/govuk_publishing_components/components/_layout_for_public.html.erb
lib/govuk_publishing_components/version.rb
spec/components/layout_for_public_spec.rb

> **Note:** for the sake of expediency, I've bumped the gem version within this PR.
Historically on GOV.UK, `og:image` asset URLs were always absolute URLs. This happened because the Rails app [static](https://github.com/alphagov/static), which renders the `layout_for_public` component for use on the frontend of GOV.UK, was configured with [`config.action_controller.asset_host`](https://guides.rubyonrails.org/configuring.html#config-action-controller-asset-host). This told Rails to use a different hostname for assets, meaning `asset_path` helper method would always produce absolute URLs – for example, `asset_path("example.png")` would output something like `http://assets.example.com/assets/example.png`.
That behaviour changed in alphagov/static@484fea37d3e957df9c7ea7395375933b386c93f6 …

Use an absolute URL for `og:image` Open Graph property

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/_image-card.scss
app/views/govuk_publishing_components/components/_image_card.html.erb
app/views/govuk_publishing_components/components/docs/image_card.yml
lib/govuk_publishing_components/presenters/image_card_helper.rb
spec/components/image_card_spec.rb

Add a new variation of the image card. 'Two thirds' maintains the row layout of the image and text containers at all screen sizes. It uses the govuk grid layout with the image being 1/3 of the width of the row and the text being 2/3 of the width of the row.
This variation is part of changes being made to the homepage.
[Relevant Trello Card](https://trello.com/c/yMdhnPPD/2063-look-and-feel-homepage-action-link-new-variation-for-popular-section-m)

Image card Two Thirds variant

---

CHANGELOG.md
app/assets/javascripts/govuk_publishing_components/analytics-ga4/ga4-page-views.js
app/assets/javascripts/govuk_publishing_components/analytics-ga4/pii-remover.js
spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-page-views.spec.js
spec/javascripts/govuk_publishing_components/analytics-ga4/pii-remover.spec.js

- Adds the `search_term` query string to the pageview.
- Fixes an issue with the email PII redaction but it is not perfect, so it would need your opinion.
- Currently, when this string is put through the PIIRemover: `hello+world+email@example.com+SW12AA+1990-01-01`, the PII remover will just return it as `[email]`. It should be `hello+world+[email]+[postcode]+[date]`.
-  This happens because the PIIRemover treats `+` as part of the email address, so the whole string ends up being included as the email address to be redacted. 
- I fixed this by making `+` a character to be excluded for pattern matching an email. 
- This works, however I know that in gmail technically users can put a `+` in their email address. [See here](https://eit.ces.ncsu.edu/2023/02/gmail-plus-addressing-the-hidden-feat …

Add 'search_term' to GA4 pageview object

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Add option select component ([PR #3623](https://github.com/alphagov/govuk_publishing_components/pull/3623))
* Image card Two Thirds variant ([PR #3597](https://github.com/alphagov/govuk_publishing_components/pull/3597))
* Add 'search_term' to GA4 pageview object ([PR #3615](https://github.com/alphagov/govuk_publishing_components/pull/3615))

Version 35.16.0

---

CHANGELOG.md
app/assets/javascripts/govuk_publishing_components/components/option-select.js
app/views/govuk_publishing_components/components/_option_select.html.erb

Remove some GA4 attributes from the option select component.
- when this component was moved here from `finder-frontend` it included some Google Analytics 4 attributes that are specific to the use of the component in `finder-frontend`
- these attributes have now been [added to finder-frontend](https://github.com/alphagov/finder-frontend/pull/3165) in a wrapping element on the component, so they now need to be removed here
Also renames one of the functions in the option select JS to be more generic, now that the code is in the gem.
None.

Remove option select GA4 attributes

---

CHANGELOG.md
app/assets/javascripts/govuk_publishing_components/analytics-ga4/ga4-page-views.js
spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-page-views.spec.js

Fixes various bugs with the GA4 pageview tracker. These are:
1. In the `query_string` parameter, I was redacting PII before stripping `_ga` and `_gl`. This breaks the _ga/_gl stripping code, as the PIIRemover detects the random characters in these values as `[date]`. And therefore the regex for stripping the values would break, as correctly it doesn't count `[` and `]` as part of the _ga/_gl values.
2. Fixes `html lang='en'` never being grabbed in certain scenarios. Previously, if the `#content` element existed, it would either grab the language value from it, or return `this.nullValue` straight away. This isn't correct, as we want to check the HTML language value as well before returning `this.nullValue`. Ironically, we couldn't figure out how to test the `<html>` element, and if we …

Fix various bugs with the GA4 pageview tracker

---

CHANGELOG.md
app/assets/javascripts/govuk_publishing_components/analytics-ga4/ga4-page-views.js
lib/govuk_publishing_components/presenters/meta_tags.rb
spec/components/meta_tags_spec.rb
spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-page-views.spec.js

The PAs were previously using the `govuk:section` meta tag to populate `browse_topic` in our pageview tracking. If you look at `meta_tags.rb` in this repo, it looks like this value is populated by grabbing a `section` value from the `content_item`. However, in reality `govuk:section` was being added to the page by digging through the `content_item` in `frontend` and pulling a deeply nested value, rather than just using the `section` value in the `content_item`, which doesn't seem to exist where we'd want it. (For the code that's in `frontend`, [click here](https://github.com/alphagov/frontend/blob/542e53d60f12b21d3299424025cdb7905ede4303/app/controllers/content_items_controller.rb#L8)) This was why the meta tag looked like it was fine for our purpose on certain pages, as these were pages …

Add 'ga4-browse-topic' meta tag to track the mainstream browse topic

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_previous_and_next_navigation.html.erb
spec/components/previous_and_next_navigation_spec.rb

Changes GA4 tracking 'type' for the previous/next navigation component from 'content' to 'previous and next'.
We want more specific types when tracking different kinds of interactions.
None.
Trello card: https://trello.com/c/6jQ96zS8/683-change-previous-and-next-page-navigation-event-types-to-previous-and-next

Change prev and next GA4 type

---

CHANGELOG.md
app/assets/javascripts/govuk_publishing_components/analytics-ga4/ga4-video-tracker.js
spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-video-tracker.spec.js

- tracking videos includes the URL of the video, retrieved from the YouTube API
- the URL changes during playback to include the time position of the video, as a URL parameter of the form `t=[0-9]`
- use regexes to remove these parameters and preserve the original URL
It's quite hard to track videos being watched in GA4 when the URL is inconsistent - removing the timestamp should make the video URL always the same for a single video.
None.
Trello card: https://trello.com/c/4r5QApUs/695-placeholder-video-url-remove-extra-query-strings

Remove timestamps from GA4 video urls

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/_big-number.scss
app/assets/stylesheets/govuk_publishing_components/components/_step-by-step-nav.scss
app/assets/stylesheets/govuk_publishing_components/components/_tabs.scss
package.json
yarn.lock

Adds [stylelint-stylistic plugin](https://github.com/elirasza/stylelint-stylistic). This includes adding the plugin to package.json, along with a few configuration rules to match our coding style.
Some changes to the code are inevitable, but limited, and are included in a separate commit.
Stylelint was [recently upgraded](https://github.com/alphagov/govuk_publishing_components/pull/3522) to v1, which [removes all stylistic rules](https://github.com/alphagov/stylelint-config-gds/blob/main/CHANGELOG.md#100) meaning that we're no longer linting for loads of things such as rogue tabs vs spaces, empty space inside parentheses, single quotes, braces on new lines, etc.
Recommended solution is to adopt Prettier (attempted in https://github.com/alphagov/govuk_publishing_components/pull/3627). …

Add stylistic plugin for stylelint

---

CHANGELOG.md
app/assets/javascripts/govuk_publishing_components/analytics-ga4/ga4-page-views.js
spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-page-views.spec.js

The cookie banner is hidden via JS. Our pageview code runs before the cookie banner is hidden. Therefore we need to start the cookie banner module before our pageview code runs, so that it is hidden when our pageview tracker goes to detect its presence.
This is the same issue we had with our intervention banner, which was fixed in https://github.com/alphagov/govuk_publishing_components/pull/3567
Will allow the PAs to properly test https://trello.com/c/bfDEtTyR/665-banners-cookie-banner-navigation-and-hide-this-message-user-interaction
None.

Ensure cookie banner isn't tracked as visible when it is hidden via JS

---

CHANGELOG.md
app/assets/javascripts/govuk_publishing_components/analytics-ga4/ga4-page-views.js
spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-page-views.spec.js

- Adds `spelling_suggestion` to the GA4 Pageview object - it pulls this value from an existing meta tag `govuk:spelling-suggestion`.
- https://trello.com/c/RMPwoe93/689-search-enhancement-new-attribute-search-spelling-suggestion
None.

Add spelling_suggestion meta tag to the GA4 pageview object

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_contents_list.html.erb
spec/components/contents_list_spec.rb

Change GA4 attributes for the contents list component from type `content` to type `contents list`.
We want more specific types when tracking different kinds of interactions.
None.
Trello card: https://trello.com/c/kPQBqdSw/675-change-contents-navigation-selectcontent-event-types-to-contents-list

Change GA4 contents list type

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_contents_list.html.erb
app/views/govuk_publishing_components/components/docs/contents_list.yml
lib/govuk_publishing_components/presenters/contents_list_helper.rb
spec/components/contents_list_spec.rb
spec/lib/govuk_publishing_components/components/contents_list_helper_spec.rb

- include GA4 attributes for tracking on nested contents item links
- includes new code to calculate the index_total (total number of links) and the index_link value for each link
- note that where a contents list item is 'active' (i.e. not a link) this should not alter the overall index_total or index_link values, it is assumed that this non-link item is included in those counts
Index values should be as follows:
```
Parent link // index_link 1
- nested link // index_link 2
- nested link // index_link 3
Parent link // index_link 4
- nested link // index_link 5
- active (not a link)
- nested link // index_link 7
index_total = 7
```
We weren't tracking clicks on nested contents items links, only on top level items.
One tiny change to the doc page for this component, under GA4 tracking …

Add GA4 to nested contents item links

---

app/views/govuk_publishing_components/components/_option_select.html.erb

- if CSS is disabled or fails to load, this component's SVG arrows (for expand/collapse) appear at a huge size
- this not only looks terrible but advertises that something is broken and gets in the way of the user using the component
- since the CSS sets the width and height of the SVG already, solution is to set width and height inline attributes on the SVG to zero, so if CSS fails to load the SVG doesn't appear
The component should be mostly usable without styles or JS enabled. Recently there was a problem with this component's styles and the massive SVG arrow was briefly visible on the live site. This has also happened a few times before.
Before | After
------ | -------

Fix option select arrow when CSS missing

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Add GA4 to nested contents item links ([PR #3638](https://github.com/alphagov/govuk_publishing_components/pull/3638))
* Change GA4 contents list type ([PR #3635](https://github.com/alphagov/govuk_publishing_components/pull/3635))
* Change prev and next GA4 type ([PR #3631](https://github.com/alphagov/govuk_publishing_components/pull/3631))
* Remove timestamps from GA4 video urls ([PR #3632](https://github.com/alphagov/govuk_publishing_components/pull/3632))
* Add stylistic plugin for stylelint ([PR #3629](https://github.com/alphagov/govuk_publishing_components/pull/3629))
* Remove option select GA4 attributes ([PR #3625](https://github.com/alphagov/govuk_publishing_components/pull/3625))
* Fix various bugs with the GA4 pageview tracker ([PR …

Version 35.16.1

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_metadata.html.erb
spec/components/metadata_spec.rb

Changes the GA4 type for `See all updates` navigation events from `content` to `content history`. I believe the type of page that uses this event is https://www.gov.uk/hmrc-internal-manuals/self-assessment-claims-manual/sacm1005
https://trello.com/c/KdNfD2FM/682-change-see-updates-show-hide-all-updates-selectcontent-event-types-to-content-history
None.

Change GA4 type for show/hide update links

---

CHANGELOG.md
app/assets/javascripts/govuk_publishing_components/analytics-ga4/ga4-core.js
spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-core.spec.js

- On licence finders, the results count heading looks like `Results: 431 licences` https://www.gov.uk/find-licences
- The current method for grabbing results counts in our ecommerce tracking expects the heading to look like `1,234 results`
- Therefore the dataLayer was pushing `NaN` for licence finder results count
- This PR fixes this
- Note: we have a technical debt card to replace this with the meta tag `<meta name="govuk:search-result-count" content="431">` https://trello.com/c/uPzYr44q/640-use-search-results-count-meta-tag-to-grab-the-amount-of-search-results-for-finder-frontend-ecommerce-tracking
https://trello.com/c/MXhpmk9c/659-fix-search-results-count-on-viewitemlist-event
- To test this, point `finder-frontend` to your local `govuk_publishing_components` and checkout this branch …

Account for licence finder results count in GA4 ecommerce tracking

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Add new light action link variant ([PR #3602](https://github.com/alphagov/govuk_publishing_components/pull/3602))
* Add new homepage variant to search component ([PR #3599](https://github.com/alphagov/govuk_publishing_components/pull/3599))
* Change GA4 type for show/hide update links ([PR #3643](https://github.com/alphagov/govuk_publishing_components/pull/3643))
* Account for licence finder results count in GA4 ecommerce tracking ([PR #3641](https://github.com/alphagov/govuk_publishing_components/pull/3641))

Version 35.17.0

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_contents_list.html.erb
app/views/govuk_publishing_components/components/docs/contents_list.yml
lib/govuk_publishing_components/presenters/contents_list_helper.rb
spec/components/contents_list_spec.rb
spec/lib/govuk_publishing_components/components/contents_list_helper_spec.rb

- type should be 'contents list' for regular links (as it was previously)
- type should be 'select content' for anchor links (newly added)
None.
Trello card: https://trello.com/c/51i0EiqQ/673-contents-link-clicks-that-go-to-anchors-in-the-page-rather-than-other-pages-to-be-selectcontent-instead-of-navigation-events

Change GA4 type on contents lists

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/_layout-super-navigation-header.scss
app/views/govuk_publishing_components/components/_layout_for_public.html.erb
app/views/govuk_publishing_components/components/_layout_super_navigation_header.html.erb
app/views/govuk_publishing_components/components/docs/layout_for_public.yml
app/views/govuk_publishing_components/components/docs/layout_super_navigation_header.yml
app/views/govuk_publishing_components/components/layout_for_public/_layout_super_navigation_header_homepage.html.erb
spec/components/layout_for_public_spec.rb
spec/components/layout_super_navigation_header_spec.rb

This commit contains several small changes that are part of the new design of the homepage. They are all optional parameters for layout_super_navigation_header and are the following:
* toggle the logo text off
* toggle the border left of the toggle button off
* change the background colour of the navbar to blue
* make the links/buttons larger for desktop only
Created a new partial `layout_super_navigation_header_home` which has all these changes toggled on. Also toggles some additional classes on elements when the navbar is blue to make sure the contrast between hover state styles is OK.
As part of several small changes that are going to be made to the homepage, we need to override some default styling of the layout super navigation header. As these variations will only be rendered on the …

Add homepage variant of navbar for new design of homepage

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Change GA4 type on contents lists ([PR #3647](https://github.com/alphagov/govuk_publishing_components/pull/3647))
* Bump Ruby version and use floating patch version ([PR #3646](https://github.com/alphagov/govuk_publishing_components/pull/3646))
* Add homepage variant of navbar for new design of homepage ([PR #3566](https://github.com/alphagov/govuk_publishing_components/pull/3566))

Version 35.18.0

---

CHANGELOG.md
app/assets/javascripts/govuk_publishing_components/analytics-ga4/ga4-page-views.js
spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-page-views.spec.js

- Search terms with spaces come through as 'hello+world' in URLs, and subsequently our `search_term` pageview parameter
- The PAs would rather have the actual spaces e.g. 'hello world'
- This PR fixes that using regex
https://trello.com/c/OCr10DWn/700-searchterm-parameter-includes-between-words
None.

Replace '+' in GA4 search term values with an actual space

---

app/views/govuk_publishing_components/components/docs/image_card.yml
lib/govuk_publishing_components/presenters/image_card_helper.rb
spec/components/image_card_spec.rb

- Set the correct width and height attributes when using the new two_thirds variation of the image-card component. The aspect ratio for the featured image size to be used on the new homepage design is 1:1 when using the new two_thirds variation of the image card component
- Add related tests to ensure that the correct width and height attributes are set
- Update documentation for the two_thirds image card variation
Required for the new homepage design
[Trello card](https://trello.com/c/OM7sZgaY/2169-look-and-feel-homepage-update-image-card-component-for-featured-section-m)

Update image card two thirds variation

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/_layout-super-navigation-header.scss

Ensure the total space to the left of the logo for mobile screen sizes is 24px (margin is 15px) for the new homepage design
For the new homepage design, the total space on the left and right of the content should be 24px for mobile.
[Trello card](https://trello.com/c/9j5GiXNP/2172-look-and-feel-homepage-update-left-and-right-spacing-on-mobile-s)

Update logo spacing for new homepage design

---

CHANGELOG.md
app/assets/javascripts/govuk_publishing_components/analytics-ga4/ga4-core.js
spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-core.spec.js

- Limits the amount of items in the GA4 ecommerce items array to a maximum of 200 items
- There are a couple search finders that contain more than 200 search results on one page, for example https://www.gov.uk/world/organisations and https://www.gov.uk/government/groups
- The dataLayer push for these was fine, but the PAs were having issues with the data when it was in their dashboard
- We think this is due to GA4 limiting how big an array sent to it can be
- Therefore we are limiting the array to the GA4 limit in their documentation
https://trello.com/c/wLz7uULw/679-fix-world-organisations-finder-ecommerce-tracking
https://trello.com/c/jHYCtOA8/678-fix-groups-finder-ecommerce-tracking
None.

Limit GA4 ecommerce arrays to 200 items

---

CHANGELOG.md
app/assets/javascripts/govuk_publishing_components/analytics-ga4/ga4-form-tracker.js
docs/analytics-ga4/ga4-form-tracker.md
spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-form-tracker.spec.js

- Adds detection of a data attribute on forms called `data-ga4-form-undefined-if-text-is-empty` 
- When this is present on a form, and the submitted text by the user on the form is empty, it will push `undefined` to GA4 instead of `No answer given`
- Let me know if `data-ga4-form-undefined-if-text-is-empty` is too long of a name
https://trello.com/c/WtvEWiS3/592-placeholder-replace-no-answer-given-with-undefined-on-homepage-search-event
None.

Allow GA4 Form text values to be undefined instead of 'No answer given'

---

CHANGELOG.md
app/assets/javascripts/govuk_publishing_components/analytics-ga4/ga4-page-views.js
spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-page-views.spec.js

Adds browser viewport width and height to the GA4 page view.
Uses a fairly clean approach that appears to be reasonably backwards compatible for browsers.
In the tests I'm using the function I'm testing to get the viewport size, which seems a bit redundant but otherwise I think we'd need to be setting the viewport size in the test, which could get complicated and messy. Although now I write this that sounds useful. Perhaps something to consider while reviewing. EDIT: done some digging, this indeed looks difficult and messy. Maybe best avoided.
None.
Trello card: https://trello.com/c/9J21E5KI/698-viewport-size-custom-dimension

Add viewport size to GA4 page view

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_contents_list.html.erb
lib/govuk_publishing_components/presenters/contents_list_helper.rb
spec/components/contents_list_spec.rb
spec/lib/govuk_publishing_components/components/contents_list_helper_spec.rb

Set the GA4 attributes for contents list events to be the correct values. Hopefully. This time.
I got them wrong. I don't know how.
None.
Trello card: https://trello.com/c/pWP26ZKI/691-add-contents-list-selectcontent-events-to-taxon-pages

Fix GA4 contents list events

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/_attachment.scss
app/assets/stylesheets/govuk_publishing_components/components/govspeak/_attachment.scss
app/views/govuk_publishing_components/components/_govspeak.html.erb

Fix some styling issues with the details component where it appears inside the attachment component.
- where the details component is included in the attachment component inside govspeak it was not being styled, because the details stylesheet was not being included
- also increases font size of this component in this context, and fixes a spacing issue
Improve accessibility and visual appearance.
The problem can be seen on [pages like this](https://www.gov.uk/government/groups/secretary-of-state-for-transports-honorary-medical-advisory-panel-on-driving-and-psychiatric-disorders) rendered using govspeak inside `government-frontend`. The details component lacks focus and other styles. In addition, the details component had been shrunk so that it was smaller than its contents.
Spacing has …

Improve attachment details styles

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Improve attachment details styles ([PR #3668](https://github.com/alphagov/govuk_publishing_components/pull/3668))
* Fix GA4 contents list events ([PR #3667](https://github.com/alphagov/govuk_publishing_components/pull/3667))
* Add viewport size to GA4 page view ([PR #3665](https://github.com/alphagov/govuk_publishing_components/pull/3665))
* Replace '+' in GA4 search term values with an actual space ([PR #3653](https://github.com/alphagov/govuk_publishing_components/pull/3653))
* Update image card two thirds variation ([PR #3661](https://github.com/alphagov/govuk_publishing_components/pull/3661))
* Update logo spacing for new homepage design ([PR #3658](https://github.com/alphagov/govuk_publishing_components/pull/3658))
* Limit GA4 ecommerce arrays to 200 items ([PR …

Version 35.19.0

---

CHANGELOG.md
app/assets/javascripts/govuk_publishing_components/analytics-ga4.js
app/assets/javascripts/govuk_publishing_components/analytics-ga4/ga4-print-intent-tracker.js
docs/analytics-ga4/ga4-all-trackers.md
docs/analytics-ga4/ga4-print-intent-tracker.md
spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-print-intent-tracker.spec.js

- Adds a new tracker called `ga4-print-intent-tracker`
- This runs on pageload, adding a `beforeprint` listener to the `window`
- The event listener fires if the user triggers a "Print page" via their browser (e.g. with `Ctrl/Cmd + P`, or by going to `File > Print`)
- This is tracked in UA https://github.com/alphagov/govuk_publishing_components/blob/main/app/assets/javascripts/govuk_publishing_components/analytics/print-intent.js . I'm not sure why the code is a lot more complicated, I guess the UA requirements were different. I didn't reuse this code as well because `mediaQueryList.addListener` is deprecated JS.
- https://trello.com/c/EpTcwew0/684-print-page-event-to-be-sent-with-ctrl-cmdp
- Run `static` with a local version of `govuk_publishing_components` pointing to this branch
- …

Add GA4 'print intent' tracker

---

spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-form-tracker.spec.js

Adds an extra test for the GA4 form tracker. 
I was using this in an application and realised it already did what I needed it to do, but there wasn't a specific test to cover the functionality.
None.
Trello card: https://trello.com/c/AvcrXf8U/703-emails-should-be-email-not-redacted-on-email-subscription-journey

Add an extra test for the form tracker

---

CHANGELOG.md
app/assets/javascripts/govuk_publishing_components/analytics-ga4/ga4-core.js
docs/analytics-ga4/ga4-ecommerce-tracker.md
spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-core.spec.js
spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-ecommerce-tracker.spec.js
spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-smart-answer-results-tracker.spec.js

- Allows the GA4 ecommerce tracker to grab a data attribute called `data-ga4-ecommerce-content-id` and push it to the dataLayer.  We want to track the content id of results, as the URLs get cut off by GA4s 100 character limit.
- We are using this for finders only, so any of the tests referring to smart answers have the value set to `undefined`
- High priority bug fix https://trello.com/c/7Snj5Lx1/710-search-enhancement-add-content-id-to-searchresults-ecommerce-items-because-link-paths-are-truncated-to-100-characters
- Related to https://github.com/alphagov/finder-frontend/pull/3192 but either PR can be merged in any order, as nothing should crash if one is merged and the other isn't
None.

Grab data-ga4-ecommerce-content-id in GA4 ecommerce tracking

---

CHANGELOG.md
app/assets/images/govuk_publishing_components/icon-close.svg
app/assets/stylesheets/govuk_publishing_components/components/_search.scss

- Replaces the default search 'cancel' button with our own custom SVG provided by one of our designers. The default browser icon does not scale well when zoomed in, so we are using our own SVG for this icon which scales when zoomed in.
- I have run the SVG through a minifier to reduce it's filesize.
- I have made it bigger than the default icon, as a bigger hitbox is better for accessibility, especially on mobile. But let me know if it's too big.
- This doesn't apply to Firefox as Firefox doesn't support search cancel buttons. I have been asked by our GOVUK Lead FE Dev to raise an issue in this repo that we're using this non standard CSS, just so we're kept aware of it once it's merged.
- Visual changes have been approved by the designer 
- The default cancel button used by browsers does …

Use custom SVG for search 'cancel' icon

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/_image-card.scss
app/views/govuk_publishing_components/components/docs/image_card.yml

Update the styling of the image-card component (two thirds variation), the changes include:
- Remove the `display: block` rule, using the default value set of `display: flex` instead
- Use flex to align the card image and card text in the same row
- Wrap the image card text onto a new line if the width would go below 70%
- Ensure the card image and card text align as intended
As part of the changes for the new homepage design and to help ensure that the image card text does not appear too squashed at smaller Desktop screen sizes.
[Trello card](https://trello.com/c/LbnpQxg3/2136-iterate-featured-section-images-m)
For larger desktop screen sizes, there is no change to the layout of the featured section, it will remain as shown in the screenshot below:
When testing in browser stack, IE11 …

Update the styling of image-card two thirds variation

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Flatten GA4 data attributes ([PR #3649](https://github.com/alphagov/govuk_publishing_components/pull/3649))
* Use custom SVG for search 'cancel' icon ([PR #3673](https://github.com/alphagov/govuk_publishing_components/pull/3673))
* Add GA4 'print intent' tracker ([PR #3652](https://github.com/alphagov/govuk_publishing_components/pull/3652))
* Update LUX to version 312 ([PR #3672](https://github.com/alphagov/govuk_publishing_components/pull/3672))
* Grab data-ga4-ecommerce-content-id in GA4 ecommerce tracking ([PR #3676](https://github.com/alphagov/govuk_publishing_components/pull/3676))
* Update the styling of image-card two thirds variation ([PR #3671](https://github.com/alphagov/govuk_publishing_components/pull/3671))

Version 35.20.0

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/_layout-super-navigation-header.scss

- Decrease the large navbar height from 86px to 72px
- Decrease the crown logo size
- Adjust related height and padding values to ensure the header logo is contained and aligned correctly
As part of the new homepage design changes.
[Trello card](https://trello.com/c/9IrSqRv5/2187-tweaks-to-apply-to-the-menu-bar-on-desktop-m-l)

Adjust the size of large navbar super navigation header

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_layout_super_navigation_header.html.erb
spec/components/layout_super_navigation_header_spec.rb

Add visually hidden span to the navbar crown logo link if we are hiding the logo text. Add test to make sure the visually hidden text is being added.
If users change the styles of the navbar, then there is still fallback text for this link.
[Relevant Trello Card](https://trello.com/c/V1oeVTKL/2206-look-and-feel-accessibility-fix-alternative-text-for-govuk-logo-is-okay-with-aria-label-but-would-be-better-with-visually-hidden)

Add visually hidden text to navbar

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_layout_super_navigation_header.html.erb

Adds `data-ga4-form-no-answer-undefined` to the header search form. When this attribute exists, it will send `text: undefined` when the form is empty, instead of `text: "No answer given"`.
https://trello.com/c/WtvEWiS3/592-placeholder-replace-no-answer-given-with-undefined-on-homepage-search-event

Add data-ga4-form-no-answer-undefined to header search form

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/_layout-super-navigation-header.scss

When interacting with the search toggle button in the main nav menu, the search icon would move up and down depending on the state.
This approach ensures that the bottom border is always 3px and blends into the background of the blue navbar.
https://github.com/alphagov/govuk_publishing_components/assets/28779939/76ac249c-bd1a-4802-a3f8-c37299ddddc2
https://github.com/alphagov/govuk_publishing_components/assets/28779939/529b0895-1c47-4818-9fe8-5506c97858e2
https://github.com/alphagov/govuk_publishing_components/assets/28779939/6f1f17fe-6288-4c3e-91a4-58381050dedd
https://github.com/alphagov/govuk_publishing_components/assets/28779939/74e84631-accc-48d2-955f-ffee8769e9bc

Stop search icon from moving up and down

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Adjustments to the navbar for the homepage ([PR #3666](https://github.com/alphagov/govuk_publishing_components/pull/3666))
* Adjust the size of large navbar super navigation header ([PR #3677](https://github.com/alphagov/govuk_publishing_components/pull/3677))
* Add visually hidden text to the navbar ([PR #3684](https://github.com/alphagov/govuk_publishing_components/pull/3684))
* Add data-ga4-form-no-answer-undefined to header search form ([PR #3682](https://github.com/alphagov/govuk_publishing_components/pull/3682))
* Stop search icon from moving up and down ([PR #3685](https://github.com/alphagov/govuk_publishing_components/pull/3685))

Version 35.20.1

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/_metadata.scss
app/views/govuk_publishing_components/components/_metadata.html.erb
app/views/govuk_publishing_components/components/docs/metadata.yml
spec/components/metadata_spec.rb

Adds a new option to the metadata component.
- when the inverse option is applied to the metadata component (to turn the text white to make it suitable for a dark background) this also includes extra spacing around the component
- have found two instances recently where this is not required and makes the page layout look odd
- adding the inverse_compress option, which allows the removal of this extra spacing when the inverse option is used
Needed for a change in `finder-frontend` (when there's an inverse header on search, see https://github.com/alphagov/finder-frontend/pull/3193) and `government-frontend` (about to raise a PR for [this page](https://www.gov.uk/guidance/the-highway-code) where application styles are overriding the appearance of the component).

Add metadata inverse no padding option

---

app/assets/stylesheets/govuk_publishing_components/components/_layout-super-navigation-header.scss

Revert margin on second item description in the navbar to 5px.
Was accidentally increased in changes to the large navbar.

Fix issue with padding on navbar description

---

CHANGELOG.md
app/assets/javascripts/govuk_publishing_components/analytics-ga4/ga4-core.js
spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-core.spec.js

This prevents the GA4 dashboards being polluted with Smokey test data
- Our GA4 dashboards are being polluted with test data coming from Smokey
- It seems that smokey sets it's user agent to `Smokey Test / Ruby`. As we can grab user agents in JS, we can use this to prevent data being sent if `Smokey Test / Ruby` is the user agent. See https://github.com/alphagov/smokey/blob/32678764d2dfdf18615b2e24d30c615b6cfec644/features/support/env.rb#L33 and https://github.com/alphagov/smokey/blob/32678764d2dfdf18615b2e24d30c615b6cfec644/features/support/http_requests.rb#L77
- I am preventing Smokey data from being sent to GA4 in the `sendData` function. I considered just disabling analytics entirely if it was a Smokey test, but I thought this was a bad idea. Mainly because then we couldn't write new …

Prevent GA4 data sending during Smokey tests

---

app/assets/javascripts/govuk_publishing_components/analytics-ga4/ga4-form-tracker.js

When data-ga4-form-no-answer-undefined exists, it sets the text to undefined. However straight after that, it was trying to call .toLowerCase(), so the GA4 JS crashes on submit of these search forms.
Not sure how I missed this, apologies. I must have just used the jasmine test (which passed) to prove this as working.

Fix bug when forms with data-ga4-form-no-answer-undefined are submitted

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Add metadata inverse no padding option ([PR #3689](https://github.com/alphagov/govuk_publishing_components/pull/3689))
* Prevent GA4 data sending during Smokey tests ([PR #3680](https://github.com/alphagov/govuk_publishing_components/pull/3680))
Also contains a patch fix for a small GA4 bug

Version 35.21.0

---

CHANGELOG.md
lib/govuk_publishing_components/presenters/contents_list_helper.rb
spec/lib/govuk_publishing_components/components/contents_list_helper_spec.rb

- In `whitehall`, a user can choose to manually number headings in their markdown, e.g. `## 1. Heading`.
- Our contents lists have some code which is meant to take these manually numbered headings, and generate a formatted contents list from them.
- However, when they format a heading like `## 1. Heading`, the space between `##` and `1.` was kept in the heading string. This caused some regex not to fire, which is used to format contents lists with heading numbers. This is because the regex expects the heading to start with a number, and not a space character.
- This caused a visual bug where contents lists were not formatted properly, since the regex was treating them as not being numbered, due to the space character causing the regex not to match against anything.
- I've fixed that in …

Fix visual bug with contents list manually numbered headings

---

app/assets/javascripts/govuk_publishing_components/analytics-ga4/ga4-core.js
docs/analytics-ga4/ga4-smart-answer-results-tracker.md
spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-core.spec.js
spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-ecommerce-tracker.spec.js
spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-smart-answer-results-tracker.spec.js

- Replaces UA ecommerce tracking attributes with GA4 specific ones in our GA4 ecommerce / smart answer trackers
- Do not merge until these are deployed: https://github.com/alphagov/finder-frontend/pull/3195 and https://github.com/alphagov/smart-answers/pull/6591
- I have tested this branch with a local version of `finder-frontend` running https://github.com/alphagov/finder-frontend/pull/3195, and used a diff checker to compare the `dataLayer` from this branch with the dataLayer currently on integration. I couldn't spot any issues with these changes. I have also done this with `smart-answers`.
- This is to decouple our GA4 analytics code from universal analytics
- https://trello.com/c/gFiJmH3D/553-audit-and-ensure-that-every-data-attribute-relies-on-has-ga4-somewhere-in-its-name
None.

Replace UA ecommerce tracking attributes with GA4 specific ones

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Replace UA ecommerce tracking attributes with GA4 specific ones ([PR #3688](https://github.com/alphagov/govuk_publishing_components/pull/3688))
* Fix visual bug with contents list manually numbered headings ([PR #3694](https://github.com/alphagov/govuk_publishing_components/pull/3694))

Version 35.21.1

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Revert nav menu font changes ([PR #3696](https://github.com/alphagov/govuk_publishing_components/pull/3696))

Version 35.21.2

---

app/assets/javascripts/govuk_publishing_components/analytics-ga4/ga4-core.js
spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-core.spec.js

We have a debug mode for GA4, activated by typing `window.GOVUK.analyticsGa4.showDebug = true` in the browser console. This outputs any data pushed to the dataLayer for GA4 while on the current page.
Currently the data is shown exactly as it is created. This change sorts the attributes in the `event_data` object alphabetically.
To make the data more readable for those using it and to make this output consistent with the implementation record, which helps when checking changes.
Before | After

GA4 debug mode sort attributes

---

CHANGELOG.md
app/assets/javascripts/govuk_publishing_components/analytics-ga4/ga4-auto-tracker.js
spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-auto-tracker.spec.js

Add PII redaction to the GA4 auto tracker.
We need PII redaction on this value.
None.
Trello card: https://trello.com/c/2kvItAoh/729-fix-postcode-lookup-pii-collection-on-contact-electoral-registration-office

GA4 auto tracker add PII redaction

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* GA4 auto tracker add PII redaction ([PR #3707](https://github.com/alphagov/govuk_publishing_components/pull/3707))

Version 35.21.3

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/_metadata.scss
app/views/govuk_publishing_components/components/docs/metadata.yml

- the metadata component has an inverse option, which includes a background colour of dark blue
- it isn't always used on a dark blue background, for example here it is used against a green background and therefore looks wrong: [Air Passenger Duty](https://www.gov.uk/hmrc-internal-manuals/air-passenger-duty/updates)
- removing the background to prevent this problem
I made a [change recently](https://github.com/alphagov/government-frontend/pull/2975/commits/a846908d0cb471f284dbf9f3b186b898bb583e06) to make `government-frontend` comply with our [component principles](https://github.com/alphagov/govuk_publishing_components/blob/main/docs/component_principles.md#a-component-is-isolated-when) better. This involved removing some style overrides on the metadata component. The focus of that work …

Metadata component inverse option remove background

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Metadata component inverse option remove background ([PR #3711](https://github.com/alphagov/govuk_publishing_components/pull/3711))

Version 35.21.4

---

CHANGELOG.md
app/assets/javascripts/govuk_publishing_components/analytics-ga4/ga4-video-tracker.js
spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-video-tracker.spec.js

- for some reason we're getting differing numbers back from the YouTube API when requesting video durations
- solution is to just ask for it once, then store it along with the percentage positions calculated when videos are loading
- in terms of efficiency, it's also therefore sensible to get and store the video title and URL at the start as well, instead of requesting them each time an event fires during playback
None.
Trello card: https://trello.com/c/Zj359UYH/727-fix-video-duration-rounding-issue

Change GA4 video tracking duration handling

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Enable GA4 by default on components ([PR #3705](https://github.com/alphagov/govuk_publishing_components/pull/3705))
* Change GA4 video tracking duration handling ([PR #3717](https://github.com/alphagov/govuk_publishing_components/pull/3717))

Version 35.22.0

---

CHANGELOG.md
app/assets/config/govuk_publishing_components_manifest.js
app/assets/javascripts/govuk_publishing_components/components/cross-service-header.js
app/assets/stylesheets/govuk_publishing_components/_all_components.scss
app/assets/stylesheets/govuk_publishing_components/components/_cross-service-header.scss
app/views/govuk_publishing_components/components/_cross_service_header.html.erb
app/views/govuk_publishing_components/components/_layout_for_public.html.erb
app/views/govuk_publishing_components/components/cross_service_header/_one_login_header.html.erb
app/views/govuk_publishing_components/components/cross_service_header/_service_header.html.erb
app/views/govuk_publishing_components/components/docs/cross_service_header.yml
lib/govuk_publishing_components/app_helpers/asset_helper.rb
spec/component_guide/component_index_spec.rb
spec/components/cross_service_header_spec.rb
spec/javascripts/components/cross-service-header.js
spec/lib/govuk_publishing_components/app_helpers/asset_helper_spec.rb

https://trello.com/c/9o9pvE3a/2146-implement-one-login-cross-service-header-on-the-email-subscriptions-service
> - To help us here in One Login improve the component
> - To provide email subscriptions service users with the navigation improvements we’re already confident about following our testing
See: https://components-gem-pr-3659.herokuapp.com/component-guide/cross_service_header
- I've added the naming convention of '**cross service header**' for both component and file names, aligning them with the JavaScript module name. Additionally, CSS classes use `gem-c-cross-service-header`, `gem-c-one-login-header`, and `gem-c-service-header`, maintaining concise and clear naming.
- See spike notes [here](https://docs.google.com/document/d/1PZMk0DA86QQLdJLKAAEH6Fwa75sxvEcs3RcXdMTbbQE/edit?pli= …

Implement One Login "cross service header"

---

CHANGELOG.md
app/assets/javascripts/govuk_publishing_components/analytics-ga4/ga4-core.js
docs/analytics-ga4/ga4-specialist-link-tracker.md
spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-link-tracker.spec.js
spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-specialist-link-tracker.spec.js

- When the `alt` or `option` key were held down while a link was clicked, it was being tracked as a `primary click`.
- This PR changes that, so that the click is tracked as an `alt/option` click.
https://trello.com/c/36r3mAUe/734-option-clicks-currently-coming-through-with-method-primary-click-switch-to-option-click
None.

Add alt/option click tracking to GA4 link tracker

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Implement One Login "cross service header" ([PR #3659](https://github.com/alphagov/govuk_publishing_components/pull/3659))
* Add alt/option click tracking to GA4 link tracker ([PR #3720](https://github.com/alphagov/govuk_publishing_components/pull/3720))

Version 35.23.0

---

CHANGELOG.md
app/assets/javascripts/govuk_publishing_components/analytics-ga4/ga4-core.js
spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-core.spec.js

Make data-ga4-set-indexes ignore links with no href
- Prevents future issues if invalid links are introduced into the HTML
- https://trello.com/c/UlhiLIok/732-update-index-code-to-count-links-if-they-also-have-href-or-text-values
None.

Make data-ga4-set-indexes ignore links with no href

---

app/assets/javascripts/govuk_publishing_components/analytics-ga4/ga4-core.js

- we have a debugging aid built into our GA4 JS, activated by pasting `window.GOVUK.analyticsGa4.showDebug = true` into the console, which shows any events fired on the current page
- it works fine except on search results e.g. /search/news-and-communications
- because it previously assumed that the data object contained `event_data`, but for search results it might be `page_view` or `search_results` instead
None.

Fix GA4 debug

---

CHANGELOG.md
app/assets/javascripts/govuk_publishing_components/analytics-ga4/ga4-auto-tracker.js
app/assets/javascripts/govuk_publishing_components/analytics-ga4/ga4-core.js
app/assets/javascripts/govuk_publishing_components/analytics-ga4/ga4-event-tracker.js
app/assets/javascripts/govuk_publishing_components/analytics-ga4/ga4-form-tracker.js
app/assets/javascripts/govuk_publishing_components/analytics-ga4/ga4-link-tracker.js
app/assets/javascripts/govuk_publishing_components/analytics-ga4/ga4-print-intent-tracker.js
app/assets/javascripts/govuk_publishing_components/analytics-ga4/ga4-scroll-tracker.js
app/assets/javascripts/govuk_publishing_components/analytics-ga4/ga4-specialist-link-tracker.js
app/assets/javascripts/govuk_publishing_components/analytics-ga4/ga4-video-tracker.js
spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-core.spec.js

- creates new function in core code 'applySchemaAndSendData', which de-duplicates calls to the schema generation code in trackers
- leaves existing sendData function in place as not always used in this way
Optimising code.
None.
Trello card: https://trello.com/c/sI76EaNX/655-investigate-shortening-calls-to-schema-code

Consolidate GA4 schema calls

---

docs/analytics-ga4/analytics.md
docs/analytics-ga4/ga4-event-tracker.md
docs/analytics-ga4/ga4-link-tracker.md

Updating some of our GA4 docs.
We changed our tracking from disabled by default to enabled by default on most components and I didn't update these docs.
Also adds some documentation around how to add tracking to components.
None.
Trello card: https://trello.com/c/Xwp7dgJN/294-tracking-auditing-tracking-by-default

Update GA4 docs

---

CHANGELOG.md
app/assets/javascripts/govuk_publishing_components/analytics-ga4/pii-remover.js
spec/javascripts/govuk_publishing_components/analytics-ga4/pii-remover.spec.js

- There is some regex to remove dates from GA4 data in our PII remover
- This was taken from the UA PII remover
- The date regex was not very comprehensive, it only matched:
- Dates exactly like '1 January 1990'
- Dates exactly like '1990-01-01'
- 8 numbers in a row (i'm assuming to catch things like 01012000 - and I believe this is causing false positives for PAs)
- The new regex can match:
- 01/01/1990
- 01-01-1990
- 1-1-1990
- 1/1/1990
- 01\01\1990
- 1\1\1990
- 1990/01/01
- 1990-01-01
- 1990-1-1
- 1990/1/1
- 1990\1\1
- 1990\01\01
- Dates like: 1st of January 1990 (or 90 or '90),  25th of May 2005 (or 05 or '05)
- Dates like: 1st January 1990 (or 90 or '90), 25th October 2005 (or 05 or '05)
- Dates like: 1 January 1990 (or 90 or '90), 25 October 2005 (or 05 or '05)
- Dates like: 1 Jan …

Improve PII date removal

---

CHANGELOG.md
docs/component-wrapper-helper.md
lib/govuk_publishing_components/presenters/component_wrapper_helper.rb
spec/lib/govuk_publishing_components/components/component_wrapper_helper_spec.rb

- applications can't use the component wrapper helper in their components, because it doesn't allow classes that start with our convention for application components, `.app-c-componentname`
- extend the component wrapper to allow classes beginning with `app-c-` so that applications can use it
I want to use it in `finder-frontend` as part of some changes to tidy up our analytics code.
None.

Let applications use the component wrapper helper

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_option_select.html.erb
app/views/govuk_publishing_components/components/docs/option_select.yml

Use the component wrapper helper in the option select component.
Based on code originally written in `finder-frontend` by @floehopper
We need the ability to pass `data_attributes` to the component as part of some GA4 refactoring work.
None.
Trello card: https://trello.com/c/OdYXlYqQ/673-finder-frontend-code-optimisations

Use component wrapper on option select

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Use component wrapper on option select ([PR #3738](https://github.com/alphagov/govuk_publishing_components/pull/3738))

Version 36.0.1

---

CHANGELOG.md
lib/govuk_publishing_components/presenters/meta_tags.rb
spec/components/meta_tags_spec.rb

- To generate a new meta tag for GA4, we were diving into a nested value within the content_item JSON: `government[:details][:current]`
- `government_frontend` tests generate random but valid schemas to test against. Therefore, the test schema sometimes would contain the `government` object, but the `government` object wouldn't contain `[:details][:current]` and therefore crash.
- The error in `government_frontend` is: 
```Ruby
Minitest::UnexpectedError:         ActionView::Template::Error: undefined method `[]' for nil:NilClass
app/views/layouts/application.html.erb:63` 
``` 
- and `application.html.erb:63` was the call to render `meta_tags.html.erb.` in `government-frontend`. I used puts statements within `meta_tags.rb` in this repo  to determine which line in our GA4 meta tag code was …

 Prevent government_frontend test failure if meta tag key doesn't exist

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Prevent government_frontend test failure if meta tag key doesn't exist ([PR #3741](https://github.com/alphagov/govuk_publishing_components/pull/3741))

Version 36.0.2

---

CHANGELOG.md
app/assets/javascripts/govuk_publishing_components/analytics-ga4/ga4-core.js
app/assets/javascripts/govuk_publishing_components/analytics-ga4/ga4-form-tracker.js
app/assets/javascripts/govuk_publishing_components/analytics-ga4/ga4-page-views.js
spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-core.spec.js
spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-ecommerce-tracker.spec.js
spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-form-tracker.spec.js
spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-page-views.spec.js

- Search terms were being cleaned up in different ways by different trackers (These were the pageview tracker, the form tracker, and the ecommerce tracker)
- I have fixed this by creating a function which all trackers that utilise the search term now use. This function will cleanup/format the search term instead of the individual trackers.
- I then added extra tests where relevant to the trackers to ensure that they handled search terms in the same way.
- The PAs require the search term to be consistent across trackers so they can cross reference data/follow user journeys.
- Trello card: ['search_term' page_view parameter is coming through with capitals - should be lowercased](https://trello.com/c/Xuzx1cYM/738-searchterm-pageview-parameter-is-coming-through-with-capitals-should-be-lowercas …

Standardise search term formatting across GA4 trackers

---

app/assets/javascripts/govuk_publishing_components/analytics-ga4/ga4-link-tracker.js
spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-link-tracker.spec.js

- If the link tracker exists without `data-ga4-track-links-only`, it will assume every child element inside of it is an `<a>` tag with a href.
- However, sometimes we do not use `data-ga4-track-links-only`, so certain elements (e.g. SVG icons or paragraph text) are being run through our `trackClick` function in the link tracker. Since these elements do not have hrefs, the link tracking crashes when these elements are clicked.
- Examples include the SVG icons on the action links on the homepage, and the "Open Government License" paragraph text in the footer. Clicking either of these produces an error in the console.
- To fix this, we put a guard in that will `return` our `trackClick` function if there is no `href` on the link, or no `url` in the link tracker JSON.
- Prevents a JS error in …

Prevent crash when link tracker runs on a non-link element

---

CHANGELOG.md
lib/govuk_publishing_components/presenters/attachment_helper.rb

Add ZIP file support to attachment component
Missed during the migration in `whitehall` to use our attachment component
I've added an example to the components guide for the PR (which is why Percy is failing,) but will remove it before merging

Add ZIP file support to attachment component

---

app/assets/javascripts/govuk_publishing_components/lib/govspeak/youtube-link-enhancement.js

- where the analytics code is not run (such as the component guide) the image card video variant was experiencing a JS error
- this shouldn't happen in the wild but it shouldn't happen in our dev environments either
- added a simple check to ensure the code fails silently if analytics is not initialised
Error was `Uncaught TypeError: Cannot read properties of undefined (reading 'VideoTracker')`
None.

Fix error in video tracker

---

docs/analytics-ga4/ga4-event-tracker.md
docs/analytics-ga4/ga4-smart-answer-results-tracker.md
docs/analytics-ga4/ga4-specialist-link-tracker.md

Make the GA4 documentation better. See individual commits for details.
We want good documentation.
None.
Trello card: https://trello.com/c/u9CyaDoA/557-data-schema-documentation-might-be-out-of-date

Improve GA4 docs

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Standardise search term formatting across GA4 trackers ([PR #3746](https://github.com/alphagov/govuk_publishing_components/pull/3746))
* Add ZIP file support to attachment component ([PR #3751](https://github.com/alphagov/govuk_publishing_components/pull/3751))

Version 36.0.3

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_file_upload.html.erb
app/views/govuk_publishing_components/components/docs/file_upload.yml
spec/components/file_upload_spec.rb

- Aligns heading behaviour with other inputs (which allow for the label for the input to be wrapped in a heading tag)
- For situations where the input is the first or only thing on a page, and no other suitable heading is appropriate (https://design-system.service.gov.uk/patterns/question-pages/)
- https://trello.com/c/JFL2u0u0/2210-add-a-label-for-the-image-upload-input-element

Add heading option to file input component

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Add heading option to file input component ([PR #3755](https://github.com/alphagov/govuk_publishing_components/pull/3755))

Version 36.1.0

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/_image-card.scss

- Remove the scaling trick for the YouTube embedded video, this was [originally added to improve the keyboard navigation](https://github.com/alphagov/govuk_publishing_components/pull/3156) when tabbing to the controls on Desktop, however this no longer appears to be an issue after further testing
- Ensure the embedded YouTube video width is fluid and contained to its parent container
Fixes rendering issues with the YouTube image card variation of the image card component where the text overlaps with the image and the padding bottom added too much space to the bottom of the component as shown in the screenshots below.
Fixes: https://github.com/alphagov/govuk_publishing_components/issues/3675

Fix rendering of the image card YouTube variation

---

CHANGELOG.md
app/assets/javascripts/govuk_publishing_components/components/option-select.js
app/views/govuk_publishing_components/components/_option_select.html.erb
app/views/govuk_publishing_components/components/docs/option_select.yml
spec/components/option_select_spec.rb
spec/javascripts/components/option-select-spec.js

- modify the option select component to allow it to accept data attributes to be added to the expand/collapse button
- the attributes are rendered on the parent element, then read in by JavaScript to be included in the JavaScript generated button, which replaces the title element of the component
- to be used for GA4 tracking purposes in finder-frontend, in place of an existing solution
- will be a breaking change, as removes the event listener that was previously being used for this
- credit to @floehopper
We're currently using a system of event and event listeners between `finder-frontend` and this component in order to track this button's expand/collapse action. This approach allows us to remove some JavaScript and move most of the heavy lifting to the backend, which should reduce load …

Data attributes for option select button

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/_image-card.scss
app/views/govuk_publishing_components/components/_image_card.html.erb
app/views/govuk_publishing_components/components/docs/image_card.yml
lib/govuk_publishing_components/presenters/image_card_helper.rb
spec/components/image_card_spec.rb

- Move the style overrides for the two thirds image card variation used in the frontend app to the gem
- Add new local assign and method to check if `large_mobile_font_size` can be used. When set to true, the font size for the title and description will be 19px on all screen sizes.
- Add test for using large mobile font size on the two thirds image card variation
- Update image card documentation
Overrides to the publishing components is not best practice, it should be avoided as it makes the component harder to maintain, behaviour / rendering will be different than expected when following the component guide, it could break if the component is updated in the gem.
[Trello card](https://trello.com/c/jZu4Jnsc/2280-homepage-live-test-5-layout-follow-up-card-iterate-the-image-card-component-in …

Move image-card overrides from frontend app

---

CHANGELOG.md

Move the entry for "Move image-card overrides from frontend app" from "36.0.3" to "Unreleased" section of the changelog.
This entry should be under the unreleased section of the change log.

Fix change log entry

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* [BREAKING] Data attributes for option select button ([PR #3750](https://github.com/alphagov/govuk_publishing_components/pull/3750))
* Remove doNotTrack from GTM component ([PR #3760](https://github.com/alphagov/govuk_publishing_components/pull/3760))
* Fix rendering of the image card YouTube variation #3757 ([PR #3757](https://github.com/alphagov/govuk_publishing_components/pull/3757))
* Move image-card overrides from frontend app ([PR #3752](https://github.com/alphagov/govuk_publishing_components/pull/3752))
* Migrate to Dart Sass from LibSass ([PR #3604](https://github.com/alphagov/govuk_publishing_components/pull/3604))

Version 37.0.0

---

app/assets/javascripts/govuk_publishing_components/components/option-select.js
spec/javascripts/components/option-select-spec.js

Fixes a possible problem with the button data attributes functionality, where attribute names with more than one underscore might not have been properly converted. Noticed in https://github.com/alphagov/finder-frontend/pull/3224 relating to the expander component, which uses the same code for the same functionality.
None.

Adjust option select JavaScript

---

CHANGELOG.md
app/assets/javascripts/govuk_publishing_components/analytics-ga4.js
app/assets/javascripts/govuk_publishing_components/analytics-ga4/ga4-copy-tracker.js
app/assets/javascripts/govuk_publishing_components/analytics-ga4/ga4-schemas.js
app/assets/javascripts/govuk_publishing_components/analytics-ga4/ga4-video-tracker.js
docs/analytics-ga4/ga4-schemas.md
docs/analytics-ga4/ga4-video-tracker.md
spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-copy-tracker.spec.js
spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-schemas.spec.js
spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-video-tracker.spec.js

- tracks text copy events within the browser
- copied text is determined using the window.getSelection() method, assuming that some text has been highlighted to copy, if not does not send an event
- strips PII, line breaks etc. from text
Have tested this in the major browsers, seems to be okay. Just in case I've wrapped the whole thing in a `try/catch` block to catch anything I've not thought of.
None.
Trello card: https://trello.com/c/s6uLhovR/751-add-tracking-browser-copy-events

Add GA4 copy event tracker

---

docs/analytics-ga4/ga4-all-trackers.md
docs/analytics-ga4/ga4-copy-tracker.md

Adds some documentation for the GA4 copy tracker.
Forgot to add as part of https://github.com/alphagov/govuk_publishing_components/pull/3761
None.
Trello card: https://trello.com/c/s6uLhovR/751-add-tracking-browser-copy-events

Add documentation for the GA4 copy tracker

---

CHANGELOG.md
spec/dummy/config/initializers/dartsass.rb

Silence Sass deprecation warnings for dependencies.
GOV.UK Frontend displays the following deprecation warnings:
```
Deprecation Warning: Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.
Recommendation: math.div(200%, 3) or calc(200% / 3)
More info and automated migrator: https://sass-lang.com/d/slash-div
```
We are unable to fix the underlying issues so have silenced the warnings.
See https://frontend.design-system.service.gov.uk/importing-css-assets-and-javascript/#override-with-your-own-css.
None.
Issues will be created for deprecation warnings not originating from dependencies e.g.
```
Deprecation Warning: Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.
Recommendation: …
```

Silence Sass deprecation warnings for dependencies

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/_layout-header.scss

Fix duplicate font download issue.
This prevents inclusion of `@font-face` declarations (from `_layout-header.css`) which are not needed since they are served from elsewhere e.g. Static or the Component Guide stylesheets.
See https://frontend.design-system.service.gov.uk/sass-api-reference/#govuk-include-default-font-face.
None.

Fix duplicate font download issue

---

spec/component_guide/component_example_accessibility_testing_spec.rb

- Temporarily add `not_applicable: true` to a failing test
- It is causing our tests locally and on GitHub to fail
- I can raise an issue in our repo to investigate/fix this properly at a later date
None.

Skip running a failing component guide test

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_feedback.html.erb
app/views/govuk_publishing_components/components/docs/feedback.yml
app/views/govuk_publishing_components/components/feedback/_problem_form.html.erb
app/views/govuk_publishing_components/components/feedback/_survey_signup_form.html.erb
app/views/govuk_publishing_components/components/feedback/_yes_no_banner.html.erb

- Removes hardcoded `text` and `section` values from the GA4 Feedback tracking, using the translation variables instead
- Adds the `disable_ga4` variable to the component so that tracking can be disabled
https://trello.com/c/DbAXO3lU/556-stop-text-that-can-be-translated-using-hard-coded-text-values
Adds another example to the component page

Remove hardcoded text from GA4 'Feedback component' tracking, and add disable_ga4 option

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Remove hardcoded text from GA4 'Feedback component' tracking, and add disable_ga4 option ([PR #3769](https://github.com/alphagov/govuk_publishing_components/pull/3769))
* Add GA4 copy event tracker ([PR #3761](https://github.com/alphagov/govuk_publishing_components/pull/3761))
* Silence Sass deprecation warnings for dependencies ([PR #3771](https://github.com/alphagov/govuk_publishing_components/pull/3771))
* Fix duplicate font download issue ([PR #3772](https://github.com/alphagov/govuk_publishing_components/pull/3772))

Version 37.1.0

---

CHANGELOG.md
app/assets/config/govuk_publishing_components_manifest.js

Delete unused builds folder.
Fix `Sprockets::ArgumentError: link_tree argument must be a directory (Sprockets::ArgumentError)`.
The builds folder isn't required on its own; it's only necessary for the application (see [dummy app manifest here](https://github.com/alphagov/govuk_publishing_components/blob/main/spec/dummy/app/assets/config/manifest.js#L5)). The Dart Sass initializer (see [dummy app config here](https://github.com/alphagov/govuk_publishing_components/blob/main/spec/dummy/config/initializers/dartsass.rb), for example) compiles all Sass entry points, including those from the Publishing Components.
None.

Delete unused builds folder

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_metadata.html.erb
spec/components/metadata_spec.rb

- Having the tracking on this link triggers a link click and a select_content as it expands an accordion on the same page. So we remove the link click tracking so only one event fires for the interaction. Example of the issue: https://www.gov.uk/government/consultations/primate-licensing-scheme on the 'See all updates' link.
- https://trello.com/c/jf1V3D02/770-placeholder-duplicate-content-history-events-firing-on-some-pages
None.

Remove duplicate GA4 tracking

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_details.html.erb
app/views/govuk_publishing_components/components/docs/details.yml
spec/components/details_spec.rb

- adds GA4 tracking (by default) to the details component
- includes disable_ga4 option to disable tracking
- uses an OpenStruct to record the index of details components on a page for the `index_section` GA4 attribute
- total number of details components is also required for `index_section_count` attribute, but cannot determine automatically
- instead can pass a hash of GA4 attributes, which are then merged with the defaults
- passing can allow existing attributes to be overridden
- tracking on links not included owing to varying requirements, better to wrap the component in the link tracker in applications, where tracking is required
None.
Trello card: https://trello.com/c/xhASj1rp/765-add-tracking-to-details-component

Details component GA4 tracking

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_image_card.html.erb
app/views/govuk_publishing_components/components/docs/image_card.yml
spec/components/image_card_spec.rb

Rework how GA4 tracking is done on the image card component (prototyped a different approach in https://github.com/alphagov/govuk_publishing_components/pull/3788)
Specifically:
- don't include any tracking at all on the component 😱 
- refactor the component to use the component wrapper helper...
- ...which allows any data attributes to be passed safely to the component without overwriting existing ones
- ...meaning that the link tracker and required data attributes can be passed to the component where required
Pros:
- another component using the component wrapper helper
- no additional code for tracking on the component, all handled by passing options
Cons:
- arguably a breaking change, as the current tracking for the homepage uses of the image card will stop working
This PR removes the …

Refactor image card tracking

---

CHANGELOG.md
app/assets/javascripts/govuk_publishing_components/analytics-ga4/ga4-schemas.js
spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-auto-tracker.spec.js
spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-copy-tracker.spec.js
spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-core.spec.js
spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-event-tracker.spec.js
spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-link-tracker.spec.js
spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-schemas.spec.js
spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-scroll-tracker.spec.js
spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-video-tracker.spec.js

- change the schema code when merging properties to automatically convert all data to strings
- currently passing numbers for various data attributes (e.g. index_section) and all should be consistent types
- updating various tests accordingly
Have looked at various options for converting integers to strings in JS. `2 + ''` seems to be the most widely supported, fastest and least likely to break of the available options, but happy to discuss.
None.
Trello card: https://trello.com/c/nPhYtY0j/761-address-inconsistency-in-index-property-data-types

Ensure all GA4 data values are strings

---

CHANGELOG.md
app/assets/javascripts/govuk_publishing_components/lib/cookie-settings.js
app/assets/javascripts/govuk_publishing_components/load-analytics.js
spec/javascripts/govuk_publishing_components/lib/cookie-settings-spec.js
spec/javascripts/govuk_publishing_components/load-analytics.spec.js

Changes necessary to support allowing the [dev docs](https://docs.publishing.service.gov.uk/) to use the GA4 tracking code in the gem. See this [related PR](https://github.com/alphagov/govuk-developer-docs/pull/4376). Specifically:
- adjust the GA4 initialisation code to include variables for the tracking on the dev docs
- include the code from `frontend` for the cookie settings page, as it will now be used in more than just `frontend` (another PR will be raised later to remove this from `frontend`)
- refactor the code in load analytics
We want to extend GA4 tracking to the whole of the dev docs, not just the implementation record section.
None.
Trello card: https://trello.com/c/kA66mxak/755-extend-analytics-to-all-of-dev-docs

Allow GA4 tracking on dev docs

---

CHANGELOG.md
app/assets/javascripts/govuk_publishing_components/analytics-ga4/ga4-core.js
spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-auto-tracker.spec.js
spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-copy-tracker.spec.js
spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-core.spec.js
spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-event-tracker.spec.js
spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-form-tracker.spec.js
spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-link-tracker.spec.js
spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-page-views.spec.js
spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-print-intent-tracker.spec.js
spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-scroll-tracker.spec.js
spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-specialist-link-tracker.spec.js
spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-video-tracker.spec.js

- Adds a `timestamp` value sent with each dataLayer push. `timestamp` is the user's unix timestamp.
- Most of the tests I used `spyOn` to fake the timestamp as `123456`, probably necessary as it's impossible to predict what the timestamp will be before vs after some tracking code has run. However I've added one test in `ga4-core` that tests the actual timestamp and it works. I think because the test is so simple, modern computers are fast enough that it can grab the timestamp for the expected and actual value, and it's so fast that the timestamp wouldn't have incremented yet.
- Will add a CHANGELOG once approved as I suspect this won't be merged until 2024.
- So that the PAs can easily sort the events to see a users journey 
None.

Add timestamp value to GA4 dataLayer pushes

---

CHANGELOG.md
app/assets/stylesheets/component_guide/application.scss
app/assets/stylesheets/govuk_publishing_components/components/_contents-list.scss
app/assets/stylesheets/govuk_publishing_components/components/_image-card.scss
app/assets/stylesheets/govuk_publishing_components/components/_modal-dialogue.scss
app/assets/stylesheets/govuk_publishing_components/components/_search.scss
app/assets/stylesheets/govuk_publishing_components/components/_share-links.scss
app/assets/stylesheets/govuk_publishing_components/components/_step-by-step-nav-related.scss
app/assets/stylesheets/govuk_publishing_components/components/_step-by-step-nav.scss
app/assets/stylesheets/govuk_publishing_components/components/_table.scss
app/assets/stylesheets/govuk_publishing_components/components/govspeak/_warning-callout.scss
app/assets/stylesheets/govuk_publishing_components/components/helpers/_markdown-typography.scss
app/assets/stylesheets/govuk_publishing_components/components/mixins/_grid-helper.scss

Fix Sass deprecation warnings related to using `/` for division outside of `calc()`.
Using `/` for division outside of `calc()` is deprecated and will be removed in Dart Sass 2.0.0.
None.

Fix Sass deprecation warnings

---

CHANGELOG.md
app/assets/stylesheets/component_guide/application.scss
app/assets/stylesheets/govuk_publishing_components/components/_contents-list.scss
app/assets/stylesheets/govuk_publishing_components/components/_image-card.scss
app/assets/stylesheets/govuk_publishing_components/components/_modal-dialogue.scss
app/assets/stylesheets/govuk_publishing_components/components/_search.scss
app/assets/stylesheets/govuk_publishing_components/components/_share-links.scss
app/assets/stylesheets/govuk_publishing_components/components/_step-by-step-nav-related.scss
app/assets/stylesheets/govuk_publishing_components/components/_step-by-step-nav.scss
app/assets/stylesheets/govuk_publishing_components/components/_table.scss
app/assets/stylesheets/govuk_publishing_components/components/govspeak/_warning-callout.scss
app/assets/stylesheets/govuk_publishing_components/components/helpers/_markdown-typography.scss
app/assets/stylesheets/govuk_publishing_components/components/mixins/_grid-helper.scss

Revert changes to fix Sass deprecation warnings
Due to compile errors when running `yarn jasmine:prepare` from an application.
None.

Revert changes to fix Sass deprecation warnings

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Revert changes to fix Sass deprecation warnings ([PR #3810](https://github.com/alphagov/govuk_publishing_components/pull/3810))

Version 37.2.1

---

CHANGELOG.md
app/assets/javascripts/govuk_publishing_components/analytics-ga4/ga4-page-views.js
spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-page-views.spec.js

- Removes hyphens and downcases the GA4 publishing government values
- Prevents duplicate values being sent to GA4, due to slight differences in casing/spacing of the meta values
- https://trello.com/c/rxbAaj4N/769-publishing-government-being-collected-with-varying-formatting
None.

Remove hyphens and downcase the GA4 publishing government value

---

spec/components/all_components_spec.rb

- adds a test to check that component template files are named correctly
- already tests for YML and SCSS files, but not for template
- in order to get an unbiased component name, the initial variable has to be modified, this is to catch the two main problems with component names: extension named .erb instead of .html.erb, and `-` used instead of `_`
Relates to issue https://github.com/alphagov/govuk_publishing_components/issues/3369
Hoping to port this test to other applications to reduce file naming inconsistencies and improve auditing tool impact.
None.

Test component filenames

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/_step-by-step-nav.scss

Fix Sass negative mixin / value issue for [step by step navigation (with links)](https://components.publishing.service.gov.uk/component-guide/step_by_step_nav/with_links/preview) component.
Invalid CSS is compiled:
```
@media (min-width: 40.0625em)
.gem-c-step-nav--large .gem-c-step-nav__paragraph+.gem-c-step-nav__list {
margin-top: -govuk-spacing(3);
}
```

Fix Sass negative mixin / value issue

---

CHANGELOG.md
config/locales/en.yml

On pages such as the social media feeds “Sharing will open the page in the new tab” is confusing and not accurate. Suggestion that the copy should be something like “The following links open in a new tab" to be clearer.
To help users understand what happens on their browse when sharing and it shouldn’t be confusing.
[Trello ticket](https://trello.com/c/UeGITj5l/2276-update-social-media-tab-copy-in-the-gem-s)
The screenshots below reflect the old proposed wording. After some discussion, the new wording is "The following links open in a new tab". I have not remade the screenshots.

Change social media links advice text

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Remove hyphens and downcase the GA4 publishing government value ([PR #3808](https://github.com/alphagov/govuk_publishing_components/pull/3808))
* Fix Sass negative mixin / value issue ([PR #3816](https://github.com/alphagov/govuk_publishing_components/pull/3816))
* Change social media links advice text ([PR #3814](https://github.com/alphagov/govuk_publishing_components/pull/3814))
* Remove current-location.js ([PR #3812](https://github.com/alphagov/govuk_publishing_components/pull/3812))

Version 37.2.2

---

CHANGELOG.md
lib/govuk_publishing_components/presenters/machine_readable/organisation_schema.rb
spec/lib/govuk_publishing_components/presenters/schema_org_spec.rb

- Adds a reference to the GOVUK logo in our `schema.org` `GovernmentOrganization` schema. 
- This schema is used by organisation index pages such as https://www.gov.uk/government/organisations/cabinet-office to provide metadata about the page to machines i.e. Google Search results.
- There is an issue on organisation pages in Google search results right now as Google is picking a random image from the organisation pages to feature next to the search results on Google. For example on this search result, it is using the our currently "Featured" image on the cabinet office page as the image next to the search result: https://www.google.com/search?q=cabinet-office
- This is a problem as we do not have control over which image it picks. Google seems to decide what image they think is best. …

Add GOVUK logo to GovernmentOrganization schema.org schemas

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Add GOVUK logo to GovernmentOrganization schema.org schemas ([PR #3827](https://github.com/alphagov/govuk_publishing_components/pull/3827))

Version 37.2.3

---

CHANGELOG.md
app/assets/javascripts/govuk_publishing_components/analytics-ga4/ga4-page-views.js
spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-page-views.spec.js

- Currently we populate the GA4 Pageview `search_term` parameter by using regex - we grab it from the URLs `keywords` query string parameter. This has two downsides. 
- The first downside was identified by PAs. Symbols are being added in odd ways via `keywords` which causes inconsistency between the other ways we add search terms to GA4 (i.e. it differs from how the search term appears in the form tracker/ecommerce tracker.)
- The second downside I noticed during testing is that using the `keywords=` method does not work properly if the user's keyword contains an ampersand.  This is because our regex uses `&` to signal the end of the search term. However we can't tell whether this an ampersand is actually a part of their search term, or is the end of their search term and the start of …

Improve reliability of grabbing GA4 search term value

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_warning_text.html.erb
app/views/govuk_publishing_components/components/docs/warning_text.yml
spec/components/warning_text_spec.rb

Adds GA4 tracking to the warning text component
https://trello.com/c/bh96e5IG/776-callout-link-tracking
None.

Add GA4 tracking to warning text component

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Fix analytics consent ([PR #3833](https://github.com/alphagov/govuk_publishing_components/pull/3833))
* Improve reliability of grabbing GA4 search term value ([PR #3818](https://github.com/alphagov/govuk_publishing_components/pull/3818))
* Update Cross Service Header component ([PR #3831](https://github.com/alphagov/govuk_publishing_components/pull/3831))
* Add GA4 tracking to warning text component ([PR #3832](https://github.com/alphagov/govuk_publishing_components/pull/3832))

Version 37.2.4

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_attachment.html.erb
app/views/govuk_publishing_components/components/docs/attachment.yml
spec/components/attachment_spec.rb

- extend the attachment component (which can contain the details component) to allow GA4 tracking attributes to be passed through to the details component
- details component does most of its own tracking but requires the `index_section_count` attribute to be passed manually
No changes to the component, but have added an extra entry in the attachment doc, so will trigger a diff.
Trello card: https://trello.com/c/xhASj1rp/765-add-tracking-to-details-component

Allow attachment to pass tracking to details

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_back_link.html.erb
app/views/govuk_publishing_components/components/docs/back_link.yml
spec/components/back_link_spec.rb

Adds tracking by default to the back link component.
None (apart from changes to the component guide)
Trello card: https://trello.com/c/Z5FYBU5o/782-back-links

Add tracking to back link

---

docs/component-wrapper-helper.md

Improve the documentation for the component wrapper helper.
It was a bit long and although it explained everything the wrapper does, it went into perhaps too much detail. It was also hard to use when actually implementing the wrapper on a component, so I've grouped most of the options together into one example that can be more easily copied and pasted into code.
None. Well, some words, obviously.

Improve component wrapper documentation

---

CHANGELOG.md
app/assets/javascripts/govuk_publishing_components/analytics-ga4/ga4-link-tracker.js
app/views/govuk_publishing_components/components/_govspeak.html.erb
app/views/govuk_publishing_components/components/docs/govspeak.yml
spec/components/govspeak_spec.rb
spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-link-tracker.spec.js

- Adds the `ga4-link-tracker` to the highest parent level element of `govspeak` content
- I tried to use the component wrapper, but it did not like the fact that this component uses classes that don't start with `js-`. So I reverted my component wrapper code in one of the commits.
- I had to write some code to make sure nested links with their own `data-ga4-link` don't end up firing tracking twice, as if the govspeak `<div>` that wraps all the content also has a `data-ga4-link` attribute on it then two link trackers would fire on the same link.
https://trello.com/c/bh96e5IG/776-add-tracking-callout-links
None except adding the docs example

Add GA4 link tracking to govspeak callout links

---

CHANGELOG.md
app/assets/javascripts/govuk_publishing_components/analytics/init.js
spec/javascripts/govuk_publishing_components/analytics/analytics.spec.js

Removes the cookie consent sharing code that relates to Digital Identity. This code was implemented to reduce the appearance of cookie banners when subscribing to emails on GOV.UK, as the journey takes the user between different sites.
Broadly, it works like this:
- coming from the DI site, the URL is decorated with either `?cookie_consent=accept` or `?cookie_consent=reject`
- this code checks the URL and if it finds this parameter, updates the local cookie preferences accordingly
Initial investigations suggest that this isn't in use in the DI code anymore - I've talked to @danacotoran and manually tested it, and the URL parameter this code looks for doesn't appear when moving from DI to GOV.UK.
We also need to remove this in order to move ahead with the [single consent API …

Remove DI cookie consent code

---

app/assets/javascripts/govuk_publishing_components/analytics-ga4/ga4-core.js
app/assets/javascripts/govuk_publishing_components/modules.js

Improve the `console.error` messages in the console when modules (and GA4 modules) fail to start, by displaying the full error in the console, not just the message part, so it's easier to track down exactly why the module failed to start.
I was having a problem with a module and realised the error handling could be more helpful.
Original:
New:

Improve error messages for module starting

---

app/models/govuk_publishing_components/audit_comparer.rb

Remove `whitehall` from the list of applications in the component audits that rely on `static`. This list is used to check assets used within the application are correct for components used within the application. `Static` has a few component assets already included, this part of the audit uses that knowledge to stop highlighting things that could be problems, but aren't (for example, `static` includes the JS for the button component, so applications that rely on `static` don't need to duplicate include that JS as well).
- `whitehall` doesn't use static anymore, so removing it from list of applications that do
- makes no difference to the auditing results, fortunately
None.

Update whitehall in component auditing

---

CHANGELOG.md
app/assets/javascripts/govuk_publishing_components/analytics-ga4/ga4-auto-tracker.js
app/assets/javascripts/govuk_publishing_components/analytics-ga4/ga4-event-tracker.js
app/assets/javascripts/govuk_publishing_components/analytics-ga4/ga4-form-tracker.js
app/assets/javascripts/govuk_publishing_components/analytics-ga4/ga4-link-tracker.js
app/assets/javascripts/govuk_publishing_components/analytics-ga4/ga4-scroll-tracker.js
app/assets/javascripts/govuk_publishing_components/analytics-ga4/ga4-smart-answer-results-tracker.js
app/assets/javascripts/govuk_publishing_components/analytics-ga4/init-ga4.js
app/assets/javascripts/govuk_publishing_components/analytics/auto-scroll-tracker.js
app/assets/javascripts/govuk_publishing_components/lib/govspeak/youtube-link-enhancement.js
app/assets/javascripts/govuk_publishing_components/rum-loader.js
docs/javascript-modules.md
spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-auto-tracker.spec.js
spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-event-tracker.spec.js
spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-form-tracker.spec.js
spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-link-tracker.spec.js
spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-scroll-tracker.spec.js
spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-smart-answer-results-tracker.spec.js

We have various bits of code that should only initialise if cookie consent is given. Since this can be given after page load (by the user clicking on the cookie banner) we have event listeners in place for the `cookie-consent` event, which is triggered by user consent.
The JS documentation states that these event listeners should be removed once triggered, but almost none of our code does this. This PR fixes this oversight, as well as updating some tests relating to these scripts. It also includes the same change for the RUM script, which is slightly different (hence a separate commit).
Following good practice. Also will make working on the single consent API changes easier. These commits were originally part of https://github.com/alphagov/govuk_publishing_components/pull/3829 but …

Update cookie event listeners

---

CHANGELOG.md
app/assets/javascripts/govuk_publishing_components/analytics-ga4/ga4-form-tracker.js
docs/analytics-ga4/ga4-form-tracker.md
spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-core.spec.js
spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-form-tracker.spec.js

- For the contact form tracking, there are three text inputs currently being collected on form submission
- The analysts are interested in collecting one of these text inputs. Therefore, I needed a way to only include that one for tracking and redact the rest.
- Therefore, a new data attribute called `data-ga4-form-include-input` has been added. If this is placed on the input, it will be included in the `text` list instead of being `[REDACTED]`
- Not using `data-ga4-form-include-text` as I don't want the other three inputs being included in the list. One of them is there user's name for contact form so doing it this way this instead makes sure that is not included in the contact form tracking.
- Progresses https://trello.com/c/jFRhH4Dh/783-adding-tracking-contact-form
None

Allow inputs to be exempt from GA4 form tracker [REDACT] code

---

CHANGELOG.md
app/assets/javascripts/govuk_publishing_components/components/cookie-banner.js
app/assets/stylesheets/govuk_publishing_components/components/_cookie-banner.scss
app/views/govuk_publishing_components/components/_cookie_banner.html.erb
app/views/govuk_publishing_components/components/docs/cookie_banner.yml
spec/javascripts/components/cookie-banner-spec.js

- Hides our cookie banner when JS is disabled
- Tested in `static` with Chrome/Firefox/Safari on Mac, and IE11 on Windows
- Has approval from our privacy people. Data protection officer: _"agrees it sounds fine, so long as we have the cookie notice linked at the bottom of the page (no message or banner necessary)"_ 
- We've had a couple of users who use the page without JavaScript mention to us that the banner is displayed. I assume the main issue being it takes up a lot of screen space for them.
If you want to test it on `static` but have issues try this. I keep having issues with my `static` updating its assets, so to get `static` to work I had to:
- Change _public_layout.html.erb in publishing components to use `<link rel="stylesheet" href="/assets/static/application.css" media="all">` …

Hide our cookie banner when JS is disabled

---

CHANGELOG.md
app/assets/javascripts/govuk_publishing_components/dependencies.js
app/assets/javascripts/govuk_publishing_components/load-analytics.js
docs/load-analytics.md
spec/javascripts/govuk_publishing_components/load-analytics.spec.js

Extends the existing `load-analytics.js` to allow other domain details to be included when checking how to initialise GA4 (and UA, although this is soon to be deprecated). This is part of the work needed to allow the components gem analytics code to run on our publishing applications (we can also switch to using this method for the dev docs analytics, instead of hard coding the details here).
None.

Allow other applications to use GA4 code

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_layout_for_public.html.erb
spec/components/layout_for_public_spec.rb

Move the skip link after the cookie banner.
**Review URL**: https://components-gem-pr-3863.herokuapp.com/component-guide/layout_for_public/full_width/preview
https://trello.com/c/AGHUDMGb/76-skip-link-unexpectedly-before-cookie-banner
https://github.com/alphagov/govuk_publishing_components/issues/3860

Move the skip link after the cookie banner

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/_print-link.scss
app/assets/stylesheets/govuk_publishing_components/components/_single-page-notification-button.scss

These changes update the colour of the border on the "Print link" and "Single page notification button" components. 
The borders on these components have been reported in DAC's audit to be too faint: #b1b4b6 against white is only a contrast of 2.1:1. Although this will not affect functionality of the button, it means that lots of people won’t see the border.
See Trello card [103 | Some button's borders are too faint](https://trello.com/c/awwxbZSm/103-some-buttons-borders-are-too-faint)
||Print link|Single page notification button|
|-|-|-|
|**Before**|![Screenshot 2024-02-06 at 10 09 14](https://github.com/alphagov/govuk_publishing_components/assets/6080548/9e13255b-f6af-4de8-a3de-a1bd1be08e23)|![Screenshot 2024-02-06 at 10 07 33](https://github.com/alphagov/govuk_publishing_components/asse …

Update border colours on email/print buttons for greater contrast

---

CHANGELOG.md
app/assets/stylesheets/component_guide/application.scss
app/assets/stylesheets/govuk_publishing_components/components/_contents-list.scss
app/assets/stylesheets/govuk_publishing_components/components/_image-card.scss
app/assets/stylesheets/govuk_publishing_components/components/_modal-dialogue.scss
app/assets/stylesheets/govuk_publishing_components/components/_search.scss
app/assets/stylesheets/govuk_publishing_components/components/_share-links.scss
app/assets/stylesheets/govuk_publishing_components/components/_step-by-step-nav-related.scss
app/assets/stylesheets/govuk_publishing_components/components/_step-by-step-nav.scss
app/assets/stylesheets/govuk_publishing_components/components/_table.scss
app/assets/stylesheets/govuk_publishing_components/components/govspeak/_warning-callout.scss
app/assets/stylesheets/govuk_publishing_components/components/helpers/_markdown-typography.scss

Fix some Sass deprecation warnings related to using `/` for division outside of `calc()`.
Using `/` for division outside of `calc()` is deprecated and will be removed in Dart Sass 2.0.0.
None.
- previous attempts to fix the warnings led to errors when precompiling assets in applications that bundle `sassc-rails` (LibSass) https://github.com/alphagov/govuk_publishing_components/issues/3776 and https://github.com/alphagov/govuk_publishing_components/pull/3810
- currently, only six deprecation warnings remain
- these warnings are caused by using the `calc()` CSS function as an argument inside of another Sass function or mixin
- the issue seems to have been reported previously: https://github.com/alphagov/govuk-frontend/issues/1350
- perhaps the remaining warnings can be fixed when we remove …

Fix some Sass deprecation warnings

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_share_links.html.erb
app/views/govuk_publishing_components/components/docs/share_links.yml
spec/components/share_links_spec.rb

- Adds a variable called `ga4_data` to the share links component.
- This variable allows an object to be passed through to the component with extra GA4 values.
- The PAs would like us to add a `section` value for share links. As the share link component is rendered in a range of different places, the `section` will need to be passed through wherever the component is rendered.
- https://trello.com/c/gAiBgeTx/785-add-tracking-organisation-pages
The component example was updated to reflect the changes

Expand GA4 share link tracking to allow for extra values

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Move the skip link after the cookie banner ([PR #3863](https://github.com/alphagov/govuk_publishing_components/pull/3863))
* Update border colours on email/print buttons for greater contrast ([PR #3855](https://github.com/alphagov/govuk_publishing_components/pull/3855))
* Fix some Sass deprecation warnings ([PR #3864](https://github.com/alphagov/govuk_publishing_components/pull/3864))
* Expand GA4 share link tracking to allow for extra values ([PR #3872](https://github.com/alphagov/govuk_publishing_components/pull/3872))

Version 37.3.1

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_metadata.html.erb
spec/components/metadata_spec.rb

- Removes the `action` value from `navigation` versions of the `content history` event
- We have a `select_content` version of this event which needs the `action`, but we forgot to remove it from the `navigation` version of the event
- https://trello.com/c/3WrRBUCk/787-remove-action-parameter-on-content-history-navigation-events
None

Remove GA4 'action' from navigation content history events

---

CHANGELOG.md
lib/govuk_publishing_components/presenters/breadcrumb_selector.rb
lib/govuk_publishing_components/presenters/contextual_navigation.rb
spec/components/contextual_breadcrumbs_spec.rb

This logic rewrite ensures that:
- In cases where specialist (Whitehall) content is tagged to a Mainstream Browse Page **and** its tagged parent is also a MSB, the breadcrumbs are set by ancestry (which was the original behaviour, minus the parent check).
- In cases where specialist (Whitehall) content is tagged to a MSB but there is no parent (or the parent is not an MSB), the breadcrumbs are set from the taxonomy.
When guidance pages were linked to mainstream browse pages after their related specialist topic was archived, the pages had no parent tag. They were tagged to taxonomy, but this was not reflected in the breadcrumb, only showing "Home."
https://trello.com/c/ls1MlMKC/2369-breadcrumb-disappears-when-whitehall-content-is-tagged-to-msb-m
Here is an example [MSB tagged guidance page …

Add Breadcrumb Handling for Mainstream Browse Pages with no Parent

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_notice.html.erb
app/views/govuk_publishing_components/components/docs/notice.yml
spec/components/notice_spec.rb

- Add GA4 tracking to the notice link component
- This component contains a nested `govspeak` component, so we disable tracking on this component so that our tracking is not duplicated by possibly having two link trackers running.
https://trello.com/c/f4i7CKvO/791-add-tracking-notice-links
Component example updated with a `With ga4 tracking disabled` example

Add GA4 tracking to the notice link component

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Update LUX to 313 ([PR #3884](https://github.com/alphagov/govuk_publishing_components/pull/3884))
* Ensure whitehall content tagged to mainstream browse and the topic taxonomy has a topic taxonomy breadcrumb ([PR #3871](https://github.com/alphagov/govuk_publishing_components/pull/3871))
* Add GA4 tracking to the document list component ([PR #3874](https://github.com/alphagov/govuk_publishing_components/pull/3874))
* Remove GA4 'action' from navigation content history events ([PR #3877](https://github.com/alphagov/govuk_publishing_components/pull/3877))
* Add GA4 tracking to the notice link component ([PR #3885](https://github.com/alphagov/govuk_publishing_components/pull/3885))

Version 37.5.0

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_govspeak.html.erb
app/views/govuk_publishing_components/components/docs/govspeak.yml
spec/components/govspeak_spec.rb

- Remove callout link tracking from `govspeak` component
- Due to how our tracking is architected, adding this tracking removed some external link tracking that we think is higher priority to track. Therefore disable tracking while we come up with a fix.
Removed example from `.yml`

Remove GA4 callout tracking from govspeak component

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Remove GA4 callout tracking from govspeak component ([PR #3889](https://github.com/alphagov/govuk_publishing_components/pull/3889))

Version 37.5.1

---

CHANGELOG.md
app/assets/javascripts/govuk_publishing_components/analytics-ga4/ga4-core.js
app/assets/javascripts/govuk_publishing_components/analytics/analytics.js
app/assets/javascripts/govuk_publishing_components/lib/cookie-settings.js
spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-core.spec.js
spec/javascripts/govuk_publishing_components/analytics/analytics.spec.js
spec/javascripts/govuk_publishing_components/lib/cookie-settings-spec.js
spec/javascripts/helpers/SpecHelper.js

- Currently, if a user has `usage` cookies set to `true`, and then disables them on `/help/cookies`, our tracking still fires on the cookie settings page until they refresh/navigate away. (This doesn't affect other pages on GOV.UK as our JS will reinitialise every time they go to another page, which then checks their consent status.)
- I have fixed this by setting a boolean called `window.GOVUK.stopSendingAnalytics` to `true` when they disable usage cookies. This boolean is then checked in Universal Analytics and GA4 before they send tracking data.
- I've set `window.GOVUK.LUX` to an empty object (`{}`) when they disable the usage cookie as well, but I'm not sure how to test if this actually doing anything.
- I'm assuming the only tracking stuff we have on our site is UA, GA4, and LUX. …

Ensure analytics stops firing if a user disables usage cookies on our cookie settings page

---

CHANGELOG.md
app/assets/javascripts/govuk_publishing_components/lib/cookie-settings.js

- The cookie settings code has a line to grab the document referrer. It partly used the `URL` object for this.
- `URL` is unsupported in IE11, so it was crashing on save in IE11
-  Use try/catch to grab the referrer value instead
- It looks new URL(document.referrer).pathname has been in the code for 5 years https://github.com/alphagov/frontend/blame/1ee93d82ba4f33e95fd5e4136b656d32963d2489/app/assets/javascripts/modules/cookie-settings.js#L98
- /help/cookies is crashing when saving the form in production in IE11
None

Fix cookie settings page crash in IE11

---

app/assets/stylesheets/govuk_publishing_components/components/_search.scss

Rework the sass for the search component SVG icon, which used a mixin with a calc function to determine the correct `top` and `left` values based on a given container size. Instead use a simpler effect - set the icon to be the height and width of the parent, but scale it by half (origin defaults to the center). Since the button is 40px and the icon should be 20px this should result in no visual difference.
For the large icon, the search icon should remain the same size, despite the button being 10px larger at 50px. Instead we apply a scale of `.4`, which results in the same size.
Trying to use the search component in the govuk-dev-docs, which is running on an older version of Sass and doesn't interpret the `calc` part properly (it outputs it without calculating it, resulting in an invalid …

Rework search icon styles

---

CHANGELOG.md
config/locales/en.yml

Update popular links in the search in the header to match those on the body of the page, as defined in  https://github.com/alphagov/frontend/blob/main/config/locales/en.yml#L572-L584
Both parts of the page should contain the same links. These were missed from https://github.com/alphagov/frontend/pull/3524
|Before|After|
|-|-|
|<img width="948" alt="Screenshot 2024-03-05 at 20 39 20" src="https://github.com/alphagov/govuk_publishing_components/assets/17908089/34fc7572-9781-40ac-88fc-7bb1a8c6c0a6">|<img width="999" alt="Screenshot 2024-03-05 at 21 25 56" src="https://github.com/alphagov/govuk_publishing_components/assets/17908089/772c1e5f-6c03-43ee-a58b-fff8320af806">|

Update popular links in search header

---

app/controllers/govuk_publishing_components/audit_controller.rb
app/models/govuk_publishing_components/audit_comparer.rb

info-frontend is now retired.
Trello:
https://trello.com/c/sWZM0a38/2387-archive-repo-in-github

Remove info-frontend refs

---

CHANGELOG.md
app/assets/javascripts/govuk_publishing_components/components/cookie-banner.js
app/assets/javascripts/govuk_publishing_components/domain-config.js
app/assets/javascripts/govuk_publishing_components/lib/cookie-settings.js
app/assets/javascripts/govuk_publishing_components/lib/govspeak/youtube-link-enhancement.js
app/assets/javascripts/govuk_publishing_components/lib/single-consent-functions.js
app/assets/javascripts/govuk_publishing_components/load-analytics.js
docs/load-analytics.md
package.json
spec/javascripts/components/cookie-banner-spec.js
spec/javascripts/components/govspeak-spec.js
spec/javascripts/govuk_publishing_components/lib/cookie-settings-spec.js
spec/javascripts/govuk_publishing_components/lib/govspeak/youtube-link-enhancement-spec.js
spec/javascripts/govuk_publishing_components/lib/single-consent-functions-spec.js
spec/javascripts/govuk_publishing_components/load-analytics.spec.js
yarn.lock

Adds code for the [single consent cookie API](https://github.com/alphagov/consent-api) to allow cookie preferences to be shared across GOV.UK.
Supersedes https://github.com/alphagov/govuk_publishing_components/pull/3829
The single consent API should take control of the setting of cookies relating to cookie consent. Fortunately it sets exactly the same cookies as we do now:
- `cookies_preferences_set` indicating that a user preference has been made
- `cookies_policy` showing the preferences chosen (set by default to no consent)
There are two main things to test - when the consent API is enabled, and when it is not. When it is not enabled (by default) everything should work as normal. This means:
- a users first visit should set the `cookies_policy` to reject all but essential cookies, and …

Add single cookie consent API

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Add single cookie consent API ([PR #3854](https://github.com/alphagov/govuk_publishing_components/pull/3854))
* Update popular links in super navigation header ([PR #3904](https://github.com/alphagov/govuk_publishing_components/pull/3904))
* Allow custom text for GA4 scroll tracker ([PR #3896](https://github.com/alphagov/govuk_publishing_components/pull/3896))
* Ensure analytics stops firing if a user disables usage cookies on our cookie settings page ([PR #3893](https://github.com/alphagov/govuk_publishing_components/pull/3893))
* Fix cookie settings page crash in IE11 ([PR #3894](https://github.com/alphagov/govuk_publishing_components/pull/3894))

Version 37.6.0

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/_contents-list.scss
app/views/govuk_publishing_components/components/_contents_list.html.erb
app/views/govuk_publishing_components/components/docs/contents_list.yml
spec/components/contents_list_spec.rb

Stop dashes before each 'Contents' list item being read by screen readers
Nearly every screen reader (except NVDA of the major ones) reads out the “em dash“ before each item/link in the “Contents“ list. Screen reader users found that frustrating to read through.
[Trello card](https://trello.com/c/MajjZ6ds/2414-dashes-before-each-contents-list-item-read-by-screen-readers-m-l)
| Screen Reader | Browser | Issue fixed |
| NVDA - 2023.3.3 | Firefox - 123 | fixed :white_check_mark: |
| Narrator - 21H2 | Edge 122 | fixed :white_check_mark: |
| JAWS 2022 | Chrome | fixed :white_check_mark: |
| JAWS 2023 | Chrome|  fixed :white_check_mark: |
| VoiceOver 10 | Safari 17.3.1 | fixed :white_check_mark: |
| VoiceOver 10 | Safari 17.3.1 | fixed :white_check_mark: |
| VoiceOver 10 | …

Fix accessibility issue in contents list component

---

spec/javascripts/govuk_publishing_components/lib/cookie-functions-spec.js

Fix intermittently failing tests in the cookie functions.
- some of the tests in this file were intermittently failing (even only using specific seeds 51181 and 04195)
- no cleanup was present for these tests, which now run alongside a lot more tests involving the single consent API, so it seems likely that uncleared cookies were causing this problem
None.

Fix failing test

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Include single consent api package ([PR #3908](https://github.com/alphagov/govuk_publishing_components/pull/3908))
* Fix accessibility issue in contents list component ([PR #3907](https://github.com/alphagov/govuk_publishing_components/pull/3907))

Version 37.6.1

---

CHANGELOG.md
app/assets/javascripts/govuk_publishing_components/analytics-ga4/ga4-specialist-link-tracker.js
app/views/govuk_publishing_components/components/_govspeak.html.erb
app/views/govuk_publishing_components/components/docs/govspeak.yml
spec/components/govspeak_spec.rb
spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-specialist-link-tracker.spec.js
spec/javascripts/govuk_publishing_components/analytics-ga4/init-ga4.spec.js
spec/javascripts/helpers/SpecHelper.js

- Reintroduces the `callout` tracking and fixes an issue with it we discovered on production. The fix is detailed in the below bullet points.
- There are two link trackers in our GA4 tracking - the `ga4-link-tracker` and the `ga4-specialist-link-tracker`
- The `ga4-link-tracker` is more specific, so it usually overrides the specialist link tracker when it exists on an element. The hierarchy for link tracking is this:
- If the `ga4-link-tracker` is on an element, the `ga4-link-tracker` should track the clicked link
- If the `ga4-link-tracker` is on an element with `data-ga4-limit-to-element-class`, and the clicked link is within the right class, the `ga4-link-tracker` should track the link
- If the `ga4-link-tracker` is on an element with `data-ga4-limit-to-element-class`, and the clicked …

Reintroduce GA4 callout tracking and fix link tracker compatibility

---

docs/organisation-logos.md

Add documentation for adding/updating single identity logos in the [organisation-logos](https://components.publishing.service.gov.uk/component-guide/organisation_logo) component.
Will be good to reference this documentation when looking at how organisation logos are updated on GOVUK, for both single identity logos and logos that are exempt.
[Trello card](https://trello.com/c/QtTiOIWM/2420-create-documentation-for-updating-organisation-logos-m)
The documentation added here will also be linked to from the developer docs, I've created a new PR here as well which goes into a bit further detail on the different types of logos that can be used and how to deploy a new organisation logo https://github.com/alphagov/govuk-developer-docs/pull/4547

Add docs for Organisation Logos

---

CHANGELOG.md
app/assets/javascripts/govuk_publishing_components/components/layout-super-navigation-header.js
app/assets/javascripts/govuk_publishing_components/lib/trigger-event.js
app/views/govuk_publishing_components/components/_layout_super_navigation_header.html.erb
app/views/govuk_publishing_components/components/docs/layout_super_navigation_header.yml
spec/javascripts/components/layout-super-navigation-header-spec.js

Trello cards: 
- [Adjust keyboard functionality of dropdown menu [L]](https://trello.com/c/ke3jvHve/2400-adjust-keyboard-functionality-of-dropdown-menu-l)
- [Unexpected focus order when activating menu button in header](https://trello.com/c/v6hdKvtj/11-unexpected-focus-order-when-activating-menu-button-in-header)
These changes update the behaviour of some keyboard functionality on the header component: 
- Adds a `handleKeyDown` method to the `layout-super-navigation-header` component to handle 'tab' and 'escape' key events
- Adds tests for the new functionality
- Updates the trigger-event lib component to accept values for the shift key
There are a some accessibility failures on the header whereby
- a user navigating with the tab key traverses the elements in an unpredictable and …

Adjust keyboard functionality of dropdown menu

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Reintroduce GA4 callout tracking and fix link tracker compatibility ([PR #3905](https://github.com/alphagov/govuk_publishing_components/pull/3905))
* Adjust keyboard functionality of dropdown menu ([PR #3888](https://github.com/alphagov/govuk_publishing_components/pull/3888))

Version 37.7.0

---

CHANGELOG.md
app/assets/javascripts/govuk_publishing_components/dependencies.js
spec/javascripts/components/cookie-banner-spec.js
spec/javascripts/govuk_publishing_components/lib/cookie-settings-spec.js
spec/javascripts/govuk_publishing_components/single-consent-functions-spec.js

Disable the single cookie consent code. This disables the code and prevents it being included in the public facing page weight, but leaves it the gem repo for now if we want to reinstate it.
- removes the inclusion of the single consent functions (which pulls in the single consent API code) from dependencies, preventing the single consent code from operating at all
- also disables a number of tests reliant on this code
Pausing the work.
None.
Trello card: https://trello.com/c/dmlTAzKB/140-implement-single-consent-api

Disable the single consent cookie API code

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Disable the single consent cookie API code ([PR #3916](https://github.com/alphagov/govuk_publishing_components/pull/3916))

Version 37.8.0

---

docs/analytics-ga4/analytics.md
docs/analytics-ga4/consent.md
docs/analytics-ga4/developer-guide.md

Add a developer guide for GA4. Also separate the consent stuff out into its own page (so we can link to it more easily from the implementation record).
There's some developer confusion around making changes to code containing tracking, this aims to improve understanding.
None.

Add GA4 developer guide

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Remove "Popular" links from super navigation header ([PR #3918](https://github.com/alphagov/govuk_publishing_components/pull/3918))

Version 37.8.1

---

CHANGELOG.md
app/assets/javascripts/govuk_publishing_components/analytics-ga4.js
app/assets/javascripts/govuk_publishing_components/analytics-ga4/ga4-focus-loss-tracker.js
docs/analytics-ga4/ga4-all-trackers.md
docs/analytics-ga4/ga4-focus-loss-tracker.md
spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-focus-loss-tracker.spec.js

- Adds a new tracker called the `ga4-focus-loss-tracker`
- Have tested it with a couple elements in `static` and seems to be working as intended
- So that we can track what users are searching for on a client side DOM filter, without analytics spam that would occur if we tracked each `keypress`.
- https://trello.com/c/EXuAg9qR/801-add-tracking-filter-search-input
None.

Add a new GA4 'focus loss' tracker

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_option_select.html.erb

This PR removes `role='group'` and `aria-labelledby` from the parent `div` of the [option select component](https://github.com/alphagov/govuk_publishing_components/blob/main/app/views/govuk_publishing_components/components/_option_select.html.erb). This was causing issues with screen readers because the [checkboxes component](https://github.com/alphagov/govuk_publishing_components/blob/main/app/views/govuk_publishing_components/components/_checkboxes.html.erb), which is what [this component ultimately renders](https://github.com/alphagov/govuk_publishing_components/blob/a2aba9d0222e67171c53cc3ff425c0990861d319/app/views/govuk_publishing_components/components/_option_select.html.erb#L63), contains a `fieldset` element with the same text as the parent `div`'s `aria-labelledby` attribute. …

Fix accessibility issue in option select component

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Add a new GA4 'focus loss' tracker ([PR #3920](https://github.com/alphagov/govuk_publishing_components/pull/3920))
* Fix accessibility issue in option select component ([PR #3926](https://github.com/alphagov/govuk_publishing_components/pull/3926))

Version 37.9.0

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_document_list.html.erb
app/views/govuk_publishing_components/components/docs/document_list.yml

- Use component wrapper in document list component
- I promised I would in the PR that added GA4 tracking to the component
Document list yml examples will now have the uses component wrapper text

Use component wrapper in document list component

---

CHANGELOG.md
app/assets/javascripts/govuk_publishing_components/analytics-ga4/ga4-specialist-link-tracker.js
app/views/govuk_publishing_components/components/_button.html.erb
app/views/govuk_publishing_components/components/docs/button.yml
docs/analytics-ga4/ga4-specialist-link-tracker.md
lib/govuk_publishing_components/presenters/button_helper.rb
spec/components/button_spec.rb
spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-specialist-link-tracker.spec.js

Modifies the button component and the specialist link tracker to allow for a `data-ga4-link` attribute to be read, containing an alternative `type` for the GA4 data.
This includes a change to the button component, where 'Start now' buttons automatically include this attribute (which can also be removed using a `disable_ga4` option if required). And a change to the specialist link tracker, to check for the presence of a `data-ga4-link` attribute and read it if found.
This could probably be made more generic to allow more attributes than just `type` to be overridden, but this is the current requirement.
Tracking of 'Start now' buttons (on pages like https://www.gov.uk/log-in-register-hmrc-online-services) is done automatically by the specialist link tracker, as an external link. We want to …

Track 'Start now' buttons with a specific GA4 type

---

CHANGELOG.md
spec/features/contextual_navigation_spec.rb

Minor update to contextual breadcrumb tests to better represent live behaviour
To improve our confidence when we retire specialist topics in future work.

Update breadcrumb tests

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_govspeak.html.erb
app/views/govuk_publishing_components/components/_notice.html.erb
app/views/govuk_publishing_components/components/docs/govspeak.yml
spec/components/govspeak_spec.rb

- Remove the `callout` tracking from the `govspeak` component (again)
- We have deemed this too fiddly to keep in
- https://trello.com/c/P20AYeRP/810-remove-callout-link-tracking
None.

Remove GA4 callout tracking from the govspeak component

---

docs/component_conventions.md

I was going through the docs on [component conventions](https://github.com/alphagov/govuk_publishing_components/blob/main/docs/component_conventions.md) and noticed the JavaScript test file conventions needed updating. I've changed:
- The suggested test file location from `spec/components` to `spec/javascripts/components`
- The suggested test file name from `my_comp_spec.rb` to `my-comp-spec.js`
Docs needed a minor update.
N/A

Update JavaScript test file convention docs

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_notice.html.erb
app/views/govuk_publishing_components/components/_warning_text.html.erb
app/views/govuk_publishing_components/components/docs/notice.yml
app/views/govuk_publishing_components/components/docs/warning_text.yml
spec/components/notice_spec.rb
spec/components/warning_text_spec.rb
spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-specialist-link-tracker.spec.js

- Removes the `callout` tracking from the non-govspeak components that had the `callout` tracking on them
- I thought we were only removing the `callout` tracking from `govspeak` as that was causing the issues, but after asking the PAs this tracking is being removed entirely instead
- https://trello.com/c/P20AYeRP/810-remove-callout-link-tracking
Removes the examples with GA4 tracking disabled from the yml files

Remove GA4 callout tracking from notice & warning text components

---

CHANGELOG.md
app/assets/javascripts/govuk_publishing_components/analytics-ga4/ga4-page-views.js
spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-page-views.spec.js

Adds a new parameter to the GA4 page view, `discovery_engine_attribution_token`. This is a unique token generated by each search result, used for debugging purposes in search. Additional work will be done in `finder-frontend` to add this token as a meta tag so this code can read it - on all non-search pages this attribute will be undefined in the page view.
None.

Add discovery_engine_attribution_token to GA4 pageview

---

CHANGELOG.md
app/assets/javascripts/govuk_publishing_components/components/layout-super-navigation-header.js
spec/javascripts/components/layout-super-navigation-header-spec.js

These changes restores a test that was temporarily removed and refactors both that and the component it relates to. 
(Trello ticket: [Refactor and improve recent change to layout-super-navigation-header component](https://trello.com/c/zhgxoNEK/2485-refactor-and-improve-recent-change-to-layout-super-navigation-header-component))
When we made the changes in [PR#3918](https://github.com/alphagov/govuk_publishing_components/pull/3918) (Remove "Popular" links from super navigation header) we lost a recently added accessibility improvement, specifically to close the search menu when a keyboard user tabs out of that element. This was because this addition relied on the presence of links that were removed in the previous PR. We decided at the time to go ahead with that change and return to this …

Restores test and refactors component and test for layout-super-navigation-header

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Add discovery_engine_attribution_token to GA4 pageview ([PR #3951](https://github.com/alphagov/govuk_publishing_components/pull/3951))
* Remove support for specialist topics from contextual navigation ie breadcrumbs ([#3927](https://github.com/alphagov/govuk_publishing_components/pull/3927))
* Improve test coverage of contextual breadcrumb logic ([PR #3944](https://github.com/alphagov/govuk_publishing_components/pull/3944) and [PR #3945](https://github.com/alphagov/govuk_publishing_components/pull/3945))
* Remove GA4 callout tracking from the govspeak component ([PR #3946](https://github.com/alphagov/govuk_publishing_components/pull/3946))
* Remove GA4 callout tracking from notice & warning text components ([PR #3947](https://github.com/alphagov/govuk_publishing_components/pull/3947))
* …

Version 37.10.0

---

app/models/govuk_publishing_components/component_docs.rb
spec/components/all_components_spec.rb

There's no need for us to call `YAML.unsafe_load_file` when parsing the documentation sources.
Fixes https://github.com/alphagov/govuk_publishing_components/security/code-scanning/7.
No visual changes or changes to functionality.

Fix unnecessary use of YAML.unsafe_load.

---

CHANGELOG.md
app/views/govuk_publishing_components/components/docs/contextual_footer.yml
app/views/govuk_publishing_components/components/docs/related_navigation.yml
lib/govuk_publishing_components/presenters/related_navigation_helper.rb
spec/components/contextual_footer_spec.rb
spec/components/related_navigation_spec.rb
spec/lib/govuk_publishing_components/presenters/related_navigation_helper_spec.rb

Remove specialist topics from the contextual footer
Specialist topics have been retired
[Trello](https://trello.com/c/lUE1xqoF/2423-remove-specialist-topic-code-from-govukpublishingcomponents-m-l)
None

Remove support for specialist topics from footer

---

README.md

The 'Run the test suite' instructions didn't work without a couple of build steps which weren't mentioned anywhere in the README. Add them to the example so that it works for new contributors.
Also remove some confusing information about GOV.UK Docker and generally tidy up the README to bring it in line with GDS tech writing style.
No changes to the gem itself apart from the README.

docs: Fix test instructions and generally spruce up the README.

---

lib/govuk_publishing_components/presenters/intervention_helper.rb
spec/lib/govuk_publishing_components/components/intervention_helper_spec.rb

`InterventionHelper::security_attr` was erroneously classifying some external URLs as same-site, including:
- URLs with domains starting with `gov.uk` or `www.gov.uk`, such as `https://gov.uk.example.com/`
- protocol-relative URLs like `//external.example.com/`
Fixes https://github.com/alphagov/govuk_publishing_components/security/code-scanning/9.
No visual change and should be no functional change in normal use.

Fix incomplete regex for detecting external links.

---

lib/govuk_publishing_components/presenters/component_wrapper_helper.rb
spec/lib/govuk_publishing_components/components/component_wrapper_helper_spec.rb

Ruby regexes are — bizarrely — multiline by default, so `ComponentWrapperHelper::check_id_is_valid` would have erroneously accepted an ID string that contained newlines.
Fixes https://github.com/alphagov/govuk_publishing_components/security/code-scanning/8.
No visual changes. Should also be no functional change for normal usage.

Fix anchoring in ID validation regex.

---

app/views/govuk_publishing_components/components/_layout_super_navigation_header.html.erb
spec/components/layout_super_navigation_header_spec.rb

Update the layout header to add `index_section` and `index_section_count` of `3` to the GA4 search form tracking data, to make it in line with other elements in these drop down menus
None.
Trello card: https://trello.com/c/PXOGIDpO/806-add-indexsection-and-indexsection-count-values-to-header-menu-bar-search

Add GA4 indexes to header search form

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* **BREAKING:** Remove show password component ([PR #3973](https://github.com/alphagov/govuk_publishing_components/pull/3973))
* Complete the removal of specialist topic code from the gem ([PR #3955](https://github.com/alphagov/govuk_publishing_components/pull/3955))
* Remove support for specialist topics from contextual footer ([PR #3950](https://github.com/alphagov/govuk_publishing_components/pull/3950))
* Update HMRC organisation logos ([PR #3962](https://github.com/alphagov/govuk_publishing_components/pull/3962))

Version 38.0.0

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Explicitly require ostruct ([PR #3976](https://github.com/alphagov/govuk_publishing_components/pull/3976))

Version 38.0.1

---

CHANGELOG.md
app/views/govuk_publishing_components/components/layout_header/_navigation_items.html.erb
spec/components/layout_header_spec.rb

Add the `hidden` attribute to the mobile menu button in the layout_header component
In preparation for upgrading to version 5 of govuk-frontend.
Adding the `hidden` attribute to the mobile menu button was a recommend change in the release of 4.3 of govuk-frontend - https://github.com/alphagov/govuk-frontend/releases/tag/v4.3.0
In version 5 of govuk-frontend, the `hidden` attribute is required to ensure that the menu button remains hidden when JavaScript is disabled:
- https://github.com/alphagov/govuk-frontend/pull/3596
- https://github.com/alphagov/govuk-frontend/blob/main/CHANGELOG.md
[Trello card](https://trello.com/c/6LsKqHIO/2231-prepare-govukpublishingcomponents-to-run-v51-of-govuk-frontend-l)

Add the hidden attribute to mobile menu button

---

CHANGELOG.md
app/views/govuk_publishing_components/components/feedback/_problem_form.html.erb
app/views/govuk_publishing_components/components/feedback/_survey_signup_form.html.erb
app/views/govuk_publishing_components/components/feedback/_yes_no_banner.html.erb
spec/components/feedback_spec.rb

- Adds `tool_name` to the GA4 feedback component tracking
- Adds tests to the component - for context this tracking was added early on in the GA4 project, so I don't think we had our spec test process set up at that time.
- https://trello.com/c/fLwaDGY3/793-feedback-form-tool-name
None.

Add tool_name to GA4 feedback component tracking

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_layout_for_admin.html.erb
app/views/govuk_publishing_components/components/_layout_for_public.html.erb
app/views/layouts/govuk_publishing_components/application.html.erb

Update the <script> snippet in view templates
For govuk-frontend v5, there now needs to be additional class added to the `body` tag to indicate that the components are supported.
This class is `govuk-frontend-supported` and is added if the browser supports JS of type `module` (which is the new browser target for govuk-frontend).
The script tag is directly taken from the documentation, see "Update the `<script>` snippet at the top of your `<body>` tag" in the [release notes for govuk-frontend 5.0.0](https://github.com/alphagov/govuk-frontend/releases/tag/v5.0.0)
We can safely move to the new snippet in advance of upgrading to V5 of govuk-frontend, this will also give us a bit more flexibility in how we release the changes in our frontend rendering apps and `static`.
For example, if we …

Update script snippet in view templates

---

CHANGELOG.md
lib/govuk_publishing_components/presenters/attachment_helper.rb
spec/lib/govuk_publishing_components/presenters/attachment_spec.rb

Fix rendering of unnumbered papers so that "Unnumbered..." is displayed
The "false" check in the unnumbered command and act papers was failing because the component is passed an empty string rather than nil for the number, which does not evaluate to false:
e.g.
```bash
a = false
!a
=> true
b = nil
!b
=> true
c = ""
!c
=> false
```
Therefore the check was returning `nil` rather than the "Unnumbered..." text.

Fix rendering of unnumbered papers

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Fix rendering of unnumbered papers ([PR #3988](https://github.com/alphagov/govuk_publishing_components/pull/3988))
* Add PDF specific icon to attachment component ([PR #3985](https://github.com/alphagov/govuk_publishing_components/pull/3985))
* Add the hidden attribute to mobile menu button ([PR #3975](https://github.com/alphagov/govuk_publishing_components/pull/3975))
* Add tool_name to GA4 feedback component tracking ([PR #3984](https://github.com/alphagov/govuk_publishing_components/pull/3984))
* Update script snippet in view templates ([PR #3986](https://github.com/alphagov/govuk_publishing_components/pull/3986))
* Font changes ahead of apps being made compatible with govuk-frontend v5 ([PR #3981](https://github.com/alphagov/govuk_publishing_components/pull/3981))

Version 38.1.0

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_layout_for_admin.html.erb
app/views/govuk_publishing_components/components/docs/layout_for_admin.yml
spec/components/layout_for_admin_spec.rb

Allow custom JS and CSS filenames to be passed to the layout_for_admin component.
We're adding an admin interface to our application and want to use retain application.js & application.scss for the public interface.
This will allow us to pass admin.js and admin.scss in as args so we can retain only loading the required components for each so the page load time is fast.
N/A
It was a bit awkward to test this as passing it a filename that doesn't exist causes exceptions. Using any_instance_of is a bit of a smell, but it's probs okay(ish) here to avoid additional complexity.
https://trello.com/c/r6uafy2D/1354-basic-admin-area

Update layout_for_admin component to take custom asset filenames 

---

app/assets/javascripts/govuk_publishing_components/vendor/lux/lux-measurer.js

Resolves https://github.com/alphagov/govuk_publishing_components/security/code-scanning/6.
This source file appears to be forked from some closed upstream. I couldn't find the upstream source, but it looks like this isn't the first change we've made to it so I'm guessing it's reasonable to make this fix here.
(slightly off-topic: I also couldn't find any licence info about this source file, so that may or may not be a pre-existing problem there.)
No visual or functional changes.

Fix minor format string vuln in log message.

---

CHANGELOG.md
app/assets/javascripts/govuk_publishing_components/analytics-ga4/ga4-core.js
spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-core.spec.js

- On the following pages, GA4 is throwing a 413 HTTP error, as we're sending too much data:
- https://www.gov.uk/world/organisations
- https://www.gov.uk/government/groups
- https://www.gov.uk/government/organisations/hm-revenue-customs/contact
- This is because the ecommerce arrays we were sending were too large (20,000 - 40,000+ bytes)
- I've done some investigation and it looks like GTM errors if a request exceeds 16,000 bytes (16KB)
- I've also discovered that each push to the dataLayer also seems to push the Pageview data with it as well. Therefore, when sending the ecommerce array we must leave some room for the pageview data as well in the request.
- Therefore I've limited the eCommerce arrays to 15,000 UTF-16 code units, which should give about 1384 bytes of room for the pageview …

Limit GA4 view_item_list arrays to 15,000 UTF-16 code units

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_layout_for_public.html.erb
app/views/govuk_publishing_components/components/docs/layout_for_public.yml
spec/components/layout_for_public_spec.rb

This PR modifies the `layout_for_public` template to accept a custom header and a custom layout. This is to accommodate a custom layout for GOV.UK Chat but still bring in all the other HTML that `layout_for_public` provides.
We've opted for generic variable names e.g. `custom_header` and `custom_layout` in case another product has this need in future.
To achieve the custom layout of GOV.UK Chat - [Trello card](https://trello.com/c/PFfhPhjK/1350-fix-ui-layout)
None.

Add custom_header and a custom_layout options

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Limit GA4 view_item_list arrays to 15,000 UTF-16 code units ([PR #3994](https://github.com/alphagov/govuk_publishing_components/pull/3994))
* Add custom_header and a custom_layout options ([PR #4004](https://github.com/alphagov/govuk_publishing_components/pull/4004))
* Update LUX to 314 ([PR #4007](https://github.com/alphagov/govuk_publishing_components/pull/4007))
* Add No. 10 logo to organisation logo component ([PR #4008](https://github.com/alphagov/govuk_publishing_components/pull/4008))

Version 38.2.0

---

CHANGELOG.md
Gemfile.lock
govuk_publishing_components.gemspec
spec/dummy/config/application.rb
spec/dummy/config/environments/production.rb

Use Terser instead of Uglifier to compile JavaScript.
govuk-frontend v5 now targets browsers that support ES6. This means that the UMD modules used in govuk_publishing_components from govuk-frontend use features of ES6 and so it means that Uglifier can't be used anymore because it only supports ES5.
[Trello card](https://trello.com/c/lnPFryyC/2562-prep-for-51-move-fe-applications-from-uglifier-to-terser-l)
Overall the minified JS has increased slightly, by 1KB in the example below, however the overall GZIP size has decreased by 2KB.
| minifier | file | minified JS | minified JS (gzip) |
| --- | --- | --- | --- |
| uglifer | component_guide/application.js | 611KB | 162KB |
| terser | component_guide/application.js | 612KB | 160KB |
The component-guide still works as expected in the gem, …

Use Terser instead of Uglifier

---

CHANGELOG.md
app/views/govuk_publishing_components/components/metadata/_sentence.html.erb
spec/components/metadata_spec.rb

Removes the Oxford comma from the metadata component. The output changes from:
`item1, item2, and item3`
to
`item1, item2 and item3`
This also adds the word `and` into some parts of this component where it was previously missing, see screenshots below, specifically the `Industry` line.
Done as part of the work around this zendesk ticket: https://govuk.zendesk.com/agent/tickets/5820104
Before:
After:

Remove Oxford comma from metadata component

---

CHANGELOG.md
app/assets/javascripts/govuk_publishing_components/components/feedback.js

Prevent errors if input field is missing from the feedback form, by adding a null check. 
This is currently causing smokey to [fail](https://argo.eks.integration.govuk.digital/applications/cluster-services/smokey?node=%2FPod%2Fapps%2Fsmokey-28595090-rh8qb&tab=logs&orphaned=false&resource=). There will be work in this area around cleaning up the feedback, but this is just to quickly fix smokey.
Due to recent changes that removed the email address from the survey form, there is no input element available to focus on when the feedback form loads.

Prevent error if input field is missing

---

CHANGELOG.md
app/assets/javascripts/govuk_publishing_components/components/feedback.js
app/views/govuk_publishing_components/components/feedback/_survey_signup_form.html.erb
spec/components/feedback_spec.rb
spec/javascripts/components/feedback-spec.js

- Reintroduces adding the current page path to the smart survey `c=` query string parameter
- By default, the query string parameter is `c=no-js`
- It uses the same PII that was removed in #4017 
- Makes the survey link open in a new tab. I added `(opens in a new tab)` in the link text, as I'm 95% sure this is good practice for accessibility but can remove it if there's disagreement.
- The page path functionality was unintentionally removed in #4017
- The survey link should open in a new tab
- https://trello.com/c/rvDFQeEc/127-correctly-pass-page-path-to-govuk-intents-survey
None.

Reintroduce feedback survey path and new tab functionality

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Reintroduce feedback survey path and new tab functionality ([PR #4024](https://github.com/alphagov/govuk_publishing_components/pull/4024))

Version 38.3.2

---

CHANGELOG.md
app/assets/javascripts/govuk_publishing_components/modules.js
spec/javascripts/govuk_publishing_components/modules.spec.js

- Update the start function in `module.js` to support how JS modules are initialisted in govuk-frontend v5 as initialisation now happens automatically
- see "Remove calls to component init methods from your JavaScript" in the release notes of [GOV.UK Frontend v5.0.0](https://github.com/alphagov/govuk-frontend/releases/tag/v5.0.0)
- Add tests to `modules.spec.js` to check modules are initialised as expected when the `init` method is not on the modules prototype
[Trello card](https://trello.com/c/Vm74rv2e/938-prep-for-51-update-modulejs-in-govuk-publishing-components-to-support-multiple-initialisation-approaches-m)
These changes are required to support v5 of govuk-frontend, by making these changes in advance of the release of v5 of govuk-frontend we can help avoid any potentially breaking …

Update `module.js` ready for v5 of govuk-frontend

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Update module.js ready for v5 of govuk-frontend ([PR #3992](https://github.com/alphagov/govuk_publishing_components/pull/3992))

Version 38.4.0

---

CHANGELOG.md
config/locales/cy.yml

The devolved nations component didn't include a Welsh translation for the text 'Applies to Wales'. When a page containing the component was rendered in Welsh, the component would display the text in English ('Applies to Wales').
The translated text in this PR was provided to us by the DWP Welsh Unit.
The component should include the Welsh translation.
[Trello ticket](https://trello.com/c/4mr2fnsq/2578-welsh-translation-needed-on-hmrc-corporate-report-page-m)

Add missing Welsh translation to the devolved nations component

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Add missing Welsh translation to the devolved nations component ([PR #4036](https://github.com/alphagov/govuk_publishing_components/pull/4036))

Version 38.4.1

---

CHANGELOG.md
app/models/govuk_publishing_components/component_docs.rb

Modify the call to `YAML.load_file` in the component guide code to include `Date` in the list of permitted classes.
Turns out that the component guide in `frontend` uses `Date`, and without this change completely fails to load (`Tried to load unspecified class: Date`). Looks like this is the only application where `Date` is needed in a component (I think it's related to the calendar component in `frontend`).
Have tested this change locally in a locally running `frontend` and it fixes the problem.
Thanks to @KludgeKML for the fix!
None.
Trello card: https://trello.com/c/N3eQJZlU/168-fix-application-component-tests

Allow Date in YAML.load_file

---

CHANGELOG.md
app/assets/javascripts/govuk_publishing_components/analytics-ga4/ga4-page-views.js
spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-page-views.spec.js

- Adds `global_bar` to GA4 page view tracking
- Uses the `data-ga4-global-bar` data attribute that was added onto the global bar when GA4 tracking was added to it last week
- https://trello.com/c/XtbvfDSo/826-global-bar-tracking
None.

Add global bar to GA4 page view tracking

---

.gitignore
CHANGELOG.md
app/views/govuk_publishing_components/components/_layout_for_public.html.erb
spec/components/layout_for_public_spec.rb

- When the global bar is present, add a `global-bar-present` class to the `<body>`
- This will allow us to conditionally style two pages in `collections` based on the presence of this class. A draft PR exists for this to demonstrate: https://github.com/alphagov/collections/pull/3644
-  This will prevent us from having to create temporary PRs such as https://github.com/alphagov/collections/pull/3637
- https://trello.com/c/T4tonmaz/166-global-bar-border-issues
None.

Add a class to the page body when our global bar is present

---

CHANGELOG.md
lib/govuk_publishing_components/presenters/button_helper.rb
spec/components/button_spec.rb

- `event_name: "navigation"` had not been added to some GA4 data for start buttons
- This PR adds that data to the start buttons
- https://trello.com/c/C6l6mC9B/830-fix-start-button-navigation-events-coming-through-with-eventname-undefined
none.

Add "event_name: navigation" to start button tracking

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Allow Date in YAML.load_file ([PR #4050](https://github.com/alphagov/govuk_publishing_components/pull/4050))
* Add global bar to GA4 page view tracking ([PR #4051](https://github.com/alphagov/govuk_publishing_components/pull/4051))
* Add a class to the page body when our global bar is present ([PR #4047](https://github.com/alphagov/govuk_publishing_components/pull/4047))
* Add "event_name: navigation" to start button tracking ([PR #4052](https://github.com/alphagov/govuk_publishing_components/pull/4052))

Version 38.4.2

---

CHANGELOG.md
app/assets/javascripts/govuk_publishing_components/components/option-select.js
app/assets/stylesheets/govuk_publishing_components/components/_checkboxes.scss
app/views/govuk_publishing_components/components/_checkboxes.html.erb
lib/govuk_publishing_components/presenters/checkboxes_helper.rb
spec/components/checkboxes_spec.rb
spec/javascripts/components/checkboxes-spec.js
spec/javascripts/components/option-select-spec.js

- switch from lists to using divs for checkbox wrappers (to align with Design System component)
- remove custom styling for 'or' divider and use Design System style
- remove unneeded style override for hint margin
- make checkbox hint a div, not a span
- remove other custom styles to set list styles as no longer using lists
Part of some prep work towards fixing a bug in the v5 upgrade. Also we should align more with the Design System if possible, as it saves code.
Shouldn't be any, although there is a minor spacing difference that occurs underneath one instance of the component, but this is acceptable.
Trello card: https://trello.com/c/DzMiicUF/74-checkboxes-unnecessarily-in-a-list

Align checkboxes component more toward Design System

---

CHANGELOG.md
app/assets/javascripts/govuk_publishing_components/components/accordion.js
spec/javascripts/components/accordion-spec.js

- Add guard to accordion component init method
- Add new test and update fixture
When the accordion component from govuk-frontend is initialised, the `govuk-accordion__show-all` class is added to the button element.
It is possible that the accordion component from govuk-frontend does not get initialised, but we have no checks in place to guard against this when initialising the accordion component from the gem.
Example error when using the accordion component with V5 govuk-frontend in Safari 10.1
This change checks if the accordion component from govuk-frontend has initialised before trying to initialise the accordion component from the publishing components gem.
A new test has been added to check it does not initialise, if the accordion from govuk-frontend has not initialised. …

Add guard to accordion component init method

---

CHANGELOG.md
app/models/govuk_publishing_components/component_wrapper_helper_options.rb
docs/component-wrapper-helper.md
lib/govuk_publishing_components/presenters/component_wrapper_helper.rb
spec/lib/govuk_publishing_components/components/component_wrapper_helper_spec.rb

- adds the ability to pass an open attribute to the component wrapper helper
- needed for the details component, where open can be passed as true to have the details component expanded by default
Originally done as part of https://github.com/alphagov/govuk_publishing_components/pull/4068 but that PR is huge enough without this additional change, so I'm separating them out.
None.
Trello card: https://trello.com/c/rNPqwDIr/188-remove-ua-code-from-components-gem

Add open attribute to component wrapper

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Add open attribute to component wrapper ([PR #4074](https://github.com/alphagov/govuk_publishing_components/pull/4074))
* Add guard to accordion component init method ([PR #4069](https://github.com/alphagov/govuk_publishing_components/pull/4069))
* Prevent screen readers from announcing document list child/parts items dashes ([PR #4066](https://github.com/alphagov/govuk_publishing_components/pull/4066))
* Align checkboxes component more toward Design System ([PR #4061](https://github.com/alphagov/govuk_publishing_components/pull/4061))
* Add govuk-frontend checking to the component auditing ([PR #4058](https://github.com/alphagov/govuk_publishing_components/pull/4058))

Version 39.1.0

---

CHANGELOG.md
app/assets/javascripts/govuk_publishing_components/components/cookie-banner.js
app/assets/javascripts/govuk_publishing_components/load-analytics.js
spec/javascripts/components/cookie-banner-spec.js

- UA is going to be switched off at some point on July 1st
- we're concerned that requesting anything from or sending any data to UA might cause some kind of error or timeout, and we'd rather be safe than sorry
- this change disables our UA code without removing it or causing any tests to fail
- have tested this through a local app running a local static both running this code, and no problems occur (most importantly GA4 still functions)
The `initAnalytics` script has been left intact, but not called. It seems to be called [from a few other places](https://github.com/search?q=org%3Aalphagov+analyticsInit&type=code&p=1), the only one that looks current is DGU.
None.
Trello card: https://trello.com/c/3p2DpogG/199-disable-universal-analytics

Disable Universal Analytics

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_contents_list.html.erb
app/views/govuk_publishing_components/components/docs/contents_list.yml
lib/govuk_publishing_components/presenters/contents_list_helper.rb
spec/components/contents_list_spec.rb
spec/lib/govuk_publishing_components/components/contents_list_helper_spec.rb

- the contents list component does clever stuff when you pass the `format_numbers` option, where it identifies numbers at the start of the link text, splits the string into two, and wraps the number and text in separate spans so that the spacing between them can be controlled with CSS (otherwise 1. is misaligned with 10.)
- in some circumstances the content arriving at the component has a non-breaking space instead of an actual space, i.e. `1.&nbsp;Text of link`, which the component doesn't recognise and fails to split and wrap with spans for nice formatting, e.g. https://www.gov.uk/government/publications/financial-sanctions-guidance-for-russia/financial-sanctions-guidance-for-russia
- this change allows for this situation and converts the non-breaking space into a regular space prior to …

Fix missing number formatting in contents list component

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Update to LUX 4.0.20 ([PR #4089](https://github.com/alphagov/govuk_publishing_components/pull/4089))
* Fix missing number formatting in contents list component ([PR #4084](https://github.com/alphagov/govuk_publishing_components/pull/4084))

Version 39.2.1

---

app/controllers/govuk_publishing_components/audit_controller.rb
app/views/govuk_publishing_components/audit/_applications.html.erb

Adds some more applications that use `govuk_publishing_components` to the component auditing tools.
The app consistency sheet was recently updated and there were a number of applications using the gem on there that weren't in here.
Only that I put the number of applications in at the top.

Add more applications to component audit

---

README.md

- Fix the status icon used in README.md
- Updated the approach to use GitHub instead: https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/adding-a-workflow-status-badge
- The status and new link for the icon will be for Continuous integration on the main branch
- The request to badgen.net to generate the status icon in the readme file is currently returning a 404 error
- Consistent with the approach used in govuk-frontend - https://github.com/alphagov/govuk-frontend
- Allow others to quickly view the status
If badgen.net is preferred, it is possible to fix the 404 using the code below:
```md
[![status](https://badgen.net/github/checks/alphagov/govuk_publishing_components/main?label=status)](https://github.com/alphagov/govuk_publishing_components/actions?query=branch …
```

Fix status icon in README.md

---

CHANGELOG.md
app/assets/javascripts/govuk_publishing_components/lib/govspeak/magna-charta.js

- when a chart is generated, the label for each bar is positioned according to the relative size of the text and the length of the bar: if the bar is longer, the text is 'indented' inside the bar, if shorter, the text is 'outdented' outside of the bar
- this effect can produce varying results depending on the overall scale of the numbers involved: if a bar is of length 6 and the longest bar is 10, the text will likely be indented, but if the longest bar is 600, the bar of length 6 will appear much narrower and the text will probably be outdented
- it was reported that in some circumstances the text was being indented when it should have been outdented, resulting in text that appeared cropped (white text overlapping onto a white background)
- this seems to be fixable by slightly increasing …

Adjust govspeak chart label positioning

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Adjust govspeak chart label positioning ([PR #4094](https://github.com/alphagov/govuk_publishing_components/pull/4094))

Version 39.2.2

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_google_tag_manager_script.html.erb

Only set gtm_cookies_win=x for preview in GTM script
The GTA doesn’t work as expected for DGU.
It appears that gtm_cookies_win=x allows GTM Preview to change the environment of a page, which means that they win over gtm_auth and gtm_preview parameters.
Setting gtm_cookies_win=x  let the GTM editor decide which environment they want to use, regardless of what was in the tracking snippet. 
This makes it identically to the behaviour in ga4-core.js. The commit message suggest that it can slow down GTM:
https://github.com/alphagov/govuk_publishing_components/blob/eb66a18f86/app/assets/javascripts/govuk_publishing_components/analytics-ga4/ga4-core.js#L25
https://govuk.zendesk.com/agent/tickets/5626599
n/a

Only set gtm_cookies_win=x for preview in GTM script

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/helpers/_brand-colours.scss

The new MHCLG has a new brand colour which will need adding into Whitehall. It's a fairly urgent change hence why we are adding it to publishing components, and not just waiting for the update to govuk-frontend

Add brand colour for MHCLG

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* LUX version 4.0.23 ([PR #4102](https://github.com/alphagov/govuk_publishing_components/pull/4102))

Version 39.2.5

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

Release notes to highlight the breaking change in what is likely to be version 40 of govuk-publishing-components.
* **BREAKING:** Upgrade to govuk frontend 5.1 ([PR #4041](https://github.com/alphagov/govuk_publishing_components/pull/4041))
This release upgrades govuk-frontend from version 4.8.0 to version 5.1.0.
The PR description for [Upgrade to govuk frontend 5.1](https://github.com/alphagov/govuk_publishing_components/pull/4041) contains info on what has changed in the publishing components gem to upgrade to v5.1.0 of govuk-frontend.
For further details on all changes in govuk-frontend, please refer to the release notes:
[Release GOV.UK Frontend v5.0.0 · alphagov/govuk-frontend](https://github.com/alphagov/govuk-frontend/releases/tag/v5.0.0)
[Release GOV.UK Frontend v5.1.0 · …

Version 40.0.0

---

.github/workflows/ci.yml
CHANGELOG.md

Adds Brakeman to the CI jobs to appease the angry CI robot, as outlined here: https://docs.publishing.service.gov.uk/manual/brakeman.html
As per the above linked docs: 
[Brakeman](https://github.com/presidentbeef/brakeman) is a static analysis tool which checks Rails applications for security vulnerabilities. It is effectively a type of linter, similar to [rubocop](https://github.com/rubocop-hq/rubocop). It is configured as a reusable workflow and should be included as a job in the CI pipeline of all GOV.UK Ruby repositories.

Add Brakeman to CI jobs

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_search.html.erb
app/views/govuk_publishing_components/components/docs/search.yml
spec/components/search_spec.rb

- Add `disable_corrections` parameter to `search` component that can be set to true to disable both `autocorrect` and `autocapitalize` attributes on the search input field [^1]
As part of our work on site search, we've discovered a pain point where mobile browsers' autocorrection features mess up user queries, especially when it comes to domain specific terminology. For example, searches for "HMRC" are frequently autocorrected to "Hercules", or searches for "SORN" to "sworn".
As our new site search engine used by Search API v2 is much better at implicitly handling misspelled user queries than the previous search engine, we want to allow disabling all mobile browser attempts at second guessing what the user has typed as the end result tends to be worse with two separate spellchecks turning …

Allow disabling `search` input spelling corrections

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_layout_super_navigation_header.html.erb
app/views/govuk_publishing_components/components/layout_header/_search.html.erb

This applies the `disable_corrections` setting from #4112 to the `search` components used in the `layout_super_navigation_header` and `layout_header` components.
We expect this to improve the quality of search results for users on mobile as their browsers will no longer excessively autocorrect, and in case of genuine misspellings, the site search engine can cope with that well anyway.
None.

Disable browser corrections for header search field

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Allow disabling `search` component input spelling correction ([PR #4112](https://github.com/alphagov/govuk_publishing_components/pull/4112))
* Disable `search` component input spelling correction in `layout_super_navigation_header` and `layout_header` components ([PR #4115](https://github.com/alphagov/govuk_publishing_components/pull/4115))
* Add Brakeman to CI jobs ([PR #4108](https://github.com/alphagov/govuk_publishing_components/pull/4108))

Release version 40.1.0

---

.github/workflows/ci.yml
CHANGELOG.md
govuk_publishing_components.gemspec

This will unblock: https://github.com/alphagov/govuk_publishing_components/pull/4123
Ruby 3.1 is a few months from end-of-life and in security fixes only territory. This update is somewhat forced upon us by the sass-embedded dependency which has dropped support for Ruby 3.1 in some circumstances [1] which causes the dartsass-rails gem to fail [2].
The consequences of this change should be pretty much negligible as there are not GOV.UK apps on Ruby 3.1 anymore and the .ruby-version for this repo was already (yet mistakenly) updated to Ruby 3.2.
[1]: https://github.com/sass-contrib/sass-embedded-host-ruby/blob/19323666b359bf3d58b562af09fdc75440453608/sass-embedded.gemspec#L39-L43
[2]: https://github.com/alphagov/govuk_publishing_components/pull/4123

Drop support for Ruby 3.1

---

app/assets/stylesheets/govuk_publishing_components/components/_accordion.scss

This PR is a cherry pick of the first commit from https://github.com/alphagov/govuk_publishing_components/pull/4106 because the other commits are going to have to wait while we finish updating apps to dart-sass, but we might as well get this one out in the meantime.
Specific change:
- `govuk-typography-responsive` was renamed to `govuk-font-size` in version 5.1.0 of `govuk-frontend`
- changing this to remove a compilation warning
- release notes here: https://github.com/alphagov/govuk-frontend/releases/tag/v5.1.0
None.
Trello card: https://trello.com/c/gW2NW1sB/142-fix-sass-compilation-warnings

Replace deprecated govuk-frontend mixin

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/_cards.scss
app/views/govuk_publishing_components/components/_cards.html.erb
app/views/govuk_publishing_components/components/docs/cards.yml
spec/components/cards_spec.rb

- Update the cards component to use a one column by default
- The one column layout variation was the winner of the AB test when used on the browse pages, so we will be using the variation on both `collections` and `frontend` in the future. The only place that would still use the three column layout is the account settings page in `signon`
- Add a new `columns` option which is used to set the number for columns to use
- Removed the `two_column_layout` option
- Update tests and docs for the new `columns` option
- Use new `columns` option
- Add test for three column variation of the card component
- Update spacing for the card component to match the new design
- Use grid `column-gap` instead of margin
- Align the chevron icon vertically, the card component content now has margin-right set …

Update cards component design and use one column by default

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Upgrade to LUX v4.0.25 ([PR #4129](https://github.com/alphagov/govuk_publishing_components/pull/4129))
* Resolve DartSass mixed declaration deprecations ([PR #4125](https://github.com/alphagov/govuk_publishing_components/pull/4125))
* Drop support for Ruby 3.1 ([PR #4124](https://github.com/alphagov/govuk_publishing_components/pull/4124))
* Update cards component design and use one column by default ([PR #4118](https://github.com/alphagov/govuk_publishing_components/pull/4118))

Version 41.1.0

---

docs/component_conventions.md

Correct the path and filename detail for test files in the component conventions doc.
It was wrong!
None.

Fix incorrect details in the component conventions doc

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/_cards.scss
app/views/govuk_publishing_components/components/_cards.html.erb
app/views/govuk_publishing_components/components/docs/cards.yml
spec/components/cards_spec.rb

When using a single column layout, the top border will now only be visible when a heading is used.
Updated `gem-c-cards__heading` to use a responsive margin-bottom.
To match the intended design of the card component when using a single column layout with a heading.
[Trello card](https://trello.com/c/F3N53ubq/1189-update-border-top-for-card-component)
| --- | --- |
| <img width="974" alt="cards-desktop-before" src="https://github.com/user-attachments/assets/68e9fcb6-974d-4610-bfa9-c25d2fea720e"> | <img width="969" alt="cards-desktop-after" src="https://github.com/user-attachments/assets/74d74297-37c0-41c5-abe1-6e4fb4baee65"> |
| --- | --- |
| <img width="364" alt="card-mobile-heading-before" src="https://github.com/user-attachments/assets/41da4e23-5704- …

Update card component styles

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/_table.scss
app/views/govuk_publishing_components/components/_table.html.erb

This PR adds/improves print styles for tables:
- sortable tables now print the same as other tables
- the filter element is hidden for print
People still print a lot of pages from [GOV.UK](http://gov.uk/). And recent discussions have highlighted potential problems, or at least a perception that HTML pages when printed aren't as good as PDFs. We're trying to move away from/discourage the use of PDFs on [GOV.UK](http://gov.uk/), so improving the print experience could help.

New print styles for the `table` component

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/_tabs.scss

This PR adds/improves print styles for tabs:
- display all tabs when printed, don't replicate the shown/hidden screen states
- linearise the tabs into a single column
People still print a lot of pages from [GOV.UK](http://gov.uk/). And recent discussions have highlighted potential problems, or at least a perception that HTML pages when printed aren't as good as PDFs. We're trying to move away from/discourage the use of PDFs on [GOV.UK](http://gov.uk/), so improving the print experience could help.

New print styles for the `tabs` component

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/_layout-footer.scss
app/assets/stylesheets/govuk_publishing_components/components/_layout-header.scss
app/views/govuk_publishing_components/components/_layout_header.html.erb
app/views/govuk_publishing_components/components/layout_header/_navigation_items.html.erb
app/views/govuk_publishing_components/components/layout_header/_search.html.erb

New and updated print styles for the `layout-header` and `layout-footer` components.
For the header, we hide some of the elements that would be redundant in print, and force text and border colours to black. The background is also unset to ensure it doesn't print, otherwise it would print with black text on black.
People still print a lot of pages from [GOV.UK](http://gov.uk/). And recent discussions have highlighted potential problems, or at least a perception that HTML pages when printed aren't as good as PDFs. We're trying to move away from/discourage the use of PDFs on [GOV.UK](http://gov.uk/), …

New print styles for layout components

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/_step-by-step-nav-header.scss
app/assets/stylesheets/govuk_publishing_components/components/_step-by-step-nav-related.scss

This PR adds/improves print styles for the following components:
[step-by-step-nav-header](https://components.publishing.service.gov.uk/component-guide/step_by_step_nav_header)
[step-by-step-nav-related](https://components.publishing.service.gov.uk/component-guide/step_by_step_nav_related)
People still print a lot of pages from [GOV.UK](http://gov.uk/). And recent discussions have highlighted potential problems, or at least a perception that HTML pages when printed aren't as good as PDFs. We're trying to move away from/discourage the use of PDFs on [GOV.UK](http://gov.uk/), so improving the print …

New print styles for step-by-step components

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/govspeak/_attachment.scss
app/assets/stylesheets/govuk_publishing_components/components/govspeak/_button.scss
app/assets/stylesheets/govuk_publishing_components/components/govspeak/_highlight-answer.scss
app/assets/stylesheets/govuk_publishing_components/components/govspeak/_media-player.scss

This PR adds/improves print styles for the following govspeak components. Follow the links for examples:
[`attachment`](https://components.publishing.service.gov.uk/component-guide/govspeak#attachment)
[`button`](https://components.publishing.service.gov.uk/component-guide/govspeak#buttons)
[`highlight_answer`](https://components.publishing.service.gov.uk/component-guide/govspeak#highlight_answer)
[`media_player`](https://components.publishing.service.gov.uk/component-guide/govspeak#with_youtube_embed)
People still print a lot of pages from [GOV.UK](http://gov.uk/). And recent discussions have …

New print styles for govspeak components

---

CHANGELOG.md
app/assets/stylesheets/component_guide/application.scss
app/assets/stylesheets/govuk_publishing_components/components/_inverse-header.scss
app/assets/stylesheets/govuk_publishing_components/components/_layout-super-navigation-header.scss
app/views/govuk_publishing_components/components/_layout_super_navigation_header.html.erb

A number of our components can be displayed inverted: white text on a dark background. These components should be set back to non-inverted for print: black text on a white background. 
For components that imply layout separation with their background colours, those aspects should be communicated with borders or other solutions that work better in print.
[Trello card](https://trello.com/c/tYpEnJfI/257-check-print-styles-for-inverse-components)
People still print a lot of pages from [GOV.UK](http://gov.uk/). And recent discussions have highlighted potential problems, or at least a perception that HTML pages when printed aren't as good as PDFs. We're trying to move away from/discourage …

Fix the print styles for inverse components

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Add icon for external in attachment component ([PR #4150](https://github.com/alphagov/govuk_publishing_components/pull/4150))
* New print styles for the table component ([PR #4139](https://github.com/alphagov/govuk_publishing_components/pull/4139))
* New print styles for the tabs component ([PR #4140](https://github.com/alphagov/govuk_publishing_components/pull/4140))
* New print styles for layout components ([PR #4137](https://github.com/alphagov/govuk_publishing_components/pull/4137))
* New print styles for step-by-step components ([PR #4138](https://github.com/alphagov/govuk_publishing_components/pull/4138))
* New print styles for govspeak components ([PR #4136](https://github.com/alphagov/govuk_publishing_components/pull/4136))
* Fix the print styles for inverse components ([PR …

Version 41.1.2

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* **BREAKING:** Drop libsass support ([PR #4106](https://github.com/alphagov/govuk_publishing_components/pull/4106))
* **BREAKING:** Drop support for legacy browsers ([PR #4111](https://github.com/alphagov/govuk_publishing_components/pull/4111))

Release Version 42.0.0

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/_organisation-logo.scss

When printing a page containing organisation logos, we want to ensure that any images are always printed. Without the images, each logo is printed as text only with an empty space for the logo and looks quite strange. 
In addition, browsers don't print background images by default, and will only print them if a hidden option is selected from the printer dialogue. This PR forces the browser to always print the logo images regardless of settings.
This is part of the work to improve our print styles more generally. [Trello](https://trello.com/c/K58GNTxY/268-fix-organisational-logo-components-to-print-correctly)
Printing the logo images helps users to establish recognition for each organisation.

Ensure that organisation logos always print

---

CHANGELOG.md
app/views/govuk_publishing_components/components/docs/contents_list.yml
lib/govuk_publishing_components/presenters/contents_list_helper.rb
spec/components/contents_list_spec.rb

- Fix an issue with ampersands not rendering as expected in the browser by calling the `strip` method on the text earlier in the `clean_string` method in `contents_list_helper.rb`
- Updated and refactored tests to check the ampersand is rendered as expected as well as other special characters
- Included special characters in the content-list document list as Percy will capture any visual changes should the tests be updated or removed in the future
The content-list component is not rendering the special characters as expected, an example of this can be seen on https://www.gov.uk/guidance/research-and-development-rd-tax-relief-the-merged-scheme-and-enhanced-rd-intensive-support
[Trello card](https://trello.com/c/FwnkPDJR/29-contents-list-component-not-rendering-ampersands-as-expected)
| …

Fix issue with using special characters in content-list

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/_all_components.scss
app/assets/stylesheets/govuk_publishing_components/component_support.scss
app/assets/stylesheets/govuk_publishing_components/components/_breadcrumbs.scss
app/assets/stylesheets/govuk_publishing_components/components/_govspeak-html-publication.scss
app/assets/stylesheets/govuk_publishing_components/components/_layout-for-admin.scss
app/assets/stylesheets/govuk_publishing_components/components/_search.scss
app/assets/stylesheets/govuk_publishing_components/components/helpers/_brand-colours.scss
app/assets/stylesheets/govuk_publishing_components/components/helpers/_govuk-frontend-settings.scss
app/views/govuk_publishing_components/components/_breadcrumbs.html.erb
app/views/govuk_publishing_components/components/docs/organisation_logo.yml
package.json
yarn.lock

- Upgrade to `govuk-frontend` v5.5.0
- See their CHANGELOG for changes: https://github.com/alphagov/govuk-frontend/blob/main/CHANGELOG.md
- Incorporates this PR's commit in order to fix the search styles: https://github.com/alphagov/govuk_publishing_components/pull/3991 
- This `finder-frontend` PR also relies on this upgrade https://github.com/alphagov/finder-frontend/pull/3334
- I have tested this PR in `finder-frontend` with the two PRs above included, and the search on mobile looked correct
Trello card: https://trello.com/c/l2yxZZ9k/274-upgrade-to-govuk-frontend-54
Feel free to critique as I eyeballed the alignment

Upgrade to govuk-frontend v5.5.0

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* **BREAKING:** Upgrade to govuk-frontend v5.5.0 ([PR #4115](https://github.com/alphagov/govuk_publishing_components/pull/4160))

Version 43.0.0

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/_layout-super-navigation-header.scss

The print styles on the layout-super-navigation-header are incorrect and need to be updated:
- Background should always print transparent
- Foreground should always print black
- No top border
- Bottom border should match new changes in cross service header
- Left/right margins are not required for print due to background removal
[Trello](https://trello.com/c/4Lk0dUxa/292-fix-print-issues-on-layout-super-navigation-header)
- The top bar has an extra top border and redundant left/right spacing when printed, it also doesn’t match the changes made to the cross service header (coming in #4073)
- The background color bug was recently introduced in the previous print styles work and needs fixing: it prevents the inverted background from printing correctly.

Fix print issues on layout-super-navigation-header

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/_cards.scss

Fixed the card component styling by removing the spacing from the first list item in one-column lists that do not have a heading. For lists with a border and a heading, the padding and spacing are retained to ensure consistency. 
Related [Trello Card](https://trello.com/c/mXZOHPnZ/2773-update-homepage-services-and-information-section-to-use-the-card-component-from-the-gem-s-m) --> _when replacing the card component to the customised card component on the GOV.UK homepage, this is where I noticed there was a visual difference in the spacing._
The previous padding settings for the first list item without a heading created extra spacing that wasn't necessarily required. Therefore, by reducing this it provided a more consistent look across different layouts, which helps improve the visual …

Fix card component padding based on heading

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Fix card component padding based on heading ([PR #4169](https://github.com/alphagov/govuk_publishing_components/pull/4169))
* Fix print issues on layout-super-navigation-header ([PR #4165](https://github.com/alphagov/govuk_publishing_components/pull/4165))
* Remove unused org colour classes ([PR #4173](https://github.com/alphagov/govuk_publishing_components/pull/4173))

Version 43.0.1

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/_layout-header.scss
app/views/govuk_publishing_components/components/layout_header/_navigation_items.html.erb
app/views/govuk_publishing_components/components/layout_header/_search.html.erb

Fix the search toggle in layout header
On mobile and tablet screen sizes clicking on the search icon in the layout header did not reveal the hidden search form element, `gem-c-layout-header__search-form`.
The reason for this is that as of [V3.0.0 of govuk-frontend](https://github.com/alphagov/govuk-frontend/blob/main/CHANGELOG.md#update-the-html-for-navigation-in-the-header), classes have a `govuk-` prefix. The HTML for the search template has been updated to reflect this, as well as using the `aria-controls` attribute to target the element to be toggled.
The toggle functionality, makes use of the `hidden` attribute to show/hide the target element, `display: none` has been removed from `.gem-c-layout-header__search-form` to ensure that the search form visibility can be toggled and can be …

Fix the search toggle in layout header

---

CHANGELOG.md
app/assets/stylesheets/component_guide/application.scss
app/assets/stylesheets/govuk_publishing_components/components/_cross-service-header.scss
app/assets/stylesheets/govuk_publishing_components/components/_intervention.scss
app/assets/stylesheets/govuk_publishing_components/components/_inverse-header.scss
app/assets/stylesheets/govuk_publishing_components/components/_layout-header.scss
app/assets/stylesheets/govuk_publishing_components/components/_layout-super-navigation-header.scss
app/assets/stylesheets/govuk_publishing_components/components/_metadata.scss
app/assets/stylesheets/govuk_publishing_components/components/_phase-banner.scss
app/assets/stylesheets/govuk_publishing_components/components/_step-by-step-nav-header.scss
app/assets/stylesheets/govuk_publishing_components/components/_step-by-step-nav-related.scss
app/assets/stylesheets/govuk_publishing_components/components/_success-alert.scss
app/assets/stylesheets/govuk_publishing_components/components/_table.scss
app/assets/stylesheets/govuk_publishing_components/components/_warning-text.scss
app/assets/stylesheets/govuk_publishing_components/components/govspeak/_button.scss
app/assets/stylesheets/govuk_publishing_components/components/govspeak/_highlight-answer.scss

In improving print styles in gem components (#4073), we used `background-color: unset` to revert backgrounds to transparent for print. This would ensure that inverse components would always print non-inverted, saving ink.
After discussion we decided to change this to use `background: none` instead, because:
- the use of `unset` is uncommon and not well understood, and its behaviour can be unpredictable
- `background: none` is a more common accepted approach and easier to understand. We've taken into account that resetting all background properties can be considered a [CSS anti-pattern](https://csswizardry.com/2016/12/css-shorthand-syntax-considered-an-anti-pattern/), however we're confident in this case that it won't have any adverse effects because we're not using any other background …

Replace 'unset' property in printed background colours

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/_layout-footer.scss
app/views/govuk_publishing_components/components/_layout_footer.html.erb

This improves the print styles for the `layout-footer` component as part of the work to improve print styles for page layouts. [Trello](https://trello.com/c/tcXZsXup/193-review-and-fix-page-level-print-styles). 
- Extra borders and padding are removed
- internal elements now run flush to their left/right edges
Note that for consistency [all variants of the layout-footer](https://components.publishing.service.gov.uk/component-guide/layout_footer) now render identically when printed .
Although we made improvements to the `layout-footer` as part of #4073, we did not look at how the component might interact with other components on the page. This PR further improves the component in context of page types.

Improve print styles for layout-footer component

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/_inverse-header.scss

This improves the print styles for the `inverse-header` component as part of the work to improve print styles for page layouts:
- Padding is removed for better alignment with printed page content
[Trello](https://trello.com/c/tcXZsXup/193-review-and-fix-page-level-print-styles)
Although we made improvements to this component as part of #4073, we did not look at how the component might interact with other components on the page. This PR further improves the component in context of page types.

Improve print styles for inverse-header component

---

app/assets/stylesheets/govuk_publishing_components/govuk_frontend_support.scss

Adds the `govuk-suppressed-warnings` flag to suppress warnings about the [organisation colour changes](https://frontend.design-system.service.gov.uk/sass-api-reference/#govuk-suppressed-warnings).
We were getting a ton of messages in the Sass compilation like this:
```
10:33:48 css.1  | [2024-09-02 10:33:48] Compiled spec/dummy/app/assets/stylesheets/views/_app-view.scss to spec/dummy/app/assets/builds/views/_app-view.css.
10:33:48 css.1  | WARNING: `department-for-business-energy-industrial-strategy` was dissolved in 2023. It was replaced by `department-for-business-trade`, `department-for-energy-security-net-zero` and `department-science-innovation-technology`. To silence this warning, update $govuk-suppressed-warnings with key: "organisation-colours"
10:33:48 css.1  | …
```

Fix govuk-frontend Sass compilation warning

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Fix the search toggle in layout header ([PR #4163](https://github.com/alphagov/govuk_publishing_components/pull/4163))
* Replace 'unset' property in printed background colours ([PR #4184](https://github.com/alphagov/govuk_publishing_components/pull/4184))
* Improve print styles for layout-footer component ([PR #4178](https://github.com/alphagov/govuk_publishing_components/pull/4178))
* Improve print styles for inverse-header component ([PR #4179](https://github.com/alphagov/govuk_publishing_components/pull/4179))

Version 43.0.2

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/_all_components.scss
app/assets/stylesheets/govuk_publishing_components/components/_summary-card.scss
app/views/govuk_publishing_components/components/_summary_card.html.erb
app/views/govuk_publishing_components/components/docs/summary_card.yml
spec/components/summary_card_spec.rb
spec/lib/govuk_publishing_components/app_helpers/asset_helper_spec.rb

Adds a new component - Summary Card - to the Gem. 
These changes 
- copy the component code from the Whitehall codebase ([here](https://github.com/alphagov/whitehall/blob/main/app/views/components/_summary_card.html.erb), [here](https://github.com/alphagov/whitehall/blob/main/app/assets/stylesheets/components/_summary-card.scss) and [here](https://github.com/alphagov/whitehall/blob/main/app/views/components/docs/summary_card.yml)) to this one
- update some class names in line with the Publishing Components standards
- refactor the ERB file to use Rails tags
- adds a test for the new component
This component already exists on Whitehall ([Summary Card](http://whitehall-admin.dev.gov.uk/component-guide/summary_card)) but is required on other apps. To facilitate this we need to move the …

Add Summary Card component to Gem

---

spec/lib/govuk_publishing_components/app_helpers/asset_helper_spec.rb

Updates the test to count number of components after the addition of the new Summary Card component

Updates `asset_helper_spec` for new component

---

app/assets/javascripts/govuk_publishing_components/lib/govspeak/youtube-link-enhancement.js

[URL API] `searchParams` works [pretty much everywhere](https://caniuse.com/?search=searchparams) since around 2017, which includes [all the user agents we support](https://www.gov.uk/service-manual/technology/designing-for-different-browsers-and-devices). It also considerably simplifies the code and makes the intent much clearer.
(We have to avoid static `canParse()` though, because Samsung Internet is weird.)
Resolves https://github.com/alphagov/govuk_publishing_components/security/code-scanning/1.
[URL API]: https://developer.mozilla.org/en-US/docs/Web/API/URL
No visual or functional change intended.

Make YoutubeLinkEnhancement URL parsing more robust.

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_chat_entry.html.erb
app/views/govuk_publishing_components/components/docs/chat_entry.yml
spec/components/chat_entry_spec.rb

This PR adds GA4 tracking to the chat entry component.
Requested by the PA on the AI team.

Add ga4 tracking to chat entry component

---

app/views/govuk_publishing_components/components/layout_header/_navigation_items.html.erb

This PR removes the `aria-label` from the menu button in the [navigation items component](https://github.com/alphagov/govuk_publishing_components/blob/main/app/views/govuk_publishing_components/components/layout_header/_navigation_items.html.erb) in the layout header.
This what identified as a level A WCAG failure during a DAC audit of GOV.UK Chat because the [aria-label (“Show or hide Top Level Navigation”)](https://github.com/alphagov/govuk_publishing_components/blob/60ab84d7936da9a8f9ce05bff5c8fcd8f5f734bf/app/views/govuk_publishing_components/components/layout_header/_navigation_items.html.erb#L10) did not match the visual text of the [menu button (“Menu”)](https://github.com/alphagov/govuk_publishing_components/blob/60ab84d7936da9a8f9ce05bff5c8fcd8f5f734bf/app/views/govuk_publishing_c …

Remove aria-label on menu button

---

app/assets/stylesheets/govuk_publishing_components/components/govspeak/_highlight-answer.scss

Fixes a layout issue with the govspeak 'highlight answer' feature.
- had a negative left/right margin, which was causing it to overflow out of its containing element slightly
- see example: https://www.gov.uk/corporation-tax-rates
Spotted recently by @kubabartwicki 
Before | After

Fix govspeak highlight answer margin

---

app/assets/stylesheets/govuk_publishing_components/components/govspeak/_advisory.scss

The [advisory](https://components.publishing.service.gov.uk/component-guide/govspeak#advisory) govspeak element had a negative left/right margin, that was causing it to escape from its parent.
Noticed by @maxgds as part of https://github.com/alphagov/govuk_publishing_components/pull/4206
Before | After
----- | -----

Fix govspeak advisory margin

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/_table.scss
app/assets/stylesheets/govuk_publishing_components/components/govspeak/_tables.scss

When printing tables, hide the URLs generated by the global print styles in govuk-frontend. [Trello](https://trello.com/c/zuT5SiYJ/324-hide-printed-urls-when-printing-tables)
When links are printed, the print styles in govuk-frontend append the URL of the link so that they are more useful to the reader. But these links can break the layout of tables and prevent all columns from printing.

Hide printed URLs when printing tables

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_hint.html.erb
app/views/govuk_publishing_components/components/docs/hint.yml
spec/components/hint_spec.rb

This adds the component wrapper to the hint component in order to provide additional options to a hint.
The primary motivation of this was that we want to dynamically change the value of a hint in GOV.UK Chat and thus want to set a .js-class to act as a selector [1] (private repo) and instead are using a custom id to work around it.
Looking at other components it seemed that using the component wrapper was a more conventional approach than just utilising the shared helper to add only classes.
[1]: https://github.com/alphagov/govuk-chat/pull/660#discussion_r1750067107
None

Use component wrapper in hint component

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/_action-link.scss
app/views/govuk_publishing_components/components/_action_link.html.erb

Re-enable the printing of the action-link component and apply consistent improvements to the printed URLs (reducing size, placing on their own line, forcing all colours to black) [Trello](https://trello.com/c/cVgisHQw/312-fix-action-link-component-print-styles)
As part of the improvements to print styles, we prevented the `action-link` component from printing at all as generally speaking printing links isn’t very helpful as they’re mainly interactive elements. However we noticed this caused problems printing certain pages, particularly the homepage Popular section which now displays nothing when printed as the entire block is composed of `action-link` components.
Before | After

Fix action link component print styles

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Use component wrapper in hint component ([PR #4214](https://github.com/alphagov/govuk_publishing_components/pull/4214))
* Hide printed URLs when printing tables ([PR #4209](https://github.com/alphagov/govuk_publishing_components/pull/4209))
* Fix action link component print styles ([PR #4213](https://github.com/alphagov/govuk_publishing_components/pull/4213))
* Improve the password input component custom text feature ([PR #4211](https://github.com/alphagov/govuk_publishing_components/pull/4211))
* Make links to parts in `document_list` component respect `remove_underline` setting ([PR #4210](https://github.com/alphagov/govuk_publishing_components/pull/4210))

Version 43.1.1

---

CHANGELOG.md
app/assets/javascripts/govuk_publishing_components/lib/cookie-functions.js
app/assets/javascripts/govuk_publishing_components/lib/cookie-settings.js
spec/javascripts/govuk_publishing_components/lib/cookie-functions-spec.js

- We were using `Date.now()` as our way of instantly expiring cookies, but based on testing in the browser, the cookie would expire based on the UTC timezone rather than the user's timezone.  I believe `Date.now()` was grabbing the user's timezone which may have been causing issues if their timezone was ahead of UTC.
- It looks like the cookie would persist for an period of time depending on how far their timezone is ahead of UTC. An assumption of the worst case scenario is that their timezone could be 14 hours ahead of UTC, so certain cookies may have persisted for that long.
- I believe this is what is causing some weird cookie behaviour on [this GA4 card](https://trello.com/c/5TNoJ3rt/842-issue-with-absent-client-ids-related-to-postal-voteservicegovuk-redirect-links):  - I think on …

Fix cookie expiration date potentially relying on user's timezone

---

CHANGELOG.md
app/assets/javascripts/govuk_publishing_components/analytics-ga4/ga4-page-views.js
app/assets/javascripts/govuk_publishing_components/analytics-ga4/pii-remover.js
docs/analytics-ga4/pii-remover.md
lib/govuk_publishing_components/presenters/meta_tags.rb
spec/components/meta_tags_spec.rb
spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-page-views.spec.js
spec/javascripts/govuk_publishing_components/analytics-ga4/pii-remover.spec.js
spec/javascripts/helpers/SpecHelper.js

Updates GOV.UK page metatags used by GA4 to make them more consistent. See individual commits for details.
Must be deployed with https://github.com/alphagov/slimmer/pull/341
This is some final tidying up post GA4 launch, to make things more consistent and clear.
None.
Trello card: https://trello.com/c/lIVmnFpY/336-page-view-enhancement-some-meta-tags-start-with-analytics

Update metatags for GA4

---

app/assets/stylesheets/govuk_publishing_components/components/_search.scss
app/views/govuk_publishing_components/components/_search.html.erb

Fix the label styles in the search component. The label was appearing broken in some pages in the component guide, although still appearing correctly in the actual homepage.
- label stylesheet was only being included if wrap_label_in_a_heading was true
- custom gem label class for white on dark colour wasn't overriding standard govuk-frontend label class colour
Appearance of the component varied considerably within the component guide. I think this is because on some pages the label styles were already being included by other instances of the component on the page.
Fixes the following inconsistencies, so all pages now appear correctly (first one was correct already).
Component guide page | Appearance
----------------------- | ----------
Main page `/search` | ![Screenshot 2024-09-16 at 11 …

Fix inconsistent search label appearance

---

CHANGELOG.md
app/assets/javascripts/govuk_publishing_components/analytics-ga4/ga4-core.js

- Remove 100 character limit on search results
- This was from when GA4 limited text to 100 characters, and we didn't have functionality in the code to limit the GA4 payload by bits.
- Trello card: https://trello.com/b/rm8pjAAk/ga4-gtm-implementation-ga4-team-user-experience-govuk
None.

Remove 100 character limit on search results

---

CHANGELOG.md
app/assets/javascripts/govuk_publishing_components/analytics-ga4/ga4-core.js
app/assets/javascripts/govuk_publishing_components/analytics-ga4/ga4-page-views.js
spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-core.spec.js
spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-page-views.spec.js

- Removes date redaction from the `standardiseSearchTerm` function, - this function ensures the search term tracks the same across multiple parameters, so dates should no longer be redacted wherever we grab a search term.
- Also removes date redaction from the `location`, `query_string`, and `search_term` values in the PageView tracker.
- The PAs have requested this, as some of the filters use dates, and I believe there was a discussion at some point about dates being useful for search tracking. https://trello.com/c/RYSxnFZ1/841-remove-date-redaction-from-search-terms.
None.

Stop redacting dates in GA4 tracking on GOVUK search pages

---

CHANGELOG.md
app/assets/javascripts/govuk_publishing_components/analytics-ga4/pii-remover.js
spec/javascripts/govuk_publishing_components/analytics-ga4/pii-remover.spec.js

- Adds redaction to GWF+9 digits, and GB+12 digits. These are application IDs for visas.
- Some users mistakenly use GOV.UK to search for the status of their application (they were being redacted by our date redaction fortunately, so this change is more for accuracy of what's being redacted)
- https://trello.com/c/pk45odvO/833-add-redaction-to-gwf-visa-and-gb-eori-numbers
None.

Add GA4 redaction to GWF and GB EORI numbers

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/component_support.scss
app/assets/stylesheets/govuk_publishing_components/lib/_print_support.scss

Provide a new helper class to "collapse" row/column layouts when printing. This class forces all floated columns in the associated row to print at full page width. [Trello](https://trello.com/c/MTJDEqDS/325-investigate-generic-print-styles-for-govuk-frontend-layout)
When printing various page types, the 2/3rds + 1/3rds column layout causes issues with cropped content and a generally poor printing experience because the full page isn't used. By selectively collapsing floated columns, we can avoid most of these issues and improve the printing experience by using the full width of the page.
| Before    | After |
| -------- | ------- |
| <img width="" alt="image" src="https://github.com/user-attachments/assets/94525704-5818-4f43-850f-3e34cda379ac">  | <img width="" alt="image" …

New class to collapse columns for print

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/_layout-super-navigation-header.scss

- Add a blue background to the Menu / Search buttons, so they don't blend into the grey background for users that increase their text scale / have a screen resolution that is >= 300px in width (mobile users)
- Fixes https://github.com/alphagov/govuk_publishing_components/issues/4208

Fix homepage super navigation buttons when text scale is increased

---

CHANGELOG.md
app/assets/javascripts/govuk_publishing_components/lib/cookie-functions.js

To remove 'govuk_not_first_visit' and 'govuk_browser_upgrade_dismissed' 
These are no longer being used and we don’t actually present a banner of this nature any more. We should remove references to it from the govuk_publishing_components gem
https://trello.com/c/lR7DOoLn/341-we-refer-to-cookies-that-are-no-longer-in-use
Ensure that references to it are removed from [Details about cookies on GOV.UK](https://www.gov.uk/help/cookie-details)

removed unused cookies in cookie category

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_password_input.html.erb
app/views/govuk_publishing_components/components/docs/password_input.yml
spec/components/password_input_spec.rb

Allow custom name attribute on password input
On Signon, we use Devise for authentication. We customise the login screen in order to use the GOV.UK Design System, but in order for everything to work seemlessly with Devise (without undue hacking), we use the default Devise input names of `user[email]` and `user[password]`. Other apps may well have a similar need given that Devise is a pretty standard library

Allow custom name attribute on password input

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/_table.scss

Fix sortable table header issue on mobile
The icon overlays the text when space is limited.

Fix sortable table header issue on mobile

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/_layout-super-navigation-header.scss
app/views/govuk_publishing_components/components/_layout_header.html.erb
app/views/govuk_publishing_components/components/docs/layout_header.yml
spec/components/layout_header_spec.rb

- Remove `search_left` variant of the layout header component
- Also fixes a SASS warning I introduced in a previous PR.
- Fixes https://github.com/alphagov/govuk_publishing_components/issues/4153
Removes the example in the docs.

Remove left search variant of layout header

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/_phase-banner.scss
app/views/govuk_publishing_components/components/docs/phase_banner.yml

Remove 'inverse' background style from phase banner
Components with an inverse option should not set a background colour as the inverse option is designed to work against a dark background, and we can't always know exactly what colour that background will be (it's usually GOV.UK dark blue, but it might be a dark green or something else in the future).
I've checked for instances where the banner is used with the inverse option [here](https://github.com/search?q=org%3Aalphagov+components%2Fcomponents%2Fphase_banner&type=Code). The only occurrence I found is in [Finder Frontend](https://github.com/alphagov/finder-frontend/blob/main/app/views/finders/_before_content.html.erb), which already applies a parent background style `app-before-content--inverse`, see [guidance and …

Remove 'inverse' background style from phase banner

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Remove left search variant of layout header ([PR #4239](https://github.com/alphagov/govuk_publishing_components/pull/4239))
* Remove 'inverse' background style from phase banner ([PR #4241](https://github.com/alphagov/govuk_publishing_components/pull/4241))
* Add experimental `search_with_autocomplete` component ([PR #4218](https://github.com/alphagov/govuk_publishing_components/pull/4218))

Release 43.4.0

---

CHANGELOG.md
govuk_publishing_components.gemspec

This was missing from the gemspec's file allowlist, causing it to not be included in the gem archive published to Rubygems.

Add `accessible-autocomplete` node_modules to gemspec

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Add accessible-autocomplete node_modules to gemspec ([PR #4246](https://github.com/alphagov/govuk_publishing_components/pull/4246))

Release 43.4.1

---

CHANGELOG.md
Gemfile.lock
govuk_publishing_components.gemspec

Ruby is dropping ostruct from standard library and will require it to be installed as a gem. When using an app with Ruby 3.3.5 there is a warning:
```
/root/.rbenv/versions/3.3.5/lib/ruby/3.3.0/bundled_gems.rb:75: warning: /root/.rbenv/versions/3.3.5/lib/ruby/3.3.0/ostruct.rb was loaded from the standard library, but will no longer be part of the default gems starting from Ruby 3.5.0.
You can add ostruct to your Gemfile or gemspec to silence this warning.
Also please contact the author of govuk_publishing_components-43.3.0 to request adding ostruct into its gemspec.
```

Add ostruct as an explicit dependency

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_radio.html.erb
app/views/govuk_publishing_components/components/docs/radio.yml
spec/components/radio_spec.rb

This adds a `visually_hidden_heading` option to the `radio` component complementing the already existing option of the same name on the `checkboxes` component.
This allows the heading/legend to be hidden for non-screenreader users, for example where the purpose of the radios is made visually obvious in another way.
We will use this on the new search filters UI to hide the heading on the sort options which is contained within a collapsible section that already has a heading of its own:

Allow visually hiding legend on `radio` component

---

CHANGELOG.md
app/views/govuk_publishing_components/components/docs/breadcrumbs.yml
app/views/govuk_publishing_components/components/docs/step_by_step_nav_header.yml

Update the accessibility criteria for the breadcrumbs and step by step navigation header components, stating they should be placed before the `<main>` element to avoid failing WCAG 2.2 success criterion 2.4.1 Bypass Blocks (Level A). This is similar to the guidance provided in the "How it works" section of the [breadcrumbs component in the Design System](https://design-system.service.gov.uk/components/breadcrumbs/#how-it-works).
[Trello card](https://trello.com/c/6aPsnjO2/2860-update-gem-docs-to-say-that-breadcrumbs-should-be-placed-outside-main-container-s?filter=label:Frontend%20devs)
We found a number of places where the breadcrumbs were incorrectly placed inside the main container, which failed [WCAG 2.2 success criterion 2.4.1 Bypass Blocks (Level …

Update accessibility criteria in component docs

---

CHANGELOG.md
app/views/govuk_publishing_components/components/docs/big_number.yml

- [In the docs for the big number component](https://components.publishing.service.gov.uk/component-guide/big_number#passing_extra_symbols), we were only showing the `400+` example when demonstrating that symbols can be passed.
- This specific example contains extra styling compared to other symbol types, as we need to align the `+` symbol in the middle of the number. [See context here](https://github.com/alphagov/govuk_publishing_components/commit/1dd5cd1c3784f54cb04e3fec8034b63c6aed3165)
- As the other symbol types like `90%` weren't being shown in the docs, devs were then using `Inspect Element` to change the `400+` example to test the other symbol types like `90%`.
- However as the `400+` example has special styles on it, this led to [an …

Show all big_number symbol types in our docs

---

CHANGELOG.md
app/views/govuk_publishing_components/components/docs/search.yml

Remove incorrect search component example
From MDN:
> Placing [heading elements](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Heading_Elements) within a <label> interferes with many kinds of assistive technology
The correct approach, from https://design-system.service.gov.uk/patterns/question-pages/#page-headings, was implemented in this PR https://github.com/alphagov/govuk_publishing_components/pull/2462.

Remove incorrect search component example

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_contextual_guidance.html.erb
app/views/govuk_publishing_components/components/docs/contextual_guidance.yml

- Adds the component wrapper to the `contextual_guidance` component
- https://trello.com/c/qH4NyWJw/364-add-component-wrapper-to-more-components#comment-66fe6e7c9757203502c5ea6d
None.

Add component wrapper to contextual guidance component

---

CHANGELOG.md
app/assets/javascripts/govuk_publishing_components/components/option-select.js
app/assets/stylesheets/govuk_publishing_components/components/_option-select.scss
app/views/govuk_publishing_components/components/_option_select.html.erb

Vertically centre align the toggle icons with the label in Option Selects. [Trello](https://trello.com/c/65zYsdtH/275-type-scale-finder-frontend-improve-spacing-and-alignment-in-search-filters-on-mobile)
The font size of this element increased with the typography changes deployed in a recent update to `govuk-frontend`. This means that the up/down icons no longer align vertically. This PR vertically centres the icons with the text for better vertical balance. A new container for the icon and button is also required so that the selected counter element can be styled independently.
This also supports the same change made in `finder-frontend` where search filter titles had the same tweak to icon positions. See the PR at https://github.com/alphagov/finder-frontend/pull/3334.
| Before    | …

Center text and icons vertically in the option select component

---

CHANGELOG.md
app/models/govuk_publishing_components/component_wrapper_helper_options.rb
app/views/govuk_publishing_components/components/_cookie_banner.html.erb
lib/govuk_publishing_components/presenters/component_wrapper_helper.rb
spec/lib/govuk_publishing_components/components/component_wrapper_helper_spec.rb

- Adds the component wrapper to the cookie banner
- The cookie banner contains a `hidden` attribute, but the component wrapper didn't support this, so I've added that
- I can't seem to get `hidden` to work when passed with an empty string. I'm not sure if it's rails or the browser, but it automatically converts it to `<div hidden="hidden">` - I don't think this is a massive issue, as `hidden="hidden"` is still valid. Therefore if you have any tips to make `<div hidden>` alone work feel free to comment.
None.

Add component wrapper to cookie banner

---

CHANGELOG.md
app/views/govuk_publishing_components/components/docs/attachment_link.yml

Update attachment link accessibility guidance
See https://www.w3.org/WAI/WCAG22/Understanding/target-size-minimum.html. The Attachment link component might fail 2.5.8 Target Size (Minimum) if not used in the correct way. The last two examples ([with target blank
](https://components.publishing.service.gov.uk/component-guide/attachment_link/with_target_blank) and [with data attributes](https://components.publishing.service.gov.uk/component-guide/attachment_link/with_data_attributes)) show the component used without a containing element such as a paragraph tag or a list item element and the target height is only 20px high (24px is required for the success criterion).
This should be highlighted in the guidance.
I explored a few other approaches here:
- enable the Axe `target-size` rule, …

Update attachment link accessibility guidance

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/_action-link.scss
app/assets/stylesheets/govuk_publishing_components/components/_cards.scss
app/assets/stylesheets/govuk_publishing_components/components/_contents-list.scss
app/assets/stylesheets/govuk_publishing_components/components/_devolved-nations.scss
app/assets/stylesheets/govuk_publishing_components/components/_document-list.scss
app/assets/stylesheets/govuk_publishing_components/components/_image-card.scss
app/assets/stylesheets/govuk_publishing_components/components/_inset-text.scss
app/assets/stylesheets/govuk_publishing_components/components/_intervention.scss
app/assets/stylesheets/govuk_publishing_components/components/_step-by-step-nav-header.scss
app/assets/stylesheets/govuk_publishing_components/components/_step-by-step-nav-related.scss
app/assets/stylesheets/govuk_publishing_components/lib/_print_support.scss
app/views/govuk_publishing_components/components/_action_link.html.erb
app/views/govuk_publishing_components/components/_cards.html.erb
app/views/govuk_publishing_components/components/_contents_list.html.erb
app/views/govuk_publishing_components/components/_devolved_nations.html.erb
app/views/govuk_publishing_components/components/_document_list.html.erb
app/views/govuk_publishing_components/components/_image_card.html.erb
app/views/govuk_publishing_components/components/_inset_text.html.erb
app/views/govuk_publishing_components/components/_intervention.html.erb
app/views/govuk_publishing_components/components/_step_by_step_nav_header.html.erb
app/views/govuk_publishing_components/components/_step_by_step_nav_related.html.erb

Two new helper classes for applying consistent formatting to printed links. These classes replace the same repeated CSS previously created as part of the print improvement work. [Trello](https://trello.com/c/7opRx4sU/336-add-a-global-link-print-style)
Most links inherit styles from `govuk-frontend`, including printing the contents of the `href`. This makes printed links more useful, but they can take up a lot of space on the page in the default font size and will print in blue by default. These helper classes sets the printed colour to black, reduce the font size, and improve the layout of the printed href.
Not applicable as the visual output is the same as before.

Global print link class

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_devolved_nations.html.erb
app/views/govuk_publishing_components/components/docs/devolved_nations.yml

- Adds the component wrapper to the `devolved_nations` component
- https://trello.com/c/qH4NyWJw/364-add-component-wrapper-to-more-components#comment-66fe6e7c9757203502c5ea6d
None.

Add component wrapper to devolved nations component

---

app/assets/javascripts/govuk_publishing_components/vendor/lux/lux-reporter.js

Upgrade our LUX Real User Monitoring script to the latest version, as per https://github.com/alphagov/govuk_publishing_components/blob/main/docs/real-user-metrics.md#updating
Currently can't do the last step locally (checking it against the debug tool) owing to problems with my local setup, so that still needs checking.
I'm actually a bit behind on this one, it's been out for more than a week. We need to keep up to date or it'll stop working.
None.

LUX 4.0.27

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/_document-list.scss
app/views/govuk_publishing_components/components/_document_list.html.erb
app/views/govuk_publishing_components/components/docs/document_list.yml
spec/components/document_list_spec.rb

The items in a document list currently have slightly more padding above the separator than below. This adds an option to have equal spacing on both sides.
For the new design for GOV.UK Search, we want the spacing above and below the separator to be equal.

Document list: Add option for equal item spacing

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* **BREAKING:** Remove Modernizr ([PR #4273](https://github.com/alphagov/govuk_publishing_components/pull/4273))
* Standardise inverse option for action link component ([PR #4288](https://github.com/alphagov/govuk_publishing_components/pull/4288))
* Update accessibility criteria in component docs ([PR #4242](https://github.com/alphagov/govuk_publishing_components/pull/4242))
* Show all big_number symbol types in our docs ([PR #4271](https://github.com/alphagov/govuk_publishing_components/pull/4271))
* Remove incorrect search component example ([PR #4253](https://github.com/alphagov/govuk_publishing_components/pull/4253))
* Add component wrapper to contextual guidance component ([PR #4277](https://github.com/alphagov/govuk_publishing_components/pull/4277))
* Center text and icons …

Release 44.0.0

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Upgrade to version 5.7.0 of govuk-frontend ([PR #4298](https://github.com/alphagov/govuk_publishing_components/pull/4298))

Release 44.2.0

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/_share-links.scss
app/views/govuk_publishing_components/components/_share_links.html.erb
app/views/govuk_publishing_components/components/docs/share_links.yml
spec/components/share_links_spec.rb

- Add variants required for square blue icon share links
- Reasoning: https://trello.com/c/LNOqGMgZ/49-build-social-media-links
- The existing component styles use `position: absolute` for the icons, which doesn't work nicely when we need them square. This is because the absolutely positioned icons don't affect the width/height of the DOM, so adding square background styles just ended up in overlapping, fiddly overflows, and made it difficult to align the text in the centre of the icons.
- Therefore, I've used `display: flex` along with `inline-block` to get the styles we want.
- ~~I added a `min-width` at a certain breakpoint to make the reflow look nicer, but this is specific to the page we're going to put this variation on. (i.e. because we know the social icons / share link text that …

Add variants required for square blue icon share links

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Add variants required for square blue icon share links ([PR #4292](https://github.com/alphagov/govuk_publishing_components/pull/4292))

Version 44.3.0

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/_organisation-logo.scss
app/views/govuk_publishing_components/components/_organisation_logo.html.erb
app/views/govuk_publishing_components/components/docs/organisation_logo.yml
spec/components/organisation_logo_spec.rb

Adds an inverse option for the organisation logo component.
This is currently WIP and limited to one organisation. Since organisations have different logos, rolling out a universal inverse option would require inverse versions of every logo.
Part of some requirements.

Add inverse option for organisation logo

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/_contents-list.scss
app/views/govuk_publishing_components/components/_contents_list.html.erb
app/views/govuk_publishing_components/components/docs/contents_list.yml
spec/components/contents_list_spec.rb

Two new options for the `contents-list` component:
- `alternative_line_style`
- `title`
These can be used to format the list as a navigation block on landing pages. [Trello](https://trello.com/c/l9yaSdmV/53-build-side-navigation)
Landing pages have a navigation element in a sidebar. This navigation element can use the `contents-list` component. However, there are additional requirements which require new options:
- the active state is shown with a vertical border and bold blue text.
- increased vertical spacing between lines
- the Contents title can be replaced by an alternative title.
| title    | alternative_line_style |
| -------- | ------- |
| <img width="335" alt="image" src="https://github.com/user-attachments/assets/1de278a7-7529-43a7-8ce2-2bed266fadd7">  | <img width="335" …

New options for contents-list component

---

CHANGELOG.md
govuk_publishing_components.gemspec

Adds the path to the `chartkick` JS explicitly into the gemspec.
Needed for the chart component. Installing in applications fails because the JS file can't be found.
None.

Add chartkick path to gemspec

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Add chartkick path to gemspec ([PR #4312](https://github.com/alphagov/govuk_publishing_components/pull/4312))

Version 44.4.1

---

app/views/govuk_publishing_components/components/_chart.html.erb

Fix incorrect markup in the chart component.
Has been causing a CI test failure.
None.

Fix missing trailing quotes in chart component markup

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Fix ecommerce tracking of searches without query ([PR #4317](https://github.com/alphagov/govuk_publishing_components/pull/4317))

Version 44.4.2

---

CHANGELOG.md
app/assets/javascripts/govuk_publishing_components/components/govspeak.js
app/assets/stylesheets/govuk_publishing_components/components/_govspeak-html-publication.scss
app/assets/stylesheets/govuk_publishing_components/components/_govspeak.scss
app/assets/stylesheets/govuk_publishing_components/components/govspeak/_attachment.scss
app/assets/stylesheets/govuk_publishing_components/components/govspeak/_tables.scss
app/assets/stylesheets/govuk_publishing_components/components/govspeak/_typography.scss
app/views/govuk_publishing_components/components/_govspeak.html.erb
app/views/govuk_publishing_components/components/docs/govspeak.yml
spec/components/govspeak_html_publication_spec.rb
spec/components/govspeak_spec.rb
spec/javascripts/components/govspeak-spec.js

Adds the `shared_helper` and `component wrapper helper` to the govspeak component.
Involves renaming a few classes to allow them to be passed to the component wrapper, specifically the disable youtube (adding a JS prefix) and direction-rtl (add a gem-c-govspeak prefix) otherwise the wrapper raises an error.
Mainly so we can pass a margin option to the component, but also because the component wrapper works well here.
Shouldn't be any visual changes, but the component guide has a few new options listed, so this will cause a Percy fail.
Trello card: https://trello.com/c/YAeRSLr4/91-blocks-need-more-spacing

Add shared helper and component wrapper helper to govspeak component

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/_chart.scss
app/views/govuk_publishing_components/components/_chart.html.erb
app/views/govuk_publishing_components/components/docs/chart.yml
spec/components/chart_spec.rb

Adds some options to the chart component:
- minimal, for when the graph is in a small space and should display minimal information and link to more information
- height, to set the height in situations like the above
I've started going down a bit of a rabbit hole with this one, so I've raised https://github.com/alphagov/govuk_publishing_components/issues/4322 as an issue to record my concerns rather than try to address them here and spiral the scope out of control.
Needed for a page where the graphs are going to be small and link to another page.
Minimal version:
Minimal version with a smaller height:
Trello card: https://trello.com/c/DFT05NWN/97-implement-small-graphs-on-main-landing-page

Add new chart component options

---

CHANGELOG.md
app/models/govuk_publishing_components/component_wrapper_helper_options.rb
app/views/govuk_publishing_components/components/_error_alert.html.erb
app/views/govuk_publishing_components/components/docs/error_alert.yml
lib/govuk_publishing_components/presenters/component_wrapper_helper.rb
spec/lib/govuk_publishing_components/components/component_wrapper_helper_spec.rb

- Adds the component wrapper to the error alert component
- The component contains a `tabindex` attribute, but the component wrapper didn't support this, so I've added support for `tabindex` in the component wrapper.
- https://trello.com/c/qH4NyWJw/364-add-component-wrapper-to-more-components
None.

Add component wrapper helper to error alert component

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/_share-links.scss
app/views/govuk_publishing_components/components/_share_links.html.erb
app/views/govuk_publishing_components/components/docs/share_links.yml
spec/components/share_links_spec.rb

- Stop using `columns: true` for our square icons as it doesn't give us the visual balance we want where we're using it.
- Therefore, use flexbox with a `min-width` for this variant instead. 
- The `min-width` is needed because alignment/stacking visual inconsistencies occur when the elements have varying widths. Therefore, if we ensure there is a minimum width for the elements, the alignment and flow when resizing is more visually pleasing. If you think of a component like our image cards, they stack and align nicely as they are all the same width, so we need some of that guarantee here, hence the `min-width`. It's also worth noting that `columns: true` was utilising a `min-width` for its balancing of links. I don't think we should be putting any max width type limitations though like …

Use flexbox for share links with square icons

---

app/views/govuk_publishing_components/components/docs/govspeak.yml
spec/components/govspeak_spec.rb

Adds a test and documentation for the recent margin option added to the govspeak component.
I forgot to add in https://github.com/alphagov/govuk_publishing_components/pull/4325
None.

Add documentation and test for govspeak margin

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Use flexbox for share links with square icons ([PR #4316](https://github.com/alphagov/govuk_publishing_components/pull/4316))

Version 44.6.0

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/_contents-list.scss
app/views/govuk_publishing_components/components/_contents_list.html.erb
app/views/govuk_publishing_components/components/docs/contents_list.yml
spec/components/contents_list_spec.rb

Adds the shared helper for margin bottom to the contents list component.
We want to use it somewhere and it needs a different bottom margin.
None.
Trello card: https://trello.com/c/t0DlqDkW

Contents list add margin_bottom option

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Contents list add margin_bottom option ([PR #4333](https://github.com/alphagov/govuk_publishing_components/pull/4333))

Version 44.7.0

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/_share-links.scss

- There's a hover underline visual issue when using the `flexbox` variant. 
- Looks like it was due to main label being a span (meaning it had `display: inline`).
- Switching to `inline-block` seems to have fixed it. This removed the default underline styles, so I reintroduced them via the CSS, which looks better anyway as there's now spacing between the line and the word.
- Not sure what's going on with the Percy visual change.

Fix incorrect underline styles on share links

---

CHANGELOG.md
app/assets/stylesheets/component_guide/application.scss

Some components do not set their default font, so they do not look right when presented in the component guide, as the component guide does not set the font either. This change fixes this problem by setting the default GDS Transport font for the components guide. By setting it, how the components look in the guide should better reflect how they look in pages, as pages also set the same default font.
This change is only related to component guides and how components look there.
This change was is a way to fix the issues described in this [Trello card](https://trello.com/c/PwSKwCN5/2949-the-government-frontend-component-guide-app-examples-dont-have-a-font-set)
Inverse header preview page:
In government-frontend's component guide:
Inverse header preview page:
In government-frontend's …

Set default font for component guide

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Fix incorrect underline styles on share links ([PR #4337](https://github.com/alphagov/govuk_publishing_components/pull/4337))
* Set default font for component guide ([PR #4330](https://github.com/alphagov/govuk_publishing_components/pull/4330))

Version 44.7.1

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/_chart.scss
app/views/govuk_publishing_components/components/_chart.html.erb
app/views/govuk_publishing_components/components/docs/chart.yml
spec/components/chart_spec.rb

Change the chart component. Specifically:
- remove the requirement for a link from the minimal mode
- adds an option to pad the text and elements around the graph
For a minimal chart we thought that it should link to a page with more data, but this has proved complicated in an actual page, and now I think it's better handled in an application rather than dictated by the component.
Padding is needed for when the chart is inside an element with a border, as these elements touch the outer edge.
No change to the minimal version, except that it no longer has a link.
Padded version shown below with the normal version for comparison (it's a bit subtle, look at the left edge).
Trello card: https://trello.com/c/VKrLuGvg

Adjust chart component options

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Adjust chart component options ([PR #4342](https://github.com/alphagov/govuk_publishing_components/pull/4342))
Needed to make https://github.com/alphagov/frontend/pull/4341 work.
Also fixes the CHANGELOG entry that I did wrong in https://github.com/alphagov/govuk_publishing_components/pull/4342

Version 44.8.0

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_layout_super_navigation_header.html.erb

- Point form at `/search/all` instead of `/search` to avoid most users going through an unnecessary 301 redirect
- Use Rails's tag helper for more concise form code (in particular data attributes)
Users currently get taken through an additional, unnecessary redirection when performing a search through the layout super nav's search form, as this points to the `/search` landing page instead of the actual site search page at `/search/all`. The former will just redirect to the latter if keywords are given:
While I was already here, using Rails's tag helper for the form tag means we have more concise and readable data attributes and don't have to manually convert to JSON.

Layout super nav header: Correct URL for search form

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_summary_card.html.erb
app/views/govuk_publishing_components/components/_summary_list.html.erb
app/views/govuk_publishing_components/components/docs/summary_card.yml
app/views/govuk_publishing_components/components/docs/summary_list.yml
spec/components/summary_card_spec.rb
spec/components/summary_list_spec.rb

This allows data attributes to be added to summary card and summary list rows
This will allow developers to add Javascript interactivity to individual rows via module initialisation.

Add data attributes to summary cards and lists

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_layout_super_navigation_header.html.erb

Sets an explicit field name (`keywords`) for the search input on the layout super navigation header, as this is coming through into Finder Frontend as the default name of `q`.
Finder Frontend implicitly converts this param so it's not actually causing problems for users, but it's causing issues with our analytics tracking.

Layout super nav header: Correct name for search input

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_chart.html.erb
app/views/govuk_publishing_components/components/docs/chart.yml
spec/components/chart_spec.rb

- In [a previous PR](https://github.com/alphagov/govuk_publishing_components/pull/4344), I added validation so that `chart_heading` is a required field.
- This was done for accessibility purposes, otherwise skip links and data tables didn't have proper labels. They used `chart_heading` to tell the user what chart the labels were related to.
- This worked in the gem, because all the examples in the gem had a `chart_heading`.
- However, in practice we veered away from the component examples, and were rendering charts without any `chart_heading` value. (The tasks page in our project.)
- Therefore, that tasks page is crashing on the latest version of the gem. Passing a `chart_heading` to this page would change the design. Therefore to fix this I have added an `hide_heading` variable that can …

Extend chart component to allow headings to be removed from the DOM

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Extend chart component to allow headings to be removed from the DOM ([PR #4362](https://github.com/alphagov/govuk_publishing_components/pull/4362))

Version 44.11.0

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/_share-links.scss
app/assets/stylesheets/govuk_publishing_components/components/helpers/_brand-colours.scss
app/views/govuk_publishing_components/components/_share_links.html.erb
app/views/govuk_publishing_components/components/docs/contents_list.yml
app/views/govuk_publishing_components/components/docs/document_list.yml
app/views/govuk_publishing_components/components/docs/image_card.yml
app/views/govuk_publishing_components/components/docs/share_links.yml
app/views/govuk_publishing_components/components/docs/subscription_links.yml
app/views/govuk_publishing_components/components/docs/translation_nav.yml
docs/component_branding.md
package.json
spec/components/share_links_spec.rb
yarn.lock

**Breaking change, as it stops certain colours working on components that are using the `brand` option.`**
- Removes generic `.brand__color` class, which was used to give organisations custom link colours from `govuk-frontend`. However we keep a namespaced `.brand__color` style for `prime-ministers-office-10-downing-street`, so that links will remain black on the no 10 page only. 
- Also removes the `brand` option from the `share_links` component, and replaces it with `black_icons` and `black_links`. These are needed because the default brand styles are now going to be a black icon with our standard blue links, but the No 10 page needs black links as well, hence needing both options. Only `collections` used the `brand` variant of this component, so this shouldn't break any other pages. …

Refactor organisation styles and upgrade to govuk-frontend v5.7.1

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

Breaking release, as it removes existing functionality from components (certain `brand` colours)
* **BREAKING** Refactor organisation styles and upgrade to govuk-frontend v5.7.1 ([PR #4321](https://github.com/alphagov/govuk_publishing_components/pull/4321))

Version 45.0.0

---

CHANGELOG.md
app/assets/javascripts/govuk_publishing_components/analytics-ga4/ga4-schemas.js
app/assets/javascripts/govuk_publishing_components/analytics-ga4/ga4-search-tracker.js
app/assets/javascripts/govuk_publishing_components/components/search-with-autocomplete.js
docs/analytics-ga4/trackers/ga4-search-tracker.md
spec/javascripts/components/search-with-autocomplete-spec.js
spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-schemas.spec.js
spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-search-tracker.spec.js

This PR:
* adds tracking attributes to the `search_with_autocomplete` component
* amends the `Ga4SearchTracker` to pick them up as part of the `search` event
* extends the GA4 schema to cover the new `search` event fields
We will soon be going live with autocomplete for site search on GOV.UK and need to track user interactions to see if it works as intended.
See [measurement approach document (internal)](https://docs.google.com/document/d/1X6vMjJpr8SiLegBGjnjL4-HSEScG-SWTgk2uy7bnWiM) for details on why we're measuring what we're measuring, and the approach taken.

Add GA4 tracking for search autocomplete

---

.github/workflows/visual-regression-tests.yml
app/controllers/govuk_publishing_components/component_guide_controller.rb
app/models/govuk_publishing_components/component_docs.rb
app/views/govuk_publishing_components/component_guide/index.html.erb

Reorganise the list of components in the application component guides so that:
- App level components are presented first
- Instead of listing All gem component in an app component guide, list gem components NOT used by the app, to potentially help users identify gem components that could be utilised by the app
Application level components are always the fewest in number in each application. They are not easily visible when looking through the list of components, even though we are most likely interested in checking the documentation for the application level components. Listing “All gem components” in a component app guide can make it difficult to identify gem components available to this application that have not already been used, so instead list "Gem components not used by this app". …

Make it easier to find application level components in component guides

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_summary_card.html.erb
spec/components/summary_card_spec.rb

See https://design-system.service.gov.uk/components/summary-list/#showing-rows-with-and-without-actions
This ensures that the bottom border is drawn correctly in some browsers, as well as ensures that items without actions span the full width of the component.

Append no-actions class to rows without actions

---

CHANGELOG.md
app/assets/javascripts/govuk_publishing_components/components/search-with-autocomplete.js
spec/javascripts/components/search-with-autocomplete-spec.js

The `accessible-autocomplete` component has an edge case where when the menu is visible, [it `preventDefault()`s on the Enter key event](https://github.com/alphagov/accessible-autocomplete/blob/b8369d037fd5d26d30a831ed73baa3dd566293ef/src/autocomplete.js#L361), even if the user hasn't yet put keyboard focus on a suggestion. This results in a scenario where the user types something, does _not_ interact with the autocomplete menu at all, and then hits Enter to try to submit the form - but it isn't submitted.
This implements a workaround that adds our own event listener and ensures `requestSubmit` is run for the form if it hasn't been already.
- Add event listener for `keydown` event and submit the containing form ourselves if the key is `Enter`
- Split out code meant to run on accepting a …

Search with autocomplete: Work around Enter edge case

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Add GA4 tracking for search autocomplete ([PR #4371](https://github.com/alphagov/govuk_publishing_components/pull/4371))
* Append no-actions class to rows without actions in Summary Cards ([PR #4368](https://github.com/alphagov/govuk_publishing_components/pull/4368))
* Search with autocomplete: Work around Enter edge case ([PR #4372](https://github.com/alphagov/govuk_publishing_components/pull/4372))

Release 45.1.0

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_radio.html.erb
app/views/govuk_publishing_components/components/docs/radio.yml

- Adds the component wrapper helper to the `radio button` component.
None.

Add component wrapper helper to radio component

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_feedback.html.erb
app/views/govuk_publishing_components/components/docs/feedback.yml

- Adds the component wrapper helper to the `feedback` component.
- Sidenote: I noticed some IE11 references while working on this component, so I've logged that here: https://github.com/alphagov/govuk_publishing_components/issues/4350
None.

Add component wrapper to feedback component

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_layout_for_public.html.erb
app/views/govuk_publishing_components/components/docs/layout_for_public.yml
spec/components/layout_for_public_spec.rb
spec/dummy/app/views/layouts/dummy_public_layout.html.erb

- original behaviour was to always include wrapper class unless show_account_layout or custom_layout was present (custom layout is as of yet not used). Alter behaviour so that default is not to have the wrapper, and it's only included if for_static is true.
layout_for_public does not behave like a standard layout - it's default is to include a wrapper element which is cut out by slimmer and replaced with the wrapper from the client app. If we try to use layout_for_public directly, this results in a double wrapper (or a single wrapper, but without the ability to add classes to it). Adding a parameter which maintains this behaviour (which can be added in Static: https://github.com/alphagov/static/pull/3440 ), but defaulting to not including the wrapper element allows other apps to use the …

Add handling of for_static parameter

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/lib/_print_support.scss
app/views/govuk_publishing_components/components/_action_link.html.erb
app/views/govuk_publishing_components/components/_cards.html.erb
app/views/govuk_publishing_components/components/_contents_list.html.erb
app/views/govuk_publishing_components/components/_devolved_nations.html.erb
app/views/govuk_publishing_components/components/_document_list.html.erb
app/views/govuk_publishing_components/components/_image_card.html.erb
app/views/govuk_publishing_components/components/_inset_text.html.erb
app/views/govuk_publishing_components/components/_intervention.html.erb
app/views/govuk_publishing_components/components/_step_by_step_nav_header.html.erb
app/views/govuk_publishing_components/components/_step_by_step_nav_related.html.erb

- [The component wrapper helper has some validation that restrict what classes can be added to components.](https://github.com/alphagov/govuk_publishing_components/blob/a2285efb2dde7d156178a8e8e0eb6c7bd903d6a7/lib/govuk_publishing_components/presenters/component_wrapper_helper.rb#L100)
- This validation doesn't like `gem-print-link` and `gem-print-links-within` as they don't conform to the validation.
- Therefore, I discussed with Andy and we've renamed them to use `gem-c-` so that they pass the validation.
- This will unblock me adding the component wrapper to more components.
None.

Rename gem-print-link and gem-print-links-within

---

CHANGELOG.md
app/views/govuk_publishing_components/components/feedback/_problem_form.html.erb

When called through the public layout, the feedback component's problem form passes on the block that's been passed to the public layout and implicitly passes it on to the two textarea components, which yield to it, resulting in the page contents passed to the component being rendered three times in the page (once where it's supposed to be, and then once more under each textarea component). Since we don't want blocks passed to these particular textareas, we add an explicit empty block to each one.
When using layout_for_public directly in an app, any yield block passed to that component gets repeated three times.
None

Add empty blocks to prevent double-yielding

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_inverse_header.html.erb
app/views/govuk_publishing_components/components/docs/inverse_header.yml

- Adds the component wrapper helper to the `inverse header` component.
None.

Add component wrapper helper to the inverse header

---

CHANGELOG.md
app/assets/javascripts/govuk_publishing_components/analytics-ga4/ga4-event-tracker.js
spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-event-tracker.spec.js

- Mark events as tracked in the `ga4-event-tracker`
- Ensure that an event has not already been tracked before tracking it
- When nested (such as in the case of details in a tab component) the event tracker was causing multiple pushes to the data layer to occur
- This resulted in some events being tracked twice
- https://trello.com/c/Mt7YXtIc/3040-bugs-double-tracking-in-some-events
- CHANGELOG
- Add test case to `ga4-event-tracker.spec.js`

Mark events as "tracked" to prevent double tracking

---

app/assets/javascripts/govuk_publishing_components/components/search-with-autocomplete.js

This stops the `search_with_autocomplete` component from wasting requests trying to fetch suggestions when our backend won't provide any for query lengths < 3.
Fewer pointless requests is better!
Note that I've not bothered making this configurable - it's unlikely for the time being that this component will be used with a different source/backend, so there isn't much point in adding a configuration option. I've also not added a changelog option as that felt over the top 😄

Search with autocomplete: Set minimum query length

---

CHANGELOG.md
app/assets/javascripts/govuk_publishing_components/components/search-with-autocomplete.js
spec/javascripts/components/search-with-autocomplete-spec.js

This amends the `search_with_autocomplete` component's tracking attributes to track the last non-empty set of suggestions the user has seen, rather than the last set of suggestions regardless of if there were any.
This allows us to track and evaluate why a user doesn't accept any of the suggestions they were offered, choosing instead to type in their own query.

Search with autocomplete: track non-empty suggestions

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/_metadata.scss
app/views/govuk_publishing_components/components/_metadata.html.erb
app/views/govuk_publishing_components/components/docs/metadata.yml
spec/components/metadata_spec.rb

Add heading option to metadata component.
The important metadata block component, used in Government Frontend e.g. https://www.gov.uk/government/statistics/announcements/core-statistics-book-august-2018, can be replaced with the metadata block component. However, some block instances include a title so we should provide a heading option and we can then replace the app variant with this component.
- https://github.com/alphagov/govuk_publishing_components/issues/3482
- https://github.com/alphagov/government-frontend/pull/3414

Add heading option to metadata component

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_inset_text.html.erb
app/views/govuk_publishing_components/components/docs/inset_text.yml

- Adds the component wrapper helper to the `inset_text` component.
None.

Add component wrapper to the inset text component

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_layout_footer.html.erb
app/views/govuk_publishing_components/components/docs/layout_footer.yml

- Adds the component wrapper helper to the `layout_footer` component.
None.

Add component wrapper helper to the footer

---

CHANGELOG.md
app/assets/javascripts/govuk_publishing_components/lib/govspeak/youtube-link-enhancement.js
app/assets/stylesheets/govuk_publishing_components/components/govspeak/_media-player.scss
spec/javascripts/govuk_publishing_components/lib/govspeak/youtube-link-enhancement-spec.js

- enhances the default appearance of a Youtube video link in govspeak when a user has not consented to cookies
- previously this simply showed the default non-JS enhanced link to Youtube
- now replaces it with a whole new element both linking to the video and the cookie settings page, explaining why the video is not shown embedded
If cookies aren't enabled it loops through all the Youtube links, hiding them and inserting this new 'placeholder' element afterwards. Then if cookies are enabled (either before landing on the page or on that page) it finds all the placeholders and removes them, before turning all the hidden links into embedded players.
Here's a page full of videos in case it's useful for testing this: https://www.gov.uk/government/case-studies/improving-attendance-good-practice- …

Enhance Youtube without cookies

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_layout_header.html.erb
app/views/govuk_publishing_components/components/docs/layout_header.yml

- Adds the component wrapper helper to the `layout_header` component.
None.

Add component wrapper helper to the header

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Enhance Youtube without cookies ([PR #4388](https://github.com/alphagov/govuk_publishing_components/pull/4388))
* Add component wrapper helper to the header ([PR #4385](https://github.com/alphagov/govuk_publishing_components/pull/4385))
* Add component wrapper helper to the footer ([PR #4380](https://github.com/alphagov/govuk_publishing_components/pull/4380))
* Add component wrapper to the inset text component ([PR #4387](https://github.com/alphagov/govuk_publishing_components/pull/4387))
* Rename gem-print-link and gem-print-links-within ([PR #4375](https://github.com/alphagov/govuk_publishing_components/pull/4375))
* Fix unwanted additional yield in textareas inside the problem form partial of the feedback component ([PR #4394](https://github.com/alphagov/govuk_publishing_components/pu …

Release 45.3.0

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Chat entry component design changes ([PR #4399](https://github.com/alphagov/govuk_publishing_components/pull/4399))

Release 45.4.0

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/lib/_print_support.scss
app/views/govuk_publishing_components/components/_action_link.html.erb
app/views/govuk_publishing_components/components/_cards.html.erb
app/views/govuk_publishing_components/components/_contents_list.html.erb
app/views/govuk_publishing_components/components/_devolved_nations.html.erb
app/views/govuk_publishing_components/components/_document_list.html.erb
app/views/govuk_publishing_components/components/_image_card.html.erb
app/views/govuk_publishing_components/components/_inset_text.html.erb
app/views/govuk_publishing_components/components/_intervention.html.erb
app/views/govuk_publishing_components/components/_step_by_step_nav_header.html.erb
app/views/govuk_publishing_components/components/_step_by_step_nav_related.html.erb

- In https://github.com/alphagov/govuk_publishing_components/pull/4375, `gem-print-link` and `gem-print-link-within` were renamed to `gem-c-print-link` and `gem-c-print-link-within` to comply with validation set by the component wrapper helper. 
- However, the class name `gem-c-print-link` conflicted with an existing print link class in the print link component. The name change was mistakenly merged without the class being checked to ensure it was unique. The issue was only surfaced when devs were trying to deploy the gem.
- This PR fixes this by giving the class a new name, that is also more descriptive.
None.

Rename print link classes to fix conflict

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Rename print link classes to fix conflict ([PR #4407](https://github.com/alphagov/govuk_publishing_components/pull/4407))

Version 45.4.1

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/_share-links.scss

Updates the colour of the share links in square option to meet design updates
Trello: https://trello.com/c/37SyRmUF/150-rework-share-links

Change icon and link colours on square option for share links

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_chart.html.erb
app/views/govuk_publishing_components/components/docs/chart.yml

- include an option to allow the Y axis to not start at zero but based on the data
- remove unnecessary formatting options
- add a point_size option to allow control over the chart appearance
- add examples of these options and behaviours
Required for chart usage.
With a different point size:
With a break in the data and not starting at zero on the Y axis:
Trello card: https://trello.com/c/aKI3YGL4

Adjust chart options and settings

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Adjust chart options and settings ([PR #4405](https://github.com/alphagov/govuk_publishing_components/pull/4405))
* Change colours on square option for share links ([PR #4409](https://github.com/alphagov/govuk_publishing_components/pull/4409))
* LUX 4.0.28 ([PR #4404](https://github.com/alphagov/govuk_publishing_components/pull/4404))

Version 45.5.0

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/_share-links.scss

- On the share links with square icons, the focus styles overspilled by a few pixels over the top of the element
- I showed this to our designer, he agreed that we should get rid of this few pixel overspill
- See screenshots

Fix yellow focus colour overspill

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/_chat-entry.scss
app/views/govuk_publishing_components/components/_chat_entry.html.erb
app/views/govuk_publishing_components/components/docs/chat_entry.yml
spec/components/chat_entry_spec.rb

This PR adds a `margin_top_until_tablet` option to the chat entry component, which adds `margin-top: 35px` on smaller screen sizes (i.e. <= tablet). I've opted for applying this via a `.gem-c-chat-entry--margin-top-until-tablet` rather than using the `margin_top` helper as 1). it should only be applied at certain screen sizes and 2). the specific amount of margin required isn't supported by the helper.
Design requirements - [trello card](https://trello.com/c/iOuUw0vs/2157-entry-banner-tweaks).
N/A

Add margin_top_until_tablet option to chat entry component

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Fix yellow focus colour overspill ([PR #4418](https://github.com/alphagov/govuk_publishing_components/pull/4418))
* Add margin_top_until_tablet option to chat entry component ([PR #4417](https://github.com/alphagov/govuk_publishing_components/pull/4417))

Version 45.6.0

---

CHANGELOG.md
app/assets/javascripts/govuk_publishing_components/components/search-with-autocomplete.js
spec/javascripts/components/search-with-autocomplete-spec.js

Our workaround for the `accessible-autocomplete` library hogging the Enter key when the menu is open was too greedy, and also submitted the form when the menu in fact wasn't open.
This adds a check to the workaround to ensure the menu is actually shown, as the behaviour doesn't actually happen otherwise.
Double submits are unnecessary, and while it wouldn't cause any user-visible impact, it would cause some problems with analytics.

Fix `search_with_autocomplete` double submit scenario

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Fix "sticky" GA4 search tracker `tool_name` ([PR #4422](https://github.com/alphagov/govuk_publishing_components/pull/4422))
* Fix `search_with_autocomplete` double submit scenario ([PR #4421](https://github.com/alphagov/govuk_publishing_components/pull/4421))

Version 45.6.1

---

app/views/govuk_publishing_components/components/_chart.html.erb
lib/govuk_publishing_components/presenters/chart_helper.rb
spec/lib/govuk_publishing_components/components/chart_helper_spec.rb

Fixes the `minimal` option in the chart component, because it wasn't hiding the legend, removing interactivity, or reducing point size automatically, as it should have been.
Managed to break this as part of https://github.com/alphagov/govuk_publishing_components/pull/4424
None (except to fix minimal mode back to what it should be).

Fix chart minimal option

---

CHANGELOG.md
app/assets/javascripts/govuk_publishing_components/analytics-ga4/ga4-search-tracker.js
spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-search-tracker.spec.js

We want to apply the search input standardisation for the search event not just on the search term itself, but also on the (partial) user input that led to the autocomplete suggestions being triggered.
- Refactor `Ga4SearchTracker.searchTerm()` into a more generic `.standardiseInput()` that we can use for both search term and trigger input value
- Standardise search term for both using this new function
- Add missing changelog entry for a previous PR (sorry!)
This will make our search events more consistently sanitised for analytics purposes.

search_with_autocomplete: Standardise trigger input

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_label.html.erb
app/views/govuk_publishing_components/components/docs/label.yml

- Adds the component wrapper helper to the `form label` component.
None.

Add component wrapper helper to label component

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Add the component wrapper to the lead paragraph component ([PR #4434](https://github.com/alphagov/govuk_publishing_components/pull/4434))
* Add component wrapper helper to label component ([PR #4364](https://github.com/alphagov/govuk_publishing_components/pull/4364))
* `search_with_autocomplete`: Change trigger input tracking ([PR #4428](https://github.com/alphagov/govuk_publishing_components/pull/4428))

Version 45.8.0

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_layout_footer.html.erb
app/views/govuk_publishing_components/components/docs/layout_footer.yml
spec/components/layout_footer_spec.rb

The layout footer component is used quite a lot by internal services, where it doesn’t make sense to show licence details. This adds a `show_licence` option to allow users to hide the licence if they want/need to. This will always default to `true`, unless the option is specifically set to `false`.

Allow licence details in footer to be hidden

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Limit chart heading width ([PR #4435](https://github.com/alphagov/govuk_publishing_components/pull/4435))
* Allow the licence details to be hidden ([PR #4438](https://github.com/alphagov/govuk_publishing_components/pull/4438))

Version 45.9.0

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_metadata.html.erb
app/views/govuk_publishing_components/components/docs/metadata.yml
spec/components/metadata_spec.rb

Fix an issue in the metadata component where only the first queried toggle section (`data-module="gem-toggle"`) is being initialised
See [extensive example](https://components-gem-pr-4397.herokuapp.com/component-guide/metadata/extensive)
A metadata component can include multiple toggle regions e.g. https://www.gov.uk/international-development-funding/global-innovation-fund (sections like 'countries' and 'sectors'), which should be transformed into separate toggle areas.
By moving the 'toggle' data module from the parent element to each individual region, each metadata group becomes a separate toggle region.

Add 'toggle' module to each expandable region in metadata component

---

CHANGELOG.md
app/views/govuk_publishing_components/components/docs/metadata.yml

Add a description for the metadata block `see_updates_link` example
https://components-gem-pr-4447.herokuapp.com/component-guide/metadata/updated_with_links_to_see_details
To provide more information on what these options do, including a link to an example page.

Add a description for the metadata block 'see_updates_link' example

---

CHANGELOG.md
app/assets/javascripts/govuk_publishing_components/components/add-another.js
app/assets/stylesheets/govuk_publishing_components/_all_components.scss
app/assets/stylesheets/govuk_publishing_components/components/_add-another.scss
app/views/govuk_publishing_components/components/_add_another.html.erb
app/views/govuk_publishing_components/components/_fieldset.html.erb
app/views/govuk_publishing_components/components/docs/add_another.yml
spec/components/add_another_spec.rb
spec/javascripts/components/add-another-spec.js
spec/lib/govuk_publishing_components/app_helpers/asset_helper_spec.rb

- Add the component wrapper helper to fieldsets
- Introduce the add another component based on the [MoJ design system](https://design-patterns.service.justice.gov.uk/components/add-another/) and [existing component in Whitehall](https://github.com/alphagov/whitehall/blob/main/app/assets/javascripts/admin/modules/add-another.js). 
- An empty field and destroy checkboxes for the existing fields are required and displayed to the user when javascript is disabled in keeping with rails conventions.
- When Javascript is enabled, an "add another" button is introduced to allow users to add copies of the empty field and the checkboxes replaced with "Delete" buttons which hide the fields and checks the appropriate checkbox.
- This component is to be used when users need to add similar information a …

Introduce "add another" component

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* **BREAKING** Stop setting `id` on fieldsets ([PR #4454](https://github.com/alphagov/govuk_publishing_components/pull/4454))

Version 46.0.0

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/_all_components.scss
app/assets/stylesheets/govuk_publishing_components/components/_glance-metric.scss
app/views/govuk_publishing_components/components/_glance_metric.html.erb
app/views/govuk_publishing_components/components/docs/glance_metric.yml
spec/components/glance_metric_spec.rb
spec/lib/govuk_publishing_components/app_helpers/asset_helper_spec.rb

This is based on the `glance_metric` component used in [content-data-admin](https://github.com/alphagov/content-data-admin) with some unused options removed. I’ve also tweaked the display of the explicit label, as `aria-label` is not supported on non-semantic elements,
Trello card: https://trello.com/c/eJTfFnFN/700-create-rollup-for-view-page-and-review-page

Add a `glance_metric` component

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_panel.html.erb
app/views/govuk_publishing_components/components/docs/panel.yml

- Adds the component wrapper helper to the `panel` component.
None.

Use component wrapper on panel component

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_notice.html.erb
app/views/govuk_publishing_components/components/docs/notice.yml

- Adds the component wrapper helper to the `notice` component.
- **Note:** This component uses an `aria_live` boolean to set `aria-live: polite`. I assume it would be best for this to be changed so that you pass `aria: { live: 'polite' }` - but was not sure if I should do this, as that would make this a breaking change which increases deployment complexity. I guess I'm not sure what our stance is on whether we want things perfectly using the wrapper or not.
None.

Use component wrapper on notice component

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_phase_banner.html.erb
app/views/govuk_publishing_components/components/docs/phase_banner.yml

Adds the component wrapper helper to the `phase banner` component.
None.

Use the component wrapper on the phase banner component 

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_metadata.html.erb
app/views/govuk_publishing_components/components/docs/metadata.yml
docs/component-wrapper-helper.md
lib/govuk_publishing_components/presenters/component_wrapper_helper.rb
spec/lib/govuk_publishing_components/components/component_wrapper_helper_spec.rb

- Adds the component wrapper helper to the `metadata` component.
- **Note:** I added `direction-rtl` to the permitted classes, as it's used across multiple components, but if you think I should do something else, let me know.
None.

Add component wrapper to the metadata component

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Use component wrapper on panel component ([PR #4459](https://github.com/alphagov/govuk_publishing_components/pull/4459))
* Use the component wrapper on the phase banner component ([PR #4460](https://github.com/alphagov/govuk_publishing_components/pull/4460))
* Add a `glance_metric` component ([PR #4452](https://github.com/alphagov/govuk_publishing_components/pull/4452))
* Use component wrapper on org logo component ([PR #4458](https://github.com/alphagov/govuk_publishing_components/pull/4458))
* Use component wrapper on notice component ([PR #4444](https://github.com/alphagov/govuk_publishing_components/pull/4444))
* Add component wrapper to the metadata component ([PR #4442](https://github.com/alphagov/govuk_publishing_components/pull/4442))

Version 46.1.0

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_previous_and_next_navigation.html.erb
app/views/govuk_publishing_components/components/docs/previous_and_next_navigation.yml

- Adds the component wrapper helper to the `previous and next` component.
None.

Use component wrapper on previous and next component

---

CHANGELOG.md
config/locales/cy.yml

Allow the devolved administration component to work properly on Welsh pages.
Trello card: https://trello.com/c/EFcpWfY2/3071-allow-devolved-administration-component-to-support-welsh-m

Allow the devolved nations component to work properly on Welsh pages

---

app/models/govuk_publishing_components/audit_components.rb
app/views/govuk_publishing_components/components/_search.html.erb
spec/component_guide/audit_components_spec.rb

Removes the heading helper from the search component.
- not used
- also remove it from the auditing tools, because it's only used by one other component (the heading component) and we only need to audit helpers that are used by multiple components, lots of components already have their own individual helpers
None.

Remove heading helper from search component

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_reorderable_list.html.erb
app/views/govuk_publishing_components/components/_share_links.html.erb
app/views/govuk_publishing_components/components/docs/reorderable_list.yml
app/views/govuk_publishing_components/components/docs/share_links.yml

- Adds the component wrapper helper to the `reorderable list` component.
None.

Use component wrapper on reorderable list component

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_copy_to_clipboard.html.erb
spec/components/copy_to_clipboard_spec.rb

Use the "button" button type for the copy to clipboard button
The copy to clipboard component is not used as a form submit button, and therefore should have the "button" button type instead of the "submit" button type.
This affects the tracking implementation in Whitehall ([related Trello](https://trello.com/c/mVJGdWsZ))

Use correct button type for copy to clipboard component

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_signup_link.html.erb
app/views/govuk_publishing_components/components/docs/signup_link.yml

- Adds the component wrapper helper to the `signup link` component.
None.

Use component wrapper on signup link component

---

spec/component_guide/component_audit_spec.rb
spec/component_guide/component_example_accessibility_criteria_spec.rb
spec/component_guide/component_example_accessibility_testing_spec.rb
spec/component_guide/component_example_spec.rb
spec/component_guide/component_index_spec.rb
spec/component_guide/component_preview_spec.rb
spec/components/contextual_breadcrumbs_spec.rb
spec/components/contextual_footer_spec.rb
spec/components/input_spec.rb
spec/components/layout_footer_spec.rb
spec/components/layout_for_public_spec.rb
spec/components/radio_spec.rb
spec/components/search_spec.rb
spec/components/textarea_spec.rb
spec/features/accordion_spec.rb
spec/features/asset_helper_spec.rb
spec/features/contextual_navigation_spec.rb
spec/features/step_nav_helper_spec.rb
spec/features/tabs_spec.rb
spec/rails_helper.rb
spec/visual_regression_tests/all_components_spec.rb

This PR was prompted after discovering in https://github.com/alphagov/govuk_publishing_components/pull/4451 that the commonly used `assert_no_selector` test assertion in view specs didn't actually assert anything and would pass even if given `assert_no_selector("*")`
The reason this non-assertion was available was because it is using a Capybara assertion (from the [Capybara::DSL](https://github.com/alphagov/govuk_publishing_components/blob/52b5260d4809c31015aee8806c21833e99237f4a/spec/rails_helper.rb#L13)) - however these assertions only have an impact if you have run `visit(url)` and have a `page` variable.
To remedy this I have taken 2 steps: 
1. I have replaced all usages of `assert_no_selector(selector)` to be `assert_select(selector, false)` to confirm when a selector isn't available …

Fix broken spec assertions

---

CHANGELOG.md
Gemfile.lock
app/views/govuk_publishing_components/components/_layout_super_navigation_header.html.erb
govuk_publishing_components.gemspec
spec/component_guide/component_index_spec.rb
spec/components/layout_super_navigation_header_spec.rb
spec/rails_helper.rb

This changes the layout super navigation header to use the new `search_with_autocomplete` component instead of the vanilla `search` one.
So users can enjoy the same autocompleting experience as on the homepage and search page.

[DO NOT MERGE] Layout super nav header: Add search autocomplete

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/_share-links.scss

Remove min-width from share links flexbox variant list-items
Current share items look odd with very small text content (eg X)
(screenshots from frontend, but also compare: https://components.publishing.service.gov.uk/component-guide/share_links/with_flexbox/preview with https://components-gem-pr-4488.herokuapp.com/component-guide/share_links/with_flexbox/preview)

Remove min-width from share links flexbox variant list-items

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Remove min-width from share links flexbox variant list-items ([PR #4488](https://github.com/alphagov/govuk_publishing_components/pull/4488))
* Add search autocomplete to layout super navigation header ([PR #4451](https://github.com/alphagov/govuk_publishing_components/pull/4451))
* Use component wrapper on reorderable list component ([PR #4474](https://github.com/alphagov/govuk_publishing_components/pull/4474))
* Use "button" button type for copy to clipboard component ([PR #4480](https://github.com/alphagov/govuk_publishing_components/pull/4480))
* Use component wrapper on signup link component ([PR #4481](https://github.com/alphagov/govuk_publishing_components/pull/4481))

Release 46.3.0

---

CHANGELOG.md
app/assets/javascripts/govuk_publishing_components/analytics-ga4/ga4-specialist-link-tracker.js
spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-specialist-link-tracker.spec.js

- Ensure links starting with `https://www.gov.uk/media/` are tracked as download links
- We either missed tracking these, or these links were recently reintroduced after an issue with attachments. Therefore the 'View Online' links were not being tracked if they used this old type of link.
- Example link: https://www.gov.uk/government/statistical-data-sets/management-information-ofsteds-initial-teacher-education-ite-inspections-outcomes
- https://trello.com/c/SlmI0kKL/847-attachment-navigation-link-clicks-not-firing-on-certain-links-view-online-links
None.

Add /media/ path to GA4 download link tracking

---

CHANGELOG.md
lib/govuk_publishing_components/app_helpers/asset_helper.rb

This adds the search-with-autocomplete component to the list of those served by static.
We are adding this to static in: https://github.com/alphagov/static/pull/3532 and want to avoid serving this stylesheet unnecessarily to users.
None

Add search-with-autocomplete to stylesheets served by static

---

CHANGELOG.md
app/assets/javascripts/govuk_publishing_components/analytics-ga4/ga4-core.js
spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-core.spec.js

- Limit the search term sent to GA4 to 500 characters
- Request by PAs, to reduce the amount of data collected
- https://trello.com/c/ZQbreFrw/856-add-500-character-limit-to-ecommerce-searchterm-tracking
None.

Limit GA4 search term tracking to 500 characters

---

app/views/govuk_publishing_components/component_guide/show.html.erb
app/views/govuk_publishing_components/components/_contextual_guidance.html.erb
docs/component-wrapper-helper.md

Update the component wrapper documentation to include recently added options e.g. `tabindex`.
Fix a bug with the component guide where the component wrapper options weren't being shown for components that only have one variation (e.g. contextual guidance).
Keeping documentation up to date.
Changes on the component guide page to the contextual guidance component.
Before | After
Trello card: https://trello.com/c/ZHmeJbMd/380-fix-missing-component-wrapper-information-on-components-without-variations

Component wrapper documentation fixes

---

CHANGELOG.md
app/models/govuk_publishing_components/component_wrapper_helper_options.rb
app/views/govuk_publishing_components/components/_accordion.html.erb
app/views/govuk_publishing_components/components/_action_link.html.erb
app/views/govuk_publishing_components/components/_chart.html.erb
app/views/govuk_publishing_components/components/_chat_entry.html.erb
app/views/govuk_publishing_components/components/_contents_list.html.erb
app/views/govuk_publishing_components/components/_contextual_sidebar.html.erb
app/views/govuk_publishing_components/components/_details.html.erb
app/views/govuk_publishing_components/components/_document_list.html.erb
app/views/govuk_publishing_components/components/_govspeak.html.erb
app/views/govuk_publishing_components/components/_heading.html.erb
app/views/govuk_publishing_components/components/_hint.html.erb
app/views/govuk_publishing_components/components/_inset_text.html.erb
app/views/govuk_publishing_components/components/_lead_paragraph.html.erb
app/views/govuk_publishing_components/components/_metadata.html.erb
app/views/govuk_publishing_components/components/_notice.html.erb
app/views/govuk_publishing_components/components/_password_input.html.erb
app/views/govuk_publishing_components/components/_radio.html.erb
app/views/govuk_publishing_components/components/_signup_link.html.erb
app/views/govuk_publishing_components/components/_single_page_notification_button.html.erb
docs/component-wrapper-helper.md
lib/govuk_publishing_components/presenters/component_wrapper_helper.rb
spec/components/details_spec.rb
spec/components/heading_spec.rb
spec/components/hint_spec.rb
spec/lib/govuk_publishing_components/components/component_wrapper_helper_spec.rb

Adds a `margin_bottom` option to the component wrapper helper, effectively copying it out of the shared_helper.
I wanted to write a new set of classes here for margins to stop using the govuk-frontend margin override classes, because they should only be used where an override is necessary (they use `!important`). However right out the gate it turns out we do need the override classes - just to override the default margin applied to some of the govuk-frontend components (details, for example, where we want a 15px margin and the component comes with 30px by default).
Supercedes https://github.com/alphagov/govuk_publishing_components/pull/4470
The CW helper seems like the more logical home for this option, rather than the shared helper. Additionally, cleaning up and standardising this will …

Add margin_bottom option to component wrapper helper

---

CHANGELOG.md
app/assets/javascripts/govuk_publishing_components/analytics-ga4/ga4-page-views.js
spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-page-views.spec.js

- Adds a `canonical_url` attribute to the GA4 page view tracker.
- https://trello.com/b/rm8pjAAk/ga4-gtm-implementation-ga4-team-user-experience-govuk
None.

Add canonical_url value to GA4 page view tracking

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_step_by_step_nav.html.erb
app/views/govuk_publishing_components/components/docs/step_by_step_nav.yml

- Adds the component wrapper helper to the `step by step navigation` component.
None.

Use component wrapper on step nav component

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Add canonical_url value to GA4 page view tracking ([PR #4500](https://github.com/alphagov/govuk_publishing_components/pull/4500))
* Add margin_bottom option to component wrapper helper ([PR #4494](https://github.com/alphagov/govuk_publishing_components/pull/4494))
* Limit GA4 search term tracking to 500 characters ([PR #4496](https://github.com/alphagov/govuk_publishing_components/pull/4496))

Version 46.4.0

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/govspeak/_highlight-answer.scss

Change the spacing in the highlight-answer styling to use govuk-spacing. 
This change is to increase reliance on the design system and decrease the amount of custom styling we have in the publishing components. 
There will be some slight changes to the spacing in the answer component. Since only 5 pages use this component I will include all of the changes below:
|--------|--------|
| <img width="1005" alt="image" src="https://github.com/user-attachments/assets/5bddb67e-bd34-4974-b1c9-b936a08a78aa" /> | <img width="1007" alt="image" src="https://github.com/user-attachments/assets/db1aadcc-d9ba-421b-b6bc-78b87d9900d3" />|
| <img width="1005" alt="image" src="https://github.com/user-attachments/assets/47fec071-87f3-4f5a-a1a6-825616eeb54e" /> | <img width="1008" alt="image" …

Use govuk-spacing for highlight answer govspeak component

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/_heading.scss
app/views/govuk_publishing_components/components/_heading.html.erb
app/views/govuk_publishing_components/components/docs/heading.yml
lib/govuk_publishing_components/presenters/heading_helper.rb
spec/components/chart_spec.rb
spec/components/heading_spec.rb

Adds a context option to the heading component, to mimic the behaviour of context on the page title component.
This also removes the 'with mobile top margin' option from the component, as we're trying to move away from margin top on components. Instead, this spacing will be applied to previous elements on a case by case basis, in further pull requests.
- instances of `mobile_top_margin` are [limited to government-frontend](https://github.com/search?q=org%3Aalphagov%20mobile_top_margin&type=code)
- PR to remove those instances: https://github.com/alphagov/government-frontend/pull/3489
We're removing the margin_top option from the title component (https://github.com/alphagov/govuk_publishing_components/pull/4508) and there are some places where this is still needed. However if the heading …

Add context option to heading component

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/_organisation-logo.scss
app/views/govuk_publishing_components/components/docs/organisation_logo.yml
lib/govuk_publishing_components/presenters/organisation_logo_helper.rb
spec/components/organisation_logo_spec.rb

An option for organisation logos to hide the link underline until it's hovered. [Trello](https://trello.com/c/TT6qZYWG/216-org-logo-component-has-app-level-styling)
On the new [Missions](https://www.gov.uk/missions) landing page served by the frontend app, the organisation logo in the header has the underline removed. This was achieved using some localised override CSS, which is against our principle of component isolation.
| Unhovered | Hovered |
| -------- | ------- |
| <img width="332" alt="image" src="https://github.com/user-attachments/assets/9d64d860-2ded-4dee-86d8-50158ffd4e3c" /> | <img width="332" alt="image" src="https://github.com/user-attachments/assets/b8769fd2-71ec-403d-8ae9-cc2b6a8ca94b" />|

Add option for organisation logos to hide the link underline until it's hovered

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_skip_link.html.erb
app/views/govuk_publishing_components/components/docs/skip_link.yml

- Adds the component wrapper helper to the `skip link` component.
None.

Use component wrapper on skip link component

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_step_by_step_nav_header.html.erb
app/views/govuk_publishing_components/components/docs/step_by_step_nav_header.yml

- Adds the component wrapper helper to the `step nav header` component.
None.

Use component wrapper on step nav header component

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_step_by_step_nav_related.html.erb
app/views/govuk_publishing_components/components/docs/step_by_step_nav_related.yml

- Adds the component wrapper helper to the `step nav related` component.
None.

Use component wrapper on step nav related component

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* **BREAKING** Remove chart component ([PR #4518](https://github.com/alphagov/govuk_publishing_components/pull/4518))
* Use govuk-spacing for highlight answer govspeak component ([PR #4515](https://github.com/alphagov/govuk_publishing_components/pull/4515))
* Add context option to heading component ([PR #4510](https://github.com/alphagov/govuk_publishing_components/pull/4510))
* Add option for organisation logos to hide the link underline until it's hovered ([PR #4509](https://github.com/alphagov/govuk_publishing_components/pull/4509))
* Remove chat entry component ([PR #4512](https://github.com/alphagov/govuk_publishing_components/pull/4512))
* Use component wrapper on skip link component ([PR #4520](https://github.com/alphagov/govuk_publishing_components/pull/4520))
* Use component …

Version 47.0.0

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_subscription_links.html.erb
app/views/govuk_publishing_components/components/docs/subscription_links.yml
spec/components/subscription_links_spec.rb

- Adds the component wrapper helper to the `subscription links` component.
None.

Use component wrapper on subscription links

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_success_alert.html.erb
app/views/govuk_publishing_components/components/docs/success_alert.yml

- Adds the component wrapper helper to the `success alert` component.
None.

Use component wrapper on success alert component

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_summary_card.html.erb
app/views/govuk_publishing_components/components/docs/summary_card.yml

- Adds the component wrapper helper to the `summary card` component.
None.

Use component wrapper on summary card component

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_summary_list.html.erb
app/views/govuk_publishing_components/components/docs/summary_list.yml

- Adds the component wrapper helper to the `summary list` component.
None.

Use component wrapper on summary list component

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_translation_nav.html.erb
app/views/govuk_publishing_components/components/docs/translation_nav.yml

- Adds the component wrapper helper to the `translation nav` component.
None.

Use component wrapper on translation nav component

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_warning_text.html.erb
app/views/govuk_publishing_components/components/docs/warning_text.yml

- Adds the component wrapper helper to the `warning text` component.
None.

Use component wrapper on warning text component

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_intervention.html.erb
app/views/govuk_publishing_components/components/docs/intervention.yml

- Adds the component wrapper helper to the `intervention` component.
- **BREAKING CHANGE** This is a breaking change as it renames the `aria_attributes` object to use the component wrapper's object called `aria`. However setting extra aria attributes is not used in production, so it shouldn't break anything on GOVUK. https://github.com/search?q=org%3Aalphagov+govuk_publishing_components%2Fcomponents%2Fintervention&type=Code  
As the [trello card](https://trello.com/c/Km9cakJx/417-add-component-wrapper-helper-to-intervention-component) states:
None.

**BREAKING**: Add component wrapper helper to intervention component

---

CHANGELOG.md
app/views/govuk_publishing_components/components/docs/devolved_nations.yml
lib/govuk_publishing_components/presenters/devolved_nations_helper.rb
spec/components/devolved_nations_spec.rb
spec/lib/govuk_publishing_components/components/devolved_nations_helper_spec.rb

Change an option on the devolved nations component.
- rename from 'type' to 'content_type'
- doing this work ahead of adding a 'type' option to the component wrapper helper, which would conflict with this component
- will be a **breaking change** as this option is used in `government-frontend` - see related fix in https://github.com/alphagov/government-frontend/pull/3508
None.
Trello card: https://trello.com/c/hUDC8lzz/418-add-component-wrapper-helper-to-button-component

[BREAKING] Change devolved nations component type option

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_layout_super_navigation_header.html.erb
app/views/govuk_publishing_components/components/docs/layout_super_navigation_header.yml

- Adds the component wrapper helper to the `super navigation header` component.
- This was tagged as breaking, but it doesn't look it is so it was probably labelled by mistake when I started adding the wrapper to components.
As the [trello card](https://trello.com/c/OJ0nOkQr/420-add-component-wrapper-helper-to-layout-super-navigation-component) states:
None.

Use component wrapper on super navigation header

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_list.html.erb
app/views/govuk_publishing_components/components/docs/list.yml
spec/components/list_spec.rb

- Adds the component wrapper helper to the `list` component.
- Breaking as this component was using `aria_label` to set its label, but now it should use the component wrapper functionality.
- Should only affect one template: https://github.com/search?q=org%3Aalphagov+govuk_publishing_components%2Fcomponents%2Flist+AND+aria_label&type=code
As the [trello card](https://trello.com/c/ro4UhaAa/423-add-component-wrapper-helper-to-list-component) states:
None.

**BREAKING** Add component wrapper helper to the list component

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_layout_super_navigation_header.html.erb
spec/components/layout_super_navigation_header_spec.rb

We are centralising the enabling/disabling of autocomplete in Search API v2 so we don't need individual feature flags across several apps and in the component itself.
The rationale for being able to disable autocomplete centres on a scenario in which the underlying search engine returns unsuitable results. The `search_with_autocomplete` component degrades gracefully anyway when no suggestions are returned, so we are moving to a simpler setup where there is a feature flag on Search API v2 to force returning empty responses instead.
**Depends on https://github.com/alphagov/search-api-v2/pull/375**

Remove `GOVUK_DISABLE_SEARCH_AUTOCOMPLETE` feature flag

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_search.html.erb
app/views/govuk_publishing_components/components/docs/search.yml
app/views/govuk_publishing_components/components/layout_header/_search.html.erb
spec/components/search_spec.rb

- Adds the component wrapper helper to the `search` component.
- Breaking as it:
- Renames the `id` option to `label_id`
- Renames `data_attributes` to `button_data_attributes` - though this is not used anywhere on GOV.UK (should it removed? I think it was needed for when Universal Analytics was on GOV.UK.)
- Should only affect three templates/two repos across GOV.UK: 
- https://github.com/alphagov/signon/blob/2cef467f8c0fc43ac633c05b9b10124a27d0ad86/app/views/users/_users_filter.html.erb#L4
- https://github.com/alphagov/finder-frontend/blob/cb655bed56409ea6cbe4f196a58665b3b6e0a6fa/app/views/finders/_show_header.html.erb#L13
- https://github.com/alphagov/finder-frontend/blob/cb655bed56409ea6cbe4f196a58665b3b6e0a6fa/app/views/finders/_facet_collection.html.erb#L9
As the [trello …

BREAKING Add component wrapper helper to the search component

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Report cache status to RUM ([PR #4537](https://github.com/alphagov/govuk_publishing_components/pull/4537))
* Add type option to component wrapper helper ([PR #4536](https://github.com/alphagov/govuk_publishing_components/pull/4536))
* **BREAKING** Change devolved nations component type option ([PR #4535](https://github.com/alphagov/govuk_publishing_components/pull/4535))
* **BREAKING** Add component wrapper helper to intervention component ([PR #4378](https://github.com/alphagov/govuk_publishing_components/pull/4378))
* **BREAKING** Add component wrapper helper to the list component ([PR #4441](https://github.com/alphagov/govuk_publishing_components/pull/4441))
* **BREAKING** Add component wrapper helper to the search component ([PR …

Version 48.0.0

---

app/views/govuk_publishing_components/components/docs/document_list.yml

Update the documentation for the equal item spacing in the document list component to reflect usage
This option for the document-list component was originally added for the new search UI, but is now used in other contexts together with the full size description text.
[Trello](https://trello.com/c/F3iYypdh/3053-settle-on-an-approach-for-rendering-a-list-of-links-with-paragraph-tags-as-well-as-the-correct-spacing-m)

Update the document list equal item spacing docs to reflect usage

---

app/models/govuk_publishing_components/component_wrapper_helper_options.rb
docs/component-wrapper-helper.md
lib/govuk_publishing_components/presenters/component_wrapper_helper.rb
spec/lib/govuk_publishing_components/components/component_wrapper_helper_spec.rb

Adds the [draggable attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/draggable) to the component wrapper helper.
Also includes a clean up/restructure of the tests, and adding some missing things to the documentation.
Needed for the button component.
None.
Trello card: https://trello.com/c/hUDC8lzz/418-add-component-wrapper-helper-to-button-component

Add 'draggable' attribute to component wrapper helper

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_attachment.html.erb
app/views/govuk_publishing_components/components/docs/attachment.yml
spec/components/attachment_spec.rb

- Adds the component wrapper to the attachment component
- This is a breaking change, as it renames `data_attributes` to `url_data_attributes`, as those data attributes were being used on a child component - `data_attributes` is now for data attributes applied to the parent HTML element.
- This should only affect two templates - [1](https://github.com/alphagov/content-publisher/blob/35087b160e255bd71b8cfbc82581d0526ca9cc4c/app/views/file_attachments/_file_attachment.html.erb#L45) and [2](https://github.com/alphagov/content-publisher/blob/35087b160e255bd71b8cfbc82581d0526ca9cc4c/app/views/file_attachments/show.html.erb#L7) which I verified using [this search criteria](https://github.com/search?q=org%3Aalphagov+govuk_publishing_components%2Fcomponents%2Fattachment+AND+data_attributes&type=co …

BREAKING Use component wrapper on attachment component

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_big_number.html.erb
app/views/govuk_publishing_components/components/docs/big_number.yml
spec/components/big_number_spec.rb

- Adds the component wrapper to the big number component
- This is a breaking change, as it renames `data_attributes` to `nested_data_attributes`, as those data attributes were being used on a child component - `data_attributes` is now for data attributes applied to the parent HTML element. I went with the name `nested_data_attributes` as it can either be on a `span` or `a` tag depending on what is passed to the component.
- This should only affect two templates which I verified using [this search criteria](https://github.com/search?q=org%3Aalphagov+govuk_publishing_components%2Fcomponents%2Fbig_number+AND+data_attributes&type=code).
- Also fixes some incorrect documentation, and removes the shared helper as the component wrapper now handles margin_bottom values.
As the [trello …

BREAKING Use component wrapper on big number component

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_attachment_link.html.erb
app/views/govuk_publishing_components/components/docs/attachment_link.yml
spec/components/attachment_link_spec.rb

- Adds the component wrapper to the attachment component
- This is a breaking change, as it renames `data_attributes` to `url_data_attributes`, as those data attributes were being used on a child component - `data_attributes` is now for data attributes applied to the parent HTML element.
- This should only affect one template which I verified using [this search criteria](https://github.com/search?q=org%3Aalphagov+govuk_publishing_components%2Fcomponents%2Fattachment_link&type=Code).
As the [trello card](https://trello.com/c/oSMnbqXu/427-add-component-wrapper-helper-to-attachment-link-component) states:
1 example has had its titled …

BREAKING Use component wrapper on attachment link component

---

CHANGELOG.md
app/models/govuk_publishing_components/component_wrapper_helper_options.rb
docs/component-wrapper-helper.md
lib/govuk_publishing_components/presenters/component_wrapper_helper.rb
spec/lib/govuk_publishing_components/components/component_wrapper_helper_spec.rb

Adds the [rel](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/rel) attribute to the component wrapper helper.
Needed for the migration of the [button component](https://components.publishing.service.gov.uk/component-guide/button) onto the component wrapper.
None.
Trello card: https://trello.com/c/hUDC8lzz/418-add-component-wrapper-helper-to-button-component

Add rel attribute to component wrapper

---

lib/govuk_publishing_components/presenters/component_wrapper_helper.rb
spec/lib/govuk_publishing_components/components/component_wrapper_helper_spec.rb

Fixes a bug in how the component wrapper handles the `rel` option.
- code previously assumed that only one rel option would be passed, but you can have more than one in the attribute
- passing more than one previously caused an error even if all of the rels were valid, this change corrects that
Because I didn't think of this when I was writing it yesterday 🤦 
None.
Trello card: https://trello.com/c/hUDC8lzz/418-add-component-wrapper-helper-to-button-component

Fix component wrapper rel option

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_modal_dialogue.html.erb
app/views/govuk_publishing_components/components/docs/modal_dialogue.yml

- Adds the component wrapper to the modal dialogue component
- This is a breaking change, as it removes the `data_attributes` hash which was placed on a child element. `data_attributes` is not actually used across any templates currently, so it can be safely removed. https://github.com/search?q=org%3Aalphagov+govuk_publishing_components%2Fcomponents%2Fmodal_dialogue&type=Code 
- Although this is a breaking change, it shouldn't affect any existing code on GOVUK.
As the [trello card](https://trello.com/c/NigFMJSC/431-add-component-wrapper-helper-to-modal-dialog-component) states:
Removed an example.

BREAKING Use component wrapper on modal dialogue component

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_contents_list.html.erb
app/views/govuk_publishing_components/components/_cross_service_header.html.erb
app/views/govuk_publishing_components/components/_layout_footer.html.erb
app/views/govuk_publishing_components/components/_layout_header.html.erb
app/views/govuk_publishing_components/components/_layout_super_navigation_header.html.erb
app/views/govuk_publishing_components/components/_previous_and_next_navigation.html.erb
app/views/govuk_publishing_components/components/_secondary_navigation.html.erb
app/views/govuk_publishing_components/components/_translation_nav.html.erb
app/views/govuk_publishing_components/components/docs/layout_footer.yml
app/views/govuk_publishing_components/components/layout_for_public/_account-layout.html.erb
app/views/govuk_publishing_components/components/related_navigation/_section.html.erb
spec/components/previous_and_next_navigation_spec.rb
spec/components/translation_nav_spec.rb
spec/dummy/app/views/layouts/dummy_admin_layout.html.erb
spec/javascripts/components/cross-service-header-spec.js
spec/lib/govuk_publishing_components/components/component_wrapper_helper_spec.rb

Remove redundant `role` attributes from components.
From GOV.UK Frontend:
<blockquote>
We've made minor changes to the HTML of the page template, as well as the header, footer and pagination components.
You can update your HTML to remove the role attribute from some elements. These include the:
`main` role on the `main` element in the template
`banner` role on the `header` element in the Header component
`contentinfo` role on the `footer` element in the Footer component
`navigation` role on the `nav` element in the Pagination component
These roles were present to support legacy browsers, such as older versions of Internet Explorer. GOV.UK Frontend no longer supports these browsers, so you can now remove these roles.
This change was introduced in …

Remove redundant `role` attributes from elements

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_contextual_breadcrumbs.html.erb
app/views/govuk_publishing_components/components/docs/contextual_breadcrumbs.yml

- Adds the component wrapper helper to the `contextual breadcrumbs` component.
As the [trello card](https://trello.com/c/7sAlXpYy/434-add-component-wrapper-helper-to-contextual-breadcrumbs-footer-and-sidebar-component) states:
None.

Use component wrapper on contextual breadcrumbs

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_contextual_sidebar.html.erb
app/views/govuk_publishing_components/components/docs/contextual_sidebar.yml

- Adds the component wrapper helper to the `contextual sidebar` component.
As the [trello card](https://trello.com/c/7sAlXpYy/434-add-component-wrapper-helper-to-contextual-breadcrumbs-footer-and-sidebar-component) states:
None.

Use component wrapper on contextual sidebar

---

CHANGELOG.md
config/locales/ar.yml

Correctly translate "Published" word to Arabic.
Before:
After:
Trello card: https://trello.com/c/NkLPasOt/3166-fix-arabic-translation-in-government-frontend

Fix Arabic translation for 'Published'

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/_breadcrumbs.scss
app/views/govuk_publishing_components/components/docs/breadcrumbs.yml

Style breadcrumbs in RTL (right-to-left) writing mode. [Trello](https://trello.com/c/6E5UoTiK/335-rtl-print-styles-have-been-considered-and-implemented-where-required)
Note that this CSS uses some "magic numbers" derived from the computed values for the `govuk-breadcrumbs` component.
This is part of the work to improve print styles more generally. 
The breadcrumb component had no support for RTL writing mode. The component was therefore incorrectly left aligned on pages in RTL languages.

Style breadcrumbs in RTL (right-to-left) writing mode

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/_metadata.scss

Improvements to the metadata component to improve RTL print styles.
This is part of the work to improve print styles more generally. [Trello](https://trello.com/c/6E5UoTiK/335-rtl-print-styles-have-been-considered-and-implemented-where-required)
_Note: This is a dependency of https://github.com/alphagov/government-frontend/pull/3404_
Some pages are broken for foreign languages that read right to left, with styles not set correctly for the changed direction.
| Before    | After |
| -------- | ------- |
| ![image](https://github.com/user-attachments/assets/8972f8bf-b926-448c-a79a-6600ef7f9865)  |![image](https://github.com/user-attachments/assets/6b91ba5f-2812-4cbb-a5a2-c061c75d1c50)  |

Improve metadata component to support RTL print styles

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Use component wrapper on contextual breadcrumbs ([PR #4560](https://github.com/alphagov/govuk_publishing_components/pull/4560))
* Use component wrapper on contextual sidebar ([PR #4561](https://github.com/alphagov/govuk_publishing_components/pull/4561))
* Correctly translate 'Published' word to Arabic ([PR #4563](https://github.com/alphagov/govuk_publishing_components/pull/4563))
* Style breadcrumbs in RTL (right-to-left) writing mode ([PR #4559](https://github.com/alphagov/govuk_publishing_components/pull/4559))
* Improve metadata component to support RTL print styles ([PR #4365](https://github.com/alphagov/govuk_publishing_components/pull/4365))
* Update organisation stylesheet ([PR #4565](https://github.com/alphagov/govuk_publishing_components/pull/4565))

Version 49.1.0

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_contextual_footer.html.erb
app/views/govuk_publishing_components/components/docs/contextual_footer.yml

- Adds the component wrapper helper to the `contextual footer` component.
As the [trello card](https://trello.com/c/7sAlXpYy/434-add-component-wrapper-helper-to-contextual-breadcrumbs-footer-and-sidebar-component) states:
None.

Use component wrapper on contextual footer

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_inset_text.html.erb
app/views/govuk_publishing_components/components/docs/inset_text.yml
spec/components/inset_text_spec.rb

Remove the shared helper from the inset text component. Specifically, this removes the `margin_top` option from the component.
I've checked the 14 applications this component is used in and as far as I can tell none of them were using the `margin_top` option, so this seems safe to remove.
We're trying to move some options out of the shared helper and into the component wrapper helper, as well as doing some cleanup, specifically to standardise our components to only use margin bottom. Removing this option from this component gets us one step closer to that goal.
Inset text had a default top margin of Design System spacing 6 applied through the shared helper but also has the same top margin from the Design System component styles, so removing this makes no visual difference.
Trello card: …

Remove shared helper from inset text component

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_button.html.erb
lib/govuk_publishing_components/presenters/button_helper.rb

Remove the shared helper from the button component, and copy a little bit of the shared helper code (for adding additional classes) into the button helper, so no resulting change in functionality.
We want to remove some options from the shared helper (specifically `classes` and `margin_bottom`) and put them in the component wrapper helper. Button was still reliant on the shared helper for `classes` but it proved impractical to add the component wrapper helper to it to replace this functionality (see https://github.com/alphagov/govuk_publishing_components/pull/4543). Instead, copy a little bit of the shared helper code for `classes` into the button helper, and remove the shared helper from the component.
None.
Trello card: https://trello.com/c/Y0pDWbHw/390-move-some-shared-helper-options-in …

Remove shared helper from button component

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/govspeak/_warning-callout.scss

Update Govspeak "Warning Text" component styles to extend the GOV.UK Frontend `govuk-warning-text__icon` styles.
See https://components-gem-pr-4487.herokuapp.com/component-guide/govspeak/warning_callout/preview
The left spacing between the icon and text appears to be excessive compared to both the [Warning Text component](https://components.publishing.service.gov.uk/component-guide/warning_text/default/preview) and its [Design System](https://design-system.service.gov.uk/components/warning-text/) equivalent

Update Govspeak "Warning Text" component styles

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_single_page_notification_button.html.erb
lib/govuk_publishing_components/presenters/single_page_notification_button_helper.rb
spec/components/single_page_notification_button_spec.rb
spec/javascripts/components/single-page-notification-button-spec.js

Refactor the markup of the single page notification button component slightly...
- move most of the component attributes (class, data attributes) to be handled by the component wrapper on the parent element
- remove the shared helper as not being used
- update the helper and tests to reflect this change
I've tested this with a branch on integration for https://www.gov.uk/guidance/check-if-an-email-youve-received-from-hmrc-is-genuine and it seems to behave as it did before, but it could use another pair of eyes (particularly from someone more familiar with this component).
This component was inconsistent because it was using the component wrapper helper but had its parent class (`gem-c-single-page-notification-button`) on a child element, rather than the parent. There seems to be no need …

Refactor single page notification component

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_print_link.html.erb
app/views/govuk_publishing_components/components/docs/print_link.yml
spec/components/print_link_spec.rb

- Adds the component wrapper to the print link component
- This is a breaking change, as it renames the `data_attributes` object that was used on child elements. This is not actually used across any templates currently, so it can be safely removed.
- Although this is a breaking change, it shouldn't affect any existing code on GOVUK.
As the [trello card](https://trello.com/c/T0F8HJwj/442-add-component-wrapper-helper-to-print-link-component) states:
Edited example titles/descriptions.

BREAKING Use component wrapper on print link component

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/_add-another.scss

This change wraps the styles for the "Add another" component in their parent class.
The change here raises the specificity of the component-specific styles so that they are not over-written by more generic styles on the page on which the component is rendered. This is demonstrated below on an implementation of the component on Mainstream Publisher:
- before this change the `margin-top` value of the "Delete" button is over-written by the value in the "Button" component
- after the change the value for `margin-top` is applied as expected.
|Before|After|
|-|-|
|![External-links-actual](https://github.com/user-attachments/assets/b7eee921-5313-422f-acec-9ffa13c4f409)|![External-links-expected](https://github.com/user-attachments/assets/6551d505-5136-48c3-bbed-0beaa0ca2a30)|

Make "Add another" component styles more specific

---

CHANGELOG.md
app/models/govuk_publishing_components/component_wrapper_helper_options.rb
app/views/govuk_publishing_components/components/_print_link.html.erb
app/views/govuk_publishing_components/components/docs/print_link.yml
spec/components/print_link_spec.rb

- removes the default margin top and the option to change the margin top from the print link component
- also removes the shared helper from the component, as this was the only thing it was used for
This seemed like it would be a big change but it turns out not so much, I don't think any changes to applications are needed to support this. Most print link components are already set to have a margin top of 0 or have an element above them with bottom margin, which overlaps with the top margin (and produces no or only a small visual difference with this change).
Exhaustive list of where we use the print link:
government-frontend
- [detailed guides](https://www.gov.uk/guidance/apply-for-an-electronic-travel-authorisation-eta) already set to margin top 0 so fine to change
- [printable versions …

Remove margin top from print link

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/_textarea.scss
app/views/govuk_publishing_components/components/_character_count.html.erb
app/views/govuk_publishing_components/components/_textarea.html.erb
app/views/govuk_publishing_components/components/docs/textarea.yml
spec/components/character_count_spec.rb
spec/components/textarea_spec.rb

Apply the component wrapper helper to the textarea component.
- breaking change, renames `id` option to `textarea_id` as this is applied to a child element and `id` is applied to the parent by the component wrapper
- removes the shared helper, instead relying on the component wrapper helper to provide the same functionality for `margin_bottom`
- removes a bit of code that sets the margin back to normal if an invalid value is passed, but this outcome is now handled by the component wrapper
To deal with this breaking change, other PRs will need to be raised in applications as follows ahead of deployment.
- collections-publisher https://github.com/alphagov/collections-publisher/pull/2373
- content-publisher https://github.com/alphagov/content-publisher/pull/3295
- govspeak-preview …

Add component wrapper helper to textarea

---

CHANGELOG.md
docs/component-wrapper-helper.md
lib/govuk_publishing_components/presenters/component_wrapper_helper.rb
spec/lib/govuk_publishing_components/components/component_wrapper_helper_spec.rb

Reduce the severity of the validation checking for `id` attributes passed to the component wrapper helper.
- previous validation was too strict, HTML5 valid characters in id attributes are almost anything
- validation now only complains if an id contains spaces, newlines or `.` characters
- `.` is technically allowed, but can lead to problems in testing as an id of `#id.stillid` could be mistakenly matched to an element with an id of `#id` and a class of `stillid`
The validation was based on HTML4, but HTML5 is a lot more relaxed: https://html.spec.whatwg.org/multipage/dom.html#global-attributes:the-id-attribute-2
None.
Trello card: https://trello.com/c/GQ1p2oSC/438-add-component-wrapper-helper-to-form-textarea-component

Change id validation on component wrapper

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Change id validation on component wrapper ([PR #4584](https://github.com/alphagov/govuk_publishing_components/pull/4584))

Version 50.0.1

---

CHANGELOG.md
app/assets/javascripts/govuk_publishing_components/analytics-ga4/ga4-search-tracker.js
docs/analytics-ga4/trackers/ga4-search-tracker.md
spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-search-tracker.spec.js

This change updates the behaviour of the `Ga4SearchTracker` module as follows:
- update the tracking to _always_ fire a `search` event when the form is submitted
- make the action of the `search` event dynamic
- update the logic to establish whether the user is searching vs filtering by checking which fields the user has interacted with (instead of checking if the keyword has changed), and set the event's action property accordingly
Now that we have collected a decent amount of tracking data on search across GOV.UK, we've come across a couple of trip hazards with the existing tracking. In particular:
- suppressing the event if the keyword hasn't changed is a bit brittle (and subtly buggy as we've forgotten to normalise the initial keyword in the JS component state)
- Relying on separate …

Improve GA4 search tracking

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/_inverse-header.scss
app/views/govuk_publishing_components/components/_inverse_header.html.erb
app/views/govuk_publishing_components/components/docs/inverse_header.yml
spec/components/inverse_header_spec.rb

Adds a `padding_top` and `padding_bottom` option to the inverse header component, as well as a `subtext` option.
- adds options to set the padding top/bottom on the component using the Design System spacing scale (from 0 to 9)
- removes the (undocumented) padding_top false option, which is used in a few places, but can be replaced with the new options
Component with custom padding:
Component with subtext. This is to support functionality on [HTML publications](https://www.gov.uk/government/publications/benefit-and-pension-rates-2025-to-2026/benefit-and-pension-rates-2025-to-2026). See commit message for details.
There was previously a `padding_top` option, but it was used only to remove the default padding top from the component. This was employed where the inverse header contained the …

Add custom padding to inverse header

---

app/views/govuk_publishing_components/audit/show.html.erb
app/views/govuk_publishing_components/component_guide/example.html.erb
app/views/govuk_publishing_components/component_guide/index.html.erb
app/views/govuk_publishing_components/component_guide/show.html.erb

Replaces the H1s rendered in the component guide by the title component with H1s rendered using the heading component.
Probably no need for a changelog entry as this is an internal change to the component guide.
These title components used the margin top option, which we're trying to remove (moving towards a world where components only have bottom margin).
Additionally we're trying to retire the title component, as the same functionality is provided by the heading component.
None.
Trello card: https://trello.com/c/Y0pDWbHw/390-remove-margintop-option-from-shared-helper

Replace title component with heading

---

CHANGELOG.md
app/assets/javascripts/govuk_publishing_components/components/add-another.js

This change updates a `querySelectorAll` call to be made on the module rather than the document. 
As it is this creates multiple "Delete" buttons if there are more than one instance of the component on the page (i.e. one per instance).

Add another: fix problem in `createRemoveButtons` method:

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/_title.scss
app/views/govuk_publishing_components/components/_title.html.erb
spec/components/title_spec.rb

- our spacing model is to apply margin bottom, so this is an anomaly
- replace margin_top with default padding on the component, so no visual changes
- margin_top option isn't widely used and can be replaced with alternatives, separate PRs will be raised
Applications that use this component, and their use of the `margin_top` option are:
- `collections` (changes covered in https://github.com/alphagov/collections/pull/3918) (done)
- `datagovuk_find` (no use of `margin_top` so no change required)
- `email-alert-frontend` (no use of `margin_top` so no change required)
- `feedback` (changes covered in https://github.com/alphagov/feedback/pull/2042) (done)
- `finder-frontend` (no use of `margin_top` so no change required)
- `frontend` (changes covered in …

Remove title component margin_top option

---

CHANGELOG.md
app/assets/javascripts/govuk_publishing_components/components/add-another.js
app/views/govuk_publishing_components/components/_add_another.html.erb
app/views/govuk_publishing_components/components/docs/add_another.yml
spec/components/add_another_spec.rb
spec/javascripts/components/add-another-spec.js

[Publishing Components Issue #4564](https://github.com/alphagov/govuk_publishing_components/issues/4564)
This adds some configuration to the ["Add another" component](https://components.publishing.service.gov.uk/component-guide/add_another) so that authors can choose how the component displays by default when it is rendered on a page and no content is provided to it.
The current default behaviour of the "Add another" component when it loads is to:
- display empty form fields where no content is provided
- not display a “Delete” button where a single instance of content is provided
There is a need to customise this behaviour for these scenarios when it is implemented on the Mainstream publisher app so that:
- no empty fields are displayed where no content is provided
- a "Delete" button is …

Add configuration to "Add another"

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Remove title component margin_top option ([PR #4508](https://github.com/alphagov/govuk_publishing_components/pull/4508))
* **BREAKING** Add global bar component from static ([PR #4538](https://github.com/alphagov/govuk_publishing_components/pull/4538))
* Add custom padding to inverse header ([PR #4590](https://github.com/alphagov/govuk_publishing_components/pull/4590))
* Add another: fix problem in createRemoveButtons method ([PR #4586 ](https://github.com/alphagov/govuk_publishing_components/pull/4586))
* Add configuration to "Add another" ([PR #4575](https://github.com/alphagov/govuk_publishing_components/pull/4575))

Release Version 51.0.0

---

app/views/govuk_publishing_components/components/docs/title.yml
lib/govuk_publishing_components/presenters/shared_helper.rb

Removes the `margin_top` option from the shared helper.
- should no longer be in use by any components
- moves us towards a world where components only have bottom margin
- also remove an example from the title component guide page that uses margin_top and is out of date
We want to have a standard model of only margin bottom on components.
None.
Trello card: https://trello.com/c/Y0pDWbHw/390-remove-margintop-option-from-shared-helper

Remove margin_top option from shared helper

---

CHANGELOG.md
app/views/govuk_publishing_components/components/docs/button.yml
lib/govuk_publishing_components/presenters/button_helper.rb
spec/components/button_spec.rb

This allows us to have a button outside a containing form element (see https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button#form) This is useful if we want to have two buttons in a form group next to one another inside a form group (for example if one form action submits the form and the other button submits to a form to delete the item that is being edited)

Add a `form` attribute to the button component

---

CHANGELOG.md
app/assets/javascripts/govuk_publishing_components/vendor/lux/lux-reporter.js

Update to LUX 4.0.29, following the instructions here: https://github.com/alphagov/govuk_publishing_components/blob/main/docs/real-user-metrics.md#how-to-update-to-a-new-version
I've tested this using the LUX debugging tool but strangely it reports a version number of 4.0.28 (the previous version) so not sure what's going on there.
We need to update to the latest version or this code will stop working.
None.

Update to LUX 4.0.29

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Update to LUX 4.0.29 ([PR #4597](https://github.com/alphagov/govuk_publishing_components/pull/4597))
* Add a `form` attribute to the button component ([PR #4588](https://github.com/alphagov/govuk_publishing_components/pull/4588))

Version 51.1.0

---

app/views/govuk_publishing_components/components/docs/big_number.yml

Big number uses the component wrapper helper, but was missing this line in the documentation that shows information about the wrapper in the component guide page for this component.
Details of the component wrapper options will now appear in the component guide page for big number.

Update big number documentation

---

app/assets/stylesheets/govuk_publishing_components/_all_components.scss

Add the Sass for the global banner component into all components sass.
Missed in https://github.com/alphagov/govuk_publishing_components/pull/4538
None.

Add global banner sass to all components sass

---

CHANGELOG.md
lib/govuk_publishing_components/presenters/shared_helper.rb
spec/lib/govuk_publishing_components/components/shared_helper_spec.rb

- Removes `shared_helper.classes` from the gem
- Correct me if I'm wrong but it doesn't seem to be used anywhere, so should be a simple removal
- Trello: https://trello.com/c/iMAtJbup/469-move-classes-option-into-component-wrapper
None

Remove classes functionality from shared helper

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/helpers/_markdown-typography.scss

Add `govuk-text-break-word` style to markdown links.
https://components-gem-pr-4603.herokuapp.com/component-guide/govspeak#how-it-looks
Enable long words or URLs to break and wrap onto a new line in Govspeak components.
https://www.gov.uk/guidance/local-authority-collected-waste-definition-of-terms

Add `govuk-text-break-word` style to markdown links

---

lib/govuk_publishing_components/presenters/checkboxes_helper.rb
spec/components/checkboxes_spec.rb

This removes the full stop from the default hint text for the component. 
This was raised in [this issue](https://github.com/alphagov/govuk_publishing_components/issues/4589) and makes this component consistent with the way hint text is presented in the Design System. 
|Before|After|
|-|-|
|![Screenshot 2025-02-04 at 15 58 19](https://github.com/user-attachments/assets/79c6a764-5737-4569-8c16-79c70e33e69d)|![Screenshot 2025-02-04 at 15 59 07](https://github.com/user-attachments/assets/9921c619-48fc-473e-962e-78fe70ea66e9)|

Remove full stop from default hint text in "Checkboxes" component

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_title.html.erb
docs/component_conventions.md
lib/govuk_publishing_components/presenters/shared_helper.rb
spec/components/title_spec.rb
spec/lib/govuk_publishing_components/components/shared_helper_spec.rb

- Removes `shared_helper.get_margin_bottom` from the gem
- As the `title` component still used`shared_helper.get_margin_bottom`, I added some specific code for `title` so that the change isn't breaking - the `title` component is being retired soon too.
- Updates the shared helper docs too. I was going to mark the shared helper as deprecated in the docs, but wasn't sure if that was true.
- Trello card https://trello.com/c/hnfXA4lu/471-move-marginbottom-option-into-component-wrapper
Should be none.

Remove margin bottom functionality from the shared helper

---

CHANGELOG.md
app/assets/stylesheets/component_guide/application.scss

- Make the padding around component previews `30px`
- Previously the padding was `30px` for the sides/bottom, and `45px` for the top
- This made testing spacing of components more confusing as the top always had more spacing around it.
- It looks like the previous padding was added 7.5 years ago to make it the same as GOVUK Elements, but we want the padding to be the same around the whole component to make the spacing of components easier to test. See trello card for sources: https://trello.com/c/pvbZKJJX/473-investigate-component-guide-example-vertical-spacing
- See https://components-gem-pr-4610.herokuapp.com/ for visual testing
None, surprisingly - I thought Percy would complain!

Make padding around component previews consistent

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Remove classes functionality from shared helper ([PR #4605](https://github.com/alphagov/govuk_publishing_components/pull/4605))
* Add govuk-text-break-word style to markdown links ([PR #4603](https://github.com/alphagov/govuk_publishing_components/pull/4603))
* Remove margin bottom functionality from shared helper ([PR #4608](https://github.com/alphagov/govuk_publishing_components/pull/4608))
* Make padding around component previews consistent ([PR #4610](https://github.com/alphagov/govuk_publishing_components/pull/4610))
* Bump govuk-frontend from 5.7.1 to 5.8.0 ([PR #4539](https://github.com/alphagov/govuk_publishing_components/pull/4539))

Version 51.2.0

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/helpers/_markdown-typography.scss

Add a margin bottom to govspeak `H2` elements.
- headings don't have margin bottom in govspeak, so rely on elements following them to have top margin for spacing
- when followed by an attachment, this is a problem because an attachment is a gem component and therefore doesn't have top margin
- solution is to add bottom margin to headings that does not exceed the top margin of other elements, so if both are present they will overlap without a visual difference
- but for attachments the space will be provided by this new bottom margin
- only doing this for H2 for now as this is the only example of this problem in the wild and I'm hesitant to make sweeping changes to govspeak
Before | After
Fixes https://github.com/alphagov/govuk_publishing_components/issues/4072

Fix spacing between govspeak headings and attachment

---

CHANGELOG.md
app/assets/javascripts/govuk_publishing_components/components/feedback.js
app/views/govuk_publishing_components/components/docs/feedback.yml
spec/javascripts/components/feedback-spec.js

- Removes some if statements that were for IE11 from our JS code
- Closes https://github.com/alphagov/govuk_publishing_components/issues/4350
- When viewing the diff, checking Hide Whitespace in the settings will make it easier to view the changes.
None.

Remove IE11 specific code from feedback.js

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Fix spacing between govspeak headings and attachment ([PR #4618](https://github.com/alphagov/govuk_publishing_components/pull/4618))
* Update LUX to v4.0.30 ([PR #4621](https://github.com/alphagov/govuk_publishing_components/pull/4621))
* Remove IE11 specific code from feedback.js ([PR #4622](https://github.com/alphagov/govuk_publishing_components/pull/4622))

Version 51.2.1

---

app/views/govuk_publishing_components/components/docs/govspeak.yml

Modify the govspeak component guide page YML to:
- add a new section showing a lot of the common govspeak elements together to demonstrate their spacing
- reorder all of the sections slightly more logically, based on alphabetic order and related items
We're looking at changing the spacing model within govspeak styles, and these changes will make it easier to compare before and after once those changes are ready.
Changes in https://github.com/alphagov/govuk_publishing_components/pull/4623
See component guide page.
Trello card: https://trello.com/c/IGbGxOO6/481-standardise-govspeak-element-spacing

Change the govspeak component guide documentation page

---

app/views/govuk_publishing_components/components/_layout_for_public.html.erb
app/views/govuk_publishing_components/components/layout_for_public/_account-layout.html.erb
spec/components/layout_for_public_spec.rb

- Add tests to ensure that for_static: true results in a main element, false results in an absence.
- Additionally, fix some tests that would always pass
Currently the for_static: false value if called for the account layout won't skip the main element in the same way the non-account layouts do. This leads to double main element in no-slimmer apps that use the account layout.
No visual changes expected.

Make account layout respect for static

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/_layout-super-navigation-header.scss
app/views/govuk_publishing_components/components/_layout_super_navigation_header.html.erb
app/views/govuk_publishing_components/components/docs/layout_super_navigation_header.yml
app/views/govuk_publishing_components/components/layout_for_public/_layout_super_navigation_header_homepage.html.erb
spec/components/layout_super_navigation_header_spec.rb

Removed the 1px left border style, and the `hide_button_left_border` option from the super navigation menu component.
- To align the menu button styling on gov.uk with the styling used on the gov.uk homepage
- The `hide_button_left_border` option is no longer as it is now removed by default
[Trello card](https://trello.com/c/2xMlOLhe/3289-remove-hidebuttonleftborder-from-the-menu-in-the-super-navigation-header)
- Live preview before - https://components.publishing.service.gov.uk/component-guide/layout_super_navigation_header/default/preview
- Live preview after - https://components-gem-pr-4631.herokuapp.com/component-guide/layout_super_navigation_header/default/preview
The failing visual regression tests in Percy are expected, screenshots of how the changes will appear on GOV.UK are …

Remove left border from the super nav menu button

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_add_another.html.erb
app/views/govuk_publishing_components/components/docs/add_another.yml

- Adds the component wrapper helper to the `add another` component.
- Trello card: https://trello.com/c/QSiP4Bw6/495-add-component-wrapper-to-add-another-component
None.

Use component wrapper on 'add another' component

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_layout_for_public.html.erb
app/views/govuk_publishing_components/components/docs/layout_for_public.yml
spec/components/layout_for_public_spec.rb

**Breaking**: Removes support for the `custom_header` and `custom_layout` options from layout_for_public view template, these options were originally created for and only used by GOV.UK Chat.
These options only appeared to be used by GOV.UK Chat, searching GitHub for `custom_layout` and `custom_header` only returns results for the govuk_publishing_components repo:
- https://github.com/search?q=org%3Aalphagov+%3Acustom_header&type=code
- https://github.com/search?q=org%3Aalphagov+custom_layout&type=code
This PR essentially reverts the changes made in https://github.com/alphagov/govuk_publishing_components/pull/4004
[Trello card](https://trello.com/c/aKklGLh5/3302-remove-customheader-option-from-govuk-publishing-components)
These options are no longer required, GOV.UK Chat now uses a custom …

Remove `custom_header` and `custom_layout` options

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Make account layout respect `for_static` ([PR #4630](https://github.com/alphagov/govuk_publishing_components/pull/4630))
* Remove left border from the super nav menu button ([PR #4631](https://github.com/alphagov/govuk_publishing_components/pull/4631))
* Use component wrapper on 'add another' component ([PR #4632](https://github.com/alphagov/govuk_publishing_components/pull/4632))
* Use component wrapper on 'copy to clipboard' component ([PR #4633](https://github.com/alphagov/govuk_publishing_components/pull/4633))
* **BREAKING** Remove custom_header and custom_layout options ([PR #4635](https://github.com/alphagov/govuk_publishing_components/pull/4635))

Version 52.0.0

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/_inset-text.scss
app/views/govuk_publishing_components/components/_inset_text.html.erb
spec/components/inset_text_spec.rb

- Swap the margin top on this component for padding as we're trying to standardise the top/bottom spacing on components. 
- Trello card: https://trello.com/c/tpFgf7uM/498-investigate-margin-top-on-inset-text-component
- This required nesting the component in a `<div>`, as we can't change the padding directly on the existing component, as the current `padding` here is used for the `border-left` effect where the border is taller than the text content. Therefore, padding had to be added to a new parent component so that the new padding doesn't affect how the component itself looks and ensures it's just used for spacing.
- You can compare the spacing with the live component: https://components.publishing.service.gov.uk/component-guide/inset_text/preview vs …

Swap inset text top margin with padding

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_table.html.erb
app/views/govuk_publishing_components/components/docs/table.yml
lib/govuk_publishing_components/app_helpers/table_helper.rb
spec/lib/govuk_publishing_components/app_helpers/table_helper_spec.rb

- Adds a `margin_bottom` option to the `table` component
- This is needed so that we can set the `margin_bottom` to 0 where this component is nested within another component (as parent components should control all of the `margin_bottom`, not child components that render inside them)
- Usually we would add the component wrapper helper to achieve this, as that helper includes `margin_bottom` functionality, but here that isn't easy due to how the component is architected. Therefore, I've added setting margin bottom as it's own option to the component.
- This is a pre requisite to completing this trello card: https://trello.com/c/Q4quM0zo/500-fix-calendar-component-margin
- Test link: https://components-gem-pr-4638.herokuapp.com/component-guide/table/with_custom_margin_bottom
None - though …

Allow margin bottom to be configured on the table component

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Swap inset text top margin with padding ([PR #4634](https://github.com/alphagov/govuk_publishing_components/pull/4634))
* Allow margin bottom to be configured on the table component ([PR #4638](https://github.com/alphagov/govuk_publishing_components/pull/4638))

Version 52.1.0

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/_layout-super-navigation-header.scss

The search button had in its default unopened state an unintended 1px dark navy bottom border. The colour change to navy was made in https://github.com/alphagov/govuk_publishing_components/pull/2413 and the colour wasn't updated when the header design subsequently changed.
This changes the bottom border to a transparent colour, instead of removing it, so that when user changes the default colours of their browser such as in Firefox, or uses Windows High Contrast mode, the button still has a visual bottom border.
The change doesn't impact the current homepage header which continues to set its own brighter blue bottom border.
The bottom dark navy border isn't part of the intended design for the search button.
https://components-gem-pr-4642.herokuapp.com/public
Fixes …

 Fix bottom border colour issue in the super nav search button

---

CHANGELOG.md
app/assets/stylesheets/component_guide/application.scss
app/assets/stylesheets/govuk_publishing_components/components/helpers/_markdown-typography.scss

- `govuk-gutter` seems to be an old variable that was used before spacing was moved to use `govuk-spacing`and `govuk-responsive-margin`.
- Therefore, this PR changes any reference to `govuk-gutter` to `govuk-spacing`.
- `govuk-gutter` equals a fixed `30px`. Therefore we can use `govuk-spacing(6)` instead, and have no visual changes. 
- `govuk-gutter-half` can be changed to `govuk-spacing(3)` which are both `15px`.
- This also replaces `$gutter-two-thirds: $govuk-gutter - calc($govuk-gutter / 3);` with `govuk-spacing(4)` as that mathematical equation equals `20px` i.e. `(30 - (30/3)) = 20`. `govuk-spacing(4)`  is `20px`.
- This also deletes a `.component-doc-h3` class that is not used anywhere.
- See https://github.com/alphagov/govuk-frontend/blob/4faad64a3af93ad5d96f2c9de78b5cc7140df70f/pa …

Use govuk-spacing instead of govuk-gutter

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/_search.scss
app/views/govuk_publishing_components/components/_search.html.erb
app/views/govuk_publishing_components/components/_search_with_autocomplete.html.erb
app/views/govuk_publishing_components/components/docs/search_with_autocomplete.yml
spec/components/search_with_autocomplete_spec.rb

- The `search with autocomplete` component is a simple component that renders the `search` component inside of it.
- The `search` component had a hardcoded 30px margin bottom in its SASS, but weirdly can be overridden as the `search` component has the component wrapper helper on it. This is what is happening on production with 2 out of 3 of the `search with autocomplete` renders currently, as they are passing a 0 margin_bottom on the homepage in `frontend`, and on the `finder-frontend` search results page.
- However having this hardcoded default margin bottom is probably not ideal, as ideally the parent component (`search with autocomplete`) should always be in control of the margin bottom that it is rendering on the page.
- The `search with autocomplete` component is also a bit unique …

Ensure 'search with autocomplete' component uses its own margin bottom

---

Gemfile.lock
govuk_publishing_components.gemspec
spec/spec_helper.rb

There's currently no code coverage (only locale coverage in the gem), so add simplecov. We'll turn on branch coverage reporting for better coverage, but won't specify a minimum coverage yet.
It's useful to have code coverage to ensure that rare paths in the code are being exercised. 
No visual changes (in fact, no external changes, this only affects CI and local testing).

Add simplecov to test code coverage of test suite

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* **BREAKING:** Remove title component ([PR #4653](https://github.com/alphagov/govuk_publishing_components/pull/4653))
* Fix bottom border colour issue in the super nav search button ([PR #4642](https://github.com/alphagov/govuk_publishing_components/pull/4642))
* Use govuk-spacing instead of govuk-gutter ([PR #4650](https://github.com/alphagov/govuk_publishing_components/pull/4650))
* Ensure 'search with autocomplete' component uses its own margin bottom ([PR #4637](https://github.com/alphagov/govuk_publishing_components/pull/4637))
We know that in static there's [a line that will need to be removed when we bump the gem](https://github.com/alphagov/static/blob/ffa7fba8bed9156f36b29e20657fa773dff907e5/app/assets/stylesheets/application.scss#L20). govuk-chat also needs a manual update, Ash …

Version 53.0.0

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/_attachment.scss
app/assets/stylesheets/govuk_publishing_components/components/govspeak/_attachment.scss
app/views/govuk_publishing_components/components/_govspeak.html.erb

- govspeak attachment sass included all necessary attachment component sass files in order to render any attachment components within govspeak
- this was done before our per-page asset model, which meant that these styles were always compiled into the govspeak sass regardless of whether they were already included on the page
- moving them out of the sass and into the view for the govspeak component means they are now included in the per-page asset handling and can be de-duplicated
- this only impacts pages where attachment components are present alongside govspeak containing attachments, which probably isn't that many, but it makes the sass handling more transparent and included in our general approach
- some extra sass is now required in the attachment component to prevent overrides, …

Move govspeak attachment sass includes into view

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_layout_for_public.html.erb
app/views/govuk_publishing_components/components/docs/layout_for_public.yml
spec/components/layout_for_public_spec.rb
spec/dummy/app/views/layouts/dummy_public_layout.html.erb

- Remove the layout_header component from the layout_for_public view template
- Update layout_for_public tests:
- Removed test for `show_explore_header` as this option is no longer available in layout_for_public
- Removed tests for `show_search` and `product_name` options, these were only required when `layout_header` was included in layout_for_public. The same tests are included in [layout_header.spec.rb](https://github.com/alphagov/govuk_publishing_components/blob/main/spec/components/layout_header_spec.rb)
[Trello card](https://trello.com/c/qE79TFYj/3303-remove-legacy-header-variants-from-layoutforpublic)
To help keep provide a consistent experience when navigating GOV.UK.
The layout_header component is only used by [/service-manual](https://www.gov.uk/service-manual) and …

BREAKING: Remove layout_header component from layout_for_public

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/_govspeak-html-publication.scss
app/assets/stylesheets/govuk_publishing_components/components/govspeak/_attachment.scss
app/assets/stylesheets/govuk_publishing_components/components/govspeak/_call-to-action.scss
app/assets/stylesheets/govuk_publishing_components/components/govspeak/_contact.scss
app/assets/stylesheets/govuk_publishing_components/components/govspeak/_example.scss
app/assets/stylesheets/govuk_publishing_components/components/govspeak/_footnotes.scss
app/assets/stylesheets/govuk_publishing_components/components/govspeak/_form-download.scss
app/assets/stylesheets/govuk_publishing_components/components/govspeak/_highlight-answer.scss
app/assets/stylesheets/govuk_publishing_components/components/govspeak/_images.scss
app/assets/stylesheets/govuk_publishing_components/components/govspeak/_information-callout.scss
app/assets/stylesheets/govuk_publishing_components/components/govspeak/_legislative-list.scss
app/assets/stylesheets/govuk_publishing_components/components/govspeak/_media-player.scss
app/assets/stylesheets/govuk_publishing_components/components/govspeak/_place.scss
app/assets/stylesheets/govuk_publishing_components/components/govspeak/_stat-headline.scss
app/assets/stylesheets/govuk_publishing_components/components/govspeak/_steps.scss
app/assets/stylesheets/govuk_publishing_components/components/govspeak/_tables.scss
app/assets/stylesheets/govuk_publishing_components/components/govspeak/_typography.scss
app/assets/stylesheets/govuk_publishing_components/components/govspeak/_warning-callout.scss
app/assets/stylesheets/govuk_publishing_components/components/helpers/_markdown-typography.scss

Change the govspeak CSS model from a margin top and bottom approach to a margin bottom only approach.
Trying to keep visual changes to a minimum but some small changes are likely, particularly as this change will include switching to `govuk-spacing()` for many margins instead of using `em` values.
To do:
- check appearance of many page types with changes
- check contents of main component govspeak sass, and govspeak html publication sass
- check with govspeak preview, and see how dependency works
- is govspeak previewed in any publishing interfaces?
For reference, I've checked these changes in the following page types. While there are minor differences I don't think there are any problems.
- news article (e.g. https://www.gov.uk/government/news/10-things-to-love-about-us)
- publication …

Change govspeak spacing model

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_cookie_banner.html.erb
spec/components/cookie_banner_spec.rb

- The cookie banner's `/help/cookies` link was a relative link
- Therefore on `assets.publishing.service.gov.uk` it would link to `assets.publishing.service.gov.uk/help/cookies` which is incorrect
- Therefore, use our existing `absolute links helper` workaround, which converts relative links to absolute ones
- This will make it link to `www.gov.uk/help/cookies`
- This fix already exists on the header and footer links on the assets domain, for example https://assets.publishing.service.gov.uk/media/6784f6eff029f40e508816d9/List_of_.gov.uk_domain_names_as_of_13_January_2025.csv/preview - you can see those links go to `www.gov.uk` so it will work similarly for the `help/cookies` link.
None.

Make /help/cookies link in cookie banner absolute instead of relative

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Change govspeak spacing model ([PR #4623](https://github.com/alphagov/govuk_publishing_components/pull/4623))
* Move govspeak attachment sass includes into view ([PR #4659](https://github.com/alphagov/govuk_publishing_components/pull/4659))
* **BREAKING:** Remove layout_header component from layout_for_public ([PR #4643](https://github.com/alphagov/govuk_publishing_components/pull/4643))
* Make /help/cookies link in cookie banner absolute instead of relative ([PR #4664](https://github.com/alphagov/govuk_publishing_components/pull/4664))

Version 54.0.0

---

CHANGELOG.md
docs/set-up-individual-component-css-loading.md
lib/govuk_publishing_components/app_helpers/asset_helper.rb
lib/govuk_publishing_components/config.rb
spec/dummy/app/views/layouts/asset_helper_layout.html.erb
spec/features/asset_helper_spec.rb
spec/lib/govuk_publishing_components/app_helpers/asset_helper_spec.rb

Add an option to supply a custom css exclude list - this is like the current list that excludes anything always supplied by static from the individual component support, but for non-static based apps, where they might as a stopgap want to provide their own application.css with a hardcoded list of styles to include, but that might not be the same list as static's list.
Also mild refactoring of the asset helper to improve test coverage.
To support a bundled set of stylesheets for email-alert-frontend, as here: https://github.com/alphagov/email-alert-frontend/pull/1890.
https://trello.com/c/O6JhukLu/487-remove-slimmer-email-alert-frontend
None.

Add custom css exclude list to Asset Helper

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/_attachment.scss
app/views/govuk_publishing_components/components/_attachment.html.erb
spec/components/attachment_spec.rb

Adjust the margins on the attachment component so that the component has a default margin bottom set on the outer element, rather than controlled by the bottom margins of inner elements sticking out.
Also make the attachment thumbnails a bit smaller on mobile.
Trying to make the component margin spacing more consistent and this relates to that work. This will also improve the spacing around attachments when included inside govspeak.
Also fixes https://github.com/alphagov/govuk_publishing_components/issues/4662
Margin bottom spacing changes (blue and red outlines have been added only to clarify boundaries of the component).
Before | After
Spacing when attachments contain a details element.
Before | After
Improved spacing shown in govspeak:
Size of attachment …

Adjust attachment component spacing

---

app/views/govuk_publishing_components/components/_feedback.html.erb

- defining a method inside a partial like this causes the method to be potentially defined multiple times, and causes `covered` to complain when running test suites in apps that use the gem.
- ...and in fact the method isn't really needed. It's checking if the thing to be encoded is a string, but it's being called only twice, with the output of a gsub (which by definition returns a string). So it'll always be a string, and always can just be passed to #encode.

Remove utf_encode method

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/govspeak/_legislative-list.scss
app/views/govuk_publishing_components/components/docs/govspeak.yml

Fix the appearance of legislative lists on pages like https://www.gov.uk/guidance/immigration-rules/immigration-rules-introduction (see the 'interpretation' section).
Have also updated the component guide to include a more detailed example of a legislative list, hopefully so any future changes will be caught by the visual diff.
This was accidentally broken in https://github.com/alphagov/govuk_publishing_components/pull/4623
Before | After

Fix govspeak legislative lists styles

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/_search.scss
app/views/govuk_publishing_components/components/_search.html.erb
app/views/govuk_publishing_components/components/docs/search.yml
spec/components/search_spec.rb

Remove search `large-mobile` option
https://trello.com/c/2WuCz8Wg/3350-remove-the-large-mobile-option-from-the-search-component

Remove search `large-mobile` option

---

app/assets/stylesheets/govuk_publishing_components/components/_search.scss

Update search (homepage option) background colour
https://trello.com/c/9DdIRxZY/3287-draft-homepage-changes

Update search homepage config background colour

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/_search.scss
app/views/govuk_publishing_components/components/_search.html.erb
app/views/govuk_publishing_components/components/docs/search.yml
spec/components/search_spec.rb

Remove the `no_border` option from the search component
https://trello.com/c/RSta9bQP

Remove the `no_border` option from the search component

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/_all_components.scss
app/assets/stylesheets/govuk_publishing_components/components/_summary-banner.scss
app/views/govuk_publishing_components/components/_summary_banner.html.erb
app/views/govuk_publishing_components/components/docs/summary_banner.yml
spec/components/summary_banner_spec.rb
spec/lib/govuk_publishing_components/app_helpers/asset_helper_spec.rb

- Migrates the [banner component from government-frontend](https://govuk-government-frontend.herokuapp.com/component-guide/banner) to this gem
- I've renamed it from `Banner` to `Summary banner`, as there are already multiple banners in this gem so it felt wrong for it to have a generic name.
- Trello card: https://trello.com/c/eF1B4BDf/513-migrate-government-frontend-components-to-the-gem
There should be none across `government-frontend` and this gem.
You can compare here: [government-frontend preview](https://govuk-government-frontend.herokuapp.com/component-guide/banner/preview) and [gem preview](https://components-gem-pr-4681.herokuapp.com/component-guide/summary_banner/preview)

Migrate banner component from government-frontend as 'Summary banner'

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Remove search large-mobile option ([PR #4682](https://github.com/alphagov/govuk_publishing_components/pull/4682))
* Add back to top link component from government-frontend ([PR #4666](https://github.com/alphagov/govuk_publishing_components/pull/4666))
* Add back to top link component translations ([PR #4689](https://github.com/alphagov/govuk_publishing_components/pull/4689))
* Remove IE8 support from action-link component ([PR #4690](https://github.com/alphagov/govuk_publishing_components/pull/4690))
* **BREAKING** Remove search from the layout header component ([PR #4687](https://github.com/alphagov/govuk_publishing_components/pull/4687))
* Remove the `no_border` option from the search component ([PR #4693](https://github.com/alphagov/govuk_publishing_components/pull/4693))
* Migrate …

Release version 55.0.0

---

app/assets/images/govuk_publishing_components/action-link-arrow--light.svg

Update Action link component light icon style from `#eeefef` to `#f3f3f3` (black tint 95%).
https://trello.com/c/NMwcObnm/3345-update-variant-of-action-link-component-to-align-with-branding

Update action link light icon style

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/govspeak/_footnotes.scss

- On [this page in production](https://www.gov.uk/government/publications/independent-investigation-of-the-nhs-in-england/independent-investigation-of-the-national-health-service-in-england-accessible-version) the footnotes are being covered by another element once the footnote number exceeds `100`.
- This is because the list styles act similar to `absolute` positioning, so the numbers are not being factored in to the `<ol>` element width.
- I did try to fix this by using `list-style-position: inside`, which would make the list styles act like `position: relative`, but this caused issues with the list item content itself as long URLs would then need `display: inline-block` to sit on the same line as the numbers - which then affected the positioning of the `↩` link.
- Therefore, I've added …

Shift footnotes above 100/1000 further to the left

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Shift footnotes above 100/1000 further to the left ([PR #4705](https://github.com/alphagov/govuk_publishing_components/pull/4705))
* Delete unused CSS from layout super navigation component ([PR #4702](https://github.com/alphagov/govuk_publishing_components/pull/4702))

Release version 55.0.1

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/_organisation-logo.scss

- Currently custom organisation logos are rendering at a large size on multiple organisation pages. These include:
- https://www.gov.uk/government/organisations/defence-equipment-and-support
- https://www.gov.uk/government/organisations/forensic-science-regulator
- https://www.gov.uk/government/organisations/sellafield-ltd
- https://www.gov.uk/government/organisations/national-data-guardian
- https://www.gov.uk/government/organisations/government-chemist
- https://www.gov.uk/government/organisations/subsidy-advice-unit
- Any organisation can suffer from this issue if they add a large "Featured" document to their page, as that seems to alter the spacing a logo gets to render in. For example, the [UK Space Agency](https://webarchive.nationalarchives.gov.uk/ukgwa/20250305161148/https://www.go …

Limit organisation logos to 320px/240px width

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/_layout-super-navigation-header.scss
app/views/govuk_publishing_components/components/_layout_super_navigation_header.html.erb

Remove the call to `add_gem_component_stylesheet("layout-header")` and import the styles required from the design system directly in `_layout-super-navigation-header.scss`.
[Trello card](https://trello.com/c/lAZzmCG9)
The super navigation layout header component is dependant on the styles from the `header` component in the design system and only needs the styles to ensure the logo is rendered correctly.
The `layout-header` component from the gem not only imports the `header` styles from the design system, but also lots of other components such as `search`, `skip-link` and `tag`, these styles are not required to render the super navigation component.

Update styles dependency in super navigation component

---

CHANGELOG.md
app/views/govuk_publishing_components/components/feedback/_survey_signup_form.html.erb
spec/components/feedback_spec.rb

- Adds `requires JavaScript` text to the `feedback` component smartsurvey link that appears when you select 'No' on the 'Is this page useful?' 
- Context: https://trello.com/c/V7mSQffS/530-fix-feedback-without-javascript
Adds some extra text.
|---|---|
| <img width="973" alt="image" src="https://github.com/user-attachments/assets/fde2e75a-30b4-4dde-9e64-619167abf1d4" /> | <img width="973" alt="image" src="https://github.com/user-attachments/assets/3db36483-ee81-463e-9c76-4bb8e1646fd5" /> |

Add 'requires JavaScript' text to feedback component survey link

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Limit organisation logos to 320px/240px width ([PR #4708](https://github.com/alphagov/govuk_publishing_components/pull/4708))
* Update styles dependency in super navigation component ([PR #4709](https://github.com/alphagov/govuk_publishing_components/pull/4709))
* Add 'requires JavaScript' text to feedback component survey link ([PR #4710](https://github.com/alphagov/govuk_publishing_components/pull/4710))
* Bump govuk-frontend from 5.8.0 to 5.9.0 ([PR #4677](https://github.com/alphagov/govuk_publishing_components/pull/4677))

Release version 55.1.0

---

app/models/govuk_publishing_components/audit_comparer.rb

- removes this app from the list that use static, because it no longer does
Component guide auditing now looks slightly different for this app, but no real changes.
Before
After

Update auditing for email-alert-frontend

---

docs/testing-components.md

Update the testing components documentation to:
- Fix the broken links for JavaScript modules docs and to `component_guide_test.rb`
- Fix markdown linting errors
Help ensure documentation is up-to-date and works as expected.

Fix broken links and markdown linting errors

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_select.html.erb
app/views/govuk_publishing_components/components/docs/select.yml
spec/components/select_spec.rb

This PR:
* Provides the ability for data attributes to be passed to the `<select>` elements rendered by the select component (See commit 2ae88ad78ee7bfd5dfb0ffb93e6836e435cd252b)
* Updates a pre-existing test description to make it clear it tested for the ability to add data attributes to the `<option>` elements
To enable the provision of data attributes relied on by JavaScript analytics tracking in Whitehall (see related PR below)
This PR visually changes the component guide to provide an example 
<details>
<summary>Screenshot</summary>
</details>
* https://github.com/alphagov/whitehall/pull/10069

Add data attributes to `<select>` elements within the Select component

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/_attachment.scss
app/assets/stylesheets/govuk_publishing_components/components/_govspeak.scss
app/assets/stylesheets/govuk_publishing_components/components/govspeak/_attachment.scss
app/assets/stylesheets/govuk_publishing_components/components/govspeak/_call-to-action.scss
app/assets/stylesheets/govuk_publishing_components/components/govspeak/_charts.scss
app/assets/stylesheets/govuk_publishing_components/components/govspeak/_footnotes.scss
app/assets/stylesheets/govuk_publishing_components/components/govspeak/_fraction.scss
app/assets/stylesheets/govuk_publishing_components/components/govspeak/_information-callout.scss
app/assets/stylesheets/govuk_publishing_components/components/govspeak/_typography.scss
app/assets/stylesheets/govuk_publishing_components/components/govspeak/_warning-callout.scss
app/views/govuk_publishing_components/components/docs/govspeak.yml

This PR moves specific govspeak print styles into their corresponding sass files (as opposed to being in the parent govspeak sass file).
Additionally, a general review of the govspeak print styles has been included in this PR and any issues/redundancies have been fixed/removed. I also came across a few things during the review that I thought I'd enquire about - I've posted the questions on the [trello card](https://trello.com/c/utTxlaKP/531-restructure-and-fix-govspeak-print-styles).
[Trello card](https://trello.com/c/utTxlaKP/531-restructure-and-fix-govspeak-print-styles)

Fix govspeak print styles

---

CHANGELOG.md
app/assets/javascripts/govuk_publishing_components/vendor/lux/lux-reporter.js

Update LUX to 4.0.32.
None.
Parsed debug output (14 events)
```
0 ms: Navigation started at 24/03/2025 10:53:10
2,841 ms: lux.js v4.0.32 is initialising. Hover to view configuration.
2,842 ms: POST beacon initialised.
2,842 ms: Sample rate is 1%. This session is not being sampled.
2,842 ms: Onload handler was triggered after 2842 ms.
2,842 ms: lux.js has finished initialising.
2,968 ms: LUX.addData("http-protocol", "http/1.1")
2,986 ms: Received layout shift at 2981 ms with value of 0.001
2,988 ms: Received paint entry at 2988 ms
2,988 ms: Received paint entry at 2988 ms
3,076 ms: Received layout shift at 3076 ms with value of 0.006
3,090 ms: Received LCP entry at 3088 ms
3,126 ms: Received layout shift at 3125 ms with value of 0.006
5,912 ms: Unload handler was triggered.
5,912 ms: This …
```

Update LUX to 4.0.32

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/_heading.scss
app/assets/stylesheets/govuk_publishing_components/components/_metadata.scss

This PR fixes the following print styles:
- Inverse heading print styles: previously, the inverse heading was not visible in print as it was rendering white text on a white background - this PR changes the text colour to black (this should fix the issue in the metadata component where this problem was originally identified)
- Metadata component print styles: the inverse version of the metadata component introduces additional spacing however this additional spacing is unnecessary in print and therefore it has been removed
[Trello card](https://trello.com/c/t7PaPZd9/547-improvements-for-print)
| Inverse heading print styles - before | Inverse heading print styles - after |
|------------------------------------------|----------------------------------------|
| …

Fix print styles

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/govspeak/_typography.scss
app/views/govuk_publishing_components/components/docs/govspeak.yml

Fix the appearance of govspeak blockquotes, primarily to remove the negative left margin that means blockquotes escape from their parent element as shown below (red outline added for clarity)
Example in the wild on this page, note how the `cite` element is sticking out to the left: https://www.gov.uk/government/history/10-downing-street
I've also fixed a few other things (see commits for details) and generally tried to clean up and simplify these styles.
As often happens, I was working on something else and noticed that this was a bit broken.
Before | After

Fix govspeak blockquotes

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/_attachment.scss
app/views/govuk_publishing_components/components/docs/attachment.yml

Update the [attachment component](https://components.publishing.service.gov.uk/component-guide/attachment) to:
- Use the `govuk-text-break-word` mixin from the design system to forcibly break URLs across multiple lines when they wouldn't otherwise fit, moved to `.gem-c-attachment__metadata` to ensure the fix works as expected in IE11
- Update the external attachment example to reference the word break helper used from the design system, the hyphens have been removed from the url text to capture any visual regression issues in the future
By aligning our approach with the design system, we will benefit from any future updates to the [word break helper](https://github.com/alphagov/govuk-frontend/blob/main/CHANGELOG.md#stop-long-words-breaking-out-of-components-with-govuk--text-break-word). …

Use govuk-frontend mixin on attachment URL text

---

CHANGELOG.md
app/assets/javascripts/govuk_publishing_components/analytics-ga4/pii-remover.js
spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-core.spec.js
spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-page-views.spec.js
spec/javascripts/govuk_publishing_components/analytics-ga4/pii-remover.spec.js

- Adds national insurance redaction to the GA4 PII remover so that it doesn't have to be redacted further down the line
- The regex I wrote is based partly on this guidance https://www.gov.uk/hmrc-internal-manuals/national-insurance-manual/nim39110 and https://github.com/alphagov/govuk-chat-private-beta/blob/2add98c736e68f630d825cbbf00e1db11a42e68d/app/validators/pii_validator.rb#L27
- For the tests I wrote some code to randomly generate numbers, just so we aren't actually storing any in the code.
- Trello card: https://trello.com/c/ndiVNNuG
None.

Add NI numbers to GA4 PII redaction

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Fix govspeak blockquotes ([PR #4739](https://github.com/alphagov/govuk_publishing_components/pull/4739))
* Fix govspeak print styles ([PR #4730](https://github.com/alphagov/govuk_publishing_components/pull/4730))
* Update LUX to 4.0.32 ([PR #4725](https://github.com/alphagov/govuk_publishing_components/pull/4725))
* Fix print styles ([PR #4738](https://github.com/alphagov/govuk_publishing_components/pull/4738))
* Use govuk-frontend mixin on attachment URL text ([PR #4737](https://github.com/alphagov/govuk_publishing_components/pull/4737))
* Add NI numbers to GA4 PII redaction ([PR #4732](https://github.com/alphagov/govuk_publishing_components/pull/4732))

Release Version 56.1.0

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_cookie_banner.html.erb
spec/javascripts/components/cookie-banner-spec.js

Fix HTML validation bug in cookie banner
See [https://validator.w3.org HTML checker results](https://validator.w3.org/nu/?doc=https%3A%2F%2Fcomponents-gem-pr-4743.herokuapp.com%2Fcomponent-guide%2Fcookie_banner%2Fdefault%2Fpreview)
https://github.com/alphagov/govuk_publishing_components/issues/3559.
Additionally, the change aligns with the Design System implementation; see https://design-system.service.gov.uk/components/cookie-banner/default/.

Fix HTML validation bug in cookie banner

---

CHANGELOG.md
app/assets/javascripts/govuk_publishing_components/components/service-navigation.js
app/assets/stylesheets/govuk_publishing_components/_all_components.scss
app/assets/stylesheets/govuk_publishing_components/components/_service-navigation.scss
app/views/govuk_publishing_components/components/_service_navigation.html.erb
app/views/govuk_publishing_components/components/docs/service_navigation.yml
spec/components/service_navigation_spec.rb
spec/lib/govuk_publishing_components/app_helpers/asset_helper_spec.rb

Add Service navigation component
**Review URL**: https://components-gem-pr-4731.herokuapp.com/component-guide/service_navigation
The `product name` and `navigation_items` options are now deprecated features of GOV.UK Frontend. These features are used by various GOV.UK apps (see publishing and utility apps).
The Service navigation component is recommended to show your service name and navigation links instead of the GOV.UK header. See https://design-system.service.gov.uk/components/header/#previous-variants-of-the-govuk-header.
https://trello.com/c/f27IC8zY/3387-create-service-navigation-component
The Cross service (One Login) header component closely resembles the implementation of the Service navigation component, as much of it is derived from the One Login header component. See …

Add service navigation component

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_summary_banner.html.erb
spec/components/summary_banner_spec.rb

Use the title text of the summary banner as the accessible label for the summary banner which is used as the label for the landmark region, by adding an aria-labelledby and link it to the summary banner title ID. Since we have no unique ID to use, use an approach similar to the notice and password input components to generate a unique ID for the title.
[Trello](https://trello.com/c/165G7d6U/3360-investigate-and-fix-accessibility-issues-on-the-gem-summary-banner-component)
We currently use the same aria-label value ("notice") on the summary banner as is already used by the notice component. This doesn't comply with the ARIA authoring practise for each landmark to have a unique label, since the notice and the summary banner often appear on the same page. The current value "notice" also …

Add a more descriptive accessible label to summary banner

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Fix HTML validation bug in cookie banner ([PR #4743](https://github.com/alphagov/govuk_publishing_components/pull/4743))
* Add service navigation component ([PR #4731](https://github.com/alphagov/govuk_publishing_components/pull/4731))
* Add a more descriptive accessible label to summary banner ([PR #4742](https://github.com/alphagov/govuk_publishing_components/pull/4742))

Release 56.2.0

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/govspeak/_typography.scss
app/views/govuk_publishing_components/components/docs/govspeak.yml

- a recent change omitted opening quote marks from multi line blockquote paragraphs that weren't the first paragraph
- GOV.UK content style is that all paragraphs in a blockquote should start with an opening quote, and only the final paragraph should end with a closing quote: https://www.gov.uk/guidance/style-guide/a-to-z#quotes-speech-marks
All paras in a blockquote should now have an opening quote mark. Only the final one should have a closing quote mark.

Adjust govspeak blockquotes quote marks

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Adjust govspeak blockquotes quote marks ([PR #4755](https://github.com/alphagov/govuk_publishing_components/pull/4755))
* Add an aria-label to the devolved nations component ([PR #4751](https://github.com/alphagov/govuk_publishing_components/pull/4751))

Version 56.2.1

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/_layout-super-navigation-header.scss

- Fix the super navigation menu styling when JavaScript is not available by making the changes below:
- Add the missing right border to the menu link (the same as when JS is enabled)
- Update the link padding used for the large variation
- Remove the blue background from the search icon link, the search icon now only has a blue background when used on the blue background variation of the super nav menu
- Fix the search button width by updating the width from `50px` to `51px`, and `68px` to `69px` for desktop devices
- The search icon width is set to `21px`, and has `15px` of left and right padding by default, `51px` in total
- The large-navbar variation of the search toggle button has `24px` of padding to the left and right, 69px in total
- Fix the search button height when used on the …

Fix super navigation menu styling

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Fix super navigation menu styling ([PR #4744](https://github.com/alphagov/govuk_publishing_components/pull/4744))

Version 56.2.2

---

CHANGELOG.md
app/views/govuk_publishing_components/components/_table.html.erb
app/views/govuk_publishing_components/components/docs/table.yml
lib/govuk_publishing_components/app_helpers/table_helper.rb
spec/components/table_spec.rb
spec/lib/govuk_publishing_components/app_helpers/table_helper_spec.rb

This enhances the `table` component with the ability to give columns a specific width by assigning the header cell a width override class from the width scale as suggested by the [upstream table component].
This is useful when:
* the width of a column is always static and less than the automatically inferred width (for example, a set of action links or buttons), or
* a certain column often contains long and/or irregular content, throwing the visual balance of the table out of whack
[upstream table component]: https://design-system.service.gov.uk/components/table/
[upstream table component]: https://design-system.service.gov.uk/components/table/

Table: add ability to specify column width

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/_layout-super-navigation-header.scss

- Updated the styles in the super navigation menu to ensure the "Menu" and "Search" toggle buttons use a consistent approach
- Fix an issue where the hover styles would stick when toggling a menu button in the super navigation menu on touchscreen devices
- https://trello.com/c/6YteIa3f/687-top-nav-hover-state-doesnt-disappear-on-touch-screens
The styling of the "Search" button toggle states have been updated to align with the approach used in the "Menu" toggle button: 
- Now uses the `pseudo-underline` mixin instead of applying `border-bottom`
- Styles are now applied on all screen sizes, not just desktop
- Added/updated comments to clearly indicate the purpose of each section of code
- Update Sass variables to be more descriptive and consistent with existing variable names
Using the same …

Update super navigation menu button toggle states

---

CHANGELOG.md
app/assets/javascripts/govuk_publishing_components/analytics-ga4/ga4-core.js
spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-ecommerce-tracker.spec.js

`populateEcommerceSchema` can populate the `item_name` of the fired event data with a data attribute (`data-ga4-ecommerce-item-name`) assigned to the clicked target or the text of the clicked target if the data attribute is not defined.
There are instances in which the link being clicked might not have text which describes the item it is associated with. In whitehall and other publishing applications, the search results are in a table and the link can be one of several to be displayed depending on the user and the content. This is also in line with the other attributes of the event data that can be set using data attributes.

`populateEcommerceSchema` can use `data-ga4-ecommerce-item-name`

---

CHANGELOG.md
app/assets/javascripts/govuk_publishing_components/lib/govspeak/youtube-link-enhancement.js
app/views/govuk_publishing_components/components/docs/govspeak.yml
spec/javascripts/govuk_publishing_components/lib/govspeak/youtube-link-enhancement-spec.js

- A user reported that a YouTube link they had added to their `govspeak` content was replacing a whole paragraph of their content with our JS YouTube embed, even though they added `data-youtube-player="off"` to the link.
- This has surfaced an issue where paragraphs on pages are being replaced entirely when cookies are disabled.
- There are two reasons for this:
- Firstly, in general we don't have a check in place to stop paragraphs being replaced when a YouTube link is in a paragraph containing other content. The YouTube link enhancement works by replacing the entire paragraph it's in with the enhancement, but it should only do this if the YouTube link is the only thing in the paragraph. Therefore, there's a risk that bugs (like this one) end up replacing page content.
- More …

Stop YouTube links being enhanced when they shouldn't

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Stop YT links being enhanced when they shouldn't ([PR #4798](https://github.com/alphagov/govuk_publishing_components/pull/4798))

Release version 56.3.1

---

CHANGELOG.md
app/assets/javascripts/govuk_publishing_components/analytics-ga4/ga4-form-tracker.js

`getInputValues` checks if the option of a `select` at `selectedIndex` exists before accessing `value`.
If `Ga4FormTracker` ran `getInputValues` on a form with an unselected select, then it would cause an error (as the `selectedIndex` would be equal to `-1`).

`Ga4FormTracker` handles `selectedIndex` of `-1`

---

CHANGELOG.md
app/assets/javascripts/govuk_publishing_components/analytics-ga4/ga4-page-views.js
spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-page-views.spec.js

Add additional meta tags for tracking in `PageViewTracker`.
These meta tags are used in `page_view` events in publishing applications.

Extra meta tags for `PageViewTracker`

---

package.json
yarn.lock

Bump govuk frontend to 5.10.1
https://trello.com/c/OtRpnkGg/3473-upgrade-to-govuk-frontend-v5101

Bump govuk frontend to 5.10.1

---

CHANGELOG.md
app/assets/javascripts/govuk_publishing_components/lib/govspeak/youtube-link-enhancement.js
app/views/govuk_publishing_components/components/docs/govspeak.yml
spec/javascripts/govuk_publishing_components/lib/govspeak/youtube-link-enhancement-spec.js

- There are a couple of edge cases in our YouTube embed code which this PR addresses.
- The first one was the result of something I introduced in https://github.com/alphagov/govuk_publishing_components/pull/4798. In this PR, I made it so that a YouTube link would only enhance into an embed if the YouTube link was the only thing within a `<p>` tag. This was because of a bug on production that was replacing content with YouTube embeds, so this was added as a safety check.
-  However, there's a use case where editors have a `<p>` that contains a YouTube link and punctuation only. Therefore the existence of the punctuation meant that the safety code was triggerring, and therefore the YouTube link was not turning into an embed. Therefore, I've fixed this by removing punctuation entirely when …

Fix edge cases with YouTube link enhancement JS

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* `Ga4FormTracker` handles `selectedIndex` of `-1` ([PR #4803](https://github.com/alphagov/govuk_publishing_components/pull/4803))
* Extra meta tags for `PageViewTracker` ([PR #4804](https://github.com/alphagov/govuk_publishing_components/pull/4804/))
* Fix edge cases with YouTube link enhancement JS ([PR #4808](https://github.com/alphagov/govuk_publishing_components/pull/4808))

Release version 56.3.2

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* **BREAKING:** Upgrade cross service header to v3.0.0 ([PR #4811](https://github.com/alphagov/govuk_publishing_components/pull/4811/))

Version 57.0.0

---

CHANGELOG.md
app/assets/javascripts/govuk_publishing_components/analytics-ga4/ga4-copy-tracker.js
docs/analytics-ga4/trackers/ga4-copy-tracker.md
spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-copy-tracker.spec.js

- `Ga4CopyTracker` will not track an event if `data-ga4-no-copy` set on parent node of element
- Add new `data-ga4-no-copy` test for `Ga4CopyTracker`
- Updae `Ga4CopyTracker` docs with this change
`Ga4CopyTracker` is initialised in `load-analytics.js`, so including this file in an application means copy tracking is always enabled. This commit adds support for marking an element with `data-ga4-no-copy` which will prevent copy tracker for that element and it's children.

Add support for exceptions to `Ga4CopyTracker`

---

CHANGELOG.md
docs/analytics-ga4/middleware.md
lib/govuk_publishing_components/middleware/ga4_optimise.rb
spec/lib/govuk_publishing_components/middleware/ga4_optimise_middleware_spec.rb

Optimise GA4 Attributes by removing unnecessary escaping (useful when not using Slimmer). 
Because the process by which Slimmer stitches together templates from static with views from the apps involves a complete parse of both sets of HTML into a nokogiri tree, then writing out that tree as HTML after manipulation, it optimises GA4 data attributes slightly - replacing the double-quotes around the attribute with single quotes, so that the double quotes in the JSON inside the attribute don't need to be escaped. Without this, the generated HTML can be up to 2 kB larger when Slimmer is not involved.
For apps without slimmer, we can replicate this with a lighter-weight middleware that only needs to be included on non-slimmer apps, using regex and gsub/sub to perform a similar optimisation in …

Add middleware to optimise GA4 Attributes by reducing unnecessary escaping

---

app/assets/stylesheets/govuk_publishing_components/components/_feedback.scss
app/assets/stylesheets/govuk_publishing_components/components/_layout-super-navigation-header.scss
app/assets/stylesheets/govuk_publishing_components/components/_search.scss
app/assets/stylesheets/govuk_publishing_components/govuk_frontend_support.scss

Replace use of tint mixins with hex variables
Dart Sass 1.79.0 introduced support for CSS Color Level 4 color spaces. Consequently, the `govuk-tint` mixin now outputs rgb values with floating-point precision, leading to unsupported property value warnings in some browsers, such as Safari 11.1.1. To maintain compatibility, we're defining equivalent hex colour values as variables instead.

Replace use of tint mixins with hex variables

---

app/assets/stylesheets/govuk_publishing_components/components/_layout-super-navigation-header.scss

- Update the search toggle button styles
- left and right padding increased from `15px` to `20px`
- the color of the "X" is now govuk-blue the same as the "menu" button in the open state
- includes the pseudo-underline in the open state
- Fix the `:focus` style in browsers that do not support `:focus-visible`
- Fix styles when JS is not available
-  only the `:focus` pseudo-class is used on the super navigation menu links
- `:focus-visible` is now only used when JS is available on the super navigation buttons
- Some refactoring to make it easier to maintain and updates the super navigation menu styles in the future
- The pseudo-underline that appears beneath the menu buttons/links are have been updated to have consistent left and right values 
The search toggle button styles are now …

Update super nav button styles

---

CHANGELOG.md
app/assets/javascripts/govuk_publishing_components/analytics-ga4/ga4-core.js
app/assets/javascripts/govuk_publishing_components/analytics-ga4/ga4-event-tracker.js
app/assets/javascripts/govuk_publishing_components/components/reorderable-list.js
app/views/govuk_publishing_components/components/_reorderable_list.html.erb
app/views/govuk_publishing_components/components/docs/reorderable_list.yml
spec/components/reorderable_list_spec.rb
spec/javascripts/components/reorderable-list-spec.js
spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-event-tracker.spec.js

Track when an item in the Reorderable List component is moved by button click or drag using `Ga4EventTracker`
- `ReorderableList` adds `ga4-event-tracker` to `data-module` and `data-ga4-event` data attribute to buttons unless `disable_ga4` is set to true
- Update documentation to include `disable_ga4` attribute
- Add `getTargetDatasetSchema` to `Ga4EventTracker` to grab updated data attributes of a tracked element without the component JS needing to parse, amend and then rewrite the `data-ga4-event` attribute with each change to indexing
- `ReorderableList.updateOrderIndexes` now updates `data-index` of each item for event tracking
- Add `onEnd` event listener to `ReorderableList` to trigger `Ga4EventTracker` to record drag and drop event
As part of adding tracking to publishing …

Add tracking to `ReorderableList`

---

CHANGELOG.md
app/assets/javascripts/govuk_publishing_components/components/add-another.js
app/views/govuk_publishing_components/components/_add_another.html.erb
app/views/govuk_publishing_components/components/docs/add_another.yml
spec/javascripts/components/add-another-spec.js

Adds tracking to the `AddAnother` component
- `disable_ga4` option added to disable the GA4 attributes being added
- If enabled `AddAnother` will add `data-ga4-event` data attributes to the `Add` and `Remove` buttons
As part of adding GA4 Tracking to components used in Publishing applications.

Add tracking to `AddAnother`

---

CHANGELOG.md
app/assets/javascripts/govuk_publishing_components/analytics-ga4/pii-remover.js
docs/analytics-ga4/pii-remover.md
spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-core.spec.js
spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-page-views.spec.js
spec/javascripts/govuk_publishing_components/analytics-ga4/pii-remover.spec.js

- Adds phone numbers to our GA4 PII redaction. 
- This includes four different regexes:
- UK Mobile numbers `e.g. 07...`
- UK Mobile numbers with the international code `+44`, which causes the first `0` in the mobile number to be dropped (`e.g. +447...`)
- UK Landline numbers  `e.g. 020...`
- UK Landline numbers with the international code `+44`, which causes the first `0` in the phone number to be dropped (`e.g. +4420...`)
- I have these separate as I found combining the UK number/international regexes together led to an incorrect scenario where `+440...` is valid when it shouldn't be, so it was easier to separate them out.
- Trello card: https://trello.com/c/V7q79XLH
None.

Add phone numbers to GA4 PII redaction

---

CHANGELOG.md
app/assets/javascripts/govuk_publishing_components/analytics-ga4/ga4-form-tracker.js
docs/analytics-ga4/trackers/ga4-form-tracker.md
spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-form-tracker.spec.js

New functionality and adjustments to the `Ga4FormTracker` submit tracking
- Change the `Ga4FormTracker` spec to be more DRY and easier to add tests to
- Support for adding labels to the `text` of the event fired (if `data-ga4-form-record-json` set), updated docs to reflect change
- Option to use character count instead of `[REDACTED]` for text fields (if `data-ga4-form-use-text-count` set), updated docs to reflect change
- Takes into account conditional fields (if conditional checkbox not checked, don't include conditional fields)
As part of adding tracking to Publishing Applications. Forms are more complex than those on GOV.UK and Smart Answers, so we need additional information included on a form submit to be able to get useful insights.

Add extra functionality to `trackFormSubmit` of `Ga4FormTracker`

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Fix welsh translations of Devolved Nations component ([PR #4807](https://github.com/alphagov/govuk_publishing_components/pull/4807))
* Add tracking to `ReorderableList` ([PR #4835](https://github.com/alphagov/govuk_publishing_components/pull/4835))
* Add tracking to `AddAnother` ([PR #4836](https://github.com/alphagov/govuk_publishing_components/pull/4836))
* Add phone numbers to GA4 PII redaction ([PR #4840](https://github.com/alphagov/govuk_publishing_components/pull/4840))
* Add image functionality to the intervention banner ([PR #4845](https://github.com/alphagov/govuk_publishing_components/pull/4845))
* Add extra functionality to trackFormSubmit of Ga4FormTracker ([PR #4847](https://github.com/alphagov/govuk_publishing_components/pull/4847/))
* Add /csv-preview/ path to GA4 …

Version 57.2.0

---

spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-auto-tracker.spec.js
spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-copy-tracker.spec.js
spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-core.spec.js
spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-ecommerce-tracker.spec.js
spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-event-tracker.spec.js
spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-finder-tracker.spec.js
spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-focus-loss-tracker.spec.js
spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-form-tracker.spec.js
spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-link-tracker.spec.js
spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-print-intent-tracker.spec.js
spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-schemas.spec.js
spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-scroll-tracker.spec.js
spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-smart-answer-results-tracker.spec.js
spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-video-tracker.spec.js
spec/javascripts/helpers/SpecHelper.js

Move repeatedly defined helper functions and variables to `SpecHelper.js`
- Assign `agreeToCookies` to `this` in the Jasmine context, remove all definitions of `agreeToCookies` in individual specs
- Assign `denyCookies` to `this` in the Jasmine context, remove all definitions of `denyCookies` in individual specs 
- Use the `gem_version` that's assigned in the `beforeAll` of `SpecHelper.js`
- Set `window.GOVUK.analyticsGa4.vars.gem_version` to `aGemVersion` (which is used in all specs) in `beforeAll` 
- Update `scroll-tracker.spec.js` to use `aGemVersion` (only test that uses `gem-version` for `gem_version`)
- Remove stubs or assignments to `window.GOVUK.analyticsGa4.vars.gem_version` in specs
- Not needed because `window.GOVUK.analyticsGa4.vars.gem_version` is set before each test
Easy to …

Use helpers in Jasmine specs

---

CHANGELOG.md
app/assets/javascripts/govuk_publishing_components/analytics-ga4/ga4-specialist-link-tracker.js
spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-specialist-link-tracker.spec.js

- The previous PR https://github.com/alphagov/govuk_publishing_components/pull/4859 did not seem to work for fixing preview link tracking
- I think this has something to do with hardcoding the domain in the check. This is flawed anyway, as it means the tracking wouldn't work on integration / locally.
- Instead, just check for  the existence of `/csv-preview/` in the href
- Have tested this locally in `government-frontend` and it works
- Trello card: https://trello.com/c/Ka9dd8VG
None.

Fix GA4 tracking for asset preview links

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Add more options to the select component ([PR #4858](https://github.com/alphagov/govuk_publishing_components/pull/4858))
* Fix GA4 tracking for asset preview links ([PR #4863](https://github.com/alphagov/govuk_publishing_components/pull/4863))

Release version 57.3.0

---

app/views/govuk_publishing_components/components/docs/organisation_logo.yml

Fix HM Prison Service logo url in the organisation component docs
The logo was recently updated and the old logo removed
The visual [change shown in Percy for the HM Prison Service is expected](https://percy.io/55ba5e1a/web/govuk_publishing_components/builds/41133573/changed/2207436785?browser=firefox&browser_ids=65&group_snapshots_by=similar_diff&subcategories=unreviewed%2Cchanges_requested&utm_source=github_status_public&viewLayout=overlay&viewMode=new&width=1280&widths=375%2C1280) as the logo now loads again

Fix HM Prison Service logo url

---

CHANGELOG.md
app/assets/javascripts/govuk_publishing_components/lib/govspeak/youtube-link-enhancement.js
spec/javascripts/govuk_publishing_components/lib/govspeak/youtube-link-enhancement-spec.js

- YouTube recently added an ?si= parameter that I believe is used to track who clicks a link that you've shared. This broke our YouTube embed code as their `?si=` value isn't an actual query parameter (As that would be `&si=`), so our code to grab the video id broke as it was counting `?si=[text]` as part of the ID.
- Therefore, remove `?si=[text]` entirely from the URL before working with the URL
- More specifically, this PR:
- Creates a `sanitiseVideoId` function (mainly so it can be easily tested)
- Adds some regex to remove the any extra parameter that can appear
- Also adds a slight enhancement by using `.trim()` when checking the govspeak HTML syntax is correct (so that line breaks/empty spaces in the paragraph of the link don't cause the YouTube link enhancement to break)
- Some …

Fix extra data in YouTube URLs breaking embeds

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Fix extra data in YouTube URLs breaking embeds ([PR #4882](https://github.com/alphagov/govuk_publishing_components/pull/4882))
* Fix `ReorderableList` tracking on drag and drop ([PR #4886](https://github.com/alphagov/govuk_publishing_components/pull/4886))

Version 57.3.1

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/govspeak/_contact.scss
app/views/govuk_publishing_components/components/docs/govspeak.yml

When adding lists inside contact blocks, they render with bullets and padding, because the styling is overriden by the govspeak styles (see https://github.com/alphagov/govuk_publishing_components/blob/f80f91c7d19422e8a15f43cf4850b6d039d54d01/app/assets/stylesheets/govuk_publishing_components/components/helpers/_markdown-typography.scss#L74)
After some discussion, we’ve decided that the simplest thing to do is to update the list styles within contacts to remove the list styling and margin/padding.
I've also added an example to the docs.

Render contact block lists without decoration

---

CHANGELOG.md
app/assets/javascripts/govuk_publishing_components/components/add-another.js
app/views/govuk_publishing_components/components/_add_another.html.erb
spec/javascripts/components/add-another-spec.js

Adds `index-start` and `index-section-count` options to the `AddAnother` tracking.
Allows overriding the default indexing behaviour, if the indexing should be a continuation of surrounding content of the page.

Add extra options to `AddAnother` component tracking

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/govspeak/_typography.scss

Ensures the quotation marks are in the correct position for right-to-left languages by using the default styles in place for left-to-right languages and flipping them.
Example page: https://www.gov.uk/government/news/foreign-secretary-statement-on-the-situation-in-el-fasher-sudan-24-april-2025.ar
The quotation marks are currently in the wrong position and in some cases overlaps with the content.
[Trello card](https://trello.com/c/pcldgiOm/1977-quotation-marks-on-arabic-pages-govt-agency-general-issue)
- Quotation marks now appear in the correct position
- Spacing is now consistent with the default styles in place for left-to-right languages, this has led to:
- a `10px` increase in spacing to the right of the block quote on desktop
- a `5px` decrease in spacing to the right of the block …

Fix quotation marks for right-to-left languages

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/govspeak/_contact.scss

At the moment, Content Blocks that render individual telephone objects are still showing with the label and phone number adjacent to each other as they’re not wrapped in a `.content` div. This reduces the specificity of the selector, so the phone numbers appear correctly.
There should be no difference in the Govspeak output as it stands, but just for visibility, I've added some screenshots:

Reduce specificity of `.email-url-number` rules

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Fix `AddAnother` `ga4_start_index` bug ([PR #4900](https://github.com/alphagov/govuk_publishing_components/pull/4900))
* Fix super navigation toggle border styling ([PR #4894](https://github.com/alphagov/govuk_publishing_components/pull/4894))
* Fix quotation marks for right-to-left languages ([PR #4903](https://github.com/alphagov/govuk_publishing_components/pull/4903))
* Reduce specificity of .email-url-number rules ([PR #4906](https://github.com/alphagov/govuk_publishing_components/pull/4906))

Version 58.1.1

---

CHANGELOG.md
app/assets/images/select-with-search/cross-icon.svg
app/assets/javascripts/govuk_publishing_components/components/select-with-search.js
app/assets/stylesheets/govuk_publishing_components/_all_components.scss
app/assets/stylesheets/govuk_publishing_components/components/_select-with-search.scss
app/assets/stylesheets/govuk_publishing_components/components/_select.scss
app/views/govuk_publishing_components/components/_select.html.erb
app/views/govuk_publishing_components/components/_select_with_search.html.erb
app/views/govuk_publishing_components/components/docs/select.yml
app/views/govuk_publishing_components/components/docs/select_with_search.yml
govuk_publishing_components.gemspec
lib/govuk_publishing_components.rb
lib/govuk_publishing_components/presenters/select_helper.rb
lib/govuk_publishing_components/presenters/select_with_search_helper.rb
package.json
spec/components/select_spec.rb
spec/components/select_with_search_spec.rb
spec/javascripts/components/select-with-search-spec.js
spec/lib/govuk_publishing_components/app_helpers/asset_helper_spec.rb
spec/lib/govuk_publishing_components/presenters/select_with_search_helper_spec.rb
yarn.lock

Add the Select With Search component to govuk_publishing_components.
The Select With Search component is an autocomplete select replacement that supports selecting multiple choices. [Accessible Autocomplete](https://github.com/alphagov/accessible-autocomplete) does not support multiple choices so previously the now deprecated [Accessible Autocomplete Multiselect](https://github.com/alphagov/accessible-autocomplete-multiselect) was used.
This component uses [Choices](https://github.com/Choices-js/Choices). It is progressively enhanced, so if it fails to load or Javascript is disabled then [the Select component](https://design-system.service.gov.uk/components/select/) will be rendered.
This PR moves the code from https://github.com/alphagov/select-with-search-component and makes some …

Add Select with Search component

---

app/views/govuk_publishing_components/components/docs/signup_link.yml
app/views/govuk_publishing_components/components/docs/single_page_notification_button.yml
app/views/govuk_publishing_components/components/docs/subscription_links.yml

- mostly removing margin_bottom examples, as these are already covered by the standard options detailed from the component wrapper
- also some rewording improvements
None.
Relates to https://github.com/alphagov/govuk_publishing_components/issues/4912

Remove redundant documentation

---

CHANGELOG.md
app/assets/images/govuk_publishing_components/action-link-arrow--dark.svg
app/assets/images/govuk_publishing_components/action-link-arrow--simple-light.svg
app/assets/images/govuk_publishing_components/action-link-arrow.svg
app/assets/stylesheets/govuk_publishing_components/components/_action-link.scss
app/views/govuk_publishing_components/components/_action_link.html.erb
app/views/govuk_publishing_components/components/docs/action_link.yml
spec/components/action_link_spec.rb

Review link: https://components-gem-pr-4915.herokuapp.com/component-guide/action_link
- Set the `light_icon` icon option as the new default
- Remove all 'yellow' variants
- Remove all 'dark' variants
- Remove other unused options for `nowrap_text`, `subtext`, `subtext_href`, `mobile_subtext`, `simple_light_arrow`.
https://trello.com/c/iiekbtY8/3561-updates-to-the-action-link-component 
Remove unused options
<table>
<tr>
<th>Before</th>
<th>After</th>
</tr>
<tr>
<td valign=top>
</td>
<td valign=top>
</td>
</tr>
</table>
Although some options have been removed and `light_icon` is now the default, this change is not breaking for any applications that use the old options. Non existent options are simply ignored, and the default is applied instead.
That said, we should clean up the unused …

Action link component updates

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/_select-with-search.scss

Fix the background colour of the `search-with-select` component so that it always renders in white.
In Specialist Publisher the `select-with-search` component sometimes appears on a grey background. Due to the missing white background, the component rendered with a transparent background allowing the grey to show through.
This was due to a Sass compilation error leaving the Sass declaration in the compiled CSS, thus generating an invalid rule:
| --- | ----------- |
| <img width="766" height="205" alt="image" src="https://github.com/user-attachments/assets/34566f86-f3f3-4214-be33-00f6c6db1c25" /> | <img width="766" height="205" alt="image" src="https://github.com/user-attachments/assets/f737d556-3148-43e2-bd60-b391da84f8b0" /> |

Fix broken background colour on `select-with-search` component

---

CHANGELOG.md
lib/govuk_publishing_components/presenters/single_page_notification_button_helper.rb
spec/components/single_page_notification_button_spec.rb
spec/lib/govuk_publishing_components/presenters/single_page_notification_button_helper_spec.rb

- following on from the work in https://github.com/alphagov/govuk_publishing_components/pull/4910 to allow the single page notification button component to allow a boolean true as well as a string true, now remove the ability for it to recognise a string true for the skip_account option
- skip_account should only be a boolean true, not a string "true"
None.
Trello card: https://trello.com/c/LTS5YNJS/725-fix-skipaccount-handling-in-components-gem

Change skip_account to only accept a boolean

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/_select-with-search.scss

Fix opacity issue on first selected item in choices.js dropdown.
Note that there are some accessibility issues with the repetition of 'Select One' which we will be addressing in a future update. A previous PR attempted an unsuccessful fix: https://github.com/alphagov/govuk_publishing_components/pull/4921
The first item in a "select one" variant of the `select-with-search` component is ghosted out due to inheriting the 50% opacity of the placeholder item.
| --- | ----------- |
| <img alt="" src="https://github.com/user-attachments/assets/ca5ab006-122c-4b13-a31f-9f54ee8c9322" /> | <img alt="" src="https://github.com/user-attachments/assets/82d9e087-a8e0-4882-8f36-ef08b9d0c467" /> |

[WHIT-2318] Fix opacity issue on first selected item in choices.js dropdown

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/govspeak/_contact.scss

Override the browser default of italics for `<address>` in govspeak. This impacts addresses on pages like [this one](gov.uk/contact-electoral-registration-office?postcode=SW1A+2AA).
The original rule was removed [here](https://github.com/alphagov/frontend/pull/4632/commits/60fb79436b6e31d7b7d4decf4bd9c7814fe8e17c). 
I discussed making this change with Keith who confirmed that just targeting the class `.govspeak .address` is correct, even though the removed the CSS rule targeted the `<address>` element. 
(Next steps: right now, govspeak doesn't automatically produce an `<address>` tag, so the change in this PR will only impact pages like the above electoral registration one that have the `<address>` tag manually added - however, the publishing team will amend the govspeak generator so that …

Override the browser default of italics for <address> in govspeak

---

app/assets/stylesheets/component_guide/application.scss
app/assets/stylesheets/govuk_publishing_components/components/_attachment.scss
app/assets/stylesheets/govuk_publishing_components/components/_layout-super-navigation-header.scss
app/assets/stylesheets/govuk_publishing_components/components/_modal-dialogue.scss
app/assets/stylesheets/govuk_publishing_components/components/_print-link.scss
app/assets/stylesheets/govuk_publishing_components/components/_search.scss
app/assets/stylesheets/govuk_publishing_components/components/_secondary-navigation.scss
app/assets/stylesheets/govuk_publishing_components/components/_single-page-notification-button.scss
app/assets/stylesheets/govuk_publishing_components/components/govspeak/_charts.scss
app/assets/stylesheets/govuk_publishing_components/components/mixins/_grid-helper.scss

- updates some outdated syntax for colour adjustment
- declarations like `@include` have to come after other lines, otherwise the compiler complains
Moving some of these rules around caused a little bit of breakage when for some elements when focussed and hovered, should be correct now, but worth checking those states when reviewing.
Issues found as part of https://github.com/alphagov/govuk_publishing_components/pull/4931 but splitting them out into their own PR to get them done quicker.
Hopefully none.
Trello card: https://trello.com/c/8vKVSmVz/764-switch-from-import-to-use-in-sass-compilation

Fix miscellaneous sass compilation warnings

---

CHANGELOG.md
app/assets/javascripts/govuk_publishing_components/components/add-another.js
app/views/govuk_publishing_components/components/_add_another.html.erb
app/views/govuk_publishing_components/components/docs/add_another.yml
spec/javascripts/components/add-another-spec.js

We want to make sure that if the content added to the DOM by the add another component has any JS modules associated with it, that these are initialised when the content is added. To achieve this, we can call `GOVUK.modules.start` after the fieldset has been added.
However, for our select with search module, this didn't work when we were removing the empty fieldset from the DOM and then cloning it and reinstating it to the DOM when the "Add another" button was clicked. It failed because ChoicesJS believed it was already initialised for that fieldset.
To work around this, we use a template element containing the empty fieldset. The template is not part of the DOM, so Choices is not initialised on page load as it is for the empty fieldset in the DOM. Now when the user clicks the add another …

Use a template element to build new fieldsets for the add another component

---

app/assets/stylesheets/component_guide/application.scss
app/models/govuk_publishing_components/component_doc.rb
app/views/govuk_publishing_components/components/docs/cross_service_header.yml
app/views/govuk_publishing_components/components/docs/layout_footer.yml
app/views/govuk_publishing_components/components/docs/layout_header.yml
app/views/govuk_publishing_components/components/docs/layout_super_navigation_header.yml
app/views/govuk_publishing_components/components/docs/service_navigation.yml
app/views/layouts/govuk_publishing_components/application.html.erb
docs/testing-components.md
spec/component_guide/audit_applications_spec.rb
spec/component_guide/component_preview_spec.rb
spec/dummy/app/views/components/_test_component_using_full_page_width.html.erb
spec/dummy/app/views/components/docs/test_component_using_full_page_width.yml

- Add support for using full width containers on component preview pages
- Update the components below to use full width layout on the preview page
- layout_super_navigation_header
- layout_header
- layout_footer
- service_navigation
- cross-service-header
- Update the preview page spacing to ensure the components accurately reflect how they will appear when used in application without any other stying applied
The main motivation for this change is to fix an issue on the [super navigation component preview page](https://components.publishing.service.gov.uk/component-guide/layout_super_navigation_header/preview) where the logo and menu button appear to overlap as shown in the screenshot below:
This can cause unexpected issues in Percy as it is set to take mobile screenshots at a width of …

Add support for using full width containers on component preview pages

---

CHANGELOG.md
app/views/govuk_publishing_components/components/feedback/_problem_form.html.erb
app/views/govuk_publishing_components/components/feedback/_survey_signup_form.html.erb

DAC has reported an issue where the H3 headings "Help us improve GOV.UK" on the feedback component might appear subordinate to previous, unrelated H2 headings on the page. 
The component does have its own H2 "Is this page useful?" but this is hidden when one of the H3 headings on the feedback component is unhidden.
The change in this PR doesn't result in any visual changes. 
I've tested the change on NVDA + Chrome and JAWS + Chrome, as well as Mac Voiceover and have not seen any issues. 
It should also be safe to assume that this change will not cause any issues with the existing heading hierarchy on pages where the feedback component appears since the default heading on the component has always been a H2, we've ran this past our content designer who agrees with this.
Our accessibility …

Make H3's on the feedback component into H2's to avoid them appearing subordinate to unrelated headings

---

app/views/govuk_publishing_components/components/docs/govspeak.yml

Add text to the govspeak component doc page to attribute the use of some classes in the govspeak examples to the microformat specification.
I just learned that's what these classes are for, and there's no documentation that explains this.
None.

Update govspeak documentation

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/_layout-header.scss

Remove unused imports in `layout-header.scss`
Fixes: https://github.com/alphagov/govuk_publishing_components/issues/4967
The layout header component does not use the components below:
- skip-link component - imported separately, [example in whitehall](https://github.com/alphagov/whitehall/blob/6229ac511a0d454dbe0154b7781bb91a0725c07e/app/views/layouts/design_system.html.erb#L26C54-L26C63)
- search component - removed in https://github.com/alphagov/govuk_publishing_components/pull/4687
Removing the imports could break in applications that are not aware that by importing layout-header, search and skip-link are rendered correctly without importing the required stylesheets separately.
From using the component auditing tools, this will not impact the publishing apps below as they use …

Remove unused imports in layout-header.scss

---

CHANGELOG.md
app/views/govuk_publishing_components/components/feedback/_problem_form.html.erb
app/views/govuk_publishing_components/components/feedback/_survey_signup_form.html.erb

Remove the `aria-expanded` attribute from the feedback component "Cancel" buttons as per the recommendation and subsequent testing by our accessibility specialist.
This change does not result any visual changes.
DAC have reported an issue where the two "Cancel" buttons on the feedback component aren't using `aria-expanded` as expected. The buttons do collapse the region, but behave more like a 'Close' button than an expandable control. 
We also sought feedback from our content designer on whether the button text needs changing to help screen reader users to understand the button's purpose but a decision was made to keep the current button text which was already revised some time ago; the user has clicked on a button to start an action so 'cancel' fits with that action to  'cancel' the …

Remove aria-expanded from feedback component Cancel buttons 

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/govspeak/_footnotes.scss
app/views/govuk_publishing_components/components/docs/govspeak.yml

Make the chosen footnote visually different from the others.
- add styling using the [target](https://developer.mozilla.org/en-US/docs/Web/CSS/:target) pseudo class to govspeak footnotes, so that the currently selected footnote is visually distinct from any others
- this should distinguish the chosen footnote particularly in situations where it is not at the top of the scrolled viewport
- considered using the govuk-frontend focussed state for this but can't because footnotes may contain links already, so could result in a focus state within a focus state
I've also slightly expanded the govspeak footnote documentation just to make it clearer.
Preview app link: https://components-gem-pr-4992.herokuapp.com/component-guide/govspeak/footnotes
Example of a page with footnotes for testing: …

Style govspeak footnote targets

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Style govspeak footnote targets ([PR #4992](https://github.com/alphagov/govuk_publishing_components/pull/4992))
* Upgrade to version 5.11.1 of govuk-frontend ([PR #4933](https://github.com/alphagov/govuk_publishing_components/pull/4933))

Version 60.1.0

---

spec/javascripts/components/feedback-spec.js

Update feedback component tests:
- Update the fixture HTML to reflect the latest version of the feedback component in use
- Remove redundant tests, the "page is not useful" form no longer contains an input to capture an email address, instead it directly links to a separate survey, tests relating the input field to capture the email address have been removed
Ensure the feedback component tests are accurate, this issue was originally spotted when working on the the [PR to remove aria-expanded attribute from feedback component](https://github.com/alphagov/govuk_publishing_components/pull/4996)
Jira: https://gov-uk.atlassian.net/browse/NAV-2611

Update feedback component tests

---

CHANGELOG.md
app/assets/javascripts/govuk_publishing_components/analytics-ga4/ga4-page-views.js
spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-page-views.spec.js

- Remove date PII (Personally Identifiable Information) redaction from page titles in our GA4 page view tracking
- This was needed when a smart answer included PII in the page title, but it no longer does this so the stripping of dates can be removed here.
- Trello card: https://trello.com/c/PJdyFZGF
None.

Remove date PII from GA4 page view tracking

---

CHANGELOG.md
app/assets/javascripts/govuk_publishing_components/components/feedback.js
app/views/govuk_publishing_components/components/feedback/_yes_no_banner.html.erb
spec/javascripts/components/feedback-spec.js

- Remove the `aria-expanded` attribute from the yes/no buttons in the feedback component view template and JavaScript file
- Updated the tests for the feedback component
- Update the fixture to reflect the latest version of the feedback component HTML
- Remove tests relating to `aria-expanded` on the yes/no buttons as this attribute was removed from the HTML
DAC have reported an issue where the two "Cancel" buttons on the feedback component aren't using aria-expanded as expected. The buttons do collapse the region, but behave more like a 'Close' button than an expandable control.
This change ensures the aria-expanded attribute is not set in the view template or via JavaScript for the feedback component.
- Jira: https://gov-uk.atlassian.net/browse/NAV-2611
- Relates to …

(NAV-2611) Remove `aria-expanded` attribute from feedback component

---

CHANGELOG.md
app/assets/javascripts/govuk_publishing_components/analytics-ga4/ga4-page-views.js
lib/govuk_publishing_components/presenters/meta_tags.rb
spec/components/meta_tags_spec.rb
spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-page-views.spec.js

- Some pages on GOV.UK have a `<link rel="canonical` tag which contains the canonical url of the page. We grab this value for GA4 tracking purposes.
- The pages that have the canonical url are ones that render the `machine_readable_metadata` component.
- Not all pages are rendering this component though, so we need an alternative way to get the canonical URL.
- Looking at the code, the canonical_url is usually a combination of the domain name and the base_path.:
https://github.com/alphagov/govuk_publishing_components/blob/63cfc71c53293949b584963556a5f21e598d9b68/lib/govuk_publishing_components/presenters/machine_readable/page.rb#L14-L16
- This only seems to be overruled in [one case by travel advice](https://github.com/search?q=org%3Aalphagov+govuk_publishing_components%2Fcomponents%2Fmach …

Add fallback for missing GA4 canonical URL

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Upgrade to LUX 4.2.1 ([PR #5007](https://github.com/alphagov/govuk_publishing_components/pull/5007))
* Address string literal deprecation ([PR #4999](https://github.com/alphagov/govuk_publishing_components/pull/4999))
* Remove focusable attribute from the close icon on the super nav search menu ([PR #5005](https://github.com/alphagov/govuk_publishing_components/pull/5005))
* Remove date PII from GA4 page view tracking ([PR #5004](https://github.com/alphagov/govuk_publishing_components/pull/5004))
* Introduce erb_lint linter ([PR #5003](https://github.com/alphagov/govuk_publishing_components/pull/5003))
* Remove aria-expanded attribute from feedback component ([PR #4996](https://github.com/alphagov/govuk_publishing_components/pull/4996))
* Add fallback for missing GA4 canonical URL ([PR …

Version 60.2.0

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/_layout-for-public.scss
app/views/govuk_publishing_components/components/_layout_for_public.html.erb
app/views/govuk_publishing_components/components/docs/layout_for_public.yml
lib/govuk_publishing_components/presenters/public_layout_helper.rb
spec/components/layout_for_public_spec.rb

Remove the `blue_bar` option from `layout_for_public` view template
The `blue_bar` option was used prior to the brand update to display a 10px blue border at the bottom of the super navigation menu across GOV.UK
This option can safely be removed as the `blue_bar` option no longer exists
Jira: https://gov-uk.atlassian.net/browse/NAV-18190
The visual changes shown are expected following the removal of the `blue_bar_background` option

Remove the `blue_bar` option from `layout_for_public` template

---

CHANGELOG.md
app/assets/javascripts/govuk_publishing_components/vendor/lux/lux-reporter.js

Update to latest version of LUX, according to https://github.com/alphagov/govuk_publishing_components/blob/main/docs/real-user-metrics.md#getting-the-new-code
Slightly oddly this update seems to undo a lot of the changes from the [previous version](https://github.com/alphagov/govuk_publishing_components/pull/5007), namely that most instances of `var` were replaced with `const` or `let` - they've now been changed back to `var`, oddly.
While I was writing this PR to update to 4.3.0, 4.3.2 was released, so have included that as a separate commit to show the differences.
None.

Upgrade to LUX version 4.3.2

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/_govspeak.scss
app/assets/stylesheets/govuk_publishing_components/components/govspeak/_content-block.scss
app/views/govuk_publishing_components/components/docs/govspeak.yml

This adds some rudimentary styling to to the Govspeak component for the Contact Content Block generated via the Content Block Manager. We originally intended for these styles to be delivered via the [content_block_tools gem](https://github.com/alphagov/content_block_tools).
However, this resulted in a more weighty CSS output and also meant we had to pull in a dependency on `govuk-frontend` in another place, which meant there was a risk of dependencies getting out of whack (see
https://github.com/alphagov/frontend/pull/4943).
After some discussion with @maxgds and @richardTowers, we decided that the least worse option would be to distribute these styles in the Components gem. This is a minor misuse of tools, as content blocks are not _strictly_ a component, but this is already repeating a …

Add content block styles

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* **BREAKING:** Remove unneeded Sass mixins ([PR #4969](https://github.com/alphagov/govuk_publishing_components/pull/4969))
* Upgrade to LUX version 4.3.2 ([PR #5018](https://github.com/alphagov/govuk_publishing_components/pull/5018))
* Add content block styles ([PR #4973](https://github.com/alphagov/govuk_publishing_components/pull/4973))
* Restructure HTML and use flexbox in super navigation component ([PR #4997](https://github.com/alphagov/govuk_publishing_components/pull/4997))

Version 61.0.0

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/govuk_frontend_support.scss
app/views/govuk_publishing_components/components/_service_navigation.html.erb
app/views/govuk_publishing_components/components/docs/service_navigation.yml
spec/components/service_navigation_spec.rb

https://gov-uk.atlassian.net/browse/NAV-18205
GOV.UK Frontend v5.11.0 and v5.11.1 updates
- The Service navigation component no longer uses a menu on mobile for a single link
- Add inverse styling to Service navigation
- Reapply colour mixins instead of hex values (used for the brand refresh)
**Review URL**: https://components-gem-pr-5023.herokuapp.com/component-guide/service_navigation
Although GOV.UK Publishing Components was previously updated to versions GOV.UK Frontend 5.11.0 - 5.11.2, not all fixes and improvements from those releases were applied. This pull request ensures that the remaining updates are now implemented.
If testing from the 'preview all' page in the component guide, only the first service navigation menu toggle responds. This happens because each toggle is tied to a …

GOV.UK Frontend v5.11.0 and v5.11.1 updates

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/_heading.scss

- govuk-heading class inside the heading component in some circumstances overrode the heading component, giving the heading inside a bottom margin
- heading inside the component should always have a margin bottom of zero, allowing the wrapping element to set the margin, controlled by the component
Recently noticed on https://www.gov.uk/cma-cases/veterinary-services-market-for-pets-review
Before | After
------ | -----

Fix heading component margin

---

app/assets/stylesheets/govuk_publishing_components/components/_single-page-notification-button.scss
app/views/govuk_publishing_components/components/_single_page_notification_button.html.erb

- text inside the button was rendering black and not blue as intended in some circumstances
- this was because the wrapping element has a class of govuk-body-s, which sets the black font colour
- if govuk-frontend styles are loaded first, button text is blue, if they load second, button text is black
- fixing by removing the govuk-body-s class and replacing with specific govuk-font setting on the text element itself
Noticed on https://www.gov.uk/government/publications/budget-2016-documents during testing of an unrelated issue.
Note that 'before' only happens if the styles are loaded in an unexpected order. However this is a brittleness in our Sass, and should be corrected even if the styles are loaded as expected.
Before | After
------ | -----

Fix specificity issue with single page notification button

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Fix incorrect colour on summary banner heading ([PR #5030](https://github.com/alphagov/govuk_publishing_components/pull/5030))
* Update search button spacing in super navigation menu on tablet devices ([PR #5028](https://github.com/alphagov/govuk_publishing_components/pull/5028))

Version 61.0.2

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/_print-link.scss
app/views/govuk_publishing_components/components/_print_link.html.erb

- govuk-body-s was overriding the colour on the print link button text, despite it being overridden by the components own styles
- this is due to a change in govspeak, which will be addressed separately, but this change makes the component less brittle by not relying on govuk-body-s anymore
Spotted by @AshGDS as being the wrong colour on this page: https://www.gov.uk/guidance/download-the-govuk-app
Note that this only occurs where the print link component appears on a page with the govspeak component.
Before | After
Relates to https://github.com/alphagov/govuk_publishing_components/issues/5035

Fix print link button styles

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/govspeak/_content-block.scss

Stop importing the GOVUK Frontend typography styles in the govspeak styles.
This was causing this issue: https://github.com/alphagov/govuk_publishing_components/issues/5035
There's a very small change in the spacing between list items, because they are no longer based on the GOVUK Frontend list classes. I've left them like this because they are now consistent with the rest of govspeak, which means we can iterate them more easily in one place further down the road if we want.
Before | After
(it's a very small change, easier to see full size if you want to compare it with https://components.publishing.service.gov.uk/component-guide/govspeak/contact_content_block/preview)

Fix govspeak styles

---

CHANGELOG.md
app/assets/stylesheets/govuk_publishing_components/components/_action-link.scss
app/views/govuk_publishing_components/components/_action_link.html.erb
app/views/govuk_publishing_components/components/docs/action_link.yml
spec/components/action_link_spec.rb

Change the vertical alignment of the action link arrow to be in the middle, not the top.
- arrow previously aligned to the top (default) whereas text is vertically aligned to the middle
- not noticeable most of the time but on the homepage, where several action links with differing text are next to each other, and an override is in place to make this change
- still not noticeable unless text size is increased (can do zoom text only in Firefox)
- therefore moving this positioning change to the component itself as the default, as it seems like a sensible option
- action link only used on homepage, browse pages, coronavirus page
Also add a new option `large` for display on the homepage, and refactoring the stylesheet a bit following these changes.
Noticed during the work on …

Adjust action link arrow

---

CHANGELOG.md
app/assets/javascripts/govuk_publishing_components/analytics-ga4/ga4-form-tracker.js
spec/javascripts/govuk_publishing_components/analytics-ga4/ga4-form-tracker.spec.js

- `Ga4FormTracker` conditional field adjustments
- `Ga4FormTracker` improve date component handling
- `Ga4FormTracker` report single selected option
- `Ga4FormTracker` stop including placeholders
The fields within a conditional checkbox were always being included even if the checkbox was not checked. This was because the query for the conditional checkbox input was being executed from the wrong node. Moving the query to `this.module` has fixed this. This was not identified before as the markup within the tests was not accurate to how conditional checkboxes are rendered. In addition, the structure of conditional fields within the JSON assigned to `text` (if JSON recording enabled) has been flattened.
Improve how dates are represented within `text`. Given a form with a date component of …

Adjustments to how `Ga4FormTracker` sets `text` on `submit`

---

CHANGELOG.md
Gemfile.lock
lib/govuk_publishing_components/version.rb

* Adjustments to how Ga4FormTracker sets text on submit ([PR #4994](https://github.com/alphagov/govuk_publishing_components/pull/4994))

Version 61.1.1
